<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">
<head>
<?php 
print css::build_tag(DEDALO_LIB_BASE_URL.'/diffusion/'.get_class($this).'/css/'.get_class($this).'.css');
print js::build_tag(DEDALO_LIB_BASE_URL . '/diffusion/'.get_class($this).'/js/'.get_class($this).'.js');
?>
</head>

<body>
<?php
$content = '';

# CONTAINER DIV
$content .= "<div class=\"diffusion_mupreva_ficha_fm_container\" >";

	#
	# IMAGEN IDENTIFICATIVA
		$imagen_identificativa_html='';
		$current_diffusion_obj = $imagen_identificativa_diffusion_obj;
			#dump($current_diffusion_obj,'current_diffusion_obj');

		# VARS
		$label 	= $current_diffusion_obj->label;
		$valor 	= $current_diffusion_obj->columns['valor'];
			#dump($valor,'$valor');

		# FORMATO DEL ARRAY RECIBIDO
		# [valor] => Array
	    #    (
	    #        [247224] => Array
	    #            (
	    #                [dd750] => dd750-2454
	    #                [dd1110] => /2
	    #                [dd851] => 28061-1
	    #            )
	    #    )
		foreach ($valor as $section_id => $ar_components_data) {

			$SID='';
			if (empty($ar_components_data[$this->campo_imagen_path]) && empty($ar_components_data[$this->campo_imagen_nombre])) {
				$SID .= $ar_components_data[$this->campo_imagen_default_nombre];
			}else{
				# Path
				if( !empty($ar_components_data[$this->campo_imagen_path]) ) {
					$SID .= $ar_components_data[$this->campo_imagen_path];
				}
				# File name
				if( !empty($ar_components_data[$this->campo_imagen_nombre]) ) {
					if(!empty($ar_components_data[$this->campo_imagen_path])) $SID .= '/';
					$SID .= $ar_components_data[$this->campo_imagen_nombre];
				}
			}
				
			# IMG
			$image_full_url = $this->get_url_full( $SID );		
			$img_url 		= DEDALO_IMAGE_FILE_URL . "?m=image&SID=$SID&w=320&h=320&fx=";
			$imagen_identificativa_html .= "\n <div class=\"img_identificativa\">";
			$imagen_identificativa_html .= "\n <a href=\"$image_full_url\" target=\"_blank\">";
			$imagen_identificativa_html .= "\n  <img src=\"$img_url\" class=\"img_identificativa_\" />";
			$imagen_identificativa_html .= "\n </a>";
			$imagen_identificativa_html .= "\n </div>";
				#dump($img_url,'img_url');

		}#end foreach ($valor as $section_id => $ar_components_data)

		$content .= $imagen_identificativa_html;

	
	#
	# OTRAS IMAGENES
		$otras_imagenes_html='';
		$current_diffusion_obj = $ar_otras_imagenes_diffusion_obj;
			#dump($current_diffusion_obj,'current_diffusion_obj');

		# VARS
		$label 	= $current_diffusion_obj->label;
		$valor 	= $current_diffusion_obj->columns['valor'];
			#dump($valor,'$valor');

		# FORMATO DEL ARRAY RECIBIDO
		# [valor] => Array
	    #    (
	    #        [247224] => Array
	    #            (
	    #                [dd750] => dd750-2454
	    #                [dd1110] => /2
	    #                [dd851] => 28061-1
	    #            )
	    #    )
		foreach ($valor as $section_id => $ar_components_data) {

			$SID='';
			if (empty($ar_components_data[$this->campo_imagen_path]) && empty($ar_components_data[$this->campo_imagen_nombre])) {
				$SID .= $ar_components_data[$this->campo_imagen_default_nombre];
			}else{
				# Path
				if( !empty($ar_components_data[$this->campo_imagen_path]) ) {
					$SID .= $ar_components_data[$this->campo_imagen_path];
				}
				# File name
				if( !empty($ar_components_data[$this->campo_imagen_nombre]) ) {
					if(!empty($ar_components_data[$this->campo_imagen_path])) $SID .= '/';
					$SID .= $ar_components_data[$this->campo_imagen_nombre];
				}
			}	
				
			# IMG
			$image_full_url = $this->get_url_full( $SID );
			$img_url 		= DEDALO_IMAGE_FILE_URL . "?m=image&SID=$SID&w=165&h=165&fx=";
			$otras_imagenes_html .= "\n <div class=\"img_otras\">";
			$otras_imagenes_html .= "\n <a href=\"$image_full_url\" target=\"_blank\">";
			$otras_imagenes_html .= "\n  <img src=\"$img_url\" class=\"img_otras_\" />";
			$otras_imagenes_html .= "\n </a>";
			$otras_imagenes_html .= "\n </div>";
				#dump($img_url,'img_url');

		}#end foreach ($valor as $section_id => $ar_components_data)

		$content .= $otras_imagenes_html;

	/*
	# OTRAS IMÁGENES
	foreach ($ar_fotos as $key => $value) {
		# DIV WRAP FOTO
		$content .= "<div class=\"diffusion_mupreva_ficha_fm\" >";
		
			# IMG
			$img_url 	= DEDALO_IMAGE_FILE_URL . "?m=image&SID=$current_valor&w=102&h=57&fx=crop"; 
			$html_head .= "<img src=\"$img_url\" class=\"img_identificativa\" />";
			$content .= "<image src=\"$url\" />";

		$content .= "</div>";#end diffusion_mupreva_ficha_fm
	}
	*/


$content .= "\n</div>";#end diffusion_mupreva_ficha_fm_container

print $content;
?>

</body>
</html>