<?php

	# VISUALIZADOR HTML	
	
	print "\n<!-- CHECK BOX [tipo:$tipo section_id_matrix:$parent] $label -->";

	print "\n<div class=\"wrap_component css_wrap_check_box wrap_component_{$tipo}\"
	id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-lang=\"{$lang}\"
	data-modo=\"{$modo}\"
	data-dato='$dato_string'
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	$required_code 	= NULL;
	#if($required)
	#	$required_code = 'style="font-weight:bold"';
	
	# CONTENIDO (INPUT)
	$html_contenido  = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= ""; 
					break;
						
		case 1	: 	$html_contenido .= $valor;
					break;	

						
		case ($permissions>=2) :					
		
					$html_contenido .= "<ul class=\"group\">";
					$i=1; foreach ($ar_list_of_values->result as $value => $rotulo) {

						$value   = (string)$value; 
						$locator = (object)json_handler::decode($value);	# Locator is json encoded object
						#dump($locator," locator"); #dump($dato," dato");
						
						$checked  = in_array($locator, $dato) ? 'checked="checked"' : '';
						$tabindex = $i==1 ? 'tabindex="1"' : '';
						
						$html_contenido .= "<li>";

						# 
						# INPUT
						$html_contenido .= "\n <input type=\"checkbox\" class=\"css_check_box\"
						onfocus=\"component_common.select_wrap(null,'$id_wrapper');\"
						onchange=\"component_check_box.Save(this)\"
						name=\"{$input_name}\"
						data-tipo=\"{$tipo}\"
						data-lang=\"{$lang}\"
						data-section_tipo=\"{$section_tipo}\"
						data-parent=\"{$parent}\"
						value='$value'
						title=\"$html_title\"
						$checked
						$tabindex
						/>";	#id=\"{$identificador_unico}\" 
						
						#
						# LABEL				
						$html_contenido .= " <label class=\"css_check_box_rotulo\" $required_code >$rotulo</label>";

						$html_contenido .= "</li>";
						$i++;
					}
					$html_contenido .= "</ul>";
							
	}


	# Prepare content to show in page
	tools::prepare_content($html_contenido);



	
	# PRINT HTML
	print $html_label;
	print $html_contenido;

	
	if(SHOW_DEBUG && isset($ar_list_of_values->debug)) {
		echo $ar_list_of_values->debug;
	}
	
	
	print "\n</div><!-- /css_wrap_check_box CHECK BOX [tipo:$tipo section_id_matrix:$tipo] $label -->\n\n"; //wrap


?>