<?php

	# VISUALIZADOR HTML	
	
	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in', $modo, $lang);

	print "<div class=\"wrap_component css_wrap_check_box wrap_component_{$tipo}\" ";
	print "id=\"{$id_wrapper}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-modo=\"{$modo}\" ";
	print 'data-dato="'.$dato_string.'" ';
	print "data-component_name=\"{$component_name}\" ";
	print "data-component_info='{$component_info}' ";
	print ">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	$required_code 	= NULL;
	#if($required)
	#	$required_code = 'style="font-weight:bold"';
	
	# CONTENIDO (INPUT)
	$html_content  = '';
	switch($permissions) {
			
		case 0	:	
			$html_content .= ""; 
			break;
		
		case 1	:
			$html_content .= $valor;
			break;
						
		case 2 :
		case 3 :					
		
			$html_content .= "<ul class=\"group\">";
			$i=1; foreach ($ar_list_of_values->result as $key => $item) {
				
				$label   = (string)$item->label;

				$locator = new stdClass();
					$locator->section_tipo 			= $item->value->section_tipo;
					$locator->section_id 			= $item->value->section_id;
					$locator->type 					= DEDALO_RELATION_TYPE_LINK;
					$locator->from_component_tipo 	= $tipo;

				$locator_json = json_encode($locator);
				
				$checked  = '';
				if (is_array($dato) && locator::in_array_locator($locator, $dato, array('section_id','section_tipo')) ) {
					$checked  = 'checked="checked"';
				}

				$tabindex = $i==1 ? 'tabindex="1"' : '';

				$current_id = $input_name.'_'.$i;
				
				$html_content .= "<li>";

				# 
				# INPUT
				$html_content .= "<input type=\"checkbox\" class=\"css_check_box\" ";
				$html_content .= "onfocus=\"component_common.select_wrap(null,'$id_wrapper');\" ";
				$html_content .= "onchange=\"component_check_box.Save(this)\" ";
				$html_content .= "name=\"{$input_name}\" ";
				$html_content .= "id=\"{$current_id}\" ";
				$html_content .= "data-tipo=\"{$tipo}\" ";
				$html_content .= "data-lang=\"{$lang}\" ";
				$html_content .= "data-section_tipo=\"{$section_tipo}\" ";
				$html_content .= "data-parent=\"{$parent}\" ";
				$html_content .= 'value=\''.$locator_json.'\' ';
				$html_content .= "title=\"$html_title\" ";
				$html_content .= "$checked ";
				$html_content .= "$tabindex ";
				$html_content .= "/>";
				
				#
				# LABEL				
				$html_content .= "<label for=\"$current_id\" class=\"css_check_box_rotulo\" {$required_code}>$label</label>";

				$html_content .= "</li>";
				$i++;
			}
			$html_content .= "</ul>";

			#
			# JS Init component
			$html_content .= '<script>';
			# Init component
			$init_options = new stdClass();
				$init_options->component_name 	= $component_name;
				$init_options->wrapper_id 		= $id_wrapper;
			$html_content .= 'component_common.init('.json_encode($init_options).');';
			$html_content .= '</script>';
			break;
	}


	# Prepare content to show in page
	tools::prepare_content($html_content);


	
	# PRINT HTML
	print $html_label;
	print $html_content;

	
	#if(SHOW_DEBUG && isset($ar_list_of_values->debug)) {
	#	echo $ar_list_of_values->debug;
	#}
	
	
	print "</div>"; //wrap


	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in', $modo, $lang);


?>