<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 				$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_check_box'])) 				$ar_css['css_check_box']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 			$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))			$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_check_box']))			$ar_css['css_wrap_check_box']='';
	if(!isset ($ar_css['css_check_box_rotulo']))		$ar_css['css_check_box_rotulo']='';
	
	if(!isset ($tools_html))							$tools_html='';
	
	
	print "\n<!-- CHECK BOX [tipo:$tipo section_id_matrix:$parent] $label -->";
	print "\n<div class=\"css_wrap_check_box wrap_component {$ar_css['css_check_box_rotulo']}\"
	id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-lang=\"{$lang}\"
	data-modo=\"{$modo}\"
	data-dato='$dato_string'
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}' >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	$required_code 	= NULL;
	#if($required)
	#	$required_code = 'style="font-weight:bold"';
	
	# CONTENIDO (INPUT)
	$html_contenido  = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= ""; 
					break;
						
		case 1	: 	$html_contenido .= $valor;
					break;	

						
		case ($permissions>=2) :					
		
					foreach ($ar_list_of_values->result as $value => $rotulo) {

						$value   = (string)$value; 
						$locator = (object)json_handler::decode($value);	# Locator is json encoded object
						#dump($locator," locator"); #dump($dato," dato");

						if (in_array($locator, $dato)) {	# dato is array always
							$checked = 'checked="checked"';
						}else{
							$checked = "";
						}
						/* OLD
						if( is_array($dato) && in_array($value, array_keys($dato)) ) {
							$checked = 'checked="checked"';
						}else {
							$checked = "";
						}
						*/
						$html_contenido .= "\n <input class=\"css_check_box {$ar_css['css_check_box']}\" type=\"checkbox\" 
						name=\"{$input_name}\"
						data-tipo=\"{$tipo}\"
						data-lang=\"{$lang}\"
						data-section_tipo=\"{$section_tipo}\"
						data-parent=\"{$parent}\"
						value='$value' 
						title=\"$html_title\" $checked />";	#id=\"{$identificador_unico}\" 
												
						$html_contenido .= "\n <label class=\"css_check_box_rotulo {$ar_css['css_check_box_rotulo']}\" $required_code >$rotulo</label>";
						$html_contenido .= "\n <br>";	
					}							
							
	}


	# Prepare content to show in page
	tools::prepare_content($html_contenido);



	
	# PRINT HTML
	print $html_label;
	print $html_contenido;

	
	if(SHOW_DEBUG && isset($ar_list_of_values->debug)) {
		echo $ar_list_of_values->debug;
	}
	
	
	print "\n</div><!-- /css_wrap_check_box CHECK BOX [tipo:$tipo section_id_matrix:$tipo] $label -->\n\n"; //wrap


?>