<?php

	# VISUALIZADOR HTML	
	
	print "<div class=\"wrap_component css_wrap_check_box wrap_check_box_search tooltip_active\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato='".json_encode($dato)."' ";
	print 'data-q_operator="'.$q_operator.'" ';
	print 'title="'.search_development2::search_options_title( $this->search_operators_info() ).'" ';
	print ">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	# CAMPO OBLIGATORIO
	$required_code 	= NULL;
	#if($required)	$required_code = 'style="font-weight:bold"';
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch(true) {
			
		case $permissions===0	:
			$html_content .= ""; 
			break;
						
		case ($permissions>=1)	:
					
			# COMPARISON OPERATORS
			#$html_content .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);
			$html_content .= '<input class="q_operator" type="text" value="'.$q_operator.'" ';
			$html_content .= "onchange=\"component_common.fix_dato(this,'{$component_name}')\" ";
			$html_content .=' />';

			$i=0;foreach ($ar_list_of_values->result as $key => $item) {
				
				$label   = (string)$item->label;
				$locator = (object)$item->value;

				# Add from_component_tipo
				$locator->from_component_tipo = $tipo;

				$locator_json = json_encode($locator);
				
				$checked  = '';
				if (is_array($dato) && locator::in_array_locator($locator, $dato, array('section_id','section_tipo')) ) {
					$checked  = 'checked="checked"';
				}

				$current_id = $tipo .'_'. $i;

				$html_content .= "<span class=\"check_box_item\">";
				$html_content .= "<input class=\"css_check_box\" type=\"checkbox\" name=\"{$search_input_name}_array\" ";
				$html_content .= "id=\"{$current_id}\" ";
				$html_content .= "data-tipo=\"{$tipo}\" ";
				$html_content .= 'value=\''.$locator_json.'\' ';
				$html_content .= "title=\"$html_title\" ";
				$html_content .= "onchange=\"component_common.fix_dato(this,'{$component_name}')\" ";
				$html_content .= $checked;
				$html_content .= "/>";						
				$html_content .= "<label class=\"css_check_box_rotulo\" for=\"{$current_id}\" ";
				$html_content .= $required_code;
				$html_content .= ">";
				$html_content .= $label;
				$html_content .= "</label> ";
				$html_content .= "</span>";	
			$i++;}
			
			# LOGICAL OPERATORS
			#$html_content .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);

			if(SHOW_DEBUG===true) {
				$html_content .= "<span class=\"debug_info\">$search_input_name</span>";
			}


			#
			# JS Init component
			$html_content .= '<script>';
			# Init component
			$init_options = new stdClass();
				$init_options->component_name 	= $component_name;
				$init_options->wrapper_id 		= $id_wrapper;
			$html_content .= 'component_common.init('.json_encode($init_options).');';
			$html_content .= '</script>';		
			
			break;							
	}

	# Prepare content to show in page
	tools::prepare_content($html_content);	
	
	# PRINT HTML
	print $html_label;
	print $html_content;
	
	
	print "</div>"; //wrap
?>