<?php

	# VISUALIZADOR HTML	
	
	
	print "\n<!-- CHECK BOX [tipo:$tipo section_id_matrix:$parent] $label -->";

	print "\n<div class=\"css_wrap_check_box\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= ""; 
					break;
						
		case 1	: 	foreach ($ar_list_of_values->result as $value => $rotulo) {
						
						if( is_array($dato) && in_array($value, array_keys($dato)) ) {
							$checked = 'checked="checked"';
						}else {
							$checked = "";
						}
						$html_contenido .= "\n <input class=\"css_check_box\" type=\"checkbox\" name=\"{$tipo}\" data-tipo=\"{$tipo}\" value=\"{$value}\" data-section_tipo=\"{$section_tipo}\" parent=\"{$parent}\" title=\"$html_title\" $checked  disabled />";						
						$html_contenido .= "\n <label class=\"css_check_box_rotulo\" $required >$rotulo</label>";	
					}
					break;	
						
		case ($permissions>=2)	:
		
					foreach ($ar_list_of_values->result as $value => $rotulo) {
						
						if( is_array($dato) && in_array($value, array_keys($dato)) ) {
							$checked = 'checked="checked"';
						}else {
							$checked = "";
						}
						$html_contenido .= "\n <input class=\"css_check_box\" type=\"checkbox\" 
						name=\"{$tipo}_{$parent}\" 
						data-tipo=\"{$tipo}\" data-section_tipo=\"{$section_tipo}\" data-parent=\"{$parent}\" data-lang=\"{$lang}\"
						value=\"{$value}\" title=\"$html_title\" $checked />";						
						$html_contenido .= "\n <label class=\"css_check_box_rotulo\" $required >$rotulo</label>";	
					}					
					break;
							
	}
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div>\n\n"; //wrap
?>