<?php

	# VISUALIZADOR HTML	
	
	
	if(isset($_REQUEST[$tipo])) $dato = $_REQUEST[$tipo];		#var_dump($_REQUEST[$tipo]);
	
	
	#print "\n<!-- CHECK BOX [tipo:$tipo section_id_matrix:$parent] $label -->";

	print "\n<div class=\"wrap_component css_wrap_check_box\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	# CAMPO OBLIGATORIO
	$required_code 	= NULL;
	#if($required)	$required_code = 'style="font-weight:bold"';
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= ""; 
					break;
						
		case ($permissions>=1)	:
					
					# COMPARISON OPERATORS
					$html_contenido .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);

		
					foreach ($ar_list_of_values->result as $value => $rotulo) {
						
						$checked = (is_array($dato) && in_array($value, array_keys($dato))) ? 'checked="checked"' : '';

						$html_contenido .= "\n <input class=\"css_check_box\" type=\"checkbox\" name=\"{$tipo}[]\" 
						data-tipo=\"{$tipo}\"
						value=\"{$value}\"
						title=\"$html_title\" $checked />";						
						$html_contenido .= "\n <label class=\"css_check_box_rotulo\"
						$required_code >$rotulo</label> ";	
					}
					
					# LOGICAL OPERATORS
					$html_contenido .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);				
					
					break;				
							
	}
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div>\n\n"; //wrap
?>