<?php

	# VISUALIZADOR HTML	

	print "<div class=\"wrap_component css_wrap_input_text\" id=\"wrap_{$tipo}\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch(true) {			
		case ($permissions===0)	:
					$html_content .= "";
					break;
						
		case ($permissions===1):
					$html_content .= "<span class=\"css_span_dato\">$dato</span>";
					break;	
						
		case ($permissions>=2)	:
					# COMPARISON OPERATORS
					$html_content .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);
		
					$html_content .= "<input class=\"css_input_text_large_search\" type=\"text\" name=\"{$search_input_name}\" ";
					$html_content .= "id=\"{$identificador_unico}\" ";
					$html_content .= "data-tipo=\"{$tipo}\" ";
					$html_content .= "data-lang=\"{$lang}\" ";
					$html_content .= "value=\"\" ";
					$html_content .= "title=\"$html_title\" />";

					# LOGICAL OPERATORS
					$html_content .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);
					break;
	}

	# Prepare content to show in page
	tools::prepare_content($html_content);	
	
	
	# PRINT HTML
	print $html_label;
	print $html_content;
	
	
	print "</div>"; //wrap
?>