<?php

	# VISUALIZADOR HTML
	
	
	print "\n<!-- INPUT_TEXT_LARGE [tipo:$tipo section_id_matrix:$parent] $label -->";

	print "\n<div class=\"wrap_component css_wrap_input_text_large wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-modo=\"{$modo}\"
	data-dato=\"{$dato}\"
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";
	
		
		# ETIQUETA (LABEL)
		$html_label = component_common_draw::draw_label($this);
		
		# CONTENIDO (INPUT)
		$html_contenido = '';
		switch($permissions) {
				
			case 0	:	
				$html_contenido .= "";
				break;
							
			case 1	: 	
				$html_contenido .= "\n <span class=\"css_span_dato\">$dato</span>";
				break;	
							
			case ($permissions>=2)	:
			
				# Dato reference default lang
				if ($modo!='tool_lang') {
				$html_contenido .= "\n <div class=\"dato_refecence_default_lang\">$dato_reference_lang</div>";
				}
				

				$html_contenido .= "\n <textarea class=\"css_input_text_large $aditional_css\" name=\"{$input_name}\"
				onchange=\"component_input_text_large.Save(this)\"
				id=\"$identificador_unico\"
				data-tipo=\"{$tipo}\"
				data-parent=\"{$parent}\"
				data-section_tipo=\"{$section_tipo}\"
				data-lang=\"{$lang}\"
				title=\"$html_title\" style=\"overflow: visible\">$dato</textarea>";				
				
				#$html_contenido .= "\n <span  class=\"css_span_log\"></span>";
				#$html_contenido .= "\n <span  class=\"css_span_ejemplo \">$ejemplo</span>";
						
				if(SHOW_DEBUG) {
					#$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";
				}
				break;
							
												
		}

		# Prepare content to show in page
		tools::prepare_content($html_contenido);
		

		# PRINT HTML
		print $html_label;
		print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_input_text_large INPUT_TEXT_large [tipo:$tipo section_id_matrix:$parent] $label -->\n"; //wrap


?>