<?php

	# VISUALIZADOR HTML	

	print "<div class=\"wrap_component css_wrap_input_text tooltip_active\" id=\"wrap_{$tipo} tooltip_active\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato='".json_encode($dato)."' ";
	print 'title="'.search_development2::search_options_title( $this->search_operators_info() ).'" ';
	print ">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch(true) {			
		case ($permissions===0)	:
					$html_content .= "";
					break;
						
		case ($permissions===1):
					$html_content .= "<span class=\"css_span_dato\">$dato</span>";
					break;	
						
		case ($permissions>=2)	:
					# COMPARISON OPERATORS
					#$html_content .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);
		
					$html_content .= "<textarea class=\"css_input_text_large_search\" type=\"text\" name=\"{$search_input_name}\" ";
					$html_content .= "id=\"{$identificador_unico}\" ";
					$html_content .= "data-tipo=\"{$tipo}\" ";
					$html_content .= "data-lang=\"{$lang}\" ";
					$html_content .= "onchange=\"component_common.fix_dato(this,'{$component_name}')\" ";
					$html_content .= "title=\"$html_title\" >";
					$html_content .= $dato;
					$html_content .= "</textarea>";

					# LOGICAL OPERATORS
					#$html_content .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);
					break;
	}

	# Prepare content to show in page
	tools::prepare_content($html_content);	
	
	
	# PRINT HTML
	print $html_label;
	print $html_content;
	
	
	print "</div>"; //wrap
?>