<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 				$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_input_text_large'])) 		$ar_css['css_input_text_large']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 			$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))			$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_input_text_large']))	$ar_css['css_wrap_input_text_large']='';
	
	if(!isset ($html_tools))							$html_tools='';
	
	
	print "\n<!-- INPUT_TEXT_LARGE [tipo:$tipo id_matrix:$id] $label -->";
	print "\n<div class=\"css_wrap_input_text_large wrap_component {$ar_css['css_wrap_input_text_large']}\" id=\"{$id_wrapper}\"
	data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-parent=\"{$parent}\" data-modo=\"{$modo}\" data-dato=\"{$dato}\" data-component_name=\"{$component_name}\" >";
	
		
		# ETIQUETA (LABEL)
		$html_label = component_common_draw::draw_label($this);
		
		# CONTENIDO (INPUT)
		$html_contenido = '';
		switch($permissions) {
				
			case 0	:	
				$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." (input_text_large)</span>";
				break;
							
			case 1	: 	
				$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\">$dato</span>";
				break;	
							
			case ($permissions>=2)	:
			
				# Dato reference default lang
				if ($modo!='tool_lang') {
				$html_contenido .= "\n <div class=\"dato_refecence_default_lang\">$dato_reference_lang</div>";
				}
				

				$html_contenido .= "\n <textarea class=\"css_input_text_large $aditional_css\" name=\"{$input_name}\" id=\"$identificador_unico\" data-tipo=\"{$tipo}\" data-id_matrix=\"{$id}\" data-parent=\"{$parent}\" data-lang=\"{$lang}\" title=\"$html_title\" style=\"overflow: visible\">$dato</textarea>";				
				
				#$html_contenido .= "\n <span  class=\"css_span_log\"></span>";
				#$html_contenido .= "\n <span  class=\"css_span_ejemplo {$ar_css['css_span_ejemplo']}\">$ejemplo</span>";
						
				if($permissions==3)		
						$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$debugger}</span>";	
												
		}

		# Prepare content to show in page
		tools::prepare_content($html_contenido);
		

		# PRINT HTML
		print $html_label;
		print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_input_text_large INPUT_TEXT_large [tipo:$tipo id_matrix:$id] $label -->\n"; //wrap


?>