<?php

	# VISUALIZADOR HTML	
		
	# BUTTON TOOL
	$html_tool    = '';
	
	#$html_tool   .= "<div class=\"tool_inspector_div\">";

	# ICON
	$title	  = label::get_label('abrir').' '.label::get_label('herramienta');
	
	$html_tool .= '<a href="javascript:void(0);" class="id_column_buttons button_catalogue link" title="'.$title.'" onclick="tool_common.open_tool_calatogue(this)" ';
	$html_tool .= 'data-tool_tipo="'.$tool_tipo.'" ';
	$html_tool .= 'data-section_tipo="'.$section_tipo.'" ';
	$html_tool .= 'data-section_id="'.$section_id.'" ';
	$html_tool .= 'data-tab_id="'.$tool_name.'_'.$section_tipo.'_'.$section_id.'" ';
	$html_tool .= '>';
		$html_tool .= "<span class='section_id_number'>";
		$html_tool .= " $section_id ";
		$html_tool .= "</span>";
	$html_tool .= "</a>";	

	#$html_tool   .= "</div>";#/tool_inspector_div

	
	# PRINT HTML
	print $html_tool;
	
?>