<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link href="<?php echo DEDALO_LIB_BASE_URL ?>/page/css/main.css" rel="stylesheet">
	<?php /*<link href="<?php echo DEDALO_LIB_BASE_URL ?>/common/css/structure.css" rel="stylesheet"> */?>
</head>
<body>
	<?php echo $html_header ?>
	<div id="main" class="hide"></div>
	<div id="debug" class="debug hide"></div>
</body>
<script>
var page_globals=<?php echo SHOW_DEBUG===true ? json_encode($page_globals, JSON_PRETTY_PRINT) : json_encode($page_globals) ?>;
</script>
<script defer="defer" src="<?php echo DEDALO_LIB_BASE_URL ?>/common/js/enviroment.js.php"></script>
<script defer="defer" src="<?php echo DEDALO_LIB_BASE_URL ?>/menu/js/menu.js"></script>
<script type="module">
	const t0 = performance.now()

	const main = document.getElementById("main")
		  main.classList.add("loading")

	// page instance
	import {get_instance} from '../common/js/instances.js'
	( async () => {

		// page instance
			const page = await get_instance({
				model 		: 'page',
				mode		: <?php echo json_encode($page_options->mode) ?> || 'edit',
				elements 	: <?php echo json_encode($page_options->page_elements) ?>
			})

		// page instance render
			await page.build()
			const wrapper_page = await page.render()

		// main add and restore class
			main.appendChild(wrapper_page)
	 		main.classList.remove("loading","hide")

		// debug
			if(SHOW_DEBUG===true) {
				console.log("+ Page instantiated and rendered total in time ms: ",performance.now()-t0)
			}
	})()
</script>
</html>
