<?php

	# VISUALIZADOR HTML	
		
	# BUTTON TOOL IN INSPECTOR
	$html_tool    = "\n<!-- TOOL PDF VERSIONS [tipo:$tipo id_matrix:$id] -->";
	$html_tool   .= "<div class=\"tool_inspector_div\">";

	$btn_title	  = label::get_label('abrir').' '.label::get_label('herramienta');
	$html_tool   .= "\n<div class=\"icon_bs tool_pdf_versions_icon link\"
								data-tipo=\"{$tipo}\" data-id_matrix=\"{$id}\" data-parent_matrix=\"{$parent}\"
								title=\"$btn_title\"
								onclick=\"tool_common.open_tool_pdf_versions(this)\"
								> </div>";


	$html_tool   .= label::get_label('tool_pdf_versions');	#" PDF versions";
	

	$html_tool   .= "</div>";#/tool_inspector_div

	# PRINT HTML
	print $html_tool;
	
?>