<?php

	# VISUALIZADOR HTML	

	
	# CONTENIDO
	$html_contenido = '';
	
	switch(true) {
						
		case ($permissions>=2) :

			// Action js
				// Default (when not defined)
				$js_action = 'button_trigger.trigger(this)';
				// Custom (defined in propiedades)
				if ($js_exec_function!==false) {
					$js_action = $js_exec_function .'(this, event)';
				}
	
			# BUTTON
				$html_contenido .= '<div class="css_button_generic css_button_trigger" ';
				$html_contenido .= 'onclick="'.$js_action.'" ';
				$html_contenido .= 'data-parent="'.$this->parent.'" ';
				$html_contenido .= 'data-tipo="'.$tipo.'" ';
				$html_contenido .= 'data-section_tipo="'.$section_tipo.'" ';
				$html_contenido .= 'data-propiedades=\''.$propiedades_json.'\' ';
				$html_contenido .= '>';
				$html_contenido .= $label;
				$html_contenido .= '</div>';


			# RESPONSE
				$html_contenido .= "<div class='button_trigger_response' id=\"button_trigger_$tipo\">";
				$html_contenido .= "";
				$html_contenido .= "</div>";
	}
	
	
	# PRINT HTML
	print $html_contenido;

	
