<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
		
	
	#print "\n\n<!-- BUTTON TRIGGER [tipo:$tipo id_matrix:$id] -->";
	#print "\n<div class=\"css_wrap_button_trigger {$ar_css['css_wrap_button_trigger']}\">";
	
	# CONTENIDO
	$html_contenido = '';
	
	switch($permissions) {
						
		case ($permissions>=2)	:					

				# BUTTON
				$html_contenido .= "\n <div class='css_button_generic css_button_trigger' onclick='button_trigger.trigger(this)' data-parent='$this->parent' data-tipo='$tipo' data-propiedades='$propiedades' >";
				$html_contenido .= $label;
				$html_contenido .= "</div>";


				# RESPONSE
				$html_contenido .= "\n <div class='button_trigger_response' id=\"button_trigger_$tipo\">";
				$html_contenido .= "";
				$html_contenido .= "</div>";									
	}
	
	
	# PRINT HTML
	print $html_contenido;
	
	
	#print "\n</div><!-- /css_wrap_button_trigger -->\n\n"; //wrap
?>