<?php

	# VISUALIZADOR HTML	

	
	if(isset($_REQUEST[$tipo]))						$dato = $_REQUEST[$tipo];		#var_dump($_REQUEST[$tipo]);
	
	
	#print "\n<!-- RADIO BUTTON [tipo:$tipo section_id_matrix:$parent] $label -->";
	print "\n<div class=\"css_wrap_radio_button\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	# CAMPO OBLIGATORIO
	$required_code 	= NULL;
	if($required)	$required_code = 'style="font-weight:bold"';
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "";
					break;						
		
		case ($permissions>=1)	:
					
					# COMPARISON OPERATORS
					$html_contenido .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);
					
					# INPUT
					$html_contenido .= "<span id=\"search_component_$tipo\">";
					foreach ($ar_list_of_values->result as $value => $rotulo) {
						if( $value == $dato ) {
							$checked = 'checked="checked"';
						}else {
							$checked = "";
						}
						$html_contenido .= "\n <input class=\"css_radio_button\" type=\"radio\" name=\"{$tipo}\"
						data-tipo=\"{$tipo}\" 
						value='$value' 
						title=\"$html_title\" $checked
						/>";
						$html_contenido .= "\n <label class=\"css_radio_button_rotulo\" $required_code >$rotulo</label>";						
					}
					$html_contenido .= "</span>";

					# LOGICAL OPERATORS
					$html_contenido .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);
							
	}	
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div>\n\n"; //wrap
?>