<?php

	# VISUALIZADOR HTML

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in', $modo, $lang);

	print "<div class=\"wrap_component css_wrap_radio_button wrap_component_{$tipo}\" id=\"{$id_wrapper}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato='{$dato_json}' ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-component_info='{$component_info}' ";
	print ">";



	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	$required_code 	= NULL;
	#if($required)
	#	$required_code = 'style="font-weight:bold"';

	# CONTENIDO (INPUT)
	$html_content = '';
	switch($permissions) {

		case 0	:	
				$html_content .= "";
				break;

		case 1	:
				$html_content .= "<ul class=\"radio_button_ul_list\">";
				$i=1; foreach((array)$ar_list_of_values->result as $value => $rotulo) {

					$value   = (string)$value;
					$locator = (object)json_handler::decode($value);	# Locator is json encoded object

					#$checked  = is_array($dato) && in_array($locator, $dato) ? true : false;
					$checked  = '';
					if (is_array($dato) && locator::in_array_locator($locator, $dato, array('section_id','section_tipo')) ) {
						$checked  = 'checked="checked"';
					}

					$tabindex = $i==1 ? 'tabindex="1"' : '';

					$input_id = $input_name.'_'.$i;

					$html_content .= "<li>";

						$checked_style='';
						if ($checked!==true) {
							$checked_style = 'checked_style_false';
						}

						#
						# LABEL
						$html_content .= "<label for=\"$input_id\" class=\"css_radio_button_rotulo $checked_style\" {$required_code}>$rotulo</label>";

					$html_content .= "</li>";
					$i++;
				}
				$html_content .= "</ul>";
				break;

		case 2 :
		case 3 :
				$html_content .= "<ul class=\"radio_button_ul_list\">";

				$i=1; foreach((array)$ar_list_of_values->result as $value => $rotulo) {

					$value   = (string)$value;
					$locator = (object)json_handler::decode($value);	# Locator is json encoded object
						#dump($locator, ' value ++ '.to_string());

					if (!property_exists($locator, 'type')) {
						$locator->type = DEDALO_RELATION_TYPE_LINK;
					}
					if (!property_exists($locator, 'from_component_tipo')) {
						$locator->from_component_tipo = $tipo;
					}

					$locator_string = json_encode($locator);

					#$checked  = is_array($dato) && in_array($locator, $dato) ? 'checked="checked"' : '';
					$checked  = '';
					if (is_array($dato) && locator::in_array_locator($locator, $dato, array('section_id','section_tipo')) ) {
						$checked  = 'checked="checked"';
					}

					$tabindex = $i==1 ? 'tabindex="1"' : '';

					$input_id = $input_name.'_'.$i;

					$html_content .= "<li>";

						#
						# INPUT
						$html_content .= "<input class=\"css_radio_button\" type=\"radio\" ";
						$html_content .= "onfocus=\"component_common.select_wrap(null,'$id_wrapper');\" ";
						$html_content .= "onchange=\"component_radio_button.Save(this)\" ";
						$html_content .= "name=\"{$input_name}\" ";
						$html_content .= "id=\"{$input_id}\" ";
						$html_content .= "data-tipo=\"{$tipo}\" ";
						$html_content .= "data-lang=\"{$lang}\" ";
						$html_content .= "data-section_tipo=\"{$section_tipo}\" ";
						$html_content .= "data-parent=\"{$parent}\" ";
						$html_content .= "data-mandatory='{$mandatory_json}' ";
						$html_content .= "value='$locator_string' ";
						$html_content .= "title=\"$html_title\" ";
						$html_content .= "$checked ";
						$html_content .= "$tabindex ";
						$html_content .= "/>";

						#
						# LABEL
						$html_content .= "<label for=\"$input_id\" class=\"css_radio_button_rotulo\" $required_code >$rotulo</label>";

					$html_content .= "</li>";
					$i++;
				}
				$html_content .= "</ul>";
				break;
	}//end switch($permissions)

	$html_content .= $js_code;


	# Prepare content to show in page
	tools::prepare_content($html_content);


	# PRINT HTML
	print $html_label;
	print $html_content;

	

	print "</div>"; //wrap


	// First test on load element
	if ($mandatory===true) {
		echo "<script>component_radio_button.mandatory('{$id_wrapper}')</script>";
	}

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out', $modo, $lang);

?>