<?php

	# VISUALIZADOR HTML	
	

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in');

	print "<div class=\"css_wrap_radio_button wrap_component\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-lang=\"{$lang}\"
	data-modo=\"{$modo}\"
	data-dato='{$dato_string}'
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";



	$required_code 	= NULL;
	#if($required)
	#	$required_code = 'style="font-weight:bold"';
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	
				$html_contenido .= "";
				break;
						
		case 1	: 
				foreach ($ar_list_of_values->result as $value => $rotulo) {						
					if( $value == $dato ) {
						$html_contenido .= " <label class=\"css_radio_button_rotulo\" $required_code >$rotulo</label>";
					}
				}
				break;	
						
		
		case ($permissions>=2) :					

				$html_contenido .= "<ul>";
				foreach ($ar_list_of_values->result as $value => $rotulo) {

					$value   = (string)$value; 
					$locator = (object)json_handler::decode($value);	# Locator is json encoded object
					#dump($locator," locator"); #dump($dato," dato");

					if (in_array($locator, $dato)) {	# dato is array always
						$checked = 'checked="checked"';
					}else{
						$checked = "";
					}

					$html_contenido .= "<li>";
					
						$html_contenido .= " <input class=\"css_radio_button\" type=\"radio\"
						onchange=\"component_radio_button.Save(this)\"
						name=\"{$input_name}\" 
						data-tipo=\"{$tipo}\"
						data-lang=\"{$lang}\"
						data-section_tipo=\"{$section_tipo}\"
						data-parent=\"{$parent}\"
						value='$value'
						title=\"$html_title\" $checked />";
						$html_contenido .= " <label class=\"css_radio_button_rotulo\" $required_code >$rotulo</label>";

						if ($rotulo!=end($ar_list_of_values->result)) {
							#$html_contenido .= "<br>";
						}
					$html_contenido .= "</li>";
				}
				$html_contenido .= "</ul>";
				break;
	}

	$html_contenido .= $js_code;

	# Prepare content to show in page
	tools::prepare_content($html_contenido);	
	
	
	# PRINT HTML
	print $html_contenido;


	if(SHOW_DEBUG) {
		echo "<hr>".$ar_list_of_values->debug;
	}
	
	print "</div>"; //wrap


	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out');


?>