<?php

	# VISUALIZADOR HTML	
	
	
	#print "<!-- RADIO BUTTON [tipo:$tipo section_id_matrix:$parent] $label -->";
	print "<div class=\"wrap_component css_wrap_radio_button\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch($permissions) {
			
		case 0	:	$html_content .= "";
					break;						
		
		case ($permissions>=1)	:
					
					# COMPARISON OPERATORS
					$html_content .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);
					
					# INPUT
					$html_content .= "<span id=\"search_component_$tipo\">";
					$i=0; foreach ($ar_list_of_values->result as $value => $rotulo) {

						$search_input_id = $search_input_name .'_'.$i;						
						
						$html_content .= "<input class=\"css_radio_button\" type=\"radio\" name=\"{$search_input_name}\" id=\"$search_input_id\" ";
						$html_content .= "data-tipo=\"{$tipo}\" ";
						$html_content .= "value='$value' ";
						$html_content .= "title=\"$html_title\" ";
						$html_content .= "/>";

						$html_content .= "<label for=\"{$search_input_id}\" class=\"css_radio_button_rotulo\">$rotulo</label>";						
					$i++;}
					$html_content .= "</span>";

					# LOGICAL OPERATORS
					$html_content .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);							
	}	
	
	
	# PRINT HTML
	print $html_label;
	print $html_content;
	
	
	print "</div>"; //wrap
?>