<?php

	# VISUALIZADOR HTML		

	$html    = "<!-- TOOL_TS_PRINT -->";	
	$html   .= '<div id="wrap_ts_print" class="wrap_tool wrap_tool_ts_print_page">';

		#
		# TOOL_TS_PRINT_TOP
		$html   .= '<section id="tool_ts_print_top">';

			#
			# SELECTOR (ar_hierachies)
			$html   .= '<label class="control-label input-lg" for="select_ts_section">'.label::get_label('tesauro').'</label>';
			$html   .= '<select id="select_ts_section" class="form-control" onchange="tool_ts_print.load_thesaurus_section(this)">';
			#$html   .= '<option></option>';
			# dump($ar_hierachies, ' ar_hierachies ++ '.to_string());
			foreach ($ar_hierachies as $key => $hierachy_obj) {
				
				$html .= '<option ';
				$html .= 'value="'.$hierachy_obj->{DEDALO_HIERARCHY_TARGET_SECTION_TIPO}.'" ';
				$html .= '>';
				$html .= $hierachy_obj->{DEDALO_HIERARCHY_TERM_TIPO};
				if(SHOW_DEBUG===true) {
					$html .= ' ['.$hierachy_obj->{DEDALO_HIERARCHY_TARGET_SECTION_TIPO}.']';
				}
				$html .= '</option>';
			}
			$html   .= '</select>';


			#
			# FORMAT SELECTOR 
			$html   .= '<label class="control-label input-lg" for="select_ts_format">'.label::get_label('formato').'</label>';
			$html   .= '<select id="select_ts_format" class="form-control" onchange="tool_ts_print.load_thesaurus_section(this)">';
			#$html   .= '<option></option>';
			# dump($ar_hierachies, ' ar_hierachies ++ '.to_string());
			$ar_formats = ['alphabetical','hierarchical'];
			# dump($ar_formats, ' ar_formats ++ '.to_string());
			foreach ($ar_formats as $current_format) {
	
				$selected = '';
				
				$html .= '<option ';
				$html .= 'value="'.$current_format.'" ';
				$html .= $selected;
				$html .= '>';
				$html .= label::get_label($current_format);
				if(SHOW_DEBUG===true) {
					$html .= ' ['.$current_format.']';
				}
				$html .= '</option>';
			}
			$html   .= '</select>';


			#
			# LANG SELECTOR 
			$lang_selector_style = 'display:none';
			if(SHOW_DEBUG===true) {
				$lang_selector_style = '';
			}
			$html   .= '<span style="'.$lang_selector_style.'">';	
			$html   .= '<label class="control-label input-lg" for="select_ts_lang">'.label::get_label('idioma').'</label>';
			$html   .= '<select id="select_ts_lang" class="form-control" onchange="tool_ts_print.load_thesaurus_section(this)">';
			#$html   .= '<option></option>';
			# dump($ar_hierachies, ' ar_hierachies ++ '.to_string());
			$ar_projects_langs = common::get_ar_all_langs();
			# dump($ar_projects_langs, ' ar_projects_langs ++ '.to_string());
			foreach ($ar_projects_langs as $key => $current_lang) {
	
				$selected = ($current_lang===DEDALO_DATA_LANG) ? 'selected' : '';
				
				$html .= '<option ';
				$html .= 'value="'.$current_lang.'" ';
				$html .= $selected;
				$html .= '>';
				$html .= lang::get_name_from_code($current_lang);
				if(SHOW_DEBUG===true) {
					$html .= ' ['.$current_lang.']';
				}
				$html .= '</option>';
			}
			$html   .= '</select>';
			$html   .= '</span>';	
			

		$html   .= '</section>';


		#
		# TS_CONTAINER
		$html   .= '<div id="ts_container">';

			#
			# LEGENDS 
			$ar_legends = ['abv_broader_term','abv_narrowed_term','abv_related_term','abv_scope_note','abv_use_for'];
			$html .= '<ul class="legends">';
			foreach ($ar_legends as $current_legend) {
				$html .= '<li>';
				$html .= '<strong>'.label::get_label($current_legend).'</strong>';
				# Definition
				$current_terminoID  = label::get_terminoID_from_label( $current_legend );
				$def 				= RecordObj_dd::get_def_by_tipo($current_terminoID, DEDALO_DATA_LANG);
				$html .= $def;
				$html .= '<li>';
			}
			$html .= '</ul>';

		$html   .='</div>';


	$html .= "</div><!-- /wrap_tool -->"; //wrap_tool


	$html .= '<script>';	
	$init_options = new stdClass();
		$init_options->ts_data  = $ts_data;
		$init_options->lang 	= DEDALO_DATA_LANG;
		$init_options->format 	= 'alphabetical';
	$html .= 'tool_ts_print.init('.json_encode($init_options).')';
	$html .= '</script>';

	if(SHOW_DEBUG===true) {
		#$html   .= '<pre id="ts_data_preview">'.json_encode($ts_data, JSON_PRETTY_PRINT).'</pre>';
	}	
	

	print $html;
?>