<?php

	# VISUALIZADOR HTML		

	$html    = "\n<!-- TOOL ADMINISTRATION -->";	
	$html   .= "\n<div class=\"wrap_tool wrap_tool_administration_page\" >";	


	#$html   .= $header_html;


	#
	# ADMIN UTILS
	$html   .= "\n<div class=\"content_data block-content-1\" >";

		# PANELS
		$html   .= "<div class=\"panel panel-primary\">";
		$html   .= "  <div class=\"panel-heading\">";
		$html   .= "    <h3 class=\"panel-title\"> ADMIN UTILS </h3>";
		$html   .= "  </div>";
		$html   .= "  <div class=\"panel-body\">";		


			#
			# UPDATE STRUCTURE
			$html   .= "<div class=\"panel_option\">";
			$html   .= "  <span class=\"glyphicon glyphicon-cog\" aria-hidden=\"true\"></span> ";
			$html   .= "  <a href=\"javascript:;\" onclick=\"tool_administration.update_structure(this)\">".label::get_label('actualizar_estructura')."</a>";
			$html   .= " <div class=\"panel_option_subcontent\">";			
			$html   .= "  <div id=\"update_structure_response\"></div>";
			$html   .= " </div>";#end panel_option_subcontent
			$html   .= "</div>";#end panel_option


			#
			# UPDATE VERSION
			$html   .= "<div class=\"panel_option\"> ";
			$html   .= "  <span class=\"glyphicon glyphicon-cog\" aria-hidden=\"true\"></span> ";
			if($update_version){
				

				#$html   .= "  <div class=\"panel_option\">";
				#$html   .= "  <span class=\"glyphicon glyphicon-cog\" aria-hidden=\"true\"></span> ";
				$html   .= "  <a href=\"javascript:;\" onclick=\"tool_administration.update_version('$update_version')\">".label::get_label('actualizar')." ".label::get_label('datos')."</a>";

				$html 	.= "  <span>[";
				$html 	.= "  <span id=\"update_current_version\">Dédalo ver: $current_dedalo_version</span> - ";
				$html 	.= "  <span id=\"update_current_version\">User data in PostgreSQL ver: $current_version</span>";
				$html 	.= "  ]</span>";
				
				$html   .= " <div class=\"panel_option_subcontent\">";
				$html 	.= "  <span id=\"update_current_version\">$current_version</span>";
				$html 	.= "  <span id=\"update_to_version\"> -----> $update_version</span>";
				$html   .= "  <div id=\"update_version_response\"></div>";
				$html   .= "  </div>";#end panel_option_subcontent

			}else{

				$html   	.=  " <span>".label::get_label('actualizar')."</span>";

				$html 		.= "  <span id=\"update_current_version\">$current_dedalo_version</span>";
				$html   	.= " <div class=\"panel_option_subcontent\">";
				if($current_dedalo_version == $current_version){
					$html 	.= "  <span class=\"glyphicon glyphicon-ok-circle\" aria-hidden=\"true\" style=\"color:#5cbd39\"></span> ";
				}else{
					$html 	.= "  <span class=\"glyphicon glyphicon-ban-circle\" aria-hidden=\"true\" style=\"color:#f72f19\"></span> ";
					$html 	.= "  <span id=\"update_current_version\">User data in PostgreSQL ver: $current_version</span> </br>";
					$html 	.= "  <span>ALERT: DON'T HAVE UPDATE!!</span> </br>";
				}
				$html  		.= "  </div>";#end panel_option_subcontent
			}
			$html   .= "</div>";#end panel_option



			#
			# FORCE_UNLOCK_ALL_COMPONENTS
			$html   .= "<div class=\"panel_option\">";
			$html   .= "  <span class=\"glyphicon glyphicon-cog\" aria-hidden=\"true\"></span>";
			$html   .= "  <a href=\"javascript:;\" onclick=\"tool_administration.force_unlock_all_components(this)\">".label::get_label('desbloquear_todos_los_componentes')."</a>";
			$html   .= " <div class=\"panel_option_subcontent\">";	
			$html   .= "  <div id=\"force_unlock_all_components_response\"></div>";
			$html   .= " </div>";#end panel_option_subcontent
			$html   .= "</div>";#end panel_option


			#
			# BUILD_STRUCTURE_CSS
			$html   .= "<div class=\"panel_option\">";
			$html   .= " <span class=\"glyphicon glyphicon-cog\" aria-hidden=\"true\"></span>";
			$html   .= " <a href=\"javascript:;\" onclick=\"tool_administration.build_structure_css(this)\">".label::get_label('build_structure_css')."</a>";
			$html   .= " <div class=\"panel_option_subcontent\">";
			$html   .= "  <div id=\"build_structure_css_response\"></div>";
			$html   .= " </div>";#end panel_option_subcontent
			$html   .= "</div>";#end panel_option


			#
			# DELETE_COMPONENT_TIPO_IN_MATRIX_TABLE
			$html   .= "<div class=\"panel_option form-inline\"> ";
			
			$html   .= " <span class=\"glyphicon glyphicon-cog\" aria-hidden=\"true\"></span>";
			$html   .= " <span>".label::get_label('delete_component_tipo_of_section_tipo')."</span>";

			$html   .= " <div class=\"panel_option_subcontent\">";
			#$html   .= "  <span title=\"component tipo\">".label::get_label('component_tipo')."</span>";
			$html   .= "  <input type=\"text\" id=\"delete_component_tipo\" class=\"form-control input-sm\" autocomplete=\"off\" placeholder=\"".label::get_label('component_tipo')."\" />";
			#$html   .= "  <span title=\"section tipo\">".label::get_label('section_tipo')."</span>";
			$html   .= "  <input type=\"text\" id=\"delete_section_tipo\" class=\"form-control input-sm\" autocomplete=\"off\" placeholder=\"".label::get_label('section_tipo')."\" />";
			#$html   .= "  <span title=\"Language\">".label::get_label('tool_lang')."</span>";
			$html   .= "  <input type=\"text\" id=\"delete_language\" class=\"form-control input-sm\" autocomplete=\"off\" placeholder=\"".label::get_label('tool_lang')."\" />";			
			$html   .= "  <div class=\"checkbox\"><label><input type=\"checkbox\" id=\"delete_save\" class=\"form-control input-sm\" name=\"Save\" value=\"true\" /> <span>".label::get_label('salvar')."</span></label></div>";	
			$html   .= "  <input type=\"button\" class=\"btn btn-default btn-sm\" value=\"".label::get_label('borrar')."\" onclick=\"tool_administration.delete_component_tipo_in_matrix_table(this)\" />";
			$html   .= "  <div id=\"delete_component_tipo_in_matrix_table\"></div>";
			$html   .= " </div>";#end panel_option_subcontent

			$html   .= "</div>";#end panel_option
			

			
			


		$html   .= "  </div>";//end panel-body
		$html   .= "</div>";//end panel-primary
		

	$html   .= "\n</div>";//end content_data block-content-1


	
	#
	# USERS INFO
	$html   .= "\n<div class=\"content_data\" >";	// text_shadow_inset

		# PANELS
		$html   .= "<div class=\"panel panel-info\">";
		$html   .= "  <div class=\"panel-heading\">";
		$html   .= "    <h3 class=\"panel-title\"> USERS INFO </h3>";
		$html   .= "  </div>";
		$html   .= "  <div class=\"panel-body\">";
		
			#
			# ACTIVE_USERS
			if (defined('DEDALO_LOCK_COMPONENTS') && DEDALO_LOCK_COMPONENTS===true) {		
				$html   .= "<div>";
				$html   .= " <span class=\"glyphicon glyphicon-info-sign\" aria-hidden=\"true\"></span> ";
				$html   .= " <a href=\"javascript:;\" onclick=\"tool_administration.get_active_users(this)\">".label::get_label('usuarios_activos')."</a>";
				$html   .= "</div>";
				$html   .= "<div id=\"active_users\"></div>";
			}

		$html   .= "  </div>";//end panel-body
		$html   .= "</div>";//end panel-info

	$html   .= "\n</div>";//end content_data

	
	#
	# SYSTEM INFO
	$html   .= "\n<div class=\"content_data block-content-2\" >";	// text_shadow_inset


		$html   .= "<div class=\"panel panel-info\">";
		$html   .= "  <div class=\"panel-heading\">";
		$html   .= "    <h3 class=\"panel-title\"> SYSTEM INFO </h3>";
		$html   .= "  </div>";
		#$html   .= "  <div class=\"panel-body\">";
		$html   .= "<ul class=\"list-group panel-body\">";


			#
			# DEDALO VERSION
			$dedalo_structure_info = RecordObj_dd::get_termino_by_tipo(DEDALO_ROOT_TIPO);
			$prefix_tipos  = unserialize(DEDALO_PREFIX_TIPOS);
			$dedalo_structure_info .= "\n".'Prefix: '. implode(",",$prefix_tipos);
			$info_database = pg_version(DBi::_getConnection());	
			$html .= tool_administration::show_info( "Dedalo version",
													 DEDALO_VERSION,
													 "v".DEDALO_VERSION ." | Build: ".DEDALO_BUILD
													);


			#
			# DEDALO STRUCTURE
			$dedalo_structure_info = RecordObj_dd::get_termino_by_tipo(DEDALO_ROOT_TIPO);
			$prefix_tipos  = unserialize(DEDALO_PREFIX_TIPOS);
			$dedalo_structure_info .= "\n".'Prefix: '. implode(",",$prefix_tipos);
			$info_database = pg_version(DBi::_getConnection());	
			$html .= tool_administration::show_info( "Dedalo structure review",
													 '',
													 $dedalo_structure_info
													);


			#
			# DATABASE
			$info_database = pg_version(DBi::_getConnection());	
			$html .= tool_administration::show_info( "Database",
													 $info_database['IntervalStyle']. " ". $info_database['server'],
													 $info_database
													);

			#
			# PHP USER
			$processUser = posix_getpwuid(posix_geteuid());
			$html .= tool_administration::show_info( "PHP user",
													 $processUser['name'],
													 $processUser
													);

			
			#
			# ENCODING mb_internal_encoding
			$result = mb_internal_encoding();
			$html .= tool_administration::show_info( "PHP ENCODING",
													 "mb_internal_encoding",
													 $result
													);
			

			#
			# ENCODING mb_regex_encoding
			$result = mb_regex_encoding();
			$html .= tool_administration::show_info( "PHP ENCODING",
													 "mb_regex_encoding",
													 $result
													);
			

			#
			# SESSION MAX LIFE TIME
			$maxlifetime = ini_get("session.gc_maxlifetime");
			$html .= tool_administration::show_info( "PHP SESSION MAX LIFE TIME",
													 "session.gc_maxlifetime",
													 $maxlifetime/60 ." min (".$maxlifetime/3600 ." hours)"
													);

			#
			# HTTP HEADERS
			# it could be useful if you using nginx instead of apache 
			if (!function_exists('getallheaders')) { 
			    function getallheaders() { 
			           $headers = ''; 
			       foreach ($_SERVER as $name => $value) { 
			           if (substr($name, 0, 5) == 'HTTP_') { 
			               $headers[str_replace(' ', '-', ucwords(strtolower(str_replace('_', ' ', substr($name, 5)))))] = $value; 
			           } 
			       } 
			       return $headers; 
			    } 
			} 
			$url 	 = DEDALO_PROTOCOL . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
			$headers = array();
			#$headers += headers_list();
			$headers += get_headers($url, 1);
			$headers += getallheaders();
			$html .= tool_administration::show_info( "HTTP HEADER",
													 " $url",
													 $headers
													);			


			#
			# FFMPEG
			$ffmpeg = shell_exec(DEDALO_AV_FFMPEG_PATH." -version ");
			preg_match("/ffmpeg version (.*) Copyright/", $ffmpeg, $output_array);
			$html .= tool_administration::show_info( "FFMPEG",
													 $output_array[1] ." - ". DEDALO_AV_FFMPEG_PATH,
													 $ffmpeg
													);


			#
			# FFPROBE
			$ffprobe = shell_exec(DEDALO_AV_FFPROBE_PATH." -version ");	
			preg_match("/ffprobe version (.*) Copyright/", $ffprobe, $output_array);
			$html .= tool_administration::show_info( "PROBE",
													 $output_array[1] ." - ". DEDALO_AV_FFPROBE_PATH,
													 $ffprobe
													);

			#
			# DEDALO_AV_FASTSTART_PATH
			$faststart = shell_exec(DEDALO_AV_FASTSTART_PATH." -v ");
			$html .= tool_administration::show_info( "FASTSTART",
													 DEDALO_AV_FASTSTART_PATH,
													 $faststart
													);



			#
			# IMAGE MAGICK
			$result = shell_exec(MAGICK_PATH."convert -version ");
			preg_match("/Version: ImageMagick (\S*)\s/", $result, $output_array);
			$html .= tool_administration::show_info( "IMAGE MAGICK",
													 $output_array[1] ." - ". MAGICK_PATH,
													 $result
													);


			#
			# NODE JS
			$result = shell_exec(DEDALO_NODEJS." -v ");
			$html .= tool_administration::show_info( "NODE JS",
													 $result." - ".DEDALO_NODEJS,
													 $result
													);
			

			#
			# TINYMCE
			#$path = DEDALO_ROOT.'/lib/tinymce/js/tinymce/tinymce.min.js';
			$path = str_replace(DEDALO_ROOT_WEB, DEDALO_ROOT, TEXT_EDITOR_URL_JS);
			$f = fopen($path, 'r');
			$result = fgets($f);
			fclose($f);
			preg_match("/\/\/\s(\S*)\s/", $result, $output_array);
			$html .= tool_administration::show_info( "TINYMCE",
													 $output_array[1]." - ".$path,
													 $result
													);



			#
			# JQUERY
			#$path = DEDALO_ROOT.'/lib/jquery/jquery.min.js';
			$path = str_replace(DEDALO_ROOT_WEB, DEDALO_ROOT, JQUERY_LIB_URL_JS);
			$f = fopen($path, 'r');
			$result = fgets($f);
			fclose($f);
			preg_match("/\*\!\sjQuery v(\S*)\s/", $result, $output_array);
			$html .= tool_administration::show_info( "JQUERY",
													 $output_array[1]." - ".$path,
													 $result
													);


			#
			# PAPER
			#$path = DEDALO_ROOT.'/lib/paper/dist/paper-full.min.js';
			$path = str_replace(DEDALO_ROOT_WEB, DEDALO_ROOT, PAPER_JS_URL);
			$lines = file($path);//file in to an array
			$result = $lines[1]; //line 2
			preg_match("/js v(\S*)\s-/", $result, $output_array);
			$html .= tool_administration::show_info( "PAPER",
													 $output_array[1]." - ".$path,
													 $result
													);


			#
			# LEAFLET
			#$path = DEDALO_ROOT.'/lib/leaflet/stable_versions/leaflet.js';
			$path = str_replace(DEDALO_ROOT_WEB, DEDALO_ROOT, LEAFLET_JS_URL);
			$lines = file($path);//file in to an array
			$result = $lines[5]; //line 2
			preg_match("/version=\"([0-9]+.[0-9]+.[0-9]+)\"/", $result, $output_array);
			$result = $output_array[1];
			$html .= tool_administration::show_info( "LEAFLET",
													 $output_array[1]." - ".$path,
													 $result
													);		
		


			#
			# DB DATA CHECK
			if(SHOW_DEBUG) {			
				require(DEDALO_LIB_BASE_PATH.'/db/class.data_check.php');
				$data_check = new data_check();
				$response 	= $data_check->check_sequences();
				if ($response->result!=true) {
					debug_log(__METHOD__." $response->msg ".to_string(), logger::WARNING);
					if(SHOW_DEBUG) {
						die("Error on ".$response->msg);
					}
				}
				$html .= tool_administration::show_info( "DB SEQUENCES STATE",
														 "",
														 $response->msg
														);
			}


		$html   .= "</ul>";//end list-group


		#$html   .= "  </div>";//end panel-body		
		$html   .= "</div>";//end #system_info_content
	

	$html .= "\n</div><!-- /content_data block-content-2 -->";





	#
	# PHP INFO
	$html   .= "\n<div class=\"content_data block-content-3\" >";
	$html   .= "<div class=\"panel panel-info\">";

		$html   .= "  <div class=\"panel-heading\">";
		$html   .= "    <h3 class=\"panel-title\"> PHP INFO </h3>";
		$html   .= "  </div>";
		
		$html   .= "<ul class=\"list-group panel-body\" style=\"display:none\">";

			#
			# PHPINFO
			$html   .= "<li>";
			$html   .= "\n<iframe id=\"phpinfo\"
			src=\"".DEDALO_LIB_BASE_URL."/tools/tool_administration/html/phpinfo.php\"
			frameborder=\"0\"
			scrolling=\"no\"
			onload=\"resizeIframe(this)\"
			></iframe>";
			$html   .= "</li>";

		$html   .= "</ul>";//end list-group
	
	$html   .= "</div>";//end #php_info_content
	$html .= "\n</div><!-- /content_data block-content-3 -->";		



	$html .= "\n</div><!-- /wrap_tool -->"; //wrap_tool

	

	print $html;
		
?>