<?php

	# VISUALIZADOR HTML	
		
	# BUTTON TOOL
	$html_tool    = '';
	#$html_tool   .= "\n<!-- TOOL TRANSCRIPTION [tipo:$tipo parent:$parent] -->";
	
	#$html_tool   .= "<div class=\"tool_inspector_div\">";

	# ICON
	$title	  = label::get_label('abrir').' '.label::get_label('herramienta');
	/*
	$html_tool   .= "\n<div id=\"btn_transcription_open\" class=\"icon_bs tool_transcription_icon link\" onclick=\"tool_common.open_tool_transcription(this)\"
	data-tipo=\"{$tipo}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-lang=\"{$lang}\"
	data-tab_id=\"img_lang_{$tipo}_{$parent}\"
	data-context_name=\"$component_name\"
	title=\"$title\"></div>";
	*/
	$html_tool .= "<a href=\"javascript:void(0);\" class=\"id_column_buttons button_transcription link\" title=\"$title\" onclick=\"tool_common.open_tool_transcription(this)\"
	data-tipo=\"{$tipo}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-lang=\"{$lang}\"
	data-tab_id=\"img_lang_{$tipo}_{$parent}\"
	data-context_name=\"$component_name\"
	>";
		$html_tool .= "<span class='section_id_number'>";
		$html_tool .= " $section_id ";
		$html_tool .= "</span>";
	$html_tool .= "</a>";

	# TOOL NAME	
	#$html_tool   .= label::get_label($tool_name="tool_transcription");


	

	#$html_tool   .= "</div>";#/tool_inspector_div


	
	# PRINT HTML
	print $html_tool;
	
?>