<?php 
/* PAGE */

$html = '';

	$html .= "<script>
				var max_size_bytes = '$maxSize',
					quality = '$quality',
					SID = '$SID',
					media_type = '$media_type',
					valid_extensions_json = '$valid_extensions_json';
			</script>";


	$html   .= "\n<!-- TOOL PAGE [tipo:$tipo] -->"; 
	$html   .= "\n<div class=\"wrap_tool wrap_tool_upload_page\" >";
	$html   .= "\n<div class=\"content_data text_shadow_inset\" >";
	
	$html .= "\n<form id=\"form_upload\" name=\"form_upload\" enctype=\"multipart/form-data\" method=\"post\" action=\"\">";

		
		# FILE INPUT
		$html .= "\n <div class=\"row\">";
			$html .= "\n <div id=\"max_size_info\"></div>";
			$html .= "\n <div class=\"mini_icon_dedalo\"></div>";
			#$html .= "\n <label for=\"fileToUpload\">" .label::get_label('seleccione_el_fichero_a_subir'). "</label>";

			$fileSelected_options = '';
			if (isset($this->fileSelected_options)) {
				$fileSelected_options = $this->fileSelected_options;
			}

			$multiple = ''; #'name="file_input" webkitdirectory="" directory="" ';
			$html .= "\n <input type=\"file\" name=\"fileToUpload\" id=\"fileToUpload\" class=\"input_file\" $multiple onchange=\"tool_upload.fileSelected($fileSelected_options);\" />";

			$html .= "<label for=\"fileToUpload\" class=\"input_file_label\" ondragover=\"tool_upload.drag_over(event)\" ondragleave=\"tool_upload.drag_leave(event)\" ondrop=\"tool_upload.drop(event)\">";

			$html .="<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"17\" viewBox=\"0 0 20 17\"><path d=\"M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z\"></path></svg>";
			#$html .= '<img class="upload_image" src="../themes/default/upload.svg">';

			$html .= label::get_label('seleccione_el_fichero_a_subir');

			$html .= "</label>";


		$html .= "\n </div>";#end file input row 
		
		
		# BUTTON UPLOAD
		$html .= "\n <div class=\"row\">";
		
			$html .= "\n <input type=\"hidden\" name=\"SID\" 	 id=\"SID\" 	value=\"{$SID}\" />";
			$html .= "\n <input type=\"hidden\" name=\"quality\" id=\"quality\" value=\"{$quality}\" />";
			$html .= "\n <input type=\"hidden\" name=\"mode\" 	 id=\"mode\" 	value=\"upload_file\" />";			
			$html .= "\n <input type=\"hidden\" name=\"tipo\" 	 id=\"tipo\" 	value=\"{$tipo}\" />";			
			$html .= "\n <input type=\"hidden\" name=\"parent\"  id=\"parent\" 	value=\"{$parent}\" />";
			$html .= "\n <input type=\"hidden\" name=\"section_tipo\" id=\"section_tipo\" value=\"{$section_tipo}\" />";
				
			$html .= "\n <input type=\"button\" class=\"css_button_generic link\" onclick=\"tool_upload.uploadFile()\" id=\"btn_upload\" value=\"Upload\" />";

			$html .= "\n  <div class=\"info_current\">";
				# Icon
				switch ($media_type) {
					case 'av':
						$icon_class = 'av_icon';
						break;
					case 'image':
						$icon_class = 'image_icon';
						break;
					case 'pdf':
						$icon_class = 'pdf_icon';
						break;
					default:
						$icon_class = 'file_icon';
						break;
				}                
				$html .= "<div class=\"icon_bs upload_icon $icon_class\"></div>";
				$html .= "File name: {$SID} - quality: $quality";
			$html .= "\n  </div>";#end info_current

			# Valid extensions          
			$html .= "\n  <div class=\"valid_extensions\">";
			$html .= label::get_label('extensiones_soportadas'). ' ' . $valid_extensions_json;
			$html .= "\n  </div>";         
		$html .= "\n </div>";#end button upload row


		# FILE INFO
		$html .= "\n <div class=\"\" id=\"fileInfo\">";
			$html .= "\n <div id=\"fileName\"></div>";
			$html .= "\n <div id=\"fileSize\"></div>";
			$html .= "\n <div id=\"fileType\"></div>";
			$html .= "\n <div id=\"progress_info\"></div>";
		$html .= "\n </div>";       


		# PROGRESS BAR
		$html .= "\n <!-- PROGRESS BAR -->";
		$html .= "\n <div class=\"\" id=\"progressIndicator\">";
				
			$html .= "\n <div id=\"progressNumber\" class=\"floatRight\"></div>";
					
			$html .= "\n <div class=\"clear\"></div>";
			$html .= "\n <div id=\"progressBar\"> </div>";
			$html .= "\n <div class=\"clear\"></div>";

			$html .= "\n <div>";   
				$html .= "\n <div id=\"transferSpeedInfo\" class=\"floatLeft\"> &nbsp; </div>";
				$html .= "\n <div id=\"timeRemainingInfo\" class=\"floatLeft\"> &nbsp; </div>";
				$html .= "\n <div id=\"transferBytesInfo\" class=\"floatRight\"> &nbsp; </div>";
				$html .= "\n <div class=\"clear\"></div>";
			$html .= "\n </div>";
		   
		$html .= "\n</div><!-- /progressIndicator -->";



		# UPOAD RESPONSE BY TRIGGER
		$html .= "\n<div id=\"uploadResponse\"> &nbsp; </div>";



		# DEBUG INFO
		$html .= "\n<!-- DEBUG INFO -->";
		$html .= "\n<div class=\"php_var_info\">";
				
			# DIRECTORIO TEMPORAL DE SUBIDA DE ARCHIVOS
			$upload_tmp_dir = ini_get('upload_tmp_dir');

			# INFO DEBUG ADMIN
			if(SHOW_DEBUG) {
				
				$html .= "PHP sys_get_temp_dir: " .sys_get_temp_dir();
				$html .= "<br>";
				$html .= "PHP upload_tmp_dir: " . ini_get('upload_tmp_dir');
				$html .= "<br>";
				$html .= "PHP upload_tmp_dir fileperms: " ; $html .= fileperms($upload_tmp_dir); 
				#$html .= "<br>";
				#$html .= "Dir: $folder_path" ;

							   
				#$html .= " (" .substr(sprintf('%o', fileperms($upload_tmp_dir)), -4) .") ";

				$file_perms_test = fileperms($upload_tmp_dir);
				if(empty($file_perms_test))
				$html .= "<br><error>WARNING: YOUR TEMP FOLDER IS NOT ACCESSIBLE FOR PHP TO VERIFY PERMISSIONS</error>";

				$html .= "<br> session_cache_limiter   " . session_cache_limiter() ;
				$html .= "<br> session.cache_expire    " . ini_get('session.cache_expire') .  " min  [" . ini_get('session.cache_expire')/60 ." hours]";
				$html .= "<br> session.gc_maxlifetime  " . ini_get('session.gc_maxlifetime'). " secs [" .ini_get('session.gc_maxlifetime')/3600 ." hours]";

			}

			# NOTIFICA QUE HAY UN PROBLEMA CON LA CARPETA TEMPORAL
			$upload_tmp_dir_fileperms = fileperms($upload_tmp_dir);
			if( empty( $upload_tmp_dir_fileperms ) ) {
				#$html .= "<br><error>ERROR: YOUR TEMP FOLDER IS NOT ACCESSIBLE AND IS IMPOSSIBLE UPLOAD FILES</error>";
				#$html .= "<script type=\"text/javascript\">$('.row').hide()</script>";
			}
			
		$html .= "\n</div>";#end php_var_info

	$html .= "\n</form>";


	$html .= "\n</div><!-- /content_data -->";
	$html .= "\n</div><!-- /wrap_tool -->"; //wrap_tool

	#$html .= "<script>";
	#$html .= "tool_upload.init()";
	#$html .= "</script>";


print $html;

	
?>