<?php

	# VISUALIZADOR HTML	
		
	# BUTTON TOOL
	$html_tool    = "\n<!-- TOOL UPLOAD [tipo:$tipo parent:$parent] -->";
	$html_tool   .= "<div class=\"tool_inspector_div\">";

	$btn_title	  = label::get_label('abrir').' '.label::get_label('herramienta');
	$html_tool   .= "\n<div class=\"icon_bs tool_upload_icon link\" 								
								data-tipo=\"{$tipo}\"
								data-parent=\"{$parent}\"
								data-section_tipo=\"$section_tipo\"
								data-sid=\"{$SID}\"
								data-quality=\"$quality\"
								data-aditional_path=\"$aditional_path\"
								data-initial_media_path=\"$initial_media_path\"
								title=\"$btn_title\"
								onclick=\"tool_common.open_tool_upload(this)\"
								> </div>";


	$html_tool   .= label::get_label('tool_upload');	#" Upload";	

	$html_tool   .= "</div>";#/tool_inspector_div

	# PRINT HTML
	print $html_tool;
	
?>