<?php

	# VISUALIZADOR HTML	
		
	# BUTTON TOOL IN INSPECTOR
	$html_tool    = '';

	if(SHOW_DEBUG===true) {
		$html_tool .= "<!-- TOOL_ADD_COMPONENT_DATA [tipo:$tipo parent:$parent] -->";
	}
	
	$html_tool   .= '<div class="tool_inspector_div">';

	$btn_title	  = label::get_label('abrir').' '.label::get_label('herramienta');
	$html_tool   .= '<div class="icon_bs tool_relation_icon link" ';
	$html_tool   .= 'data-tipo="'.$tipo.'" ';
	$html_tool   .= 'data-parent="'.$parent.'" ';
	$html_tool   .= 'data-caller_id="'.$parent.'" ';
	$html_tool   .= 'title="'.$btn_title.'" ';
	$html_tool   .= 'onclick="tool_common.open_tool_add_component_data(this)" ';
	$html_tool   .= '></div>';

	$html_tool   .= label::get_label('tool_add_component_data');
	

	$html_tool   .= '</div>';#/tool_inspector_div

	# PRINT HTML
	print $html_tool;	
?>