// @license magnet:?xt=urn:btih:0b31508aeb0634b347b8270c7bee4d411b5d4109&dn=agpl-3.0.txt AGPL-3.0
/*global page_globals */
/*eslint no-undef: "error"*/



/**
* CANVAS_TOOL_PRINT
*
* Page/canvas model and box editing for tool_print.
* Geometry is canonical in millimetres; on-screen pixels are always derived
* (mm * PX_PER_MM * zoom). The same .print_root / .print_page / .box DOM is
* reused for editing and for printing (see tool_print.less @media print and the
* beforeprint hook in render_tool_print.js).
*
* No core helper does absolute-mm drag/resize, so the move/resize handlers here
* adopt the offset-drag pattern of core/common/js/dd-modal.js (capture a cursor
* offset on mousedown, listen on document, clear on mouseup).
*/

	import {ui} from '../../../core/common/js/ui.js'
	import {is_relation_model, column_key} from './render_box_tool_print.js'
	import {make_editor_ctx, layout_flow} from './flow_engine.js'



// CSS reference pixels per millimetre (96 dpi / 25.4 mm-per-inch)
	export const PX_PER_MM = 96 / 25.4

// named page formats (portrait mm)
	export const PAGE_FORMATS = {
		A4		: { width_mm: 210, height_mm: 297 },
		A3		: { width_mm: 297, height_mm: 420 },
		A5		: { width_mm: 148, height_mm: 210 },
		Letter	: { width_mm: 215.9, height_mm: 279.4 },
		Legal	: { width_mm: 215.9, height_mm: 355.6 }
	}

// font family options → CSS stacks (default sans-serif / Helvetica)
	export const FONT_STACKS = {
		sans	: 'Helvetica, Arial, sans-serif',
		serif	: 'Georgia, "Times New Roman", Times, serif',
		mono	: 'Menlo, Consolas, "Courier New", monospace'
	}
	export const font_stack = function(key) {
		return FONT_STACKS[key] || FONT_STACKS.sans
	}//end font_stack



// tool_print SCHEMA VERSION. v2 = document-flow grid: layout.flow.rows[].cells[].block,
// pages are content-driven (generated by the flow engine), no absolute boxes/pages.
export const SCHEMA_VERSION = 2

/**
* NEW_LAYOUT
* Builds a fresh layout blob (v2 document-flow model) for the target section,
* seeded with one empty single-cell row.
* @param object self - The tool_print instance
* @param object opts - { name }
* @return object layout blob (schema_version 2)
*/
export const new_layout = function(self, opts={}) {

	const target_section_tipo = Array.isArray(self.target_section_tipo)
		? self.target_section_tipo[0]
		: self.target_section_tipo

	return {
		schema_version		: SCHEMA_VERSION,
		kind				: 'tool_print_layout',
		// NOTE: must NOT be named 'id' — component_json reads a top-level data-item
		// 'id' as the entry counter (int); a string here breaks raise_component_counter
		uid					: gen_id(self, 'tpl'),
		name				: opts.name || 'Untitled',
		target_section_tipo	: target_section_tipo,
		visibility			: 'user',
		owner_user_id		: '' + page_globals.user_id,
		units				: 'mm',
		page_defaults		: {
			size		: 'A4',
			width_mm	: PAGE_FORMATS.A4.width_mm,
			height_mm	: PAGE_FORMATS.A4.height_mm,
			orientation	: 'portrait',
			margins_mm	: { top: 15, right: 15, bottom: 15, left: 15 }
		},
		grid				: { enabled: false, size_mm: 5, snap: true },
		style_defaults		: {
			font_family	: 'sans',
			font_size_pt: 11,
			align		: 'left',
			valign		: 'top',
			text_color	: '#111111',
			border_show	: true,
			border_color: '#cccccc'
		},
		flow				: { rows: [ new_row(self) ] }
	}
}//end new_layout



/**
* NEW_ROW
* A flow row: a horizontal grid of cells (1..N, fractional widths summing ~1).
* @param object self
* @param object[] cells - optional initial cells (defaults to one empty cell)
* @return object row
*/
export const new_row = function(self, cells) {
	return {
		id				: gen_id(self, 'row'),
		kind			: 'row',
		space_after_mm	: 0,
		style			: {},
		cells			: (Array.isArray(cells) && cells.length) ? cells : [ new_cell(self) ]
	}
}//end new_row



/**
* NEW_CELL
* One cell of a flow row. width = fraction of the content column. block = the
* cell's content (a component, free text, or empty).
* @param object self
* @param object block - optional block (defaults to empty)
* @param number width - optional fraction (default 1)
* @return object cell
*/
export const new_cell = function(self, block, width) {
	return {
		id		: gen_id(self, 'cell'),
		width	: (typeof width==='number') ? width : 1,
		block	: block || { type: 'empty' }
	}
}//end new_cell



/**
* NEW_SPACER_ROW
* A whitespace row of fixed mm height (no cells).
* @param object self
* @param number height_mm
* @return object spacer row
*/
export const new_spacer_row = function(self, height_mm) {
	return {
		id			: gen_id(self, 'row'),
		kind		: 'spacer',
		height_mm	: (typeof height_mm==='number') ? height_mm : 8
	}
}//end new_spacer_row



/**
* COMPONENT_BLOCK
* Builds a cell block for a component (from a palette ddo drop payload).
* @param object parsed - { ddo, path } drop payload
* @return object block
*/
export const component_block = function(parsed) {
	const ddo = parsed.ddo
	return {
		type			: 'component',
		component_ref	: {
			tipo			: ddo.tipo,
			section_tipo	: ddo.section_tipo,
			model			: ddo.model,
			view			: ddo.view || 'default',
			label_snapshot	: ddo.label || ddo.tipo
		},
		path			: parsed.path || null,
		show_label		: true,
		render			: { value_view: 'default', lang: 'inherit', multivalue: { mode: 'list' } },
		style			: {}
	}
}//end component_block



/**
* GEN_ID
* Deterministic-enough unique id within the session (no Math.random needed).
* @param object self
* @param string prefix
* @return string
*/
const gen_id = function(self, prefix) {
	self.id_counter = (self.id_counter || 0) + 1
	return prefix + '_' + self.id_counter
}//end gen_id



/**
* RESEAT_IDS
* Re-assigns globally-unique ids to every row and cell of the current layout and
* seeds self.id_counter past them. A loaded template carries ids minted in another
* session (e.g. row_8/cell_9); without reseating, the session counter starts low
* and gen_id() collides with them, so two rows share an id and select_cell() picks
* the wrong (first-matching) one. Run on load to de-duplicate and keep new ids unique.
* @param object self
* @return void
*/
export const reseat_ids = function(self) {
	const rows = self && self.layout && self.layout.flow && self.layout.flow.rows
	if (!Array.isArray(rows)) return
	let n = 0
	for (const row of rows) {
		row.id = 'row_' + (++n)
		if (Array.isArray(row.cells)) {
			for (const cell of row.cells) {
				cell.id = 'cell_' + (++n)
			}
		}
	}
	self.id_counter = n
}//end reseat_ids



// geometry helpers ----------------------------------------------------------

	/**
	* PAGE_DIMS
	* Resolves a page's width/height in mm honouring orientation and any
	* per-page override, falling back to layout.page_defaults.
	* @param object self
	* @param object page
	* @return object { width_mm, height_mm }
	*/
	export const page_dims = function(self, page) {

		const defaults	= self.layout.page_defaults
		const ov		= (page && page.page_overrides) ? page.page_overrides : {}
		const size		= ov.size || defaults.size
		const format	= PAGE_FORMATS[size] || { width_mm: defaults.width_mm, height_mm: defaults.height_mm }
		const orient	= ov.orientation || defaults.orientation

		const w = (size==='custom') ? (ov.width_mm || defaults.width_mm) : format.width_mm
		const h = (size==='custom') ? (ov.height_mm || defaults.height_mm) : format.height_mm

		return (orient==='landscape')
			? { width_mm: h, height_mm: w }
			: { width_mm: w, height_mm: h }
	}//end page_dims

	export const mm_to_px = (self, mm) => Math.round(mm * PX_PER_MM * (self.zoom || 1))
	export const px_to_mm = (self, px) => px / (PX_PER_MM * (self.zoom || 1))

	/**
	* SNAP_MM
	* Snaps a mm value to the grid when snapping is enabled.
	* @param object self
	* @param number mm
	* @return number
	*/
	export const snap_mm = function(self, mm) {
		const grid = self.layout.grid
		if (!grid || !grid.snap || !grid.size_mm) {
			return Math.round(mm * 10) / 10 // 0.1mm resolution
		}
		return Math.round(mm / grid.size_mm) * grid.size_mm
	}//end snap_mm



// rendering -----------------------------------------------------------------

/**
* RENDER_CANVAS
* (Re)builds the whole print surface (.print_root) inside the given container.
* @param object self
* @param HTMLElement container
* @return HTMLElement print_root
*/
export const render_canvas = function(self, container) {

	// reset
		self.canvas_container = container
		container.replaceChildren()

	const print_root = ui.create_dom_element({
		element_type	: 'div',
		class_name		: 'print_root',
		parent			: container
	})
	self.print_root = print_root

	// v2 document-flow render (async): generates pages from layout.flow.rows and
	// paginates, then decorates with editor chrome. Callers don't await.
	// A generation token guards against stale decorate_editor calls when a new
	// render supersedes an in-flight one (rapid mutations / template switches).
	const ctx = make_editor_ctx(self, print_root)
	self._flow_ctx = ctx
	const gen = (self._render_gen = (self._render_gen || 0) + 1)
	layout_flow(self, ctx)
		.then(() => { if (gen === self._render_gen) decorate_editor(self) })
		.catch(e => console.error('tool_print render_canvas flow error', e))


	return print_root
}//end render_canvas



/**
* APPLY_BOX_STYLE
* Applies the box content styling (font, alignment, overflow) to its content node.
* @param object self
* @param object box
*/
export const apply_box_style = function(self, box) {
	const c = box.content_node
	if (!c) return
	const st	= box.style || {}
	const defs	= self.layout.style_defaults || {}
	c.style.fontSize	= (st.font_size_pt || defs.font_size_pt || 11) + 'pt'
	c.style.textAlign	= st.align || defs.align || 'left'
	c.style.fontFamily	= font_stack(st.font_family || defs.font_family)
	// text color (fixes the muted light-grey list rendering; per-box override)
	c.style.color		= st.text_color || defs.text_color || '#111111'
	// border: show/hide + color for the box frame and any table grid lines
	const border_show	= (st.border_show!==undefined) ? st.border_show : (defs.border_show!==false)
	const border_color	= st.border_color || defs.border_color || '#cccccc'
	c.style.setProperty('--tp_border_color', border_show ? border_color : 'transparent')
	c.classList.toggle('no_border', !border_show)
	// vertical align via flex
	const valign = st.valign || defs.valign || 'top'
	c.style.justifyContent = valign==='middle' ? 'center' : (valign==='bottom' ? 'flex-end' : 'flex-start')
	// overflow
	const mode = box.overflow?.mode || 'clip'
	c.style.overflow = (mode==='clip') ? 'hidden' : 'visible'
	// grow/flow: content sizes to itself so the box (min-height = rect.h) expands
	c.style.height = (mode==='grow' || mode==='flow') ? 'auto' : '100%'
	// component field label optional (default shown so the component is identifiable)
	c.classList.toggle('hide_label', box.show_label===false)
}//end apply_box_style



/**
* PARSE_DROP_DATA
* Reads + validates the palette drag payload from a drop event.
* @param event event
* @return object|null parsed payload ({drag_type:'add', ddo, path?}) or null
*/
const parse_drop_data = function(event) {
	let parsed
	try {
		parsed = JSON.parse(event.dataTransfer.getData('text/plain'))
	} catch (e) {
		console.error('tool_print on_drop: invalid drag data', e)
		return null
	}
	if (!parsed || parsed.drag_type!=='add' || !parsed.ddo) return null
	return parsed
}//end parse_drop_data




/**
* SET_ZOOM
* Updates the zoom factor and recomputes every page/box px from mm.
* @param object self
* @param number zoom
*/
export const set_zoom = function(self, zoom) {
	self.zoom = zoom
	if (self.canvas_container) render_canvas(self, self.canvas_container)
}//end set_zoom





// table column management (portal/relation boxes) ---------------------------

/**
* CURRENT_COLUMNS
* The box's current column descriptors (its table_columns, or the resolved
* defaults when not yet customized).
* @param object box
* @return object[]
*/
const current_columns = function(box) {
	return Array.isArray(box.table_columns)
		? box.table_columns
		: (Array.isArray(box.available_columns) ? box.available_columns.slice() : [])
}//end current_columns



/**
* APPLY_COLUMNS
* Sets the box columns and re-renders the canvas (a column change can alter
* pagination), then reselects the edited cell so the inspector stays on it.
* @param object self
* @param object box
* @param object[] cols
*/
const apply_columns = function(self, box, cols) {
	box.table_columns = cols
	self.mark_dirty?.()
	render_canvas(self, self.canvas_container)
	if (self.sel) requestAnimationFrame(() => select_cell(self, self.sel.row_id, self.sel.cell_id))
}//end apply_columns



/**
* ADD_TABLE_COLUMN
* Adds a dragged related component as a new table column (when it belongs to the
* portal's related section). Ignores duplicates and non-matching sections.
* @param object self
* @param object box
* @param object ddo - dragged component ddo {tipo, section_tipo, model, label}
* @return bool added
*/
export const add_table_column = function(self, box, ddo) {

	if (!box.component_ref || !is_relation_model(box.component_ref.model)) return false
	if (box.related_section_tipo && ddo.section_tipo && ddo.section_tipo!==box.related_section_tipo) return false

	const col = {
		type			: 'component',
		label			: ddo.label || ddo.tipo,
		tipo			: ddo.tipo,
		section_tipo	: ddo.section_tipo,
		model			: ddo.model
	}
	const current = current_columns(box)
	if (current.some(c => column_key(c)===column_key(col))) return true // already present

	apply_columns(self, box, [...current, col])
	return true
}//end add_table_column



/**
* REMOVE_TABLE_COLUMN
* Removes a column (by key) from the box table.
* @param object self
* @param object box
* @param string key - column_key
*/
export const remove_table_column = function(self, box, key) {
	apply_columns(self, box, current_columns(box).filter(c => column_key(c)!==key))
}//end remove_table_column



/**
* SET_COLUMN_WIDTH
* Sets (or clears) a column's fixed width in mm.
* @param object self
* @param object box
* @param string key - column_key
* @param number|null width - mm, or null/0 for auto
*/
export const set_column_width = function(self, box, key, width) {
	const w		= (width && width>0) ? width : null
	const cols	= current_columns(box).map(c => column_key(c)===key ? { ...c, width: w } : c)
	apply_columns(self, box, cols)
}//end set_column_width



/**
* SET_COLUMN_HEADER
* Overrides (or clears) a column's header text. Empty/blank → revert to the
* component's own label.
* @param object self
* @param object box
* @param string key - column_key
* @param string|null header - custom header text, or null to use the default label
*/
export const set_column_header = function(self, box, key, header) {
	const h		= (header!=null && header.trim()!=='') ? header : undefined
	const cols	= current_columns(box).map(c => {
		if (column_key(c)!==key) return c
		const next = { ...c }
		if (h===undefined) { delete next.header } else { next.header = h }
		return next
	})
	apply_columns(self, box, cols)
}//end set_column_header



/**
* MOVE_TABLE_COLUMN
* Reorders a table column one step left (dir -1) or right (dir +1).
* @param object self
* @param object box
* @param string key - column_key
* @param number dir - -1 | +1
*/
export const move_table_column = function(self, box, key, dir) {
	const cols	= current_columns(box).slice()
	const idx	= cols.findIndex(c => column_key(c)===key)
	if (idx===-1) return
	const ni = idx + dir
	if (ni < 0 || ni >= cols.length) return
	const moved = cols.splice(idx, 1)[0]
	cols.splice(ni, 0, moved)
	apply_columns(self, box, cols)
}//end move_table_column



/**
* REORDER_TABLE_COLUMN
* Moves the dragged column (from_key) to the position of the drop target column
* (to_key). Used by the inspector drag-and-drop reorder.
* @param object self
* @param object box
* @param string from_key - column_key of the dragged column
* @param string to_key - column_key of the drop target column
*/
export const reorder_table_column = function(self, box, from_key, to_key) {
	if (from_key===to_key) return
	const cols		= current_columns(box).slice()
	const from_idx	= cols.findIndex(c => column_key(c)===from_key)
	const to_idx	= cols.findIndex(c => column_key(c)===to_key)
	if (from_idx===-1 || to_idx===-1) return
	const moved = cols.splice(from_idx, 1)[0]
	cols.splice(to_idx, 0, moved)
	apply_columns(self, box, cols)
}//end reorder_table_column



/**
* ADD_DEFAULT_COLUMN
* Re-adds a default column (by key) that was previously removed.
* @param object self
* @param object box
* @param string key - column_key
*/
export const add_default_column = function(self, box, key) {
	const avail = Array.isArray(box.available_columns) ? box.available_columns : []
	const col = avail.find(c => column_key(c)===key)
	if (!col) return
	const current = current_columns(box)
	if (current.some(c => column_key(c)===key)) return
	apply_columns(self, box, [...current, col])
}//end add_default_column



// ============================================================================
// v2 DOCUMENT-FLOW EDITOR — model mutations, selection, drop, decorate
// ============================================================================

const flow_rows = (self) => (self.layout.flow && Array.isArray(self.layout.flow.rows)) ? self.layout.flow.rows : []

export const find_row = function(self, row_id) { return flow_rows(self).find(r => r.id===row_id) || null }
export const find_cell = function(self, row_id, cell_id) {
	const row = find_row(self, row_id)
	return (row && Array.isArray(row.cells)) ? (row.cells.find(c => c.id===cell_id) || null) : null
}//end find_cell

const equalize_widths = function(row) {
	const n = row.cells.length || 1
	row.cells.forEach(c => { c.width = 1 / n })
}//end equalize_widths

const rerender = function(self) {
	self.mark_dirty?.()
	render_canvas(self, self.canvas_container)
}//end rerender



/**
* SELECT_CELL
* Selects a cell (or a whole row when cell_id is null), highlights it and syncs
* the inspector with { row, cell }.
*/
export const select_cell = function(self, row_id, cell_id) {
	self.sel = row_id ? { row_id, cell_id: cell_id || null } : null
	highlight_selection(self)
	if (typeof self.sync_inspector==='function') {
		const row	= row_id ? find_row(self, row_id) : null
		const cell	= cell_id ? find_cell(self, row_id, cell_id) : null
		self.sync_inspector(row ? { row, cell } : null)
	}
}//end select_cell

const highlight_selection = function(self) {
	if (!self.print_root) return
	self.print_root.querySelectorAll('.flow_row.selected, .flow_cell.selected, .flow_continued.selected').forEach(n => n.classList.remove('selected'))
	const sel = self.sel
	if (!sel) return
	if (sel.cell_id) {
		const c = self.print_root.querySelector('.flow_cell[data-cell-id="' + sel.cell_id + '"]')
		if (c) c.classList.add('selected')
		// also mark the split-block continuation segments of the selected cell
		self.print_root.querySelectorAll('.flow_continued[data-master-cell-id="' + sel.cell_id + '"]').forEach(cont => cont.classList.add('selected'))
	} else if (sel.row_id) {
		self.print_root.querySelectorAll('.flow_row[data-row-id="' + sel.row_id + '"]').forEach(r => r.classList.add('selected'))
	}
}//end highlight_selection



// --- row / cell mutations ---------------------------------------------------

export const add_row = function(self, block) {
	const row = new_row(self, block ? [ new_cell(self, block, 1) ] : undefined)
	flow_rows(self).push(row)
	rerender(self)
	requestAnimationFrame(() => select_cell(self, row.id, row.cells[0].id))
	return row
}//end add_row

export const add_spacer = function(self) {
	flow_rows(self).push(new_spacer_row(self, 8))
	rerender(self)
}//end add_spacer

export const remove_row = function(self, row_id) {
	const rows = flow_rows(self)
	const i = rows.findIndex(r => r.id===row_id)
	if (i<0) return
	rows.splice(i, 1)
	if (self.sel && self.sel.row_id===row_id) self.sel = null
	rerender(self)
	self.sync_inspector?.(null)
}//end remove_row

export const move_row = function(self, from_id, to_id) {
	const rows = flow_rows(self)
	const fi = rows.findIndex(r => r.id===from_id)
	const ti = rows.findIndex(r => r.id===to_id)
	if (fi<0 || ti<0 || fi===ti) return
	const [m] = rows.splice(fi, 1)
	rows.splice(ti, 0, m)
	rerender(self)
}//end move_row

export const move_row_dir = function(self, row_id, dir) {
	const rows = flow_rows(self)
	const i = rows.findIndex(r => r.id===row_id)
	const ni = i + dir
	if (i<0 || ni<0 || ni>=rows.length) return
	const [m] = rows.splice(i, 1)
	rows.splice(ni, 0, m)
	rerender(self)
}//end move_row_dir

export const insert_row_after = function(self, row_id, block) {
	const rows = flow_rows(self)
	const i = rows.findIndex(r => r.id===row_id)
	const row = new_row(self, block ? [ new_cell(self, block, 1) ] : undefined)
	rows.splice(i<0 ? rows.length : i+1, 0, row)
	rerender(self)
	requestAnimationFrame(() => select_cell(self, row.id, row.cells[0].id))
	return row
}//end insert_row_after

export const insert_spacer_after = function(self, row_id) {
	const rows = flow_rows(self)
	const i = rows.findIndex(r => r.id===row_id)
	rows.splice(i<0 ? rows.length : i+1, 0, new_spacer_row(self, 8))
	rerender(self)
}//end insert_spacer_after

/**
* DELETE_SELECTION
* Removes the selected cell (or the whole row if no cell / last cell). Wired to
* the Delete key.
*/
export const delete_selection = function(self) {
	const sel = self.sel
	if (!sel) return
	if (sel.cell_id) { remove_cell(self, sel.row_id, sel.cell_id) }
	else { remove_row(self, sel.row_id) }
}//end delete_selection

/**
* RESIZE_CELLS
* Adjusts two adjacent cells' widths by a fraction delta (from a divider drag),
* keeping the row's total width constant. Re-renders.
*/
export const resize_cells = function(self, row_id, left_cell_id, delta_frac) {
	const row = find_row(self, row_id)
	if (!row || !Array.isArray(row.cells)) return
	const i = row.cells.findIndex(c => c.id===left_cell_id)
	if (i<0 || i>=row.cells.length-1) return
	const a = row.cells[i], b = row.cells[i+1]
	const min = 0.05
	let aw = (a.width||0) + delta_frac
	let bw = (b.width||0) - delta_frac
	if (aw<min) { bw -= (min-aw); aw = min }
	if (bw<min) { aw -= (min-bw); bw = min }
	a.width = aw; b.width = bw
	self.mark_dirty?.()
	render_canvas(self, self.canvas_container)
	requestAnimationFrame(() => { if (self.sel) select_cell(self, self.sel.row_id, self.sel.cell_id) })
}//end resize_cells

export const add_cell = function(self, row_id) {
	const row = find_row(self, row_id)
	if (!row || row.kind!=='row') return
	row.cells.push(new_cell(self))
	equalize_widths(row)
	rerender(self)
}//end add_cell

export const remove_cell = function(self, row_id, cell_id) {
	const row = find_row(self, row_id)
	if (!row || !Array.isArray(row.cells)) return
	if (row.cells.length<=1) { remove_row(self, row_id); return }
	const i = row.cells.findIndex(c => c.id===cell_id)
	if (i<0) return
	row.cells.splice(i, 1)
	equalize_widths(row)
	rerender(self)
}//end remove_cell

export const set_cell_width = function(self, row_id, cell_id, frac) {
	const cell = find_cell(self, row_id, cell_id)
	if (!cell) return
	cell.width = Math.max(0.05, Math.min(1, frac))
	rerender(self)
}//end set_cell_width

export const set_cell_block = function(self, row_id, cell_id, block) {
	const cell = find_cell(self, row_id, cell_id)
	if (!cell) return
	cell.block = block
	rerender(self)
	requestAnimationFrame(() => select_cell(self, row_id, cell_id))
}//end set_cell_block

export const set_row_space_after = function(self, row_id, mm) {
	const row = find_row(self, row_id)
	if (!row) return
	row.space_after_mm = Math.max(0, mm || 0)
	rerender(self)
}//end set_row_space_after



// --- decorate the rendered flow with editor chrome + listeners --------------

/**
* DECORATE_EDITOR
* Adds selection / drag-reorder / drop chrome to the rendered flow rows + cells.
* Run after layout_flow resolves (continuation segments are left read-only).
* @param object self
*/
export const decorate_editor = function(self) {
	if (!self.print_root) return
	self.print_root.classList.add('editor')
	wire_flow_keys(self)

	const mk = (cls, html, title, parent, onclick) => {
		const b = ui.create_dom_element({ element_type:'span', class_name:'rc_btn no_print ' + cls, inner_html:html, parent })
		if (title) b.title = title
		if (onclick) b.addEventListener('click', (e) => { e.stopPropagation(); onclick(e) })
		return b
	}

	// rows (master segments only) ------------------------------------------------
	self.print_root.querySelectorAll('.flow_row[data-row-id]:not(.flow_continued)').forEach(row_node => {
		const row_id	= row_node.dataset.rowId
		const row		= find_row(self, row_id)
		const is_spacer	= row && row.kind==='spacer'

		if (!row_node.querySelector('.row_chrome')) {
			// left chrome: drag handle + up/down reorder
			const left = ui.create_dom_element({ element_type:'div', class_name:'row_chrome row_chrome_left no_print', parent: row_node })
			const handle = mk('rc_grip', '⋮⋮', 'Drag to reorder · click to select row', left, () => select_cell(self, row_id, null))
			handle.draggable = true
			handle.addEventListener('dragstart', (e) => { e.dataTransfer.effectAllowed='move'; e.dataTransfer.setData('text/plain','row:'+row_id); row_node.classList.add('dragging') })
			handle.addEventListener('dragend', () => row_node.classList.remove('dragging'))
			mk('rc_up', '▲', 'Move up', left, () => move_row_dir(self, row_id, -1))
			mk('rc_down', '▼', 'Move down', left, () => move_row_dir(self, row_id, +1))

			// right chrome: +cell (rows only) + remove row
			const right = ui.create_dom_element({ element_type:'div', class_name:'row_chrome row_chrome_right no_print', parent: row_node })
			if (!is_spacer) mk('rc_addcell', '＋', 'Add cell', right, () => add_cell(self, row_id))
			mk('rc_remove', '✕', 'Remove row', right, () => remove_row(self, row_id))

			// below-row insert bar: + row / + spacer
			const below = ui.create_dom_element({ element_type:'div', class_name:'row_insert no_print', parent: row_node })
			mk('ri_row', '＋ row', 'Insert row below', below, () => insert_row_after(self, row_id))
			mk('ri_spacer', '＋ spacer', 'Insert spacer below', below, () => insert_spacer_after(self, row_id))
		}

		// spacer rows: bottom drag handle to set the height
		if (is_spacer && !row_node.querySelector('.spacer_resize')) {
			const sr = ui.create_dom_element({ element_type:'div', class_name:'spacer_resize no_print', parent: row_node })
			sr.title = 'Drag to resize spacer height'
			sr.addEventListener('mousedown', (e) => start_spacer_drag(self, e, row_node, row_id))
		}

		// row-level drop = reorder (only acts on a 'row:' payload)
		row_node.addEventListener('dragover', (e) => { e.preventDefault(); e.dataTransfer.dropEffect = 'move'; row_node.classList.add('row_drop') })
		row_node.addEventListener('dragleave', (e) => { if (e.target===row_node) row_node.classList.remove('row_drop') })
		row_node.addEventListener('drop', (e) => {
			row_node.classList.remove('row_drop')
			const raw = e.dataTransfer.getData('text/plain') || ''
			if (!raw.startsWith('row:')) return
			e.preventDefault(); e.stopPropagation()
			move_row(self, raw.slice(4), row_id)
		})

		// cell dividers (drag to resize) — between each adjacent cell pair
		const cells = [...row_node.querySelectorAll(':scope > .flow_cell')]
		for (let i = 0; i < cells.length - 1; i++) {
			const left_id = cells[i].dataset.cellId
			const divider = ui.create_dom_element({ element_type:'div', class_name:'cell_divider no_print', parent: cells[i] })
			divider.title = 'Drag to resize cells'
			divider.addEventListener('mousedown', (e) => start_divider_drag(self, e, row_node, cells[i], cells[i+1], row_id, left_id))
		}
	})

	// cells: click to select, drop a palette component to fill, remove icon ------
	self.print_root.querySelectorAll('.flow_cell[data-cell-id]').forEach(cell_node => {
		if (cell_node.closest('.flow_continued')) return
		const row_id	= cell_node.dataset.rowId
		const cell_id	= cell_node.dataset.cellId
		cell_node.addEventListener('click', (e) => { e.stopPropagation(); select_cell(self, row_id, cell_id) })
		cell_node.addEventListener('dragenter', (e) => e.preventDefault())
		cell_node.addEventListener('dragover', (e) => { e.preventDefault(); e.stopPropagation(); e.dataTransfer.dropEffect = 'move'; cell_node.classList.add('cell_drop') })
		cell_node.addEventListener('dragleave', (e) => { if (e.target===cell_node) cell_node.classList.remove('cell_drop') })
		cell_node.addEventListener('drop', (e) => {
			cell_node.classList.remove('cell_drop')
			const raw = e.dataTransfer.getData('text/plain') || ''
			if (raw.startsWith('row:')) return
			e.preventDefault(); e.stopPropagation()
			const parsed = parse_drop_data(e)
			if (!parsed) return
			// drop INTO a table cell: a field of the table's related section is added
			// as a COLUMN; anything else naturally replaces the cell (add_table_column
			// returns false for a non-matching section → fall through to replace).
			const cell	= find_cell(self, row_id, cell_id)
			const b		= cell && cell.block
			const is_table = !!(b && b.type==='component' && b.component_ref && is_relation_model(b.component_ref.model))
			if (is_table && add_table_column(self, b, parsed.ddo)) return
			set_cell_block(self, row_id, cell_id, component_block(parsed))
		})
		if (!cell_node.querySelector('.cell_remove')) {
			mk('cell_remove', '✕', 'Remove cell', cell_node, () => remove_cell(self, row_id, cell_id))
		}
	})

	// each generated page is a drop target → append a row at the bottom of the flow
	self.print_root.querySelectorAll('.flow_column').forEach(col => {
		col.addEventListener('dragover', (e) => { e.preventDefault(); e.dataTransfer.dropEffect = 'move'; col.classList.add('col_drop') })
		col.addEventListener('dragleave', (e) => { if (e.target===col) col.classList.remove('col_drop') })
		col.addEventListener('drop', (e) => {
			col.classList.remove('col_drop')
			if (e.target.closest('.flow_cell')) return   // a cell handled it
			const raw = e.dataTransfer.getData('text/plain') || ''
			if (raw.startsWith('row:')) return
			e.preventDefault()
			const parsed = parse_drop_data(e)
			if (parsed) add_row(self, component_block(parsed))
		})
	})

	// continuation segments (a split table/text on later pages) select their
	// master cell on click, so a table whose bulk paginated away is still editable
	self.print_root.querySelectorAll('.flow_continued[data-master-cell-id]').forEach(cont => {
		cont.classList.add('continued_selectable')
		cont.style.cursor = 'pointer'
		cont.title = 'Part of a split block — click to edit its properties'
		cont.addEventListener('click', (e) => {
			e.stopPropagation()
			select_cell(self, cont.dataset.masterRowId, cont.dataset.masterCellId)
			const master = self.print_root.querySelector('.flow_row[data-row-id="' + cont.dataset.masterRowId + '"]:not(.flow_continued)')
			master?.scrollIntoView({ block:'nearest', behavior:'smooth' })
		})
	})

	highlight_selection(self)
}//end decorate_editor



/**
* START_DIVIDER_DRAG
* Live cell-resize drag: previews widths during the drag, commits on mouseup.
*/
const start_divider_drag = function(self, e, row_node, a_node, b_node, row_id, left_cell_id) {
	e.preventDefault(); e.stopPropagation()
	const row_w		= row_node.getBoundingClientRect().width
	const start_x	= e.clientX
	const aw0		= a_node.getBoundingClientRect().width
	const bw0		= b_node.getBoundingClientRect().width
	const min		= 0.05 * row_w
	document.body.classList.add('tp_col_resizing')

	const on_move = (me) => {
		let aw = aw0 + (me.clientX - start_x)
		let bw = bw0 - (me.clientX - start_x)
		if (aw<min) { bw -= (min-aw); aw = min }
		if (bw<min) { aw -= (min-bw); bw = min }
		a_node.style.flex = '0 0 ' + aw + 'px'; a_node.style.maxWidth = aw + 'px'
		b_node.style.flex = '0 0 ' + bw + 'px'; b_node.style.maxWidth = bw + 'px'
	}
	const on_up = () => {
		document.removeEventListener('mousemove', on_move)
		document.removeEventListener('mouseup', on_up)
		document.body.classList.remove('tp_col_resizing')
		const delta_frac = (a_node.getBoundingClientRect().width - aw0) / row_w
		resize_cells(self, row_id, left_cell_id, delta_frac)
	}
	document.addEventListener('mousemove', on_move)
	document.addEventListener('mouseup', on_up)
}//end start_divider_drag



/**
* START_SPACER_DRAG
* Live spacer-height drag: previews on mousemove, commits row.height_mm on mouseup.
*/
const start_spacer_drag = function(self, e, row_node, row_id) {
	e.preventDefault(); e.stopPropagation()
	const ctx		= self._flow_ctx
	const px_per_mm	= (ctx && typeof ctx.to_px==='function') ? ctx.to_px(1) : (96 / 25.4)
	const start_y	= e.clientY
	const start_h	= row_node.getBoundingClientRect().height
	document.body.classList.add('tp_row_resizing')

	const on_move = (me) => {
		const h = Math.max(px_per_mm, start_h + (me.clientY - start_y))
		row_node.style.height = h + 'px'
	}
	const on_up = () => {
		document.removeEventListener('mousemove', on_move)
		document.removeEventListener('mouseup', on_up)
		document.body.classList.remove('tp_row_resizing')
		const row = find_row(self, row_id)
		if (row) {
			const mm = row_node.getBoundingClientRect().height / px_per_mm
			row.height_mm = Math.max(1, Math.round(mm * 10) / 10)
			self.mark_dirty?.()
			render_canvas(self, self.canvas_container)
			requestAnimationFrame(() => select_cell(self, row_id, null))
		}
	}
	document.addEventListener('mousemove', on_move)
	document.addEventListener('mouseup', on_up)
}//end start_spacer_drag



/**
* WIRE_FLOW_KEYS
* Global keydown: Delete/Backspace removes the selected cell/row (unless typing
* in a field). Wired once; the listener is stored on self._flow_key_handler so
* on_close_actions can remove it.
*/
const wire_flow_keys = function(self) {
	if (self._flow_key_handler) return
	const handler = (e) => {
		if (e.key!=='Delete' && e.key!=='Backspace') return
		const t = e.target
		if (t && (t.tagName==='INPUT' || t.tagName==='TEXTAREA' || t.tagName==='SELECT' || t.isContentEditable)) return
		if (!self.sel) return
		e.preventDefault()
		delete_selection(self)
	}
	self._flow_key_handler = handler
	document.addEventListener('keydown', handler)
}//end wire_flow_keys



/**
* SERIALIZE_LAYOUT
* Produces a clean, DOM-free copy of the layout blob for persistence.
* Strips transient node/instance pointers attached during rendering.
* @param object self
* @return object blob
*/
export const serialize_layout = function(self) {

	const l = self.layout
	const rows = (l.flow && Array.isArray(l.flow.rows)) ? l.flow.rows : []

	return {
		schema_version		: SCHEMA_VERSION,
		kind				: 'tool_print_layout',
		uid					: l.uid || l.id || null,
		name				: l.name,
		target_section_tipo	: l.target_section_tipo,
		visibility			: l.visibility || 'user',
		owner_user_id		: l.owner_user_id || ('' + page_globals.user_id),
		units				: 'mm',
		page_defaults		: l.page_defaults,
		grid				: l.grid,
		style_defaults		: l.style_defaults,
		flow				: { rows: rows.map(serialize_row) }
	}
}//end serialize_layout



/**
* SERIALIZE_ROW
* @param object row
* @return object plain row (DOM-free)
*/
const serialize_row = function(row) {
	if (row.kind==='spacer') {
		return { id: row.id, kind: 'spacer', height_mm: row.height_mm || 8 }
	}
	return {
		id				: row.id,
		kind			: 'row',
		space_after_mm	: row.space_after_mm || 0,
		style			: row.style || {},
		cells			: (Array.isArray(row.cells) ? row.cells : []).map(serialize_cell)
	}
}//end serialize_row



/**
* SERIALIZE_CELL
* @param object cell
* @return object plain cell (DOM-free)
*/
const serialize_cell = function(cell) {
	return {
		id		: cell.id,
		width	: (typeof cell.width==='number') ? cell.width : 1,
		block	: serialize_block(cell.block || { type: 'empty' })
	}
}//end serialize_cell



/**
* SERIALIZE_BLOCK
* A cell's content (component / static text / empty). Strips transient render
* state (the _table_render cache, node pointers).
* @param object block
* @return object plain block
*/
const serialize_block = function(block) {
	if (!block || block.type==='empty') return { type: 'empty' }
	if (block.type==='static_text') {
		return { type: 'static_text', static: block.static || { text: '' }, style: block.style || {} }
	}
	return {
		type				: 'component',
		component_ref		: block.component_ref || null,
		path				: block.path || null,
		show_label			: block.show_label!==false,
		show_table_header	: block.show_table_header!==false,
		table_columns		: Array.isArray(block.table_columns) ? block.table_columns : null,
		render				: block.render || null,
		style				: block.style || {}
	}
}//end serialize_block



// @license-end
