<?php

	# VISUALIZADOR HTML	


	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 		$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_relation'])) 		$ar_css['css_relation']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 	$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))	$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_relation']))	$ar_css['css_wrap_relation']='';
	


	# WRAP
	print "\n<!-- RELATION EDIT [current_tipo_section:$current_tipo_section section_name:$section_name] -->";

	
	print "\n<div class=\"css_wrap_relation wrap_component {$ar_css['css_wrap_relation']}\" id=\"{$id_wrapper}\" 
	data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-section_tipo=\"{$section_tipo}\" data-parent=\"{$parent}\" data-modo=\"{$modo}\" data-dato=\"{$dato_string}\" 
	data-current_tipo_section=\"{$current_tipo_section}\" data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}' >";


	# CONTENIDO
	$html_contenido = '';
	

	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> No access here (relation)! </span>";
					break;
		
						
		case ($permissions>=1)	:

					# DIV CON EL LISTADO DE REGISTROS (SECTION LIST MODO RELATION) RELACIONADOS DECORADOS POR UN SECTION_GROUP
					$html_contenido .= "\n $section_group_html ";					
	}



	# Prepare content to show in page
	tools::prepare_content($html_contenido);	
	

	print  $html_contenido;



	print "\n</div><!-- /css_wrap_relation -->\n\n"; //relation_wrapper

?>