<?php

	# VISUALIZADOR HTML	

	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	$html_contenido .= "\n<div class=\"css_section_group_content tab_content component_relation_selector_div\" data-caller_id=\"{$caller_id}\" >";

	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> No access here (relation)! </span>";
					break;
						
		case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\">$dato</span>";
					break;	
						
		case ($permissions>=2)	:					

					#$html_contenido .= "\n <div>" . label::get_label('sections') ."</div>";
					$html_contenido .= "\n <ul> ";
					
						foreach($ar_sections as $tipo_section => $value) {

						  $html_contenido .= "\n <li>";
							
							$html_contenido .= "\n <a href=\"javascript:void(0)\" class=\"open_section_link text_shadow_inset\" title=\"$parent - $tipo_section - $tipo - $caller_id - $section_tipo\"
							onclick=\"tool_relation.open_section_link(this)\"
							data-tipo=\"{$tipo_section}\" data-caller_tipo=\"{$tipo}\" >";
							$html_contenido .= "$value";
							$html_contenido .= "\n</a>";
							if(SHOW_DEBUG===true) {
							$html_contenido .= " <span class=\"debug_info\">[$tipo_section]</span>";
							}
							
						  $html_contenido .= "\n </li>";
						}

					$html_contenido .= "\n </ul> ";
	}

	$html_contenido .= "\n</div>";
	
		#dump($html_contenido);

	print $html_contenido;


	/*
	# Preparamos el contenido html para no tener problemas con javascript
	$html_contenido 		= str_replace(array("\n","\r","  "),' ',$html_contenido);
	$html_contenido 		= addslashes($html_contenido);
	$html_contenido_json 	= json_encode($html_contenido, JSON_UNESCAPED_UNICODE);

	# Coloca el resultado html en el inspector	
	print '	<script>
			$(function(event) {				
				if ($("#inspector_relations").length>0) {
					$("#inspector_relations").html( '.$html_contenido_json.' );					
				}
				//alert("pasado content from '.$id.' ")			
			})
			</script>';
	*/	
	
?>