<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 		$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_relation'])) 		$ar_css['css_relation']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 	$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))	$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_relation']))	$ar_css['css_wrap_relation']='';
	
	if(!isset ($tools_html))					$tools_html='';
	
	
	echo "\n<!-- RELATION [tipo:$tipo id_matrix:$id] -->";
	echo "\n<div class=\"css_wrap_relation {$ar_css['css_wrap_relation']}\" >";
	
	# ETIQUETA (LABEL)
	#$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> No access here (relation_list)! </span>";
					break;
						
		case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\">$dato</span>";
					break;	
						
		case ($permissions>=2)	:
		
					$html_contenido .= "";
					/*
					if(is_array($ar_etiquetas_de_los_campos)) foreach ($ar_etiquetas_de_los_campos as $etiqueta_campo){
						$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\">$etiqueta_campo</span>";
					}
					*/
					$html_contenido .= " Working in this visualizer (relation list) ...";	
					/*	
					if(is_array($ar_components)) foreach ($ar_components as $parent_id => $ar_obj){
						
						$html_contenido .= "";
						//print_r ($ar_obj);
							if ($link)(
								
								$html_contenido .= "<img class=\"css_edit_icon\" />"
								
								);
							foreach ($ar_obj as $obj){
							
								$html_contenido .= $obj->get_html();
								$html_contenido .= "<br>";
								
						}
					}
					*/
					//$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\">$dato</span>";
					//$html_contenido .= "\n <input class=\"css_input_text {$ar_css['css_relation']}\" type=\"text\" name=\"{$tipo}\" data-tipo=\"{$tipo}\" id=\"{$id}\" value=\"{$dato}\" title=\"$html_title\" />";
		
					#$html_contenido .= $tools_html;
					//$html_contenido .= "\n <span  class=\"css_span_ejemplo {$ar_css['css_span_ejemplo']}\">$ejemplo</span>";
						
			if($permissions==3)
					
					$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$debugger}</span>";	
					
					
	}
	
	
	# PRINT HTML
	#print $html_label;
	print $html_contenido;
	#print $html_tools;
	
	
	echo "\n</div>\n\n"; //wrap
?>