<?php


	#
	# Tables info 
	echo "<h2>Tables info</h2>";
	echo "<pre>";
	print_r($tables_info,false);
	echo "</pre>";


	#
	# Records info
	echo "<h2>Publication schema [source_table] [column] => target_table</h2>";
	echo "<pre>";
	print_r($publication_schema,false);
	echo "</pre>";


	#
	# Records info
	echo "<h2>Records of table: $table</h2>";
	echo "<blockquote>";

	#
	# SEARCH_DATA_RECORDS
	# Records iteration generate 'rows' as objects 
	foreach ($search_data_records->result as $row) {

		$row = (object)$row; # Convert to object for easy access
		
		# String
		# TITULO String
		$titulo = 'ID '.$row->section_id;
		if(isset($row->titulo)) {
			$titulo = "[$row->section_id] ".$row->titulo;
		}
		echo "<h3>$titulo</h3>";

			#dump($row, '$row info '.to_string());
			/**/
			echo "<pre>";
			print_r($row,false);
			echo "</pre>";
			

		# RESUMEN String
		if(isset($row->resumen)) {
			$resumen = $row->resumen;
			echo "<div>$resumen</div>";
		}
		
		#echo "<hr>";

	}//end foreach ($search_data_records->result as $row)

	echo "</blockquote>";


	#
	# Terms of reel
	echo "<h2>Terms of reel: $av_section_id</h2>";
	echo "<blockquote>";
	
		echo "<pre>";
		print_r($search_data_reel_terms->result);
		echo "</pre>";

	echo "</blockquote>";


	#
	# Terms of reel
	echo "<h2>Fragment for locator: </h2>";
	echo "<blockquote>";
	
		echo $locator;
		echo "<pre>";
		if (isset($search_data_fragment_from_index_locator->result)) {
			print_r($search_data_fragment_from_index_locator->result);
		}else{
			echo "Not found locator data";
		}	
		echo "</pre>";

	echo "</blockquote>";
	


	if(SHOW_DEBUG===true && isset($search_data_records->debug->total_time)) {
		echo "<div>Dedalo public API request total time: ".$search_data_records->debug->total_time." secs from ".JSON_TRIGGER_URL."</div>";
	}
?>