<?php

	# VISUALIZADOR HTML	
	
	print "<div class=\"css_wrap_calculation\" id=\"wrap_{$tipo}\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato='".json_encode($dato)."' ";
	print ">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch(true) {
			
		case $permissions===0 :	
				$html_contenido .= "";
				break;
						
		case $permissions>=1 :
		
				$html_contenido .= "<input class=\"css_calculation\" type=\"text\" ";
				$html_contenido .= "name=\"{$tipo}\" ";
				$html_contenido .= "data-tipo=\"{$tipo}\" ";
				$html_contenido .= "value=\"{$dato}\" title=\"$html_title\" />";											
	}

	# Prepare content to show in page
	tools::prepare_content($html_contenido);	
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "</div>"; //wrap
?>