<?php
/*
	
	This single element is every thumbnail that appears bellow the video icon when user click's.
	Compound the filmstrip of video links of current selected term

*/
$html = '';

#
# ICON IMAGE
#$image_url = Tools::get_image_from_fotoURL( $image_url, $image_w=146, $image_h=100  );

/*
if (empty($image_url)) {
	$no_image = 'bg_foto_search_free.png';
	$image_url  = __WEB_ROOT_WEB."/images/$no_image"; 
}else{
	$image_url = __WEB_ROOT_WEB."/inc/img.php?s=".$image_url."&fx=crop&w=146&h=100";
}
*/
$style = !empty($image_url) ? "background-image: url('$image_url');" : null;
#$style = '';

// common.open_shadowbox(this,{"m":"free","av_section_id":"1","word":"casa","match":1})
#$js = "common.open_shadowbox(this,{\"m\":\"thematic\",\"av_section_id\":\"1\",\"word\":\"casa\",\"match\":1});";

# ICON LINK
$html .= "<a href=\"javascript:;\" ";
$html .= "id=\"indexation_node_{$node_id}_{$term_id}\" ";
$html .= "class=\"indexation_node_link\" ";
$html .= "style=\"$style\" ";
$html .= "rel=\"tooltip\" ";
$html .= "title=\"".tstring('ver_video')."\" ";
#$html .= "onclick=\"common.open_fr_window_tesauro(this)\" ";
$html .= "onclick=\"tpl_common.load_video_search_thematic(this)\" ";
#$html .= $js;
$html .= "data-term_id='$term_id' ";
$html .= "data-term=\"" . $term . "\" ";
$html .= "data-locator='".$locator_json."' ";
$html .= "data-locator_key='0' ";
$html .= ">";
#$html .= "	<img class=\"indexation_node_image\" src=\"$image_url\" />";
if(SHOW_DEBUG) {
	$html .= " <h2>$node_id</h2>";
	$html .= " <span>".count($interview_locators)."</span>";
}
$html .= " </a>";

echo $html ;