<?php

	# VISUALIZADOR HTML
	/*
	
	print "\n<!-- SECURITY AREAS (CHECK BOX) [tipo:$tipo section_id_matrix:$parent] -->";
	print "\n<div class=\"css_wrap_component_security_areas wrap_component\" 
	data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-modo=\"{$modo}\" data-dato=\"{$dato_string}\" data-component_name=\"{$component_name}\" >";

	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." (component security areas) $valor</span>"; 
					break;
						
		case 1	: 	
					$html_contenido .= "\n <div class=\"security_areas_tree\">";
					$html_contenido .= $html_tree;
					$html_contenido .= "\n </div>";

					break;	
						
		case ($permissions>=2)	:
					
					$html_contenido .= "\n <div class=\"security_areas_tree\">";
					$html_contenido .= $html_tree;
					$html_contenido .= "\n </div>";
					
					#$html_contenido .= "\n <span class=\"css_span_log\"></span>";										
					#$html_contenido .= "\n <span  class=\"css_span_ejemplo\">$ejemplo</span>";
							
					if(SHOW_DEBUG) {
						#$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
					}
					break;
		
	}
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div>\n\n"; //wrap
	*/
?>