<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 			$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_check_box'])) 			$ar_css['css_check_box']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 		$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))		$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_check_box']))		$ar_css['css_wrap_check_box']='';
	if(!isset ($ar_css['css_check_box_rotulo']))	$ar_css['css_check_box_rotulo']='';
	
	if(!isset ($tools_html))						$tools_html='';
	
	if(isset($_REQUEST[$tipo]))						$dato = $_REQUEST[$tipo];		#var_dump($_REQUEST[$tipo]);
	
	
	print "\n<!-- SECURITY AREAS (CHECK BOX) [tipo:$tipo id_matrix:$id] -->";
	print "\n<div class=\"css_wrap_check_box {$ar_css['css_check_box_rotulo']}\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." (checkbox)</span>"; 
					break;
						
		case ($permissions>=1)	:
		
					if (is_array ($ar_list_of_values)) foreach ($ar_list_of_values as $value => $rotulo) {
						
						if( is_array($dato) && in_array($value,$dato) ) {
							$checked = 'checked="checked"';
						}else {
							$checked = "";
						}
						$html_contenido .= "\n <input class=\"css_check_box {$ar_css['css_check_box']}\" type=\"checkbox\" name=\"{$tipo}[]\" data-tipo=\"{$tipo}\" value=\"{$value}\" id=\"{$id}\" title=\"$html_title\" $checked />";						
						$html_contenido .= "\n <label class=\"css_check_box_rotulo {$ar_css['css_check_box_rotulo']}\" $required >$rotulo</label>";	
					}					
										
							
	}
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div>\n\n"; //wrap
?>