<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 			$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_check_box'])) 			$ar_css['css_check_box']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 		$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))		$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_check_box']))		$ar_css['css_wrap_check_box']='';
	if(!isset ($ar_css['css_check_box_rotulo']))	$ar_css['css_check_box_rotulo']='';
	
	if(!isset ($tools_html))						$tools_html='';
	
	
	print "\n<!-- SECURITY AREAS (CHECK BOX) [tipo:$tipo section_id_matrix:$parent] -->";
	print "\n<div class=\"css_wrap_check_box {$ar_css['css_check_box_rotulo']}\" data-section_tipo=\"{$section_tipo}\" data-section_id_matrix=\"{$parent}\" data-tipo=\"{$tipo}\">";
	
	# ETIQUETA (LABEL)
	#$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." (check_box_list)</span>"; 		
					break;	
						
		case ($permissions>=1)	:
		
					
					$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\">$valor</span>";				
					
		
			if($permissions==3)
		
					$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
												
	}
	
	
	# PRINT HTML
	#print $html_label;
	print $html_contenido;
	#print $html_tools;
	
	
	echo "\n</div>\n\n"; //wrap
?>