<?php

	# VISUALIZADOR HTML	

	
	print "\n<!-- SECURITY AREAS (CHECK BOX) [tipo:$tipo section_id_matrix:$parent] -->";
	print "\n<div class=\"css_component_security_areas\" id=\"wrap_{$identificador_unico}\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= ''; 		
					break;
						
		case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato\">$dato</span>";
					break;	
						
		case ($permissions>=2)	:
		
					if (is_array ($ar_list_of_values)) foreach ($ar_list_of_values as $value => $rotulo) {
						
						if( is_array($dato) && in_array($value,$dato) ) {
							$checked = 'checked="checked"';
						}else {
							$checked = "";
						}
						$html_contenido .= "\n <input class=\"css_component_security_areas\" type=\"checkbox\" 
						name=\"{$tipo}_{$parent}_tm\"
						data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-flag=\"component_security_areas\" 
						value=\"{$value}\"
						title=\"$html_title\" 						
						$checked 
						disabled />";						
						
						$html_contenido .= "\n <label class=\"css_component_security_areas_rotulo\" $required >$rotulo</label>";
					}
					
					//$html_contenido .= "\n <span  class=\"css_span_ejemplo\">$ejemplo</span>";
						
					if($permissions==3){
						$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
					}
					break;
							
	}
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	echo "\n</div>\n\n"; //wrap
?>