<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 							$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_component_security_areas'])) 			$ar_css['css_component_security_areas']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 						$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))						$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_component_security_areas']))		$ar_css['css_wrap_component_security_areas']='';
	if(!isset ($ar_css['css_component_security_areas_rotulo']))		$ar_css['css_component_security_areas_rotulo']='';
	
	
	#print "\n<!-- SECURITY AREAS (CHECK BOX) [tipo:$tipo section_id_matrix:$parent] -->";
	#print "\n<div class=\"css_component_security_areas {$ar_css['css_component_security_areas_rotulo']}\" >";
	
	# ETIQUETA (LABEL)
	#$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	#dump($permissions'permissions');
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." (component security areas) $valor</span>"; 
					break;
						
		case ($permissions>=1)	:
		
					$html_contenido .= "<div class=\"security_areas_list_div\" >";
					
					if(isset($ar_authorized_areas_for_user_as_list)) {

						if(is_array($ar_authorized_areas_for_user_as_list)) foreach ($ar_authorized_areas_for_user_as_list as $tipo => $area_name) {

							$html_contenido .= "$area_name ";
							$html_contenido .= "<br>";
						}else{
							
							$html_contenido .= "$ar_authorized_areas_for_user_as_list ";
						}	
					}
					
					#$html_contenido .= $this->get_valor();
					$html_contenido .= "</div>";
										
	}
	
	# PRINT HTML
	#print $html_label;
	print $html_contenido;
	
	
	#print "\n</div>\n\n"; //wrap
?>