<?php
/*
	# VISUALIZADOR HTML	
		
	
	print "\n<!-- SECURITY AREAS (CHECK BOX) [tipo:$tipo section_id_matrix:$parent] -->";

	print "\n<div class=\"wrap_component css_wrap_check_box wrap_component_{$tipo}\"
	data-section_tipo=\"{$section_tipo}\"
	data-section_id_matrix=\"{$parent}\"
	data-tipo=\"{$tipo}\">";
	
	# ETIQUETA (LABEL)
	#$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	
				$html_contenido .= "";
				break;	
						
		case ($permissions>=1) :		
					
				$html_contenido .= "\n <span class=\"css_span_dato\">$valor</span>";				
					
		
				if(SHOW_DEBUG) {
					$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\">{$debugger}</span>";
				}
				beak;				
												
	}
	
	
	# PRINT HTML
	#print $html_label;
	print $html_contenido;
	
	echo "\n</div>\n\n"; //wrap
	*/
?>