<?php

	# VISUALIZADOR HTML	
	
	print "\n<!-- SECURITY AREAS (CHECK BOX) [tipo:$tipo section_id_matrix:$parent] -->";

	print "\n<div class=\"wrap_component css_wrap_component_security_areas wrap_component_{$tipo}\" 
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-parent=\"{$parent}\"
	data-section_tipo=\"{$section_tipo}\"
	data-modo=\"{$modo}\"
	data-dato=\"\"
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";

	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:

				$html_contenido .= "No access here"; 
				break;
						
		case ($permissions>=1):

				
				$html_contenido .= "\n <div class=\"security_areas_tree\">";

				$max_input_vars = ini_get("max_input_vars");
				if ($max_input_vars<2000) {
					$html_contenido .= "<div class=\"error\">PHP directive 'max_input_vars' is too small ($max_input_vars).
					This can truncate your data when manage big structures with thousands of elements.<br>
					Please configure your instalation with max_input_vars value with 2000 or higher to use security access safely</div>";
				}
				
				$html_contenido .= $html_tree;
				$html_contenido .= "\n </div>";	
	
				if(SHOW_DEBUG) {
					#$html_contenido .= "\n <span id=\"debugger_{$tipo}\" class=\"css_span_debugger\">{$debugger}</span>";	
				}
				break;							
	}

	# Prepare content to show in page
	tools::prepare_content($html_contenido);
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div>\n\n"; //wrap


	echo "<script>
			component_security_areas.update_area_childrens_obj_opened();
			component_security_areas.update_area_access_obj_opened();
		</script>"


?>