<?php

	# VISUALIZADOR HTML
	
	
	print "\n<!-- SECURITY AREAS (CHECK BOX) [tipo:$tipo section_id_matrix:$parent] -->";
	print "\n<div class=\"css_wrap_component_security_areas wrap_component\" 
	data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-modo=\"{$modo}\" data-dato=\"{$dato_string}\" data-component_name=\"{$component_name}\" >";

	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." (component security areas) $valor</span>"; 
					break;
						
		case 1	: 	/*
					foreach ($ar_list_of_values->result as $value => $rotulo) {
						
						if( is_array($dato) && in_array($value,$dato) ) {
							$checked = 'checked="checked"';
						}else {
							$checked = "";
						}
						$html_contenido .= "\n <input class=\"css_component_security_areas\" type=\"checkbox\" name=\"{$tipo}\" 
						data-tipo=\"{$tipo}\" value=\"{$value}\" id=\"{$id}\" title=\"$html_title\" data-flag=\"component_security_areas\" $checked  disabled />";						
						$html_contenido .= "\n <label class=\"css_component_security_areas_rotulo\" $required >$rotulo</label>";	
					}
					*/
					$html_contenido .= "\n <div class=\"security_areas_tree\">";
					$html_contenido .= $html_tree;
					$html_contenido .= "\n </div>";

					break;	
						
		case ($permissions>=2)	:
					/*
					foreach ($ar_list_of_values->result as $value => $rotulo) {
						
						if( is_array($dato) && in_array($value,$dato) ) {
							$checked = 'checked="checked"';
						}else {
							$checked = "";
						}
						$html_contenido .= "\n <input class=\"css_component_security_areas\" type=\"checkbox\" 
						name=\"{$tipo}_{$id}\"
						data-tipo=\"{$tipo}\" data-id_matrix=\"{$id}\" data-lang=\"{$lang}\" data-flag=\"component_security_areas\" 
						value=\"{$value}\"
						title=\"$html_title\" 						
						$checked />";											
						
						$html_contenido .= "\n <label class=\"css_component_security_areas_rotulo\" $required >$rotulo</label>";	
					}
					*/
					$html_contenido .= "\n <div class=\"security_areas_tree\">";
					$html_contenido .= $html_tree;
					$html_contenido .= "\n </div>";
					
					#$html_contenido .= "\n <span class=\"css_span_log\"></span>";										
					#$html_contenido .= "\n <span  class=\"css_span_ejemplo\">$ejemplo</span>";
							
					if($permissions==3){
						$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
					}
					break;
		
	}
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div>\n\n"; //wrap
?>