<?php

	# VISUALIZADOR HTML	

	
	if(!isset ($tools_html))						$tools_html='';
	
	if(isset($_REQUEST[$tipo]))						$dato = $_REQUEST[$tipo];		#var_dump($_REQUEST[$tipo]);
	
	
	print "\n<!-- SECURITY AREAS (CHECK BOX) [tipo:$tipo section_id_matrix:$parent] -->";
	print "\n<div class=\"css_wrap_check_box\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." (checkbox)</span>"; 
					break;
						
		case ($permissions>=1)	:
		
					foreach ($ar_list_of_values->result as $value => $rotulo) {
						
						if( is_array($dato) && in_array($value,$dato) ) {
							$checked = 'checked="checked"';
						}else {
							$checked = "";
						}
						$html_contenido .= "\n <input class=\"css_check_box\" type=\"checkbox\" name=\"{$tipo}[]\" data-tipo=\"{$tipo}\" value=\"{$value}\" data-section_tipo=\"{$section_tipo}\" parent=\"{$parent}\" title=\"$html_title\" $checked />";						
						$html_contenido .= "\n <label class=\"css_check_box_rotulo\" $required >$rotulo</label>";	
					}					
										
							
	}
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div>\n\n"; //wrap
?>