<?php
	

# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
		
		case ($permissions>=1) :
				
				# ETIQUETA (LABEL)
				if (!isset($this->print_options->show_label) || $this->print_options->show_label==true) {
					$html_contenido .= "\n <div class=\"css_print_label {$component_name}_print_label\">$label</div>";
				}
				# SECTION (LABEL)
				if (!isset($this->print_options->show_label_section) || $this->print_options->show_label_section==false){}else {
					$html_contenido .= "\n <div class=\"css_print_label {$component_name}_print_label\">$section_label</div>";
				}
	}

	# PRINT HTML
	print $html_contenido;
	
?>