<?php
	

	# VISUALIZADOR HTML
	


	$html    = "\n<!-- TOOL PAGE [tipo:$tipo] -->";	
	$html   .= "\n<div class=\"wrap_tool wrap_tool_relation_page\" >";
	$html   .= "\n<div class=\"content_data text_shadow_inset\" >";

		/*
		$html   .= "\n<script>
					var media_base_path = '',
						media_extension = ''									
					</script>";
		*/

		# LEFT SIDE
		$html   .= "\n<div class=\"left_side\">";			

			#
			# SELECTOR
			$html   .= "\n<div class=\"selector_areas_relation\">";
			$html 	.= $selector_relation_html;
			$html   .= "\n</div>";

		$html   .= "\n</div>";#left_side

		
		# RIGHT SIDE
		$html   .= "\n<div class=\"right_side\">";
			

			#
			# IFRAME RECORDS LIST
			$html   .= "\n<div class=\"records_relation\">";
			$html 	.= "\n <iframe id=\"iframe_records_relation\" name=\"iframe_records_relation\" class=\"iframe_records_relation\" src=\"{$iframe_records_relation_url}\" ></iframe>";
			$html   .= "\n</div>";

			
			

		$html   .= "\n</div>";#right_side
	
	$html .= "\n</div><!-- /content_data -->";
	$html .= "\n</div><!-- /wrap_tool -->"; //wrap_tool

	
	# INSPECTOR LOG TOOL
	$html .= "\n<div id=\"inspector_log\" class=\"tool_transcription_inspector_log\"> </div>";

	print $html;
		
?>