<?php


	# VISUALIZADOR HTML	

	$btn_title	= label::get_label('abrir').' '.label::get_label('herramienta');
	$tool_name	= label::get_label('tool_import_rdf');


	$html_tool  = '';
	$html_tool .= '<div id="button_tool_import_rdf" class="css_button_generic btn_inside_section_buttons_container tool_import_rdf"';
	$html_tool .= ' data-section_tipo="'.$section_tipo.'"';
	$html_tool .= ' data-section_id="'.$section_id.'"';
	$html_tool .= ' data-tool_name="'.$tool_name.'"';
	$html_tool .= ' onclick="tool_common.open_tool_import_rdf(this)"';
	$html_tool .= ' title="'.$btn_title.'">';
	
	$html_tool .= '<span>';
	$html_tool .= 'import-RDF';
	$html_tool .= '</span>';

	$html_tool .= '</div>';

	# PRINT HTML
	print $html_tool;