<?php

	# HTML VIEW

	if(SHOW_DEBUG) {
	print "\n<!-- ".get_class()."[section_tipo:$section_tipo section_id:$section_id] -->";
	}

	print "\n<div class=\"wrap_row_thesaurus wrap_row_thesaurus_{$modo} wrap_row_thesaurus_{$section_tipo}\" id=\"{$id_wrapper}\"	
	data-section_tipo=\"{$section_tipo}\"
	data-section_id=\"{$section_id}\"
	>";


		# CONTENT
		$html_content = '';
		# Note: permissions are from current section
		switch($permissions) {

			case 0 :
					$html_content .= "";
					break;

			case ($permissions>=1) :

					# ID COLUMN
					$html_content .= "<div class=\"id_column_content\">";
					
						#
						# ADD BUTTON
						$title='Add';	
						$html_content .= "<a href=\"javascript:;\" class=\"id_column_link row_thesaurus_add\" title=\"$title\" onclick=\"row_thesaurus.add_children(this)\">";
						$html_content .= "  <div class=\"row_thesaurus_add_icon\"></div>";
						$html_content .= "</a>";

						#
						# DELETE BUTTON
						$title='Delete';
						$html_content .= "<a href=\"javascript:;\" class=\"id_column_link row_thesaurus_delete\" data-tipo=\"test2\" data-section_id=\"1\" title=\"$title\" onclick=\"row_thesaurus.delete(this)\">";
						$html_content .= "  <div class=\"row_thesaurus_delete_icon\"></div>";						
						$html_content .= "</a>";

						#
						# EDIT BUTTON
						$title='Edit';
						#$html_content .= "<a href=\"javascript:;\" class=\"id_column_link button_edit link row_thesaurus_edit\" title=\"$title\"><span>Edit</span></a>";
						$html_content .= "<a href=\"javascript:;\" class=\"id_column_link row_thesaurus_edit\" title=\"$title\" onclick=\"row_thesaurus.edit(this)\">";
						$html_content .= "  <div class=\"row_thesaurus_section_id_number\">$section_id</div>";
						$html_content .= "  <div class=\"row_thesaurus_edit_icon\"></div>";
						$html_content .= "</a>";

					$html_content .= "</div>";//end id_column_content


					# ELEMENTS
					dump($ar_elements, ' ar_elements ++ '.to_string());
					$html_content .= "<div class=\"elements_container\">";
					foreach ($ar_elements as $element_tipo => $render_vars) {
						
						$modelo_name 	 = RecordObj_dd::get_modelo_name_by_tipo($element_tipo);
						$component 		 = component_common::get_instance($modelo_name,
																		  $element_tipo,
																		  $section_id,
																		  $modo='list_thesaurus',
																		  $lang=DEDALO_DATA_LANG,
																		  $section_tipo);			
						$component->set_render_vars( $render_vars );
						$html = $component->get_html();
						$html_content .= $html;					
					}
					$html_content .= "</div>";//end elements_container

				
					# DATA CONTAINER 
					$html_content .= '<div class="data_container"></div>';

					# CONTAINER CHILDRENS
					$html_content .= '<div class="childrens_container">'.$childrens_html.'</div>';

					# CONTAINER INDEXATIONS
					$html_content .= '<div class="indexations_container">'.$indexations_html.'</div>';

					break;
		}	


		# PRINT HTML
		print $html_content;


	print "\n</div>";
	if(SHOW_DEBUG) {
	print "<!-- /wrap_row_thesaurus ".get_class()." [section_tipo:$section_tipo section_id:$section_id] -->\n"; //wrap
	}



?>
