<?php

	# VISUALIZADOR HTML	
	//if(isset($_REQUEST[$tipo]))					$dato = $_REQUEST[$tipo];		#var_dump($_REQUEST[$tipo]);
	
	
	#print "\n<!-- NUMBER -->";

	print "\n<div class=\"wrap_component css_wrap_number\" id=\"wrap_{$tipo}\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch($permissions) {
			
		case 0	:	$html_content .= "";
					break;
						
		case ($permissions>=1):
		
					$html_content .= "\n <input class=\"css_number\" type=\"text\" name=\"{$search_input_name}\"
					data-tipo=\"{$tipo}\"
					value=\"{$dato}\"
					title=\"$html_title\" />";

					if(SHOW_DEBUG===true) {
						$html_content .= "<span class=\"debug_info\">$search_input_name</span>";
					}
	}

	# Prepare content to show in page
	tools::prepare_content($html_content);
	
	
	# PRINT HTML
	print $html_label;
	print $html_content;
	
	
	print "\n</div>\n\n"; //wrap
?>