<?php

	# VISUALIZADOR HTML	

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in');

	$wrap_style = isset($wrap_style) ? $wrap_style : '';
	print "<div id=\"{$id_wrapper}\" class=\"wrap_component css_wrap_image wrap_component_{$tipo}\" ";
	print "style=\"$wrap_style\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato=\"{$valor}\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-component_info='{$component_info}' ";
	print "data-related_tipo='{$ar_related_component_tipo_json}' ";
	print 'data-original_img_height="'.$original_img_height.'" ';
	print 'data-original_img_width="'.$original_img_width.'" ';
	print 'data-canvas_id="'.$identificador_unico.'" ';
	print ">";
	
		
		# ETIQUETA (LABEL)
		$html_label = component_common_draw::draw_label($this);
		

		# CONTENIDO (INPUT)
		$html_content = '';
		switch(true) {
				
			case $permissions===0 :
				$html_content .= "";
				break;
							
			case ($permissions>=1) :
			
				# IMAGE THUMB
				$title = '';
				if(SHOW_DEBUG) {
					$title .= "image_path: ".$this->get_image_path($quality);
				}
				
				$open_tool_default='';
				$add_class='';
				# IMAGE NOT EXISTS. PLACE DEDALO IMAGE WITH LINK TO DEFAULT TOOL
				if (component_security_tools::is_authorized_tool_for_logged_user('tool_upload') &&
					!$this->ImageObj->get_file_exists() &&
					!$this->get_original(DEDALO_IMAGE_QUALITY_ORIGINAL,false) &&
					$permissions>=2
					) {
					$open_tool_default .= "data-image_id=\"$image_id\" ";
					$open_tool_default .= "data-quality=\"".DEDALO_IMAGE_QUALITY_ORIGINAL."\" ";
					$open_tool_default .= "data-aditional_path=\"$aditional_path\" ";
					$open_tool_default .= "data-initial_media_path=\"$initial_media_path\" ";
					$open_tool_default .= "data-tipo=\"$tipo\" ";
					$open_tool_default .= "data-parent=\"$parent\" ";
					$open_tool_default .= "data-section_tipo=\"$section_tipo\" ";
					$open_tool_default .= "data-original_img_height=\"$original_img_height\" ";
					$open_tool_default .= "onclick=\"tool_common.open_tool_upload(this)\" ";
					$open_tool_default .= "title=\"Upload file in original quality\" ";

					$add_class = 'no_file';
				}

				$html_content .= '<div class="loading_image blink">Loading image..</div>';
		

				# CANVAS : IMAGE
				$html_content .= "<div class=\"canvas_container\">";
				$html_content .= "<canvas id=\"$identificador_unico\" class=\"canvas_edit $add_class\" hidpi=\"on\" {$open_tool_default}>";				
				$html_content .= "</canvas>";
				$html_content .= "</div>";

				#
				# JS Init component
				$html_content .= '<script>';
				# Init component
				$init_options = new stdClass();
					$init_options->component_name 	= $component_name;
					$init_options->init_mode 		= 'read';
					$init_options->wrapper_id 		= $id_wrapper;
					$init_options->image_url 		= $image_url;
				$html_content .= 'component_common.init('.json_encode($init_options).');';
				$html_content .= '</script>';
				break;
		}

		

		# Prepare content to show in page
		tools::prepare_content($html_content);
		

		# PRINT HTML
		print $html_label;
		print $html_content;
	
	
	print "</div>";//wrap


	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out');
	

