<?php

	# VISUALIZADOR HTML


	# CONTENIDO
	$html_contenido = (string)'';
	switch($permissions) {

		case 0	:
			$html_contenido .= '';
			break;

		case ($permissions>=1):

			# CLICK_ACTION
			$click_action="onclick=\"tool_common.open_player(this,{'type':'component_image','image_full_url':'$image_full_url'});\" ";

			$style = "background-image:url('$thumb_file_url')";
			$html_contenido .= "<div class=\"thumb_in_list div_image_image_in_list\" style=\"$style\" $click_action ";
			$html_contenido .= "data-image_id=\"$image_id\" ";
			$html_contenido .= "data-parent_matrix=\"$parent\" ";
			$html_contenido .= "alt=\"$image_id\" ";
			$html_contenido .= "></div>";

			break;
	}


	# PRINT HTML
	print $html_contenido;
?>