<?php
		
	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in');


	print "<div class=\"css_wrap_image wrap_component\" id=\"{$id_wrapper}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato=\"{$valor}\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-related_tipo='{$ar_related_component_tipo_json}' ";
	print ">";
	
		
		# ETIQUETA (LABEL)
		#$html_label = component_common_draw::draw_label($this);


		# Buttons
		$html_buttons='';

		
		# CONTENIDO (INPUT)
		$html_contenido = '';
		switch($permissions) {
				
			case 0 :	$html_contenido .= "";
						break;
							
			case ($permissions>=1) :


				# CANVAS : IMAGE   width=\"$img_width\" height=\"$img_height\"
				$html_contenido .= "<canvas id=\"$identificador_unico\" class=\"canvas_transcription_edit\" resize hidpi=\"off\">";
				$html_contenido .= "<img id=\"img_$identificador_unico\" src=\"$img_src\" data-img_width=\"$img_width\" data-img_height=\"$img_height\"/>";
				$html_contenido .= "</canvas>";

				$html_buttons .= "<div class=\"image_buttons\">";
				
					$html_buttons .= '<select name="zoom" id="zoom">';
					$html_buttons .= '<option value="800">800%</option>';
					$html_buttons .= '<option value="400">400%</option>';
					$html_buttons .= '<option value="200">200%</option>';
					$html_buttons .= '<option value="100">100%</option>';
					$html_buttons .= '<option value="75">75%</option>';
					$html_buttons .= '<option value="50">50%</option>';
					$html_buttons .= '<option value="25">25%</option>';
					$html_buttons .= '<option value="12.5">12.5%</option>';
					$html_buttons .= '<option value="6.25">6.25%</option>';
					$html_buttons .= '<option value="5">5%</option>';
					$html_buttons .= '<option value="1">1%</option>';
					$html_buttons .= '<option value=""></option>';
					$html_buttons .= '</select>';
					
					$html_buttons .= "<div class=\"main_buttons hide\">"; // <i class=\"glyphicon glyphicon-cog\"></i>
					#$html_buttons .= '<button class="btn btn-sm button_activate cuadrado" onclick=\"component_image.active_tool(this)\" data-tool_name=\"circulo\"> Cuadrado</button>';
					$html_buttons .= "<input type=\"button\" value=\"cuadrado\" class=\"button_activate cuadrado\" onclick=\"component_image.active_tool(this)\" data-tool_name=\"cuadrado\">";
					$html_buttons .= "<input type=\"button\" value=\"circulo\" class=\"button_activate\" onclick=\"component_image.active_tool(this)\" data-tool_name=\"circulo\">";
					$html_buttons .= "<input type=\"button\" value=\"vectores\" class=\"button_activate\" onclick=\"component_image.active_tool(this)\" data-tool_name=\"vectores\">";
					$html_buttons .= "<input type=\"button\" value=\"puntero\" class=\"button_activate\" onclick=\"component_image.active_tool(this)\" data-tool_name=\"puntero\">";
					#$html_buttons .= "<input type=\"button\" value=\"anadido\" onclick=\"anadido.activate()\">";
					$html_buttons .= "<input type=\"button\" value=\"salvar\" class=\"save_image_path\" onclick=\"component_image.save(this)\">";
					$html_buttons .= "</div>";

				$html_buttons .= "</div>";
				break;
												
		}

		# INIT : Init text editor 
		$html_contenido .= '<script>';
		$html_contenido .= 'window.addEventListener("load", function (event) {';
		$html_contenido .= "component_image.init_canvas('$identificador_unico','$id_wrapper');";
		$html_contenido .= '});';//end onload window
		$html_contenido .= '</script>';

		# Prepare content to show in page
		tools::prepare_content($html_contenido);	
		

		# PRINT HTML
		print $html_buttons;
		print $html_contenido;
	
	
	print "</div>"; //wrap


	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out');


