<?php

	# VISUALIZADOR HTML
	$html_tool  ='';
	$html_tool .= "<div class=\"tool_inspector_div\">";
	$html_tool .= "\n <div id=\"button_difussion_export_record\" class=\"icon_bs tool_diffusion tool_diffusion_inspector link\"
	data-options='$options_json'
	onclick=\"tool_diffusion.export_record(this,'')\">";
	$html_tool .= label::get_label('tool_diffusion');
	$html_tool .= " </div>";
	#$html_tool .= "<div id=\"tool_diffusion_response\" ondblclick=\"return function(){this.innerHTML='';}\"></div>";
	$html_tool .= "</div>";
	
	
	# PRINT HTML
	echo $html_tool;
	
?>