<?php
// Solve the problem of intelephense reporting error, Save as idehelper.php
define('DEDALO_VERSION','');
define('DEDALO_LIB_BASE_PATH','');
define('DEDALO_DIFFUSION_TM','');

define('DEDALO_ROOT_PATH','');
define('DEDALO_HOST','');
define('DEDALO_PROTOCOL','');
define('DEDALO_CONFIG','');
define('DEDALO_CORE','');
define('DEDALO_SHARED_PATH','');
define('DEDALO_TOOLS','');
define('DEDALO_LIB','');
define('DEDALO_CONFIG_PATH','');
define('DEDALO_CORE_PATH','');
define('DEDALO_CORE_URL','');
define('DEDALO_SHARED_URL','');
define('DEDALO_TOOLS_PATH','');
define('DEDALO_TOOLS_URL','');
define('DEDALO_LIB_PATH','');
define('DEDALO_LIB_URL','');
define('DEDALO_WIDGETS_PATH','');
define('DEDALO_WIDGETS_URL','');
define('DEDALO_EXTRAS_PATH','');
define('DEDALO_EXTRAS_URL','');
define('DEDALO_SALT_STRING','');
define('DEDALO_TIMEZONE','');
define('DEDALO_LOCALE','');
define('DEDALO_DATE_ORDER','');
define('DEDALO_ENTITY','');
define('DEDALO_ENTITY_LABEL','');
define('DEDALO_ENTITY_ID',0);
define('DEVELOPMENT_SERVER', false);
define('DEDALO_SESSIONS_PATH','');
define('DEDALO_SESSION_HANDLER','');
define('DEDALO_CACHE_MANAGER',[]);
define('SHOW_DEBUG', false);
define('SHOW_DEVELOPER',false);
define('DEDALO_BACKUP_ON_LOGIN',false);
define('DEDALO_BACKUP_TIME_RANGE',8);
define('DEDALO_BACKUP_PATH','');
define('DEDALO_BACKUP_PATH_TEMP','');
define('DEDALO_BACKUP_PATH_DB','');
define('DEDALO_BACKUP_PATH_ONTOLOGY','');
define('LOGGER_LEVEL',8);
define('UPDATE_LOG_FILE'.'');
define('DEDALO_STRUCTURE_LANG','');
define('DEDALO_APPLICATION_LANGS',[]);
define('DEDALO_APPLICATION_LANGS_DEFAULT','');
define('DEDALO_APPLICATION_LANG','');
define('DEDALO_DATA_LANG_DEFAULT','');
define('DEDALO_DATA_LANG','');
define('DEDALO_DATA_LANG_SELECTOR',true);
define('DEDALO_DATA_LANG_SYNC',false);
define('DEDALO_DATA_NOLAN','');
define('DEDALO_PROJECTS_DEFAULT_LANGS',[]);
define('DEDALO_DIFFUSION_LANGS',[]);
define('DEDALO_PREFIX_TIPOS',[]);
define('MAIN_FALLBACK_SECTION','');
define('NUMERICAL_MATRIX_VALUE_YES',1);
define('NUMERICAL_MATRIX_VALUE_NO',2);
define('DEDALO_MAX_ROWS_PER_PAGE',10);
define('DEDALO_PROFILE_DEFAULT',2);
define('DEDALO_DEFAULT_PROJECT',1);
define('DEDALO_FILTER_SECTION_TIPO_DEFAULT','');
define('DEDALO_MEDIA_PATH','');
define('DEDALO_MEDIA_URL','');
// media definitions here...
define('DEDALO_UPLOAD_TMP_DIR','');
define('DEDALO_UPLOAD_TMP_URL','');
define('DEDALO_UPLOAD_SERVICE_CHUNK_FILES',false);
define('DEDALO_GEO_PROVIDER','');
define('DEDALO_ENTITY_MEDIA_AREA_TIPO','');
define('DEDALO_ENTITY_MENU_SKIP_TIPOS',[]);
define('DEDALO_TEST_INSTALL', true);
define('DEDALO_SECTION_ID_TEMP','');
define('DEDALO_TOOL_EXPORT_FOLDER_PATH','');
define('DEDALO_TOOL_EXPORT_FOLDER_URL','');
define('DEDALO_TOOL_IMPORT_DEDALO_CSV_FOLDER_PATH','');
define('DEDALO_LOCK_COMPONENTS',true);
define('DEDALO_PROTECT_MEDIA_FILES',false);
define('DEDALO_NOTIFICATIONS',false);
define('DEDALO_AR_EXCLUDE_COMPONENTS',[]);
define('DEDALO_FILTER_USER_RECORDS_BY_ID',false);
define('ENCRYPTION_MODE','');
define('DEDALO_DIFFUSION_DOMAIN','');
define('DEDALO_DIFFUSION_RESOLVE_LEVELS',2);
define('DEDALO_PUBLICATION_CLEAN_URL',false);
define('DIFFUSION_CUSTOM',false);
define('API_WEB_USER_CODE_MULTIPLE',[]);
define('STRUCTURE_FROM_SERVER',true);
define('STRUCTURE_SERVER_CODE','');
define('STRUCTURE_SERVER_URL','');
define('ONTOLOGY_DOWNLOAD_DIR','');
define('STRUCTURE_DOWNLOAD_JSON_FILE','');
define('DEDALO_SOURCE_VERSION_URL','');
define('DEDALO_SOURCE_VERSION_LOCAL_DIR','');
define('IP_API',[]);
define('DEDALO_MAINTENANCE_MODE',false);
define('DEDALO_NOTIFICATION',[]);



define('SAML_CONFIG', ['']);
define('INIT_COOKIE_AUTH_ADDONS','');
define('DEDALO_BUILD','');
define('DEDALO_MAJOR_VERSION','');
define('CONFIG_DEFAULT_FILE_PATH','');
define('TR_TAGS_CDN','');
define('PREVENT_SESSION_LOCK','');

define('SERVER_PROXY','');
define('DEDALO_API_URL','');
define('DEDALO_API_URL_UNIT_TEST','');
define('DEDALO_IMAGE_QUALITY_DEFAULT','');
define('ONTOLOGY_DB','');

define('DEDALO_SECTION_PROJECTS_TIPO','');
define('DEDALO_ROOT_WEB','');

define('POSTPROCESSING_IMAGE_SCRIPT','');
define('DEDALO_SUPERUSER','');
define('DEDALO_IMAGE_ALTERNATIVE_EXTENSIONS','');
define('MYSQL_DB_BIN_PATH','');

define('DEDALO_NOTIFICATION',[]);
define('EXPORT_HIERARCHY_PATH','');
define('DEDALO_PDF_ALTERNATIVE_EXTENSIONS','');
define('DEDALO_NOTIFICATION_CUSTOM','');
define('STRUCTURE_IS_MASTER','');
define('DEDALO_CODE_SERVER_GIT_DIR','');
define('DEDALO_CODE_FILES_DIR','');

define('DEDALO_6_CODE_SERVER_GIT_DIR','');
define('DEDALO_6_CODE_FILES_DIR','');
define('SOCRATA_CONFIG',[]);

define('PDF_OCR_ENGINE','');

function session_start_manager(){};
function fix_cascade_config_var(){};
class logger{};
function custom_postprocessing_image(){};
// function logged_user_id() : ?int {};
function logged_user_is_developer() {};
// function array_find(?array $ar_value=null, callable $fn);
class Socrata(){function post(){}};
$options = new stdClass();
function apcu_enabled(){};
