<?php
// Solve the problem of intelephense reporting error, Save as idehelper.php
define('DEDALO_VERSION','');
define('DEDALO_LIB_BASE_PATH','');
define('DEDALO_DIFFUSION_TM','');
define('DEDALO_ROOT_PATH','');
define('DEDALO_ENTITY','');
define('SAML_CONFIG', ['']);
define('DEDALO_PROTECT_MEDIA_FILES','');
define('INIT_COOKIE_AUTH_ADDONS','');
define('DEDALO_BUILD','');
define('CONFIG_DEFAULT_FILE_PATH','');
define('TR_TAGS_CDN','');
define('DEDALO_CORE_PATH','');
define('DEDALO_CONFIG_PATH','');
define('PREVENT_SESSION_LOCK','');
define('DEDALO_LIB_PATH','');
define('DEDALO_LIB_URL','');
define('DEDALO_CORE_URL','');
define('DEDALO_BACKUP_PATH_ONTOLOGY','');
define('SERVER_PROXY','');
define('DEDALO_API_URL','');
define('DEDALO_API_URL_UNIT_TEST','');
define('DEDALO_IMAGE_QUALITY_DEFAULT','');
define('ONTOLOGY_DB','');
define('DEDALO_SHARED_PATH','');
define('DEDALO_SECTION_PROJECTS_TIPO','');
define('DEDALO_ROOT_WEB','');
define('DEDALO_PROTOCOL','');
define('DEDALO_MAJOR_VERSION','');
define('POSTPROCESSING_IMAGE_SCRIPT','');
define('DEDALO_SUPERUSER','');
define('DEDALO_EXTRAS_PATH','');
define('DEDALO_IMAGE_ALTERNATIVE_EXTENSIONS','');
define('MYSQL_DB_BIN_PATH','');
define('DEDALO_PUBLICATION_CLEAN_URL','');
define('DEDALO_DATA_LANG_SYNC','');
define('DEDALO_NOTIFICATION',[]);
define('EXPORT_HIERARCHY_PATH','');
define('DEDALO_PDF_ALTERNATIVE_EXTENSIONS','');
define('DEDALO_NOTIFICATION_CUSTOM','');
define('STRUCTURE_IS_MASTER','');
define('DEDALO_CODE_SERVER_GIT_DIR','');
define('DEDALO_CODE_FILES_DIR','');
define('DEDALO_SOURCE_VERSION_URL','');
define('DEDALO_SOURCE_VERSION_LOCAL_DIR','');
define('DEDALO_6_CODE_SERVER_GIT_DIR','');
define('DEDALO_6_CODE_FILES_DIR','');
function session_start_manager(){};
function fix_cascade_config_var(){};
class logger{};
function custom_postprocessing_image(){};
// function logged_user_id() : ?int {};
function logged_user_is_developer() {};
function array_find(array $ar_value=null, callable $fn);
$options = new stdClass();
