<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>request_config_editor</title>
	<!-- <script src="js/request_conf_editor.js"></script> -->
</head>
<body>
	<h1>request_config_editor</h1>
	<div id="main_div"></div>
</body>
<!-- <link rel="modulepreload" href="js/request_conf_editor.js?v=<?php echo DEDALO_VERSION ?>"> -->
<script type="module">
	import {request_conf_editor} from './js/request_conf_editor.js';	
	// ( async () => {		
		const main_div = document.getElementById("main_div")
		request_conf_editor.init({
			main_div	: main_div,
			tipo		: <?php echo json_encode($_GET['tipo'])?>
		})
	// })()
</script>
</html>