<?php

	# VISUALIZADOR HTML
	$html    = "<!-- $tool_name $modo -->";

	#
	# TOOL HEADER
	include($tool_name.'_header.phtml');


	#
	# TOOL BODY
	$html .= "<div class=\"wrap_tool_tr_portal_page\">";

		#
		# PORTAL IMAGES


		#
		# TEXT AREAS


		#
		# AUTOCOMPLETE		
		$html .= '<div class="autocomplete_wrap">';
		$html .= $autocomplete_html;
		$html .= '</div>';		

		
	$html .= "</div><!-- /wrap_tool_tr_portal_page -->"; //page body wrap


	# INSPECTOR LOG TOOL_LANG ()
	$html 	.= "<div id=\"inspector_log\" class=\"tool_inspector_log\"> </div>";



	print $html;		
?>