<?php

	# VISUALIZADOR HTML	
		
	# BUTTON TIME MACHINE
	#$html_time_machine    = "\n<!-- TOOL TIME MACHINE [tipo:$tipo] -->";

	
	$html_time_machine   .= "\n<div class=\"tm_list_wrap\">";

	$btn_title	  		  = label::get_label('abrir').' '.label::get_label('herramienta');
	$html_time_machine   .= "\n<div class=\"icon_bs tool_time_machine_icon link\" 
								data-tap_id=\"btn_time_machine_{$tipo}\" data-tipo=\"{$tipo}\" data-lang=\"{$lang}\"
								title=\"$btn_title\"
								onclick=\"tool_common.open_tool_time_machine(this)\"
								> </div> ";


	$html_time_machine   .= label::get_label('tool_time_machine');	#" Time machine ";

	
	$html_time_machine   .= "<div id=\"tm_list_container\" class=\"tm_list_container\" style=\"display:none\"><!-- Ajax load --></div>";

	$html_time_machine   .= "\n</div><!-- /tm_list_wrap -->";	

	
	# PRINT HTML
	print $html_time_machine;

?>
