<?php

	# VISUALIZADOR HTML	
		
	# BUTTON TOOL IN INSPECTOR
	$html_tool    = "\n<!-- TOOL FILE VERSIONS [tipo:$tipo section_id_matrix:$parent] -->";
	$html_tool   .= "<div class=\"tool_inspector_div\">";

	$btn_title	  = label::get_label('abrir').' '.label::get_label('herramienta');
	$html_tool   .= "\n<div class=\"icon_bs tool_av_versions_icon link\"
								data-tipo=\"{$tipo}\" data-parent=\"{$parent}\"
								title=\"$btn_title\"
								onclick=\"tool_common.open_tool_av_versions(this)\"
								> </div>";


	$html_tool   .= label::get_label('tool_av_versions');	#" File versions";
	

	$html_tool   .= "</div>";#/tool_inspector_div

	# PRINT HTML
	print $html_tool;
	
?>