<?php
	

	# VISUALIZADOR HTML
	


	$html    = "\n<!-- TOOL PAGE [tipo:$tipo] -->";	
	$html   .= "\n<div class=\"wrap_tool wrap_tool_image_versions_page\" >";
	$html   .= "\n<div class=\"content_data text_shadow_inset\" >";


		$html   .= "\n<script>
					page_globals.media_base_path = '$media_base_path',
					page_globals.media_extension = '$media_extension'									
					</script>";


		# THUMB
		$html .= "\n<div class=\"thumb_container\">";
		#$html .= "<span class=\"helper\"></span>";
		$html .= $thumb_html;
		$html .= "\n</div>";

		# VERSIONS
		$html .= "\n<table class=\"table_versions\">";
    
    	
	    	#
			# QUALITY ROW
		    $html .= "\n <tr>";
		    $html .= "\n <th>". label::get_label('calidad'). "</th>" ;
		    foreach ($ar_quality as $quality) {
		    	$td_style = null; if($quality==DEDALO_IMAGE_QUALITY_DEFAULT) $td_style = 'td_default_quality';
		    	$html .= "\n <th class=\"$td_style\">";
		    	$html .= $quality;
		    	if ($quality==DEDALO_IMAGE_QUALITY_DEFAULT) {
		    		$html .= " <span class=\"image_info\">[Default]</span>";
		    	}
		    	$html .= "\n </th>";
		    }
		    $html .= "\n </tr>";
			
		    
			#
			# FILE ROW
			$html .= "\n <tr>";
			$html .= "\n <td>". label::get_label('fichero')."</td>" ;
			foreach ($ar_quality as $quality) {
				$td_style = null; if($quality==DEDALO_IMAGE_QUALITY_DEFAULT) $td_style = 'td_default_quality';
				$html .= "\n <td class=\"$td_style\">";
			
				if( file_exists($this->component_obj->get_image_path($quality)) ) {	    			
	    		
					$html .= "<div class=\"icon_bs link image_image_icon\"
					data-tipo=\"$tipo\"
			    	data-parent=\"$parent\"
			    	data-section_tipo=\"$section_tipo\"
			    	data-image_id=\"$image_id\"
			    	data-quality=\"$quality\"
			    	data-aditional_path=\"$aditional_path\"
			    	data-initial_media_path=\"$initial_media_path\"
			    	onclick=\"tool_image_versions.change_media_quality(this)\"
			    	></div>";
				}

		    	$html .= "\n </td>";
		    }
		    $html .= "\n </tr>";
			
		    
		    #
		    # SIZE ROW
		    $html .= "\n <tr>";
		    $html .= "\n <td>". label::get_label('tamano')."</td>" ;
		    foreach ($ar_quality as $quality) {
		    	$td_style = null; if($quality==DEDALO_IMAGE_QUALITY_DEFAULT) $td_style = 'td_default_quality';
		    	$html .= "\n <td class=\"$td_style\">";
		    	
	    		if( file_exists($this->component_obj->get_image_path($quality)) ) {	    			
	    			    	
					$html .= "<div class=\"image_size_info\" 
			    	data-quality=\"$quality\" data-aditional_path=\"$aditional_path\" data-initial_media_path=\"$initial_media_path\"
			    	>";
			    	$html .= $this->component_obj->get_image_size($quality) ;

			    	$ImageObj 		= new ImageObj($image_id, $quality, $this->component_obj->aditional_path, $this->component_obj->initial_media_path);
					$current_width 	= $ImageObj->get_image_width();
					$current_height = $ImageObj->get_image_height();
					$pixels = $current_width * $current_height;
			    	$megabytes_from_pixels = ImageObj::get_megabytes_from_pixels($pixels);

			    	$html .= " <span class=\"image_info\">[{$megabytes_from_pixels}MB]</span>";
			    	"</div>";	#dump($this->component_obj->get_image_size($quality), $this->component_obj->get_image_path($quality));
		    	}

		    	$html .= "\n </td>";
		    }
		    $html .= "\n </tr>";


		    #
		    # PIXEL DIMENSIONS ROW
		    $html .= "\n <tr>";
		    $html .= "\n <td>Pixels <span class=\"image_info\">[WxH]</span></td>" ;	#label::get_label('dimensiones').
		    foreach ($ar_quality as $quality) {
		    	$td_style = null; if($quality==DEDALO_IMAGE_QUALITY_DEFAULT) $td_style = 'td_default_quality';
		    	$html .= "\n <td class=\"$td_style\">";
		    	
	    		if( file_exists($this->component_obj->get_image_path($quality)) ) {
	    		
	    		    $ImageObj 		= new ImageObj($image_id, $quality, $this->component_obj->aditional_path, $this->component_obj->initial_media_path);
					$current_width 	= $ImageObj->get_image_width();
					$current_height = $ImageObj->get_image_height();

					$html .= "\n <div class=\"image_size_info\" data-quality=\"$quality\" data-aditional_path=\"$aditional_path\"  data-initial_media_path=\"$initial_media_path\" >";					
					$html .= "$current_width x $current_height";
					$html .= "\n </div>";
				}
		    		    	
		    	$html .= "\n </td>";
		    }
		    $html .= "\n </tr>";

		    #
		    # PRINT SIZE ROW
		    $html .= "\n <tr>";
		    $html .= "\n <td>Print size <span class=\"image_info\">[".DEDALO_IMAGE_PRINT_DPI."dpi]</span></td>" ;	#label::get_label('dimensiones').
		    foreach ($ar_quality as $quality) {		    	
		    	$td_style = null; if($quality==DEDALO_IMAGE_QUALITY_DEFAULT) $td_style = 'td_default_quality';
		    	$html .= "\n <td class=\"$td_style\">";

	    		if( file_exists($this->component_obj->get_image_path($quality)) ) {
	    			 	
					$html .= "\n <div class=\"image_size_info\" data-quality=\"$quality\" data-aditional_path=\"$aditional_path\" data-initial_media_path=\"$initial_media_path\" >";
						$image_print_dimensions = $this->component_obj->get_image_print_dimensions($quality);
						# Widht
						$html .= $image_print_dimensions[0] .' x ';		#dump( $image_print_dimensions[0] . $image_print_dimensions[1] );
						# Height
						$html .= $image_print_dimensions[1] .'';
					$html .= "\n </div>";
				}
		    		    	
		    	$html .= "\n </td>";
		    }
		    $html .= "\n </tr>";
			
		    
			#
			# UPLOAD ROW
			if ($permissions>=2) {

				$current_section_tipo = isset($_GET['section_tipo']) ?  $_GET['section_tipo'] : ''; 	

				$html .= "\n <tr>";
				$html .= "\n <td>". label::get_label('subir')."</td>" ;
				foreach ($ar_quality as $quality) {
					$td_style = null; if($quality==DEDALO_IMAGE_QUALITY_DEFAULT) $td_style = 'td_default_quality';
		    		$html .= "\n <td class=\"$td_style\">";

					$html .= "<div class=\"icon_bs link tool_upload_icon\"
					data-image_id=\"$image_id\"
					data-quality=\"$quality\"
					data-aditional_path=\"$aditional_path\"
					data-initial_media_path=\"$initial_media_path\"
					data-tipo=\"$tipo\"
					data-parent=\"$parent\"
					data-section_tipo=\"$current_section_tipo\"
					onclick=\"tool_common.open_tool_upload(this)\"
					></div>";	    		    	
					$html .= "\n </td>";
				}
				$html .= "\n </tr>";
		    }
			
		    
		    #
		    # DOWNLOAD ROW
		    if ($permissions>=2) {

			    $html .= "\n <tr>";
			    $html .= "\n <td>". label::get_label('descargar')."</td>" ;
			    foreach ($ar_quality as $quality) {
			    	$td_style = null; if($quality==DEDALO_IMAGE_QUALITY_DEFAULT) $td_style = 'td_default_quality';
		    		$html .= "\n <td class=\"$td_style\">";

		    		if( file_exists($this->component_obj->get_image_path($quality)) ) {		    			
		    		
				    	$html .= "<div class=\"icon_bs link image_download_icon\"
				    	data-image_id=\"$image_id\" data-quality=\"$quality\" data-aditional_path=\"$aditional_path\" data-initial_media_path=\"$initial_media_path\"
				    	data-tipo=\"$tipo\" data-parent=\"$parent\"
				    	onclick=\"tool_image_versions.download_file(this)\"
				    	></div>";				    							
					}

					# ORIGINAL ICON (TIF, PSD, ETC.)
			    	$original = $this->component_obj->get_original();
			    		#dump($original,'original');
			    	if($original) {
			    		$html .= "<div class=\"original_icon\" title=\"original $original version\"
				    	data-image_id=\"$image_id\" data-quality=\"$quality\" data-aditional_path=\"$aditional_path\" data-initial_media_path=\"$initial_media_path\" data-extension=\"$original\"
				    	data-tipo=\"$tipo\" data-parent=\"$parent\"
				    	onclick=\"tool_image_versions.download_file(this)\"
				    	>$original</div>";
			    	}
			    	    	
			    	$html .= "\n </td>";
			    }
			    $html .= "\n </tr>";
			}


		    # VIEW ROW
		    if ($permissions>=1) {

			    $html .= "\n <tr>";
			    $html .= "\n <td>". label::get_label('visualizar')."</td>" ;
			    foreach ($ar_quality as $quality) {
			    	$td_style = null; if($quality==DEDALO_IMAGE_QUALITY_DEFAULT) $td_style = 'td_default_quality';
		    		$html .= "\n <td class=\"$td_style\">";

		    		if( file_exists($this->component_obj->get_image_path($quality)) ) {

				    	$html .= "<div class=\"icon_bs link image_zoom_in_icon\"
				    	data-image_id=\"$image_id\" data-quality=\"$quality\" data-aditional_path=\"$aditional_path\" data-initial_media_path=\"$initial_media_path\"
				    	data-tipo=\"$tipo\" data-parent=\"$parent\"
				    	onclick=\"tool_image_versions.view_image(this)\"
				    	></div>";
					}

			    	$html .= "\n </td>";
			    }
			    $html .= "\n </tr>";
			}
			
			
			#
		    # DELETE ROW
		    if ($permissions>=2) {

			    $html .= "\n <tr>";
			    $html .= "\n <td>". label::get_label('borrar')."</td>" ;
			    foreach ($ar_quality as $quality) {
			    	$td_style = null; if($quality==DEDALO_IMAGE_QUALITY_DEFAULT) $td_style = 'td_default_quality';
		    		$html .= "\n <td class=\"$td_style\">";
			    	
		    		if( file_exists($this->component_obj->get_image_path($quality)) ) {
		    			
				    	$html .= "<div class=\"icon_bs link image_delete_icon\"
				    	data-image_id=\"$image_id\"
				    	data-quality=\"$quality\"
				    	data-aditional_path=\"$aditional_path\"
				    	data-initial_media_path=\"$initial_media_path\"
				    	data-tipo=\"$tipo\"
				    	data-parent=\"$parent\"
				    	data-section_tipo=\"$section_tipo\"
				    	onclick=\"tool_image_versions.delete_version(this)\"
				    	></div>";
			    	  }

			    	$html .= "\n </td>";
			    }
			    $html .= "\n </tr>";
			}
			
			
			#
		    # GENERATE ROW
		    if ($permissions>=2 && DEDALO_IMAGE_LIB) {

			    $html .= "\n <tr>";
			    $html .= "\n <td>". label::get_label('generar') .' '.label::get_label('version'). "</td>" ;
			    foreach ($ar_quality as $quality) {
			    	$td_style = null; if($quality==DEDALO_IMAGE_QUALITY_DEFAULT) $td_style = 'td_default_quality';
		    		$html .= "\n <td class=\"$td_style\">";

			    	$source_quality_file 	= $this->component_obj->get_image_path($quality);
			    	
			    	if( file_exists($source_quality_file) ) {

			    		$previous_quality 	= $quality;
						$ImageObj 			= new ImageObj($image_id, $quality, $this->component_obj->aditional_path, $this->component_obj->initial_media_path);
						$previous_width 	= $ImageObj->get_image_width();
						$previous_height 	= $ImageObj->get_image_height();			
						if(SHOW_DEBUG) {
						 	#dump($previous_quality, "previous_quality - current:$quality  - $previous_width - $previous_height");	
						 }				
					
					}else if ( $this->component_obj->get_original() ) {

						$source_file = DEDALO_MEDIA_BASE_PATH.DEDALO_IMAGE_FOLDER.'/'.$quality . $aditional_path .'/'. $image_id.'.'.$this->component_obj->get_original();
						$target_file = DEDALO_MEDIA_BASE_PATH.DEDALO_IMAGE_FOLDER.'/'.$quality . $aditional_path .'/'. $image_id.'.'.DEDALO_IMAGE_EXTENSION;

						#dump($source_file,'$source_file '.$target_file);
						$title = "Convert ".$this->component_obj->get_original()." to ".DEDALO_IMAGE_EXTENSION. " (width same quality)";
						$html .= "<div class=\"icon_bs link image_generate_icon\"
						data-image_id=\"$image_id\" data-quality=\"$quality\" data-aditional_path=\"$aditional_path\" data-initial_media_path=\"$initial_media_path\" data-source_file=\"$source_file\" data-target_file=\"$target_file\" data-flags=\"\" 
						data-tipo=\"$tipo\" data-parent=\"$parent\"
						onclick=\"tool_image_versions.convert_simple(this)\"
						title=\"$title\"
						></div>";
						/*
						# ORIGINAL ICON (TIF, PSD, ETC.)
				    	$source_quality = $previous_quality;						
						$title = null;
						if(isset($previous_quality)) {							

							$ar_target 		= ImageObj::get_target_pixels_to_quality_conversion($previous_width, $previous_height, $quality);
							$widht_target 	= $ar_target[0];
							$height_target 	= $ar_target[1];
								#dump($ar_target,"$widht_target x $height_target - source_quality:$source_quality - target_quality:$quality ($previous_width x $previous_height)");
							
							$title 			= "Convert from \nQ:$source_quality ($previous_width x $previous_height)\nto \nQ:$quality ($widht_target x $height_target)";
						}						
						*/
									
					}else if(isset($previous_quality )) {

						
						$source_quality = $previous_quality;											
						$title = null;
						/* OLD WORLD					
						if(isset($previous_quality)) {							

							$ar_target 		= ImageObj::get_target_pixels_to_quality_conversion($previous_width, $previous_height, $quality);
							$widht_target 	= $ar_target[0];
							$height_target 	= $ar_target[1];
								#dump($ar_target,"$widht_target x $height_target - source_quality:$source_quality - target_quality:$quality ($previous_width x $previous_height)");
							
							$title 			= "Convert from \nQ:$source_quality ($previous_width x $previous_height)\nto \nQ:$quality ($widht_target x $height_target)";
						}
						# Si la calidad target es válida para calcular el tamaño 
						if($widht_target>0 && $height_target>0) {
							$html .= "<div class=\"icon_bs link image_generate_icon\"
							data-image_id=\"$image_id\" data-quality=\"$quality\" data-aditional_path=\"$aditional_path\" data-source_quality=\"$source_quality\" data-target_quality=\"$quality\"
							data-tipo=\"$tipo\" data-parent=\"$parent\"
							onclick=\"tool_image_versions.generate_version(this)\"
							title=\"$title\"
							></div>";
						}
						*/	
						$html .= "<div class=\"icon_bs link image_generate_icon\"
							data-image_id=\"$image_id\" data-quality=\"$quality\" data-aditional_path=\"$aditional_path\" data-initial_media_path=\"$initial_media_path\" data-source_quality=\"$source_quality\" data-target_quality=\"$quality\"
							data-tipo=\"$tipo\" data-parent=\"$parent\"
							onclick=\"tool_image_versions.generate_version(this)\"
							title=\"Convert from $previous_quality\"
							></div>";


					}#end else

					$html .= "\n </td>";
				}#end foreach
			    $html .= "\n </tr>";
			}



			#
		    # ROTATE
		    if ($permissions>=2 && DEDALO_IMAGE_LIB) {

			    $html .= "\n <tr>";
			    $html .= "\n <td>". label::get_label('rotar') .' '.label::get_label('imagen'). "</td>" ;
			    foreach ($ar_quality as $quality) {
			    	$td_style = null; if($quality==DEDALO_IMAGE_QUALITY_DEFAULT) $td_style = 'td_default_quality';
		    		$html .= "\n <td class=\"$td_style\">";
			    	
			    	$source_quality_file 	= $this->component_obj->get_image_path($quality);

			    	if( file_exists($source_quality_file) ) {
											
						$title 		= null;
						$degrees 	= 90;

						$html .= "<div class=\"icon_bs link image_rotate_left_icon\"
						data-image_id=\"$image_id\" data-quality=\"$quality\" data-aditional_path=\"$aditional_path\" data-initial_media_path=\"$initial_media_path\" data-degrees=\"$degrees\"
						data-tipo=\"$tipo\" data-parent=\"$parent\"					
						onclick=\"tool_image_versions.rotate_image(this)\"
						title=\"$title\"
						></div>";

						$title 		= null;
						$degrees 	= -90;
												
						$html .= "<div class=\"icon_bs link image_rotate_right_icon\"
						data-image_id=\"$image_id\" data-quality=\"$quality\" data-aditional_path=\"$aditional_path\" data-initial_media_path=\"$initial_media_path\" data-degrees=\"$degrees\"
						data-tipo=\"$tipo\" data-parent=\"$parent\"					
						onclick=\"tool_image_versions.rotate_image(this)\"
						title=\"$title\"
						></div>";
					}

					$html .= "\n </td>";
				}#end foreach
			    $html .= "\n </tr>";
			}#END ROTATE
		

		$html .= "\n</table><!-- /table_versions -->";


	
	$html .= "\n</div><!-- /content_data -->";
	$html .= "\n</div><!-- /wrap_tool -->"; //wrap_tool

	
	# INSPECTOR LOG TOOL
	$html .= "\n<div id=\"inspector_log\" class=\"tool_image_versions_inspector_log\"> </div>";

	print $html;
		
?>