/**
 * Diffusion unpublish on delete (PHP diffusion_delete::delete_record): a
 * deleted record's published copies leave every diffusion target.
 *
 *   - sql / socrata elements → the NATIVE in-process executor registered at
 *     boot (src/diffusion/targets/mariadb/delete_record.ts) receives
 *     [{database_name, table_name, section_ids:[id], section_tipo}] — the
 *     engine wire shape, kept verbatim across the seam;
 *   - rdf / xml / markdown elements → published-file unlinks under the
 *     media root: rdf = /rdf/{service}/{sanitize(rdfName_st_id)}.rdf (+ the
 *     legacy '{base}_*.rdf' variants), xml/markdown = /{type}/{service}/
 *     {st}_{id}.{ext}; missing service_name (this install's live rdf
 *     config) → pending; nothing published → idempotent success;
 *   - per-element outcomes land in the dd1758 diffusion log
 *     (matrix_activity_diffusion): unpublished (2) on success,
 *     unpublish_pending (3) on failure — retryPendingDiffusion() re-runs the
 *     pending rows and flips them in place (PHP retry_pending, DIFFU-08
 *     rule: only flip when the retry actually resolved targets).
 *
 * No registered executor → DEC-19 loud warning + pending rows (see
 * deleteDiffusionRecord); no targets → silent no-op, matching a fresh
 * install. The old-engine unix-socket/token transport
 * (DEDALO_DIFFUSION_SOCKET_PATH / DEDALO_DIFFUSION_INTERNAL_TOKEN) was
 * retired at the 2026-07-11 cutover (DIFFUSION_PLAN P5 step 3;
 * rewrite/CUTOVER_RUNBOOK.md §5) — the native paths are primary since S2-31.
 */

import { existsSync, readdirSync, unlinkSync } from 'node:fs';
import { readEnv } from '../../config/env.ts';
import { sql } from '../db/postgres.ts';
import { virtualDateNow } from '../section/record/create_record.ts';
import { getSectionDiffusionTargets } from './diffusion_map.ts';

export interface DiffusionDeleteOutcome {
	/** db|table keys the engine confirmed deleted. */
	deleted: string[];
	/** Targets that failed or were ledgered (rdf/xml/markdown). */
	pending: string[];
}

/**
 * TEST-ONLY dd1758 activity-table override (the DIFFUSION_JOBS_TABLE seam
 * twin — S1-17/DEC-18a pattern). Every dd1758 read/write funnels through this
 * module; without the seam, a test's retryPendingDiffusion selects the oldest
 * pending rows of the REAL matrix_activity_diffusion — its stub engine can
 * flip REAL pending rows to 'unpublished' without any actual delete, and ≥10
 * older real rows starve the test's probe rows (the ledgered intermittent).
 * The bun-test preload (test/preload/session_db.ts) points
 * DIFFUSION_ACTIVITY_TABLE at a per-run scratch table. Guard: an override
 * MUST carry the scratch prefix `dedalo_ts_test_` — production (including the
 * live dev server's delete executor) can never be redirected; no env → the
 * real 'matrix_activity_diffusion'.
 */
function resolveActivityTable(): string {
	// readEnv (not process.env) per the S2-21 config rule; the bun-test preload
	// sets this in the real process env, which wins the precedence chain anyway,
	// and the dedalo_ts_test_ guard below keeps ANY source from redirecting
	// production to an arbitrary table.
	const override = readEnv('DIFFUSION_ACTIVITY_TABLE');
	if (override === undefined || override === '') {
		return 'matrix_activity_diffusion';
	}
	if (!/^dedalo_ts_test_[a-z0-9_]*$/.test(override)) {
		throw new Error(
			`DIFFUSION_ACTIVITY_TABLE override '${override}' rejected: it is a TEST seam and must match /^dedalo_ts_test_[a-z0-9_]*$/.`,
		);
	}
	return override;
}

export const DIFFUSION_ACTIVITY_TABLE = resolveActivityTable();

let activityTableEnsured: Promise<void> | null = null;

/**
 * Scratch-table bootstrap. The REAL matrix_activity_diffusion is PHP-owned
 * (install/db/matrix_activity_diffusion.sql) — never touched here. When the
 * test seam is active the scratch twin must exist before the first write;
 * columns mirror the PHP DDL (the subset this module and the matrix codecs
 * use), section_id keeps its own sequence default ("sequence-allocated
 * section_id", same as the real table).
 */
async function ensureActivityTable(): Promise<void> {
	if (DIFFUSION_ACTIVITY_TABLE === 'matrix_activity_diffusion') return; // PHP owns the real DDL
	if (activityTableEnsured === null) {
		activityTableEnsured = (async () => {
			await sql.unsafe(
				`CREATE SEQUENCE IF NOT EXISTS "${DIFFUSION_ACTIVITY_TABLE}_section_id_seq"`,
			);
			await sql.unsafe(`
				CREATE TABLE IF NOT EXISTS "${DIFFUSION_ACTIVITY_TABLE}" (
					id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					"timestamp" timestamp without time zone DEFAULT now(),
					section_id integer NOT NULL DEFAULT nextval('${DIFFUSION_ACTIVITY_TABLE}_section_id_seq'),
					section_tipo character varying(255) NOT NULL,
					data jsonb,
					relation jsonb,
					string jsonb,
					date jsonb,
					iri jsonb,
					geo jsonb,
					number jsonb,
					media jsonb,
					misc jsonb,
					relation_search jsonb,
					meta jsonb
				)
			`);
		})().catch((error) => {
			// A failed bootstrap must not poison the memo forever — retry next call.
			activityTableEnsured = null;
			throw error;
		});
	}
	return activityTableEnsured;
}

/** One sql/socrata delete target handed to the executor (engine wire shape). */
export interface NativeSqlDeleteTarget {
	database_name: string;
	table_name: string;
	section_ids: (number | string)[];
	section_tipo?: string;
}

type NativeSqlDeleteExecutor = (
	targets: NativeSqlDeleteTarget[],
) => Promise<{ deleted: string[]; errors: string[] }>;

/**
 * Native in-process SQL delete executor, registered by the diffusion module
 * at boot (src/diffusion/targets/mariadb/delete_record.ts). Registration seam
 * instead of an import because core must never import src/diffusion/**
 * (DIFFUSION_SPEC §2.5 boundary; ragRecordHook precedent). While unregistered
 * there is NO fallback (the old-engine socket retired at the 2026-07-11
 * cutover): sql deletes go pending with the DEC-19 loud warning.
 */
let nativeSqlDeleteExecutor: NativeSqlDeleteExecutor | null = null;

export function registerNativeDiffusionSqlDelete(executor: NativeSqlDeleteExecutor): void {
	nativeSqlDeleteExecutor = executor;
}

/** Test hook: drop the registered executor (restores the DEC-19 pending state). */
export function resetNativeDiffusionSqlDeleteForTests(): void {
	nativeSqlDeleteExecutor = null;
}

/**
 * Native media-index (publication-marker store) operations, registered by the
 * diffusion module at boot (src/diffusion/targets/mediastore/media_index.ts)
 * through the same seam pattern as the SQL delete executor (S2-31 port).
 * While unregistered there is NO fallback: rebuild reports the DEC-19 loud
 * error (the old-engine socket retired at the 2026-07-11 cutover).
 */
export interface NativeMediaIndexOps {
	rebuild(
		targets: { database_name: string; table_name: string; section_tipo: string }[],
	): Promise<{ result: boolean; msg: string; markers: number; errors?: string[] }>;
	getStatus(): Promise<{
		enabled: boolean;
		base: string | null;
		pub_markers: number;
		auth_markers: number;
		databases: string[];
	}>;
	reconcile(): Promise<{ added: number; removed: number } | null>;
}

let nativeMediaIndexOps: NativeMediaIndexOps | null = null;

export function registerNativeMediaIndex(ops: NativeMediaIndexOps): void {
	nativeMediaIndexOps = ops;
}

/** The registered native media-index ops (null while unregistered). */
export function getNativeMediaIndexOps(): NativeMediaIndexOps | null {
	return nativeMediaIndexOps;
}

/** Test hook: drop the registered ops (restores the DEC-19 unregistered state). */
export function resetNativeMediaIndexForTests(): void {
	nativeMediaIndexOps = null;
}

/** Propagate a record deletion to the diffusion targets. Never throws. */
export async function deleteDiffusionRecord(
	sectionTipo: string,
	sectionId: number,
	/** false when a retry drives the call (the pending row IS the log). */
	logActivity = true,
	/** The acting user for the dd1758 ledger; absent → dd1762 omitted. */
	userId?: number,
): Promise<DiffusionDeleteOutcome> {
	const outcome: DiffusionDeleteOutcome = { deleted: [], pending: [] };
	try {
		const targets = await getSectionDiffusionTargets(sectionTipo);
		if (targets.length === 0) return outcome;

		const sqlTargets = targets.filter(
			(target) =>
				(target.type === 'sql' || target.type === 'socrata') &&
				target.database_name !== '' &&
				target.table_name !== '',
		);
		for (const target of targets) {
			if (target.type !== 'sql' && target.type !== 'socrata') {
				const unlinked = await unlinkPublishedFiles(
					target.element_tipo,
					target.type,
					sectionTipo,
					sectionId,
				);
				if (unlinked) outcome.deleted.push(`${target.type}:${target.element_tipo}`);
				else outcome.pending.push(`${target.type}:${target.element_tipo}`);
			}
		}
		if (sqlTargets.length === 0) return outcome;

		// NATIVE path (DIFFUSION_SPEC §4.2) — the ONLY executor since the
		// 2026-07-11 cutover: MariaDB deletes run through the registered
		// in-process executor, then execution falls through to the dd1758
		// ledger below.
		if (nativeSqlDeleteExecutor === null) {
			// DEC-19: sql targets exist but no native executor is registered —
			// delete propagation is NOT running and published rows/markers will
			// rot. Loud, per DECISIONS.md:391-395. (No dd1758 rows here — the
			// deliberate fresh-install no-op posture; with the executor
			// registered at boot this branch only fires when that registration
			// failed, which server.ts already reports as FATAL-FOR-DELETES.)
			console.error(
				`[diffusion] DEC-19: record ${sectionTipo}/${sectionId} has ${sqlTargets.length} sql publication target(s) but no native delete executor is registered — unpublish is deferred to pending rows. Fix the boot registration (src/server.ts).`,
			);
			for (const target of sqlTargets) {
				outcome.pending.push(`${target.database_name}|${target.table_name}`);
			}
			return outcome;
		}

		const native = await nativeSqlDeleteExecutor(
			sqlTargets.map((target) => ({
				database_name: target.database_name,
				table_name: target.table_name,
				section_ids: [sectionId],
				section_tipo: sectionTipo, // enables media marker removal in the store
			})),
		);
		const confirmed = new Set(native.deleted);
		for (const target of sqlTargets) {
			const key = `${target.database_name}|${target.table_name}`;
			if (confirmed.has(key)) outcome.deleted.push(key);
			else outcome.pending.push(key);
		}
		if (native.errors.length > 0) {
			console.error('diffusion unpublish reported errors:', native.errors);
		}
	} catch (error) {
		console.error('diffusion unpublish failed (swallowed, pending rows persist):', error);
	}
	await logUnpublishOutcome(sectionTipo, sectionId, outcome, logActivity, userId);
	return outcome;
}

/**
 * dd1758 diffusion log: one row per sql element — unpublished (2) when every
 * one of its targets confirmed, unpublish_pending (3) otherwise. Shared by
 * the native and engine-socket delete paths so the ledger is identical
 * regardless of executor.
 */
async function logUnpublishOutcome(
	sectionTipo: string,
	sectionId: number,
	outcome: DiffusionDeleteOutcome,
	logActivity: boolean,
	userId?: number,
): Promise<void> {
	if (!logActivity) return;
	try {
		const targets = await getSectionDiffusionTargets(sectionTipo);
		const confirmedKeys = new Set(outcome.deleted);
		const elements = new Map<string, boolean>();
		for (const target of targets) {
			const key =
				target.type === 'sql' || target.type === 'socrata'
					? `${target.database_name}|${target.table_name}`
					: `${target.type}:${target.element_tipo}`;
			const previous = elements.get(target.element_tipo) ?? true;
			elements.set(target.element_tipo, previous && confirmedKeys.has(key));
		}
		for (const [elementTipo, success] of elements) {
			await logDiffusionActivity({
				sectionTipo,
				sectionId,
				elementTipo,
				action: success ? 2 : 3, // unpublished | unpublish_pending
				userId,
			});
		}
	} catch (error) {
		console.error('diffusion log write failed (swallowed):', error);
	}
}

/** dd1767 action ids (PHP diffusion_activity_logger). */
export const DIFFUSION_ACTION = { published: 1, unpublished: 2, unpublishPending: 3 } as const;

/**
 * Append one dd1758 diffusion-log row (matrix_activity_diffusion, sequence-
 * allocated section_id): dd1762 user, dd1763 processed-record locator,
 * dd1764 section_id number, dd1765 section_tipo string, dd1766 element
 * locator ({tld}0 / numeric part — the ontology-node-as-record convention),
 * dd1767 action locator (dd1774).
 *
 * dd1762 records the REAL acting user; when no userId reaches us the field is
 * OMITTED entirely (PHP diffusion_activity_logger `if ($user_id)`) — never a
 * fabricated superuser −1 locator.
 */
export async function logDiffusionActivity(entry: {
	sectionTipo: string;
	sectionId: number;
	elementTipo: string | null;
	action: number;
	userId?: number;
	now?: Date;
}): Promise<void> {
	const now = entry.now ?? new Date();
	const relation: Record<string, unknown[]> = {
		dd1763: [
			{
				type: 'dd151',
				section_id: String(entry.sectionId),
				section_tipo: entry.sectionTipo,
				from_component_tipo: 'dd1763',
			},
		],
		dd1767: [
			{
				type: 'dd151',
				section_id: String(entry.action),
				section_tipo: 'dd1774',
				from_component_tipo: 'dd1767',
			},
		],
	};
	// Truthiness on purpose — PHP's `if ($user_id)`: 0/undefined/NaN → omit.
	if (entry.userId) {
		relation.dd1762 = [
			{
				type: 'dd151',
				section_id: String(entry.userId),
				section_tipo: 'dd128',
				from_component_tipo: 'dd1762',
			},
		];
	}
	if (entry.elementTipo !== null) {
		const match = entry.elementTipo.match(/^([a-z]+)([0-9]+)$/);
		if (match !== null) {
			relation.dd1766 = [
				{
					type: 'dd151',
					section_id: match[2],
					section_tipo: `${match[1]}0`,
					from_component_tipo: 'dd1766',
				},
			];
		}
	}
	const { encodeForJsonb } = await import('../db/json_codec.ts');
	await ensureActivityTable();
	await sql.unsafe(
		`INSERT INTO "${DIFFUSION_ACTIVITY_TABLE}" (section_tipo, relation, string, date, number, misc)
		 VALUES ('dd1758', $1::text::jsonb, $2::text::jsonb, $3::text::jsonb, $4::text::jsonb, '{}'::text::jsonb)`,
		[
			encodeForJsonb(relation),
			encodeForJsonb({ dd1765: [{ lang: 'lg-nolan', value: entry.sectionTipo }] }),
			encodeForJsonb({ dd1761: [{ start: virtualDateNow(now) }] }),
			encodeForJsonb({ dd1764: [{ value: entry.sectionId }] }),
		],
	);
}

/**
 * Re-run pending unpublish rows (PHP diffusion_delete::retry_pending): read
 * dd1758 rows whose dd1767 action is unpublish_pending, re-run the delete
 * restricted to the row's element, and flip the action locator IN PLACE to
 * unpublished — only when the retry actually confirmed targets (DIFFU-08).
 */
export async function retryPendingDiffusion(
	limit = 100,
): Promise<{ total: number; retried: number; remaining: number }> {
	await ensureActivityTable();
	const rows = (await sql.unsafe(
		`SELECT section_id,
		        relation->'dd1763'->0->>'section_tipo' AS target_section,
		        relation->'dd1763'->0->>'section_id' AS target_id
		 FROM "${DIFFUSION_ACTIVITY_TABLE}"
		 WHERE section_tipo = 'dd1758'
		   AND relation->'dd1767' @> '[{"section_id":"3","section_tipo":"dd1774"}]'
		 ORDER BY section_id ASC LIMIT ${Math.max(1, Math.floor(limit))}`,
	)) as { section_id: number; target_section: string | null; target_id: string | null }[];
	const outcome = { total: rows.length, retried: 0, remaining: 0 };
	for (const row of rows) {
		if (row.target_section === null || row.target_id === null) {
			outcome.remaining++;
			continue;
		}
		const retry = await deleteDiffusionRecord(
			row.target_section,
			Number(row.target_id),
			false, // the pending row already represents the intent — no new rows
		);
		if (retry.deleted.length > 0) {
			// flip unpublish_pending → unpublished in place
			await sql.unsafe(
				`UPDATE "${DIFFUSION_ACTIVITY_TABLE}"
				 SET relation = jsonb_set(relation, '{dd1767,0,section_id}', '"2"'::jsonb)
				 WHERE section_tipo = 'dd1758' AND section_id = $1`,
				[row.section_id],
			);
			outcome.retried++;
		} else {
			outcome.remaining++;
		}
	}
	return outcome;
}

/** PHP sanitize_file_name + beautify (delete-side subset: dash-safe names). */
export function sanitizePublishedFileName(name: string): string {
	let out = name.replace(/[^\w\s\d\-_~,;[\]().]/gu, '');
	out = out.replace(/\.{2,}/g, '');
	out = out.toLowerCase().replace(/[^a-z0-9.]+/g, '-');
	out = out.replace(/[\s_]+/g, '-').replace(/-+/g, '-');
	out = out.replace(/-*\.-*/g, '.').replace(/\.{2,}/g, '.');
	return out.replace(/^[-.]+|[-.]+$/g, '');
}

/**
 * Resolve one file element's published path (PHP diffusion_rdf/xml/markdown
 * get_record_file_path). Null when the element declares no service_name —
 * the live rdf config here — which the caller records as pending.
 */
export async function resolvePublishedFilePath(
	elementTipo: string,
	type: string,
	sectionTipo: string,
	sectionId: number,
	mediaRoot?: string,
): Promise<string | null> {
	const root = mediaRoot ?? readEnv('MEDIA_PATH');
	if (root === undefined || root === '') return null;
	const propsRows = (await sql.unsafe(
		`SELECT properties->'diffusion'->>'service_name' AS service FROM dd_ontology WHERE tipo = $1`,
		[elementTipo],
	)) as { service: string | null }[];
	const service = propsRows[0]?.service ?? null;
	if (service === null || service === '') return null;

	if (type === 'xml' || type === 'markdown') {
		const extension = type === 'xml' ? 'xml' : 'md';
		return `${root}/${type}/${service}/${sectionTipo}_${sectionId}.${extension}`;
	}
	// rdf: the owl:Class child whose related section matches names the file.
	const owlRows = (await sql.unsafe(
		`SELECT term, relations FROM dd_ontology WHERE parent = $1 AND model = 'owl:Class'`,
		[elementTipo],
	)) as { term: Record<string, string> | null; relations: { tipo?: string }[] | null }[];
	let rdfName: string | null = null;
	for (const row of owlRows) {
		const related = (row.relations ?? []).map((link) => link.tipo);
		if (related.includes(sectionTipo)) {
			rdfName = row.term?.['lg-spa'] ?? Object.values(row.term ?? {})[0] ?? null;
			break;
		}
	}
	if (rdfName === null) return null;
	const fileName = `${sanitizePublishedFileName(`${rdfName}_${sectionTipo}_${sectionId}`)}.rdf`;
	return `${root}/rdf/${service}/${fileName}`;
}

/**
 * Unlink a file element's published copy (+ rdf legacy '{base}_*.rdf'
 * variants). True on success INCLUDING the nothing-published idempotent
 * case; false when the path is unresolvable or an unlink fails.
 */
export async function unlinkPublishedFiles(
	elementTipo: string,
	type: string,
	sectionTipo: string,
	sectionId: number,
	mediaRoot?: string,
): Promise<boolean> {
	try {
		const filePath = await resolvePublishedFilePath(
			elementTipo,
			type,
			sectionTipo,
			sectionId,
			mediaRoot,
		);
		if (filePath === null) return false; // unresolvable → pending
		const toUnlink: string[] = [];
		if (existsSync(filePath)) toUnlink.push(filePath);
		if (type === 'rdf') {
			const slash = filePath.lastIndexOf('/');
			const dir = filePath.slice(0, slash);
			const base = filePath.slice(slash + 1).replace(/\.rdf$/, '');
			if (existsSync(dir)) {
				for (const name of readdirSync(dir)) {
					if (name.startsWith(`${base}_`) && name.endsWith('.rdf')) {
						toUnlink.push(`${dir}/${name}`);
					}
				}
			}
		}
		for (const path of toUnlink) unlinkSync(path);
		return true; // empty toUnlink = already removed (idempotent)
	} catch (error) {
		console.error('published-file unlink failed:', error);
		return false;
	}
}

/** The rebuild_media_index response envelope (PHP dd_diffusion_api shape). */
export interface RebuildMediaIndexResponse {
	result: boolean;
	msg: string;
	errors: unknown[];
	markers: number;
	targets: number;
}

/**
 * PHP dd_diffusion_api::rebuild_media_index — resolve EVERY sql/socrata
 * publication target of the diffusion map and regenerate the
 * .publication/pub marker store from them through the NATIVE store (S2-31; a
 * full resync; idempotent — markers derive from the published rows). The
 * global-admin gate lives in the dispatch caller (PHP checks it in the API
 * method; TS keeps permission checks at the dispatch boundary).
 */
export async function rebuildMediaIndex(): Promise<RebuildMediaIndexResponse> {
	const response: RebuildMediaIndexResponse = {
		result: false,
		msg: 'Error. Request failed [rebuild_media_index]',
		errors: [],
		markers: 0,
		targets: 0,
	};
	try {
		const { getAllMediaIndexTargets } = await import('./diffusion_map.ts');
		const targets = await getAllMediaIndexTargets();
		response.targets = targets.length;

		if (nativeMediaIndexOps === null) {
			// DEC-19: sql targets exist but the native marker store is not
			// registered — the published surface can rot silently. Warn loudly;
			// keep the PHP empty-engine-response envelope bytes.
			if (targets.length > 0) {
				console.error(
					`[media_index] DEC-19: ${targets.length} sql publication target(s) exist but no native media-index is registered — the .publication/ marker store is NOT being maintained. Fix the boot registration (src/server.ts).`,
				);
			}
			response.msg = 'Error. Empty engine response';
			return response;
		}

		const native = await nativeMediaIndexOps.rebuild(targets);
		response.result = native.result;
		response.msg = native.msg;
		response.markers = native.markers;
		if (native.errors !== undefined && native.errors.length > 0) {
			response.errors.push(...native.errors);
		}
	} catch (error) {
		response.msg = `Error: ${(error as Error).message}`;
		response.errors.push((error as Error).message);
	}
	return response;
}
