/**
 * Diffusion unpublish on delete (PHP diffusion_delete::delete_record): a
 * deleted record's published copies leave every diffusion target.
 *
 *   - sql / socrata elements → the NATIVE in-process executor registered at
 *     boot (src/diffusion/targets/mariadb/delete_record.ts) receives
 *     [{database_name, table_name, section_ids:[id], section_tipo}] — the
 *     engine wire shape, kept verbatim across the seam;
 *   - rdf / xml / markdown elements → published-file unlinks under the
 *     media root: rdf = /rdf/{service}/{sanitize(rdfName_st_id)}.rdf (+ the
 *     legacy '{base}_*.rdf' variants), xml/markdown = /{type}/{service}/
 *     {st}_{id}.{ext}; missing service_name (this install's live rdf
 *     config) → pending; nothing published → idempotent success;
 *   - per-element outcomes land in the dd1758 diffusion log
 *     (matrix_activity_diffusion): unpublished (2) on success,
 *     unpublish_pending (3) on failure — retryPendingDiffusion() re-runs the
 *     pending rows and flips them in place (PHP retry_pending, DIFFU-08
 *     rule: only flip when the retry actually resolved targets).
 *
 * No registered executor → DEC-19 loud warning + pending rows (see
 * deleteDiffusionRecord); no targets → silent no-op, matching a fresh
 * install. The old-engine unix-socket/token transport
 * (DEDALO_DIFFUSION_SOCKET_PATH / DEDALO_DIFFUSION_INTERNAL_TOKEN) was
 * retired at the 2026-07-11 cutover (DIFFUSION_PLAN P5 step 3;
 * rewrite/CUTOVER_RUNBOOK.md §5) — the native paths are primary since S2-31.
 */

import { existsSync, readdirSync, unlinkSync } from 'node:fs';
import { readEnv } from '../../config/env.ts';
import { canonicalizeStoredSectionId } from '../concepts/section_id.ts';
import { sql } from '../db/postgres.ts';
import { DedaloError } from '../errors/index.ts';
import { relationProbeGroups } from '../search/containment.ts';
import { virtualDateNow } from '../section/record/create_record.ts';
import type { DiffusionSqlTarget } from './diffusion_graph.ts';
import { getSectionDiffusionTargets } from './diffusion_map.ts';

export interface DiffusionDeleteOutcome {
	/** db|table keys the engine confirmed deleted. */
	deleted: string[];
	/** Targets that failed or were ledgered (rdf/xml/markdown). */
	pending: string[];
}

/**
 * TEST-ONLY dd1758 activity-table override (the DIFFUSION_JOBS_TABLE seam
 * twin — S1-17/DEC-18a pattern). Every dd1758 read/write funnels through this
 * module; without the seam, a test's retryPendingDiffusion selects the oldest
 * pending rows of the REAL matrix_activity_diffusion — its stub engine can
 * flip REAL pending rows to 'unpublished' without any actual delete, and ≥10
 * older real rows starve the test's probe rows (the ledgered intermittent).
 * The bun-test preload (test/preload/session_db.ts) points
 * DIFFUSION_ACTIVITY_TABLE at a per-run scratch table. Guard: an override
 * MUST carry the scratch prefix `dedalo_ts_test_` — production (including the
 * live dev server's delete executor) can never be redirected; no env → the
 * real 'matrix_activity_diffusion'.
 */
function resolveActivityTable(): string {
	// readEnv (not process.env) per the S2-21 config rule; the bun-test preload
	// sets this in the real process env, which wins the precedence chain anyway,
	// and the dedalo_ts_test_ guard below keeps ANY source from redirecting
	// production to an arbitrary table.
	const override = readEnv('DIFFUSION_ACTIVITY_TABLE');
	if (override === undefined || override === '') {
		return 'matrix_activity_diffusion';
	}
	if (!/^dedalo_ts_test_[a-z0-9_]*$/.test(override)) {
		throw new Error(
			`DIFFUSION_ACTIVITY_TABLE override '${override}' rejected: it is a TEST seam and must match /^dedalo_ts_test_[a-z0-9_]*$/.`,
		);
	}
	return override;
}

export const DIFFUSION_ACTIVITY_TABLE = resolveActivityTable();

let activityTableEnsured: Promise<void> | null = null;

/**
 * Scratch-table bootstrap. The REAL matrix_activity_diffusion is PHP-owned
 * (install/db/matrix_activity_diffusion.sql) — never touched here. When the
 * test seam is active the scratch twin must exist before the first write;
 * columns mirror the PHP DDL (the subset this module and the matrix codecs
 * use), section_id keeps its own sequence default ("sequence-allocated
 * section_id", same as the real table).
 */
async function ensureActivityTable(): Promise<void> {
	if (DIFFUSION_ACTIVITY_TABLE === 'matrix_activity_diffusion') return; // PHP owns the real DDL
	if (activityTableEnsured === null) {
		activityTableEnsured = (async () => {
			await sql.unsafe(
				`CREATE SEQUENCE IF NOT EXISTS "${DIFFUSION_ACTIVITY_TABLE}_section_id_seq"`,
			);
			await sql.unsafe(`
				CREATE TABLE IF NOT EXISTS "${DIFFUSION_ACTIVITY_TABLE}" (
					id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					"timestamp" timestamp without time zone DEFAULT now(),
					section_id integer NOT NULL DEFAULT nextval('${DIFFUSION_ACTIVITY_TABLE}_section_id_seq'),
					section_tipo character varying(255) NOT NULL,
					data jsonb,
					relation jsonb,
					string jsonb,
					date jsonb,
					iri jsonb,
					geo jsonb,
					number jsonb,
					media jsonb,
					misc jsonb,
					relation_search jsonb,
					meta jsonb
				)
			`);
		})().catch((error) => {
			// A failed bootstrap must not poison the memo forever — retry next call.
			activityTableEnsured = null;
			throw error;
		});
	}
	return activityTableEnsured;
}

/** One sql/socrata delete target handed to the executor (engine wire shape). */
export interface NativeSqlDeleteTarget {
	database_name: string;
	table_name: string;
	section_ids: (number | string)[];
	section_tipo?: string;
}

type NativeSqlDeleteExecutor = (
	targets: NativeSqlDeleteTarget[],
) => Promise<{ deleted: string[]; errors: string[] }>;

/**
 * Native in-process SQL delete executor, registered by the diffusion module
 * at boot (src/diffusion/targets/mariadb/delete_record.ts). Registration seam
 * instead of an import because core must never import src/diffusion/**
 * (DIFFUSION_SPEC §2.5 boundary; ragRecordHook precedent). While unregistered
 * there is NO fallback (the old-engine socket retired at the 2026-07-11
 * cutover): sql deletes go pending with the DEC-19 loud warning.
 */
let nativeSqlDeleteExecutor: NativeSqlDeleteExecutor | null = null;

export function registerNativeDiffusionSqlDelete(executor: NativeSqlDeleteExecutor): void {
	nativeSqlDeleteExecutor = executor;
}

/** Test hook: drop the registered executor (restores the DEC-19 pending state). */
export function resetNativeDiffusionSqlDeleteForTests(): void {
	nativeSqlDeleteExecutor = null;
}

/**
 * Native media-index (publication-marker store) operations, registered by the
 * diffusion module at boot (src/diffusion/targets/mediastore/media_index.ts)
 * through the same seam pattern as the SQL delete executor (S2-31 port).
 * While unregistered there is NO fallback: rebuild reports the DEC-19 loud
 * error (the old-engine socket retired at the 2026-07-11 cutover).
 */
export interface NativeMediaIndexOps {
	/**
	 * The FOREIGN shape of src/diffusion/targets/mediastore/media_index.ts
	 * (`rebuildMediaIndexStore`) — declared here as the seam contract, owned
	 * there. Its `result` flag is that module's field name, not a wire body:
	 * `rebuildMediaIndex` below turns a false one into a typed throw.
	 */
	rebuild(
		targets: { database_name: string; table_name: string; section_tipo: string }[],
	): Promise<{ result: boolean; msg: string; markers: number; errors?: string[] }>;
	getStatus(): Promise<{
		enabled: boolean;
		base: string | null;
		pub_markers: number;
		auth_markers: number;
		databases: string[];
	}>;
	reconcile(): Promise<{ added: number; removed: number } | null>;
}

let nativeMediaIndexOps: NativeMediaIndexOps | null = null;

export function registerNativeMediaIndex(ops: NativeMediaIndexOps): void {
	nativeMediaIndexOps = ops;
}

/** The registered native media-index ops (null while unregistered). */
export function getNativeMediaIndexOps(): NativeMediaIndexOps | null {
	return nativeMediaIndexOps;
}

/** Test hook: drop the registered ops (restores the DEC-19 unregistered state). */
export function resetNativeMediaIndexForTests(): void {
	nativeMediaIndexOps = null;
}

/** Propagate a record deletion to the diffusion targets. Never throws. */
export async function deleteDiffusionRecord(
	sectionTipo: string,
	sectionId: number,
	/** false when a retry drives the call (the pending row IS the log). */
	logActivity = true,
	/** The acting user for the dd1758 ledger; absent → dd1762 omitted. */
	userId?: number,
	/**
	 * Restrict the run to these element tipos (PHP retry_pending's
	 * `only_element_tipos`). The retry loop passes the pending row's dd1766
	 * element so its flip criterion is that element's outcome, never the
	 * record's; absent → every element of the section.
	 */
	onlyElementTipos?: readonly string[],
): Promise<DiffusionDeleteOutcome> {
	const outcome: DiffusionDeleteOutcome = { deleted: [], pending: [] };
	// Hoisted so the dd1758 fold below sees the SAME (restricted) target set
	// this run acted on — and is reached on every path that produced one.
	let targets: readonly DiffusionSqlTarget[] = [];
	try {
		targets = restrictToElements(await getSectionDiffusionTargets(sectionTipo), onlyElementTipos);

		const sqlTargets = targets.filter(
			(target) =>
				(target.type === 'sql' || target.type === 'socrata') &&
				target.database_name !== '' &&
				target.table_name !== '',
		);
		for (const target of targets) {
			if (target.type !== 'sql' && target.type !== 'socrata') {
				const unlinked = await unlinkPublishedFiles(
					target.element_tipo,
					target.type,
					sectionTipo,
					sectionId,
				);
				if (unlinked) outcome.deleted.push(targetKey(target));
				else outcome.pending.push(targetKey(target));
			}
		}

		// NATIVE path (DIFFUSION_SPEC §4.2) — the ONLY executor since the
		// 2026-07-11 cutover: MariaDB deletes run through the registered
		// in-process executor, then execution falls through to the dd1758
		// ledger below. No sql target → nothing to execute, and execution
		// falls through to that same ledger (D10, fixed 2026-08-09: the old
		// `if (sqlTargets.length === 0) return outcome;` returned first and
		// left a file-only section's failed unlink with no pending row).
		if (sqlTargets.length > 0) {
			if (nativeSqlDeleteExecutor === null) {
				// DEC-19: sql targets exist but no native executor is registered —
				// delete propagation is NOT running and published rows/markers will
				// rot. Loud, per DECISIONS.md:391-395. (No dd1758 rows here — the
				// deliberate fresh-install no-op posture; with the executor
				// registered at boot this branch only fires when that registration
				// failed, which server.ts already reports as FATAL-FOR-DELETES.)
				console.error(
					`[diffusion] DEC-19: record ${sectionTipo}/${sectionId} has ${sqlTargets.length} sql publication target(s) but no native delete executor is registered — unpublish is deferred to pending rows. Fix the boot registration (src/server.ts).`,
				);
				for (const target of sqlTargets) {
					outcome.pending.push(targetKey(target));
				}
				return outcome;
			}
			await executeNativeSqlDeletes(
				nativeSqlDeleteExecutor,
				sqlTargets,
				sectionTipo,
				sectionId,
				outcome,
			);
		}
	} catch (error) {
		console.error('diffusion unpublish failed (swallowed, pending rows persist):', error);
	}
	await logUnpublishOutcome(targets, sectionTipo, sectionId, outcome, logActivity, userId);
	return outcome;
}

/**
 * Keep only the named elements (PHP retry_pending's `only_element_tipos`).
 * An absent/empty restriction means "every element", never "no element".
 */
function restrictToElements(
	targets: readonly DiffusionSqlTarget[],
	onlyElementTipos: readonly string[] | undefined,
): readonly DiffusionSqlTarget[] {
	if (onlyElementTipos === undefined || onlyElementTipos.length === 0) return targets;
	return targets.filter((target) => onlyElementTipos.includes(target.element_tipo));
}

/** Hand the sql/socrata targets to the registered executor and record each outcome. */
async function executeNativeSqlDeletes(
	executor: NativeSqlDeleteExecutor,
	sqlTargets: readonly DiffusionSqlTarget[],
	sectionTipo: string,
	sectionId: number,
	outcome: DiffusionDeleteOutcome,
): Promise<void> {
	const native = await executor(
		sqlTargets.map((target) => ({
			database_name: target.database_name,
			table_name: target.table_name,
			section_ids: [sectionId],
			section_tipo: sectionTipo, // enables media marker removal in the store
		})),
	);
	const confirmed = new Set(native.deleted);
	for (const target of sqlTargets) {
		const key = targetKey(target);
		if (confirmed.has(key)) outcome.deleted.push(key);
		else outcome.pending.push(key);
	}
	if (native.errors.length > 0) {
		console.error('diffusion unpublish reported errors:', native.errors);
	}
}

/**
 * The outcome-ledger key of a target — the SINGLE producer of the strings
 * pushed into DiffusionDeleteOutcome.deleted/pending, so the fold below reads
 * the same grammar the delete path wrote (DIFF-A class of drift):
 * sql/socrata → `db|table`, file elements → `type:element_tipo`.
 */
export function targetKey(target: DiffusionSqlTarget): string {
	return target.type === 'sql' || target.type === 'socrata'
		? `${target.database_name}|${target.table_name}`
		: `${target.type}:${target.element_tipo}`;
}

/**
 * Fold per-target confirmations into per-element outcomes: an element is
 * successful ONLY when EVERY one of its targets confirmed (AND, not OR — one
 * unconfirmed target poisons its element). Elements fold independently; the
 * `?? true` seed makes the first target of an element decide on its own.
 */
export function foldElementOutcomes(
	targets: readonly DiffusionSqlTarget[],
	deletedKeys: ReadonlySet<string>,
): Map<string, boolean> {
	const elements = new Map<string, boolean>();
	for (const target of targets) {
		const previous = elements.get(target.element_tipo) ?? true;
		elements.set(target.element_tipo, previous && deletedKeys.has(targetKey(target)));
	}
	return elements;
}

/**
 * dd1758 diffusion log: one row per element (sql AND file) — unpublished (2)
 * when every one of its targets confirmed, unpublish_pending (3) otherwise.
 * Shared by
 * the native and engine-socket delete paths so the ledger is identical
 * regardless of executor.
 */
async function logUnpublishOutcome(
	/** The targets this run acted on — already restricted by onlyElementTipos. */
	targets: readonly DiffusionSqlTarget[],
	sectionTipo: string,
	sectionId: number,
	outcome: DiffusionDeleteOutcome,
	logActivity: boolean,
	userId?: number,
): Promise<void> {
	if (!logActivity) return;
	try {
		const elements = foldElementOutcomes(targets, new Set(outcome.deleted));
		for (const [elementTipo, success] of elements) {
			await logDiffusionActivity({
				sectionTipo,
				sectionId,
				elementTipo,
				action: success ? 2 : 3, // unpublished | unpublish_pending
				userId,
			});
		}
	} catch (error) {
		console.error('diffusion log write failed (swallowed):', error);
	}
}

/** dd1767 action ids (PHP diffusion_activity_logger). */
export const DIFFUSION_ACTION = { published: 1, unpublished: 2, unpublishPending: 3 } as const;

/**
 * D16 — THE ACTION IS NOT AN ADDRESS.
 *
 * PHP wrote the dd1767 action id into a locator's `section_id`, pointing at a
 * `dd1774` section that does not exist in the ontology and holds no records:
 * the field named "record address" carried an ENUM TOKEN. Under
 * WC-2026-08-10-section-id-int-canonical every `section_id` in the matrix is a
 * record address, so the token gets its own key and stops lying:
 *
 *     { type, diffusion_action: 3, section_tipo: 'dd1774', from_component_tipo }
 *
 * `section_tipo: 'dd1774'` stays — it is the ledger's discriminator, and the
 * probes below key on it. WRITE NEW, READ BOTH: rows written before this change
 * (and rows whose legacy `section_id` a canonicalization sweep has since turned
 * from '3' into 3) are still matched by diffusionActionProbePayloads, and the
 * retry loop upgrades every row it flips to the new shape.
 */
export const DIFFUSION_ACTION_KEY = 'diffusion_action';
const DIFFUSION_ACTION_SECTION = 'dd1774';
const DIFFUSION_ACTION_COMPONENT = 'dd1767';

/**
 * Every stored shape of "the dd1767 action is `action`", as jsonb containment
 * payloads to OR together: the new explicit-key shape first, then the two
 * typed forms of the legacy locator shape (string and int section_id — the
 * dual-probe law of core/search/containment.ts).
 */
export function diffusionActionProbePayloads(action: number): string[] {
	const legacy = relationProbeGroups(DIFFUSION_ACTION_COMPONENT, [
		{ section_id: String(action), section_tipo: DIFFUSION_ACTION_SECTION },
	])[0] as string[];
	return [
		`{"${DIFFUSION_ACTION_COMPONENT}":[{"${DIFFUSION_ACTION_KEY}":${action},"section_tipo":"${DIFFUSION_ACTION_SECTION}"}]}`,
		...legacy,
	];
}

/**
 * The shape-tolerant SQL predicate for the probe payloads above. `bind` maps a
 * payload to its placeholder — callers bind, never inline (the payloads are
 * built from numeric constants here, but the discipline is the module's).
 */
export function diffusionActionContains(
	columnRef: string,
	action: number,
	bind: (payload: string) => string,
): string {
	const ors = diffusionActionProbePayloads(action).map(
		(payload) => `${columnRef} @> ${bind(payload)}::text::jsonb`,
	);
	return `(${ors.join(' OR ')})`;
}

/**
 * Append one dd1758 diffusion-log row (matrix_activity_diffusion, sequence-
 * allocated section_id): dd1762 user, dd1763 processed-record locator,
 * dd1764 section_id number, dd1765 section_tipo string, dd1766 element
 * locator ({tld}0 / numeric part — the ontology-node-as-record convention),
 * dd1767 action (see DIFFUSION_ACTION_KEY).
 *
 * Every locator section_id is minted in canonical INT form
 * (WC-2026-08-10-section-id-int-canonical) — the ledger's addresses are matrix
 * record addresses, and readers below read them through `->>` (text either way)
 * or through the dual-form probes.
 *
 * dd1762 records the REAL acting user; when no userId reaches us the field is
 * OMITTED entirely (PHP diffusion_activity_logger `if ($user_id)`) — never a
 * fabricated superuser −1 locator.
 */
export async function logDiffusionActivity(entry: {
	sectionTipo: string;
	sectionId: number;
	elementTipo: string | null;
	action: number;
	userId?: number;
	now?: Date;
}): Promise<void> {
	const now = entry.now ?? new Date();
	const relation: Record<string, unknown[]> = {
		dd1763: [
			{
				type: 'dd151',
				section_id: entry.sectionId,
				section_tipo: entry.sectionTipo,
				from_component_tipo: 'dd1763',
			},
		],
		[DIFFUSION_ACTION_COMPONENT]: [
			{
				type: 'dd151',
				// D16: the action token rides its OWN key, never section_id.
				[DIFFUSION_ACTION_KEY]: entry.action,
				section_tipo: DIFFUSION_ACTION_SECTION,
				from_component_tipo: DIFFUSION_ACTION_COMPONENT,
			},
		],
	};
	// Truthiness on purpose — PHP's `if ($user_id)`: 0/undefined/NaN → omit.
	if (entry.userId) {
		relation.dd1762 = [
			{
				type: 'dd151',
				section_id: entry.userId,
				section_tipo: 'dd128',
				from_component_tipo: 'dd1762',
			},
		];
	}
	if (entry.elementTipo !== null) {
		const match = entry.elementTipo.match(/^([a-z]+)([0-9]+)$/);
		if (match !== null) {
			relation.dd1766 = [
				{
					type: 'dd151',
					// digits of the element tipo as an address: canonical int
					// (canonicalize, not Number — a padded id would be preserved
					// rather than silently renumbered).
					section_id: canonicalizeStoredSectionId(match[2]),
					section_tipo: `${match[1]}0`,
					from_component_tipo: 'dd1766',
				},
			];
		}
	}
	const { encodeForJsonb } = await import('../db/json_codec.ts');
	await ensureActivityTable();
	await sql.unsafe(
		`INSERT INTO "${DIFFUSION_ACTIVITY_TABLE}" (section_tipo, relation, string, date, number, misc)
		 VALUES ('dd1758', $1::text::jsonb, $2::text::jsonb, $3::text::jsonb, $4::text::jsonb, '{}'::text::jsonb)`,
		[
			encodeForJsonb(relation),
			encodeForJsonb({ dd1765: [{ lang: 'lg-nolan', value: entry.sectionTipo }] }),
			encodeForJsonb({ dd1761: [{ start: virtualDateNow(now) }] }),
			encodeForJsonb({ dd1764: [{ value: entry.sectionId }] }),
		],
	);
}

/**
 * Re-run pending unpublish rows (PHP diffusion_delete::retry_pending): read
 * dd1758 rows whose dd1767 action is unpublish_pending, re-run the delete
 * restricted to the row's element, and flip the action locator IN PLACE to
 * unpublished — only when the retry actually confirmed targets (DIFFU-08).
 */
export async function retryPendingDiffusion(
	limit = 100,
): Promise<{ total: number; retried: number; remaining: number }> {
	await ensureActivityTable();
	// `->>` yields text for a stored int as well as a stored string, so the
	// projected target/element ids read identically in both typed forms; only
	// the ACTION probe needs the shape tolerance (D16 + dual-form).
	const pendingParams: string[] = [];
	const pendingProbe = diffusionActionContains(
		'relation',
		DIFFUSION_ACTION.unpublishPending,
		(payload) => `$${pendingParams.push(payload)}`,
	);
	const rows = (await sql.unsafe(
		`SELECT section_id,
		        relation->'dd1763'->0->>'section_tipo' AS target_section,
		        relation->'dd1763'->0->>'section_id' AS target_id,
		        relation->'dd1766'->0->>'section_tipo' AS element_section,
		        relation->'dd1766'->0->>'section_id' AS element_id
		 FROM "${DIFFUSION_ACTIVITY_TABLE}"
		 WHERE section_tipo = 'dd1758'
		   AND ${pendingProbe}
		 ORDER BY section_id ASC LIMIT ${Math.max(1, Math.floor(limit))}`,
		pendingParams,
	)) as {
		section_id: number;
		target_section: string | null;
		target_id: string | null;
		element_section: string | null;
		element_id: string | null;
	}[];
	const outcome = { total: rows.length, retried: 0, remaining: 0 };
	for (const row of rows) {
		if (row.target_section === null || row.target_id === null) {
			outcome.remaining++;
			continue;
		}
		const element = pendingRowElementTipo(row.element_section, row.element_id);
		const retry = await deleteDiffusionRecord(
			row.target_section,
			Number(row.target_id),
			false, // the pending row already represents the intent — no new rows
			undefined,
			// D10b (fixed 2026-08-09): restrict the retry to THIS row's element
			// (PHP retry_pending `only_element_tipos`). Without it the flip below
			// — record-level `retry.deleted.length > 0` — marks a still-failing
			// element 'unpublished' because a SIBLING element succeeded.
			element === null ? undefined : [element],
		);
		if (retry.deleted.length > 0) {
			// Flip unpublish_pending → unpublished in place, AND upgrade the
			// element to the D16 shape in the same statement: drop whatever
			// legacy `section_id` token the row carried (string '3' or the int 3
			// a canonicalization sweep left) and stamp the action under its own
			// key. Shape-agnostic, so it is correct for old and new rows alike.
			await sql.unsafe(
				`UPDATE "${DIFFUSION_ACTIVITY_TABLE}"
				 SET relation = jsonb_set(
				         relation,
				         '{${DIFFUSION_ACTION_COMPONENT},0}',
				         ((relation->'${DIFFUSION_ACTION_COMPONENT}'->0) - 'section_id')
				             || jsonb_build_object('${DIFFUSION_ACTION_KEY}', $2::int)
				     )
				 WHERE section_tipo = 'dd1758' AND section_id = $1`,
				[row.section_id, DIFFUSION_ACTION.unpublished],
			);
			outcome.retried++;
		} else {
			outcome.remaining++;
		}
	}
	return outcome;
}

/**
 * Rebuild an element tipo from a dd1766 locator — the inverse of the
 * ontology-node-as-record encoding logDiffusionActivity writes
 * ({tld}0 / numeric part → 'zzd0' + '7' = 'zzd7'). Null when the row carries
 * no element locator (a record-level pending row): the retry then runs
 * unrestricted, exactly as before.
 */
export function pendingRowElementTipo(
	elementSection: string | null,
	elementId: string | null,
): string | null {
	if (elementSection === null || elementId === null) return null;
	const match = elementSection.match(/^([a-z]+)0$/);
	if (match === null) return null;
	return `${match[1]}${elementId}`;
}

/** PHP sanitize_file_name + beautify (delete-side subset: dash-safe names). */
export function sanitizePublishedFileName(name: string): string {
	let out = name.replace(/[^\w\s\d\-_~,;[\]().]/gu, '');
	out = out.replace(/\.{2,}/g, '');
	out = out.toLowerCase().replace(/[^a-z0-9.]+/g, '-');
	out = out.replace(/[\s_]+/g, '-').replace(/-+/g, '-');
	out = out.replace(/-*\.-*/g, '.').replace(/\.{2,}/g, '.');
	return out.replace(/^[-.]+|[-.]+$/g, '');
}

/**
 * Resolve one file element's published path (PHP diffusion_rdf/xml/markdown
 * get_record_file_path). Null when the element declares no service_name —
 * the live rdf config here — which the caller records as pending.
 */
export async function resolvePublishedFilePath(
	elementTipo: string,
	type: string,
	sectionTipo: string,
	sectionId: number,
	mediaRoot?: string,
): Promise<string | null> {
	const root = mediaRoot ?? readEnv('MEDIA_PATH');
	if (root === undefined || root === '') return null;
	const propsRows = (await sql.unsafe(
		`SELECT properties->'diffusion'->>'service_name' AS service FROM dd_ontology WHERE tipo = $1`,
		[elementTipo],
	)) as { service: string | null }[];
	const service = propsRows[0]?.service ?? null;
	if (service === null || service === '') return null;

	if (type === 'xml' || type === 'markdown') {
		const extension = type === 'xml' ? 'xml' : 'md';
		return `${root}/${type}/${service}/${sectionTipo}_${sectionId}.${extension}`;
	}
	// rdf: the owl:Class child whose related section matches names the file.
	const owlRows = (await sql.unsafe(
		`SELECT term, relations FROM dd_ontology WHERE parent = $1 AND model = 'owl:Class'`,
		[elementTipo],
	)) as { term: Record<string, string> | null; relations: { tipo?: string }[] | null }[];
	let rdfName: string | null = null;
	for (const row of owlRows) {
		const related = (row.relations ?? []).map((link) => link.tipo);
		if (related.includes(sectionTipo)) {
			rdfName = row.term?.['lg-spa'] ?? Object.values(row.term ?? {})[0] ?? null;
			break;
		}
	}
	if (rdfName === null) return null;
	const fileName = `${sanitizePublishedFileName(`${rdfName}_${sectionTipo}_${sectionId}`)}.rdf`;
	return `${root}/rdf/${service}/${fileName}`;
}

/**
 * Unlink a file element's published copy (+ rdf legacy '{base}_*.rdf'
 * variants). True on success INCLUDING the nothing-published idempotent
 * case; false when the path is unresolvable or an unlink fails.
 */
export async function unlinkPublishedFiles(
	elementTipo: string,
	type: string,
	sectionTipo: string,
	sectionId: number,
	mediaRoot?: string,
): Promise<boolean> {
	try {
		const filePath = await resolvePublishedFilePath(
			elementTipo,
			type,
			sectionTipo,
			sectionId,
			mediaRoot,
		);
		if (filePath === null) return false; // unresolvable → pending
		const toUnlink: string[] = [];
		if (existsSync(filePath)) toUnlink.push(filePath);
		if (type === 'rdf') {
			const slash = filePath.lastIndexOf('/');
			const dir = filePath.slice(0, slash);
			const base = filePath.slice(slash + 1).replace(/\.rdf$/, '');
			if (existsSync(dir)) {
				for (const name of readdirSync(dir)) {
					if (name.startsWith(`${base}_`) && name.endsWith('.rdf')) {
						toUnlink.push(`${dir}/${name}`);
					}
				}
			}
		}
		for (const path of toUnlink) unlinkSync(path);
		return true; // empty toUnlink = already removed (idempotent)
	} catch (error) {
		console.error('published-file unlink failed:', error);
		return false;
	}
}

/**
 * What a completed rebuild REPORTS. Not a wire body: `msg` and `markers` are
 * top-level extension keys the media_control panel reads by name
 * (render_media_control.js :543-545), and the caller is the one that puts them
 * on an `ok(...)` envelope. A rebuild that did NOT complete THROWS.
 */
export interface RebuildMediaIndexReport {
	/** Operator sentence the panel prints. */
	msg: string;
	/** Non-fatal per-target findings the store reported. */
	errors: string[];
	markers: number;
	targets: number;
}

/**
 * PHP dd_diffusion_api::rebuild_media_index — resolve EVERY sql/socrata
 * publication target of the diffusion map and regenerate the
 * .publication/pub marker store from them through the NATIVE store (S2-31; a
 * full resync; idempotent — markers derive from the published rows). The
 * global-admin gate lives in the dispatch caller (PHP checks it in the API
 * method; TS keeps permission checks at the dispatch boundary).
 *
 * FAILURE IS A THROW (envelope v2): `media.operation_failed` carries the
 * operator sentence as its public message, and the original exception rides as
 * `cause` — a raw exception string never reaches a wire field again.
 */
export async function rebuildMediaIndex(): Promise<RebuildMediaIndexReport> {
	const { getAllMediaIndexTargets } = await import('./diffusion_map.ts');
	let targets: { database_name: string; table_name: string; section_tipo: string }[];
	try {
		targets = await getAllMediaIndexTargets();
	} catch (error) {
		throw new DedaloError('media.operation_failed', {
			cause: error,
			coordinates: { operation: 'rebuild_media_index.resolve_targets' },
		});
	}

	if (nativeMediaIndexOps === null) {
		// DEC-19: sql targets exist but the native marker store is not
		// registered — the published surface can rot silently. Loud, and a
		// refusal: an "empty engine response" reported as success is how the
		// marker store rots unnoticed.
		if (targets.length > 0) {
			console.error(
				`[media_index] DEC-19: ${targets.length} sql publication target(s) exist but no native media-index is registered — the .publication/ marker store is NOT being maintained. Fix the boot registration (src/server.ts).`,
			);
		}
		throw new DedaloError('media.operation_failed', {
			publicMessage: 'Error. Empty engine response',
			coordinates: { operation: 'rebuild_media_index', targets: targets.length },
		});
	}

	let native: Awaited<ReturnType<NativeMediaIndexOps['rebuild']>>;
	try {
		native = await nativeMediaIndexOps.rebuild(targets);
	} catch (error) {
		throw new DedaloError('media.operation_failed', {
			cause: error,
			coordinates: { operation: 'rebuild_media_index', targets: targets.length },
		});
	}
	const errors = native.errors ?? [];
	if (native.result !== true) {
		// The store's own sentence is engine-authored (never caller data), so it
		// is the one worth showing the operator; the per-target findings go to
		// the log, which is the only place that keeps them all.
		if (errors.length > 0) {
			console.error('[media_index] rebuild reported errors:', errors);
		}
		throw new DedaloError('media.operation_failed', {
			publicMessage: native.msg,
			coordinates: { operation: 'rebuild_media_index', targets: targets.length },
		});
	}
	return { msg: native.msg, errors, markers: native.markers, targets: targets.length };
}
