<?php

	# VISUALIZADOR HTML
	$html_tool  ='';
	$html_tool .= "<div id=\"button_update_cache\" class=\"css_button_generic btn_inside_section_buttons_container\"
	onclick=\"tool_update_cache.update_cache(this,{'section_tipo':'$this->section_tipo'})\"
	title=\"$button_title\">";
	$html_tool .= "<span>".label::get_label('update_cache')."</span>";
	$html_tool .= "</div>";
	
	
	# PRINT HTML
	echo $html_tool;
	
?>