// @license magnet:?xt=urn:btih:0b31508aeb0634b347b8270c7bee4d411b5d4109&dn=agpl-3.0.txt AGPL-3.0
/*global get_label, page_globals, SHOW_DEBUG, DEDALO_LIB_URL*/
/*eslint no-undef: "error"*/



// imports
	import {ui} from '../../common/js/ui.js'
	import {open_tool} from '../../../core/tools_common/js/tool_common.js'
	import {when_in_viewport,dd_request_idle_callback} from '../../common/js/events.js'



/**
* VIEW_DEFAULT_EDIT_AV
* Standard edit-mode view for the audio/video component.
*
* Renders a media wrapper containing a posterframe image and, when a processed
* video file is available, an HTML5 <video> element that is lazily loaded only
* once the component enters the browser viewport (see get_content_value). When
* no video file is available, clicking the posterframe opens the upload tool so
* the operator can supply the source file.
*
* Exports:
*  - view_default_edit_av          — empty constructor (view namespace)
*  - view_default_edit_av.render   — async factory; returns the component wrapper
*
* DOM tree produced by render:
*   .wrapper_component
*     .content_data.media_content_data
*       .content_value.media_content_value   (one per entry; built asynchronously)
*         <img class="posterframe">           (static poster; replaced once video loads)
*         <video class="posterframe hide">    (present only when video_url is resolved)
*         <select class="quality_selector">   (present only when video file exists)
*     .buttons_container
*       .buttons_fold
*         [tool buttons] [.button.full_screen]
*
* Consumed globals (declared via // @license pragma and /*global*\/):
*   - page_globals.fallback_image  — URL of the default placeholder image
*   - DEDALO_MEDIA_URL             — base URL for all stored media files
*   - SHOW_DEBUG                   — runtime flag for verbose console output
*   - get_label                    — localised label map
*
* Relevant self properties (populated by component_common.prototype.init):
*   - self.data.entries            — Array of entry objects; each entry carries a
*                                    `files_info` array with per-quality file records
*   - self.data.posterframe_url    — Path (relative to DEDALO_MEDIA_URL) to the JPEG
*                                    posterframe generated by FFmpeg
*   - self.quality                 — Active quality label, e.g. '404', overrides context
*   - self.context.features.quality — Fallback quality label from the ontology features
*   - self.context.features.extension — Media file extension filter used by quality selector
*   - self.permissions             — 1 = read-only, 2+ = full edit
*   - self.show_interface.tools    — Whether tool buttons should be rendered
*   - self.show_interface.button_fullscreen — Whether the fullscreen button is rendered
*   - self.tools                   — Array of tool context objects (model, tipo, etc.)
*   - self.view                    — Current view name ('default'|'line'|'print')
*/
export const view_default_edit_av = function() {

	return true
}//end  view_default_edit_av



/**
* RENDER
* Async factory: builds the full component wrapper for the default edit view.
*
* When render_level === 'content', the wrapper shell is skipped and only the
* content_data node is returned. This is used by the component refresh mechanism
* to swap inner content without rebuilding the outer frame.
*
* The label node is suppressed (wrapper_options.label = null) in 'line' view
* because the grid layout already provides a column header.
*
* @param {Object} self - Component instance (see VIEW_DEFAULT_EDIT_AV above for properties).
* @param {Object} options - Render options.
* @param {string} [options.render_level='full'] - 'full' builds the complete wrapper;
*   'content' returns only the content_data node.
* @returns {Promise<HTMLElement>} The .wrapper_component element, or the .content_data
*   element when render_level === 'content'.
*/
view_default_edit_av.render = async function(self, options) {

	// options
		const render_level = options.render_level || 'full'

	// content_data
		const content_data = get_content_data_edit(self)
		if (render_level==='content') {
			return content_data
		}

	// buttons
		const buttons = (self.permissions > 1)
			? get_buttons(self)
			: null

	// wrapper. ui build_edit returns component wrapper
		const wrapper_options = {
			content_data	: content_data,
			buttons			: buttons,
			add_styles		: ['media_wrapper'] // common media classes
		}
		if (self.view==='line') {
			wrapper_options.label = null // prevent to create label node
		}
		const wrapper = ui.component.build_wrapper_edit(self, wrapper_options)
		// set pointers to content_data
		wrapper.content_data = content_data


	return wrapper
}//end render



/**
* GET_CONTENT_DATA_EDIT
* Builds the content_data container and schedules per-entry content_value
* nodes via dd_request_idle_callback so that each entry is rendered in its
* own browser idle task, avoiding long-task jank on sections with many entries.
*
* Each built content_value is appended to content_data and also stored as a
* numeric index pointer (content_data[i]) for later programmatic access by
* refresh logic.
*
* The guard `if (self.status==='destroyed')` inside each callback prevents
* stale idle tasks from touching a component that was torn down before the
* task ran — important for fast navigation between records.
*
* (!) entries is normalised to [null] when empty so that at least one
*     content_value slot is always rendered, giving the operator a visible
*     upload affordance even for empty records.
*
* @param {Object} self - Component instance.
* @returns {HTMLElement} The .content_data.media_content_data container element.
*/
const get_content_data_edit = function(self) {

	// short vars
		const data		= self.data || {}
		const entries	= data.entries || []

	// content_data
		const content_data = ui.component.build_content_data(self)
		// common media classes
		content_data.classList.add('media_content_data')

	// values (inputs)
		const inputs_value		= (entries.length>0) ? entries : [null] // force one empty input at least
		const entries_length	= inputs_value.length
		for (let i = 0; i < entries_length; i++) {
			// force use new separate task
			dd_request_idle_callback(
				() => {
					// status check. If instance is destroyed, return
					if (self.status==='destroyed') return

					const content_value = (self.permissions===1)
						? get_content_value(i, inputs_value[i], self)
						: get_content_value(i, inputs_value[i], self)
					content_data.appendChild(content_value)
					// set pointer
					content_data[i] = content_value
				}
			)
		}


	return content_data
}//end get_content_data_edit



/**
* GET_CONTENT_VALUE
* Builds a single .content_value element for one AV entry.
*
* Rendering strategy:
*  1. A <img class="posterframe"> is always rendered first as a static fallback
*     while the video is not yet available or not in the viewport.
*  2. When a processed video file is found (`file_info.file_exist === true`), a
*     <video> element is created in the hidden state and placed in front of the
*     poster image via prepend(). A viewport observer (when_in_viewport) delays
*     setting video.src until the element is scrolled into view, conserving
*     browser network resources. Once visible, the posterframe <img> is removed
*     from the DOM because the video element's own poster attribute takes over.
*  3. When no video file is found, the posterframe image becomes a clickable
*     affordance that opens tool_upload so the operator can supply the file.
*  4. In 'print' view (self.view === 'print'), only the posterframe is returned;
*     no interactive video or quality selector is built.
*
* Poster image error handling: if the posterframe URL fails to load (e.g. no
* posterframe has been generated yet), the src falls back to
* page_globals.fallback_image; the fallback itself is never retried to prevent
* infinite error loops.
*
* networkState interpretation (HTML Media spec §4.8.11.5):
*   0 = NETWORK_EMPTY, 1 = NETWORK_IDLE, 2 = NETWORK_LOADING, 3 = NETWORK_NO_SOURCE
*   Values > 2 indicate that the browser cannot load the resource.
*
* Cache busting: all media URLs receive a `?t=<timestamp>` query string so that
* browsers do not serve a stale cached file after a re-transcode or posterframe
* regeneration.
*
* (!) The permissions===1 branch currently calls the same get_content_value path
*     as the edit branch. The conditional is a documented no-op placeholder for
*     a future read-only rendering variant. See commented-out
*     get_content_value_read below.
*
* @param {number} i - Zero-based entry index within self.data.entries.
* @param {Object|null} current_value - The entry object at index i, or null for
*   an empty record. When non-null, must carry a `files_info` array of file records
*   with shape: { quality, file_path, file_exist, extension }.
* @param {Object} self - Component instance.
* @returns {HTMLElement} The .content_value.media_content_value container element.
*/
const get_content_value = (i, current_value, self) => {

	// media url from files_info based on selected context quality
		const quality			= self.quality || self.context?.features?.quality
		const data				= self.data || {}
		const files_info		= current_value && current_value.files_info
			? current_value.files_info
			: []
		const file_info			= files_info.find(el => el.quality===quality)
		const posterframe_url	= data.posterframe_url
			? data.posterframe_url + '?t=' + (new Date()).getTime()
			: page_globals.fallback_image

	// content_value
		const content_value = ui.create_dom_element({
			element_type	: 'div',
			class_name 		: 'content_value media_content_value'
		})

	// posterframe_img
		const posterframe_img = ui.create_dom_element({
			element_type	: 'img',
			class_name		: 'posterframe',
			parent			: content_value
		})
		posterframe_img.setAttribute('height', 392)
		posterframe_img.addEventListener('error', function(e) {
			if (posterframe_img.src!==page_globals.fallback_image) {
				posterframe_img.src = page_globals.fallback_image
			}
		})
		// set posterframe_img source URL
		posterframe_img.src = posterframe_url

		// image background color
			// posterframe_img.addEventListener('load', set_bg_color, false)
			// function set_bg_color() {
			// 	this.removeEventListener('load', set_bg_color, false)
			// 	ui.set_background_image(this, content_value)
			// }

	// view_print case. No video is generated
		if (self.view === 'print') {
			return content_value
		}

	// video
		const video_url	= file_info && file_info.file_exist===true
			? DEDALO_MEDIA_URL + file_info.file_path + '?t=' + (new Date()).getTime()
			: null
		if (video_url) {

			// render the video node
			const video = build_video_node(
				posterframe_url
			)
			// fix pointer
			content_value.video = video
			// append node to content_value
			content_value.prepend(video)

			// fix pointer to allow play/pause
			self.video = video

			// observer. Set video node only when it is in viewport (to save browser resources)
			when_in_viewport(
				content_value, // node to observe
				() => { // callback function returns int timestamp

					// remove posterframe image node (video posterframe is set and we don't need it anymore)
						posterframe_img.remove()

					// error event
						video.addEventListener('error', function(e) {

							// debug
								if(SHOW_DEBUG===true) {
									console.warn('e:', e);
									console.warn('this.networkState MediaError:', this.networkState);
								}

							// if the error is caused by the video not loading
							// @see https://html.spec.whatwg.org/multipage/media.html#error-codes
								if (this.networkState > 2) {
									// add an image default
									this.setAttribute('poster', page_globals.fallback_image)
									// notify
									console.error('Network error ['+this.networkState+'] loading video:', e.target);
								}
						}, true)

					video.preload = 'metadata' // load only metadata (duration, dimensions) not full video
					video.src = video_url
					video.classList.remove('hide')
				}
			)
		}else{

			posterframe_img.classList.add('link')
			// mousedown event
			const mousedown_handler = (e) => {
				e.stopPropagation();

				const tool_upload = self.tools.find(el => el.model==='tool_upload')
				// open_tool (tool_common)
				open_tool({
					tool_context	: tool_upload,
					caller			: self
				})
			}
			posterframe_img.addEventListener('mousedown', mousedown_handler)
		}

	// quality_selector
		const quality_selector = get_quality_selector(content_value, self)
		content_value.appendChild(quality_selector)


	return content_value
}//end get_content_value



/**
* GET_CONTENT_VALUE_READ
* @param {number} i
* @param {Object|null} current_value
* @param {Object} self
* @returns {HTMLElement} content_value
*/
	// const get_content_value_read = (i, current_value, self) => {

	// 	// content_value
	// 		const content_value = ui.create_dom_element({
	// 			element_type	: 'div',
	// 			class_name 		: 'content_value read_only'
	// 		})

	// 	// posterframe
	// 		const posterframe_url	= self.data.posterframe_url
	// 		const posterframe		= ui.create_dom_element({
	// 			element_type	: 'img',
	// 			class_name		: 'posterframe',
	// 			src				: posterframe_url,
	// 			parent			: content_value
	// 		})
	// 		// image background color
	// 		posterframe.addEventListener('load', set_bg_color, false)
	// 		function set_bg_color() {
	// 			this.removeEventListener('load', set_bg_color, false)
	// 			ui.set_background_image(this, content_value)
	// 		}


	// 	return content_value
	// }//end get_content_value_read



/**
* BUILD_VIDEO_NODE
* Creates an HTML5 <video> element pre-configured for deferred autoplay:
*  - Initially hidden ('hide' CSS class) so the posterframe remains visible
*    until the viewport observer fires.
*  - preload='none' prevents the browser from downloading any video data before
*    the element enters the viewport. The observer upgrades this to 'metadata'
*    once visible.
*  - The `poster` attribute is set to posterframe_url so that a frame is shown
*    before the first video frame is decoded.
*  - tabindex=0 makes the player keyboard-accessible.
*  - height=392 matches the fixed design grid height for AV components.
*
* @param {string|null} posterframe_url - Absolute URL for the poster image, or null
*   when no posterframe exists (the video will have no poster attribute).
* @returns {HTMLElement} A configured <video> element in the hidden state.
*/
const build_video_node = (posterframe_url) => {

	// video tag
		const video	= document.createElement('video')
		video.classList.add('hide')
		if (posterframe_url) {
			video.poster = posterframe_url
		}
		video.preload	= 'none' // prevent video data loading until user interaction
		video.controls	= true
		video.classList.add('posterframe')
		video.setAttribute('tabindex', 0)
		video.setAttribute('height', 392)


	return video
}//end build_video_node



/**
* GET_QUALITY_SELECTOR
* Builds a <select> control that lets the operator switch the active quality
* level of the video playing in the sibling <video> element.
*
* Quality options are derived from `files_info` for the first entry only
* (`entries[0]`): only records where `file_exist === true` and `extension`
* matches `self.context.features.extension` are offered, so the operator
* never sees a quality level whose file has not yet been transcoded.
*
* The selected option is pre-set to the current active quality
* (self.quality ?? self.context.features.quality) so the control reflects the
* rendering state on first paint.
*
* Cache busting: each option value URL carries a `?t=<timestamp>` so that
* switching quality always fetches the latest transcoded file.
*
* The change event sets video.src directly. The video element is accessed via
* `content_value.video` (a pointer set by get_content_value before this function
* is called). If the video pointer is undefined (e.g. no processed file exists),
* no <option> elements will be added and the selector is empty.
*
* @param {HTMLElement} content_value - The parent .content_value node that must
*   already carry a `video` property pointing to the sibling <video> element.
* @param {Object} self - Component instance.
* @returns {HTMLElement} The configured <select class="quality_selector"> element,
*   wrapped inside a DocumentFragment during construction then returned directly.
*/
const get_quality_selector = (content_value, self) => {

	// short vars
		const data			= self.data || {}
		const entries		= data.entries || []
		const files_info	= entries[0] && entries[0].files_info
			? entries[0].files_info
			: []
		const quality		= self.quality || self.context?.features?.quality
		const extension		= self.context?.features?.extension
		const video			= content_value.video

	const fragment = new DocumentFragment()

	// create the quality selector
		const quality_selector = ui.create_dom_element({
			element_type	: 'select',
			class_name		: 'quality_selector',
			parent			: fragment
		})
		quality_selector.tabIndex = -1;
		quality_selector.addEventListener('change', (e) =>{
			video.src = e.target.value
			// event_manager.publish('image_quality_change_'+self.id, img_src)
			if(SHOW_DEBUG===true) {
				console.log("quality_selector set video.src:", video.src);
			}
		})

		const quality_list		= files_info.filter(el => el.file_exist===true && el.extension===extension)
		const quality_list_len	= quality_list.length
		for (let i = 0; i < quality_list_len; i++) {

			const file_info = quality_list[i]

			// create the node with the all qualities sent by server
			const url = DEDALO_MEDIA_URL + file_info.file_path + '?t=' + (new Date()).getTime()

			const select_option = ui.create_dom_element({
				element_type	: 'option',
				value			: url,
				text_node		: quality_list[i].quality,
				parent			: quality_selector
			})
			//set the default quality_list to config variable dedalo_image_quality_default
			select_option.selected = quality_list[i].quality===quality ? true : false
		}


	return quality_selector
}//end get_quality_selector



/**
* GET_BUTTONS
* Builds the buttons container for the edit view toolbar.
*
* Two button groups are conditionally rendered based on self.show_interface flags:
*  - Tool buttons (show_interface.tools === true): delegated to ui.add_tools(),
*    which reads self.tools and renders the registered tool icons (e.g. tool_upload,
*    tool_posterframe).
*  - Fullscreen button (show_interface.button_fullscreen === true): a span that
*    calls ui.enter_fullscreen(self.node) on click, putting the component node
*    into the browser's native fullscreen mode.
*
* All buttons are placed inside a .buttons_fold div, which enables CSS sticky
* positioning when the component content overflows the viewport height.
*
* This function is called only when self.permissions > 1 (edit rights); read-only
* users receive no buttons container.
*
* @param {Object} self - Component instance; must expose show_interface, tools, and node.
* @returns {HTMLElement} The .buttons_container element ready to be appended to the wrapper.
*/
const get_buttons = (self) => {

	// short vars
		const show_interface = self.show_interface

	// fragment
		const fragment = new DocumentFragment()

	// buttons tools
		if(show_interface.tools === true){
			ui.add_tools(self, fragment)
		}

	// des
		// const button_info = ui.create_dom_element({
		// 	element_type	: 'span',
		// 	class_name 		: 'button full_screen',
		// 	parent 			: fragment
		// })
		// button_info.addEventListener("mouseup", async (e) =>{

		// 	const player_av = await get_instance({
		// 		model 			: 'component_av',
		// 		section_tipo	: self.section_tipo,
		// 		section_id		: self.section_id,
		// 		tipo			: self.tipo,
		// 		context			: {},
		// 		mode 			: 'player'
		// 	})

		// 	await player_av.build(true)

		// 	player_av.fragment = {tc_in: 3, tc_out: 5}

		// 	const node = await player_av.render()

		// 	// cotainer, for every ipo will create a li node
		// 		const cotainer = ui.create_dom_element({
		// 			element_type	: 'div'
		// 		})
		// 		self.node[0].appendChild(node)
		// })

	// button_fullscreen
		if(show_interface.button_fullscreen === true){

			const button_fullscreen = ui.create_dom_element({
				element_type	: 'span',
				class_name		: 'button full_screen',
				title			: get_label.full_screen || 'Full screen',
				parent			: fragment
			})
			button_fullscreen.addEventListener('click', function(e) {
				ui.enter_fullscreen(self.node)
			})
		}

	// buttons container
		const buttons_container = ui.component.build_buttons_container(self)

	// buttons_fold (allow sticky position on large components)
		const buttons_fold = ui.create_dom_element({
			element_type	: 'div',
			class_name		: 'buttons_fold',
			parent			: buttons_container
		})
		buttons_fold.appendChild(fragment)


	return buttons_container
}//end  get_buttons



/**
* BUILD_VIDEO_HTML5
* @returns {HTMLElement} video
*/
	// const build_video_html5 = function(request_options) {

	// 	const self = this

	// 	// options
	// 		const options = {
	// 			// video type. (array) default ["video/mp4"]
	// 			type 	 : ["video/mp4"],
	// 			// video src. (array)
	// 			src  	 : [""],
	// 			// id. dom element video id (string) default "video_html5"
	// 			id 		 : "video_html5",
	// 			// controls. video control property (boolean) default true
	// 			controls : true,
	// 			// play (boolean). play video on ready. default false
	// 			play : false,
	// 			// poster image. (string) url of posterframe image
	// 			poster 	 : "",
	// 			// class css. video additional css classes
	// 			class 	 : "",
	// 			// preload (string) video element attribute preload
	// 			preload  : "auto",
	// 			// height (integer) video element attribute. default null
	// 			height 	 : null,
	// 			// width (integer) video element attribute. default null
	// 			width 	 : null,
	// 			// tcin_secs (integer). default null
	// 			tcin_secs  : 0,
	// 			// tcout_secs (integer). default null
	// 			tcout_secs : null,
	// 			// ar_subtitles (array). array of objects with subtitles full info. default null
	// 			ar_subtitles : null,
	// 			// ar_restricted_fragments. (array) default null
	// 			ar_restricted_fragments : null
	// 		}

	// 		// apply options
	// 		for (var key in request_options) {
	// 			if (request_options.hasOwnProperty(key)) {
	// 				options[key] = request_options[key]
	// 			}
	// 		}
	// 		// debug
	// 		if(SHOW_DEBUG===true) {
	// 			console.log("[common.build_video_html5] options",options)
	// 		}

	// 	// video handler events
	// 		const handler_events = {
	// 			loadedmetadata 	: {},
	// 			timeupdate 		: {},
	// 			contextmenu 	: {}
	// 		}

	// 	// html5 video. dom element html5 video
	// 		const video 				= document.createElement("video")
	// 			  video.id 				= options.id
	// 			  video.controls 		= options.controls
	// 			  video.poster 			= options.poster
	// 			  video.className 		= options.class
	// 			  video.preload 		= options.preload
	// 			  video.controlsList 	= "nodownload"
	// 			  video.dataset.setup 	= '{}'

	// 			  if (options.height) {
	// 				video.height = options.height
	// 			  }
	// 			  if (options.width) {
	// 				video.width = options.width
	// 			  }
	// 			  options.play = true
	// 			  if (options.play && options.play===true) {

	// 				handler_events.loadedmetadata.play = (e) => {
	// 			  		try {
	// 						//video.play()
	// 					}catch(error){
	// 				  		console.warn("Error on video play:",error);
	// 				  	}
	// 				}
	// 			  }

	// 		// src. video sources
	// 			for (let i = 0; i < options.src.length; i++) {
	// 				let source 		= document.createElement("source")
	// 					source.src  = options.src[i]
	// 					source.type = options.type[i]
	// 				video.appendChild(source)
	// 			}

	// 		// restricted fragments. Set ar_restricted_fragments on build player to activate skip restricted fragments
	// 			if (options.ar_restricted_fragments) {
	// 				const ar_restricted_fragments = options.ar_restricted_fragments
	// 				const tcin_secs 			  = options.tcin_secs
	// 				if (typeof ar_restricted_fragments!=="undefined" && ar_restricted_fragments.length>0) {
	// 					handler_events.timeupdate.skip_restricted = () => {
	// 						self.skip_restricted(video, ar_restricted_fragments, tcin_secs)
	// 					}
	// 				}
	// 			}

	// 		// subtitles
	// 			if (options.ar_subtitles) {
	// 				const subtitles_tracks = []
	// 				for (let i = 0; i < options.ar_subtitles.length; i++) {

	// 					let subtitle_obj = options.ar_subtitles[i]

	// 					if (subtitle_obj.src===undefined) {
	// 						console.warn("Invalid subtitle object:",subtitle_obj);
	// 						continue
	// 					}

	// 					// Build track
	// 					let track = document.createElement("track")
	// 						track.kind 		= "captions" // subtitles | captions
	// 						track.src 		= subtitle_obj.src
	// 						track.srclang 	= subtitle_obj.srclang
	// 						track.label 	= subtitle_obj.label
	// 						if (subtitle_obj.default && subtitle_obj.default===true) {
	// 							track.default = true
	// 							track.addEventListener("load", function() {
	// 							   this.mode = "showing";
	// 							   video.textTracks[0].mode = "showing"; // thanks Firefox
	// 							});
	// 						}
	// 					// add track
	// 					subtitles_tracks.push(track)
	// 				}//end for (var i = 0; i < options.ar_subtitles.length; i++)

	// 				handler_events.loadedmetadata.add_subtitles_tracks = () => {
	// 					for (let i = 0; i < subtitles_tracks.length; i++) {
	// 						// add to video
	// 						video.appendChild(subtitles_tracks[i]);
	// 						//console.log("added subtitle track:",subtitles_tracks[i]);
	// 					}
	// 				}
	// 			}

	// 		// msj no html5
	// 			const msg_no_js = document.createElement("p")
	// 				  msg_no_js.className = "vjs-no-js"
	// 			const msj_text = document.createTextNode("To view this video please enable JavaScript, and consider upgrading to a web browser that supports HTML5 video")
	// 				  msg_no_js.appendChild(msj_text)
	// 			video.appendChild(msg_no_js)

	// 		// disable_context_menu - (TEMPORAL DISABLED !)
	// 			// handler_events.contextmenu.disable_context_menu = (e) => {
	// 			// 	e.preventDefault();
	// 			// }



	// 		// REGISTER_EVENTS
	// 		const register_events = function(handler_object, handler_events) {

	// 			for (let event_name in handler_events) {
	// 				// add event
	// 				const event_functions = handler_events[event_name]
	// 				handler_object.addEventListener(event_name, function(e) {
	// 					for (let key in event_functions) {
	// 						event_functions[key](e)
	// 					}
	// 				})
	// 			}

	// 			return true
	// 		}

	// 		// video events	register
	// 			register_events(video, handler_events)


	// 	return video
	// }//end  build_video_html5



// @license-end
