<?php
	

	# VISUALIZADOR HTML	
	print "\n\n<!-- SECTION TAB [tipo:$tipo] $label -->";

	# CONTENT
	$html_content = "\n<div class=\"css_section_tab_content \" >";
	
	switch($permissions) {
			
		case 0 :
				$html_content .= "\n <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." (tab)</span>"; 
				break;
		
		case ($permissions>=1) :

				# TABS LABELS
				$i=0; foreach ($ar_tab_html as $tab_tipo => $tab_html) {
					$name = RecordObj_dd::get_termino_by_tipo($tab_tipo,DEDALO_DATA_LANG,true);
					$checked = $i===0 ? 'checked' : null;
					$checked  = null;

					$html_content .= "<input id=\"section_tab_{$tab_tipo}\" type=\"radio\" name=\"tabs\" $checked onclick=\"section_tabs.set_tab_active(this)\">";
					$html_content .= "<label for=\"section_tab_{$tab_tipo}\" >$name</label>";
					$i++;
				}
				
				# TABS CONTENT
				foreach ($ar_tab_html as $tab_tipo => $tab_html) {
					
					$html_content .= "<section id=\"section_tab_content_{$tab_tipo}\" class=\"sgc_{$modo}\">";
					$html_content .= $tab_html;
					$html_content .= "</section>";
				}

				# TABS CSS
				# CSS control interactions between label and content and is necessary create custom css for each case
				$css_custom = '';
				foreach ($ar_tab_html as $tab_tipo => $tab_html) {
					$css_custom .= "#section_tab_{$tab_tipo}:checked ~ #section_tab_content_{$tab_tipo},";
				}
				$css_custom = substr($css_custom, 0,-1) . '{ display: block; }';
				$html_content .= '<style>'.$css_custom.'</style>';

				# TABS JS
				# Select last active tab on every navigation
				$html_content .= "<script>section_tabs.select_tab_active()</script>";
				
		case 2	: 
		case 3	:	
				break;
	}
	
	$html_content .= "\n</div><!-- /css_section_tab_content -->";

	
	
	# PRINT HTML
	echo $html_content;
?>