<?php
	
	# VISUALIZADOR HTML	
	
	print "\n\n<!-- SECTION TAB [tipo:$tipo] $label -->";

	# CONTENIDO (INPUT)
	$html_contenido = "\n<div class=\"css_section_tab_content \" >";
	
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." (tab)</span>"; 		
					break;
						
		case ($permissions>=1)	:

					# TAB UL
  					$html_contenido .= "\n<ul>";
					foreach ($ar_tab_html as $tab_tipo => $tab_html) {	

						$html_contenido .= "\n <li><a href=\"#tab_{$tab_tipo}\">" . RecordObj_dd::get_termino_by_tipo($tab_tipo,DEDALO_DATA_LANG,true) ."</a></li>";
					}	
					$html_contenido .= "\n</ul>";
					
					# TAB CONTENT DIV
					foreach ($ar_tab_html as $tab_tipo => $tab_html) {
						
						$html_contenido .= "\n<div id=\"tab_{$tab_tipo}\" >";
						$html_contenido .= "\n $tab_html ";
						$html_contenido .= "\n</div>";
					}					
						
		case 2	: 
		case 3	:	
					break;			
	}
	
	$html_contenido .= "\n</div><!-- /css_section_tab_content -->";


	# Prepare content to show in page
	#tools::prepare_content($html_contenido);
	
	
	# PRINT HTML
	#print $html_label;
	print $html_contenido;

	
	#print "\n</div><!-- /css_section_tab_wrap SECTION TAB [tipo:$tipo] $label  -->\n\n"; //wrap
?>