<?php








	return null;














































	# VISUALIZADOR HTML	

		
	
	#print "\n<!-- BUTTON DELETE [tipo:$tipo section_id:$id] -->";
	print "<div class=\"css_wrap_button_delete\">";
	
	# ETIQUETA (LABEL)
	#$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." (button_new)</span>";
					break;
						
		case 1	: 	$html_contenido .= "";
					break;	
						
		case ($permissions>=2)	:
		
					$html_contenido .= "<div class=\"css_button_delete div_image_link link \" data-tipo=\"{$section_tipo}\" data-section_id=\"{$id}\" title=\"$label $id\"></div>";

					if($permissions==3){
						$html_contenido .= "<span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";
					}
					break;
								
	}
	
	
	# PRINT HTML
	print $html_contenido;
	
	
	print "</div>"; //wrap <!-- /css_wrap_button_delete -->\n\n
?>