<?php declare(strict_types=1);
/**
* CLASS EXEC COMMAND
*
*
*/
class exec_ {



	/**
	* EXEC COMMAND
	* Exec the given command in the php CLI
	* @param string $command
	* @param string $to='2>&1'
	* @return bool
	*/
	public static function exec_command(string $command, string $to='2>&1') : bool {

		$output = null;

		try {

			// escape command for security
			$command = escapeshellcmd( $command ) . ' '. $to;

			// Exec command and get output
			$output = shell_exec( $command );

			// debug
				debug_log(__METHOD__
					. " Notice: exec command: " . PHP_EOL
					. ' command: ' . $command . PHP_EOL
					. ' output: ' . $output
					, logger::WARNING
				);

			if( !$output ) {
				debug_log(__METHOD__
					. " Error processing media command: " . PHP_EOL
					. ' command: ' . $command
					, logger::ERROR
				);
				throw new Exception("Error processing media command", 1);
			}

		}catch(Exception $e){

			debug_log(__METHOD__
				. " Exception: " . PHP_EOL
				. $e->getMessage()
				, logger::ERROR
			);

			return false;
		}


		return true;
	}//end exec_command



	/**
	* EXEC SH FILE
	* @param string $file
	* @return int|null $PID
	*/
	public static function exec_sh_file(string $file) : ?int {

		$PID = null;

		try {
			// exec("sh $file > /dev/null &", $output); # funciona!!! <<<<
			// exec("sh $file > /dev/null 2>&1 & echo $!", $output); # return pid
			// $response = exec("sh $file > /dev/null 2>&1 & echo $!", $output);

			// exec command from sh file. Security: $file must be a server-built
			// path (currently only `component_av::Save` passes a temp .sh file
			// generated by `media_engine`); escapeshellarg adds defence-in-depth
			// against any future caller that interpolates user-controlled paths.
				$response = exec("sh " . escapeshellarg($file) . " > /dev/null & echo $!", $output);

			// response check. Could be empty
				if ( empty($response) ) {
					debug_log(__METHOD__
						. " Warning processing media file. response is empty: " . PHP_EOL
						. ' file: ' . $file
						, logger::WARNING
					);
				}

			// PID. Output returns the PID as ["3647"]
				$PID = isset($output[0])
					? (int)$output[0]
					: null;

			return $PID;

		}catch(Exception $e){

			debug_log(__METHOD__
				. " Exception: " . PHP_EOL
				. ' Exception message: ' . $e->getMessage()
				, logger::ERROR
			);
		}

		return $PID;
	}//end exec_sh_file




	// SEC-045: removed unused helpers `exec_sh_file_isolated`, `getCommandPath`,
	// `live_execute_command`. Each had zero callers in production / CLI / tests
	// (verified by repo-wide grep) and used raw shell interpolation that would
	// have been Class C/D had they been revived. If any of these helpers is
	// reintroduced, route through `request_cli` (below — uses `escapeshellarg`)
	// or `proc_open` with an arg array; never interpolate user-supplied strings
	// into a shell command line.



	/**
	* REQUEST_CLI
	* Exec given method in CLI using a process runner file
	* @see /core/base/process_runner.php
	* @param object $options
	* {
	* 	class_name: string "request_cli"
	* 	method_name: string "export_records"
	* 	class_file: string
	*	params: object
	* }
	* @return object response { result: mixed, msg: string }
	*/
	public static function request_cli(object $options) : object {

		// options
			$class_name		= $options->class_name;
			$method_name	= $options->method_name;
			$class_file		= $options->class_file;
			$params			= $options->params;

		// params. Pass through without safe_xss sanitization — params are
		// application data (e.g. SQO filter values with '>' operators) not
		// rendered as HTML. htmlspecialchars() corrupts such operational values.
		// The direct (non-CLI) path also passes options unsanitized to tool
		// methods, and process_runner.php now skips params sanitization too.
			$safe_params = $params;

		// server_vars
			// sh_data mandatory vars
			$sh_data = [
				'server' => [
					'HTTP_HOST'		=> $_SERVER['HTTP_HOST'] ?? 'localhost',
					'REQUEST_URI'	=> $_SERVER['REQUEST_URI'] ?? '/',
					'SERVER_NAME'	=> $_SERVER['SERVER_NAME'] ?? $_SERVER['HTTP_HOST'] ?? 'development'
				],
				'session_id'		=> session_id(),
				'error_log_path'	=> system::get_error_log_path(), // current PHP-FPM path to use the same error output
				'user_id'			=> logged_user_id(),
				'class_name'		=> $class_name, // class name
				'method_name'		=> $method_name, // method name
				'file'				=> $class_file, // class file to include optional
				'params'			=> $safe_params // object with options passed to the function
			];
			$server_vars = json_encode($sh_data, JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);

		// process file (temporal file where store function output)
			$pfile			= process::get_unique_process_file(); // like 'process_1_2024-03-31_23-47-36_3137757' usually stored in the sessions directory
			$file_path		= process::get_process_path() .'/'. $pfile; // output file with errors and stream data

		// process_runner. File to sh execute that manage given vars calling desired class and method
			$process_runner	= DEDALO_CORE_PATH . '/base/process_runner.php';

		// command composition
			$cmd		= PHP_BIN_PATH . " $process_runner " . escapeshellarg($server_vars);
			// $command	= "nohup nice -n 19 $cmd >$file_path 2>&1 & echo $!";
			$command	= "nohup nice -n 19 $cmd >$file_path & echo $!";

			// debug
				debug_log(__METHOD__
					." Running tool task in background ($pfile)". PHP_EOL
					." Command: ". PHP_EOL. to_string($command)
					, logger::DEBUG
				);

		// process creation
			$process	= new process($command);
			$pid		= $process->getPid();

		// store process info
			processes::add(
				logged_user_id(),
				$pid,
				$pfile
			);

		// response OK
			$response = new stdClass();
				$response->result	= true;
				$response->pid		= $pid;
				$response->pfile	= $pfile;
				$response->msg		= 'OK. Running publication ' . $pid;


		return $response;
	}//end request_cli



}//end class exec_



/**
 * An easy way to keep in track of external processes.
 * Ever wanted to execute a process in php, but you still wanted to have somewhat control of the process ? Well.. This is a way of doing it.
 * @compatibility: Linux only. (Windows does not work).
 * @author: Peec
 */
class process {

    /** @var int|null $pid */
    private ?int $pid = null;

    /** @var string|null $command */
    private ?string $command = null;

    /** @var string|null $file */
    private ?string $file = null;

    public function __construct(?string $cl=null) {
        if ($cl != false){
            $this->command = $cl;
            $this->runCom();
        }
    }
    private function runCom() : void {
    	// reference command for non blocking process
		// $command = 'nohup '.$this->command.' > /dev/null 2>&1 & echo $!';
		$command = $this->command; // untouched command

		// debug
		if(SHOW_DEBUG===true) {
			debug_log(__METHOD__
				. " Executing process command: " . PHP_EOL
				. $command
				, logger::DEBUG
			);
		}

        exec($command, $output);
        $this->pid = (int)$output[0];
    }

    public function setPid(?int $pid) : void {
        $this->pid = $pid;
    }

    public function getPid() : ?int {
        return $this->pid;
    }

    public function status() : bool {
        // SEC-043 defence-in-depth: cast pid to int. `setPid()` accepts arbitrary
        // input from `dd_utils_api::get_process_status` (which now does its own
        // ownership check), but quoting here means future callers cannot inject
        // shell metacharacters through the pid path.
        $command = 'ps -p '.(int)$this->pid;
        exec($command, $output);
        if (!isset($output[1]))return false;
        else return true;
    }

    public function start() : bool {
        if ($this->command != '') {
            $this->runCom();
            return true;
        }
        return true;
    }

    public function stop() : bool {
        // SEC-043 defence-in-depth: int-cast pid before shell interpolation.
        $command = 'kill '.(int)$this->pid;
        exec($command);
        if ($this->status() === false) return true;
        else return false;
    }

    public function setFile(?string $file) : void {
        $this->file = $file;
    }

    public function read() : array {
        // SEC-043 defence-in-depth: shell-quote $this->file. Currently set only
        // through `processes::get_process_item()` (server-generated path from
        // `get_unique_process_file()`); the helper now enforces escaping so
        // future callers cannot regress.
        $command = 'tail -n 1 '.escapeshellarg((string)$this->file);
        exec($command, $output);
        return $output;
    }

    /**
	* GET_UNIQUE_PROCESS_FILE
	* Calculate unified unique process path name for files
	* @return string $name
	*/
	static function get_unique_process_file() : string {

		$name = 'process_' . logged_user_id() .'_'. date('Y-m-d_H-i-s') .'_'. hrtime(true);

		return $name;
	}//end get_unique_process_file

	/**
	* GET_PROCESS_PATH
	* Calculate common process path name
	* Normally, it is stored in the session directory
	* @return string $dir
	*/
	static function get_process_path() : string {

		$dir = defined('DEDALO_SESSIONS_PATH')
			? DEDALO_SESSIONS_PATH
			: (@session_save_path() ?? '/tmp');

		return $dir;
	}//end get_process_path

}//end class process
