// @license magnet:?xt=urn:btih:0b31508aeb0634b347b8270c7bee4d411b5d4109&dn=agpl-3.0.txt AGPL-3.0
/*global*/
/*eslint no-undef: "error"*/



/**
 * SERVICE WORKER
 * Manages Dédalo files cache when is fired by login, acting as proxy.
 * Once registered, it handles all requests, being transparent
 * for requests for files that are not in the cached list.
 * The registration is done by the login, after authorizing the user.
 * Note that files_list is generated by API dd_utils_api::get_dedalo_files
 * and is a list of main javascript Dédalo core and tools modules cached
 * with this service to take controls about files changes on every user login.
 * On user logout (quit), the service worker is unregistered and cache is deleted.
 * This is HTTPS only service !
 */



/**
 * DATA_MANAGER REQUEST CUSTOM
 * Avoid to use data_manager module to allow happy Firefox users
 */
const data_manager = {
	request : async function(options) {

		// options (local variables prevent shared-state races on concurrent calls)
			const url			= options.url
			const method		= options.method || 'POST' // *GET, POST, PUT, DELETE, etc.
			const mode			= options.mode || 'cors' // no-cors, cors, *same-origin
			const cache			= options.cache || 'no-cache' // *default, no-cache, reload, force-cache, only-if-cached
			const credentials	= options.credentials || 'same-origin' // include, *same-origin, omit
			const headers		= options.headers || {'Content-Type': 'application/json'}// 'Content-Type': 'application/x-www-form-urlencoded'
			const redirect		= options.redirect || 'follow' // manual, *follow, error
			const referrer		= options.referrer || 'no-referrer' // no-referrer, *client
			const body			= options.body // body data type must match "Content-Type" header

		// handle_errors
			const handle_errors = function(response) {
				if (!response.ok) {
					console.warn("-> HANDLE_ERRORS response:",response);
					throw Error(response.statusText);
				}
				return response;
			}

		const api_response = fetch(
			url,
			{
				method		: method,
				mode		: mode,
				cache		: cache,
				credentials	: credentials,
				headers		: headers,
				redirect	: redirect,
				referrer	: referrer,
				body		: JSON.stringify(body)
			})
			.then(handle_errors)
			.then(response => {
				const json_parsed = response.json().then((result)=>{

					if (result.error) {

						// debug console message
							console.error("result error:",result);

						// alert msg to user
							const msg = result.msg || result.error
							console.error("An error occurred in the connection with the API (worker cache data_manager). \n" + msg);

						// custom behaviors
							switch (result.error) {
								case 'not_logged':
									// redirect to login page
									// location.reload();
									console.warn('Result error. no logged!', result);
									break;

								default:
									// write message to the console
									break;
							}
					}

					return result
				})

				return json_parsed
			})
			.catch(error => {
				console.error("!!!!! [data_manager.request] SERVER ERROR. Received data is not JSON valid. See your server log for details. catch ERROR:\n", error)
				console.warn("options:", options);
				return {
					result	: false,
					msg		: error.message,
					error	: error
				}
			});


		return api_response
	}
}//end data_manager



/**
 * @vars
 */
// string cache_name. The cache is keyed by the SERVED CODE, not by a fixed name:
// the API's `dedalo_version` carries the engine version plus a signature of the
// client bytes on disk (see core/api/dedalo_files.ts). Edit or deploy a client
// file and the key moves, so the old cache is dropped and the files are re-fetched.
// A FIXED name (the previous 'dedalo_files') meant an edited file stayed cached
// forever and only a fresh login ever refreshed it — a logged-in user kept running
// the old JS against the new server.
// Resolved by load_files_list(); null until the manifest has been read.
const cache_prefix = 'dedalo_files'
let cache_name = null
// array files_list. Filled with the list of Dédalo main javascript files
let files_list
// Set files_set. For O(1) lookup in fetch handler
let files_set



/**
 * LOAD_FILES_LIST
 * Call API to get a list of the Dédalo main javascript files
 * to cache and fix the value in 'files_list' var
 * @return array|null files_list
 */
const load_files_list = async () => {

	if (files_list) {
		return files_list
	}

	// get_dedalo_files from API
		const api_response = await data_manager.request({
			url		: './api/v1/json/', // DEDALO_API_URL,
			body	: {
				action	: 'get_dedalo_files',
				dd_api	: 'dd_utils_api'
			}
		});

	// API error case
		if (!api_response.result) {
			console.error('Error on get api response:', api_response);
			return null
		}

	// fix values
		files_list = api_response.result.map(el => el.url)
		// build a Set with absolute URLs for fast lookups in the fetch handler
		files_set = new Set(files_list.map(url => new URL(url, self.location.origin).href))
		// the cache is named after the served code (see cache_name above)
		cache_name = cache_prefix + '_' + (api_response.dedalo_version || 'unknown')


	return files_list
}//end load_files_list




/**
 * ADD_RESOURCES_TO_CACHE
 * Load file list from API
 * Put files_list in cache sending a message for each file load
 * @param object options
 * @return void
 */
const add_resources_to_cache = async (options) => {

	// options unpack
	const {
		load_file_handler
	} = options

	// fire load files from API
	const list = await load_files_list()
	if (!list) {
		return // API error already logged in load_files_list
	}

	// open cache interface
	const cache = await caches.open( cache_name );

	// headers for js files (built once, reused for every fetch)
	const js_headers = new Headers();
	js_headers.append('Content-Type', 'text/javascript');

	// custom cache add equivalent to 'cache.add' but using fetch param 'cache' as 'reload'
	// to force load the file from server always
	const custom_cache_add = async (url) => {
		try {

			const response = await fetch(url, {
				headers	: js_headers,
				method	: 'GET',
				cache	: 'reload'
			})
			if (!response.ok) {
				throw new TypeError("bad response status");
			}
			return cache.put(url, response);

		} catch (error) {
			console.log('Failed fetch file. URL:', url);
			console.error(error)
		}

		return false
	}

	// add files in parallel, tracking completion with an atomic counter
	let loaded_count = 0
	const ar_promises = []
	const files_list_length = files_list.length
	for (let i = 0; i < files_list_length; i++) {

		const ad_promise = custom_cache_add( files_list[i] );

		ar_promises.push(ad_promise)

		// notify file is loaded into cache (for files loader circle using loading handler)
		ad_promise.then(()=>{
			loaded_count++
			load_file_handler(loaded_count, files_list_length)
		})
	}
	await Promise.all(ar_promises)

	// Drop every SUPERSEDED cache. The current one is keyed by the served code, so
	// any other key is a previous version of the client and must not linger: it
	// would keep occupying storage and, if it were ever consulted, answer with the
	// old file. (delete_old_caches existed but nothing ever called it — which is
	// why every client version a browser had ever seen stayed on disk.)
	await delete_old_caches( cache_name )
}//end add_resources_to_cache



/**
 * DELETE_CACHE
 * Delete caches item by key
 * @param string key
 * @return void
 */
const delete_cache = async (key) => {
	await caches.delete(key);
}//end delete_cache



/**
 * DELETE_OLD_CACHES
 * Delete whole caches except the given name
 * @param string keep_name
 * @return void
 */
const delete_old_caches = async (keep_name) => {

	console.log(')) deleting cache:', keep_name);

	const cacheKeepList		= [keep_name];
	const keyList			= await caches.keys();
	const cachesToDelete	= keyList.filter((key) => !cacheKeepList.includes(key));
	await Promise.all(cachesToDelete.map(delete_cache));
}//end delete_old_caches



/**
 * CACHE_FIRST
 * Check for request file from cache. If file is found, return from cache,
 * else request the file normally.
 * Only checks cache for files in files_set to avoid unnecessary lookups.
 * @param object request
 * @return promise
 * 	fetch promise
 */
const cache_first = async (request) => {
	// only check cache for files we actually cached
	if (cache_name && files_set && files_set.has(request.url)) {
		// Scoped to the CURRENT cache on purpose: caches.match() searches every
		// cache in the origin, so a superseded one would keep answering with the
		// stale file even after the key moved.
		const cache = await caches.open(cache_name);
		const responseFromCache = await cache.match(request);
		if (responseFromCache) {
			return responseFromCache;
		}
	}
	return fetch(request);
}//end cache_first



/**
 * INSTALL EVENT
 */
self.addEventListener('install', (event) => {

	console.log(')) install event:', event);
	// take over from older SW versions immediately
	event.waitUntil(self.skipWaiting());
});



/**
 * ACTIVATE EVENT
 */
self.addEventListener('activate', (event) => {

	console.log(')) activate event:', event);
	// claim all open clients so the new SW handles fetches immediately
	event.waitUntil(self.clients.claim());
});



/**
 * MESSAGE EVENT
 */
self.addEventListener('message', (event) => {

	console.log(')) message event:', event.data, event);

	if (event.data==='update_files') {

		// wrap in waitUntil to keep the SW alive until caching completes
		event.waitUntil((async () => {
			const t1 = performance.now()

			// ready message (enable loading files circle render by ready handler)
				if (event.source) {
					event.source.postMessage({
						status : 'ready'
					});
				}

			// load files updating existing ones
				const load_file_handler = (loaded_count, total_files) => {
					// on_load_file
					if (event.source) {
						event.source.postMessage({
							status		: 'loading',
							key			: loaded_count,
							total_files	: total_files,
							file_loaded	: true
						})
					}
				}
				await add_resources_to_cache({
					load_file_handler : load_file_handler
				})

			// all files are loaded. Notify finish
				if (event.source && files_list) {
					event.source.postMessage({
						status		: 'finish',
						total_files	: files_list.length,
						time		: performance.now()-t1
					});
				}
		})());
	}
});



/**
 * FETCH EVENT
 */
self.addEventListener('fetch', (event) => {

	// debug
		// console.log('event.request.url:', event.request.url);

	// Manage only javascript files excluding images, css, etc.
	// that will be handled by the browser normally
	if (	event.request.url.endsWith('.js')
		&& !event.request.url.endsWith('/sw.js')
		&& !event.request.url.includes('/lib/')
		) {

		event.respondWith(
			cache_first(event.request)
		);
	}
});



// @license-end
