<?php

	# VISUALIZADOR HTML	

	if(SHOW_DEBUG===true) {
		print "<!-- SECTION EDIT [section_id:$section_id tipo:$tipo] -->";
	}	

	print "<div class=\"css_section_wrap wrap_section wrap_section_{$modo} wrap_section_{$tipo}\" id=\"{$id_wrapper}\" ";
	print "data-section_id=\"{$section_id}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato=\"array\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-section_id=\"{$section_id}\" ";
	print "data-label=\"{$label}\" ";
	print "data-section_info='{$section_info}' ";
	print ">";


	# CONTENT
	$html_content  = '';
	$html_content = "<div class=\"css_section_content section_content_list section_list_rows_content_div\" data-role=\"section_list_rows_content\" >";

		#$html_content .= "<div class=\"css_section_content\" id=\"section_{$identificador_unico}\" >";			
		
			# Fields
			switch(true) {
					
				case $permissions===0 :	
					
					$html_content .= "<span class=\"css_span_dato\">";
					$html_content .= label::get_label('contenido_no_autorizado');
						#dump(security::$ar_permissions_table," security::ar_permissions_table");
					$html_content .= " (Section $tipo - $modo)</span>";
					break;
								
				case ($permissions>=1) :

					if($this->caller_id>0 && $modo!='edit') {
						$html_content .= "<div class=\"div_clear_edit_in_relation\"></div>";
					}

					#
					# SEARCH_FORM_HTML
						#$html_content .= $search_form_html;
					
					
					#
					# SECTION_RECORDS_HTML
					/*
					$section_records_html = '';
					if(SHOW_DEBUG===true) 
					$section_records_html .= "<!-- SECTION RECORDS EDIT [tipo:$tipo modo:$modo] -->";					
					$section_records_html .= '<div class="css_section_list_wrap" id="wrap_'.$tipo.'_'.$modo.'" data-options=\''.$search_options_json.'\'>';
					# Rows loads here
					$section_records_html .= "<div class=\"css_section_group_content tab_content section_records_{$modo}\" data-rol=\"section_records\">";
					$section_records_html .= '<div id="load_rows_button_edit"><span>Loading..</span></div>';
					$section_records_html .= '<script>';
					$section_records_html .= 'search.load_rows(\''.$search_options_json.'\', document.getElementById("load_rows_button"))';
					$section_records_html .= '</script>';
					$section_records_html .= "</div><!-- /css_section_group_content -->";
					$section_records_html .= '</div><!-- /css_section_list_wrap -->'; //wrap */
					
					$html_content .= $section_records_html;
					break;
			}

		$html_content .= "</div>";//end css_section_content

		if(SHOW_DEBUG===true) {
			$html_content .= "\n<!-- /css_section_content -->";
		}
		

		#######################
		# SIDEBAR (INSPECTOR)
		$show_inspector=true;	// <---- / temporal : borrar tras acabar el apartado
		if ($show_inspector) {
			print "<div id=\"sidebar\">";
			print isset($inspector_html) ? $inspector_html : '';
			print "</div><!-- /sidebar -->";
		}
		#######################

		
		#######################
		# CONTENT PRINT HTML
		print "<div class=\"records main_section_{$modo}\">";
			print "<div class=\"css_section_content\" id=\"section_{$identificador_unico}\">";
			print $html_content;
			print "</div><!-- /css_section_content -->";
		print "</div><!-- /records -->";#end records;
		#######################


	print "</div>"; //wrap


	if(SHOW_DEBUG===true) {
		print "\n<!-- /wrap_section [section_id:$section_id tipo:$tipo] -->"; //wrap
		print "\n<!-- / SECTION EDIT [section_id:$section_id tipo:$tipo] -->\n";
	}
	

?>