<?php
	/*
	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_section_wrap']))				$ar_css['css_section_wrap']='';
	if(!isset ($ar_css['css_section_content']))				$ar_css['css_section_content']='';
	if(!isset ($ar_css['css_section_titulo']))				$ar_css['css_section_titulo']='';
	if(!isset ($ar_css['css_span_dato'])) 					$ar_css['css_span_dato']='';

	
	#dump($_SESSION);

	print "\n\n<!-- SECTION [id:$id tipo:$tipo] -->";
	print "\n<div class=\"css_section_wrap {$ar_css['css_section_wrap']}\" 
	data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-modo=\"{$modo}\" data-component_name=\"{$component_name}\">";		#dump($dato);
	

		# BUTTON OPEN / HIDE SIDEBAR
		#if (!$this->caller_id)
		print "<div id=\"button_toggle_inspector\" class=\"css_button_generic text_unselectable\">INSPECTOR</div>";

						
		# CONTENT
		$html_contenido  = NULL;


		$html_contenido .= "\n<div class=\"css_section_content \">";		
		
			# Header (label)	
			#$html_contenido	.= "\n<div class=\"css_section_titulo\" >[ ID: $section_id - MatrixID: $id - Tipo: <a href=\"?n=list&t=$tipo\">$tipo</a> ] - SECTION: " . component_common_draw::draw_label($this) . " </div>";
			#$html_contenido  	.= "\n<div class=\"css_section_titulo2\" > ID: $section_id - MatrixID: $id - tipo: <a href=\"?n=list&t=$tipo\">$tipo</a></div>";
			
		
			# Fields
			switch($permissions) {
					
				case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> <h3>".label::get_label('contenido_no_autorizado')."</h3> </span>";
							break;
								
				case ($permissions>=1)	:
											
							$html_contenido .= "\n $html_section_add ";	
								
				case 2	: 
				case 3	:	
							break;			
			}
			
		$html_contenido .= "\n</div>";# /css_section_content		
		
		# Prepare content to show in page
		#tools::prepare_content($html_contenido);	

		# PRINT HTML
		print $html_contenido;


		# SIDEBAR (INSPECTOR)
		$html_sidebar  = '';
		$html_sidebar .= '<!-- sidebar -->';
		$html_sidebar .= "\n<div id=\"sidebar\">";
		$html_sidebar .= $html_inspector;				
		$html_sidebar .= "\n</div><!-- /sidebar -->";
		
		

	
	print "\n</div><!-- /SECTION WRAP [id:$id tipo:$tipo] -->\n\n"; //wrap
	*/
?>