<?php
	
	# VISUALIZADOR HTML	
	
	print "\n\n<!-- SECTION SEARCH [tipo:$tipo id_matrix:$id] -->";
	print "\n<div class=\"css_section_wrap\" >";
	
	
	# ETIQUETA (LABEL)	
	$html_label 	= "\n<div class=\"css_section_titulo\" > <hr> SECTION: ".component_common_draw::draw_label($this)." </div>";
	$html_label  	.= "\n<div class=\"css_section_titulo\" > Número: ".$dato." </div>";
		
	
	# CONTENIDO (INPUT)
	$html_contenido = "\n<div class=\"css_section_content\" >";
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." </span>";
					break;
						
		case ($permissions>=1)	:
					
					$html_contenido .= "\n $html_section_add ";	
						
		case 2	: 
		case 3	:	
					break;			
	}
	$html_contenido .= "\n</div><!-- /css_section_content -->";
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div><!-- /css_section_wrap -->\n\n"; //wrap
?>