<?php
	
	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_section_wrap']))		$ar_css['css_section_wrap']='';
	if(!isset ($ar_css['css_section_titulo']))		$ar_css['css_section_titulo']='';
	if(!isset ($ar_css['css_span_dato'])) 			$ar_css['css_span_dato']='';	
	
	
	print "\n\n<!-- SECTION LIST TM [tipo:$tipo id_matrix:$id] -->";
	print "\n<div class=\"css_section_wrap {$ar_css['css_section_wrap']}\" >";
	
	
	# ETIQUETA (LABEL)
	#$html_label 	= "\n<div class=\"css_section_titulo\" > SECTION: ".component_common_draw::draw_label($this)." </div>";
	#$html_label  	.= "\n<div class=\"css_section_titulo\" > Número: ".$dato." </div>";
		
	
	# CONTENIDO (INPUT)
	$html_contenido = "\n<div class=\"css_section_content section_content_list\" style=\"margin:0\" >";
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('contenido_no_autorizado')." </span>";
					break;
						
		case ($permissions>=1)	:
		
					#$html_contenido .= "\n".$ar_components_html;
					#$html_contenido .= "\n <a href=\"javascript:;\" onclick=\"New(this)\" data-tipo=\"{$tipo}\"> New ($tipo)</a> <div class=\"new_ajax_response\"></div> ";	
					
					$html_contenido .= "\n $html_section_add ";
						
		case 2	: 
		case 3	:	
					break;			
	}
	$html_contenido .= "\n</div><!-- /css_section_content -->";

	
	
	
	# PRINT HTML
	#print $html_label;
	print $html_contenido;
	
	
	print "\n</div><!-- /css_section_wrap SECTION [$tipo] -->\n\n"; //wrap
	
	
?>