<?php
	
	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_section_wrap']))		$ar_css['css_section_wrap']='';
	if(!isset ($ar_css['css_section_titulo']))		$ar_css['css_section_titulo']='';
	if(!isset ($ar_css['css_span_dato'])) 			$ar_css['css_span_dato']='';	
	
	
	print "\n\n<!-- SECTION [tipo:$tipo modo:$modo] -->";
	print "\n<div class=\"css_section_wrap {$ar_css['css_section_wrap']}\" id=\"section_wrap_{$tipo}\" data-modo=\"$modo\" data-options=\"\" >";
	
	
	# ETIQUETA (LABEL)
	#print $context;
	$html_label='';
	switch ($context) {

		case 'list_into_tool_portalXX':
			$html_label 	= '';
			break;

		default:
			/*
			$html_label 	.= "\n<div class=\"css_section_titulo\" >";
			$html_label 	.= component_common_draw::draw_label($this);
			if(SHOW_DEBUG)
			$html_label 	.= " [context:$context] ";
			$html_label 	.= "</div>";
			#$html_label  	.= "\n<div class=\"css_section_titulo\" > Número: ".$dato." </div>";
			*/
			#print "\n<script>$('#current_section_label').html('$label').css('right','8px')</script>";
			break;
	}
	
	
	
	
	# CONTENIDO (INPUT)
	$html_contenido = "\n<div class=\"css_section_content section_content_list section_list_rows_content_div\" >";
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato sin_acceso {$ar_css['css_span_dato']}\"> ".label::get_label('contenido_no_autorizado')." </span>";
					break;
						
		case ($permissions>=1)	:
		
					#$html_contenido .= "\n".$ar_components_html;
					#$html_contenido .= "\n <a href=\"javascript:;\" onclick=\"New(this)\" data-tipo=\"{$tipo}\"> New ($tipo)</a> <div class=\"new_ajax_response\"></div> ";	
					#dump( $_SESSION['dedalo4']['config']['search_options']['section_'.$tipo.'_'.$modo.'_'.TOP_TIPO.'_'.$_REQUEST['t']], ' 1 ');
					#dump('section_'.$tipo.'_'.$modo.'_'.TOP_TIPO.'_'.$_REQUEST['t'], ' var');
	


					

					#
					# BUTTONS
					#
					$html_buttons=(string)'';
					$html_buttons .= "\n<div class=\"section_buttons_container\">";

						#
						# BUTTON SHOW ALL / SHOW FILTERED 
						# SEARCH_OPTIONS_SESSION_KEY						
						if (isset($_REQUEST['m']) && $_REQUEST['m']=='tool_portal') {					
						
							$search_options_session_key = ''.$tipo.'_'.$modo.'_'.TOP_TIPO.'_'.$_REQUEST['t'];	// section_
							if(!empty($_SESSION['dedalo4']['config']['search_options'][$search_options_session_key]->filter_by_section_creator_portal_tipo)){
								$current_btn_label = label::get_label('mostrar_todos');
								$current_btn_class = 'show_full';
							}else{
								$current_btn_label = label::get_label('mostrar_filtrados');
								$current_btn_class = 'show_filtered';
							}					

							$html_buttons .= "
							<div id=\"btn_tool_portal_show_full\" class=\"btn_inside_section_buttons_container $current_btn_class\"
							data-search_options_session_key=\"$search_options_session_key\" 
							data-mode=\"$current_btn_class\" 
							onclick=\"tool_portal.show_more_toggle(this)\">
							$current_btn_label</div>";
						}//<div class=\"icon_bs $current_btn_class\"></div>


						#dump($ar_buttons, 'ar_buttons', array());
						foreach ($ar_buttons as $current_button_modelo_name => $current_ar_button_obj_model) {
							# Skip delete button
							#if($current_button_modelo_name=='button_stats') continue;
							foreach($current_ar_button_obj_model as $current_button_obj) {
								# Set buton target tipo
								$current_button_obj->set_target($tipo);
								$html_buttons .= $current_button_obj->get_html();
							}							
						}
						# DEBUG BUTTONS
						$is_global_admin = component_security_administrator::is_global_admin( navigator::get_user_id() );
							#dump($is_global_admin, ' is_global_admin');
						if( (SHOW_DEBUG || $is_global_admin) && !isset($_REQUEST['cache_updated'])	) {
							if(isset($_GET['m']) && strpos($_GET['m'], 'tool')!==false) {
								# Nothing to show
							}else{
								$tool_update_cache = new tool_update_cache($tipo,'button');
								$html_buttons     .= $tool_update_cache->get_html();

								# Temporal
								#$html_buttons .= "\n <div id=\"button_update_cache\" class=\"btn_inside_section_buttons_container\"
								#onclick=\"tool_update_cache.update_cache(this,{'section_tipo':'$this->tipo'})\">".label::get_label('update_cache')." $this->tipo *
								#</div>";
							}							
						}
						
						

					$html_buttons .= "\n</div>";#end section_buttons_container
					$html_contenido .= $html_buttons;




					

					#$html_contenido .= "\n<div id=\"stats_info\"><!-- Stats content here --></div>";


					# Content html
					$html_contenido .= "\n $html_section_add ";

					# Time machine section button
					#$html_contenido .= "\n $html_section_tm ";
						
		case 2	: 
		case 3	:	
					break;			
	}
	$html_contenido .= "\n</div><!-- /css_section_content -->";

	
	
	
	# PRINT HTML
	#print $html_label;
	print $html_contenido;
	
	
	print "\n</div><!-- /css_section_wrap SECTION [tipo:$tipo modo:$modo] -->\n\n"; //wrap


	# Time machine section button and rows list					
	print $html_section_tm;	
	
	
?>