<?php
	
	# VISUALIZADOR HTML	
	
	print "\n\n<!-- SECTION LIST [tipo:$tipo modo:$modo] -->";

	print "\n<div class=\"css_section_wrap css_section_wrap_{$modo} wrap_section wrap_section_{$tipo}\"	id=\"section_wrap_{$tipo}\"
	data-modo=\"$modo\"
	data-options=\"\"
	>";
	
	
		# ETIQUETA (LABEL)
		#print $context;
		$html_label='';
		switch ($context) {

			case 'list_into_tool_portalXX':
				$html_label 	= '';
				break;

			default:
				/*
				$html_label 	.= "\n<div class=\"css_section_titulo\" >";
				$html_label 	.= component_common_draw::draw_label($this);
				if(SHOW_DEBUG)
				$html_label 	.= " [context:$context] ";
				$html_label 	.= "</div>";
				#$html_label  	.= "\n<div class=\"css_section_titulo\" > Número: ".$dato." </div>";
				*/
				#print "\n<script>$('#current_section_label').html('$label').css('right','8px')</script>";
				break;
		}
		
		
		
		
		# CONTENIDO (INPUT)
		$html_contenido = "\n<div class=\"css_section_content section_content_list section_list_rows_content_div\">";
		
		switch($permissions) {
				
			case 0	:

				$html_contenido .= "\n<span class=\"css_span_dato sin_acceso\"> ".label::get_label('contenido_no_autorizado')." </span>";
				break;
							
			case ($permissions>=1) :	

				#
				# BUTTONS
				#
					$html_buttons='';
					$html_buttons .= "\n<div class=\"section_buttons_container\">";

						#
						# PORTAL BUTTONS: SHOW ALL / SHOW FILTERED 
						# Add buttons for tool_portal mode (modo is 'list' but url request contain var m=tool_portal)
						if (isset($_REQUEST['m']) && $_REQUEST['m']=='tool_portal') {					
							#dump($search_options_session_key, " search_options_session_key ".to_string());
							#dump($_SESSION['dedalo4']['config']['search_options'][$search_options_session_key]->filter_by_section_creator_portal_tipo, " search_options_session_key ".to_string());
							#$search_options_session_key = ''.$tipo.'_'.$modo.'_'.TOP_TIPO;	// section_ .'_'.$_REQUEST['t']
							if(!empty($_SESSION['dedalo4']['config']['search_options'][$search_options_session_key]->filter_by_section_creator_portal_tipo)){
								$current_btn_label = label::get_label('mostrar_todos');
								$current_btn_class = 'show_full';
							}else{
								$current_btn_label = label::get_label('mostrar_filtrados');
								$current_btn_class = 'show_filtered';
							}

							$html_buttons .= "
							<div id=\"btn_tool_portal_show_full\" class=\"btn_inside_section_buttons_container $current_btn_class\"
							data-search_options_session_key=\"$search_options_session_key\" 
							data-mode=\"$current_btn_class\" 
							onclick=\"tool_portal.show_more_toggle(this)\">
							$current_btn_label";
							if(SHOW_DEBUG) {
								$html_buttons .= " $search_options_session_key";
							}
							$html_buttons .= "</div>";
						}//end if (isset($_REQUEST['m']) && $_REQUEST['m']=='tool_portal') {


						#
						# SECTION TOP BUTTONS (new, stats, print, etc)
						# dump($ar_buttons, 'ar_buttons', array());
						foreach((array)$ar_buttons as $current_button_modelo_name => $current_ar_button_obj_model) {
							# Skip delete button
							#if($current_button_modelo_name=='button_stats') continue;
							foreach($current_ar_button_obj_model as $current_button_obj) {
								#dump($current_button_obj, ' $current_button_obj ++ '.to_string());								
								# Set buton target tipo
								$current_button_obj->set_target($tipo);
								$html_buttons .= $current_button_obj->get_html();
							}						
						}


						#
						# TOOL_EXPORT button for export to csv, etc.						
						$authorized_tool = (bool)component_security_tools::is_authorized_tool_for_logged_user('tool_export');
						if ($authorized_tool && defined('DEDALO_TOOL_EXPORT_FOLDER_PATH') && !$is_process_section) {
							$tool_export = new tool_export($tipo,'button');
							$html_buttons  .= $tool_export->get_html();
						}
							
										
						
						/* # TOOL_DIFFUSION button for export to mysql OLD
							$authorized_tool = (bool)component_security_tools::is_authorized_tool_for_logged_user('tool_diffusion');						
							if ($authorized_tool && defined('DEDALO_DIFFUSION_MAP')) {
								$DEDALO_DIFFUSION_MAP = unserialize(DEDALO_DIFFUSION_MAP);
								#dump($DEDALO_DIFFUSION_MAP, ' DEDALO_DIFFUSION_MAP ++ '.to_string($tipo));
								if (isset($DEDALO_DIFFUSION_MAP[$tipo]) && !$is_process_section) {								
									$tool_diffusion = new tool_diffusion($tipo,'button');
									$html_buttons  .= $tool_diffusion->get_html();									
								}
							}
							*/


						#
						# TOOL_DIFFUSION button for export to mysql
						if ((bool)component_security_tools::is_authorized_tool_for_logged_user('tool_diffusion') &&
							(bool)tool_diffusion::have_section_diffusion($tipo)) {
							$tool_diffusion = new tool_diffusion($tipo,'button');							
							$html_buttons  .= $tool_diffusion->get_html();
						}
						


						#
						# DEBUG BUTTONS
						# Special debug only buttons
						$is_global_admin = component_security_administrator::is_global_admin( navigator::get_user_id() );						
						if( (SHOW_DEBUG || $is_global_admin) && !isset($_REQUEST['cache_updated'])	) {
							if(isset($_GET['m']) && strpos($_GET['m'], 'tool')!==false) {
								# Nothing to show
							}else{								
								if (isset($context->context_name) && $context->context_name=='section_tool') {
									# Section tool is not updateable
								}else{
									#
									# TOOL_UPDATE_CACHE
									$tool_update_cache = new tool_update_cache($tipo,'button');
									$html_buttons     .= $tool_update_cache->get_html();

									# Temporal
									#$html_buttons .= "\n <div id=\"button_update_cache\" class=\"btn_inside_section_buttons_container\"
									#onclick=\"tool_update_cache.update_cache(this,{'section_tipo':'$this->tipo'})\">".label::get_label('update_cache')." $this->tipo *
									#</div>";
								}							
							}																					
						}
						

					$html_buttons .= "\n</div>";//end section_buttons_container
					$html_contenido .= $html_buttons;
				

				#$html_contenido .= "\n<div id=\"stats_info\"><!-- Stats content here --></div>";


				#
				# CONTENT HTML
				#
					# SEARCH_FORM_HTML
					$html_contenido .= $search_form_html;

					# ROWS_LIST_HTML
					$html_contenido .= $rows_list_html;
				

				# Time machine section button
				#$html_contenido .= "\n $html_section_tm ";
				break;			
		}

		$html_contenido .= "\n</div><!-- /css_section_content -->";

	
	
	
	# PRINT HTML
	#print $html_label;
	echo $html_contenido;
	
	
	echo "\n</div><!-- /css_section_wrap SECTION [tipo:$tipo modo:$modo] -->\n\n"; //wrap


	#
	# Time machine section button and rows list					
	echo $time_machine_html;	
	
	
?>