<?php

	# VISUALIZADOR HTML	
	
	print '<!-- LOGIN [tipo:$tipo id_matrix:$id] -->';
	print '<div class="login_body">';
	print '<div class="css_wrap_login" id="wrap_login">';

	#
	# MAINTENANCE
	$maintenance_mode_class='';
	if (DEDALO_MAINTENANCE_MODE===true) {
		$label = label::get_label('sitio_en_mantenimiento');		
		if ( strpos($label, '.')!==false ) {
			$label = substr($label, 0, strpos($label, '.') );
		}
		echo "<div class=\"maintenance_advice main_font_light\">$label</div>";
		$maintenance_mode_class = 'maintenance_mode_class';
	}

	print '<form class="css_form '.$maintenance_mode_class.'" name="form_login" id="form_login" action="" method="post">'; // onsubmit="login.Login()"


		# CONTENIDO (INPUT)
		$html_content = '';

			// lang jump
				$html_content .= $dedalo_aplication_langs_selector_html;
			
			// username
				$username_value = (DEDALO_ENTITY==='dedalo4_demo') ? "dedalo" : null;
				$html_content .= "<input type=\"text\" ";
				$html_content .= "class=\"login_input\" ";
				$html_content .= "id=\"login_username\" ";
				$html_content .= "name=\"login_username\" ";
				$html_content .= "value=\"$username_value\" ";
				$html_content .= "placeholder=\"".$username_label."\" ";
				$html_content .= "maxlength=\"64\" ";
				$html_content .= "/>";
			
			// password
				$username_password = (DEDALO_ENTITY==='dedalo4_demo') ? "dedalo4Demo" : null;
				$html_content .= "<input type=\"password\" ";
				$html_content .= "class=\"login_input\" ";
				$html_content .= "id=\"login_password\" ";
				$html_content .= "name=\"login_password\" ";
				$html_content .= "value=\"$username_password\" ";
				$html_content .= "placeholder=\"".$password_label."\" ";
				$html_content .= "maxlength=\"64\" ";
				$html_content .= "/>";

			// button login
				$html_content .= $html_button_login;
			
			// hidden inputs
				$html_content .= "<input type=\"hidden\" id=\"tipo_login\" value=\"$tipo\">";
				$html_content .= "<input type=\"hidden\" id=\"tipo_username\" value=\"$tipo_username\">";
				$html_content .= "<input type=\"hidden\" id=\"tipo_password\" value=\"$tipo_password\">";
				$html_content .= "<input type=\"hidden\" id=\"tipo_active_account\" value=\"$tipo_active_account\">";
			
			// Ajax response	
				$html_content .= '<div id="login_ajax_response" class="login_ajax_response"></div>';

			// Version : Dedalo verrsion info
				$html_content .= '<div class="dedalo_version">';

					$html_content .= 'Dédalo version ' . DEDALO_VERSION . ' - Build ' . DEDALO_BUILD ;

					# Postgres user and db name
					if(DEDALO_ENTITY==='development') {
						$html_content .= "<br> ".DEDALO_USERNAME_CONN." -> ".DEDALO_DATABASE_CONN ;
					}					

					try {
					    $str_version   = RecordObj_dd::get_termino_by_tipo(DEDALO_ROOT_TIPO);
						$html_content .= "<br>DD version: $str_version";
					} catch (Exception $e) {
					    $html_content .= 'Excepction: ' . $e->getMessage() . "\n";
					}

					if(DEVELOPMENT_SERVER===true) {
						$html_content .= "<span class=\"note\">";
						$html_content .= " ".DEDALO_DATABASE_CONN." ";
						$html_content .= "  - ".DEDALO_HOSTNAME_CONN." ";
						$html_content .= "  - ".DEDALO_USERNAME_CONN." ";
						#$html_content .= " : ".DEDALO_DB_PORT_CONN." ";
						$html_content .= "</span>";
					}				
			
				$html_content .= "</div>";

			// SAML login
				if (defined('SAML_CONFIG') && SAML_CONFIG['active']===true) {
					/*
					$button_label = 'Autologin';// label::get_label('autologin')
					$html_content .= '<button type="button" class="btn btn-success btn-block autologin" onclick="login.autologin(\''.SAML_CONFIG['url'].'\')">'.$button_label.'</button>';
					if(SAML_CONFIG['debug']===true) {
						$html_content .= '<br>SAML ';
						$html_content .= '   <a href="'.SAML_CONFIG['url'].'/metadata.php">Metadata</a>';
						$html_content .= ' | <a href="'.SAML_CONFIG['url'].'/acs.php">ACS</a>';
						$html_content .= ' | <a href="'.SAML_CONFIG['url'].'/sls.php">SLS</a>';
						$html_content .= '</br>';
					}
					*/
					$html_content .= include(dirname(__FILE__) . '/saml_button.phtml');
				}


		// js
			$html_content .= '<script>';
			$init_options = new stdClass();
				$init_options->development_server  		= DEVELOPMENT_SERVER;
				$init_options->dedalo_maintenance_mode 	= DEDALO_MAINTENANCE_MODE;
			$html_content .= "login.init(".json_encode($init_options).");";
			$html_content .= '</script>';

		
		
		# PRINT HTML
		print $html_content;


	
	
	print '</form>';	
	print '</div>'; //css_wrap_login	
	print '</div>'; //login_body


