<?php
$saml_button_html = '';
if(defined('SAML_CONFIG')) {
	$button_label = 'Autologin';// label::get_label('autologin')
	$saml_button_html .= '<button type="button" class="btn btn-success btn-block autologin" onclick="login.autologin(\''.SAML_CONFIG['url'].'\')">'.$button_label.'</button>';
	if(SAML_CONFIG['debug']===true) {
		$saml_button_html .= '<br>SAML ';
		$saml_button_html .= '   <a href="'.SAML_CONFIG['url'].'/metadata.php">Metadata</a>';
		$saml_button_html .= ' | <a href="'.SAML_CONFIG['url'].'/acs.php">ACS</a>';
		$saml_button_html .= ' | <a href="'.SAML_CONFIG['url'].'/sls.php">SLS</a>';
		$saml_button_html .= '</br>';
	}
}
return $saml_button_html;