<div class="main_menu">
<ul>
<?php
# MENU DEFAULT
if($this->main_menu_data) foreach ($this->main_menu_data as $key => $row) {
	#dump($row, ' row ++ '.to_string());

	$link 	= __WEB_ROOT_WEB__ .'/web/' . common::generate_url($row->web_path);
		#dump($link, ' link ++ '.to_string());

	$row_html  = '';
	$row_html .= '<li>';
	$row_html .= '<a href="'.$link.'" title="'.$row->titulo.'">';
	$row_html .= $row->term;
	if(SHOW_DEBUG===true) {
		#$row_html .= ' <span>['.$row->term_id.']</span>';
	}
	$row_html .= '</a>';
	$row_html .= '</li>';

	echo $row_html;
	
}//end if (isset($this->main_menu_data))
?>
</ul>
</div>





