<!DOCTYPE html>
<html>
<head>
	<title><?php echo $page_title ?></title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<?php echo $css_links ?>
	<?php echo $js_links ?>
</head>
<body>
<section id="header"><?php echo $header_html ?></section>
<section id="content"><?php echo $content_html ?></section>
<section id="footer"><?php echo $footer_html ?></section>
</body>
</html>