<?php

	# VISUALIZADOR HTML


	print "\n<!-- RELATION_PARENT [tipo:$tipo section_id:$parent section_tipo:$section_tipo] $label -->";

	print "\n<div class=\"wrap_component css_wrap_relation_parent wrap_component_{$modo} wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-parent=\"{$parent}\"
	data-section_tipo=\"{$section_tipo}\"
	data-modo=\"{$modo}\"	
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	data-children_component_tipo=\"{$children_component_tipo}\"
	>";

	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	# CONTENIDO (INPUT)
	$html_content = '';
	switch($permissions) {

		case 0 :
				$html_content .= "";
				break;

		case 1 :
				$html_content .= $this->valor;
				break;

		case 2 :
		case 3 :

				$html_content .= "<div class=\"wrap_relation_parent_values\">";

					# ADD BUTTON
					$html_content .= "<div class=\"button_add relation_parent_add_button\"
					data-target_tipo=\"$section_tipo\"
					onclick=\"component_relation_parent.open_parent_selector_window(this,event)\">					
					</div>";

				
					foreach ((array)$dato as $key => $current_parent) {

						$html_content .= "<div class=\"relation_parent_input_line\">";

						# REMOVE BUTTON
						$html_content .= "<input type=\"button\" class=\"button_remove component_relation_parent_button_remove\" value=\"\"
											data-role=\"component_relation_parent_button_remove\"
											data-children_section_tipo=\"$current_parent->section_tipo\"
											data-children_section_id=\"$current_parent->section_id\"
											data-children_component_tipo=\"$current_parent->component_tipo\"
											onclick=\"component_relation_parent.remove_parent(this)\" />";

						# TERM STRING
						$value = $this->get_parent_value( $current_parent->section_id, $current_parent->section_tipo); // Provissional !!
						$html_content .= '<span class="locator_label">'.$value.'</span>';

						$html_content .= "</div>";//relation_parent_input_line
					}					

				$html_content .= "</div>";//end wrap_parent_values

				

				/*
				$html_content .= "<object type=\"image/svg+xml\" data=\"../themes/default/open.svg\" class=\"relation_parent_add_button\"
				data-target_tipo=\"$section_tipo\"
				onclick=\"component_relation_parent.open_parent_selector_window(this,event)\">					
				</object>";
				*/
				#$html_content .= "<div class=\"\" style=\"content:ur('../themes/default/open.svg')\"> 123 </div>";



				if(SHOW_DEBUG) {
					#$html_content .= "\n <div class=\"debug_info\"> Current val: <strong>$valor</strong></div>";				
					#$html_content .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\">{$debugger}</span>";
					$html_content .= "\n <span class=\"debug_info\">";
					$html_content .= "<br> locators in section relation (parent.tipo: ".$this->relation_type.") : ";
					#$html_content .= wrap_pre( to_string($this->get_my_section_relations($this->relation_type)), false );
					$html_content .= "<br><span>".component_relation_parent::$get_parents_query."</span>";
					$html_content .= "</span>";
				}


				break;
	}

	# Prepare content to show in page
	tools::prepare_content($html_content);


	# PRINT HTML
	print $html_label;
	print $html_content;


	print "\n</div><!-- /css_wrap_relation_parent RELATION_PARENT [tipo:$tipo section_id:$parent] $label -->\n\n"; //wrap
?>
