<?php

	# VISUALIZADOR HTML	

	$var_requested = common::get_request_var($tipo);
	#if(isset($_REQUEST[$tipo])) $dato = $_REQUEST[$tipo];	#var_dump($_REQUEST[$tipo]);
	if(!empty($var_requested)) $dato = $var_requested;
	
	print "\n<!-- ".__CLASS__." -->";
	print "\n<div class=\"wrap_component css_wrap_relation_parent\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch($permissions) {
			
		case 0	:	$html_content .= "";
					break;
						
		
		case ($permissions>=1)	:

					# COMPARISON OPERATORS
					$html_content .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);

					
					# INPUT
					$html_content .= "\n<input class=\"css_relation_parent\" type=\"text\" name=\"{$search_input_name}\" value=\"\"/> ";
					

					# LOGICAL OPERATORS
					$html_content .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);

					if(SHOW_DEBUG===true) {
						$html_content .= "<span class=\"debug_info\">$search_input_name</span>";
					}
											
	}
	
	# Prepare content to show in page
	tools::prepare_content($html_content);
	

	# PRINT HTML
	print $html_label;
	print $html_content;	

	
	print "\n</div><!-- /css_wrap_relation_parent -->\n\n"; //wrap
?>