<?php
/**
* TOOL_LAYOUT_PRINT PAGE
*/

$html='';

	$html   .= "\n<!-- TOOL LAYOUT PRINT PAGE [tipo:$tipo] -->";
	#$html   .= "\n<div class=\"section_title text_shadow_inset\" > TOOL LAYOUT PRINT - $section_title ( context_name: $context_name )</div>";



	#
	# LIST
	if ($context_name=='list') {
	
		$html .= "<div id=\"wrap_list\">";
		$html .= $html_list;
		$html .= "</div><!-- /wrap_list -->";
	}

	#
	# EDIT
	if ($context_name=='edit') {

		$html .= "<div id=\"wrap_edit\">";
		$html .= $html_edit;
		$html .= "</div><!-- /wrap_edit -->";
	}	
	
	#
	# RENDER
	if ($context_name=='render') {

		$html .= "<div id=\"wrap_render\">";
		$html .= $html_render;
		$html .= "</div><!-- /wrap_render -->";
	}	
echo $html;
?>