<?php

	# VISUALIZADOR HTML	
		
	# BUTTON TOOL
	$html_tool    = "\n<!-- TOOL POSTERFRAME [tipo:$tipo id_matrix:$id] -->";
	$html_tool   .= "<div class=\"tool_inspector_div\">";

	$btn_title	  = label::get_label('abrir').' '.label::get_label('herramienta');
	$html_tool   .= "\n<div class=\"icon_bs tool_posterframe_icon link\"
								data-tipo=\"{$tipo}\" data-id_matrix=\"{$id}\"
								title=\"$btn_title\"
								onclick=\"tool_common.open_tool_posterframe(this)\"
								> </div>";


	$html_tool   .= label::get_label('tool_posterframe');	#" Posterframe";	
		

	$html_tool   .= "</div>";#/tool_inspector_div

	# PRINT HTML
	print $html_tool;
	
?>