// @license magnet:?xt=urn:btih:0b31508aeb0634b347b8270c7bee4d411b5d4109&dn=agpl-3.0.txt AGPL-3.0
/*global get_label, page_globals, SHOW_DEBUG, DEDALO_LIB_URL, DEDALO_CORE_URL, DEDALO_MEDIA_URL */
/*eslint no-undef: "error"*/



// imports
	import {ui} from '../../common/js/ui.js'
	import {handler_open_viewer} from '../../component_media_common/js/component_media_common.js'



/**
* VIEW_DEFAULT_LIST_3D
* Client-side list view for component_3d — renders the 3D component as a
* thumbnail image inside a standard list-row wrapper.
*
* This module provides two exports:
*   - `view_default_list_3d`   — the view constructor (namespace object / no-op).
*   - `get_content_data`       — the content subtree builder, exported so it can
*                                be reused by other list views (e.g. search results).
*
* Rendering strategy:
*   In list mode the component does NOT embed the Three.js viewer.  Instead, it
*   displays the 'thumb' quality still image (generated by the server when the
*   3D file is first uploaded) with a click/mousedown handler that opens the
*   full interactive viewer in a separate window via `handler_open_viewer`.
*   If no thumb exists the posterframe is used as fallback; if that too is
*   absent, `page_globals.fallback_image` is shown.
*
* Data contract (self.data):
*   {
*     entries        : Array<FileInfoObject>  // flat list — only 'default' and
*                                             // 'thumb' qualities are included
*                                             // in list mode (server filters via
*                                             // get_list_value())
*     posterframe_url: string|null            // server-rendered still or null
*   }
*
*   FileInfoObject shape (each element of entries):
*   {
*     quality    : string  // e.g. 'thumb', 'default', 'original'
*     file_path  : string  // media-relative path, prepend DEDALO_MEDIA_URL
*     file_exist : boolean // true when the physical file is confirmed on disk
*     extension  : string  // file extension, e.g. 'glb'
*     file_name  : string
*     file_size  : number
*   }
*/
export const view_default_list_3d = function() {

	return true
}//end  view_default_list_3d



/**
* RENDER
* Builds the full list-row DOM tree for a component_3d instance.
*
* When `options.render_level === 'content'` the function short-circuits and
* returns only the inner content_data node, skipping the outer wrapper.
* This is used by callers that assemble the wrapper themselves (e.g. portal
* or dataframe list renderers).
*
* @param {Object} self - component_3d instance; must expose `.data`, `.tipo`,
*   `.section_tipo`, `.section_id`, `.context`, `.quality`, and `.permissions`.
* @param {Object} options - render configuration object.
* @param {string} [options.render_level='full'] - 'full' builds wrapper +
*   content; 'content' returns the inner content node only.
* @returns {Promise<HTMLElement>} wrapper div with CSS classes
*   `wrapper_component component_3d <tipo> <section_tipo>_<tipo> list view_default
*   media media_wrapper`, or the bare content_data node when render_level is
*   'content'.
*/
view_default_list_3d.render = async function(self, options) {

	// options
		const render_level = options.render_level || 'full'

	// content_data
		const content_data = get_content_data(self)
		if (render_level==='content') {
			return content_data
		}

	// wrapper
		const wrapper = ui.component.build_wrapper_list(self, {
			add_styles : ['media','media_wrapper']
		})
		wrapper.appendChild(content_data)
		// set pointers
		wrapper.content_data = content_data


	return wrapper
}//end render



/**
* GET_CONTENT_DATA
* Builds the inner content subtree for the list view: a thumbnail `<img>` that
* opens the interactive 3D viewer (or the upload tool, when no file exists) on
* mousedown.
*
* Quality resolution waterfall for the thumbnail source URL:
*   1. 'thumb' entry in `data.entries` where `file_exist === true`
*      → prepend DEDALO_MEDIA_URL to `file_path`
*   2. `data.posterframe_url` (server-rendered still)
*      → append `?t=<timestamp>` to bust the browser cache
*   3. `page_globals.fallback_image` (global placeholder path)
*
* The resolved `quality` from `self.quality` or `self.context.features.quality`
* is used to locate the primary file_info entry (default/original quality) for
* passing to `handler_open_viewer`, even though the displayed thumbnail always
* comes from the 'thumb' quality entry.
*
* Side effects:
*   - Attaches a `load` event listener on the image to run `set_bg_color` once;
*     the listener self-removes after the first fire.  The body of `set_bg_color`
*     is currently a no-op (the `ui.set_background_image` call is commented out).
*   - Attaches an `error` event listener that swaps `src` to the global fallback
*     image if the primary URL fails to load; the guard `image.src!==fallback`
*     prevents an infinite error loop if the fallback itself fails.
*   - Attaches a `mousedown` listener bound to `self` that delegates to
*     `handler_open_viewer`, which either opens the viewer window or the upload
*     tool depending on whether any file exists.
*   - Sets `image.open_window_features` so `handler_open_viewer` can read the
*     desired viewer window dimensions (1024 × 720 px) from the element.
*
* @param {Object} self - component_3d instance.
* @returns {HTMLElement} content_data div containing the thumbnail `<img>`.
*/
export const get_content_data = function(self) {

	// short vars
		const data				= self.data || {}
		const entries			= data.entries || [] // value is a files_info list
		const files_info		= entries
		const quality	= self.quality || self.context.features.quality

	// content_data
		const content_data = ui.component.build_content_data(self)

	// posterframe (used as fallback)
		const posterframe_url = data.posterframe_url
			? data.posterframe_url + '?t=' + (new Date()).getTime()
			: page_globals.fallback_image

	// thumb, if thumb doesn't exist get the posterframe then if the posterframe doesn't exist get the default image.
		const thumb	= files_info.find(el => el.quality==='thumb' && el.file_exist===true) //

	// URL
	// if thumb doesn't exist get the posterframe then if the posterframe doesn't exist get the default image.
		const url = thumb?.file_path
			? DEDALO_MEDIA_URL + thumb.file_path
			: posterframe_url

		const file_info	= files_info.find(item => item.quality===quality)

	// image
		const image = ui.create_dom_element({
			element_type	: 'img',
			class_name		: 'link',
			parent			: content_data
		})
		image.loading = 'lazy'
		// tells handler_open_viewer window dimensions
		image.open_window_features = {
			width	: 1024,
			height	: 720
		}

		// load event . image background color
			image.addEventListener('load', set_bg_color, false)
			function set_bg_color() {
				this.removeEventListener('load', set_bg_color, false)
				// ui.set_background_image(this, this)
			}
		// error event
			image.addEventListener('error', () => {
				if (image.src!==page_globals.fallback_image) {
					image.src = page_globals.fallback_image
				}
			}, false)

		// set image src
			image.src = url

		// open viewer. Media common handler for 3d, av, image, pdf, svg
			image.addEventListener('mousedown', handler_open_viewer.bind(self))


	return content_data
}//end get_content_data



// @license-end
