<?php
	

	# VISUALIZADOR HTML	
	$html    = "";

	#$html    .= "\n<!-- TOOL PAGE [tipo:$tipo] -->";	
	#$html   .= "\n<div class=\"wrap_tool wrap_tool_indexation_page\" >";
	#$html   .= "\n<div class=\"content_data text_shadow_inset\" >";

		/*
		$html   .= "\n<script>
					var media_base_path = '',
						media_extension = ''									
					</script>";
		*/

		$html   .= "\n<div class=\"relaciones_list_title\" >";
		$html 	.= " Index id: $tag_value";
		$html   .= "\n</div>";

		$html .= $registros_list_html ;


	
	#$html .= "\n</div><!-- /content_data -->";
	#$html .= "\n</div><!-- /wrap_tool -->"; //wrap_tool


	print $html;
		
?>