<?php
	
	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_module_wrap']))				$ar_css['css_module_wrap']='';
	if(!isset ($ar_css['css_module_titulo']))			$ar_css['css_module_titulo']='';

	if(!isset ($ar_css['css_span_dato'])) 				$ar_css['css_span_dato']='';;
	
	
	
	print "\n\n<!-- MODULE [tipo:$tipo id_matrix:$id] -->";
	print "\n<div class=\"css_module_wrap {$ar_css['css_module_wrap']}\" >";
	
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	print "\n<div class=\"css_module_titulo\" ><hr> MODULE: $html_label </div>";
	
		
	
	# CONTENIDO (INPUT)
	$html_contenido = "\n<div class=\"css_module_content\" >";
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." </span>"; 		
					break;
						
		case ($permissions>=1)	:
		
					foreach ($ar_section as $key => $section){
						
						$label	= $section->get_label();
						$tipo	= $section->get_tipo();
						
						
						if($selected_section == 	$tipo) {
							$html_contenido .= "\n <b>$label</b>  ";
						}else{
							$html_contenido .= "\n <a href=\"?modo=list&section=$tipo\"> $label </a> ";
						}
						
						
						if($key != end(array_keys($ar_section))) $html_contenido .=	 ' | ';	
						
					}					
			
					$html_contenido .= "\n $html_section ";	
						
		case 2	: 
		
		case 3	:	
					break;			
	}
	$html_contenido .= "\n</div>";
	
	
	# PRINT HTML
	print $html_contenido;

	# INIT COMPONENT
	#require(DEDALO_LIB_BASE_PATH . "/component_common/trigger.component_init.php");
	
	
	print "\n</div><!-- /MODULE [$tipo] -->\n\n"; //wrap
?>