<?php

	# VISUALIZADOR HTML
	
	print "<div class=\"wrap_component css_wrap_number tooltip_active\" id=\"wrap_{$tipo}\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato='".json_encode($dato)."' ";
	print 'title="'.search_development2::search_options_title( $this->search_operators_info() ).'" ';
	print ">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "";
					break;
						
		case ($permissions>=1):
		
					$html_contenido .= "<input class=\"css_number\" type=\"text\" ";
					$html_contenido .= "name=\"{$tipo}\" ";
					$html_contenido .= "data-tipo=\"{$tipo}\" ";
					$html_contenido .= "value=\"{$dato}\" title=\"$html_title\" ";
					$html_contenido .= "/>";											
	}

	# Prepare content to show in page
	tools::prepare_content($html_contenido);	
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "</div>"; //wrap
?>