<?php

	# VISUALIZADOR HTML		
	
	
	print "\n<!-- ORDER [tipo:$tipo section_id:$parent] $label -->";

	print "\n<div class=\"wrap_component css_wrap_order wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-modo=\"{$modo}\"
	data-dato=\"{$dato}\"
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";
	
		
		# ETIQUETA (LABEL)
		$html_label = component_common_draw::draw_label($this);
		
		# CONTENIDO (INPUT)
		$html_contenido = '';
		switch($permissions) {
				
			case 0	:	$html_contenido .= "";
						break;
							
			case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato\">$dato</span>";
						break;
							
			case ($permissions>=2) :
					
						$html_contenido .= "\n <input class=\"css_order\" type=\"text\" onchange=\"component_order.Save(this)\"
						name=\"{$input_name}\" 
						data-tipo=\"{$tipo}\"
						data-section_tipo=\"{$section_tipo}\"
						data-parent=\"{$parent}\"
						data-lang=\"{$lang}\" 
						value=\"{$dato}\" 
						title=\"$html_title\"
						/>";
						
						#$html_contenido .= "\n <span  class=\"css_span_log\"></span>";					
						#$html_contenido .= "\n <span  class=\"css_span_ejemplo\">$ejemplo</span>";						
						
						if(SHOW_DEBUG) {
							#$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
						}	
						break;									
		}

		# Prepare content to show in page
		tools::prepare_content($html_contenido);	
		

		# PRINT HTML
		print $html_label;
		print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_order ORDER [tipo:$tipo section_id:$parent] $label -->\n"; //wrap


?>