<?php

	# VISUALIZADOR HTML	
			
	
	print "\n<!-- FILTER MASTER [tipo:$tipo section_id_matrix:$parent] -->";

	print "\n<div class=\"wrap_component css_wrap_filter_master wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-modo=\"{$modo}\"
	data-dato=\"{$dato_string}\"
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";
	
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch(true) {
			
		case ($permissions==0) :

				$html_contenido .= ""; 
				break;
						
		case ($permissions==1)	:

				$html_contenido .= "<ul class=\"filter_master_list\">";

				$i=1;foreach ($ar_proyectos_section as $value => $rotulo) {
					
					$html_contenido .= "<li>";						
					$html_contenido .= "- <label class=\"css_check_box_filter_master_rotulo\">$rotulo</label>";						
					$html_contenido .= "</li>";

				$i++;}

				$html_contenido .= "</ul>";
				break;	
						
		case ($permissions>=2)	:					

				$disabled = ($user_id_logged==$user_id_viewed) ? 'disabled' : '';	

				$html_contenido .= "<ul class=\"filter_master_list\">";

				$i=1;foreach ($ar_proyectos_section as $current_section_id => $rotulo) {
					
					$html_contenido .= "<li>";

						$checked  = is_array($dato) && in_array($current_section_id, array_keys($dato)) ? 'checked="checked"' : '';
						$tabindex = ($i==1) ? 'tabindex="1"' : '';

						$html_contenido .= "\n <input class=\"css_check_box_filter_master\" type=\"checkbox\"
						onchange=\"component_filter_master.Save(this)\"
						name=\"{$input_name}\"
						value=\"{$current_section_id}\"
						title=\"$html_title\"
						data-tipo=\"{$tipo}\"
						data-lang=\"{$lang}\"
						data-section_tipo=\"{$section_tipo}\"
						data-parent=\"{$parent}\"
						$checked
						$disabled
						$tabindex
						/>";
						
						$html_contenido .= "<label class=\"css_check_box_filter_master_rotulo\" $required >";
						if(SHOW_DEBUG) {
							$html_contenido .= "[$current_section_id] ";
						}
						$html_contenido .= $rotulo;
						$html_contenido .= "</label>";	
						
					$html_contenido .= "</li>";

				$i++;}

				$html_contenido .= "</ul>";
				
	
				if(SHOW_DEBUG) {
					#$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";
				}
				break;							
	}


	# Prepare content to show in page
	tools::prepare_content($html_contenido);

	
	# PRINT HTML
	print $html_label;
	print $html_contenido;


	print "\n</div>\n\n"; //wrap

?>