<?php

	# VISUALIZADOR HTML	
			
	
	print "\n<!-- FILTER MASTER [tipo:$tipo section_id_matrix:$parent] -->";

	print "\n<div class=\"wrap_component css_wrap_filter_master wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-parent=\"{$parent}\"
	data-modo=\"{$modo}\"
	data-dato=\"{$dato_string}\" data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";
	
	//data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-parent=\"{$parent}\" data-modo=\"ajax\"
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= ""; 
					break;
						
		case 1	: 	if (is_array ($ar_proyectos_section)) foreach ($ar_proyectos_section as $value => $rotulo) {
						
						if( is_array($dato) && in_array($value,$dato) ) {
							$checked = 'checked="checked"';
						}else {
							$checked = "";
						}
						$html_contenido .= "\n <input class=\"css_check_box_filter_master\" type=\"checkbox\" 
						name=\"{$input_name}\"
						data-tipo=\"{$tipo}\" data-section_tipo=\"{$section_tipo}\" data-parent=\"{$parent}\"
						value=\"{$value}\" title=\"$html_title\" 
						$checked  disabled />";						
						$html_contenido .= "\n <label class=\"css_check_box_filter_master_rotulo\" $required >$rotulo</label>";	
					}
					break;	
						
		case ($permissions>=2)	:

					# VERIFY USER LOGGED IS CURRENT VIEWED USER			
						$user_id_logged = navigator::get_user_id();							#dump($user_id_logged,'user_id_logged');
						$user_id_viewed = $parent;
						
						$disabled = NULL;
						if($user_id_logged==$user_id_viewed)
							$disabled = "disabled";
						#dump($dato,"dato");
						#dump($ar_proyectos_section,"");

					foreach ($ar_proyectos_section as $value => $rotulo) {
						
						if( in_array($value, array_keys($dato)) ) {
							$checked = 'checked="checked"';
						}else {
							$checked = "";
						}
						$html_contenido .= "\n <input class=\"css_check_box_filter_master\" type=\"checkbox\"
						onchange=\"component_filter_master.Save(this)\"
						name=\"{$input_name}\"
						data-tipo=\"{$tipo}\"
						data-lang=\"{$lang}\"
						data-section_tipo=\"{$section_tipo}\"
						data-parent=\"{$parent}\"
						value=\"{$value}\"
						title=\"$html_title\"
						$checked
						$disabled
						/>";
						
						$html_contenido .= "\n <label class=\"css_check_box_filter_master_rotulo\" $required >$rotulo</label><br>";	
					}					
					
		
					if($permissions==3) {
						$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";
					}
					break;					
							
	}


	# Prepare content to show in page
	tools::prepare_content($html_contenido);

	
	# PRINT HTML
	print $html_label;
	print $html_contenido;


	print "\n</div>\n\n"; //wrap

?>