<?php
	
	# VISUALIZADOR HTML	

	# ELEMENTOS	
	if(!isset ($ar_css['css_span_dato'])) 				$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_span_debugger'])) 			$ar_css['css_span_debugger']='';
	
	print "\n\n<!-- ROWS [$id] -->";	

	# CONTENIDO (INPUT)
	$html_contenido  = "\n<tr class=\"\" data-dato='$rel_locator'>";		
	
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." </span>";
					break;
						
		case ($permissions>=1)	:
					
					if( !is_array($ar_valor) || count($ar_valor)==0 ) {
						
						$html_contenido .= "\n <td class=\"section_list_td_border\">";
						#$html_contenido .= "No records found.. ";
						$html_contenido .= "\n </td>";
						
					}else{
					
						# TD ID
						$title=null;
						if(SHOW_DEBUG) $title .= "matrix id: $id";
						$html_contenido .= "\n <td class=\"section_list_td_border section_list_td_row id_column\" title=\"$title\">";		
						
							if(SHOW_DEBUG) {
								$html_contenido .= "<mark style=\"color:#a3a3a3;padding-right:5px\">$current_id</mark>";
							}

							# SECTION_ID TEXT
							$html_contenido .= "\n  $section_id ";
							$id_time_machine = $current_id;
							
							#
							# BUTTON RESTORE
							$title = label::get_label('recuperar') .' '.label::get_label('registro');
							if(SHOW_DEBUG) $title .= "\n id time machine: $id_time_machine";
					        $html_contenido .= "
					        <!-- BUTTON RECOVER -->
					        <div class=\"icon_bs tool_time_machine_goback_icon link\" title=\"$title\"
					        data-tipo=\"$section_tipo\"
					        data-section_id=\"$section_id\"
					        data-id_time_machine=\"$id_time_machine\"
					        onclick=\"tool_time_machine.section_list_recover_section(this)\"
					        ></div> ";

					        if(SHOW_DEBUG) {
					        	#$html_contenido .= "id_time_machine: $id_time_machine - $section_tipo ";
					        }

					        $html_contenido .= label::get_label('recuperar');


							# DEBUG INFO
							if($permissions==3)		
							$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$id}</span>";	
								
							

						$html_contenido .= "\n </td>";

						
						
						# TD DATOS
						foreach($ar_valor as $component_tipo => $valor_list) {

							# aditional td css selectors
							$modelo_name 	 = RecordObj_dd::get_modelo_name_by_tipo($component_tipo, true);
							$td_css_selector = 'td_'.$modelo_name;

							# CSS modificadores de estilos en las propiedades del section list (estructura)
							# Formato 
							# "dd83": {
							#        "CSS": {
							#            "style": {
							#                "width": "5%"
							#            },
							#			"class": {
							#                "column_test"
							#            }
							#        }
							#    },
							# dump($propiedades->$component_tipo->CSS->style,"");
							$style = '';
							if (isset($propiedades->$component_tipo->CSS->style)) {
								$style .= 'style="';
								foreach ((array)$propiedades->$component_tipo->CSS->style as $prop => $value) {
									$style .= $prop.':'.$value.';';
								}
								$style .= '"';
							}
							$css_class = '';
							if (isset($propiedades->$component_tipo->CSS->class)) {
								foreach ((array)$propiedades->$component_tipo->CSS->class as $current_class) {
									$css_class .= $current_class.' ';
								}
								#dump($propiedades->$component_tipo->CSS->class,"");
							}

							$html_contenido .= "\n <td class=\"section_list_td_border section_list_td_row $td_css_selector $css_class\" $style data-tipo=\"$component_tipo\">";
							if (strlen($valor_list)<20) {
								#dump($valor_list,"valor_list $component_tipo");
								#$valor_list = ' ,,,, ';
							}
							$html_contenido .= $valor_list ; 
							$html_contenido .= "\n </td>";
						}
					}
	}
	$html_contenido .= "\n</tr>";
	
	# PRINT HTML
	print $html_contenido;
	

?>