<?php
	
	# VISUALIZADOR HTML	

	# ELEMENTOS	
	if(!isset ($ar_css['css_span_dato'])) 				$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_span_debugger'])) 			$ar_css['css_span_debugger']='';
	
	print "\n\n<!-- ROWS [$id] -->";
		
	# Hilight unassigned (to projects filter) records
	$class_td_id = NULL;
	if( isset(filter::$ar_records_unassigned) && in_array($id, filter::$ar_records_unassigned) && $section_tipo!=DEDALO_ACTIVITY_SECTION_TIPO) 
		$class_td_id = 'unassigned';
		#dump(filter::$ar_records_unassigned);


	# CONTENIDO (INPUT)
	$html_contenido  = "\n<tr class=\"{$class_td_id}\">";	
	
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." </span>";
					break;
						
		case ($permissions>=1)	:
					
					if( !is_array($ar_rows) || count($ar_rows)==0 ) {
						
						$html_contenido .= "\n <td class=\"section_list_td_border\">";
						#$html_contenido .= "No records found.. ";
						$html_contenido .= "\n </td>";
						
					}else{
					
						# TD ID
						$title=null;
						if(SHOW_DEBUG) $title .= "matrix id: $id";
						$html_contenido .= "\n <td class=\"section_list_td_border section_list_td_row \" title=\"$title\">";					
						
							
							# ID TEXT
							$html_contenido .= "\n  $section_dato ";
							

							#
							# BUTTON EDIT
							# IF ISSET CALLER_ID ADD LINK VAR CALLER_ID
							switch ($context) {
								
								case 'list_into_tool_portal':
									# modo tool_portal
									$url 	= htmlspecialchars("?t=$section_tipo&id=$id&caller_id=$caller_id&m=edit&context=$context");
									$title 	= "Goto resource $section_dato [$id]";
									if(SHOW_DEBUG) $title .= "\n url:$url \n modo $modo, context $context";
									$html_contenido .= "<div class='css_section_group_image_edit div_image_link link' title=\"$title\" onclick=\"goto_url('$url')\"></div>";									
									break;

								case 'list_into_tool_relation':									
									# modo tool_relation
									$url 	= htmlspecialchars("?t=$section_tipo&id=$id&caller_id=$caller_id&m=edit&context=$context");
									$title 	= "Goto record $section_dato [$id]";
									if(SHOW_DEBUG) $title .= "\n url:$url \n modo $modo, context $context";
									$html_contenido .= "<div class='css_section_group_image_edit div_image_link link' title=\"$title\" onclick=\"goto_url('$url')\"></div>";									
									break;
								
								default:
									# modo normal (list)
									switch ($section_tipo) {
										case DEDALO_ACTIVITY_SECTION_TIPO:
											# nothing to show...
											break;
										default:
											$url 	= htmlspecialchars("?t=$section_tipo&id=$id&m=edit");
											$title 	= "Edit record $section_dato [$id]";
											if(SHOW_DEBUG) $title .= "\n url:$url \n modo $modo, context $context";
											$html_contenido .= "<div class='css_section_group_image_edit div_image_link link' title=\"$title\" onclick=\"goto_url('$url')\"></div>";
											break;
									}									
							}							

								
							#
							# BUTTON DELETE / ADD RELATION
							# IF ISSET CALLER_ID HIDE BTN DELETE AND SHOW BTN 'ADD RELATION'					
							switch ($context) {

								case 'list_into_tool_relation':
									# ADD RELATION BUTTON
									$title = "Add relation [$rel_locator]";
									$html_contenido .= " <div class=\"icon_bs tool_relation_icon link\"
									data-id_matrix=\"{$id}\" data-caller_tipo=\"{$section_tipo}\" data-rel_locator=\"$rel_locator\" data-tipo=\"$tipo\" 
									onclick=\"parent.tool_relation.add_relation(this)\"
									title=\"$title\";
									>";
									#$html_contenido .= "Add relation ";
									$html_contenido .= "</div>";
									break;

								case 'list_into_tool_portal':
									# ADD RESOURCE BUTTON
									$title = "Add resource [$rel_locator]";							
									$html_contenido .= " <div class=\"icon_bs tool_add_portal_icon link\"
									data-id_matrix=\"{$id}\" data-caller_tipo=\"{$section_tipo}\" data-rel_locator=\"$rel_locator\" data-tipo=\"$tipo\" 
									onclick=\"tool_portal.add_resource(this)\"
									title=\"$title\";
									>";
									#$html_contenido .= "Add resource ";
									$html_contenido .= "</div>";
									break;

								default:
									$html_contenido .= $button_delete_html;
							}

							#$html_contenido .= "context:$context ";



							# DEBUG INFO
							if($permissions==3)		
							$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$id}</span>";	
								
							

						$html_contenido .= "\n </td>";

						
						# TD DATOS
						if(isset($ar_component_obj) && is_array($ar_component_obj)) foreach($ar_component_obj as $component_obj) {

							# aditional td css selectors
							$td_css_selector = 'td_'.get_class($component_obj);							
							
							$html_contenido .= "\n <td class=\"section_list_td_border section_list_td_row $td_css_selector\">";
							$html_contenido .=  $component_obj->get_html(); 
							$html_contenido .= "\n </td>";													
						}


					}
	}
	$html_contenido .= "\n</tr>";
	
	# PRINT HTML
	print $html_contenido;
	

?>