<?php
	
	# VISUALIZADOR HTML	

	# ELEMENTOS	
	if(!isset ($ar_css['css_span_dato'])) 				$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_span_debugger'])) 			$ar_css['css_span_debugger']='';
	
	print "\n\n<!-- ROWS [$id] -->";
		
	# CONTENIDO (INPUT)

	$html_contenido   = "";	
	$html_contenido  .= "\n<tr>";
	
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." </span>";
					break;
						
		case ($permissions>=1)	:
					
					if( !is_array($ar_rows) || count($ar_rows)==0 ) {
						
						$html_contenido .= "\n <td colspan=\"2\">";
						#$html_contenido .= "No records found.. ";
						$html_contenido .= "\n </td>";
						
					}else{
					
						# TD ID
						$html_contenido .= "\n <td class=\"row_id\">";					
						
							
							# ID TEXT
							$html_contenido .= "\n  $section_dato ";

							# BUTTON EDIT							
							#$html_contenido .= "<div class='css_section_group_image_edit div_image_link' href='?m=edit&t={$current_section}&id=$id' title=\"matrix $id\" ></div>";
							$url 	= htmlspecialchars("?m=edit&t={$section_tipo}&id=$id");
							$title 	= "matrix $id";
							if(SHOW_DEBUG) $title .= "\n url:$url"; 
							$html_contenido .= "<div class='css_section_group_image_edit div_image_link open_section_link_from_iframe' 							
							onclick=\"goto_url('{$url}')\" 
							data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\"
							title=\"$title\" ></div>";
							#$html_contenido .= "\n <a href=\"javascript:void(0)\" class=\"open_section_link_from_iframe\" data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" > edit $id</a>";
							
							
							# BUTTON REMOVE RELATION
							$html_contenido .= "<div class=\"link_relation\" title=\"$rel_locator - caller_tipo: $caller_tipo\"
							data-id_matrix=\"{$id}\" data-caller_id=\"{$caller_id}\" data-caller_tipo=\"{$caller_tipo}\" data-tipo=\"{$section_tipo}\" data-rel_locator=\"{$rel_locator}\"
							onclick='component_relation.remove_relation_from_section(this)'> ". label::get_label('remove') ."</div>";

							#dump($this->section_obj,'$this->section_obj');


						$html_contenido .= "\n </td>";



						
						# TD INFO
						$html_contenido .= "\n <td class=\"td_relation_info\">";	

							if(isset($ar_component_obj_html) && is_array($ar_component_obj_html)) {
								$n = count($ar_component_obj_html);
								$i = 1;
								foreach($ar_component_obj_html as $id_section => $component_obj_html) {							
									
									$html_contenido .= $component_obj_html;
									if ($i<$n) {
										#$html_contenido .= "\n <hr class=\"hr_row_relation\">";
										$html_contenido .= ", ";
									}
									$i++;
								}											
							}

						$html_contenido .= "\n </td>";
						

						
						# TD DATOS
						$html_contenido .= "\n <td class=\"td_relation_fragment\">";
							#if($fragment_html==NULL) $fragment_html = "<em>Full</em>";
							$html_contenido .= "\n $fragment_html";

						$html_contenido .= "\n </td>";
						

					}
	}
	$html_contenido .= "\n</tr>";
	
	
	# PRINT HTML
	print $html_contenido;
	

?>