<?php
	

	# VISUALIZADOR HTML

	$html = "<!-- $tool_name PAGE [tipo:$tipo] -->";	
	#$html .= "<div class=\"wrap_tool wrap_$tool_name_page\" >";	
	
	#
	# HEADER TOOL	
	$header_html ='';
	$header_html .= "<div class=\"header_tool text_unselectable\">";


		#
		# TOOL NAME
		$header_html .= "<div class=\"header_info header_tool_name tool_structuration_icon\">";
		$header_html .= label::get_label($tool_name) ;
		$header_html .= "</div>";//end header_tool_name


		#
		# HEADER_TOOL_TABS
		$header_html .= "<ul class=\"header_tool_tabs\">";
		$header_html .= "<li class=\"tab_active\" onclick=\"tool_common.change_view_selector(this,'thesaurus','tesaurus_frame')\"> Thesaurus</li>";
		$header_html .= "<li class=\"\" onclick=\"tool_common.change_view_selector(this,'media', 'tesaurus_frame')\"> Video</li>";
		$header_html .= "</ul>";
		$header_html .= "<script>";
		$header_html .= "tool_common.media_frame_url='$av_player_url';";
		$header_html .= "</script>";


		#
		# INFO
		$header_html .= "<div class=\"header_info\">";
		$header_html .= $section_label;
		$header_html .= ' | ' . $section_id . ' | ';
		if (is_object($inverse_code)) {
			$header_html .= $inverse_code->value;
		}
		$header_html .= "</div>";//end header_info


		#
		# TOP_ID SELECTOR
		if (isset($inverse_locators) && is_array($inverse_locators)) {
			
			$header_html .= "<div class=\"top_id_selector\">";

			$header_html .= "<label>".label::get_label('enfoque')."</label> : ";
			$header_html .= "<select id=\"top_id_selector\" class=\"custom_dropdown\" onchange=\"$tool_name.update_top_id(this)\" >";
			#$header_html .= " <option></option>";
			$ar_inverse = $this->get_ar_inverse($inverse_locators);
			foreach ($ar_inverse as $current_id => $current_name) {				
				$selected = $current_id==TOP_ID ? 'selected' : '';
				$header_html .= " <option value=\"$current_id\" {$selected}>$current_name</option>";
			}
			$header_html .= "</select>";

			$header_html .= "<script>";
			$header_html .= "{$tool_name}.update_top_id(document.getElementById('top_id_selector'));";			
			$header_html .= "</script>";

			$header_html .= "</div>";//end top_id_selector			
		}


		$header_html .= "<div class=\"header_buttons\">";
			#
			# BUTTON_TOOL_TR_PRINT_HTML
			if (isset($button_tool_tr_print_html)) {
				$header_html .= $button_tool_tr_print_html;
			}
			#
			# BUTTON_TOOL_TIME_MACHINE_HTML
			if (isset($button_tool_time_machine_html)) {
				$header_html .= $button_tool_time_machine_html;
			}
		$header_html .= "</div>";//end header_buttons	


		#
		# COMPONENT STATE
		$header_html .= $component_state_html;


	$header_html .= "</div>";//end header_tool
	$html .= $header_html;
	


	#
	# CONTENT 
	$html .= "<div id=\"indexation_container\" class=\"container\" >"; //text_shadow_inset


		#
		# LEFT SIDE
		$html .= "<div id=\"left_side\" class=\"split split-horizontal left_side\">";	
		
			#
			# THESAURUS (IFRAME)
			$html .= "<div class=\"indexation_page_tesauro\">";

			
			$html .= "<iframe id=\"videoFrame\" name=\"videoFrame\" class=\"media_frame\" src=\"\"></iframe>"; // {$av_player_url}
			$html .= "<iframe id=\"tesaurus_frame\" name=\"tesaurus_frame\" class=\"tesaurus_frame\" src=\"\" data-url=\"{$tesaurus_url}\"></iframe>";	
			$html .= "<div id=\"tesaurus_frame_loading\" class=\"\"> <span class=\"css_spinner\"></span></div>";
					
			$html .= "</div>";


		$html .= "</div>";#end left_side


		#
		# RIGHT SIDE
		$html .= "<div id=\"right_side\" class=\"split split-horizontal right_side\">";

			#
			# TEXT (TEXT DIV)
			$html .= "<div id=\"text_preview_wrapper\">";
			$html .= "<span id=\"current_lang\">$lang</span>";
			$html .= $component_text_area_html;
			$html .= "</div>";

			# Buttons
			$html .= "<div id=\"text_buttons\">";	
			# Create chapter
			$label = label::get_label('crear_capitulo');	
			#$html .= "<input type=\"button\" class=\"btn btn-default\" value=\"".label::get_label('crear_capitulo')."\" onclick=\"tool_structuration.create_area(this,event,'$component_text_area_wrapper')\" /> ";
			$html .= "<button type=\"submit\" class=\"btn btn-default hide_on_not_source\" onclick=\"tool_structuration.create_area(this,event,'$component_text_area_wrapper')\">".$label."</button>";
			#$html .= "<input type=\"button\" class=\"btn btn-default\" value=\"Remove area\" onclick=\"tool_structuration.remove_area(this)\" /> ";
			$label = label::get_label('mostrar_ocultar_etiquetas');
			#$html .= "<input type=\"button\" class=\"btn btn-default button_border_active\" value=\"".$label."\" onclick=\"tool_structuration.toggle_tags(this)\" /> <span class=\"glyphicon glyphicon-search\"></span>";
			$html .= "<button type=\"submit\" class=\"btn btn-default button_border_active hide_on_not_source\" onclick=\"tool_structuration.toggle_tags(this)\">".$label." <span class=\"glyphicon glyphicon-lock\"></span></button>";
			if(SHOW_DEBUG===true) {
			#$html .= "<button type=\"submit\" class=\"btn btn-default button_border_active\" onclick=\"tool_structuration.place_broken_tag_in_approximate_position(this)\">place_broken_tag_in_approximate_position</button>";
			}
			$html .= "<div id=\"tool_info_log\">  </div>";
			$label = label::get_label('actualizar_vista');
			#$html .= "<input type=\"button\" class=\"btn btn-default button_save_text\" value=\"".label::get_label('actualizar_vista')."\" onclick=\"tool_structuration.update_view(this)\" /> ";
			$html .= "<button type=\"submit\" class=\"btn btn-default button_save_text\" onclick=\"tool_structuration.update_view(this)\">".$label."</button>";		
			$html .= "</div>";

			/*
			#
			# TEXT (TEXT AREA)
			$html   .= "<div class=\"indexation_page_text\">";
			$html 	.= $component_text_area_html;
			$html   .= "</div>";			
			*/

			#
			# TERM LIST
			$html   .= "<div id=\"indexation_page_list\" class=\"css_section_tab_content indexation_page_list\">";
			$html 	.= label::get_label('seleccione_una_etiqueta_para_indexar') . ' <br>';
			$html 	.= label::get_label('para_crear_un_fragmento');
			$html   .= "</div>";			
			
			
		$html .= "</div>";#end right_side
		
	
	$html .= "</div><!-- /container -->";
	#$html .= "</div><!-- /wrap_tool -->"; //wrap_tool

	
	# INSPECTOR LOG TOOL_LANG ()
	$html 	.= "<div id=\"inspector_log\" class=\"tool_inspector_log\"> </div>";
	

	# Init tool
	$html .= "<script>";
	$html .= "tool_structuration.component_tipo='$component_tipo';";
	$html .= "tool_structuration.section_tipo='$section_tipo';";
	$html .= "tool_structuration.section_id='$section_id';";
	$html .= "tool_structuration.lang='$lang';";
	$html .= "tool_structuration.original_lang='$original_lang';";
	$html .= "tool_structuration.original_lang_label='$original_lang_label';";
	/**/
	#$html .= "get_instance({name:'$tool_name',id_wrapper:'$component_text_area_wrapper',init:{textarea_lang:'$original_lang'}});";
	$html .= "$tool_name.init({textarea_lang:'$original_lang',uid:'$component_text_area_wrapper'});";
	$html .= "</script>";


	echo $html;


?>