<?php
	

	# VISUALIZADOR HTML

	$html = "<!-- $tool_name PAGE [tipo:$tipo] -->";	
	#$html .= "<div class=\"wrap_tool wrap_$tool_name_page\" >";	
	
	#
	# HEADER TOOL	
	$header_html ='';
	$header_html .= "<div class=\"header_tool\">";

		#
		# INFO
		$header_html .= "<div class=\"header_info\">";
		$header_html .= "ID $section_id";
		$header_html .= "</div>";

		#
		# TOP_ID SELECTOR		
		if (isset($inverse_locators) && is_array($inverse_locators)) {
			$top_id_selector  = '';
			$top_id_selector .= "<div class=\"top_id_selector\">";
			$top_id_selector .= "<label>".label::get_label('enfoque')."</label>";
			$top_id_selector .= "<select id=\"top_id_selector\" onchange=\"$tool_name.update_top_id(this)\" >";
			#$top_id_selector .= " <option></option>";
			$ar_inverse = $this->get_ar_inverse($inverse_locators);
			foreach ($ar_inverse as $current_id => $current_name) {
				$top_id_selector .= " <option value=\"$current_id\">$current_name</option>";
			}
			$top_id_selector .= "</select>";
			$top_id_selector .= "</div>";
			$top_id_selector .= "<script>$tool_name.update_top_id(document.getElementById('top_id_selector'));</script>";
			$header_html .= $top_id_selector;
		}		

		#
		# COMPONENT STATE
		$header_html .= $component_state_html;

	$header_html .= "</div>";//end header_tool
	$html .= $header_html;
	/**/

	#
	# CONTENT 
	$html .= "<div id=\"indexation_container\" class=\"container\" >"; //text_shadow_inset


		#
		# LEFT SIDE
		$html .= "<div id=\"left_side\" class=\"split split-horizontal left_side\">";	
		
			#
			# THESAURUS (IFRAME)
			$html .= "<div class=\"indexation_page_tesauro\">";
			$html .= " <iframe id=\"tesauro_frame\" name=\"tesauro_frame\" class=\"tesauro_frame\" src=\"{$tesauro_url}\" ></iframe>";
			$html .= "</div>";


		$html .= "</div>";#end left_side


		#
		# RIGHT SIDE
		$html .= "<div id=\"right_side\" class=\"split split-horizontal right_side\">";

			#
			# TEXT (TEXT DIV)
			$html .= "<div id=\"text_preview_wrapper\">";
			$html .= "<span id=\"current_lang\">$lang</span>";
			$html .= $component_text_area_html;
			$html .= "</div>";

			# Buttons
			$html .= "<div id=\"text_buttons\">";			
			$html .= "<input type=\"button\" class=\"btn btn-default\" value=\"Create area\" onclick=\"tool_structuration.create_area(this)\" /> ";
			#$html .= "<input type=\"button\" class=\"btn btn-default\" value=\"Remove area\" onclick=\"tool_structuration.remove_area(this)\" /> ";
			$html .= "<input type=\"button\" class=\"btn btn-default\" value=\"Toggle tags\" onclick=\"tool_structuration.toggle_tags(this)\" /> ";
			$html .= "<div id=\"tool_info_log\">  </div>";
			$html .= "<input type=\"button\" class=\"btn btn-default button_save_text\" value=\"Update view\" onclick=\"tool_structuration.update_view(this)\" /> ";			
			$html .= "</div>";

			/*
			#
			# TEXT (TEXT AREA)
			$html   .= "<div class=\"indexation_page_text\">";
			$html 	.= $component_text_area_html;
			$html   .= "</div>";			
			*/

			#
			# TERM LIST
			$html   .= "<div id=\"indexation_page_list\" class=\"css_section_tab_content indexation_page_list\">";
			$html 	.= label::get_label('seleccione_una_etiqueta_para_indexar') . ' <br>';
			$html 	.= label::get_label('para_crear_un_fragmento');
			$html   .= "</div>";
			
			$html .= "<div id=\"inspector_log\" class=\"tool_transcription_inspector_log\"> </div>";
			
		$html .= "</div>";#end right_side
		
	
	$html .= "</div><!-- /container -->";
	#$html .= "</div><!-- /wrap_tool -->"; //wrap_tool

	
	# Inspector log tool
	$html .= "<div id=\"inspector_log\" class=\"tool_transcription_inspector_log\"> </div>";
	

	# Init tool
	$html .= "<script>";
	$html .= "tool_structuration.component_tipo='$component_tipo';";
	$html .= "tool_structuration.section_tipo='$section_tipo';";
	$html .= "tool_structuration.section_id='$section_id';";
	$html .= "tool_structuration.lang='$lang';";
	$html .= "$tool_name.init();";
	$html .= "</script>";
	

	echo $html;


?>