<?php declare(strict_types=1);
/**
* CLASS DD_CACHE
* File-based cache manager for Dédalo, optimized for OPcache bytecode reuse.
*
* Provides a uniform API for storing and retrieving arbitrary PHP data in
* per-user cache files on disk. The primary consumers are:
* - component_security_access — caches the permission tree per user per language
* - login — deletes all user-scoped files on logout / quit
* - ontology, label, and tool helpers — cache expensive structure lookups
*
* Key design decisions:
* - Cache files are PHP scripts generated by OpcacheObjectManager (var_export-style),
*   so they are eligible for OPcache bytecode caching and avoid the overhead of
*   JSON decode or unserialize on every hit.
* - File names are scoped to entity + user ID via get_cache_file_prefix(), providing
*   automatic per-user isolation. A custom prefix bypasses this isolation and those
*   files are NOT deleted automatically on logout — the caller is responsible.
* - Expensive background calculations (e.g. security tree) are offloaded to a
*   separate PHP process via process_and_cache_to_file(); the result is written to
*   the same file the main request will later read via cache_from_file().
* - All public entry points validate file_name against directory traversal
*   ('../', '/') before constructing any file path.
*
* Storage layout:
*   DEDALO_CACHE_MANAGER['files_path']/{prefix}{file_name}
*   Default prefix format: {DEDALO_ENTITY}_{user_id}_
*   Example: /tmp/monedaiberica_42_cache_tree_lg-eng.php
*
* @see OpcacheObjectManager Handles atomic writes and OPcache invalidation
* @see DEDALO_CACHE_MANAGER Configuration constant — must contain 'files_path' key
* @see component_security_access Primary consumer for permission-tree caching
* @see login::logout() Triggers automatic cache cleanup on user logout
*
* @package Dédalo
* @subpackage Core
*/
class dd_cache {



	/**
	* GET_CACHE_FILE_PREFIX
	* Builds the user-scoped prefix prepended to every cache file name.
	*
	* Combines the installation entity constant and the currently logged-in user ID
	* to produce a prefix that is unique per user per installation. This ensures
	* that cache files created by one user are never read by another.
	*
	* When no user is logged in (logged_user_id() returns null) the literal string
	* 'anonymous' is used in place of the user ID. Anonymous-prefixed files are
	* not deleted automatically on logout.
	*
	* Returned format: '{DEDALO_ENTITY}_{user_id}_'
	* Example: 'monedaiberica_42_'
	*
	* @return string Cache file prefix in format '{entity}_{user_id}_'
	*/
	public static function get_cache_file_prefix() : string {
		$user_id = logged_user_id();
		if ($user_id === null) {
			$user_id = 'anonymous';
		}
		return DEDALO_ENTITY .'_'. $user_id . '_';
	}//end get_cache_file_prefix



	/**
	* GET_CACHE_FILES_PATH
	* Returns the validated, writable cache directory path from configuration.
	*
	* Reads DEDALO_CACHE_MANAGER['files_path'] and runs four guards before
	* returning the path:
	* 1. The DEDALO_CACHE_MANAGER constant must be defined.
	* 2. The 'files_path' key must be present in the constant array.
	* 3. The path must resolve to an actual directory on disk.
	* 4. The directory must be writable by the web-server process.
	*
	* All guard failures are written to the error log via debug_log() before
	* returning false, so callers can simply test the return value.
	*
	* Typical configuration in config.php:
	*   define('DEDALO_CACHE_MANAGER', ['manager' => 'files', 'files_path' => '/tmp']);
	*
	* @return string|false Validated directory path on success, false on any guard failure
	*/
	private static function get_cache_files_path() : string|false {
		if (!defined('DEDALO_CACHE_MANAGER') || !isset(DEDALO_CACHE_MANAGER['files_path'])) {
			debug_log(__METHOD__
				." Error: Check your DEDALO_CACHE_MANAGER config to fix it "
				, logger::ERROR
			);
			return false;
		}
		$base_path = defined('DEDALO_CACHE_PATH')
			? DEDALO_CACHE_PATH
			: DEDALO_CACHE_MANAGER['files_path'];

		if (!is_dir($base_path) || !is_writable($base_path)) {
			debug_log(__METHOD__." Error: base_path is not writable: $base_path", logger::ERROR);
			return false;
		}

		return $base_path;
	}//end get_cache_files_path



	/**
	* PROCESS_AND_CACHE_TO_FILE
	* Spawns a PHP sub-process to run a calculation script and write the result to a cache file.
	*
	* Used for operations that are too slow to run inline (e.g. building the full security
	* access tree for a user). The designated $options->process_file script is expected to
	* compute the result and write it directly to the output file via stdout redirection or
	* the dd_cache API; the shell command wires the redirection automatically.
	*
	* The spawned process receives a JSON-encoded object as its first argument. That object
	* merges the caller's $options->data properties with a 'server' key that carries the
	* minimal $_SERVER values the sub-process needs to bootstrap Dédalo (HTTP_HOST,
	* REQUEST_URI, SERVER_NAME).
	*
	* Execution mode is controlled by $options->wait:
	* - false (default): the shell command is suffixed with '&' so it runs in the
	*   background and the main request continues immediately. The caller must handle the
	*   case where the cache file does not yet exist on the first hit.
	* - true: exec() blocks until the process exits. Use when the caller needs the result
	*   before it can proceed.
	*
	* Security guards applied before any shell execution:
	* - $options->process_file must exist on disk.
	* - Its real path must start with realpath(DEDALO_CORE_PATH) or realpath(DEDALO_LIB_PATH),
	*   preventing execution of arbitrary files outside the Dédalo installation.
	* - $options->file_name must not contain '..' or '/' to prevent directory traversal.
	* - PHP_BIN_PATH must be defined; the value is passed through escapeshellcmd().
	* - The JSON argument is passed through escapeshellarg().
	*
	* $options properties:
	*   string  process_file  Required. Absolute path to the PHP script to execute.
	*                         Must be within DEDALO_CORE_PATH or DEDALO_LIB_PATH.
	*   object  data          Required. Properties merged into the JSON argument passed
	*                         to the sub-process (session_id, user_id, lang, etc.).
	*   string  file_name     Required. File name (no path, no directory separators)
	*                         for the output cache file. E.g. 'cache_tree_lg-eng.php'.
	*   bool    wait          Optional. Block until the process exits. Default: false.
	*   string  prefix        Optional. Override the default user-scoped prefix.
	*                         (!) Custom-prefix files are not deleted on logout.
	*
	* @param object $options Configuration object; see property list above
	* @return string|bool Last output line from exec() on success, false on any guard failure
	*
	* @see cache_to_file() For direct in-process caching without a sub-process
	* @see cache_from_file() For reading back the file written by the sub-process
	*/
	public static function process_and_cache_to_file(object $options) : string|bool {

		// input validation
			if (!isset($options->process_file) || !is_string($options->process_file)) {
				debug_log(__METHOD__." Error: process_file is required and must be a string", logger::ERROR);
				return false;
			}
			if (!isset($options->data) || !is_object($options->data)) {
				debug_log(__METHOD__." Error: data is required and must be an object", logger::ERROR);
				return false;
			}
			if (!isset($options->file_name) || !is_string($options->file_name)) {
				debug_log(__METHOD__." Error: file_name is required and must be a string", logger::ERROR);
				return false;
			}

		// options
			// string process_file. File to manage the data process
			// Sample: dirname(__FILE__, 2) . '/component_security_access/calculate_tree.php'
			$process_file	= $options->process_file;
			// object data
			$data			= $options->data;
			// string file_name. Sample: 1.cache_tree.php
			$file_name		= $options->file_name;
			// wait until process ends
			$wait			= $options->wait ?? false;
			// prefix
			$prefix			= $options->prefix ?? dd_cache::get_cache_file_prefix();

		// validate file paths
			if (!file_exists($process_file)) {
				debug_log(__METHOD__." Error: process_file does not exist: $process_file", logger::ERROR);
				return false;
			}
			// Security: Ensure process_file is within allowed paths
			if (defined('DEDALO_CORE_PATH') && strpos(realpath($process_file), realpath(DEDALO_CORE_PATH)) !== 0) {
				if (!defined('DEDALO_LIB_PATH') || strpos(realpath($process_file), realpath(DEDALO_LIB_PATH)) !== 0) {
					debug_log(__METHOD__." Error: process_file is not within allowed paths: $process_file", logger::ERROR);
					return false;
				}
			}
			if (strpos($file_name, '..') !== false || strpos($file_name, '/') !== false) {
				debug_log(__METHOD__." Error: file_name contains invalid characters: $file_name", logger::ERROR);
				return false;
			}

		// sh_data
			$sh_data = [
				'server' => [
					'HTTP_HOST'		=> $_SERVER['HTTP_HOST'] ?? 'localhost',
					'REQUEST_URI'	=> $_SERVER['REQUEST_URI'] ?? '',
					'SERVER_NAME'	=> $_SERVER['SERVER_NAME'] ?? 'development'
				]
			];
			foreach ($data as $key => $value) {
				$sh_data[$key] = $value;
			}

		// server_vars
			$server_vars = json_encode($sh_data, JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);

		// base_path. Used to save the files. Usually '/tmp'
			$base_path = self::get_cache_files_path();
			if ($base_path === false) {
				return false;
			}

		// output file path
			$output_file = $base_path .'/'. $prefix . $file_name;

		// output redirection
			$output = '> '.escapeshellarg($output_file).' ';

		// wait
			if ($wait!==true) {
				$output	.= '&';
			}

		// command with proper escaping
			if (!defined('PHP_BIN_PATH')) {
				debug_log(__METHOD__." Error: PHP_BIN_PATH constant is not defined", logger::ERROR);
				return false;
			}
			// Resolve the php binary robustly (configured → platform base → PATH) so the cache
			// worker spawns correctly on a non-standard layout (e.g. a Homebrew Mac) without the
			// administrator hand-editing PHP_BIN_PATH.
			$php_bin = class_exists('system') ? system::get_php_bin() : PHP_BIN_PATH;
			$command = escapeshellcmd($php_bin) .' '.escapeshellarg($process_file).' '.escapeshellarg($server_vars).' '.$output;

		// debug
			debug_log(__METHOD__
				." ------> COMMAND PROCESS_AND_CACHE_TO_FILE ------------------------------------------------:" . PHP_EOL
				.'file_name: ' .$file_name . PHP_EOL
				.'wait: ' . to_string($wait) . PHP_EOL
				.'command: ' . PHP_EOL
				. $command   . PHP_EOL
				." -------------------------------------------------------------------------------------------"
				, logger::DEBUG
			);

		// exec command
			$status = exec($command);


		return $status;
	}//end process_and_cache_to_file



	/**
	* CACHE_TO_FILE
	* Writes arbitrary PHP data to a cache file using OPcache-optimized serialization.
	*
	* Delegates to OpcacheObjectManager::save(), which serializes $options->data via
	* var_export-style PHP code and writes it atomically (temp file + rename()) to
	* prevent partial reads in concurrent scenarios. If OPcache is active the written
	* file is immediately eligible for bytecode caching, making subsequent cache_from_file()
	* calls significantly faster than JSON decode or unserialize.
	*
	* The cache file is placed at:
	*   {cache_dir}/{prefix}{file_name}
	* where {prefix} defaults to the user-scoped value from get_cache_file_prefix().
	*
	* $options properties:
	*   mixed   data       Required. Any serializable PHP value (array, object, scalar, null).
	*                      Stored as a PHP return statement inside the cache file.
	*   string  file_name  Required. File name without path or directory separators.
	*                      Must not contain '..' or '/'. Extension is typically '.php'.
	*                      Example: 'cache_tree_lg-eng.php'.
	*   string  prefix     Optional. Override the default user-scoped prefix.
	*                      (!) Custom-prefix files are not deleted on logout — caller must manage cleanup.
	*
	* @param object $options Configuration object; see property list above
	* @return bool true on successful write, false on validation failure or write error
	*
	* @see cache_from_file() For reading data written by this method
	* @see cache_file_exists() For checking cache existence before retrieval
	* @see OpcacheObjectManager::save() Underlying atomic write + OPcache invalidation
	*/
	public static function cache_to_file(object $options) : bool {

		// input validation
			if (!isset($options->data)) {
				debug_log(__METHOD__." Error: data is required", logger::ERROR);
				return false;
			}
			if (!isset($options->file_name) || !is_string($options->file_name)) {
				debug_log(__METHOD__." Error: file_name is required and must be a string", logger::ERROR);
				return false;
			}

		// options
			// data
			$data = $options->data;
			// file_name. E.g. '1.cache_tree.php'
			$file_name = $options->file_name;
			// prefix
			$prefix = $options->prefix ?? dd_cache::get_cache_file_prefix();

		// validate file_name
			if (strpos($file_name, '..') !== false || strpos($file_name, '/') !== false) {
				debug_log(__METHOD__." Error: file_name contains invalid characters: $file_name", logger::ERROR);
				return false;
			}

		// base_path. Used to save the files. Usually '/tmp'
			$base_path = self::get_cache_files_path();
			if ($base_path === false) {
				return false;
			}

		// file_path
			$file_path = $base_path . '/' . $prefix . $file_name;

		// Write data to file. Using var_export enables the Opcode cache for this file.
			try {
				$result = OpcacheObjectManager::save($file_path, $data);
			} catch (Exception $e) {
				debug_log(__METHOD__
					." Error on write file: " . $e->getMessage()
					. " file_path: " . $file_path
					, logger::ERROR
				);
				$result = false;
			}

		// debug
			debug_log(__METHOD__.
				" ------> CACHE_TO_FILE: $file_name ------------------------------------------------------:" .PHP_EOL
				.' result: ' . to_string($result) .PHP_EOL
				." ----------------------------------------------------------------------------------------"
				, logger::DEBUG
			);


		return $result;
	}//end cache_to_file



	/**
	* CACHE_FROM_FILE
	* Reads and returns data previously written by cache_to_file() or process_and_cache_to_file().
	*
	* Delegates to OpcacheObjectManager::load(), which uses include to execute the cache
	* file (a 'return ...' PHP script). This makes the data eligible for OPcache bytecode
	* caching on subsequent requests, providing faster retrieval than JSON decode or
	* unserialize.
	*
	* A null return value has two distinct meanings:
	* - The cache file does not yet exist (cache miss).
	* - The cache file exists but is empty or corrupted (OpcacheObjectManager::load returns null).
	* Callers should treat both cases as a cache miss and regenerate the data.
	*
	* $options properties:
	*   string  file_name  Required. Name of the cache file to read. Must not contain
	*                      '..' or '/'. Example: 'cache_tree_lg-eng.php'.
	*   string  prefix     Optional. Must match the prefix used during cache_to_file().
	*                      Defaults to the user-scoped value from get_cache_file_prefix().
	*                      (!) Custom-prefix files are not deleted on logout — caller must manage cleanup.
	*
	* @param object $options Configuration object; see property list above
	* @return mixed Cached data value on success, null on cache miss or any error
	*
	* @see cache_to_file() For storing data to cache
	* @see cache_file_exists() For a lightweight existence check before loading
	* @see delete_cache_files() For cache invalidation and cleanup
	* @see OpcacheObjectManager::load() Underlying file include implementation
	*/
	public static function cache_from_file(object $options) : mixed {

		// input validation
			if (!isset($options->file_name) || !is_string($options->file_name)) {
				debug_log(__METHOD__." Error: file_name is required and must be a string", logger::ERROR);
				return null;
			}

		// options
			// string file_name. Sample: 1.cache_tree.php
			$file_name = $options->file_name;
			// prefix. (!) If you set custom prefix, the file created will not be deleted automatically on logout/quit
			$prefix = $options->prefix ?? dd_cache::get_cache_file_prefix();

		// validate file_name
			if (strpos($file_name, '..') !== false || strpos($file_name, '/') !== false) {
				debug_log(__METHOD__." Error: file_name contains invalid characters: $file_name", logger::ERROR);
				return null;
			}

		// base_path. Used to save the files. Usually '/tmp'
			$base_path = self::get_cache_files_path();
			if ($base_path === false) {
				return null;
			}

		// file_path
			$file_path = $base_path . '/' . $prefix . $file_name;

		// Include file. Note that PHP Opcode caches the file.
			try {
				$contents = OpcacheObjectManager::load($file_path);
				if ($contents === null) {
					debug_log(__METHOD__." Warning: Cache file returned null: $file_path", logger::WARNING);
				}
			} catch (Exception $e) {
				debug_log(__METHOD__." Error loading cache file: " . $e->getMessage(), logger::ERROR);
				$contents = null;
			}


		return $contents;
	}//end cache_from_file



	/**
	* CACHE_FILE_EXISTS
	* Returns true when the requested cache file exists on disk.
	*
	* A lightweight stat-only check used to distinguish a cache miss from stale
	* data without loading the file contents. Typical pattern:
	*   if (!dd_cache::cache_file_exists($opts)) { /* regenerate *\/ }
	*   $data = dd_cache::cache_from_file($opts);
	*
	* $options properties:
	*   string  file_name  Required. Cache file name without path or directory separators.
	*                      Must not contain '..' or '/'.
	*   string  prefix     Optional. Must match the prefix used during cache_to_file().
	*                      Defaults to the user-scoped value from get_cache_file_prefix().
	*
	* @param object $options Configuration object; see property list above
	* @return bool true if the cache file exists on disk, false on any guard failure or absence
	*
	* @see cache_from_file() For reading cached data after an existence check
	* @see cache_to_file() For writing a new cache entry on miss
	*/
	public static function cache_file_exists(object $options) : bool {

		// input validation
			if (!isset($options->file_name) || !is_string($options->file_name)) {
				debug_log(__METHOD__." Error: file_name is required and must be a string", logger::ERROR);
				return false;
			}

		// options
			// string file_name. Sample: 1.cache_tree.php
			$file_name	= $options->file_name;
			// prefix. (!) If you set custom prefix, the file created will not be deleted automatically on logout/quit
			$prefix		= $options->prefix ?? dd_cache::get_cache_file_prefix();

		// validate file_name
			if (strpos($file_name, '..') !== false || strpos($file_name, '/') !== false) {
				debug_log(__METHOD__." Error: file_name contains invalid characters: $file_name", logger::ERROR);
				return false;
			}

		// base_path. Used to save the files. Usually '/tmp'
			$base_path = self::get_cache_files_path();
			if ($base_path === false) {
				return false;
			}

		// file_path
			$file_path	= $base_path . '/' . $prefix . $file_name;

		// result
			$result = file_exists($file_path);


		return $result;
	}//end cache_file_exists



	/**
	* DELETE_CACHE_FILES
	* Removes cache files from the cache directory, either by explicit list or by prefix glob.
	*
	* Two operating modes:
	* 1. Specific files — pass a non-empty $cache_files array with bare file names (no path,
	*    no prefix). The prefix is prepended to each name before building the full path.
	*    Use $prefix=null to apply the default user-scoped prefix.
	* 2. Pattern sweep — pass $cache_files=null to glob for all files matching the prefix
	*    pattern ('{base_path}/{prefix}*'). Glob failures (returns false) are treated as an
	*    empty match set, not an error.
	*
	* Called automatically by login::logout() with no arguments to clean up all user-scoped
	* files when a session ends. Files created with a custom prefix are NOT swept by the
	* default logout call and must be deleted explicitly by the caller.
	*
	* (!) The method returns true even when individual unlink() calls fail; partial deletion
	* is logged at ERROR level but does not abort the loop.
	*
	* @param array|null  $cache_files = null  Bare file names to delete; null to glob all prefix matches
	* @param string|null $prefix      = null  File prefix override; null uses get_cache_file_prefix()
	* @return bool true on completion, false only when the cache directory is inaccessible
	*
	* @see login::logout() Primary caller for automatic per-user cleanup
	* @see get_cache_file_prefix() Builds the default user-scoped prefix
	*/
	public static function delete_cache_files( ?array $cache_files=null, ?string $prefix=null ) : bool {

		// check base_path
			$base_path = self::get_cache_files_path();
			if ($base_path === false) {
				return false;
			}

		// files
			$cache_files_parsed = !empty($cache_files)
				? (function() use($cache_files, $prefix) {
					$cache_files_parsed = [];
					foreach ($cache_files as $file_name) {
						$full_file_name = $prefix===null
							? dd_cache::get_cache_file_prefix() . $file_name
							: $prefix . $file_name;
						$cache_files_parsed[] = $full_file_name;
					}
					return $cache_files_parsed;
				  })()
				: (function() use($base_path, $prefix){
					$use_prefix		= $prefix ?? dd_cache::get_cache_file_prefix();
					$file_pattern	= $base_path .'/'. $use_prefix .'*';
					$found_files	= glob($file_pattern);
					// Handle glob() failure
					return $found_files === false ? [] : $found_files;
				  })();

		// delete
			if (!empty($cache_files_parsed)) {
				foreach ($cache_files_parsed as $file_name) {
					$file_path = strpos($file_name, $base_path)===0
						? $file_name
						: $base_path .'/'. $file_name;
					if (file_exists($file_path)) {
						$deleted = unlink($file_path);
						if ($deleted===true) {
							debug_log(__METHOD__." Deleted file $file_path ", logger::DEBUG);
						}else{
							debug_log(__METHOD__
								. " Error deleting file " .PHP_EOL
								. ' file_path: ' . $file_path
								, logger::ERROR
							);
						}
					}else{
						debug_log(__METHOD__
							. " Warning. Ignored file not found for deletion " .PHP_EOL
							. ' file_path: ' . $file_path
							, logger::WARNING
						);
					}
				}
			}

		return true;
	}//end delete_cache_files



}//end class dd_cache
