<?php

	# VISUALIZADOR HTML
	
	print "<div class=\"wrap_component css_wrap_relation_index tooltip_active\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato='".json_encode($dato)."' ";
	print 'title="'.search_development2::search_options_title( $this->search_operators_info() ).'" ';
	print ">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "";
					break;
						
		
		case ($permissions>=1)	:

					# COMPARISON OPERATORS
					$html_contenido .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);

					
					# INPUT
					$html_contenido .= "<input class=\"css_relation_index\" type=\"text\" name=\"{$search_input_name}\" value=\"\"/> ";
					

					# LOGICAL OPERATORS
					$html_contenido .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);
											
	}
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);
	

	# PRINT HTML
	print $html_label;
	print $html_contenido;	

	
	print "</div>"; //wrap
?>