<?php

	# VISUALIZADOR HTML

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in');

	print "<div class=\"wrap_component css_wrap_relation_index wrap_component_{$modo} wrap_component_{$tipo}\" id=\"{$id_wrapper}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato='{$dato_string}' ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-component_info='{$component_info}' ";
	print ">";

	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	# CONTENIDO (INPUT)
	$html_content = '';
	switch(true) {

		case ($permissions===0) :
				$html_content .= "";
				break;

		case ($permissions===1) :
				$html_content .= $this->valor;
				break;


		case ($permissions>=2) :
				/*
				$html_content .= "<div class=\"wrap_relation_index_values\">";

				
				#
				# CONTEXT
				# Set as disabled on time machine context 
				$disabled = (isset($context->context_name) && $context->context_name=='tool_time_machine') ? 'disabled="disabled"' : '';

				# Inputs
				function component_relation_index_input($locator_string, $disabled, $tipo, $lang, $parent, $section_tipo, $modo) {		
					
					return "<input class=\"css_relation_index\" type=\"text\"
					value='{$locator_string}'
					data-role=\"component_relation_index_input\"
					data-tipo=\"{$tipo}\"
					data-lang=\"{$lang}\"
					data-parent=\"{$parent}\"
					data-section_tipo=\"{$section_tipo}\"
					data-modo=\"{$modo}\"
					onchange=\"component_relation_index.Save(this)\"
					$disabled
					tabindex=\"1\"
					/>";
				}

				# Button remove
				$button_remove = "<input type=\"button\" class=\"component_relation_index_button_remove\" value=\"Remove relation\"
				data-role=\"component_relation_index_button_remove\"
				onclick=\"component_relation_index.remove_locator(this)\" />";

				if (empty($dato)) {
						# Note : This line is only for javascript reference purposes (clone)
						# Never is shown
						$html_content .= "<div class=\"relation_index_input_line\" style=\"display:none\">";
						$html_content .= component_relation_index_input('',$disabled, $tipo, $lang, $parent, $section_tipo, $modo);
						$html_content .= $button_remove;
						$html_content .= "</div>";//relation_index_input_line
				}else{
					foreach ((array)$dato as $key => $current_locator) {
						$locator_value = component_relation_index::get_locator_value( $current_locator, $lang, $section_tipo );

						$current_locator_string = json_encode($current_locator);
						$html_content .= "<div class=\"relation_index_input_line\">";
						$html_content .= component_relation_index_input($current_locator_string,$disabled, $tipo, $lang, $parent, $section_tipo, $modo);
						$html_content .= $button_remove;
						$html_content .= '<span class="locator_label">'.$locator_value.'</span>';
						$html_content .= "</div>";//relation_index_input_line
					}
				}

				$html_content .= "</div>";//end wrap_parent_values


				$html_content .= "<input type=\"button\" class=\"relation_index_add_button\" value=\"Add indexation\"
				data-target_tipo=\"$section_tipo\"				
				onclick=\"component_relation_index.open_index_selector_window(this,event)\" />";
				*/

				# TERMS
				# dump($dato, ' dato ++ '.to_string());
				foreach ((array)$dato as $key => $current_locator) {

					$html_content .= "<div class=\"relation_index_input_line\">";

					# REMOVE BUTTON
					/*
					$html_content .= "<input type=\"button\" class=\"button_remove component_relation_index_button_remove\" value=\"\"
										data-role=\"component_relation_index_button_remove\"
										data-target_section_tipo=\"$current_locator->section_tipo\"
										data-target_section_id=\"$current_locator->section_id\"
										onclick=\"component_relation_index.remove_children(this)\" />";
					*/
					# TERM STRING
					$value = ts_object::get_term_by_locator( $current_locator, DEDALO_DATA_LANG, $from_cache=true );
					#$value = $current_locator->section_tipo .'_'. $current_locator->section_id .'_'. $current_locator->component_tipo .'_'. $current_locator->tag_id;
					$html_content .= '<span class="locator_label">'.$value.'</span>';

					if(SHOW_DEBUG===true) {
						#$html_content .= to_string($current_locator);
					}

					$html_content .= "</div>";//relation_index_input_line
				}//end foreach ((array)$dato as $key => $current_locator)
				
				



				if(SHOW_DEBUG) {
					#$html_content .= " <div class=\"debug_info\"> Current val: <strong>$valor</strong></div>";				
					#$html_content .= " <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\">{$debugger}</span>";
					$html_content .= "<span class=\"debug_info\">";
					$html_content .= "<br> locators in section relation (parent.tipo: ".$this->relation_type.") : ";
					$html_content .= wrap_pre( to_string($this->get_my_section_relations($this->relation_type)), false );
					$html_content .= "</span>";
				}
				break;
	}

	# Prepare content to show in page
	tools::prepare_content($html_content);


	# PRINT HTML
	print $html_label;
	print $html_content;


	print '</div>'; //wrap


	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out');


?>