<?php

	# VISUALIZADOR HTML	

	$var_requested = common::get_request_var($tipo);
	#if(isset($_REQUEST[$tipo])) $dato = $_REQUEST[$tipo];	#var_dump($_REQUEST[$tipo]);
	if(!empty($var_requested)) $dato = $var_requested;	
	print "\n<div class=\"wrap_component css_wrap_relation_index\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "";
					break;
						
		
		case ($permissions>=1)	:

					# COMPARISON OPERATORS
					$html_contenido .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);

					
					# INPUT
					$html_contenido .= "\n<input class=\"css_relation_index\" type=\"text\" name=\"{$search_input_name}\" value=\"\"/> ";
					

					# LOGICAL OPERATORS
					$html_contenido .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);
											
	}
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);
	

	# PRINT HTML
	print $html_label;
	print $html_contenido;	

	
	print "\n</div><!-- /css_wrap_relation_index -->\n\n"; //wrap
?>