<?php

	# VISUALIZADOR HTML	


	# PLAYER
	$html_contenido = '';

	$html_contenido .= "\n<div class=\"css_player_wrap\">";


	# POSTERFRAME ONLY
	#$html_contenido .= "\n <img class=\"av_posterframe_only\" src=\"$posterframe_url\" width=\"$video_width\" height=\"$video_height\" alt=\"Posterframe\" title=\"\" />";

	
	# VIDEO HTML5 OBJ
	$html_contenido .= "\n<video class=\"css_av_video\"	
	preload=\"metadata\" 
	controls=\"controls\"  
	poster=\"$posterframe_url\"  
	onerror=\"component_av.failed(event)\" 
	id=\"{$player_id}\" 
	data-tipo=\"{$tipo}\" data-video_id=\"{$video_id}\"					
	>";

	$html_contenido .= "\n <source id=\"video_mp4_{$tipo}\" src=\"$video_url\" preload=\"metadata\" type=\"video/mp4\" >";
	# FALLBACK IMG (no html5 codec video support)
	$html_contenido .= "\n <img src=\"$posterframe_url\" alt=\"Posterframe\" title=\"No video playback capabilities\" />";

	$html_contenido .= "\n</video>";
		



	$html_contenido .= "\n</div><!-- /css_player_wrap -->";

	# PRINT HTML
	print $html_contenido;

?>