<?php

	# VISUALIZADOR HTML


	# CONTENIDO
	$html_contenido = (string)'';
	switch($permissions) {

		case 0	:
			$html_contenido .= '';
			break;

		case ($permissions>=1):

			$html_contenido .= "<div class=\"div_image_image_in_list\">"; //width=\"102\" height=\"57\"

			# CLICK_ACTION
			$click_action="onclick=\"tool_common.open_player(this,{'type':'component_image','image_full_url':'$image_full_url'});\" ";
					
			$html_contenido .= "<img class=\"thumb_in_list image_image_in_list\" src=\"$image_url\" data-image_id=\"$image_id\" data-parent_matrix=\"$parent\" data-objetive_thumb_url=\"$objetive_thumb_url\" $click_action/>";

			$html_contenido .= "</div>";
			break;
	}


	# PRINT HTML
	print $html_contenido;
?>