<?php

	# VISUALIZADOR HTML	


	# PLAYER
	$html_content = '';

	$html_content .= "<div class=\"css_player_wrap\">";


	# POSTERFRAME ONLY
	#$html_content .= " <img class=\"av_posterframe_only\" src=\"$posterframe_url\" width=\"$video_width\" height=\"$video_height\" alt=\"Posterframe\" title=\"\" />";

	
	# VIDEO HTML5 OBJ
	$html_content .= "<video class=\"css_av_video\" ";
	$html_content .= "preload=\"metadata\" ";
	$html_content .= "controls=\"controls\"  ";
	$html_content .= "poster=\"$posterframe_url\" "; 
	$html_content .= "onerror=\"component_av.failed(event)\" ";
	$html_content .= "id=\"{$player_id}\" ";
	$html_content .= "data-tipo=\"{$tipo}\" data-video_id=\"{$video_id}\"	";				
	$html_content .= ">";

	$html_content .= "<source id=\"video_mp4_{$tipo}\" src=\"$video_url\" preload=\"metadata\" type=\"video/mp4\" >";
	# FALLBACK IMG (no html5 codec video support)
	$html_content .= "<img src=\"$posterframe_url\" alt=\"Posterframe\" title=\"No video playback capabilities\" />";

	$html_content .= "</video>";
		



	$html_content .= "</div><!-- /css_player_wrap -->";

	# PRINT HTML
	print $html_content;

?>