<?php

	# VISUALIZADOR HTML


	# CONTENIDO THUMB
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." (image)</span>";
					break;

					
		case ($permissions>=1) :


				$html_contenido .= "\n <div class=\"player_container\">";
				$html_contenido .= "\n <img class=\"css_image\" src=\"$image_url\" />";
				$html_contenido .= "\n </div>";

				
					
	}
	
	# PRINT HTML	
	print $html_contenido;	

?>