<?php
$js_url = DEDALO_LIB_BASE_URL.'/component_image/js/component_image_read.js';
?>
<script>
var url = '<?php echo $js_url ?>';
	console.log(url)
//head.ready(function () {
    // some callback stuff
    //head.load(url);
   // console.log(url)
//});
</script>
<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 			$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_image'])) 				$ar_css['css_image']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 		$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))		$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_image']))			$ar_css['css_wrap_image']='';	


	#print "<script>";
	#print " head.load('".DEDALO_LIB_BASE_URL.'/component_image/js/component_image_read.js'."')";
	#print '</script>';
	
	
	print "\n<!-- IMAGE [tipo:$tipo id_matrix:$id] $label -->";
	print "\n<div class=\"css_wrap_image wrap_component {$ar_css['css_wrap_image']}\" id=\"{$id_wrapper}\"
	data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-parent=\"{$parent}\" data-modo=\"{$modo}\" data-dato=\"{$valor}\" data-component_name=\"{$component_name}\" >";
	
		
		# ETIQUETA (LABEL)
		$html_label = component_common_draw::draw_label($this);
		
		# CONTENIDO (INPUT)
		$html_contenido = '';
		switch($permissions) {
				
			case 0 :	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." (av)</span>";
						break;
							
			case ($permissions>=1) :
			
						# IMAGE THUMB
						$title = '';
						if(SHOW_DEBUG) {
							$title .= "image_path: ".$this->get_image_path($quality);
						}
						
						# CANVAS : IMAGE   width=\"$img_width\" height=\"$img_height\"
						$html_contenido .= "<canvas id=\"$identificador_unico\" class=\"canvas_edit\" title=\"$title\">";
						$html_contenido .= $image_thumb_html ;
						//$html_contenido .= "<img id=\"img_$identificador_unico\" src=\"$img_src\" />";
						$html_contenido .= "</canvas>";
						
						
						
						
				if($permissions==3)		
						$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$debugger}</span>";	
												
		}

		# INIT : Init text editor 
		$html_contenido .= "\n<script>component_image_read.init_canvas('$identificador_unico');</script>";

		# Prepare content to show in page
		tools::prepare_content($html_contenido);	
		

		# PRINT HTML
		print $html_label;
		print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_image IMAGE [tipo:$tipo id_matrix:$id] $label -->\n"; //wrap


	
?>









