<?php

	# VISUALIZADOR HTML


	# CONTENIDO
	$html_contenido = (string)'';
	switch($permissions) {

		case 0	:
			$html_contenido .= '';
			break;

		case ($permissions>=1):
			/*
			$html_contenido .= "<div class=\"div_image_image_in_list\">"; //width=\"102\" height=\"57\"

				# CLICK_ACTION
				$click_action="onclick=\"tool_common.open_player(this,{'type':'component_image','image_full_url':'$image_full_url'});\" ";
				
				# IMG TAG	
				$html_contenido .= "<img class=\"thumb_in_list image_image_in_list\" src=\"$thumb_file_url\"
				data-image_id=\"$image_id\"
				data-parent_matrix=\"$parent\"				
				$click_action
				alt=\"$image_id\" />";

				// data-objetive_thumb_url=\"$objetive_thumb_url\"
				#$html_contenido .= " thumb_file_url: $thumb_file_url ";

			$html_contenido .= "</div>";
			*/

			# CLICK_ACTION
			$click_action="onclick=\"tool_common.open_player(this,{'type':'component_image','image_full_url':'$image_full_url'});\" ";

			$style = "background-image:url('$thumb_file_url')";
			$html_contenido .= "<div class=\"thumb_in_list div_image_image_in_list\" style=\"$style\" $click_action
			data-image_id=\"$image_id\"
			data-parent_matrix=\"$parent\"
			alt=\"$image_id\"
			></div>";

			break;
	}


	# PRINT HTML
	print $html_contenido;
?>