<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 			$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_image'])) 				$ar_css['css_image']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 		$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))		$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_image']))			$ar_css['css_wrap_image']='';	
	
	
	print "\n<!-- IMAGE [tipo:$tipo id_matrix:$id] $label -->";
	print "\n<div class=\"css_wrap_image wrap_component {$ar_css['css_wrap_image']}\" id=\"{$id_wrapper}\"
	data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-parent=\"{$parent}\" data-modo=\"{$modo}\" data-dato=\"{$valor}\" data-component_name=\"{$component_name}\" >";
	
		
		# ETIQUETA (LABEL)
		#$html_label = component_common_draw::draw_label($this);


		# Buttons
		$html_buttons='';

		
		# CONTENIDO (INPUT)
		$html_contenido = '';
		switch($permissions) {
				
			case 0 :	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." (image)</span>";
						break;
							
			case ($permissions>=1) :


						# CANVAS : IMAGE   width=\"$img_width\" height=\"$img_height\"
						$html_contenido .= "<canvas id=\"$identificador_unico\" class=\"canvas_transcription_edit\">";
						$html_contenido .= "<img id=\"img_$identificador_unico\" src=\"$img_src\" data-img_width=\"$img_width\" data-img_height=\"$img_height\" />";
						$html_contenido .= "</canvas>";

						$html_buttons .= "<div class=\"image_buttons\">";
						
							$html_buttons .= '
							<select name="zoom" id="zoom">
								<option value="800">800%</option>
								<option value="400">400%</option>
								<option value="200">200%</option>
								<option value="100">100%</option>
								<option value="75">75%</option>
								<option value="50">50%</option>
								<option value="25">25%</option>
								<option value="12.5">12.5%</option>
								<option value="6.25">6.25%</option>
								<option value="5">5%</option>
								<option value="1">1%</option>
								<option value=""></option>
							</select>
							';
							$html_buttons .= "<span class=\"main_buttons\">";
							$html_buttons .= "<input type=\"button\" value=\"cuadrado\" onclick=\"cuadrado.activate()\">";
							$html_buttons .= "<input type=\"button\" value=\"circulo\" onclick=\"circulo.activate()\">";
							$html_buttons .= "<input type=\"button\" value=\"vectores\" onclick=\"vectores.activate()\">";
							$html_buttons .= "<input type=\"button\" value=\"puntero\" onclick=\"puntero.activate()\">";							
							#$html_buttons .= "<input type=\"button\" value=\"anadido\" onclick=\"anadido.activate()\">";
							$html_buttons .= "<input type=\"button\" value=\"salvar\" class=\"save_image_path\" onclick=\"salvar()\">";
							$html_buttons .= "</span>";

						$html_buttons .= "</div>";
			
						
				if($permissions==3)		
						$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$debugger}</span>";	
												
		}

		# INIT : Init text editor 
		$html_contenido .= "\n<script>component_image.init_canvas('$identificador_unico');</script>";

		# Prepare content to show in page
		tools::prepare_content($html_contenido);	
		

		# PRINT HTML
		print $html_buttons;
		print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_image IMAGE [tipo:$tipo id_matrix:$id] $label -->\n"; //wrap
?>