<?php

	# VISUALIZADOR HTML


	# CONTENIDO THUMB
	$html_contenido = '';
	switch($permissions) {	
					
		case ($permissions>=1) :


				#$html_contenido .= "\n <div class=\"player_container\">";
				$html_image = "\n <img class=\"css_image\" style=\"width:100%\" src=\"$image_url\" />";
				#$html_contenido .= "\n </div>";

				# ETIQUETA (LABEL)
				if (!isset($this->print_options->show_label) || $this->print_options->show_label==true) {					
				$html_contenido .= "\n <div class=\"print_label {$component_name}_print_label\">$label</div>";
				}
				# CONTENT (DATO)
				$html_contenido .= "\n <div class=\"print_content {$component_name}_print_content\">$html_image</div>";				
					
	}
	
	# PRINT HTML	
	print $html_contenido;	

?>