<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>D4 TS</title>
<link rel="shortcut icon" href="../favicon.ico" />

<link rel="stylesheet" type="text/css" charset="utf-8" href="../css/general.css" />

<script type="text/javascript" src="<?php echo JQUERY_LIB_URL_JS ?>"></script>
<script type="text/javascript" src="../inc/javascript.js"></script>
<script type="text/javascript">
// vars

var id						= '<?php echo $datos['id'];?>' ;
var alpha2					= '<?php echo $datos['alpha2'];?>' ;
var activa					= '<?php echo $datos['activa'];?>' ;
var modo					= '<?php echo $modo ?>' ;

var debe_introducir_title				= '<?php echo msgJS($debe_introducir_title)?>';
var nombre_title						= '<?php echo msgJS($nombre_title)?>';
var unico_title							= '<?php echo msgJS($unico_title)?>';
var utilizado_title						= '<?php echo msgJS($utilizado_title)?>';
var no_title							= '<?php echo msgJS($no_title)?>';
var un_title							= '<?php echo msgJS($un_title)?>';
var se_eliminaran_todos_los_datos_title	= '<?php echo msgJS($se_eliminaran_todos_los_datos_title)?>';
var de_title							= '<?php echo msgJS($de_title)?>';
var tipo_title							= '<?php echo msgJS($tipo_title)?>';
var ya_se_usa_title						= '<?php echo msgJS($ya_se_usa_title)?>';
var valido_title						= '<?php echo msgJS($valido_title)?>';

var idsOcupados=new Array();
<?php 
if(is_array($idsOcupados)) foreach($idsOcupados as $key=>$idactual)
{
	if($idactual != $datos['id'])
	echo "idsOcupados[$key]='$idactual';\n";
}
?>
var alpha2Ocupados=new Array();
<?php 
if(is_array($alpha2Ocupados)) foreach($alpha2Ocupados as $key=>$alpha2Actual)
{
	if($alpha2Actual != $datos['alpha2'])
	echo "alpha2Ocupados[$key]='$alpha2Actual';\n";
}
?>

var alpha3Ocupados=new Array();
<?php 
if(is_array($alpha3Ocupados)) foreach($alpha3Ocupados as $key=>$alpha3Actual)
{
	if($alpha3Actual != $datos['alpha3'])
	echo "alpha3Ocupados[$key]='$alpha3Actual';\n";
}
?>
//alert(idsOcupados)

function activaChange(value)
{
	//alert(value)
	//if(activa=='si' && value=='no') alert(se_eliminaran_todos_los_datos_title + " " + de_title + " "+toponimia_title )
}

function openTipo()
{
	alert("openTipo in progress !")	
}

function validar(form1)
{
	// ID
	var index = idsOcupados.indexOf(form1.id.value); //alert(index + " "+form1.id.value) // Find the index	
	if (index != -1) {
     	alert(debe_introducir_title + " " + un_title + " ID " + unico_title + " ! \n (" + no_title +" "+ utilizado_title+ ") " );
	 	document.form1.id.focus();	  
     	return (false);
  	}
	if (document.form1.id.value.length < 1)  {
     	alert(debe_introducir_title + " ID ej. 254 " );
	 	document.form1.id.focus();	  
     	return (false);
  	}
	
	// NOMBRE
	if (document.form1.nombre.value.length < 1)  {
     	alert(debe_introducir_title +" "+nombre_title + " ej. España " );
	 	document.form1.nombre.focus();	  
     	return (false);
  	}	
	
	// ALPHA2
	document.form1.alpha2.value.toUpperCase();
	if (document.form1.alpha2.value.length < 2)  {
     	alert(debe_introducir_title + " TLD (alpha2) " + valido_title + " (2 chars)" );
	 	document.form1.alpha2.focus();	  
     	return (false);
  	}
	var regexAlpha2 = new RegExp('[A-Z][A-Z]');
	if (!document.form1.alpha2.value.match(regexAlpha2)) {
		alert(debe_introducir_title + " TLD (alpha2) " + valido_title );
		document.form1.alpha2.focus();
		return (false);
	}
	var index = alpha2Ocupados.indexOf(form1.alpha2.value.toUpperCase());
	if (index != -1) {
     	alert(debe_introducir_title + " " + un_title + " TLD (alpha2) " + unico_title + " ! \n (" + no_title +" "+ utilizado_title+ ") " );
	 	document.form1.alpha2.focus();	  
     	return (false);
  	}
	
	// ALPHA3
	document.form1.alpha3.value.toUpperCase();
	if (document.form1.alpha3.value.length < 3)  {
     	alert(debe_introducir_title + " TLD (alpha3) " + valido_title + " (3 chars)" );
	 	document.form1.alpha3.focus();	  
     	return (false);
  	}
	var regexAlpha3 = new RegExp('[A-Z][A-Z][A-Z]');
	if (!document.form1.alpha3.value.match(regexAlpha3)) {
		alert(debe_introducir_title + " TLD (alpha3) " + valido_title );
		document.form1.alpha2.focus();
		return (false);
	}
	var index = alpha3Ocupados.indexOf(form1.alpha3.value.toUpperCase());
	if (index != -1) {
     	alert(debe_introducir_title + " " + un_title + " TLD (alpha3) " + unico_title + " ! \n (" + no_title +" "+ utilizado_title+ ") " );
	 	document.form1.alpha3.focus();	  
     	return (false);
  	}	
	
	
	// TIPO
	if (form1.tipo.value.length < 1)  {
     	alert(debe_introducir_title + " " + tipo_title );
	 	form1.tipo.focus();	  
     	return (false);
  	}
	
  return (true); 
}

function estaUsado_alpha2(value)
{
	if(value.length == 2)
	{		
		// ALPHA2
		var index = alpha2Ocupados.indexOf(value);
		if (index != -1)
		{			
			$('#alpha2aviso').html( ya_se_usa_title );			
		}else{
			$('#alpha2aviso').html( '' );	
		}		
	}
}

function estaUsado_alpha3(value)
{
	if(value.length == 3)
	{		
		// ALPHA3
		var index = alpha3Ocupados.indexOf(value);
		if (index != -1)
		{			
			$('#alpha3aviso').html( ya_se_usa_title );			
		}else{
			$('#alpha3aviso').html( '' );	
		}		
	}
}


$(document).ready(function()
{
	if(modo=="edit" && activa == 'no') document.form1.nombre.focus();
	
}); //FIN domready jquery

</script>

</head>
<body>
<table width="100%"  height="100%" border="0" cellspacing="0" cellpadding="0">
  
  <tr>
    <td align="center" valign="top" >
    
	<div id="wrapGeneral" style="width:820px"  >
      
      
    <form name="form1" id="form1" method="post" action="controller.Jerarquia.php"  onSubmit="return validar(this)" >
      <table width="50%" border="0" cellpadding="4" cellspacing="1">
		<tr>
          <td colspan="2" align="right" nowrap bgcolor="#496473" class="blanco"><?php echo "$modo $jerarquias_title " ?><?php if($id) echo " ID: $id " ?></td>
          </tr>
		<tr align="center">
          <td width="160" align="right" nowrap bgcolor="#CCCCCC" >&nbsp;</td>
          <td width="78%" align="left" nowrap bgcolor="#CCCCCC">&nbsp;</td>
        </tr>
        <tr align="center"  style="margin-left:4px" >
          <td width="160" align="right" nowrap bgcolor="#CCCCCC" > ID <?php echo " $unico_title " ?></td>
          <td align="left" nowrap bgcolor="#CCCCCC" >
          	<input name="id" type="text" id="id" style="width:50px; text-align:center; font-weight:bold; color:#000"  value="<?php echo $id ?>" <?php if($activa=='si') print 'readonly'; ?>  >
          </td>
        </tr>
        <tr align="center"  style="margin-left:4px" >
          <td width="160" align="right" nowrap bgcolor="#CCCCCC" > <?php echo $nombre_title ?>  </td>
          <td align="left" nowrap bgcolor="#CCCCCC" >
          	<input name="nombre" type="text" id="nombre" style="width:200px;padding-left:5px;" value="<?php echo $datos['nombre'] ?>" <?php if($activa=='si') print 'readonly'; ?> >
          </td>
        </tr>
        <tr align="center"  style="margin-left:4px" >
          <td width="160" align="right" valign="middle" nowrap bgcolor="#CCCCCC" >TLD (alpha2)</td>
          <td align="left" nowrap bgcolor="#CCCCCC">
          	<div id="alpha2aviso" style="float:right;margin-top:4px; margin-right:4px;width:auto;text-align:right;color:red; font-weight:bold"></div>
            <input name="alpha2" type="text" id="alpha2" style="width:30px; text-align:center" value="<?php echo $datos['alpha2'] ?>" maxlength="2" onKeyUp="this.value=this.value.toUpperCase();" onChange="estaUsado_alpha2(this.value)" <?php if($activa=='si') print 'readonly'; ?>> 
          	<span class="anotacionTexto"> ej. ES  (<?php echo $solo_letras_title ?>)</span>            
          </td>
        </tr>
        <tr align="center"  style="margin-left:4px" >
          <td width="160" align="right" valign="middle" nowrap bgcolor="#CCCCCC" >TLD (alpha3)</td>
          <td align="left" nowrap bgcolor="#CCCCCC">
          	<div id="alpha3aviso" style="float:right;margin-top:4px; margin-right:4px;width:auto;text-align:right;color:red; font-weight:bold"></div>
          	<input name="alpha3" type="text" id="alpha3" style="width:40px; text-align:center" value="<?php echo $datos['alpha3'] ?>" maxlength="3" onKeyUp="this.value=this.value.toUpperCase();" onChange="estaUsado_alpha3(this.value)" <?php if($activa=='si') print 'readonly'; ?>> 
          	<span class="anotacionTexto"> ej. ESP (<?php echo $solo_letras_title ?>)</span>
            </td>
        </tr>
        <tr align="center"  style="margin-left:4px" >
          <td align="right" valign="middle" nowrap bgcolor="#CCCCCC" ><?php echo $tipo_title ?></td>
          <td align="left" nowrap bgcolor="#CCCCCC">			
            <?php echo crearDesplegableJerTipo($datos['tipo']) ; ?>
            <input type="button" name="tipoBtn" value="<?php echo $nuevo_title.' '.$tipo_title ?>" class="SubmitButon" onClick="openTipo()">
          </td>
        </tr>
        <tr align="center"  style="margin-left:4px" >
          <td align="right" valign="middle" nowrap bgcolor="#CCCCCC" ><?php echo $activa_title ?></td>
          <td align="left" nowrap bgcolor="#CCCCCC">
            <?php 
			$selectBGcolor = false ;
			$activa = $datos['activa']; if(!isset($activa)) $activa = 'no';
			if($activa=='si') $selectBGcolor = "background-color:#090;" ;
			if($activa=='no') $selectBGcolor = "background-color:#FF0000;" ;
			?>
        	<select name="activa" id="activa" <?php echo $selectBGcolor ?>  onChange="activaChange(this.value)">
				<option value="si" <?php if (!(strcmp('si', $activa))) {echo "selected=\"selected\" ";} ?> ><?php echo $si_title ?></option>
				<option value="no" <?php if (!(strcmp('no', $activa))) {echo "selected=\"selected\" ";} ?> ><?php echo $no_title ?></option>              
			</select>
            <div style="width:18px; height:18px;<?php echo $selectBGcolor ?>display:inline-block; vertical-align: middle">&nbsp;</div>
          </td>
        </tr>
        
        
          
	<tr align="center">
      <td height="50" align="left" valign="middle" nowrap bgcolor="#CCCCCC" >&nbsp;</td>
      <td align="left" valign="middle" nowrap bgcolor="#CCCCCC" >
       
        <!-- Campos obligatorios -->
        <input type="hidden" name="activaAnterior" value="<?php echo $datos['activa']; ?>" >
        <input name="accion" type="hidden" value="<?php echo $modo ?>" >
        <input type="submit" name="Submit" value="  <?php echo $modificar_title ?>  " class="SubmitButon" >
        <?php if($head=='no'){ ?>
        <input name="cancelar" type="button" value=" <?php echo $cerrar_title ?> "  class="flechas" onClick="javascript: window.close() ;">
        <?php }else{ ?>
        <input name="cancelar" type="button" value=" <?php echo $cancelar_title ?> " onClick="javascript: history.go(-1);">
        <?php }//if($head=='no'){ ?>
      </tr>
	</table>
    </form> 
    
       
	</div><!-- wrapGeneral -->
      
      </td>
  </tr>
  
  
  
</table>

</body>
</html>