<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>D4 TS</title>
<link rel="shortcut icon" href="../favicon.ico" />

<?php
# CSS
print css::build_tag(JQUERY_UI_URL_CSS); 
print css::build_tag(DEDALO_LIB_BASE_URL .'/html_page/css/html_page.css');
print css::build_tag(DEDALO_LIB_BASE_URL .'/common/css/common.css');
print css::build_tag(DEDALO_LIB_BASE_URL .'/menu/css/menu.css'); 
print css::build_tag(DEDALO_ROOT_WEB .'/css/list.css');
print css::build_tag(DEDALO_ROOT_WEB .'/jer/css/jer_main.css');
?>
<script type="text/javascript">
    var DEDALO_LIB_BASE_URL = '<?php echo DEDALO_LIB_BASE_URL ?>' ;
    var page_globals = new Object();
        page_globals.dedalo_application_lang    = '<?php echo DEDALO_APPLICATION_LANG ?>' ;
        page_globals.dedalo_data_lang       = '<?php echo DEDALO_DATA_LANG ?>' ;
        page_globals.dedalo_data_nolan      = '<?php echo DEDALO_DATA_NOLAN ?>' ;       
        page_globals.modo           = '<?php echo $modo ?>' ;
 
    var DEBUG = true;

    /*
    * clean query $_SERVER['QUERY_STRING'] for avoid duplicates in js function ordenar()
    */
    var query_string = '<?php echo eliminarOT() ?>';

    // vars
    var esta_seguro_de_eliminar_registro_1_title    = '<?php echo msgJS($esta_seguro_de_eliminar_registro_1_title) ?>';
    var esta_completamente_seguro_title             = '<?php echo msgJS($esta_completamente_seguro_title) ?>';
    var nombre_title                                = '<?php echo msgJS($nombre_title) ?>';
</script>
<?php
# JS
print js::build_tag(JQUERY_LIB_URL_JS);
print js::build_tag(JQUERY_UI_URL_JS);
print js::build_tag(DEDALO_LIB_BASE_URL . '/common/js/common.js');
print js::build_tag(DEDALO_LIB_BASE_URL . '/common/js/cookies.js');
print js::build_tag(DEDALO_LIB_BASE_URL . '/menu/js/menu.js');
print js::build_tag(DEDALO_LIB_BASE_URL . '/login/js/login.js');
print js::build_tag(DEDALO_ROOT_WEB . '/inc/javascript.js');
print js::build_tag(DEDALO_ROOT_WEB . '/jer/js/jer_list.js');
?>

</head>

<body>      
<div id="wrapGeneral">  
<table width="100%"  border="0" cellspacing="0" cellpadding="0" height="100%">
  
  <tr>
    <td><?php print $html_header ?></td>
  </tr>
  
  <tr>
    <td height="100%" align="center" valign="top">  
    
    <div class="wrap_content">

	<div id="left_content" class="list_content">    
    
        <form name="form1" method="get" action="" style="text-align:center"> 
           
            <table id="form_table" width="96%" cellpadding="0" cellspacing="0" align="center">
            <tr >
            	<td align="center">ID</td>
            	<td align="center">TLD</td>
            	<td><?php echo $nombre_title ?></td>
            	<td><?php echo $activa_title ?></td>
            	<td><?php echo $tipo_title ?></td>
            	<td><?php echo $max_por_pagina_title ?></td>
            	<td align="center"> <a href="javascript:top.location.href='?' ;"><?php echo $todos_title ?></a> </td>
            	
            </tr>
            <tr>
            	<td align="center"><input type="text" name="id" id="id" value="<?php echo $idGET ?>" style="width:40px; text-align:center"></td>
            	<td align="center"><input type="text" name="alpha2" id="alpha2" value="<?php echo $alpha2GET ?>" style="width:30px; text-align:center"></td>
            	<td><input type="text" name="nombre" id="nombre" value="<?php echo $nombreGET ?>" style="width:100px; text-align:center"></td>
            	<td>
                <select name="activa" id="activa">
            	  <option value="" ></option>
            	  <option value="si" <?php if (!(strcmp('si', $activaGET))) {echo "selected=\"selected\" ";} ?> ><?php echo $si_title ?></option>
            	  <option value="no" <?php if (!(strcmp('no', $activaGET))) {echo "selected=\"selected\" ";} ?> ><?php echo $no_title ?></option>
          	  	  </select>
              </td>
            	<td>
                <?php echo $jer->crearDesplegableJerTipo($tipoGET,90) ?>
                </td>
            	<td><input type="text" name="max" id="max" value="<?php echo $maxRows_Recordset1 ?>" style="width:40px; text-align:center"></td>
            	<td><input type="submit" name="button" id="button" value=" <?php echo $buscar_title ?> " class="SubmitButon"><input name="filtro" type="hidden" value="y"></td>
            	
            </tr>
            </table><!-- /form_table -->
        
        </form>
   
    
	   <div id="list" style="margin-top:10px">
    	   <?php $pag = 'top'; $pag = 'pagContDivNoMargen';  include('../inc/paginacion.php'); ?>
        
            <table id="tabla" class="recordsTableList">
        	<tr class="rowHead">            
                <td width="46" align="center"  nowrap>ID<?php echo flechasOrden('id')?></td>
                <td width="48" align="center" nowrap >Tld<?php echo flechasOrden('alpha2')?></td>
                <td	width="" align="left" nowrap ><?php echo $nombre_title ?> <?php echo flechasOrden('nombre')?></td>
                <td width="63" align="center" nowrap ><?php echo $tipo_title ?><?php echo flechasOrden('tipo')?></td>
                <td width="23" align="center" nowrap >M</td>
                <td width="35" align="center" nowrap >D</td>  
            </tr>
            </table>
        
        
    		<div style="height:470px; width:100%; overflow:auto">
        		<table class="recordsTableList">
                
        		<?php
                #if($totalRows_Recordset1>0) do { 
                while ($row_Recordset1 = pg_fetch_assoc($result) ) {
            
        		$id 		= intval($row_Recordset1['id']);	
        		$alpha2 	= $row_Recordset1['alpha2'];
        		$nombre 	= $row_Recordset1['nombre'];
        		$activa 	= $row_Recordset1['activa'];
        		$tipo	 	= $row_Recordset1['tipo'];
        		$tipoText 	= $row_Recordset1['tipo_text'];
        		$mainLang 	= $row_Recordset1['main_lang'];
                    #dump($mainLang,"mainLang");
        		?>    
                <tr id="<?php echo "tr_$id"?>" align="center" bgcolor="#CFCFCF" class="trTaxlist" >     
                
                <td width="42" height="34" align="right" nowrap > <span style="margin-right:2px;"><?php echo $id ?></span></td>        
                <td width="44" nowrap><?php echo $alpha2 ?></td>
                
                <td width="" align="left">
                	<?php if(SHOW_DEBUG==true){?>			   
        			<img src="../images/iconos/edit_grey.png"   title="Edit" onClick="go2edit('<?php echo $id ?>')" class="btnEdit" />
                    <img src="../images/iconos/button_drop.png" title="Drop" onClick="borrarFicha('<?php echo $id ?>','<?php echo addslashes($nombre)?>','<?php echo $alpha2 ?>');" class="dropIcon" />
        			<?php }//if(SHOW_DEBUG==true){?>
        			<?php echo $nombre ?>
                    <?php echo " [$mainLang]" ?>
                </td>
                
                 <!-- TIPO -->   
                <td width="50" ><?php #echo $tipo ?> <?php echo $tipoText ?></td>  
                
                 <!-- ESMODELO -->      
                <td width="25" style="padding:0px">
        		<?php if($activa=='si'){?>
                	<div style="width:100%; height:34px; margin:0px; cursor:pointer " onClick="gotoFlatList('<?php echo $id ?>','<?php echo $alpha2 ?>','modelo_edit')">
                	<img src="../images/iconos/m-icon.gif" style="margin-top:10px; cursor:pointer" >
                    </div>
        		<?php }//if($activa=='si')?>
                </td>
                
                <!-- NO ESMODELO. DATOS -->  
                <td width="25" style="padding:0px">
        		<?php if($activa=='si'){?>
                	<div style="width:100%; height:34px; margin:0px; cursor:pointer " onClick="gotoFlatList('<?php echo $id ?>','<?php echo $alpha2 ?>','tesauro_edit')">
                	<img src="../images/iconos/flecha.gif" style="margin-top:12px; cursor:pointer" >
                    </div>
        		<?php }//if($activa=='si')?>
                </td>   
                
                     
                
                </tr>
        		<?php 
                #} while ($row_Recordset1 = mysql_fetch_assoc($Recordset1)); mysql_free_result($Recordset1); 
                #} while ($row_Recordset1 = $result->fetch_array(MYSQLI_ASSOC) ); #$result->close();
                };
                ?>
         
         
         
          
          		<?php if($totalRows_Recordset1<1){ ?>
                <tr>
                    <td colspan="5"> <div style="color: #F30; padding:10px"><?php echo $no_hay_resultados_coincidentes_title ?></div> </td>
                </tr>    
        		<?php } #if($totalRows_Recordset1>0) ?>
            
              
        		</table>
                </div>    
              
        	<?php $pag = 'down'; include('../inc/paginacion.php'); ?> <br>
    	</div><!-- /#list -->
      
    </div><!-- /left_content -->

      
   
      <!-- IFRAME FLAT DATOS - MODELO -->
      <div style="display:block; width:auto; float:none; margin-left:475px; ">
      	<?php /* */ ?>
        <iframe id="iframeFlat" name="iframeFlat" width="100%" height="610px" frameborder="0" src="jer_flat_list.php?head=no&tld=" scrolling="auto" ></iframe> 
      </div>
      
    </div><!-- /wrap_content -->  
    </td>
  </tr>
</table><!-- /jer_list_table -->

</div><!-- /wrapGeneral -->
</body>
</html>