<?php

	# VISUALIZADOR HTML
	$html ='';

	// $dato->total_dato 		= $total_dato 			?? null;
	// $dato->total_answer 		= $total_answer 		?? null;
	// $dato->total_closed 		= $total_closed 		?? null;

				// $ar_answer = [];
				// $ar_closed = [];
				// $answer_label ='';
				// $closed_label = '';


	$html .= "<div id=\"get_archive_states\" class=\"get_archive_states\">";
		#
		# CLOSED TO TEXT
		$html .= "<div class=\"total_closed\">";
				//$add_label = label::get_label('average', $lang).': ';
			$html .= ' <span class="css_date label_range">'.$closed_label.':</span> ';
			
		$html .= "</div>";//end sum_dates_total


		$html .= "<span class=\"get_archive_states\">";
			if(isset($total_closed["1"]) && $total_closed["1"]>0 ) {
				$add_label = label::get_label('si', $lang).': ';

				$html .= ' <span class="css_date label_range">'.$add_label.'</span> ';
				$html .= $total_closed["1"];
				$percent = ($total_closed["1"] * 100 ) / $total_dato;
				$html .= ' ('.round($percent, 1).'%)';

			}
			if(isset($total_closed["2"]) && $total_closed["2"]>0) {
				$no_label 	= label::get_label('no', $lang).': ';
				$add_label = (isset($total_closed["1"]) && $total_closed["1"]>0 ) ? " | ".$no_label : $no_label;
				$html .= ' <span class="css_date label_range">'.$add_label.'</span> ';
				$html .= $total_closed["2"];
				$percent = ($total_closed["2"] * 100 ) / $total_dato;
				$html .= ' ('.round($percent, 1).'%)';
			}
			if(isset($count_answer) && $count_answer>0) {
				$add_label = ' | n: ';
				$html .= ' <span class="css_date label_range">'.$add_label.'</span> ';
				$html .= $count_closed;
				$percent = ($count_closed * 100 ) / $total_dato;
				$html .= ' ('.round($percent, 1).'%)';
			}
		$html .= "</span>";//end sum_dates_total

	$html .= "</div>";


	$html .= "<div id=\"get_archive_states\" class=\"get_archive_states\">";

		#
		# ANSWER TO TEXT
		$html .= "<div class=\"total_answer\">";
				//$add_label = label::get_label('average', $lang).': ';
			$html .= ' <span class="css_date label_range">'.$answer_label.':</span> ';
			
		$html .= "</div>";//end sum_dates_total

		$html .= "<span class=\"get_archive_states\">";
			if(isset($total_answer["1"]) && $total_answer["1"]>0 ) {
				// $add_label = label::get_label('max', $lang).'max: ';
				$add_label = 'pos: ';
				$html .= ' <span class="css_date label_range">'.$add_label.'</span> ';
				$html .= $total_answer["1"];
				$percent = ($total_answer["1"] * 100 ) / $total_dato;
				$html .= ' ('.round($percent, 1).'%)';
			}
			if(isset($total_answer["2"]) && $total_answer["2"]>0) {
				//$add_label = label::get_label('min', $lang).'min: ';
				$add_label = (isset($total_answer["1"]) && $total_answer["1"]>0 ) ? ' | neg: ' : ' neg:';
				$html .= ' <span class="css_date label_range">'.$add_label.'</span> ';
				$html .= $total_answer["2"];
				$percent = ($total_answer["2"] * 100 ) / $total_dato;
				$html .= ' ('.round($percent, 1).'%)';
			}
			if(isset($count_answer) && $count_answer>0) {
				$add_label = ' | n: ';
				$html .= ' <span class="css_date label_range">'.$add_label.'</span> ';
				$html .= $count_answer;
				$percent = ($count_answer * 100 ) / $total_dato;
				$html .= ' ('.round($percent, 1).'%)';
			}
		$html .= "</span>";//end sum_dates_total

	$html .= "</div>";


	print $html;
