<?php

	# VISUALIZADOR HTML	
	
	
	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in');

	print "<div class=\"wrap_component css_wrap_score wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-modo=\"{$modo}\"
	data-dato=\"{$valor}\"
	data-textarea_rel_tipo=\"{$textarea_rel_tipo}\"
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	data-related_tipo='{$ar_related_component_tipo_json}'
	>";
	
		
		# ETIQUETA (LABEL)
		$html_label = component_common_draw::draw_label($this);
		
		# CONTENIDO (INPUT)
		$html_content = '';
		switch($permissions) {
				
			case 0 :	
					$html_content .= "";
					break;
							
			case ($permissions>=1) :

				#$html_content .= "<div class=\"vex-tabdiv \" >";
				
				$html_content .= " <canvas class=\"vextab-player\" width=\"\" height=\"112\" id=\"view-0\" style=\"\"></canvas>";						
				#$html_content .= " <textarea class=\"editor\" style=\"width: 750px; height: 200px;\"></textarea>";
				$html_content .= " <canvas id=\"$canvas_id\" class=\"canvas-score\"></canvas>";
				$html_content .= " <div class=\"div_error_score\" id=\"$div_error_id\">Error</div>";

				#$html_content .= "<div class=\"vex-tabdiv\">vex-tabdiv</div>";	
				
				#$html_content .= "</div><!-- /vex-tabdiv -->";
						
					
				if(SHOW_DEBUG) {
					#$html_content .= " <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
				}

				#
				# JS Init component
				$html_content .= '<script>';
				# Init component
				$init_options = new stdClass();
					$init_options->component_name 	= $component_name;
					$init_options->id_wrapper 		= $id_wrapper;
					$init_options->uid 				= $identificador_unico;
				$html_content .= 'component_common.init('.json_encode($init_options).');';
				$html_content .= '</script>';
				break;									
		}



		# Prepare content to show in page
		tools::prepare_content($html_content);
		

		# PRINT HTML
		print $html_label;
		print $html_content;
	
	
	print "</div>"; //wrap

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out');
	
?>