<?php

	# VISUALIZADOR HTML	
	
	
	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in');

	print "<div class=\"wrap_component css_wrap_score wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-modo=\"{$modo}\"
	data-dato=\"{$valor}\"
	data-textarea_rel_tipo=\"{$textarea_rel_tipo}\"
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";
	
		
		# ETIQUETA (LABEL)
		$html_label = component_common_draw::draw_label($this);
		
		# CONTENIDO (INPUT)
		$html_contenido = '';
		switch($permissions) {
				
			case 0 :	
					$html_contenido .= "";
					break;
							
			case ($permissions>=1) :

					#$html_contenido .= "<div class=\"vex-tabdiv \" >";
					
					$html_contenido .= " <canvas class=\"vextab-player\" width=\"\" height=\"112\" id=\"view-0\" style=\"\"></canvas>";						
					#$html_contenido .= " <textarea class=\"editor\" style=\"width: 750px; height: 200px;\"></textarea>";
					$html_contenido .= " <canvas id=\"$canvas_id\" class=\"canvas-score\"></canvas>";
					$html_contenido .= " <div class=\"div_error_score\" id=\"$div_error_id\">Error</div>";

					#$html_contenido .= "<div class=\"vex-tabdiv\">vex-tabdiv</div>";	
					
					#$html_contenido .= "</div><!-- /vex-tabdiv -->";
							
						
					if(SHOW_DEBUG) {
						#$html_contenido .= " <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
					}	
					break;
									
		}


		# INIT : Init text editor 
		$html_contenido .= "<script>component_score.init('$id_wrapper')</script>";


		# Prepare content to show in page
		tools::prepare_content($html_contenido);
		

		# PRINT HTML
		print $html_label;
		print $html_contenido;
	
	
	print "</div>"; //wrap

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out');
	
?>