<?php
	
	# VISUALIZADOR HTML		
	
	
	
	print "<!-- AREA [tipo:$tipo id_matrix:$id] -->";

	print "<div class=\"css_wrap_area\" > ";
	
	
	# ETIQUETA (LABEL)
	$html_label = "<div class=\"css_area_titulo\" > <hr> AREA: ".component_common_draw::draw_label($this)." </div>";	
		
	
	# CONTENIDO (INPUT)
	$html_contenido = "<div class=\"css_area_content\" > areas 2: ";
	
	switch($permissions) {
			
		case 0	:	$html_contenido .= " <span class=\"css_span_dato\"> No access here ! </span>";
					break;
						
		case ($permissions>=1)	:
					
					/*
					# Find last key of current array
					$array_keys = array_keys($ar_children_areas);
					$end_array 	= end($array_keys);							
					$html_selected_area = NULL;
					foreach ($ar_children_areas as $key => $area){
						
						$label	= $area->get_label();
						$tipo	= $area->get_tipo();
						
						if($selected_area == $tipo) {
							$link_style = 'link_navigation_selected';
						}else{
							$link_style = '';
						}
						
						$html_contenido .= " <a href=\"?modo=list&area=$tipo\" class=\"link_navigation link {$link_style}\" >$label +</a> ";					
						
						if($key != $end_array) $html_contenido .= ' | ';	
					} 
			
					$html_contenido .= " $html_area ";					
					*/
					break;			
	}
	
	$html_contenido .= "</div>";
	
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);

	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "</div><!-- /AREA [$tipo] -->"; //wrap
?>