<?php
	
	# VISUALIZADOR HTML	

		
	
	print "\n\n<!-- AREA [tipo:$tipo] -->";

	print "\n<div class=\"css_wrap_area\" > ";
	
	
	# ETIQUETA (LABEL)
	$html_label = "\n<div class=\"css_area_titulo\" > ".component_common_draw::draw_label($this)." </div>";
		
	
	# CONTENIDO (INPUT)
	$html_contenido  ='';
	$html_contenido .= "\n<div class=\"css_area_content area_content_list\" >";
	
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." </span>";
					break;
						
		case ($permissions>=1) :
					/*
					#dump($ar_ts_children ,'$ar_ts_children ');
					foreach ($ar_ts_children as $key => $current_obj) {
						if (is_object($current_obj)) {
							$html_contenido .= $current_obj->get_html();
						}						
					}
					*/
					# Div stats content (loaded by ajax triggered whe button is clicked)
					#$html_contenido .= "<div id=\"stats_info\"><!-- Stats content here --></div>";


					#dump($ar_children_areas ,'$ar_children_areas ');
					$path = DEDALO_LIB_BASE_URL .'/main/';
					$html_contenido .= "\n <blockquote> ";
					foreach ($ar_children_areas as $tipo => $value) {

						$section_name = RecordObj_dd::get_termino_by_tipo($tipo,DEDALO_APPLICATION_LANG,true);
						$modelo_name  = RecordObj_dd::get_modelo_name_by_tipo($tipo,true);
						
						$html_contenido .= menu::create_link($tipo, $section_name, $modelo_name, null);
						$html_contenido .= "<br>";
						/*
						$url  = "{$path}?t=$tipo";						
						if ($modelo_name=='section_tool') {
							#$url .= "&m=$modelo_name";
								dump($section_name, ' var ++ '.to_string($tipo));
						}						
						#$html_contenido .= "<a href=\"$url\">$section_name</a><br>";
						*/
					}
					$html_contenido .= "\n </blockquote> ";
					
					
					break;			
	}
	
	$html_contenido .= "\n</div>";
	
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);

	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div><!-- /AREA [$tipo] -->\n\n"; //wrap
?>