<?php

	# VISUALIZADOR HTML	

	print "<div class=\"wrap_component css_wrap_relation_model tooltip_active\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato='".json_encode($dato)."' ";
	print 'title="'.search_development2::search_options_title( $this->search_operators_info() ).'" ';
	print ">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch($permissions) {
			
		case 0	:	$html_content .= "";
					break;
						
		
		case ($permissions>=1)	:

					# COMPARISON OPERATORS
					$html_content .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);
					
					# SELECT
					$html_content .= "<select class=\"css_relation_model\" name=\"{$search_input_name}\" ";
					$html_content .= "data-tipo=\"{$tipo}\" ";
					$html_content .= "title=\"$html_title\" ";
					$html_content .= ">";

						if(empty($dato)) {
							$checked = 'selected';
						}else{
							$checked = "";
						}
						$html_content .= "<option value=\"\" {$checked}> </option>";
						
						foreach ($ar_list_of_values->result as $value => $rotulo) {
							
							if( $dato == $value) {
								$checked = 'selected';
							}else {
								$checked = "";
							}
							$html_content .= "<option value='$value' {$checked}> {$rotulo}</option>";
						}					
					$html_content .= "</select>";	
					

					# LOGICAL OPERATORS
					$html_content .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);

					if(SHOW_DEBUG===true) {
						$html_content .= "<span class=\"debug_info\">$search_input_name</span>";
					}											
	}
	
	# Prepare content to show in page
	tools::prepare_content($html_content);
	

	# PRINT HTML
	print $html_label;
	print $html_content;	

	
	print "</div>"; //wrap
?>