<?php

	# VISUALIZADOR HTML	

	
	if(isset($_REQUEST[$tipo])) $dato = $_REQUEST[$tipo];
	
	print "\n<!-- COMPONENT_RELATION_MODEL -->";
	print "\n<div class=\"wrap_component css_wrap_relation_model\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "";
					break;
						
		
		case ($permissions>=1)	:

					# COMPARISON OPERATORS
					$html_contenido .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);

					
					# SELECT
					$html_contenido .= "\n <select class=\"css_relation_model\" name=\"{$tipo}\"
					data-tipo=\"{$tipo}\" 
					title=\"$html_title\">";

						if(empty($dato)) {
							$checked = 'selected';
						}else{
							$checked = "";
						}
						$html_contenido .= "\n <option value=\"\" {$checked}> </option>";
						
						foreach ($ar_list_of_values->result as $value => $rotulo) {
							
							if( $dato == $value) {
								$checked = 'selected';
							}else {
								$checked = "";
							}
							$html_contenido .= "\n <option value='$value' {$checked}> {$rotulo}</option>";
						}					
					$html_contenido .= "\n </select>";	
					

					# LOGICAL OPERATORS
					$html_contenido .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);
											
	}
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);
	

	# PRINT HTML
	print $html_label;
	print $html_contenido;	

	
	print "\n</div><!-- /css_wrap_relation_model -->\n\n"; //wrap
?>