<?php

	# VISUALIZADOR HTML	

	
	$var_requested = common::get_request_var($tipo);
	#if(isset($_REQUEST[$tipo])) $dato = $_REQUEST[$tipo];	#var_dump($_REQUEST[$tipo]);
	if(!empty($var_requested)) $dato = $var_requested;
	
	print "\n<!-- COMPONENT_RELATION_MODEL -->";
	print "\n<div class=\"wrap_component css_wrap_relation_model\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch($permissions) {
			
		case 0	:	$html_content .= "";
					break;
						
		
		case ($permissions>=1)	:

					# COMPARISON OPERATORS
					$html_content .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);

					
					# SELECT
					$html_content .= "\n <select class=\"css_relation_model\" name=\"{$search_input_name}\"
					data-tipo=\"{$tipo}\" 
					title=\"$html_title\">";

						if(empty($dato)) {
							$checked = 'selected';
						}else{
							$checked = "";
						}
						$html_content .= "\n <option value=\"\" {$checked}> </option>";
						
						foreach ($ar_list_of_values->result as $value => $rotulo) {
							
							if( $dato == $value) {
								$checked = 'selected';
							}else {
								$checked = "";
							}
							$html_content .= "\n <option value='$value' {$checked}> {$rotulo}</option>";
						}					
					$html_content .= "\n </select>";	
					

					# LOGICAL OPERATORS
					$html_content .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);

					if(SHOW_DEBUG===true) {
						$html_content .= "<span class=\"debug_info\">$search_input_name</span>";
					}
											
	}
	
	# Prepare content to show in page
	tools::prepare_content($html_content);
	

	# PRINT HTML
	print $html_label;
	print $html_content;	

	
	print "\n</div><!-- /css_wrap_relation_model -->\n\n"; //wrap
?>