<?php
	
	# VISUALIZADOR HTML	

		
	# CONTENIDO (INPUT)
	$html_contenido  = "\n<div class=\"css_wrap_rows_paginator text_unselectable\">";
					
		$html_contenido  .= "\n<div class=\"css_rows_paginator_content\">";		
		#if ($total_rows>0) {			
			
			
			# LINKS
			$html_contenido  .= "\n<div class=\"css_rows_paginator_div_links\">";

				#  To first page <<					
				if($page_number>1) {							
					$options->offset  = $first_page_offset;						
					$html_contenido  .= "\n <div onclick='section_list.load_rows(".json_handler::encode($options).",this)' class=\"icon_bs paginator_first_icon link\"></div>";
				}else{
					$html_contenido  .= "\n <div class=\"icon_bs paginator_first_icon paginator_desactive\"></div>";
				}
				
				#  To previous page <
				if($prev_page_offset>=0) {						
					$options->offset  = $prev_page_offset;
					$html_contenido  .= "\n <div onclick='section_list.load_rows(".json_handler::encode($options).",this)' class=\"icon_bs paginator_prev_icon link\"></div>";
				}else{
					$html_contenido  .= "\n <div class=\"icon_bs paginator_prev_icon paginator_desactive\"></div>";
				}

				#  To next page >
				if($next_page_offset<$total_rows) {							
					$options->offset  = $next_page_offset;
						#dump($options,"options en next button");
					$html_contenido  .= "\n <div onclick='section_list.load_rows(".json_handler::encode($options).",this)' class=\"icon_bs paginator_next_icon link\"></div>";
				}else{
					$html_contenido  .= "\n <div class=\"icon_bs paginator_next_icon paginator_desactive\"></div>";
				}
			
				#  To last page >>
				if($page_number<$total_pages) {
					$options->offset  = $last_page_offset;
					$html_contenido  .= "\n <div onclick='section_list.load_rows(".json_handler::encode($options).",this)' class=\"icon_bs paginator_last_icon link\"></div>";
				}else{
					$html_contenido  .= "\n <div class=\"icon_bs paginator_last_icon paginator_desactive\"></div>";
				}		
			
			$html_contenido  .= "\n </div>";


			# INFO
			$html_contenido  .= "\n<div class=\"css_rows_paginator_info\">Page $page_number of $total_pages. Displayed records from $page_row_begin to $page_row_end of $total_rows</div>";
			

		#}#end if ($total_rows>0)			
		$html_contenido  .= "\n</div><!-- /css_rows_paginator_content -->";	
	
	$html_contenido .= "\n</div><!-- /css_wrap_rows_paginator -->";
	
	# PRINT HTML
	print $html_contenido;
	

?>