<?php

	$html = '';

	// 0 dedalo_install_status. If already installed, stop here
		if (DEDALO_INSTALL_STATUS==='installed') {
			$html .= '<section>';
			$html .= '<h3 class="">Install status</h3>';
			$html .= '<div class="description"></div>';
			$html .= '<h3 class="ok">This system is already installed</h3>';
			$html .= '<section>';
			$html .= '<input type="button" id="button_install" class="btn btn-primary" value=" ENTER TO DEDALO " onclick="window.location.href=\'../main\';" />';
			$html .= '</section>';
			$html .= '</section>';
			echo $html;
			return;
		}

	// Instalation help
		$html .= '<section class="instalation_help">';
		$html .= '<h3 class="">Instalation help</h3>';
		$html .= '<div class="description"><img src="https://dedalo.dev/tpl/assets/img/logos/logo_dedalo.svg" height="16px"/> Instalation info: <a href="https://dedalo.dev/v5" target="_blank">https://dedalo.dev/v5</a></div>';
		$html .= '<div class="description"><img src="https://dedalo.dev/tpl/assets/img/logos/logo_dedalo.svg" height="16px"/> Configuration info: <a href="https://dedalo.dev/v5_config" target="_blank">https://dedalo.dev/v5_config</a></div>';
		$html .= '</section>';

	// 0 Configuration test
		// init test
			require(DEDALO_LIB_BASE_PATH.'/config/dd_init_test.php');
			if ($init_response->result===false) {
				trigger_error(__METHOD__." Configuration test error: ".$init_response->msg);
			}
		$html .= '<section>';
		$html .= '<h3 class="">Configuration test</h3>';
		if ($init_response->result===false) {
			$html .= '<h2 class="warning">Configuration test contains warnings!</h2>';
			$errors = json_encode($init_response, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES );
			$html .= '<pre>'. str_replace('\n', ' ', $errors).'</pre>';
		}else{
			if (empty($init_response->warnings)) {
				$html .= '<div class="ok">Configuration test passed for entity: <b>'.DEDALO_ENTITY.'</b></div>';
			}else{
				$html .= '<div class="">Configuration test passed with some errors for entity: <b>'.DEDALO_ENTITY.'</b></div>';
				$html .= '<ul class="warning_list warning">';
				foreach ($init_response->warnings as $key => $msg) {
					$html .= '<li class="description">'. $msg.'</li>';
				}
				$html .= '</ul>';
			}
		}
		$html .= '</section>';

	// 1 Install Dédalo DB
		$html .= '<section>';
		$html .= '<h3 class="">1. Install Dédalo DDBB</h3>';
		if ($db_is_imported===false) {
			$html .= '<div class="description">Install DDBB source file: '.$install_db_file.'</div>';
			if (!file_exists($install_db_file)) {
				$html .= '<h2 class="error">Database file not found! Please verify that the installation file exists in: '.$install_db_file.'</h2>';
				$html .= '</section>';
				echo $html;
				return;
			}
			$html .= '<div class="description">DB Config:</div>';
			$html .= '<ul class="ul_list">';
			foreach ($db_config as $key => $value) {
				$html .= '<li>'.$key.' : '.$value.'</li>';
			}
			$html .= '</ul>';
			try {
				$conn = DBi::_getConnection();
			}catch (Exception $e) {
				$html .= '<h2 class="error">Database connection error!</h2>';
				$html .= '</section>';
				echo $html;
				return;
			}
			$html .= '</section>';

			// button INSTALL DATABASE FROM FILE
			$html .= '<section>';
			$html .= '<input type="button" id="button_install" class="btn btn-primary" value=" INSTALL DATABASE FROM FILE " onclick="install.install_db_from_default_file(this)" />';
			$html .= '</section>';

			// logout user
				if (login::is_logged()===true) {
					unset($_SESSION['dedalo4']);
				}

			echo $html;
			return;

		}else{

			$html .= '<div class="ok">Database <b>'.DEDALO_DATABASE_CONN.'</b> is ready</div>';
		}
		$html .= '</section>';


	// 2 login
		$html .= '<section>';
		$html .= '<h3 class="">2. Set root password / login</h3>';
		if (login::is_logged()!==true) {
			$html .= '<div class="warning">You must be logged before continue.</div>';
			$html .= '<iframe id="iframe_login" src="../main">';
			$html .= '</iframe>';
			$html .= '<section>';
			$html .= '
				<script>
					window.document.addEventListener(\'login_success\', handleEvent, false)
					function handleEvent(e) {
						// login response
						if(e.detail.result===true) {
							// document.getElementById("iframe_login").remove()
							location.reload()
						}
					}
				</script>
			';
			$html .= '</section>';
			$html .= '</section>';
			echo $html;
			return;
		}else{
			$html .= '<div class="ok">User is logged as <b>'.navigator::get_user_id().'</b></div>';
		}
		$html .= '</section>';


	// 3 Install / activate hierarchies list
		$html .= '<section>';
		$html .= '<h3 class="">3. Install/activate selected hierarchies</h3>';
		if (DEDALO_INSTALL_STATUS!=='installed') {

			$html .= '<div class="description">It will be displayed in the thesaurus. Keep in mind that large countries can consume a lot of resources. Don\'t load unnecessary countries. You can always load more countries later.</div>';
			$html .= '<div class="description">Source files dir: '.$hierarchy_files_path.'</div>';
			$html .= '<ul id="hierarchies_list" class="ul_list">';
			foreach ($hierarchies->result as $key => $item) {
				// skip model
				if ($item->type==='model') {
					continue;
				}
				$checked = in_array($item->tld, $install_checked_default)
					? 'checked="checked"'
					: '';
				$html .= '<li><label><input type="checkbox" name="hierarchies" value="'.$item->tld.'" '.$checked.'/>'.$item->label.'</label></li>';
			}
			$html .= '</ul>';

			// button INSTALL HIERARCHIES
			$html .= '<section>';
			$html .= '<input type="button" id="button_install" class="btn btn-primary" value=" INSTALL HIERARCHIES " onclick="install.install_hierarchies(this)" />';
			$html .= '</section>';

			$html .= '
				<script>
					install.init({
						hierarchies_list : document.getElementById(\'hierarchies_list\')
					})
				</script>
			';
		}else{

			$html .= '<div class="ok">Dédalo hierarchies are ready</div>';
		}
		$html .= '</section>';


echo $html;


