<?php

	# VISUALIZADOR HTML	
		
	# BUTTON TOOL
	$html_tool    = "<!-- TOOL POSTERFRAME [tipo:$tipo parent:$parent] -->";
	$html_tool   .= "<div class=\"tool_inspector_div\">";

	$btn_title	= label::get_label('abrir').' '.label::get_label('herramienta');

	$html_tool .= "<div class=\"icon_bs tool_posterframe_icon link\" ";
	$html_tool .= "data-tipo=\"{$tipo}\" data-parent=\"{$parent}\" ";
	$html_tool .= "title=\"$btn_title\" ";
	$html_tool .= "onclick=\"tool_common.open_tool_posterframe(this)\" ";
	$html_tool .= "> </div>";


	$html_tool   .= label::get_label('tool_posterframe');	#" Posterframe";	
		

	$html_tool   .= "</div>";#/tool_inspector_div

	# PRINT HTML
	print $html_tool;
	
?>