<?php

	# VISUALIZADOR HTML	
		
	# SELECTOR SOURCE LANG
	$html_selector    	= '';

	
		
		$html_selector .= "\n<!-- TOOL LANG SELECTOR SOURCE LANG -->";
		$html_selector .= "\n <span class=\"rotulo_tool_lang_selector\">".label::get_label('idioma_de_origen').":</span> ";
		$html_selector .= "\n <select class=\"tool_lang_selector_source css_select\"
		data-tipo=\"{$tipo}\"
		data-parent=\"{$parent}\"
		data-section_tipo=\"{$section_tipo}\"
		data-tool_name=\"{$tool_name}\"
		data-tool_locator=\"{$tool_locator}\"
		onchange=\"tool_lang.load_source_component(this)\"
		> ";
					
				if(empty($lang)) {
					$checked = 'selected';
				}else{
					$checked = "";
				}
				$html_selector .= "\n <option value=\"\" {$checked}> </option>";
				
				if (is_array ($ar_source_langs)) foreach ($ar_source_langs as $current_source_lang => $current_source_lang_name) {
					
					if( $lang == $current_source_lang) {
						$checked = 'selected';
					}else {
						$checked = "";
					}
					$html_selector .= "\n <option value=\"{$current_source_lang}\" {$checked}>$current_source_lang_name</option>";							
				}

		$html_selector .= "\n </select>";	


	

	
	# PRINT HTML
	print $html_selector;
	
?>