<?php

	# VISUALIZADOR HTML	
		
	# SELECTOR TARGET LANG
	$html_selector = '';

	switch ($modo) {
		case 'selector_source':
			
			break;
		
		case 'selector_target':
			
			break;
	}
	#dump($desired_lang, ' desired_lang ++ '.to_string());

	$select_id = 'tool_lang_'.$modo;
	$css_class = 'tool_lang_'.$modo;
		
	$html_selector .= "<!-- TOOL LANG SELECTOR LANG -->";
	#$html_selector .= " <span class=\"rotulo_tool_lang_selector\">".label::get_label('idioma_de_destino').":</span> ";
	$html_selector .= "<select class=\"{$css_class} css_select\" ";
	$html_selector .= "id=\"{$select_id}\" ";
	$html_selector .= "data-tipo=\"{$tipo}\" ";
	$html_selector .= "data-parent=\"{$parent}\" ";
	$html_selector .= "data-section_tipo=\"{$section_tipo}\" ";
	$html_selector .= "data-tool_name=\"{$tool_name}\" ";
	$html_selector .= "data-tool_locator=\"{$tool_locator}\" ";
	$html_selector .= "data-role=\"{$modo}\" ";
	$html_selector .= "onchange=\"tool_lang.render_component(this)\" ";
	$html_selector .= ">";
			
		# Empty option					
		$html_selector .= "<option></option>";
		
		# Value option
		foreach ((array)$ar_select_langs as $current_lang => $current_lang_name) {

			if ($current_lang===DEDALO_DATA_NOLAN) {
				$current_lang_name = DEDALO_DATA_NOLAN;
			}
			
			$selected 		= ($desired_lang === $current_lang) ? ' selected' : '';
			$html_selector .= "<option value='{$current_lang}'{$selected}>$current_lang_name</option>";
		}

	$html_selector .= "</select>";
	
	$html_selector .= "<script>";
	$html_selector .= "tool_lang.".$modo."_selected_lang = '".$desired_lang."';"; // tool_lang.selector_source_selected_lang
	$html_selector .= "</script>";
	
	# PRINT HTML
	print $html_selector;	
?>