<?php

	# VISUALIZADOR HTML	
		
	# BUTTON TOOL
	$html_tool    = '';
	#$html_tool   .= "\n<!-- TOOL LANG [tipo:$tipo parent:$parent] -->";
	#$html_tool   .= "<div class=\"tool_inspector_div\">";

	$title	  	  = label::get_label('abrir').' '.label::get_label('herramienta');
	/*
	$html_tool   .= "\n<div class=\"icon_bs tool_lang_icon link\"
						data-tipo=\"{$tipo}\"
						data-parent=\"{$parent}\"
						data-lang=\"{$lang}\"
						data-tab_id=\"img_lang_{$tipo}_{$parent}\"
						title=\"$title\"
						onclick=\"tool_common.open_tool_lang(this)\"
						></div>";
	*/
	$html_tool .= "<a href=\"javascript:void(0);\" class=\"id_column_buttons button_translation link\" title=\"$title\" onclick=\"tool_common.open_tool_lang(this)\"
	data-tipo=\"{$tipo}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-lang=\"{$lang}\"
	data-tab_id=\"img_lang_{$tipo}_{$parent}\"
	>";
		$html_tool .= "<span class='section_id_number'>";
		$html_tool .= " $section_id ";
		$html_tool .= "</span>";
	$html_tool .= "</a>";


	#$html_tool   .= label::get_label('tool_lang');	#" Lang";

	#$html_tool   .= "</div>";#/tool_inspector_div
	
	# PRINT HTML
	print $html_tool;
	
?>