<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	
	print "\n<!-- COMPONENT_LAYOUT [tipo:$tipo section_id_matrix:$parent] $label -->";
	print "\n<div class=\"css_wrap_html_text wrap_component\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\" data-section_tipo=\"{$section_tipo}\" data-parent=\"{$parent}\" data-lang=\"{$lang}\" data-modo=\"{$modo}\" data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}' >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {	
			
		case 0	:	$html_contenido .= "";	
					break;
						
		case 1	: 	
					foreach ($dato as $key => $value) {
						$html_contenido .= "\n <span class=\"css_span_dato \">".htmlentities($value)."</span>";
					}
					break;	
						
		
		case ($permissions>=2) :

					#dump($dato, ' $dato');
					if ( empty(get_object_vars($dato) ) ) {
						$dato = new stdClass();
							$dato->edit = '';
							#dump($dato, ' dato');								
					}
					

					foreach ($dato as $key => $value) {
						
						$html_contenido .= "<div class=\"layout_key_label\">$key</div>";
						
						##
						# Text area		
						$html_contenido .= "\n <textarea class=\"css_input_text_layout\" 
						id=\"{$identificador_unico}_$key\" 
						name=\"{$input_name}\" 
						data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-section_tipo=\"{$section_tipo}\" data-parent=\"{$parent}\" data-key_name=\"{$key}\"
						data-context_name=\"$context_name\"
						title=\"$html_title\">$value</textarea>";
					}				
					
					
					if (SHOW_DEBUG) {
					$html_contenido .= "<span class=\"debug_info\"> $identificador_unico</span>";
					}			

		
					if($permissions==3) {
						#$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$tipo}\" >{$debugger}</span>";
					}	
					
					
					break;							
	}

	# INIT : Init text editor	
	#$html_contenido .= "\n<script>component_html_text_editor.init('$identificador_unico','$modo','$propiedades_json');</script>";
	
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);

	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_html_text  $label -->\n\n"; //wrap	
?>

