<?php declare(strict_types=1);
/**
 * GENERATE_CONFIG
 * Generates the Dédalo .env file and supporting config for an unattended
 * local install. Used by the "Dédalo Desktop" launcher on first run.
 *
 * The unified config/bootstrap.php is committed as-is and reads all real values
 * from .env files via env_loader. This script only needs to produce:
 *  - .env               (host-specific environment variables)
 *  - config_core.php    (DEDALO_INSTALL_STATUS marker)
 *  - config_areas.php   (copied verbatim from sample.config_areas.php)
 *
 * No config.php or config_db.php generation is needed — those are now unified
 * in the committed config/bootstrap.php which uses env_loader.
 *
 * Parameters are read from environment variables (all optional except where noted):
 *  DD_ROOT           absolute path to the Dédalo root (default: dirname,3 of this file)
 *  DD_PRIVATE_DIR    absolute path to the private dir (default: dirname,3 of this file + '/../private')
 *  DD_DB_HOST        default 127.0.0.1
 *  DD_DB_PORT        default 5432
 *  DD_DB_NAME        default dedalo
 *  DD_DB_USER        default dedalo
 *  DD_DB_PASS        REQUIRED (no sample-default fallback)
 *  DD_ENTITY         default dedalo_local
 *  DD_SALT           default: random 32-hex
 *  DD_INFO           default: "Dédalo local <timestamp>"
 *  DD_INSTALL_STATUS "installed" | "false"  (default installed, for seeded DB)
 *  DD_FORCE          "1" to overwrite existing files
 *  DD_SESSIONS_PATH  absolute path for sessions dir (default: skip)
 *  DD_BACKUP_PATH    absolute path for backups dir (default: skip)
 *  DD_BINARY_BASE_PATH  default /usr/bin
 *
 * @package Dedalo
 * @subpackage Desktop
 */

function env_or(string $key, ?string $default) : ?string {
	$v = getenv($key);
	return ($v === false || $v === '') ? $default : $v;
}

$dd_root = env_or('DD_ROOT', dirname(__DIR__, 2));
$config_dir = $dd_root . '/config';
$private_dir = env_or('DD_PRIVATE_DIR', dirname($dd_root) . '/private');

if (!is_dir($config_dir)) {
	fwrite(STDERR, "Config dir not found: $config_dir\n");
	exit(1);
}
if (!is_dir($private_dir)) {
	fwrite(STDERR, "Private dir not found: $private_dir\n");
	exit(1);
}

$db_host	= env_or('DD_DB_HOST', '127.0.0.1');
$db_port	= env_or('DD_DB_PORT', '5432');
$db_name	= env_or('DD_DB_NAME', 'dedalo');
$db_user	= env_or('DD_DB_USER', 'dedalo');
$db_pass	= env_or('DD_DB_PASS', null);
$entity		= env_or('DD_ENTITY', 'dedalo_local');
$salt		= env_or('DD_SALT', bin2hex(random_bytes(16)));
$info		= env_or('DD_INFO', 'Dédalo local ' . date('Y-m-d H:i:s'));
$status		= env_or('DD_INSTALL_STATUS', 'installed');
$force		= env_or('DD_FORCE', '0') === '1';
$binary_base= env_or('DD_BINARY_BASE_PATH', '/usr/bin');

if ($db_pass === null) {
	fwrite(STDERR, "DD_DB_PASS is required\n");
	exit(1);
}

/**
 * Write a file unless it exists and $force is false.
 */
function put(string $file, string $contents, bool $force) : void {
	if (file_exists($file) && !$force) {
		fwrite(STDOUT, "skip (exists): " . basename($file) . "\n");
		return;
	}
	if (file_put_contents($file, $contents) === false) {
		fwrite(STDERR, "Failed to write $file\n");
		exit(1);
	}
	fwrite(STDOUT, "wrote: " . basename($file) . "\n");
}

// ---- .env : environment variables for the local install ----
$env  = "# Generated by Dédalo Desktop on " . date('c') . "\n";
$env .= "# Local install environment configuration\n";
$env .= "# Sections mirror bootstrap.php numbering for easy cross-reference.\n\n";

$env .= "# ── 2. Host + protocol ─────────────────────────────────────────────────────────\n";
$env .= "# DEDALO_HOST=localhost\n\n";

$env .= "# ── 4. Environmental scalar constants ──────────────────────────────────────────\n\n";
$env .= "# -- secrets\n";
$env .= "DEDALO_SALT_STRING=" . $salt . "\n\n";
$env .= "# -- locale\n";
$env .= "# DEDALO_TIMEZONE=Europe/Madrid\n# DEDALO_LOCALE=es-ES\n# DEDALO_DATE_ORDER=dmy\n\n";
$env .= "# -- entity\n";
$env .= "DEDALO_ENTITY=" . $entity . "\n";
$env .= "DEDALO_ENTITY_LABEL=" . ucfirst(str_replace('_', ' ', $entity)) . "\n";
$env .= "DEDALO_ENTITY_ID=0\n\n";
$env .= "# -- production / development\n";
$env .= "IS_PRODUCTION=false\nDEVELOPMENT_SERVER=true\n\n";
$env .= "# -- binary base path\n";
$env .= "DEDALO_BINARY_BASE_PATH=" . $binary_base . "\n\n";

$env .= "# ── 6. Sessions ────────────────────────────────────────────────────────────────\n";
$env .= "DEDALO_SESSION_HANDLER=files\n";
$sessions_path = env_or('DD_SESSIONS_PATH', null);
if ($sessions_path !== null) {
	$env .= "DEDALO_SESSION_SAVE_PATH=" . $sessions_path . "\n";
}
$env .= "\n";

$env .= "# ── 7. Database constants ──────────────────────────────────────────────────────\n\n";
$env .= "# -- PostgreSQL\n";
$env .= "DEDALO_HOSTNAME_CONN=" . $db_host . "\n";
$env .= "DEDALO_DB_PORT_CONN=" . $db_port . "\n";
$env .= "DEDALO_DATABASE_CONN=" . $db_name . "\n";
$env .= "DEDALO_USERNAME_CONN=" . $db_user . "\n";
$env .= "DEDALO_PASSWORD_CONN=" . $db_pass . "\n";
$env .= "DB_BIN_PATH=" . env_or('DD_DB_BIN', $binary_base . '/') . "\n";
$env .= "PHP_BIN_PATH=" . env_or('DD_PHP_BIN', $binary_base . '/php') . "\n";
$env .= "SLOW_QUERY_MS=6000\nDEDALO_DB_MANAGEMENT=true\n# PERSISTENT_CONNECTION=false\n";
$env .= "DEDALO_INFORMATION=" . $info . "\n";
$env .= "DEDALO_INFO_KEY=" . $entity . '_' . substr($salt, 0, 8) . "\n\n";
$env .= "# -- MySQL (diffusion)\n";
$env .= "MYSQL_DEDALO_HOSTNAME_CONN=localhost\nMYSQL_DEDALO_USERNAME_CONN=unused\n";
$env .= "MYSQL_DEDALO_PASSWORD_CONN=unused\nMYSQL_DEDALO_DATABASE_CONN=web_dedalo\n";
$env .= "MYSQL_DEDALO_DB_PORT_CONN=\nMYSQL_DEDALO_SOCKET_CONN=/tmp/mysql.sock\n";
$env .= "MYSQL_DB_BIN_PATH=" . $binary_base . '/' . "\n\n";

$env .= "# ── 8. Cache + debug ──────────────────────────────────────────────────────────\n";
$env .= "# DEDALO_CACHE_PATH=\nSHOW_DEBUG=true\n# SHOW_DEVELOPER=false\n\n";

$env .= "# ── 10. Backup paths ──────────────────────────────────────────────────────────\n";
$backup_path = env_or('DD_BACKUP_PATH', null);
if ($backup_path !== null) {
	$env .= "DEDALO_BACKUP_PATH=" . $backup_path . "\n";
} else {
	$env .= "# DEDALO_BACKUP_PATH=/var/backups/dedalo\n";
}
$env .= "# DEDALO_BACKUP_ON_LOGIN=true\n# DEDALO_BACKUP_TIME_RANGE=8\n";
$env .= "# DEDALO_BACKUP_PATH_TEMP=/var/backups/dedalo/temp\n";
$env .= "# DEDALO_BACKUP_PATH_DB=/var/backups/dedalo/db\n";
$env .= "# DEDALO_BACKUP_PATH_ONTOLOGY=/var/backups/dedalo/ontology\n\n";

$env .= "# ── 13. Lang config ───────────────────────────────────────────────────────────\n";
$env .= "DEDALO_APPLICATION_LANGS={\"lg-eng\":\"English\",\"lg-spa\":\"Castellano\"}\n";
$env .= "DEDALO_APPLICATION_LANGS_DEFAULT=lg-eng\nDEDALO_STRUCTURE_LANG=lg-spa\n";
$env .= "# DEDALO_DATA_LANG_DEFAULT=lg-eng\n# DEDALO_DATA_LANG_SELECTOR=true\n";
$env .= "# DEDALO_DATA_LANG_SYNC=false\n# DEDALO_DATA_NOLAN=lg-nolan\n";
$env .= "DEDALO_PROJECTS_DEFAULT_LANGS=[\"lg-eng\",\"lg-spa\"]\n";
$env .= "DEDALO_DIFFUSION_LANGS=[\"lg-eng\",\"lg-spa\"]\n\n";

$env .= "# ── 14. Default config values ─────────────────────────────────────────────────\n";
$env .= "DEDALO_PREFIX_TIPOS=[\"dd\",\"rsc\",\"ontology\",\"hierarchy\",\"lg\",\"oh\",\"ich\",\"nexus\"]\n";
$env .= "MAIN_FALLBACK_SECTION=oh1\n";
$env .= "# NUMERICAL_MATRIX_VALUE_YES=1\n# NUMERICAL_MATRIX_VALUE_NO=2\n";
$env .= "# DEDALO_MAX_ROWS_PER_PAGE=10\n# DEDALO_PROFILE_DEFAULT=2\n# DEDALO_DEFAULT_PROJECT=1\n\n";

$env .= "# ── 15. Media config ──────────────────────────────────────────────────────────\n\n";
$env .= "# -- media base paths\n# DEDALO_MEDIA_DIR_NAME=media\n\n";
$env .= "# -- thumb common\n";
$env .= "# DEDALO_THUMB_EXTENSION=jpg\n# DEDALO_QUALITY_THUMB=thumb\n";
$env .= "# DEDALO_IMAGE_THUMB_WIDTH=222\n# DEDALO_IMAGE_THUMB_HEIGHT=148\n\n";
$env .= "# -- av media\n";
$env .= "# DEDALO_AV_FOLDER=/av\n# DEDALO_AV_EXTENSION=mp4\n";
$env .= "# DEDALO_AV_EXTENSIONS_SUPPORTED=[\"mp4\",\"wave\",\"wav\",\"aiff\",\"aif\",\"mp3\",\"mov\",\"avi\",\"mpg\",\"mpeg\",\"vob\",\"zip\",\"flv\"]\n";
$env .= "# DEDALO_AV_MIME_TYPE=video/mp4\n# DEDALO_AV_TYPE=h264/AAC\n";
$env .= "# DEDALO_AV_QUALITY_ORIGINAL=original\n# DEDALO_AV_QUALITY_DEFAULT=404\n";
$env .= "# DEDALO_AV_AR_QUALITY=[\"original\",\"1080\",\"720\",\"576\",\"404\",\"240\",\"audio\"]\n";
$env .= "# DEDALO_AV_POSTERFRAME_EXTENSION=jpg\n# DEDALO_AV_STREAMER=\n";
$env .= "# DEDALO_SUBTITLES_FOLDER=/subtitles\n# DEDALO_AV_SUBTITLES_EXTENSION=vtt\n";
$env .= "# DEDALO_AV_RECOMPRESS_ALL=1\n\n";
$env .= "# -- image media\n";
$env .= "# DEDALO_IMAGE_FOLDER=/image\n# DEDALO_IMAGE_EXTENSION=jpg\n";
$env .= "# DEDALO_IMAGE_MIME_TYPE=image/jpeg\n# DEDALO_IMAGE_TYPE=jpeg\n";
$env .= "# DEDALO_IMAGE_EXTENSIONS_SUPPORTED=[\"jpg\",\"jpeg\",\"png\",\"tif\",\"tiff\",\"bmp\",\"psd\",\"raw\",\"webp\",\"heic\",\"avif\"]\n";
$env .= "# DEDALO_IMAGE_ALTERNATIVE_EXTENSIONS=[]\n";
$env .= "# DEDALO_IMAGE_QUALITY_ORIGINAL=original\n# DEDALO_IMAGE_QUALITY_RETOUCHED=modified\n";
$env .= "# DEDALO_IMAGE_QUALITY_DEFAULT=1.5MB\n";
$env .= "# DEDALO_IMAGE_AR_QUALITY=[\"original\",\"modified\",\"100MB\",\"25MB\",\"6MB\",\"1.5MB\",\"thumb\"]\n";
$env .= "# DEDALO_IMAGE_PRINT_DPI=150\n";
$env .= "# MAGICK_CONFIG={\"remove_layer_0\":false,\"is_opaque\":null}\n";
$env .= "# COLOR_PROFILES_PATH=\n# DEDALO_IMAGE_WEB_FOLDER=/web\n\n";
$env .= "# -- pdf media\n";
$env .= "# DEDALO_PDF_FOLDER=/pdf\n# DEDALO_PDF_EXTENSION=pdf\n";
$env .= "# DEDALO_PDF_EXTENSIONS_SUPPORTED=[\"pdf\",\"doc\",\"pages\",\"odt\",\"ods\",\"rtf\",\"ppt\",\"pages\"]\n";
$env .= "# DEDALO_PDF_ALTERNATIVE_EXTENSIONS=[\"jpg\"]\n";
$env .= "# DEDALO_PDF_MIME_TYPE=application/pdf\n# DEDALO_PDF_TYPE=pdf\n";
$env .= "# DEDALO_PDF_QUALITY_ORIGINAL=original\n# DEDALO_PDF_QUALITY_DEFAULT=web\n";
$env .= "# DEDALO_PDF_AR_QUALITY=[\"original\",\"web\"]\n\n";
$env .= "# -- 3d media\n";
$env .= "# DEDALO_3D_FOLDER=/3d\n# DEDALO_3D_EXTENSION=glb\n";
$env .= "# DEDALO_3D_EXTENSIONS_SUPPORTED=[\"glb\",\"gltf\",\"obj\",\"fbx\",\"dae\",\"zip\"]\n";
$env .= "# DEDALO_3D_MIME_TYPE=model/gltf-binary\n";
$env .= "# DEDALO_3D_QUALITY_ORIGINAL=original\n# DEDALO_3D_QUALITY_DEFAULT=web\n";
$env .= "# DEDALO_3D_THUMB_DEFAULT=thumb\n";
$env .= "# DEDALO_3D_AR_QUALITY=[\"original\",\"web\"]\n\n";
$env .= "# -- svg media\n";
$env .= "# DEDALO_SVG_FOLDER=/svg\n# DEDALO_SVG_EXTENSION=svg\n";
$env .= "# DEDALO_SVG_EXTENSIONS_SUPPORTED=[\"svg\"]\n";
$env .= "# DEDALO_SVG_MIME_TYPE=image/svg+xml\n";
$env .= "# DEDALO_SVG_QUALITY_ORIGINAL=original\n# DEDALO_SVG_QUALITY_DEFAULT=web\n";
$env .= "# DEDALO_SVG_AR_QUALITY=[\"original\",\"web\"]\n\n";
$env .= "# -- html files\n";
$env .= "# DEDALO_HTML_FILES_FOLDER=/html_files\n# DEDALO_HTML_FILES_EXTENSION=html\n\n";

$env .= "# ── 16. Upload config ───────────────────────────────────────────────────────────\n";
$env .= "# DEDALO_UPLOAD_SERVICE_CHUNK_FILES=4\n# DEDALO_UPLOAD_SERVICE_MAX_CONCURRENT=50\n\n";

$env .= "# ── 17. Geo + entity menu + misc ──────────────────────────────────────────────\n";
$env .= "# DEDALO_GEO_PROVIDER=VARIOUS\n";
$env .= "DEDALO_ENTITY_MEDIA_AREA_TIPO=\nDEDALO_ENTITY_MENU_SKIP_TIPOS=[]\n";
$env .= "# DEDALO_TEST_INSTALL=true\n# DEDALO_LOCK_COMPONENTS=true\n";
$env .= "# DEDALO_PROTECT_MEDIA_FILES=false\n# DEDALO_NOTIFICATIONS=false\n";
$env .= "# DEDALO_AR_EXCLUDE_COMPONENTS=[]\n";
$env .= "# DEDALO_FILTER_USER_RECORDS_BY_ID=false\n# ENCRYPTION_MODE=openssl\n\n";

$env .= "# ── 18. Diffusion config ────────────────────────────────────────────────────────\n";
$env .= "DEDALO_DIFFUSION_DOMAIN=default\nDEDALO_DIFFUSION_RESOLVE_LEVELS=2\n";
$env .= "DEDALO_PUBLICATION_CLEAN_URL=false\n# DIFFUSION_CUSTOM=false\n";
$env .= "API_WEB_USER_CODE_MULTIPLE=[{\"db_name\":\"\",\"code\":\"\",\"api_ui\":null}]\n";
$env .= "EXCLUDE_DIFFUSION_ELEMENTS=[]\n\n";

$env .= "# ── 19. Structure / ontology / code servers ────────────────────────────────────\n";
$env .= "# STRUCTURE_FROM_SERVER=true\n# IS_AN_ONTOLOGY_SERVER=false\n";
$env .= "# ONTOLOGY_SERVERS=[{\"name\":\"Official Dédalo Ontology server\",\"url\":\"https://master.dedalo.dev/dedalo/core/api/v1/json/\",\"code\":\"x3a0B4Y020Eg9w\"}]\n";
$env .= "# IS_A_CODE_SERVER=false\n";
$env .= "# CODE_SERVERS=[{\"name\":\"Official Dédalo code server\",\"url\":\"https://master.dedalo.dev/dedalo/core/api/v1/json/\",\"code\":\"x3a0B4Y020Eg9w\"}]\n";
$env .= "# DEDALO_SOURCE_VERSION_LOCAL_DIR=/tmp/\n\n";

$env .= "# ── 20. IP API ──────────────────────────────────────────────────────────────────\n";
$env .= "# IP_API={\"url\":\"https://api.country.is/$ip\",\"href\":\"https://ip-api.com/#$ip\",\"country_code\":\"country\"}\n\n";

$env .= "# ── 21. CORS + MCP + maintenance ────────────────────────────────────────────────\n";
$env .= "# DEDALO_CORS={\"allowed_origins\":[\"*\"],\"allowed_methods\":[\"GET\",\"POST\",\"PUT\",\"OPTIONS\"],\"allowed_headers\":[\"Content-Type\",\"Content-Range\",\"Authorization\",\"X-Requested-With\"],\"max_age\":86400}\n";
$env .= "# DEDALO_MCP_PROXY_URL=http://localhost:3001\n# DEDALO_MAINTENANCE_MODE=false\n\n";

$env .= "# ── 22. Mailer config ─────────────────────────────────────────────────────────────\n";
$env .= "MAILER_HOST=\nMAILER_USERNAME=\nMAILER_PASSWORD=\n";
$env .= "MAILER_SMTP_SECURE=tls\nMAILER_PORT=587\nMAILER_FROM=\nMAILER_REPLY=\n";
$env .= "# MAILER_SMTP_AUTH=true\n\n";

$env .= "# ── 23. Optional configs (JSON-encoded, leave commented to skip) ────────────────\n";
$env .= "# SAML_CONFIG={\"active\":true,\"url\":\"/dedalo/core/login/saml\",\"logout_url\":\"https://idp.example.com/saml\",\"debug\":true,\"code\":\"urn:oid:1.3.6.1.4.1.5923.1.1.1.6\",\"idp_ip\":[\"127.0.0.1\"]}\n";
$env .= "# SOCRATA_CONFIG={\"app_token\":\"\",\"socrata_user\":\"\",\"socrata_password\":\"\",\"server\":\"\",\"mode\":\"pre\"}\n";
$env .= "# GEONAMES_ACCOUNT_USERNAME=yoadev\n# INIT_COOKIE_AUTH_ADDONS=[]\n";
$env .= "# CONFIG_DEFAULT_FILE_PATH=\n# EXPORT_HIERARCHY_PATH=\n";
$env .= "# SERVER_PROXY=\n# PDF_OCR_ENGINE=\n\n";

put($private_dir . '/.env', $env, $force);

// ---- config_areas.php : copy sample verbatim ----
$sample_areas = file_get_contents($config_dir . '/sample.config_areas.php');
if ($sample_areas !== false) {
	put($config_dir . '/config_areas.php', $sample_areas, $force);
}

// ---- config_core.php : install status marker ----
$status_literal = ($status === 'installed') ? "'installed'" : 'false';
$core = "<?php\n"
	. "// Generated by Dédalo Desktop. Managed by the install/update system.\n"
	. "define('DEDALO_INSTALL_STATUS', " . $status_literal . ");\n";
put($config_dir . '/config_core.php', $core, $force);

fwrite(STDOUT, "Config generation done.\n");
