/**
 * THE CONFIGURATION HAS ONE RESOLUTION PATH — this is the gate that keeps it one.
 *
 * `src/config.ts` used to be `envSchema.safeParse(process.env)`. That is not a path, it is
 * whatever the ambient environment happened to hold, and the three contexts this daemon runs
 * in filled it three different ways: a developer's exported shell variables, Bun's automatic
 * `.env.test` load, and systemd's EnvironmentFile plus a per-unit credential tmpfs. The
 * measured consequence was a fully provisioned instance whose daemon could not boot — the
 * rendered env is SECRET-FREE by law, so SERVICE_TOKEN was missing, while the value sat
 * minted in a root-owned file the module had never heard of.
 *
 * So the source is built explicitly — named env file, small ambient allowlist, credentials
 * last — and every one of those layers is asserted here, through `resolveConfig()`. The
 * function is exported PURE for exactly this reason: the module-level singleton parses the
 * real environment and can `process.exit(1)`, which no gate can be written against.
 *
 * The scratch files live under the suite's own scratch tree, through the fixture, like every
 * other filesystem test in this suite (tests/seam_tripwire.test.ts) — and the resolved object
 * is bound as `resolved`, never as `config`, because `config.<ROOT>` in a test file is what
 * that seam tripwire refuses: reading a root off the daemon's frozen singleton. This file
 * asserts what a FRESH resolution produces from sources it wrote itself.
 */

import { describe, test, expect, afterEach } from 'bun:test';
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { SCRATCH_ROOT } from './fixtures/instance';
import { resolveConfig, parseEnvFile, readCredentials, type ConfigSources } from '../src/config';

/** This gate's own scratch corner. Outside every root, so no reset walks over it. */
const GATE_DIR = join(SCRATCH_ROOT, 'config_gate');
const ENV_FILE = join(GATE_DIR, 'env');
const CREDS_DIR = join(GATE_DIR, 'credentials');

afterEach(() => rmSync(GATE_DIR, { recursive: true, force: true }));

/** The smallest env file that resolves — every required key, no credential. */
function baseEnv(overrides: Record<string, string> = {}): Record<string, string> {
  return {
    DEDALO_SITE_INSTANCE: 'gate',
    SERVICE_TOKEN: 'x'.repeat(40),
    SITES_ROOT: './workspaces',
    AGENT_HOME: './agent_home',
    AUDIT_DIR: './audit',
    WEBSPACE_BASE: './webspaces',
    // The provisioner's site table — required like the roots, because the daemon reads
    // every site's placement out of it instead of deriving one.
    SITE_TABLE_FILE: './config/sites.json',
    PUBLICATION_API_URL: 'http://127.0.0.1:3100/publication/server_api/v2',
    ...overrides,
  };
}

function writeEnvFile(values: Record<string, string>): string {
  mkdirSync(GATE_DIR, { recursive: true });
  const body = Object.entries(values)
    .map(([key, value]) => `${key}="${value}"`)
    .join('\n');
  writeFileSync(ENV_FILE, `# generated by a gate\n${body}\n`, 'utf8');
  return ENV_FILE;
}

function writeCredential(key: string, value: string): string {
  mkdirSync(CREDS_DIR, { recursive: true });
  writeFileSync(join(CREDS_DIR, key), value, 'utf8');
  return CREDS_DIR;
}

function sources(patch: Partial<ConfigSources> = {}): ConfigSources {
  return { envFilePath: ENV_FILE, ambient: {}, credentialsDir: null, ...patch };
}

/* ────────────────────────────────────────────────────────────────────────────────────
 * The identity
 * ──────────────────────────────────────────────────────────────────────────────────── */

describe('the instance name is required and constrained', () => {
  test('a configuration that does not say which museum it is is refused', () => {
    const values = baseEnv();
    delete values.DEDALO_SITE_INSTANCE;
    writeEnvFile(values);
    expect(() => resolveConfig(sources())).toThrow(/DEDALO_SITE_INSTANCE/);
  });

  test('a malformed instance name is refused, whatever shape it is malformed in', () => {
    // The name becomes a unix user name, a systemd unit instance, a socket path and a
    // marker's content. Everything downstream trusts this grammar, so it is checked once,
    // here, against the same pattern the layout derives every host artifact from.
    for (const bad of ['Museum', 'has space', '../escape', 'x'.repeat(64), '9lives', '']) {
      writeEnvFile(baseEnv({ DEDALO_SITE_INSTANCE: bad }));
      expect(() => resolveConfig(sources())).toThrow(/DEDALO_SITE_INSTANCE/);
    }
  });

  test('the unit and a stale env file disagreeing about the museum is a refusal', () => {
    // The generated unit states Environment=DEDALO_SITE_INSTANCE AFTER its EnvironmentFile=,
    // so systemd's own precedence would let the unit silently win. It must not: everything
    // else the daemon reads — the ROOTS it writes to — came out of the same stale file.
    writeEnvFile(baseEnv({ DEDALO_SITE_INSTANCE: 'gate' }));
    expect(() => resolveConfig(sources({ ambient: { DEDALO_SITE_INSTANCE: 'other' } }))).toThrow(
      /disagrees with itself/,
    );
  });

  test('the same name on both sides is not a disagreement', () => {
    writeEnvFile(baseEnv());
    const { config: resolved } = resolveConfig(sources({ ambient: { DEDALO_SITE_INSTANCE: 'gate' } }));
    expect(resolved.DEDALO_SITE_INSTANCE).toBe('gate');
  });
});

/* ────────────────────────────────────────────────────────────────────────────────────
 * The layers
 * ──────────────────────────────────────────────────────────────────────────────────── */

describe('a credential file wins over anything the environment said', () => {
  test('the value comes from $CREDENTIALS_DIRECTORY, not from the env file', () => {
    // The whole point of LoadCredential: the file lives in a per-unit tmpfs that only this
    // process can read, and it is the one layer a service user cannot have written. A stale
    // SERVICE_TOKEN left behind in an env file must not be able to outrank it.
    writeEnvFile(baseEnv({ SERVICE_TOKEN: 'stale-token-'.padEnd(40, '0') }));
    const credentialsDir = writeCredential('SERVICE_TOKEN', 'live-token-'.padEnd(40, '1'));

    const { config: resolved, report } = resolveConfig(sources({ credentialsDir }));
    expect(resolved.SERVICE_TOKEN).toBe('live-token-'.padEnd(40, '1'));
    expect(report.origin.SERVICE_TOKEN).toBe('credential');
    expect(report.credentialKeys).toEqual(['SERVICE_TOKEN']);
  });

  test('a credential file wins over an ambient value too', () => {
    writeEnvFile(baseEnv({ SERVICE_TOKEN: 'x'.repeat(40) }));
    const credentialsDir = writeCredential('ANTHROPIC_API_KEY', 'from-the-credential-store');
    const { config: resolved } = resolveConfig(
      sources({ ambient: { ANTHROPIC_API_KEY: 'from-the-shell' }, credentialsDir }),
    );
    expect(resolved.ANTHROPIC_API_KEY).toBe('from-the-credential-store');
  });

  test("a secret file's trailing newline is not part of the secret", () => {
    // Every ordinary way an operator writes a root-owned secret file (echo, printf, an
    // editor) leaves one, and a bearer that differs from the engine's by a newline fails
    // authentication with nothing in either log to say why.
    writeEnvFile(baseEnv());
    const credentialsDir = writeCredential('SERVICE_TOKEN', `${'y'.repeat(40)}\n`);
    expect(resolveConfig(sources({ credentialsDir })).config.SERVICE_TOKEN).toBe('y'.repeat(40));
  });

  /**
   * THE CREDENTIAL DOOR'S OWN REFUSALS, asked of `readCredentials` DIRECTLY.
   *
   * The test below drives `resolveConfig`, where an unknown credential is refused twice: by
   * this door, and — a layer later — by the schema's `strict()`. So it passed with the
   * door's own check disarmed, which is exactly how a renamed key whose `LoadCredential=`
   * line was not renamed with it would ship: the host converges, `provision check` is
   * clean, every mode is right, and the provider is silently unconfigured.
   *
   * The refusal MUST live at this door and not only at the schema, because the two say
   * different things. The schema says "this daemon has no such setting"; this door says
   * "the unit declares a credential nothing consumes" — the only message that names the
   * unit line an operator has to fix.
   */
  test('the credential door refuses a name the daemon does not read, on its own', () => {
    const dir = writeCredential('OPENAI_API_KEY', 'sk-not-a-key-this-daemon-reads');
    expect(() => readCredentials(dir)).toThrow(/not a key this daemon reads/);
    // And it names the census, so an operator can see what the unit SHOULD have said.
    expect(() => readCredentials(dir)).toThrow(/SERVICE_TOKEN/);
  });

  test('the credential door refuses a filename that is not a credential name at all', () => {
    // The same string is a filename, a `LoadCredential=` id and an environment variable
    // name (layout.ts holds all three to one grammar), so a file that cannot be all three
    // is a declaration mistake and not a credential.
    for (const name of ['service_token', '1SERVICE', 'SERVICE-TOKEN', 'SERVICE.TOKEN']) {
      const dir = writeCredential(name, 'whatever');
      expect(() => readCredentials(dir)).toThrow(/not a usable\s+credential name/);
      rmSync(join(dir, name));
    }
  });

  test('a lawful credential directory is read, so the refusals above are not refusing everything', () => {
    const dir = writeCredential('SERVICE_TOKEN', 'z'.repeat(40));
    expect(readCredentials(dir)).toEqual({ SERVICE_TOKEN: 'z'.repeat(40) });
  });

  test('a key the daemon does not read is refused even as a credential', () => {
    writeEnvFile(baseEnv());
    const credentialsDir = writeCredential('OPENAI_API_KEY', 'sk-nope');
    expect(() => resolveConfig(sources({ credentialsDir }))).toThrow(/OPENAI_API_KEY/);
  });

  test('the PATH form is read only when no credential supplied the value', () => {
    // The rendered env may carry PUBLICATION_API_KEY_FILE — a path — and never the value.
    mkdirSync(GATE_DIR, { recursive: true });
    const keyFile = join(GATE_DIR, 'api_key');
    writeFileSync(keyFile, 'key-from-the-file\n', 'utf8');
    writeEnvFile(baseEnv({ PUBLICATION_API_KEY_FILE: keyFile }));

    const viaFile = resolveConfig(sources());
    expect(viaFile.config.PUBLICATION_API_KEY).toBe('key-from-the-file');
    expect(viaFile.report.origin.PUBLICATION_API_KEY).toBe('api-key-file');

    const credentialsDir = writeCredential('PUBLICATION_API_KEY', 'key-from-the-credential');
    const viaCredential = resolveConfig(sources({ credentialsDir }));
    expect(viaCredential.config.PUBLICATION_API_KEY).toBe('key-from-the-credential');
  });

  test('a PUBLICATION_API_KEY_FILE nothing can read names both doors in its refusal', () => {
    writeEnvFile(baseEnv({ PUBLICATION_API_KEY_FILE: join(GATE_DIR, 'absent_key') }));
    expect(() => resolveConfig(sources())).toThrow(/CREDENTIALS_DIRECTORY\/PUBLICATION_API_KEY/);
  });
});

describe('the ambient environment is an allowlist, not a source', () => {
  test('an exported root in the shell cannot repoint a museum daemon', () => {
    writeEnvFile(baseEnv());
    const { config: resolved } = resolveConfig(sources({ ambient: { SITES_ROOT: '/somewhere/else' } }));
    expect(resolved.SITES_ROOT).toBe(join(GATE_DIR, 'workspaces'));
  });

  test('NODE_ENV and LOG_LEVEL are allowed through, because nothing renders them', () => {
    writeEnvFile(baseEnv());
    const { config: resolved, report } = resolveConfig(
      sources({ ambient: { NODE_ENV: 'development', LOG_LEVEL: 'debug' } }),
    );
    expect(resolved.NODE_ENV).toBe('development');
    expect(resolved.LOG_LEVEL).toBe('debug');
    expect(report.origin.NODE_ENV).toBe('ambient');
  });

  test('the env file wins over an ambient value it also states', () => {
    writeEnvFile(baseEnv({ LOG_LEVEL: 'warn' }));
    const { config: resolved } = resolveConfig(sources({ ambient: { LOG_LEVEL: 'debug' } }));
    expect(resolved.LOG_LEVEL).toBe('warn');
  });

  /**
   * THE CENSUS ITSELF — asked of every key the daemon has, one at a time.
   *
   * The three tests above hold the LAYERING (a root cannot be repointed, two named keys do
   * come through, the file wins a tie). None of them holds the LIST: widening AMBIENT_KEYS
   * to include SERVICE_TOKEN or ANTHROPIC_API_KEY left the whole suite green, and that one
   * edit re-opens the door §3 of engineering/SITE_BUILDER_INSTANCES.md closes — a
   * credential reaching the daemon out of `/proc/<pid>/environ`, a unit `Environment=`
   * line, or an operator's shell, instead of only out of `$CREDENTIALS_DIRECTORY`, while
   * every rendered file on disk still looks correct.
   *
   * So the census is DERIVED and TOTAL: every key of the resolved configuration is offered
   * ambiently, alone, with the env file silent about it, and the set that actually takes
   * effect is compared against the three. No list of keys is written in this test — the
   * subject is which of the daemon's OWN keys the daemon honours.
   */
  test('exactly three keys can come from the ambient environment, and they are these', () => {
    writeEnvFile(baseEnv());
    const { config: baseline } = resolveConfig(sources());

    const honoured: string[] = [];
    for (const key of Object.keys(baseline).sort()) {
      // The env file says nothing about this key, so the ambient layer is free to fill it.
      const values = baseEnv();
      delete values[key];
      writeEnvFile(values);

      // A value that is certain to parse: the one the daemon itself resolved.
      const ambient = { [key]: String((baseline as Record<string, unknown>)[key]) };
      try {
        const { report } = resolveConfig(sources({ ambient }));
        if (report.origin[key] === 'ambient') honoured.push(key);
      } catch {
        // A refusal means the ambient value was NOT used to fill a required key — the key
        // is not on the allowlist. (An ambient value that WAS consulted and disagreed
        // would have been a different message, and that case cannot arise here: the file
        // is silent about the key.)
      }
    }

    expect(honoured).toEqual(['DEDALO_SITE_INSTANCE', 'LOG_LEVEL', 'NODE_ENV']);
  });
});

/* ────────────────────────────────────────────────────────────────────────────────────
 * The refusals
 * ──────────────────────────────────────────────────────────────────────────────────── */

describe('an unknown key is a named refusal, never a silent no-op', () => {
  test('the refusal names the key, where it came from, and what is known', () => {
    // A generated env file carrying a key nothing reads is either a renderer inventing a
    // knob or a daemon that dropped one. Both are drift; drift that takes effect nowhere
    // while every file on disk looks correct is the failure this refusal exists for.
    writeEnvFile(baseEnv({ PREPROD_ROOT_TYPO: '/srv/typo' }));
    let message = '';
    try {
      resolveConfig(sources());
    } catch (error) {
      message = (error as Error).message;
    }
    expect(message).toContain('PREPROD_ROOT_TYPO');
    expect(message).toContain('env-file');
    expect(message).toContain('SITES_ROOT'); // the known-key census is quoted
    expect(message).toContain('Nothing was started');
  });

  test('a line that is neither KEY=VALUE nor a comment names the file and the line', () => {
    mkdirSync(GATE_DIR, { recursive: true });
    writeFileSync(ENV_FILE, 'DEDALO_SITE_INSTANCE="gate"\nthis is not a directive\n', 'utf8');
    expect(() => resolveConfig(sources())).toThrow(/line 2/);
  });
});

describe('the env file grammar is the one the renderer writes', () => {
  test('quotes, escapes, comments and blank lines round-trip', () => {
    const parsed = parseEnvFile(
      [
        '# a comment',
        '',
        'PLAIN=value',
        'QUOTED="a value with spaces"',
        'ESCAPED="a \\"quoted\\" \\\\ backslash"',
        "SINGLE='literal'",
        'export EXPORTED=ok',
      ].join('\n'),
      '(gate)',
    );
    expect(parsed).toEqual({
      PLAIN: 'value',
      QUOTED: 'a value with spaces',
      ESCAPED: 'a "quoted" \\ backslash',
      SINGLE: 'literal',
      EXPORTED: 'ok',
    });
  });
});

describe('the roots resolve against the file that declared them', () => {
  test('a relative root means "beside the env file", never "beside the cwd"', () => {
    // A root is what every publish and every reset operates on. Resolving it against the
    // process's working directory made one string mean two places depending on where the
    // daemon (or the suite) was started from.
    writeEnvFile(baseEnv());
    const { config: resolved } = resolveConfig(sources());
    expect(resolved.SITES_ROOT).toBe(join(GATE_DIR, 'workspaces'));
    expect(resolved.AGENT_HOME).toBe(join(GATE_DIR, 'agent_home'));
    expect(resolved.AUDIT_DIR).toBe(join(GATE_DIR, 'audit'));
    expect(resolved.WEBSPACE_BASE).toBe(join(GATE_DIR, 'webspaces'));
    expect(resolved.SITE_TABLE_FILE).toBe(join(GATE_DIR, 'config', 'sites.json'));
  });

  test('the surface roots are GONE — a site is served out of its own webspace', () => {
    // PREPROD_ROOT and PROD_ROOT described one tree per surface with every site a directory
    // inside it, served at <root>/<slug>/. The provisioner never built that and no generated
    // vhost ever served it. They are not deprecated, they are deleted: an env file still
    // carrying one is an unknown key and a named refusal, which is how an operator finds out
    // rather than publishing into a directory nothing serves.
    writeEnvFile(baseEnv({ PREPROD_ROOT: '/srv/preprod' }));
    let message = '';
    try {
      resolveConfig(sources());
    } catch (error) {
      message = (error as Error).message;
    }
    expect(message).toContain('PREPROD_ROOT');
    expect(message).toContain('does not read');

    // What remains is the pair of host facts a site's URL needs, with laptop defaults.
    writeEnvFile(baseEnv());
    const { config: resolved } = resolveConfig(sources());
    expect(resolved.PREPROD_HOST_PREFIX).toBe('pre');
    expect(resolved.PROD_URL_SCHEME).toBe('https');
  });
});

describe('what a provisioned host actually supplies is enough to boot', () => {
  test('the rendered env plus its credentials resolves — the K1 regression', () => {
    // The shape of a converged provision: no secret in the env file, no surface roots and
    // no instance-wide base URL, the socket named, the key as a PATH, and every credential
    // in the per-unit tmpfs.
    const credentialsDir = writeCredential('SERVICE_TOKEN', 'z'.repeat(48));
    writeCredential('ANTHROPIC_API_KEY', 'sk-ant-from-the-store');
    writeCredential('PUBLICATION_API_KEY', 'api-key-from-the-store');
    writeEnvFile({
      AGENT_DRIVER: 'claude_code',
      AGENT_HOME: '/var/lib/dedalo_sites/gate/home',
      AUDIT_DIR: '/srv/dedalo_audit/gate',
      CLAUDE_CODE_BIN: '/usr/local/bin/claude',
      DEDALO_SITE_INSTANCE: 'gate',
      DEPLOYMENT_MODE: 'nginx',
      LISTEN_KIND: 'unix',
      LISTEN_SOCKET: '/run/dedalo-sites/gate/daemon.sock',
      MAX_SITES: '8',
      PUBLICATION_API_KEY_FILE: '/etc/dedalo_sites/instances/gate/secrets/PUBLICATION_API_KEY',
      PREPROD_HOST_PREFIX: 'pre',
      PROD_URL_SCHEME: 'https',
      PUBLICATION_API_URL: 'http://127.0.0.1:3100/publication/server_api/v2',
      RELEASES_RETAINED: '10',
      SITES_ROOT: '/var/lib/dedalo_sites/gate/workspaces',
      SITE_TABLE_FILE: '/etc/dedalo_sites/instances/gate/sites.json',
      WEBSPACE_BASE: '/srv/www',
    });

    const { config: resolved, report } = resolveConfig(sources({ credentialsDir }));
    expect(resolved.SERVICE_TOKEN).toBe('z'.repeat(48));
    expect(resolved.LISTEN_SOCKET).toBe('/run/dedalo-sites/gate/daemon.sock');
    expect(resolved.MAX_SITES).toBe(8);
    // The table's path is configuration like any other root — a provisioned daemon is TOLD
    // where its sites are and computes no placement of its own.
    expect(resolved.SITE_TABLE_FILE).toBe('/etc/dedalo_sites/instances/gate/sites.json');
    // The unreadable 0600 path did not have to be read: the credential answered first.
    expect(resolved.PUBLICATION_API_KEY).toBe('api-key-from-the-store');
    expect(report.origin.PUBLICATION_API_KEY).toBe('credential');
  });
});
