<?php

	# VISUALIZADOR HTML
	

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in', $modo, $lang);


	$wrap_style = isset($wrap_style) ? $wrap_style : '';
	print "<div class=\"wrap_component css_wrap_svg wrap_component_{$modo} wrap_component_{$tipo}\" id=\"{$id_wrapper}\" ";
	print "style=\"$wrap_style\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-modo=\"{$modo}\" ";
	#print "data-dato='{$dato_json}' ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-component_info='{$component_info}' ";
	print ">";
	

	# LABEL
	$html_label = component_common_draw::draw_label($this);
	

	# CONTENIT
	$html_content = '';
	switch($permissions) {

		case 0 :
				$html_content .= "";
				break;

		case 1 :
				
				break;

		case 2 :
		case 3 :

				if(SHOW_DEBUG===true) {
					$html_content .= "<span class=\"debug_info notes\">".$file_url."</span>";
				}

				$svg_container_id = 'svg_container_' . $identificador_unico;
				$html_content .= '<div class="svg_container" id="'.$svg_container_id.'"></div>';

				# JS				
				$html_content .= "<script>";
				// Init
				$init_options = array(
					"uid" 			=> $identificador_unico,
					"modo" 			=> $modo,
					"propiedades" 	=> $propiedades,
					"file_url" 		=> $file_url,
					"file_exists" 	=> $file_exists,
					"file_content"	=> $file_content,
					"svg_id" 		=> $svg_id
				);
				$html_content .= "component_svg.init(".json_encode($init_options).");";
				$html_content .= "</script>";
				
				
				break;
	}

	# Prepare content to show in page
	tools::prepare_content($html_content);


	# PRINT HTML
	if($modo!=='edit_in_list'){
		print $html_label;
	}		
	print $html_content;


	print "</div>"; //wrap

	

	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out', $modo, $lang);

	
?>