<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset($ar_css['css_wrap_geolocation']))		$ar_css['css_wrap_geolocation'] = null;
	
	
	print "\n<!-- GEOLOCATION [tipo:$tipo id_matrix:$id] $label -->";
	print "\n<div class=\"css_wrap_geolocation wrap_component {$ar_css['css_wrap_geolocation']}\" id=\"{$id_wrapper}\"
	data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-parent=\"{$parent}\" data-modo=\"{$modo}\" data-dato=\"{$valor}\" data-component_name=\"{$component_name}\" >";
	
		
		# ETIQUETA (LABEL)
		$html_label = component_common_draw::draw_label($this);
		
		# CONTENIDO (INPUT)
		$html_contenido = '';
		switch($permissions) {
				
			case 0	:	$html_contenido .= "\n <span class=\"css_span_sin_acceso\">".label::get_label('sin_acceso')."</span>";
						break;
							
			case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> Under construction </span>";
						break;	
							
			case ($permissions>=2)	:						

						$html_contenido .= "\n <div class=\"leaflet_map\" id=\"$identificador_unico\"><!-- Content here --></div>";												
						
				if($permissions==3)		
						$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$debugger}</span>";	
												
		}

		# Prepare content to show in page
		tools::prepare_content($html_contenido);	
		

		# PRINT HTML
		print $html_label;
		print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_geolocation GEOLOCATION [tipo:$tipo id_matrix:$id] $label -->\n"; //wrap


?>
<script type="text/javascript">
	// Set var geo provider fron config
	component_geolocation.DEDALO_GEO_PROVIDER = '<?php echo DEDALO_GEO_PROVIDER ?>';
	// Build map
	
		component_geolocation.init_map('<?php echo $identificador_unico ?>');
	setTimeout(function(){	
		//L.Util.requestAnimFrame(map.invalidateSize,map,!1,map._container);
		//L.map.invalidateSize(false);
		//console.log(L.map)
		//console.log(component_geolocation)
		//component_geolocation.maps.invalidateSize(false);
	}, 1000)
	
		
</script>