<?php

	# VISUALIZADOR HTML	
	
	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in');

	$add_class = ($modo==='player') ? 'leaflet_map_player' : '';

	print "<div class=\"wrap_component css_wrap_geolocation wrap_component_{$tipo} $add_class\" id=\"{$id_wrapper}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-label=\"{$label}\" ";
	print "data-dato='{$dato_json}' ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-component_info='{$component_info}' ";
	print "data-related_tipo='{$ar_related_component_tipo_json}' ";
	print ">";
	
		
		# ETIQUETA (LABEL)
		$html_label = component_common_draw::draw_label($this);
		
		# CONTENIDO (INPUT)
		$html_content = '';
		switch($permissions) {
				
			case 0	:
					$html_content .= "";
					break;
							
			case 1	: 	
					$html_content .= "<span class=\"css_span_dato\"> Under construction </span>";
					break;	
							
			case 2 :
			case 3 :
					
					// map_inputs
						$html_content .= '<div class="map_inputs">';

							# LAT
							$html_content .= '<span>'.label::get_label('latitud').'</span>';
							$html_content .= "<input type=\"text\" name=\"lat\" value =\"{$dato->lat}\" class=\"geo_active_input\" ";
							$html_content .= "data-name=\"lat\" ";
							
							#$html_content .= "data-tipo=\"{$tipo}\" ";
							#$html_content .= "data-lang=\"{$lang}\" ";
							#$html_content .= "data-section_tipo=\"{$section_tipo}\" ";
							#$html_content .= "data-parent=\"{$parent}\" ";
							#$html_content .= "data-modo=\"{$modo}\" ";						
							$html_content .= "/>";

							# LON
							$html_content .= '<span>'.label::get_label('longitud').'</span>';
							$html_content .= "<input type=\"text\" name=\"lon\" value=\"{$dato->lon}\" data-name=\"lon\" class=\"geo_active_input\"/>";

							# ZOOM
							$html_content .= '<span>'.label::get_label('mapa_zoom').'</span>';
							$html_content .= "<input type=\"text\" name=\"zoom\" value=\"{$dato->zoom}\" data-name=\"zoom\" class=\"geo_active_input\"/>";

							# ALTITUDE
							$html_content .= '<span>'.label::get_label('altitude').'</span>';
							#$html_content .= " <span name=\"alt\" data-name=\"alt\"/>".$dato->alt.'</span>';
							$alt = isset($dato->alt) ? $dato->alt : null;
							$html_content .= "<input type=\"text\" name=\"alt\" class=\"input_altitude\" value=\"{$alt}\" data-name=\"alt\" readonly=\"readonly\"/>";
							
							# SEPARATOR
							$html_content .= '<span class="geolocation_separator"></span>';

							# REFRESH BUTTON
							$html_content .= "<span id=\"map_refresh\" class=\"glyphicon glyphicon-refresh geolocation_text link\"></span>";

							# SEPARATOR
							$html_content .= '<span class="geolocation_separator"></span>';

							# SAVE BUTTON
							$html_content .= "<span id=\"map_fixed\" class=\"link save_geolocation\"> ".label::get_label('salvar').'</span>';

							# SEPARATOR
							$html_content .= '<span class="geolocation_separator"></span>';

							# TOGGLE BUTTON
							$html_content .= "<span id=\"map_fixed\" class=\"link glyphicon glyphicon-fullscreen geolocation_text\" onclick=\"component_geolocation.toggle_full_map(this)\"></span>";

						$html_content .= '</div>';//end map_inputs


					#
					# MAP
						$html_content .= " <div class=\"leaflet_map\" id=\"$identificador_unico\"><!-- Map content here --></div>";

					
					#
					# JS Init component
					$html_content .= '<script>';
					# Init component
					$init_options = new stdClass();
						$init_options->component_name 		= $component_name;
						$init_options->wrapper_id 			= $id_wrapper;
						$init_options->uid 					= $identificador_unico;
						$init_options->DEDALO_GEO_PROVIDER 	= DEDALO_GEO_PROVIDER;
					$html_content .= 'component_common.init('.json_encode($init_options).');';
					$html_content .= '</script>';
					break;														
		}

		# Prepare content to show in page
		tools::prepare_content($html_content);	
		

		# PRINT HTML
		if ($modo==='edit') {
		print $html_label;
		}		
		print $html_content;
	
	
	print '</div>';


	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out');


