<?php

	# VISUALIZADOR HTML	
	
	print "\n<!-- GEOLOCATION [tipo:$tipo section_id_matrix:$parent] $label -->";
	print "\n<div class=\"css_wrap_geolocation wrap_component\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-section_tipo=\"{$section_tipo}\" data-parent=\"{$parent}\" data-modo=\"{$modo}\" data-dato=\"{$valor}\" data-component_name=\"{$component_name}\" >";
	
		
		# ETIQUETA (LABEL)
		$html_label = component_common_draw::draw_label($this);
		
		# CONTENIDO (INPUT)
		$html_contenido = '';
		switch($permissions) {
				
			case 0	:	$html_contenido .= "\n <span class=\"css_span_sin_acceso\">".label::get_label('sin_acceso')."</span>";
						break;
							
			case ($permissions>=1)	:						

						$html_contenido .= "\n <div id=\"$identificador_unico\">$component_name. working here..</div>";						
												
		}

		# PRINT HTML
		print $html_label;
		print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_geolocation GEOLOCATION [tipo:$tipo section_id_matrix:$parent] $label -->\n"; //wrap

?>