<?php

	# VISUALIZADOR HTML	
		
	# CONTENIDO (INPUT)
	$html_content = '';
	switch($permissions) {
			
		case 0	:	$html_content .= "";		
					break;
					
		case ($permissions>=1)	:
			
					$html_content = '';
			
		$html_content .= "<ul class=\"css_inverse_list\">";

			foreach ($dato as $key => $current_locator) {

				$current_section_id 	= $current_locator->from_section_id;
				$current_section_tipo 	= $current_locator->from_section_tipo;
				$current_component_tipo = $current_locator->from_component_tipo;

				$line = '';
				foreach ($inverse_show as $ikey => $ivalue) {
					if ($ivalue===false) continue;

					# link to caller section
					if ($ikey === 'link') {
						$url = DEDALO_CORE_URL . '/main/?t='.$current_section_tipo.'&id='.$current_section_id;
						$line .= "<a class=\"css_button_generic btn_go_inverse\" href=\"$url\">";
						$line .= "<div class=\"link css_inverse_link\"></div>";
						$line .= "</a>";
					}

					# section_id
					if ($ikey === 'section_id') {
						if(strlen($line)>0) $line .= ' ';
						$line .= '<span class="inverse_show_section_id_list">'.$current_section_id.'</span>';
					}

					# section_tipo
					if ($ikey === 'section_tipo') {
						if(strlen($line)>0) $line .= ' ';
						$line .= '<span class="inverse_show_section_tipo">'.$current_section_tipo.'</span>';
					}

					# section_label
					if ($ikey === 'section_label') {
						if(strlen($line)>0) $line .= ' ';
						$label = RecordObj_dd::get_termino_by_tipo($current_section_tipo);
						$line .= '<span class="inverse_show_section_label">'.$label.'</span>';
					}

					# component_tipo
					if ($ikey === 'component_tipo') {
						if(strlen($line)>0) $line .= ' ';
						$line .= '<span class="inverse_show_component_tipo">'.$current_component_tipo.'</span>';
					}

					# component_label
					if ($ikey === 'component_label') {
						if(strlen($line)>0) $line .= ' ';
						$label = RecordObj_dd::get_termino_by_tipo($current_component_tipo);
						$line .= '<span class="inverse_show_component_label">'.$label.'</span>';
					}
				}			
				
				$html_content .= '<li>'. $line . '</li>';
			}

		$html_content .= "</ul>";

		if(SHOW_DEBUG===true) {
			$html_content .= " <span class=\"debug_info notes\">".$dato_json."</span>";
		}
		

	
	# PRINT HTML	
	print $html_content;
}
	
?>