<?php
	
	# VISUALIZADOR HTML	
	
	print "\n\n<!-- SECTION GROUP DIV [tipo:$tipo] $label -->";

	print "\n<div id=\"$identificador_unico\" class=\"wrap_section_group_div wrap_section_group_div_{$tipo}\" >";	
	

	# CONTENIDO (INPUT)
	$html_contenido='';
	$html_contenido .= "\n $components_html ";
	
	
	# PRINT HTML	
	print $html_contenido;

	
	print "\n</div><!-- /wrap_section_group_div SECTION GROUP DIV [tipo:$tipo]  -->\n\n"; //wrap
	
?>