<?php
	
	# VISUALIZADOR HTML	
	
	print "<!-- SECTION GROUP DIV [tipo:$tipo] $label -->";

	print "<div id=\"$identificador_unico\" class=\"wrap_section_group_div wrap_section_group_div_{$tipo} sgc_{$modo}\" >";	
	

	# CONTENIDO (INPUT)
	$html_contenido='';
	$html_contenido .= " $components_html ";
	
	
	# PRINT HTML	
	print $html_contenido;

	
	print "</div><!-- /wrap_section_group_div SECTION GROUP DIV [tipo:$tipo]  -->"; //wrap
	
?>