// @license magnet:?xt=urn:btih:0b31508aeb0634b347b8270c7bee4d411b5d4109&dn=agpl-3.0.txt AGPL-3.0
/*global get_label, page_globals, SHOW_DEBUG, DEDALO_CORE_URL */
/*eslint no-undef: "error"*/



/**
 * TOOL_QR
 * Generates and displays printable QR-code sheets for the records in a section.
 *
 * Each QR code encodes the deep-link URL of one section record, and each card
 * on the sheet can optionally display a thumbnail image and a label component
 * alongside the QR code — making the output suitable for physical warehouse or
 * museum labels.
 *
 * Entry points & dependencies:
 *   - `tool_qr`          — constructor; extends `tool_common` via prototype delegation.
 *   - `tool_qr.init`     — loads the EasyQRCodeJS library lazily after common init.
 *   - `tool_qr.build`    — drives section data loading; delegates rendering to
 *                          `render_tool_qr.prototype.edit` (wired in below).
 *   - `tool_qr.load_section` — resolves API context, applies `ddo_map` from the
 *                          button trigger config, and creates the live section instance.
 *
 * Configuration is driven by a `tool_config.ddo_map` JSON blob stored on the
 * triggering button's properties (key `button_trigger`). Each entry in `ddo_map`
 * carries a `role` field (`"image"` or `"label"`) to tell the renderer which
 * component tipos to use for the card's thumbnail and text.
 *
 * The QR code itself is generated by the EasyQRCodeJS library, served from the
 * client-lib registry (`/dedalo/lib/qrcode/dist/easy.qrcode.min.js` — the pinned
 * `easyqrcodejs` package; src/core/client_libs/registry.ts). A Web Worker implementation was attempted
 * (`worker_qr.js`) but is currently disabled — see the commented-out block in
 * `render_tool_qr.js`:`generate_qr`.
 *
 * Main exports:
 *   {Function} tool_qr — constructor for QR tool instances
 */



// import needed modules
	import {data_manager} from '../../../core/common/js/data_manager.js'
	import {response_data} from '../../../core/common/js/api_error.js'
	import {get_instance} from '../../../core/common/js/instances.js'
	import {common} from '../../../core/common/js/common.js'
	import {tool_common} from '../../../core/tools_common/js/tool_common.js'
	import {render_tool_qr} from './render_tool_qr.js' // self tool rendered (called from render common)
	import {max_page_limit} from '../../../core/common/js/sqo_limit.js'



/**
* TOOL_QR
* Constructor for the QR tool instance.
* Declares every instance property to null so that introspection tools and the
* common destroy/refresh cycle can find and clean up all state.
*
* Properties inherited from tool_common are seeded in `tool_common.prototype.init`;
* tool-specific additions:
*   - `section`   — the live section instance built from the caller's context.
*   - `qr_canvas` — a pointer to the `.qr_canvas` DOM element set by the renderer
*                   so that the direction-selector handler can toggle CSS classes
*                   (portrait / landscape) on it directly.
*/
export const tool_qr = function () {

	this.id				= null
	this.model			= null
	this.mode			= null
	this.node			= null
	this.ar_instances	= null
	this.events_tokens	= null
	this.status			= null
	this.main_element	= null
	this.type			= null
	this.source_lang	= null
	this.target_lang	= null
	this.langs			= null
	this.caller			= null

	this.section		= null

	this.qr_canvas		= null
}//end page



/**
* COMMON FUNCTIONS
* extend component functions from component common
*/
// prototypes assign
	tool_qr.prototype.render		= tool_common.prototype.render
	tool_qr.prototype.destroy		= common.prototype.destroy
	tool_qr.prototype.refresh		= common.prototype.refresh
	// render mode edit (default). Set the tool custom manager to build the DOM nodes view
	tool_qr.prototype.edit			= render_tool_qr.prototype.edit



/**
* INIT
* Custom tool init.
* Calls the shared `tool_common.prototype.init` first (which seeds all common
* properties from `options`), then dynamically imports the EasyQRCodeJS
* library from the client-lib registry so it is available by the time `build` calls the QR renderer.
*
* The library is imported lazily here rather than at module load time because
* QRCode generation is only needed when the tool is actually opened, and the
* library is relatively large (~60 KB minified).
*
* @param {Object} options - Standard tool init options forwarded to tool_common.
* @returns {Promise<boolean>} Resolves with the return value of `tool_common.init`.
*/
tool_qr.prototype.init = async function(options) {

	const self = this

	// call the generic common tool init
		const common_init = await tool_common.prototype.init.call(this, options);

	try {

		// The UMD bundle binds `QRCode` on globalThis (it resolves its root through
		// Function('return this')), which is what render_tool_qr.js reads.
		await import('/dedalo/lib/qrcode/dist/easy.qrcode.min.js');

	} catch (error) {
		self.error = error
		console.error(error)
	}


	return common_init
}//end init



/**
* BUILD
* Custom tool build.
* Delegates to `tool_common.prototype.build` for generic setup (CSS loading,
* ddo_map resolution), then calls `load_section` to fetch the section records that
* will populate the QR sheet.
*
* The `load_ddo_map` hook passed to tool_common is intentionally a no-op because
* this tool reads its ddo_map from the button trigger config (`tool_config.ddo_map`)
* rather than from the standard tool context, which is handled inside `load_section`.
*
* The built section instance is pushed into `self.ar_instances` so that it is
* destroyed when the tool closes.
*
* @param {boolean} [autoload=false] - When true, triggers automatic data loading
*   in the common build step.
* @returns {Promise<boolean>} Resolves with the return value of `tool_common.build`.
*/
tool_qr.prototype.build = async function(autoload=false) {

	const self = this

	// call generic common tool build
		const common_build = await tool_common.prototype.build.call(self, autoload, {
			load_ddo_map : () => {
				// catches load_ddo_map
			}
		});

	try {

		// debug
			if(SHOW_DEBUG===true) {
				console.log('tool_qr self:', self);
			}
		// section
			// load_section from API
			self.section = await self.load_section()
			// add to tool instances for destroy at end of tool life
			self.ar_instances.push(self.section)

	} catch (error) {
		self.error = error
		console.error(error)
	}


	return common_build
}//end build_custom



/**
* LOAD_SECTION
* Resolves the API context for the caller's tipo/section_tipo pair, applies the
* ddo_map from the button trigger config, and instantiates + builds the live
* section instance whose data drives the QR sheet.
*
* Data-source strategy (`ddo_map_source`):
*   - `'button_trigger'` (current default) — reads `self.tool_config.ddo_map` that
*     was stored on the activating button's properties. This is the preferred path
*     because each button can be scoped to a specific user group.
*   - Section-list properties path (commented fallback) — would read the ddo_map
*     from `element_context.properties.tool_config.tool_qr.ddo_map`. Kept as a
*     reference; not active.
*
* After obtaining the ddo_map the method overrides the SQO pagination to
* `limit = max_page_limit() / offset = 0` — the SERVER's client ceiling
* (common/js/sqo_limit.js), which is what one request can ever return. It used
* to send `limit = 0`: the server read that as the same ceiling and clamped in
* silence, so a sheet over a large selection was truncated with nothing to say
* so — the worst outcome for a QR sheet is a record silently missing (P2-31).
*
* The resolved section's `total` is the SERVER's count (section.get_total);
* when it exceeds the rows fetched the render surfaces the truncation
* (render_tool_qr `qr_truncated`) instead of printing a partial sheet as whole.
*
* @returns {Promise<Object|boolean>} Resolves with the built section instance, or
*   `false` when the element_context API call fails or returns no rows.
*/
tool_qr.prototype.load_section = async function() {

	const self = this

	const tipo			= self.caller.tipo
	const section_tipo	= self.caller.section_tipo

	// resolve section context
		const element_context_response = await data_manager.get_element_context({
			tipo			: tipo,
			section_tipo	: section_tipo
		})
		const element_context_data = response_data(element_context_response)
		if (!element_context_data || !element_context_data[0]) {
			console.error('element_context_response:', element_context_response);
			return false
		}
		const element_context = element_context_data[0]

	// request_config
		const request_config = element_context.request_config
		// request_config_dedalo item
		const request_config_dedalo = request_config.find(el => el.api_engine==='dedalo')

		// overwrite ddo_map
		// The tool allows to get the tool_config from the section list or from a button
		// Button way has the possibility of control user access by section. At now this
		// will be the default source
		const ddo_map_source = 'button_trigger'
		const ddo_map = ddo_map_source==='button_trigger'
			? self.tool_config.ddo_map || [] // from button properties
			: element_context.properties?.tool_config?.tool_qr?.ddo_map || [] // from section_list properties

		request_config_dedalo.show.ddo_map = ddo_map
		// overwrite pagination: one page at the server's client ceiling
		request_config_dedalo.sqo.limit = max_page_limit()
		request_config_dedalo.sqo.offset = 0

	// section
		const section = await get_instance({
			tipo			: tipo,
			section_tipo	: section_tipo,
			model			: self.caller.model,
			lang			: self.caller.lang,
			mode			: 'list',
			request_config	: request_config,
			add_show		: true,
			id_variant		: self.section_tipo +'_' + self.model
		})

		await section.build(true)

	// set total: the SERVER's count, so a selection above the ceiling is seen
	// as truncated (rows fetched < total) rather than reported as whole
		const fetched = section.data.value?.length || 0
		let total = fetched
		if (typeof section.get_total==='function') {
			// the FILTERED count: the same sqo the rows were read with
			const server_total = await section.get_total(section.rqo?.sqo || request_config_dedalo.sqo)
			if (Number.isFinite(Number(server_total))) {
				total = Number(server_total)
			}
		}
		section.total		= total
		section.truncated	= total > fetched


	return section
}//end load_section



// @license-end
