<?php

	$html_row = '';

	$html_row .= "<tr class=\"tr_row\">";
	
	# Empty td (below the image)
	$html_row .= "<td>";
		$html_row .= " ";
	$html_row .= "</td>";

	#
	# INFO
	$colspan   = count($ar_diffusion_obj_head)-1;
	$html_row .= "<td colspan=\"$colspan\">";

	
	$html_row .= "<table class=\"diffusion_index_ts_row_table\">";
	$included_tr_head = false;
	foreach ($ar_row_elements as $current_section_id => $rel_locator_obj) {

		$section_tipo 		= $rel_locator_obj->section_tipo;
		$section_id 	  	= $rel_locator_obj->section_id;
		$parent 	  		= $section_id;
		$component_tipo 	= $rel_locator_obj->component_tipo;
		$section_top_tipo 	= $rel_locator_obj->section_top_tipo;
		$section_top_id 	= $rel_locator_obj->section_top_id;
		$tag_id 			= $rel_locator_obj->tag_id;
		$type 				= $rel_locator_obj->type;
			#dump($type, ' type ++ '.to_string());

			#dump($rel_locator_obj, ' section_tipo ++ '.to_string());
		
		# COMPONENT_TEXT_AREA
		$component_text_area 	= component_common::get_instance('component_text_area',
																 $component_tipo,
																 $section_id,
																 'edit',
																 DEDALO_DATA_LANG,
																 $section_tipo);
		if ($type===DEDALO_RELATION_TYPE_STRUCT_TIPO) {
			$raw_text = $component_text_area->get_dato();
			# Returns original lang transcription
			$main_lang = component_text_area::force_change_lang($component_tipo, $section_id, 'edit', DEDALO_DATA_LANG, $section_tipo);
			$pattern = TR::get_mark_pattern('struct', $standalone=true, $tag_id, false, false);
			preg_match($pattern, $raw_text, $matches);
			#dump($matches, ' matches ++ '.to_string($raw_text));
			if (empty($matches[0]) && $main_lang!=DEDALO_DATA_LANG) {
				$component_text_area->set_lang($main_lang);
				$raw_text = $component_text_area->get_dato();
			}
		}

		#dump($component_text_area,'component_text_area');
		$propiedades 	= array('rel_locator'=>$rel_locator_obj);
		$diffusion_obj 	= $component_text_area->get_diffusion_obj( $propiedades );			
			#dump($diffusion_obj, ' diffusion_obj ++ '.to_string());
			#dump($component_text_area->get_dato(), '$component_text_area->get_dato() ++ '.to_string());

		#$component_text_area->set_lang(DEDALO_DATA_LANG);

		# ROW TR HEAD ------------------------------------------------
		if(!$included_tr_head) {
			/*
			$html_row .= "<tr>";
			$html_row .= "<th>ID</th>";
			$html_row .= "<th>Tag</th>";
			$html_row .= "<th clas=\"th_fragment\">Fragment</th>";
			$html_row .= "<th>".label::get_label('informacion')."</th>";
			$html_row .= "</tr>";

			$included_tr_head = true;
			*/
		}
		

	
		# ROW TR -----------------------------------------------------
		$html_row .= "<tr>";
		

			#
			# TD_SECTION_ID
			$html_row .= "<td class=\"td_section_id\">";
				$html_row .= "<div class=\"section_id\">";
				$html_row .= $section_id;
				$html_row .= "</div>";
			$html_row .= "</td>";


			
			#
			# TD_TAG_ID
			$html_row .= "<td class=\"td_tag_id\">";

			if ($type===DEDALO_RELATION_TYPE_STRUCT_TIPO) {
				# DEDALO_RELATION_TYPE_STRUCT_TIPO (dd490)
				$html_row .= "<div class=\"tag_title\">";
		
				$pattern = TR::get_mark_pattern('struct', $standalone=true, $tag_id, false, false);
				preg_match($pattern, $raw_text, $matches);
				#dump($matches, ' matches ++ '.to_string($raw_text));
				if (isset($matches[0])) {	
					// tag data is the locator inside tag struct	
					$tag_data  = TR::tag2data($matches[0], 'struct');
						#dump($tag_data, ' tag_data ++ '.to_string());
					if ($tag_data!==null) {					
						$title_modelo_name = RecordObj_dd::get_modelo_name_by_tipo(DEDALO_STRUCTURATION_TITLE_TIPO,true);
						$title_component= component_common::get_instance($title_modelo_name,
																		 DEDALO_STRUCTURATION_TITLE_TIPO,
																		 $tag_data->section_id,
																		 'list',
																		 DEDALO_DATA_LANG,
																		 $tag_data->section_tipo);
						$title = $title_component->get_valor(DEDALO_DATA_LANG);
							#dump($title, ' title ++ '.to_string(DEDALO_STRUCTURATION_TITLE_TIPO));
						if ($main_lang!=DEDALO_DATA_LANG) {
							$title_component->set_lang($main_lang);
							$title = $title_component->get_valor($main_lang);
							$title = "<mark>".$title ."</mark>";
						}
						$html_row .= "<span class=\"struct_title\">$title</span>";
					}else{
						debug_log(__METHOD__." Empty matches tag_data in text for tag_id:".to_string($tag_id), logger::ERROR);
					}
				}
				$html_row .= "</div>";
			}else{
				# DEDALO_RELATION_TYPE_INDEX_TIPO (dd96)
				$html_row .= "<div class=\"tag_id\">";
				$html_row .= $tag_id;
				$html_row .= "</div>";
			}
				/*		
				$url = DEDALO_CORE_URL . "/main/?m=tool_indexation&t={$diffusion_obj->tipo}&section_tipo={$section_tipo}&parent={$parent}&top_tipo={$section_top_tipo}&top_id={$section_top_id}&tag_id={$tag_id}";
				$html_row .= "<a href=\"$url\" target=\"_blank\" class=\"tag_id\"
				data-parent=\"$parent\"
				data-section_tipo=\"$section_tipo\"
				data-tipo=\"$diffusion_obj->tipo\"
				title=\"".label::get_label('ir_al_fragmento')."\">";
				$html_row .= $tag_id;
				$html_row .= "</a>";
				*/
			
			$html_row .= "</td>";


			
			#
			# TD_FRAGMENT (av / image / ..)
			$html_row .= "<td class=\"td_fragment\">";
			$column_related = isset($diffusion_obj->columns['related']) ? $diffusion_obj->columns['related'] : null;
			switch ($column_related) {
				case 'component_av':

					# Indexation link
					if ($type===DEDALO_RELATION_TYPE_STRUCT_TIPO) {
						$url = DEDALO_CORE_URL."/main/?m=tool_structuration&t=$diffusion_obj->tipo&section_tipo=$section_tipo&parent=$parent&top_tipo=$section_top_tipo&top_id=$section_top_id&tag_id=$tag_id";
						$html_row .= "<a href=\"$url\" class=\"icon_bs tool_structuration_icon link button_structuration\" target=\"_blank\" title=\"".label::get_label('tool_structuration')."\"></a>";				
					}else{
						$url = DEDALO_CORE_URL."/main/?m=tool_indexation&t=$diffusion_obj->tipo&section_tipo=$section_tipo&parent=$parent&top_tipo=$section_top_tipo&top_id=$section_top_id&tag_id=$tag_id";
						$html_row .= "<a href=\"$url\" class=\"icon_bs tool_indexation_icon link button_indexation\" target=\"_blank\" title=\"".label::get_label('tool_indexation')."\"></a>";				
					}
					
					# Transcription link
					$related_tipo 	= $diffusion_obj->columns['related_tipo'];
					$url = DEDALO_CORE_URL."/main/?m=tool_transcription&t=$related_tipo&section_tipo=$section_tipo&parent=$parent&context_name=component_av&tag_id=$tag_id&top_tipo=$section_top_tipo&top_id=$section_top_id"; 
					$html_row .= "<a href=\"$url\" class=\"icon_bs tool_transcription_icon link button_indexation_av\" target=\"_blank\" title=\"".label::get_label('tool_transcription')."\"></a>";

					# Video player link
					$reelID  		= isset($diffusion_obj->columns['video_id'])  ? $diffusion_obj->columns['video_id'] : null;
					$quality 		= DEDALO_AV_QUALITY_DEFAULT;
					$tcin_secs 		= isset($diffusion_obj->columns['tcin_secs'])  ? $diffusion_obj->columns['tcin_secs']  : null;
					$tcout_secs 	= isset($diffusion_obj->columns['tcout_secs']) ? $diffusion_obj->columns['tcout_secs'] : null;	// Like vbegin=287&vend=318 tcout_secs
					$url = DEDALO_CORE_URL."/media_engine/av_media_player.php?reelID=$reelID&quality=$quality&top_tipo=$section_top_tipo&top_id=$section_top_id&section_tipo=$section_tipo&vbegin=$tcin_secs&vend=$tcout_secs"; 
					$html_row .= "<a href=\"$url\" class=\"icon_bs av_video_icon link\" target=\"_blank\" title=\"".label::get_label('fragmento')."\"></a>";

					# Share custom link					
					# icon_share					
					if( defined('PUBLIC_FRAGMENT_URL') ) {
						/* V3 COMPATIBILITY IN PRECESS
						# modo=5&terminoID=aa124&captacionID=19&key=4&identificador_unico=aa124_19_4
						$public_fragment_url  = PUBLIC_FRAGMENT_URL;
						$public_fragment_url .= '?';
						$public_fragment_url .= '&modo=5';
						$public_fragment_url .= '&terminoID='.$terminoID;
						$public_fragment_url .= '&captacionID='.$captacionID;
						$public_fragment_url .= '&key='.$key2;
						$public_fragment_url .= '&identificador_unico='.$terminoIDGet.'_'.$captacionID.'_'.$key2;
						$public_fragment_url .= '&single=1';			
							#dump($public_fragment_url, 'public_fragment_url', array());

						echo "<div onclick=\"open_public_fragment_url('$public_fragment_url')\" class=\"open_public_fragment_url icon_share\"> </div>";
						*/
					}//end if( defined('PUBLIC_FRAGMENT_URL') ) {					
					break;
				
				default:
					$html_row .= "  ";					
					break;
			}

			#
			# TEXT (Transcription fragment)
			# dump($diffusion_obj->columns['fragment'], '$diffusion_obj->columns ++ '.to_string());
			$html_row .= "<div class=\"fragment_text\">";
			$current_fragment = TR::limpiezaFragmentoEnListados($diffusion_obj->columns['fragment'],122);
			if ($type===DEDALO_RELATION_TYPE_STRUCT_TIPO && DEDALO_DATA_LANG!=$main_lang) {
				$current_fragment = "<mark>".$current_fragment."</mark>";
			}
			$html_row .= $current_fragment;
			$html_row .= "</div>";

			$html_row .= "</td>";

		

			#
			# TD_INFO
			$html_row .= "<td class=\"td_info\">";			
		
				$component_related_tipo = isset($diffusion_obj->columns['related']) ? $diffusion_obj->columns['related'] : null;
				# dump($component_related_tipo, ' related ++ '.to_string());
				switch ($component_related_tipo) {
					
					case 'component_av':

						$tc_in 		 = $diffusion_obj->columns['tc_in'];
						$tc_out 	 = $diffusion_obj->columns['tc_out'];
						$duracion_tc = $diffusion_obj->columns['duracion_tc'];
							#dump($duracion_tc, ' duracion_tc ++ '.to_string());

						if (!empty($tc_in)) {
							$html_row .= $tc_in;
							if (!empty($tc_out)) $html_row .= ' - '. $tc_out ;
						}												

						# Download fragment
		                if( !empty($duracion_tc) && $duracion_tc!=='00:00:00.000' && !empty($tc_in) && !empty($tc_out)) {

		                	if (OptimizeTC::TC2seg($duracion_tc)<=0) {
		                		$duracion_tc = '<span class="error">'.$duracion_tc.'</span>';
		                	}
		                	$html_row .= ' '.label::get_label('total').': '. $duracion_tc;
		                   
							$quality 	= DEDALO_AV_QUALITY_DEFAULT;
							$video_id 	= $diffusion_obj->columns['video_id'];

							if(SHOW_DEBUG) {
								#dump($diffusion_obj, ' $diffusion_obj');
							}							

							# DOWNLOAD BUTTON NORMAL
		                    $html_row .= "<div class=\"icon_bs link av_download_icon\" ";
					    	$html_row .= "data-video_id=\"$video_id\" data-quality=\"$quality\" data-tc_in=\"$tc_in\" data-tc_out=\"$tc_out\" data-watermark=\"0\" data-tag_id=\"$tag_id\" ";
					    	$html_row .= "data-parent=\"$parent\" data-tipo=\"$diffusion_obj->tipo\" data-top_id=\"$section_top_id\" data-top_tipo=\"$section_top_tipo\" ";
					    	$html_row .= "onclick=\"tool_av_versions.donwload_fragment(this)\" ";
					    	$html_row .= "></div>";

					    	# DOWNLOAD BUTTON WATERMARK
					    	if(file_exists(DEDALO_AV_WATERMARK_FILE)) {
					    	$html_row .= "<div class=\"icon_bs link av_download_icon_watermark\" ";
					    	$html_row .= "data-video_id=\"$video_id\" data-quality=\"$quality\" data-tc_in=\"$tc_in\" data-tc_out=\"$tc_out\" data-watermark=\"1\" data-tag_id=\"$tag_id\" ";
					    	$html_row .= "data-parent=\"$parent\" data-section_tipo =\"$section_tipo\" data-tipo=\"$diffusion_obj->tipo\" data-top_id=\"$section_top_id\" data-top_tipo=\"$section_top_tipo\" ";
					    	$html_row .= "onclick=\"tool_av_versions.donwload_fragment(this)\" ";
					    	$html_row .= "></div>";
					    	}
		                }
						break;
					
					case 'component_image':
						break;
					case 'component_geolocation':
						break;
					default:
						# code...
						break;
				}#end switch component_related_tipo
			

			$html_row .= "</td>";//end TD_INFO	



		$html_row .= "</tr>";
	}
	$html_row .= "</table>";


	$html_row .= "</td>";


	$html_row .= "</tr>";

	#echo $html_row ;
?>