<?php

	# VISUALIZADOR HTML	
	
	
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in', $modo, $lang);

	print "<div class=\"wrap_component css_wrap_date wrap_portal_list\" id=\"{$id_wrapper}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-from_modo=\"{$from_modo}\" ";
	print "data-dato='{$dato_json}' ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-component_info='{$component_info}' ";
	print ">";
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch($permissions) {
			
		case 0	:	$html_content .= ''; 		
					break;
		case 1	:
					$html_content .= " <span class=\"date_in_list css_span_dato\">";				
					
					switch ($date_mode) {

						case 'range':
							$html_content .= $valor_start;
							if (strlen($valor_end)>0) {
								$html_content .=' <> '. $valor_end;
							}
							break;

						case 'period':
							if(!empty($valor_year)) {
									$html_content .= $valor_year;
								if($valor_year>1){
									$html_content .= ' '.label::get_label('anyos').' ';
								}else{
									$html_content .= ' '.label::get_label('anyo').' ';
								}
							}
							
							if(!empty($valor_month)) {
								$html_content .= $valor_month;
								if($valor_month>1){
									$html_content .= ' '.label::get_label('meses').' ';
								}else{
									$html_content .= ' '.label::get_label('mes').' ';
								}
							}

							if(!empty($valor_day)) {
								$html_content .= $valor_day;
								if($valor_day>1){
									$html_content .= ' '.label::get_label('dias');
								}else{
									$html_content .= ' '.label::get_label('dia');
								}
							}
							break;

						case 'date':
						default:
							$html_content .= $valor ;
							break;
					}
					
					$html_content .= "</span>";
					break;

		case ($permissions>=2)	:

					if($modo =='portal_list'){
						if(empty($dato)){
							$html_content .= "<span class=\"css_date_span_edit_in_portal\" onclick=\"component_common.change_mode_component(this, '$modo','edit')\">";
							$html_content .= "</span>";
							break;	
							#$edit_class = 'css_date_span_edit_in_portal';	
						}else{
							$html_content .= "<span class=\"css_date_span\" onclick=\"component_common.change_mode_component(this, '$modo','edit')\">";
							#$edit_class = 'css_date_span';
						}
						#$html_content .= " <span class=$edit_class onclick=\"component_common.change_mode_component(this, '$modo','edit')\">";
							
					}else{
						$html_content .= "<span class=\"date_in_list css_span_dato\">";
					}

					switch ($date_mode) {

						case 'range':
							$html_content .= $valor_start;
							if (strlen($valor_end)>0) {
								$html_content .=' <> '. $valor_end;
							}
							break;

						case 'period':
							if(!empty($valor_year)) {
									$html_content .= $valor_year;
								if($valor_year>1){
									$html_content .= ' '.label::get_label('anyos').' ';
								}else{
									$html_content .= ' '.label::get_label('anyo').' ';
								}
							}
							
							if(!empty($valor_month)) {
								$html_content .= $valor_month;
								if($valor_month>1){
									$html_content .= ' '.label::get_label('meses').' ';
								}else{
									$html_content .= ' '.label::get_label('mes').' ';
								}
							}

							if(!empty($valor_day)) {
								$html_content .= $valor_day;
								if($valor_day>1){
									$html_content .= ' '.label::get_label('dias');
								}else{
									$html_content .= ' '.label::get_label('dia');
								}
							}
							break;

						case 'date':
						default:
							$html_content .= $valor ;
							break;
					}
					
					$html_content .= "</span>";
					break;							
	}	

	# Prepare content to show in page
	tools::prepare_content($html_content);

	# PRINT HTML	
	print $html_content;

	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out', $modo, $lang);
	
?>