<?php
# VISUALIZADOR HTML	

	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
		
		case ($permissions>=1) :
				
				# ETIQUETA (LABEL)
				if (!isset($this->print_options->show_label) || $this->print_options->show_label==true) {
				$html_contenido .= "\n <div class=\"print_label {$component_name}_print_label\">$label</div>";
				}
				
				# CONTENT (DATO)
				#$html_contenido .= "\n <div class=\"print_content {$component_name}_print_content\">$valor</div>";
				$html_contenido .= "\n <div class=\"print_content {$component_name}_print_content\">";
				switch ($date_mode) {
						case 'range':
							$html_contenido .= "$valor_start <> $valor_end";
							break;

						case 'period':
							# year
							$html_contenido .= $valor_year;
							if($valor_year>1){
								$html_contenido .= '<span class="css_date label_range">'.label::get_label('anyos').'</span>';
							}else{
								$html_contenido .= '<span class="css_date label_range">'.label::get_label('anyo').'</span>';
							}
							# month
							$html_contenido .= $valor_month;
							if($valor_month>1){
								$html_contenido .= '<span class="css_date label_range label_range_34">'.label::get_label('meses').'</span>';
							}else{
								$html_contenido .= '<span class="css_date label_range label_range_34">'.label::get_label('mes').'</span>';
							}
							# day
							$html_contenido .= $valor_day;
							if($valor_day>1){
								$html_contenido .= '<span class="css_date label_range">'.label::get_label('dias').'</span>';
							}else{
								$html_contenido .= '<span class="css_date label_range">'.label::get_label('dia').'</span>';
							}
							break;

						case 'time':
							$html_contenido .= $valor;
							break;

						case 'date':
						default:
							$html_contenido .= "$valor_start";
							// PREVIOUS TO 4.9.1
							//$html_content .= $valor ;

				}//end switch ($date_mode) {
				$html_contenido .= "</div>";

				break;
	}

	# PRINT HTML
	print $html_contenido;
?>