<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 		$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_date'])) 			$ar_css['css_date']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 	$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))	$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_date']))		$ar_css['css_wrap_date']='';
	
	if(!isset ($html_tools))					$html_tools='';
	
	if(isset($_REQUEST[$tipo]))					$dato = $_REQUEST[$tipo];		#var_dump($_REQUEST[$tipo]);
	
	
	#print "\n<!-- date [tipo:$tipo id_matrix:$id] -->";
	#print "\n<div class=\"css_wrap_date {$ar_css['css_wrap_date']}\" id=\"wrap_{$tipo}\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." (date)</span>";
					break;
						
		case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\">$dato</span>";
					break;	
						
		case ($permissions>=1):

					# COMPARISON OPERATORS
					$html_contenido .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);
					
					
					$html_contenido .= "<span id=\"search_component_$tipo\">";	
					$html_contenido .= "\n <input class=\"css_date {$ar_css['css_date']}\" type=\"text\" 
						name=\"{$tipo}\" 
						data-tipo=\"{$tipo}\" data-parent=\"{$parent}\" data-lang=\"{$lang}\" 
						value=\"{$valor}\" 
						title=\"$html_title\"
						/>";
					$html_contenido .= "</span>";	

					$html_contenido .= " <span class=\"css_span_ejemplo\">Format $ejemplo </span>";	

					
					# LOGICAL OPERATORS
					$html_contenido .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);
											
	}
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);

	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	#print "\n</div>\n\n"; //wrap
?>