<?php

	# VISUALIZADOR HTML	
	
	
	print "<div class=\"css_wrap_password\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content  = '';	
	$html_content .= "<input class=\"css_password\" type=\"password\" ";
	$html_content .= "name=\"{$tipo}\" ";
	$html_content .= "data-tipo=\"{$tipo}\" ";
	$html_content .= "data-modo=\"login\" ";
	$html_content .= "data-section_tipo=\"{$section_tipo}\" ";
	$html_content .= "data-parent=\"{$parent}\" ";
	$html_content .= "value=\"\" ";
	$html_content .= "title=\"$html_title\" ";
	$html_content .= "placeholder=\"$label\" ";
	$html_content .= "/>";	
	
	
	# PRINT HTML
	print $html_label;
	print $html_content;
	
	
	print "</div>"; //wrap
?>