<?php

	# VISUALIZADOR HTML		

	
	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in');

	print "<div class=\"wrap_component css_wrap_ip wrap_component_{$tipo}\" id=\"{$id_wrapper}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato=\"$dato\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-component_info='{$component_info}' ";
	print ">";
	
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch(true) {
			
		case $permissions===0	:
			$html_content .= '';
			break;
					
		case ($permissions>=1)	:
			
			$html_content .= "<span class=\"css_span_dato list_ip_dato\" ";
			$html_content .= "data-tipo=\"{$tipo}\" ";
			$html_content .= "data-section_tipo=\"{$section_tipo}\" ";
			$html_content .= "data-parent=\"{$parent}\" ";
			$html_content .= "data-lang=\"{$lang}\" ";
			$html_content .= ">";
			$html_content .= $dato;
			$html_content .= "</span>";


			# GEOIP FLAGS : geoip_info
			if (isset($geoip_info) && is_object($geoip_info)) {
				
				#$html_content .= "<span class=\"city_span\">$geoip_info->city</span>" ;
				$html_content .= '<a href="'.$geoip_info->geo_tool_link.'" target="_blank">';
				# Flag (http://cdn.whatismyipaddress.com/images/flags/mx.png)
				$flag_url 	= DEDALO_LIB_BASE_URL.'/themes/default/flags/'.$geoip_info->code.'.gif';
				$title 		= $geoip_info->continent .' '. $geoip_info->country .' '. $geoip_info->region_name;
				$html_content .= '<img src="'.$flag_url.'" class="flag_img" title="'.$title.'" />'; 
				$html_content .= '</a>';
			}
	
			
			#
			# JS Init component
			$html_content .= '<script>';
			# Init component
			$init_options = new stdClass();
				$init_options->component_name 	= $component_name;
				$init_options->wrapper_id 		= $id_wrapper;
			$html_content .= 'component_common.init('.json_encode($init_options).');';
			$html_content .= '</script>';
			break;
	}	

	
	# Prepare content to show in page
	tools::prepare_content($html_content);

	
	# PRINT HTML
	print $html_label;
	print $html_content;
	


	print "</div>";


	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out');


?>