<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?php echo DEDALO_ENTITY ?> DD Edit</title>
<?php
print css::build_tag(DEDALO_CORE_URL .'/dd/css/legacy/general.css',null,false);
print css::build_tag(DEDALO_CORE_URL .'/dd/css/legacy/edit.css',null,false);
print css::build_tag(DEDALO_CORE_URL .'/dd/css/dd_edit.css',null,false);
?>

<?php #print js::build_tag(DEDALO_CORE_URL . '/common/js/enviroment.js.php'); ?>
<script type="text/javascript">
<?php
$page_globals = new stdClass();
	# version
	$page_globals->dedalo_version 			= DEDALO_VERSION;
	# lang
	$page_globals->dedalo_application_lang 	= DEDALO_APPLICATION_LANG;
	$page_globals->dedalo_data_lang 		= DEDALO_DATA_LANG;
	$page_globals->dedalo_data_nolan 		= DEDALO_DATA_NOLAN;
	# modo
	$page_globals->modo 					= isset($modo) ? $modo : null;
?>
const page_globals=<?php echo SHOW_DEBUG===true ? json_encode($page_globals, JSON_PRETTY_PRINT) : json_encode($page_globals) ?>;

// vars
const id = '<?php echo $id ?>',
	terminoID = '<?php echo $terminoID ?>',
	esdescriptor = '<?php echo $esdescriptor ?>',
	parent = '<?php echo $parent;?>',
	head = '<?php echo $head;?>',
	debe_introducir_el_tesauro_title = '<?php echo msgJS($debe_introducir_el_tesauro_title) ?>',
	nHijos = '<?php echo $nHijos;?>',
	un_termino_con_hijos_title = '<?php echo msgJS($un_termino_con_hijos_title)?>',
	hasRelation = '<?php echo $hasRelation ?>',
	un_termino_con_descriptores_title	= '<?php echo msgJS($un_termino_con_descriptores_title)?>',
	un_no_descriptor_ha_de_depender_title	= '<?php echo msgJS($un_no_descriptor_ha_de_depender_title) ?>',
	seguro_que_quiere_desvincular_title	= '<?php echo msgJS($seguro_que_quiere_desvincular_title) ?>',
	descriptor_title = '<?php echo msgJS($descriptor_title) ?>',
	esta_seguro_de_eliminar_registro_1_title = '<?php echo msgJS($esta_seguro_de_eliminar_registro_1_title) ?>',
	debe_introducir_title = '<?php echo msgJS($debe_introducir_title)?>';
	padre_title = '<?php echo msgJS($padre_title);  ?>';

const trsND = '#relTR,#hermanosTR,#hijosTR,#modeloTR,#usableIndexTR';
</script>
<?php
# JS
print js::build_tag(DEDALO_CORE_URL . '/common/js/enviroment.js.php');
#print js::build_tag(JQUERY_LIB_URL_JS);
#print js::build_tag(JQUERY_UI_URL_JS);
print js::build_tag(DEDALO_CORE_URL . '/dd/jquery/dist/jquery.min.js');
print js::build_tag(DEDALO_CORE_URL . '/dd/jquery/dist/jquery-ui.min.js');
#print js::build_tag(DEDALO_CORE_URL . '/common/js/common.js');
#print js::build_tag(DEDALO_CORE_URL . '/login/js/login.js');
print js::build_tag(DEDALO_CORE_URL . '/dd/inc/javascript.js');
print js::build_tag(DEDALO_CORE_URL . '/dd/js/dd_common.js');
print js::build_tag(DEDALO_CORE_URL . '/dd/js/dd_edit.js');

# Aditional css / js
	print css::build_tag(DEDALO_CORE_URL . '/dd/jsoneditor/dist/jsoneditor.min.css');
	print js::build_tag(DEDALO_CORE_URL . '/dd/jsoneditor/dist/jsoneditor.min.js');

?>
</head>
<body <?php /* onBeforeUnload="closeTesaurus()" */?>>
<div id="wrapGeneral">

		<form name="form1" id="form1" method="post" onSubmit="return validar(this)" >

			<table class="table_edit">

				<tr>
					<td align="right" nowrap class="topTDround"><?php echo "$editar_title $termino_title  <strong>$terminoID</strong> "?></td>
				</tr>


				<!-- OPCIONES PRINCIPALES -->
				<tr>
					<td>
						<table class="table_opciones_principales" width="100%" border="0" cellspacing="2" cellpadding="2">
							<tr>

							<!-- ES DESCRIPTOR -->
							<td align="center" valign="top">
								<?php echo $es_descriptor_title ?><br>
								<select name="esdescriptor" id="esdescriptor" onChange="verificarDescriptor(this.value)" title="<?php echo $cambiar_tipo_title ?>">
								 <option value="si" <?php if (!(strcmp('si', $esdescriptor))) {echo "selected=\"selected\" ";} ?>><?php echo $si_title ?></option>
								 <option value="no" <?php if (!(strcmp('no', $esdescriptor))) {echo "selected=\"selected\" ";} ?>><?php echo $no_title ?></option>
								</select>
							</td>

							<?php /*
							<!-- USABLE EN INDEXACION -->
							<td align="center" valign="top"><?php echo $usable_en_title . $indexacion_title ?>
									<?php
									$selectBGcolor = false ;
									if($usableIndex=='si') $selectBGcolor = "background-color:#090;" ;
									if($usableIndex=='no') $selectBGcolor = "background-color:#FF0000;" ;
									?>
									<br>
									<select name="usableIndex" id="usableIndex" <?php echo $selectBGcolor ?> >
										<option value="si" <?php if (!(strcmp('si', $usableIndex))) {echo "selected=\"selected\" ";} ?> ><?php echo $si_title ?></option>
										<option value="no" <?php if (!(strcmp('no', $usableIndex))) {echo "selected=\"selected\" ";} ?> ><?php echo $no_title ?></option>
									</select>
									<div style="width:18px; height:18px;<?php echo $selectBGcolor ?>display:inline-block; vertical-align: middle">&nbsp;</div>
							</td>
							*/ ?>

							<!-- MODELO -->
							<td align="center"  valign="top">
								<?php
								echo ucfirst($modelo_title);
								if(SHOW_DEBUG==true || SHOW_DEVELOPER===true) echo " (esmodelo:$esmodelo)" ;
								?>
								<br>
								<?php
								# select modelos
								if($esmodelo!='si')	{
									echo "<input name=\"esmodelo\" type=\"hidden\" id=\"esmodelo\" style=\"width:30px;text-align:center\" value=\"no\" readonly>";
									include_once('dd_select_modelos.php');
								}else{
									echo "<input name=\"esmodelo\" type=\"text\" id=\"esmodelo\" style=\"width:30px;text-align:center\" value=\"si\" readonly>";
								}
								?>
							</td>

							<!-- TRADUCIBLE -->
							<td align="center" nowrap="nowrap" valign="top">
								<?php if(!empty($traducible_title)) echo ucfirst($traducible_title) ?><br>
								<select name="traducible" id="traducible">
									<option value="si" <?php if (!(strcmp('si', $traducible))) {echo "selected=\"selected\" ";} ?>><?php echo $si_title ?></option>
									<option value="no" <?php if (!(strcmp('no', $traducible))) {echo "selected=\"selected\" ";} ?>><?php echo $no_title ?></option>
								</select>
							</td>

							<!-- VISIBLE -->
							<td align="center" nowrap="nowrap" valign="top">
								<?php echo "Visible";#ucfirst($visible_title) ?><br>
								<select name="visible" id="visible">
									<option value="si" <?php if (!(strcmp('si', $visible))) {echo "selected=\"selected\" ";} ?>><?php echo $si_title ?></option>
									<option value="no" <?php if (!(strcmp('no', $visible))) {echo "selected=\"selected\" ";} ?>><?php echo $no_title ?></option>
								</select>
							</td>

							</tr>
						</table><!-- /table_opciones_principales -->
				 </td>
				</tr>
				<!-- /OPCIONES PRINCIPALES -->



				<!-- TERMINO Y TRADUCCIONES -->
				<tr>
					<td>
						<table id="terminosTable" width="100%" border="0" cellpadding="0" cellspacing="0">

							<!-- header -->
							<tr>
								<td class="td_header" style="text-align:left;"><?php echo $idioma_title ?></td>
								<td class="td_header" width="220" ><?php echo $termino_title ?></td>
								<td class="td_header" width="420" ><?php echo $definicion_title ?></td>
								<td class="td_header" width="40"  ><?php echo $nuevo_title ?></td>
							</tr>

							<!-- mainLang -->
							<tr>
								<td colspan="4" style="margin:0px;padding:0px;"><div id="div_keyup"><!-- Ajax response here codigoKeyup(termino) --></div></td>
							</tr>

							<!-- descriptors_tr -->
							<?php echo $descriptors_tr_html ?>


							<!-- traducciones header -->
							<tr>
								<td colspan="4" class="td_header" style="text-align:left;" ><?php echo $traducciones_title ?></td>
							</tr>
							<!-- traducciones descriptors grid ts_descriptors_grid.php ajax -->
							<tbody id="tbodyDescriptorsGrid">
								<!-- Ajax load grid from ts_descriptors_grid.php . need id of currrent descriptor -->
							</tbody>

						</table> <!-- /terminosTable -->
					</td>
				</tr>
				<!-- /TERMINO Y TRADUCCIONES -->



				<!-- INFORMACION -->
				<tr>
					<td class="td_header"> <?php echo $informacion_title ?></td>
				</tr>

				<!-- OBSERVACIONES -->
				<?php echo $descriptors_tr_obs_html ?>

				<!-- RELACIONES -->
				<tr>
					<td>
							<div class="div_wraper wraper_relations">
								<div class="left_div" style="padding-top:6px;">
									<?php echo $relaciones_title ?>
								</div>
								<div class="right_div">
									<div id="div_rel" style=" margin:0px; padding:0px"><!-- Ajax lista de relaciones --></div>
								</div>
							</div><!-- /div_wraper -->
					</td>
				</tr>
				<!-- /INFORMACION -->



				<!-- OTRA INFO -->
				<!-- HEADER OTRA INFO -->
				<tr>
					<td class="td_header" onClick="simpleToogleTBODY('otraInfo',this);redimensionarVentana();" style="cursor:pointer">
						<?php echo $otra_informacion_title ?> <div class="flecha_close_tboby"></div>
					</td>
				</tr>

				<!-- TBODY OTRA INFO -->
				<tbody id="otraInfo">


				<!-- PROPIEDADES (JSON) -->
				<?php if (SHOW_DEBUG===true || SHOW_DEVELOPER===true) { ?>
				<tr>
					<td>
						<div class="wraper_propiedades">
							<?php /*
							<label class="left_div propiedades_label">Propiedades (JSON)</label>
							*/ ?>
							<textarea id="propiedades" name="propiedades" class="propiedades_textarea"><?php echo $propiedades ?></textarea>
							<?php #dump($propiedades, ' propiedades ++ '.to_string()); ?>
							<div id="editor_json" class="editor_json_container"></div>
							<script>
							var propiedades_textarea_element = document.getElementById('propiedades')
							  	propiedades_textarea_element.style.display = 'none';
							  var options = {
							    mode: 'code',
							    modes: ['code', 'form', 'text', 'tree', 'view'], // allowed modes
							    error: function (err) {
							      alert(err.toString());
							    }
							  };
							  // create the editor
							  var container = document.getElementById('editor_json');
							  var editor 	= new JSONEditor(container, options, <?php echo !empty($propiedades) ? (string)$propiedades : '""' ?>);
							 	//console.log(editor);

							// Send JSON text to input and force save
							// document.getElementById('submit_button').onclick = function () {
							//	    $('#propiedades')
							//	    	.val(editor.getText())
							//	    	.trigger('change');
							// };
							</script>
							<?php /**/ ?>
						</div><!-- /div_wraper -->
					</td>
				</tr>
				<?php } #if (SHOW_DEBUG) ?>


				<!-- HIERARCHIE INFO -->
				<tr class="row_border_bottom">
					<td>
					 <table class="table_hierarchy_info">
						<?php /*
						<!-- PARENTS -->
						<tr>
							<td align="right" valign="top" nowrap  ><?php echo $jerarquia_title ?>: <?php echo $padres_title ?></td>
							<td align="center"  valign="top" nowrap bgcolor="#999999">
								<?php
								# PARENTS : SACAMOS RECURSIVAMENTE TODOS LOS PADRES QUE TENDRÁ EL TESAURO ACTUAL
								$matriz = $ar_parents_of_this;	#$padresArray['termino'];#print_r($matriz);
								$nivel = 0 ;
								if(is_array($matriz)) {
										$niveles = count($matriz)-1 ;
										foreach( $matriz as $myKey=>$value5) {
												echo "$nivel_title " ;
												echo " $nivel <br>";
												$nivel++ ;
										}
								}
								?>
							</td>
							<td align="left" style="font-size:9px;">
								<?php
								# ordenamos inversamente los padres
								$nivel = 0 ;
								if(is_array($matriz)) {
										krsort($matriz);
										$niveles = count($matriz)-1 ;
										foreach( $matriz as $key => $value) {
												echo $value . '<br> ';
												$nivel++ ;
										}
								}
								?>
							</td>
						</tr>
						<!-- /PARENTS -->


						<!-- HERMANOS -->
						<tr id="hermanosTR">
						 <td align="right" valign="top" nowrap  ><?php echo $hermanos_title ?> </td>
						 <td align="center" valign="top" nowrap bgcolor="#999999">
								<?php echo "$nivel_title ". ($nivel)   ?>
						 </td>
						 <td align="left">
								<div style="max-height:70px; overflow:auto" >
								<?php
								$nivel +1 ;

								# HERMANOS : Array de hermanos del término actual
								if(is_array($ar_siblings)) {
									foreach($ar_siblings as $current_terminoID) {
										$ar_hermanosNombres[]	= RecordObj_dd::get_termino_by_tipo($current_terminoID);
									}
									echo implode(', ',$ar_hermanosNombres);
								}
								?>
								</div>
						 </td>
						</tr>
						<!-- /HERMANOS -->


						<!-- HIJOS -->
						<tr id="hijosTR">
						 <td align="right" nowrap  ><?php echo $hijos_directos_title ?></td>
						 <td align="center" nowrap bgcolor="#999999"  ><?php echo "$nivel_title " . ($nivel+1);  ?></td>
						 <td align="left"  >
								<div style="max-height:70px; overflow:auto" >
								<?php
								# HIJOS : Mostramos el deglose de hijos del término actual desde el array de datos
								$sizeOf_hijosArray = sizeof($hijosArray);
								$n=0;
								if(is_array($hijosArray)) foreach($hijosArray as $hijoActual) {
										#echo $hijoActual ;
										echo RecordObj_dd::get_termino_by_tipo($hijoActual);
										$n++;
										if($n < $sizeOf_hijosArray) echo ', ';
										#echo ",($sizeOf_hijosArray)";
								}
								?>
								</div>
						 </td>
						</tr>
						<!-- /HIJOS -->
						<?php */ ?>

						<!-- PARENT : Dependiente de (padre) -->
						<tr >
						 <td align="right" nowrap  ><?php echo $dependiente_de_title ?> </td>
						 <td align="center" nowrap ><?php echo $parentInicial = $parent ; ?></td>
						 <td align="left" nowrap  >
								<?php echo $cambiar_a_title ?>
								<input name="parent" type="text" id="parent" style="width:90px; text-align:center" value="<?php echo $parent ?>" onFocus="myfocus(this)" onBlur="myblur(this)">
								<span class="anotacionTexto">(<?php echo $al_cambiar_el_padre_title ?>)</span>
						 </td>
						</tr>
						<!-- /PARENT : Dependiente de (padre) -->

					 </table><!-- /table_hierarchy_info -->
					</td>
				</tr>

				</tbody><!-- /otraInfo -->



				<!-- SUBMIT -->
				<tr>
					<td style="padding:10px; text-align:center">
						<div class="form_buttons">
							<input type="hidden" name="terminoID" value="<?php echo $terminoID # el terminoID devuelto por por la búsqueda.(idem que el get) ?>">

							<!-- Campos obligatorios -->
							<input type="hidden" name="parentInicial" value="<?php echo $parent ?>" >
							<input type="hidden" name="nHijos" value="<?php echo $nHijos ?>">

							<input type="hidden" name="MM_insert" value="form1">
							<input type="hidden" name="accion" value="editTS">

							<input type="submit" id="submit_button" name="Submit" value="  <?php echo $modificar_title ?>  " class="SubmitButon" onClick="submit(this)">
							<script type="text/javascript">
							// Send JSON text to input and force update
							document.getElementById('submit_button').onclick = function () {
								$(propiedades_textarea_element)
										.val(editor.getText())
							   			.trigger('change');
							}
							</script>

							<input name="cancelar" type="button" value=" <?php echo $cerrar_title ?> "  onClick="javascript:window.close();">

							<input name="export" type="button" value=" Export " onClick="export_ontology('<?php echo $terminoID ?>');">
						</div><!-- /form_buttons -->
					</td>
				</tr>
				 <!-- /SUBMIT -->


			</table><!-- /table_edit -->
		</form>


</div><!-- wrapGeneral -->
</body>
</html>
