<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>D4 TS</title>
<?php
print css::build_tag(DEDALO_LIB_BASE_URL .'/dd/css/legacy/general.css',null,false);
print css::build_tag(DEDALO_LIB_BASE_URL .'/dd/css/legacy/edit.css',null,false);
print js::build_tag(JQUERY_LIB_URL_JS);
?>
<script type="text/javascript">
// vars 
const debe_introducir_title_orden_title = '<?php echo msgJS("$debe_introducir_title N. $orden_title") ?>';

function validar(form1) {
	if (document.form1.ordenNuevo.value.length < 1)
	{
     	alert(debe_introducir_title_orden_title);
	 	form1.ordenNuevo.focus();	
		  
     	return (false);
  	}  
  return (true); 
}

$(function() {
  $('#ordenNuevo').focus()
	//onblur="close()"	
}); // FIN domready AJAX  formularios

</script>
</head>

<body>

<div id="wrapGeneral">
<form name="form1" id="form1" method="post"  onSubmit="return validar(this)" action="?accion=norden"  >
<table width="100%"  border="0" cellpadding="5" cellspacing="5" >
    <tr>
      <th colspan="3" align="left" nowrap="nowrap"  class="blanco" bgcolor="#333333"><?php echo $modificar_title ?> <?php echo $orden_title ?> <?php echo $listado_title ?></th>
      </tr>
    <tr>
      <td align="right" nowrap="nowrap"><?php echo $tesaurus_title ?></td>
      <td colspan="2" align="left"><strong><?php echo $terminoget ?></strong></td>
      </tr>
    <tr>
    <td align="right" nowrap="nowrap">
    Nº  <?php echo $orden_title ?> <?php echo $actual_title ?></td>
    <td width="95" align="center"><strong><?php echo $nordenV ?></strong></td>
    <td width="818" align="left">terminoID: <?php echo $terminoIDget ?></td>
    </tr>
    <tr>
      <td width="87" align="right" nowrap="nowrap"><?php echo $cambiar_por_title ?></td>
      <td align="center">
      <input type="text" name="ordenNuevo" id="ordenNuevo" style="width:60px; text-align:center" />
      </td>
      <td align="left">&nbsp;</td>
    </tr>
    <tr>
      <td width="87" align="right" nowrap="nowrap">
      <span class="anotacionTexto">
      <?php
      if(SHOW_DEBUG==true) echo "estaOrdenado: $estaOrdenado" ; 
      ?>
      </span>
      <input type="hidden" name="terminoID" value="<?php echo $terminoIDget ?>" />
      <input type="hidden" name="ordenActual" value="<?php echo $nordenV ?>" />
      <input type="hidden" name="ordenF" value="<?php echo $ordenF ?>" />
      <input type="hidden" name="parent" value="<?php echo $padre ?>" />
      </td>
      <td align="center"><input type="submit" name="Submit" value="  <?php echo $modificar_title ?>  "  class="SubmitButon" /></td>
      <td align="left"><input name="cancelar" type="button" value=" <?php echo $cerrar_title ?> "  class="flechas"  onclick="javascript:window.close();" /></td>
    </tr>
</table>
</form>
</div>
</body>
</html>