<?php

	# VISUALIZADOR HTML

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in');

	$wrap_style = isset($wrap_style) ? $wrap_style : '';

	print "<div class=\"css_wrap_iri wrap_component wrap_component_{$modo} wrap_component_{$tipo}\" id=\"{$id_wrapper}\" ";
	print "style=\"$wrap_style\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato='{$dato_json}' ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-component_info='{$component_info}' ";
	print ">";
	

		# ETIQUETA (LABEL)
		$html_label = component_common_draw::draw_label($this);

		# CONTENIDO (INPUT)
		$html_content = '';
		switch(true) {

			case ($permissions===0) :
					$html_content .= "";
					break;

			case ($permissions===1) :
					foreach ($dato as $value) {
						$html_content .= " <span class=\"css_span_dato\">$value</span>";
						# Button link
						$html_content .= "<a class=\"input-group-addon css_button_generic btn_go_iri\" onclick=\"component_iri.go_iri_link(this)\">";
						$html_content .= "<div class=\"link css_iri_link\"></div>";
						$html_content .= "</a>";
					}
					break;

			case ($permissions>=2) :

				# Avoid autocomplete input username in Users section
				$remove_autocomplete = null;
				if ($section_tipo==DEDALO_SECTION_USERS_TIPO) {
					$remove_autocomplete = "readonly onfocus=\"this.removeAttribute('readonly');component_common.select_wrap(null,'$id_wrapper');\"";
				}else{
					$remove_autocomplete = '';//"onfocus=\"component_common.select_wrap(null,'$id_wrapper')\";\"";
					$remove_autocomplete = "onfocus=\"component_common.select_wrap_on_tab_focus(this,'$id_wrapper')\"";
				}

				# Read only mode (set in propiedades)
				$read_only = null;
				if (isset($propiedades->read_only) && $propiedades->read_only==true) {
					$read_only = 'readonly';
				}
				#IRI content
				$html_content .= "<div class=\"css_iri_content\">";


					if(empty($dato)){
						$obj_value = new stdClass();
						$obj_value->iri = "";
						$dato_view = array($obj_value);						
					}else{
						$dato_view = $dato;
					}

					$html_content .= "<ul>";
					foreach ($dato_view as $key => $obj_value) {

						if(isset($obj_value->iri)){
							# Correct issues with quotes
							$value_iri = htmlentities($obj_value->iri);
						}else{
							$value_iri = "";
						}

						if(isset($obj_value->title)){
							# Correct issues with quotes
							$value_title = htmlentities($obj_value->title);
						}else{
							$value_title = "";
						}

						$html_content .= "<li class=\"input-group\">";

						# Title
						$css_optional='';
						if(!$use_title){
							$css_optional='css_iri_off';
						}
							$html_content .= "<input type=\"text\" id=\"{$id_wrapper}_input_{$key}\" class=\"css_iri $css_optional\" onchange=\"component_iri.Save(this)\" ";
							$html_content .= "data-tipo=\"{$tipo}\" ";
							$html_content .= "data-section_tipo=\"{$section_tipo}\" ";
							$html_content .= "data-parent=\"{$parent}\" ";
							$html_content .= "data-lang=\"{$lang}\" ";
							$html_content .= "data-mandatory='{$mandatory_json}' ";
							$html_content .= "value=\"{$value_title}\" ";
							$html_content .= "title=\"$html_title\" ";
							$html_content .= "name=\"{$input_name}\" ";
							$html_content .= 'placeholder="'.label::get_label('title').'" ';
							$html_content .= "autocomplete=\"off\" ";
							$html_content .= $remove_autocomplete." ";
							$html_content .= $read_only." ";
							$html_content .= "tabindex=\"1\" ";
							$html_content .= "/>";


						# IRI
						$html_content .= "<input type=\"url\" id=\"{$id_wrapper}_input_url_{$key}\" class=\"css_iri\" onchange=\"component_iri.Save(this)\" ";
						$html_content .= "onfocus=\"component_iri.validate_iri(this)\" ";
						$html_content .= "data-tipo=\"{$tipo}\" ";
						$html_content .= "data-section_tipo=\"{$section_tipo}\" ";
						$html_content .= "data-parent=\"{$parent}\" ";
						$html_content .= "data-lang=\"{$lang}\" ";
						$html_content .= "data-mandatory='{$mandatory_json}' ";
						$html_content .= "data-source_for_component=\"{$source_for_component}\" ";
						$html_content .= "value=\"{$value_iri}\" ";
						$html_content .= "title=\"$html_title\" ";
						$html_content .= "name=\"{$input_name}\" ";
						$html_content .= "placeholder=\"http://\" ";
						$html_content .= 'pattern="(https?)?:\/\/.*\..+" ';
						$html_content .= "autocomplete=\"off\" ";
						$html_content .= $remove_autocomplete." ";
						$html_content .= $read_only." ";
						$html_content .= "tabindex=\"2\" ";
						$html_content .= "/>";

						# Button link
						$html_content .= "<a class=\"input-group-addon css_button_generic btn_go_iri\" onclick=\"component_iri.go_iri_link(this)\">";
						$html_content .= "<div class=\"link css_iri_link\"></div>";
						$html_content .= "</a>";

						$html_content .= "</li>";
						
					}//end foreach
					$html_content .= "</ul>";

					# Button add

					$css_optional='';
					if(!$multiple_value){
						$css_optional='css_iri_off';
					}
					$html_content .= "<div class=\"css_button_generic btn_add_iri $css_optional\" onclick=\"component_iri.add_iri(this)\">";
					$html_content .= "<div class=\"link css_iri_add\"></div>";
					$html_content .= "</div>";
					

				#end IRI content
				$html_content .= "</div>";

				if(SHOW_DEBUG===true) {
					$html_content .= " <span class=\"debug_info notes\">".$dato_json."</span>";
				}

				#
				# JS Init component
				$html_content .= '<script>';
				# Init component
				$init_options = new stdClass();
					$init_options->component_name 	= $component_name;
					$init_options->wrapper_id 		= $id_wrapper;
				$html_content .= 'component_common.init('.json_encode($init_options).');';
				$html_content .= '</script>';
				break;
		}

		# Prepare content to show in page
		tools::prepare_content($html_content);


		# PRINT HTML
		print $html_label;
		print $html_content;


	print "</div><!-- /css_wrap_iri ".__CLASS__." [tipo:$tipo section_id_matrix:$parent] $label -->"; //wrap


	// First test on load element
	if ($mandatory===true) {
		echo "<script>component_iri.mandatory('{$id_wrapper}')</script>";
	}

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out');

?>