/**
 * THE AGENT AUTHORIZATION — the one host artifact that lets a non-root daemon start a turn
 * under a DIFFERENT uid, and lets it do nothing else.
 *
 * WHY IT HAS TO EXIST. The confinement this subsystem now depends on
 * (`src/drivers/confinement.ts`) runs each agent turn as a transient systemd service owned
 * by `identity.agentUser`, because the kernel draws no boundary between a process and
 * itself: while the turn ran as the daemon's own uid, `$CREDENTIALS_DIRECTORY`, the
 * provider keys and the audit handle were all readable to it whatever the unit's
 * `Protect*` directives said. Starting a unit as another uid is PID 1's job, and asking PID
 * 1 for it is a privileged operation. So either the daemon is root (it is not, and must
 * never be), or the host says in writing which non-root caller may ask for what — which is
 * what polkit is, and this file is that sentence.
 *
 * WHY IT IS RENDERED AND NOT DOCUMENTED. A hand-written rule is a second owner of the
 * museum's identity: it would state the service user and the unit prefix again, in a file
 * nothing compares against the layout, and the failure mode is silent in the dangerous
 * direction — a stale rule keeps authorizing a name that has moved, or authorizes more than
 * the prefix it was meant to. Rendered from `layout.identity` and `layout.agentUnitPrefix`,
 * it cannot disagree with the daemon that will invoke it.
 *
 * THE GRANT, EXACTLY. Subject: this instance's service user, by name. Action:
 * `org.freedesktop.systemd1.manage-units`. Object: a unit whose name STARTS WITH this
 * museum's agent prefix and ends in `.service`. Verbs: start, stop, kill — never enable,
 * never reload the manager, never anything about a unit installed on the host. Everything
 * else falls through as NOT_HANDLED, so this file can only ever ADD the one permission it
 * names; it cannot take one away or widen another rule.
 *
 * The renderer law of ./types.ts applies here as everywhere: pure, zero-dep, stamped, and
 * carrying no credential. The stamp is a `//` comment, because polkit rules are JavaScript.
 */

import type { InstanceLayout } from '../layout';
import { UNIX_NAME_PATTERN } from '../layout';
import type { Renderer } from './types';
import { artifact } from './types';

/** The polkit action a transient unit start is checked against. */
export const MANAGE_UNITS_ACTION = 'org.freedesktop.systemd1.manage-units';

/** The verbs a turn needs, and the complete set this rule will ever answer YES to. */
export const AGENT_UNIT_VERBS = Object.freeze(['start', 'stop', 'kill']);

/**
 * A value that becomes a JavaScript string literal inside a root-installed rule file.
 *
 * Refused rather than escaped, for the same reason `render/unit.ts` refuses a newline in a
 * unit value: the grammars that would have to be escaped correctly here are two (JavaScript
 * string escapes and polkit's own file parsing), the strings this file interpolates are all
 * held to `UNIX_NAME_PATTERN` or built from it, and an escape is a property every future
 * call site would have to get right while a grammar is a property of the value.
 */
function ruleLiteral(label: string, value: string, pattern: RegExp): string {
  if (typeof value !== 'string' || !pattern.test(value)) {
    throw new Error(
      `render(agent_authorization): ${label} '${String(value)}' does not match ${pattern.source}. ` +
        `It becomes a JavaScript string in a root-installed polkit rule, where a quote or a ` +
        `backslash would end the literal and the rest would be code. Nothing was rendered.`,
    );
  }
  return value;
}

/** The unit-name prefix grammar: the service user's own naming, plus the trailing dash. */
const UNIT_PREFIX_PATTERN = /^[a-z][a-z0-9-]{2,60}-$/;

export const agentAuthorizationRenderer: Renderer = {
  kind: 'agent_authorization',

  render(layout: InstanceLayout) {
    const user = ruleLiteral('identity.user', layout.identity.user, UNIX_NAME_PATTERN);
    const agentUser = ruleLiteral('identity.agentUser', layout.identity.agentUser, UNIX_NAME_PATTERN);
    const prefix = ruleLiteral('agentUnitPrefix', layout.agentUnitPrefix, UNIT_PREFIX_PATTERN);
    const verbs = AGENT_UNIT_VERBS.map(verb => `"${verb}"`).join(', ');

    const body = [
      `// GENERATED by publication/site_builder/src/provision/render/agent_authorization.ts`,
      `// — do NOT edit. A hand edit is reported as drift and re-rendered away.`,
      `//`,
      `// Instance: ${layout.instance}`,
      `//`,
      `// WHAT THIS AUTHORIZES, AND NOTHING ELSE: the service user '${user}' may start, stop`,
      `// and kill TRANSIENT units named '${prefix}<id>.service'. Those are agent turns, run`,
      `// as '${agentUser}' so that a turn is not the daemon and cannot read the daemon's`,
      `// credentials. It authorizes no other unit, no other verb and no other user; every`,
      `// other question falls through to whatever else this host decided.`,
      `polkit.addRule(function (action, subject) {`,
      `  if (action.id !== "${MANAGE_UNITS_ACTION}") {`,
      `    return polkit.Result.NOT_HANDLED;`,
      `  }`,
      `  if (subject.user !== "${user}") {`,
      `    return polkit.Result.NOT_HANDLED;`,
      `  }`,
      `  var unit = action.lookup("unit");`,
      `  if (typeof unit !== "string") {`,
      `    return polkit.Result.NOT_HANDLED;`,
      `  }`,
      `  // Anchored at BOTH ends: a prefix test alone would authorize`,
      `  // '${prefix}x.service.wanted' style names and anything a future systemd spells`,
      `  // with this stem, and this grant must cover transient services only.`,
      `  if (unit.indexOf("${prefix}") !== 0) {`,
      `    return polkit.Result.NOT_HANDLED;`,
      `  }`,
      `  if (unit.substr(unit.length - 8) !== ".service") {`,
      `    return polkit.Result.NOT_HANDLED;`,
      `  }`,
      `  var verb = action.lookup("verb");`,
      `  var allowed = [${verbs}];`,
      `  if (allowed.indexOf(verb) === -1) {`,
      `    return polkit.Result.NOT_HANDLED;`,
      `  }`,
      `  return polkit.Result.YES;`,
      `});`,
    ].join('\n');

    return [
      artifact(layout, {
        kind: 'agent_authorization',
        path: layout.agentPolicyPath,
        // Read by polkitd running as root: 0644 root:root, like the unit and the vhosts.
        mode: 'hostConfig',
        body: `${body}\n`,
        commentPrefix: '//',
      }),
    ];
  },
};
