-- =============================================================================
-- rag_embeddings.sql — THE Dédalo vector-store schema.
--
-- WHAT IT IS. The DDL of the SEPARATE pgvector database the RAG subsystem
-- reads and writes (src/ai/rag/vector_store.ts): the `rag_embeddings` parent
-- table, its non-vector + lexical indexes, and the
-- `rag_create_model_partition(model, dimension)` provisioner every write door
-- calls before its first upsert. Apply it to the vector database, never to the
-- matrix database:
--
--     createdb dedalo7_rag
--     psql -d dedalo7_rag -f install/db/rag_embeddings.sql
--
-- WHY IT IS VENDORED HERE (2026-08-30, audit 2026-08-26 P1-16). Until now this
-- DDL existed only as a fenced block a human was told to copy out of
-- docs/core/ai/rag_cookbook.md. That was survivable while provisioning was a
-- once-per-install manual step; it stopped being survivable the moment the
-- SUITE needed its own vector database, because `bun run test:db:setup` has to
-- BUILD one on every rebuild and a build step cannot read prose. The cookbook
-- now points at this file, so there is ONE copy of the schema and a drifting
-- second one cannot exist.
--
-- It is idempotent (CREATE … IF NOT EXISTS / CREATE OR REPLACE), so re-applying
-- it to an existing vector database is a no-op — which is what makes it safe to
-- run from both the operator's install procedure and the suite's fixture build.
--
-- STILL NOT A MIGRATION. install/db/migrations/ belongs to the MATRIX database
-- (install/db/migrate.ts runs it at boot against `config.db`); this database is
-- a different server credential and is optional in an install that never
-- enables RAG, so it is not in that runner. Applying this file is the
-- provisioning step; docs/core/ai/rag.md names it.
--
-- Distance is COSINE throughout. The `<=>` operator must always pair with
-- vector_cosine_ops / halfvec_cosine_ops or the planner silently falls back to
-- a sequential scan.
-- =============================================================================

-- 1. Extensions + the immutable unaccent wrapper the lexical index/query use.
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE OR REPLACE FUNCTION f_unaccent(text)
  RETURNS text
  LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT
AS $$ SELECT public.unaccent('public.unaccent', $1) $$;

-- 2. The embeddings parent table — PARTITIONED BY LIST (model). One physical
--    child partition per embedding model (see the function below); cosine space
--    is never compared across models, and text vs image vectors stay isolated.
CREATE TABLE IF NOT EXISTS rag_embeddings (
    id             bigint       GENERATED BY DEFAULT AS IDENTITY,
    section_tipo   varchar(64)  NOT NULL,
    section_id     integer      NOT NULL,
    component_tipo varchar(64)  NOT NULL,
    lang           varchar(16)  NOT NULL,
    chunk_index    integer      NOT NULL,
    provider       varchar(64)  NOT NULL,
    model          varchar(128) NOT NULL,
    dimension      integer      NOT NULL,
    embedding      vector       NOT NULL,
    source_hash    char(64)     NOT NULL,   -- sha256(CHUNKER_VERSION|embedText)
    source_text    text,                    -- clean text, stored for citation
    token_count    integer,
    modality       varchar(16)  NOT NULL DEFAULT 'text',   -- text | image
    source_kind    varchar(32)  NOT NULL DEFAULT 'text',
    egress_class   varchar(16)  NOT NULL DEFAULT 'public',
    parent_key     varchar(255),            -- structural section (small-to-big)
    chunk_meta     jsonb,                   -- view / thumb_url / page / tc / …
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    -- The partition key (model) + dimension MUST be in the PK of a partitioned table.
    PRIMARY KEY (section_tipo, section_id, component_tipo, lang, chunk_index, model, dimension)
) PARTITION BY LIST (model);

-- 3. Parent indexes (propagate to every child partition).
CREATE INDEX IF NOT EXISTS rag_embeddings_record_idx
    ON rag_embeddings (section_tipo, section_id);
CREATE INDEX IF NOT EXISTS rag_embeddings_component_idx
    ON rag_embeddings (section_tipo, component_tipo, lang);
-- Lexical (hybrid) leg: accent-folded FTS. MUST match the query expression
-- exactly (retrieval uses to_tsvector('simple', f_unaccent(...))) or it won't hit.
CREATE INDEX IF NOT EXISTS rag_embeddings_lexical_idx
    ON rag_embeddings USING gin (to_tsvector('simple', f_unaccent(coalesce(source_text, ''))));

-- 4. The per-model partition provisioner. The store calls this idempotently on
--    every write (SELECT rag_create_model_partition(model, dimension)); it creates
--    the child table + its HNSW cosine index. halfvec above the 2000-dim ceiling.
CREATE OR REPLACE FUNCTION rag_create_model_partition(
    p_model text,
    p_dimension integer,
    p_hnsw_m integer DEFAULT 16,
    p_hnsw_ef_construction integer DEFAULT 64
) RETURNS void
  LANGUAGE plpgsql
AS $function$
DECLARE
    v_child   text := 'rag_embeddings_' || regexp_replace(lower(p_model), '[^a-z0-9_]+', '_', 'g');
    v_index   text := v_child || '_hnsw_idx';
    v_cast    text;
    v_opclass text;
BEGIN
    IF p_dimension > 2000 THEN
        v_cast := format('halfvec(%s)', p_dimension); v_opclass := 'halfvec_cosine_ops';
    ELSE
        v_cast := format('vector(%s)', p_dimension);  v_opclass := 'vector_cosine_ops';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = v_child) THEN
        EXECUTE format('CREATE TABLE %I PARTITION OF rag_embeddings FOR VALUES IN (%L)', v_child, p_model);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = v_index) THEN
        EXECUTE format(
            'CREATE INDEX %I ON %I USING hnsw ((embedding::%s) %s) WITH (m=%s, ef_construction=%s)',
            v_index, v_child, v_cast, v_opclass, p_hnsw_m, p_hnsw_ef_construction);
    END IF;
END;
$function$;
