<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 		$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_html_text'])) 		$ar_css['css_html_text']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 	$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))	$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_html_text']))	$ar_css['css_wrap_html_text']='';
	
	if(!isset ($html_tools))					$html_tools='';
	
	
	print "\n<!-- COMPONENT_HTML_TEXT [tipo:$tipo section_id_matrix:$parent] $label -->";
	print "\n<div class=\"css_wrap_html_text wrap_component {$ar_css['css_wrap_html_text']}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\" data-section_tipo=\"{$section_tipo}\" data-parent=\"{$parent}\" data-lang=\"{$lang}\" data-modo=\"{$modo}\" data-dato=\"{$dato_raw}\" data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}' >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {	
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> No access here (html_text)! </span>";	
					break;
						
		case 1	: 	#$html_contenido .= "\n<div class=\"html_text_content html_text_content_shadow\" >";
					$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\">$dato</span>";
					#$html_contenido .= "\n</div>"; #end html_text_content

					##
					# WRAP CURRENT SELECTED FRAGMENT (RELATION / ADD PORTAL BUTTON) 
					#
					$html_contenido .= "\n <div id=\"relations_ajax_div_{$tipo}\" class=\"wrap_fragment\" 
					data-tipo=\"{$tipo}\" data-section_tipo=\"{$section_tipo}\" data-parent=\"{$parent}\" data-modo=\"selected_fragment\" data-lang=\"{$lang}\" data-context_name=\"$context_name\"
					data-caller_id=\"$caller_id\" data-component_name=\"$component_name\"
					>
					<div class=\"content_data\"><!-- AJAX CONTENT HERE --></div>
					</div>";

						
					break;	
						
		
		case ($permissions>=2)	:

					/*
					# Dato reference default lang
					if ($modo!='tool_lang' && !empty($default_component)) {
						#$html_contenido .= "\n <div class=\"dato_refecence_default_lang\">$dato_reference_lang</div>";						
						# Fijamos el lenguaje actual como el de destino para el tool_lang
						$html_contenido .= "<script>set_localStorage('last_target_lang','$lang')</script>";
						$tool_lang = new tool_lang($default_component,'button');
							#dump($tool_lang,'$tool_lang');
						$html_contenido .= $tool_lang->get_html();
					}
					*/


					if (is_object($context_name)) {
						$context_name_text = isset($context_name->context_name) ? $context_name->context_name : '';
					}else{
						$context_name_text = $context_name;
					}
					

					##
					# Text area  contenteditable=\"true\"
					#					
					$html_contenido .= "\n <textarea class=\"css_html_text {$ar_css['css_html_text']}\" 
					id=\"{$identificador_unico}\" 
					name=\"{$input_name}\" 
					data-tipo=\"{$tipo}\"
					data-lang=\"{$lang}\"
					data-section_tipo=\"{$section_tipo}\"
					data-parent=\"{$parent}\"
					data-context_name=\"$context_name_text\"
					title=\"$html_title\">$dato</textarea>";					
					
					
					if (SHOW_DEBUG) {
						#$html_contenido .= "<span class=\"debug_info\"> $identificador_unico</span>";
					}			

		
			if($permissions==3)	
					
					#$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$tipo}\" >{$debugger}</span>";
					break;							
	}

	# INIT : Init text editor	
	$html_contenido .= "\n<script>$(function(){component_html_text_editor.init('$identificador_unico','$modo','$propiedades_json');});</script>";
	
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);

	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_html_text  $label -->\n\n"; //wrap	
?>

