<?php

	# VISUALIZADOR HTML

	#echo "\n<!-- TEXT AREA [tipo:$tipo id_matrix:$id] -->";

	echo "<div class=\"css_html_text_wrap\" >";
	
	# ETIQUETA (LABEL)
	#$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0:		
			$html_contenido .= "\n <span class=\"css_span_dato\"> No access here (html_text)! </span>";	
					break;
						
		case ($permissions>=1):
		
			$html_contenido .= "<span class=\"css_span_dato\" data-tipo=\"{$tipo}\" data-section_tipo=\"{$section_tipo}\" data-parent=\"{$parent}\" data-lang=\"{$lang}\">$valor</span>";
			
			
			if($permissions==3) {
				$html_contenido .= "<span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
			}
			break;
	}
	
	
	# PRINT HTML
	print $html_contenido;
	
	
	echo "</div>"; //wrap
?>