<?php

	# VISUALIZADOR HTML		
	
	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in', $modo, $lang);

	print "<div class=\"wrap_component css_wrap_html_text wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-lang=\"{$lang}\"
	data-modo=\"{$modo}\"
	data-dato=\"{$dato_raw}\"
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch(true) {	
			
		case $permissions===0	:
					$html_contenido .= "";	
					break;
						
		case $permissions===1	: 	#$html_contenido .= "<div class=\"html_text_content html_text_content_shadow\" >";
					$html_contenido .= "<span class=\"css_span_dato\">$dato</span>";
					#$html_contenido .= "</div>"; #end html_text_content

					##
					# WRAP CURRENT SELECTED FRAGMENT (RELATION / ADD PORTAL BUTTON) 
					#
					$html_contenido .= "<div id=\"relations_ajax_div_{$tipo}\" class=\"wrap_fragment\" ";
					$html_contenido .= "data-tipo=\"{$tipo}\" ";
					$html_contenido .= "data-section_tipo=\"{$section_tipo}\" ";
					$html_contenido .= "data-parent=\"{$parent}\" ";
					$html_contenido .= "data-modo=\"selected_fragment\" ";
					$html_contenido .= "data-lang=\"{$lang}\" ";
					$html_contenido .= "data-context_name=\"$context_name\" ";
					$html_contenido .= "data-caller_id=\"$caller_id\" ";
					$html_contenido .= "data-component_name=\"$component_name\" ";
					$html_contenido .= ">";
					$html_contenido .= "<div class=\"content_data\"><!-- AJAX CONTENT HERE --></div>";
					$html_contenido .= "</div>";
					break;						
		
		case ($permissions>=2)	:

					/*
					# Dato reference default lang
					if ($modo!='tool_lang' && !empty($default_component)) {
						#$html_contenido .= " <div class=\"dato_refecence_default_lang\">$dato_reference_lang</div>";
						# Fijamos el lenguaje actual como el de destino para el tool_lang
						$html_contenido .= "<script>set_localStorage('last_target_lang','$lang')</script>";
						$tool_lang = new tool_lang($default_component,'button');
							#dump($tool_lang,'$tool_lang');
						$html_contenido .= $tool_lang->get_html();
					}
					*/					

					##
					# Text area
					#					
					$html_contenido .= "<textarea class=\"css_html_text\" ";
					$html_contenido .= "id=\"{$identificador_unico}\" ";
					$html_contenido .= "name=\"{$input_name}\" ";
					$html_contenido .= "data-tipo=\"{$tipo}\" ";
					$html_contenido .= "data-lang=\"{$lang}\" ";
					$html_contenido .= "data-section_tipo=\"{$section_tipo}\" ";
					$html_contenido .= "data-parent=\"$parent\" ";
					$html_contenido .= "data-context_name=\"$context_name\" ";
					$html_contenido .= "title=\"$html_title\">";
					$html_contenido .= $dato;
					$html_contenido .= "</textarea>";

	
					# INIT : Init text editor					
					$html_contenido .= "<script>";
					$html_contenido .= "component_html_text.init({\"uid\":\"{$identificador_unico}\",\"modo\":\"{$modo}\",\"traducible\":\"{$traducible}\",\"propiedades_json\":$propiedades_json});";
					$html_contenido .= "</script>";


					if (SHOW_DEBUG) {
						#$html_contenido .= "<span class=\"debug_info\"> $identificador_unico</span>";					
						#$html_contenido .= " <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";
					}
					break;
	}	
	
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "</div>"; //wrap

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out', $modo, $lang);


?>