<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 		$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_html_text'])) 		$ar_css['css_html_text']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 	$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))	$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_html_text']))	$ar_css['css_wrap_html_text']='';
	
	if(!isset ($html_tools))					$html_tools='';
	
	
	print "\n<!-- HTML_TEXT [tipo:$tipo id_matrix:$id] $label -->";
	print "\n<div class=\"css_wrap_html_text wrap_component html_text_tool_lang {$ar_css['css_wrap_html_text']}\" id=\"{$id_wrapper}\"
	data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-parent=\"{$parent}\" data-lang=\"{$lang}\" data-modo=\"{$modo}\" data-dato=\"{$dato_raw}\" data-component_name=\"{$component_name}\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);#."<span class=\"debug_info\"> $identificador_unico</span>";
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	

			$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> No access here (html_text)! </span>";	
			break;
						
		case 1	: 	

			$html_contenido .= "\n<div class=\"html_text_content html_text_content_shadow\" >";
			$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\">$dato</span>";
			$html_contenido .= "\n</div>"; #end html_text_content			
			break;						
		
		case ($permissions>=2)	:

			#
			# Text area
			#
			$html_contenido .= "\n <textarea class=\"css_html_text \" 
			id=\"{$identificador_unico}\" 
			name=\"{$input_name}\" 
			data-tipo=\"{$tipo}\" data-id_matrix=\"{$id}\" data-lang=\"{$lang}\" data-parent=\"{$parent}\" data-last_tag_index_id=\"{$last_tag_index_id}\"
			title=\"$html_title\">$dato</textarea>";

			# Init text editor
			#$html_contenido .= '<script>text_editor.init("'.$identificador_unico.'");</script>';	


			if (SHOW_DEBUG) {
			$html_contenido .= "<span class=\"debug_info\"> $identificador_unico</span>";
			}			


			if($permissions==3)						
			$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$debugger}</span>";
			
			break;							
	}

	# INIT : Init text editor 
	$html_contenido .= "\n<script>component_html_text_editor.init('$identificador_unico','$modo','$propiedades_json');</script>";
	
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);

	
	# PRINT HTML
	print $html_label;
	print $html_contenido;

	
	
	print "\n</div><!-- /css_wrap_html_text  $label -->\n\n"; //wrap
?>
