<?php

	# VISUALIZADOR HTML	
	
	
	print "<!-- HTML_TEXT [tipo:$tipo section_id_matrix:$parent] $label -->";

	print "<div class=\"css_wrap_html_text wrap_component html_text_tool_lang\" id=\"{$id_wrapper}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato=\"{$dato_raw}\" ";
	print "data-component_name=\"{$component_name}\" ";
	print ">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);#."<span class=\"debug_info\"> $identificador_unico</span>";
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	

			$html_contenido .= " <span class=\"css_span_dato\"> No access here (html_text)! </span>";	
			break;
						
		case 1	: 	

			$html_contenido .= "<div class=\"html_text_content html_text_content_shadow\" >";
			$html_contenido .= " <span class=\"css_span_dato\">$dato</span>";
			$html_contenido .= "</div>"; #end html_text_content			
			break;						
		
		case ($permissions>=2)	:

			#
			# Text area
			#
			$html_contenido .= "<textarea class=\"css_html_text \" ";
			$html_contenido .= "id=\"{$identificador_unico}\" ";
			$html_contenido .= "name=\"{$input_name}\" ";
			$html_contenido .= "data-tipo=\"{$tipo}\" ";
			$html_contenido .= "data-lang=\"{$lang}\" ";
			$html_contenido .= "data-section_tipo=\"{$section_tipo}\" ";
			$html_contenido .= "data-parent=\"{$parent}\" ";
			$html_contenido .= "title=\"$html_title\">";
			$html_contenido .= $dato;
			$html_contenido .= "</textarea>";

			# INIT : Init text editor 
			$html_contenido .= "<script>";
			$html_contenido .= "component_html_text.init({\"uid\":\"$identificador_unico\",\"modo\":\"$modo\",\"traducible\":\"$traducible\",\"propiedades_json\":$propiedades_json});";
			$html_contenido .= "</script>";
			

			if (SHOW_DEBUG) {
				#$html_contenido .= "<span class=\"debug_info\"> $identificador_unico</span>";			
				#$html_contenido .= " <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";
			}					
			break;							
	}	
	
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);

	
	# PRINT HTML
	print $html_label;
	print $html_contenido;

	
	
	print "</div>"; //wrap
?>