<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>D4 Actualización GDP</title>

<?php
# CSS
print css::build_tag(JQUERY_UI_URL_CSS);
print css::build_tag(DEDALO_LIB_BASE_URL .'/common/css/common.css');
print css::build_tag(DEDALO_LIB_BASE_URL .'/html_page/css/html_page.css');
print css::build_tag(DEDALO_LIB_BASE_URL .'/diffusion/diffusion_index_ts/css/diffusion_index_ts.css');
print css::build_tag(DEDALO_LIB_BASE_URL .'/component_tools/tool_av_versions/css/tool_av_versions.css');
print css::build_tag(DEDALO_LIB_BASE_URL .'/menu/css/menu.css');
print css::build_tag(DEDALO_LIB_BASE_URL .'/component_portal/css/component_portal.css');
print css::build_tag(DEDALO_LIB_BASE_URL .'/cargawstracasa/css/actualizargdp.css');
?>

<script type="text/javascript">
	var DEDALO_LIB_BASE_URL	= '<?php echo DEDALO_LIB_BASE_URL ?>' ;
	var page_globals = new Object();
		page_globals.dedalo_application_lang	= '<?php echo DEDALO_APPLICATION_LANG ?>' ;
		page_globals.dedalo_data_lang		= '<?php echo DEDALO_DATA_LANG ?>' ;
		page_globals.dedalo_data_nolan		= '<?php echo DEDALO_DATA_NOLAN ?>' ;
		page_globals.modo			= '<?php echo $modo ?>' ;
	
	DEBUG = <?php var_export(SHOW_DEBUG);?>;

	// VARS de mensajes de aviso multi-idioma
	var el_descriptor_tiene_hijos_title 			= '<?php echo msgJS($el_descriptor_tiene_hijos_title) ?>' ;
	var el_descriptor_tiene_indexaciones_title		= '<?php echo msgJS($el_descriptor_tiene_indexaciones_title) ?>' ;
	var seguro_que_quiere_borrar_este_termino_title	= '<?php echo msgJS($seguro_que_quiere_borrar_este_termino_title) ?>' ;
	var hijos_title									= '<?php echo msgJS($hijos_title) ?>' ;

	// Establecemos una cookie de modo para toda la página
	var modo 		= '<?php echo $modo ?>';
	var accion 		= '<?php echo $accion ?>';
	var ts_lang		= '<?php echo $ts_lang ?>';
	var type		= '<?php echo $type ?>';

	/*
	* VAR terminoIDresalte es un string viene del get  cuando se hace una búsqueda.
	* Se le pasa al loop "openTrackedDivs" para que pase en cada ciclo el listado de 
	* terminos a resaltar (tipo 525,632,874)
	*/
	var terminoIDresalte = '<?php echo $terminoIDlist ?>';	//alert(terminoIDresalte);
</script>

<?php
# JS
print js::build_tag(JQUERY_LIB_URL_JS);
print js::build_tag(JQUERY_UI_URL_JS);
print js::build_tag(DEDALO_LIB_BASE_URL . '/common/js/common.js');
print js::build_tag(DEDALO_LIB_BASE_URL . '/login/js/login.js');
print js::build_tag(DEDALO_LIB_BASE_URL .'/component_portal/js/component_portal.js');
print js::build_tag(DEDALO_LIB_BASE_URL .'/component_tools/tool_av_versions/js/tool_av_versions.js');
print js::build_tag(DEDALO_LIB_BASE_URL . '/common/js/cookies.js');
print js::build_tag(DEDALO_LIB_BASE_URL . '/common/js/labels.php');
#print js::build_tag(DEDALO_ROOT_WEB 	. '/lib/jquery/jquery.ajaxQueue.min.js');
print js::build_tag(DEDALO_ROOT_WEB 	. '/lib/jquery/AjaxQ-master/ajaxq.js');
#print js::build_tag(DEDALO_ROOT_WEB 	. '/inc/javascript.js');
print js::build_tag(DEDALO_LIB_BASE_URL . '/ts/js/ts_common.js');
print js::build_tag(DEDALO_LIB_BASE_URL . '/cargawstracasa/js/actualizargdp.js');
?>
</head>

<body onLoad="set_localStorage('tsopen','1',7);" onBeforeUnload="set_localStorage('tsopen','0',7);" onUnload="set_localStorage('tsopen','0',7);" >
<div id="actualizargdp_spinner" style="visibility:hidden" ><span>Sincronizando datos con WS Tracasa...</span></div>
<div id="wrapGeneral">
<table >  
  	
  <tr>
    <td>
    	<?php print $html_header ?>
    </td>
  </tr>

  <tr>
    <td align="center" valign="top" >
    <div id="actgdp_content">         
    
        <form id="form1" name="form1" method="post">            
            <span>La actualización GDP es necesaria para mantener actualizados los municipios y entidades singulares de Navarra. El proceso conecta con el servicio de Tracasa desde donde se obtiene la información.</span></br></br>
            <input type="submit" name="button" id="button" value=" Sincronizar Municipios y Entidades Singulares " class="SubmitButon">
            
        </form>
    
    </div><!-- /actgdp_content -->
    
    </td>
	</tr>    	
    
</table>
</div><!-- fin wrapGeneral -->

<?php include_once(DEDALO_ROOT .'/inc/operators_help.html');?>

</body>
</html>