<?php

	# VISUALIZADOR HTML	
	
	
	print "\n<!-- DIFFUSION_SECTION_STATS_GRAPHICS -->";
	print "\n<div class=\"css_wrap_diffusion_section_stats_graphics\" >";
	
		# Close button
		#echo "<div class=\"close_stats\" onclick=\"diffusion_section_stats.hide_stats_content(this)\"> ".label::get_label('cerrar')." </div>";
		echo "<div class=\"close_stats\" onclick=\"$('.css_button_stats:first').trigger('click');\"> ".label::get_label('cerrar')." </div>";
		
		# Stats container div
		echo "<div id=\"stats_container\" >";

			# Iterate all stats elements
			foreach ((array)$ar_js_obj as $key => $ar_value) {		
				# Current_stats_item div
				echo "<div class=\"current_stats_item\" id=\"current_stats_item_$key\">";

					#
					# SVG GRAPHIC BUILDED BY JS
					echo "<script>";
					echo "	diffusion_section_stats.build_charts(".json_handler::encode($ar_value).", '$key')";
					echo "</script>";

					
					#
					# INFO DROP DOWN
					echo "<div class=\"current_stats_item_info\">";
					
						#
						# TABLE INFO
						$column_title 	= $ar_value->title;
						echo "<table>";
						echo "<tr>";
							echo "<th>";
							echo "Total";
							echo "</th>";
							echo "<th>";
							echo "$column_title";
							echo "</th>";
						echo "</tr>";
						$current_values = isset($ar_value->data[0]) ? $ar_value->data[0]->values : array();
						foreach ((array)$current_values as $ckey => $cvalue) {
							echo "<tr>";
								echo "<td>";
								echo $cvalue->y;
								echo "</td>";
								echo "<td>";
								echo $cvalue->x;
								echo "</td>";
							echo "</tr>";
						}
						echo "</table>";

						if(SHOW_DEBUG) {
							#dump($ar_js_obj[$key], 'js_obj', array());
							echo "<pre>".print_r($ar_js_obj[$key],true)."</pre>";
							$current_component_tipo = $ar_js_obj[$key]->tipo;
							#dump($this->diffusion_map_object->$caller_section_tipo->$current_component_tipo->debug, 'debug', array());
							if (isset($this->diffusion_map_object->$caller_section_tipo->$current_component_tipo->debug)) {
							echo "<pre>".print_r($this->diffusion_map_object->$caller_section_tipo->$current_component_tipo->debug,true)."</pre>";
							}							
						}

					echo "</div>";#end current_stats_item_info


				echo "</div>";#end current_stats_item
			}#end foreach ((array)$ar_js_obj as $key => $value)

		echo "</div>";#end stats_container	

	
	
	print "\n</div><!-- /css_wrap_diffusion_section_stats_graphics -->\n"; //wrap

	
	
	


?>
