<?php

	# VISUALIZADOR HTML	
	
	
	print "\n<!-- DIFFUSION_SECTION_STATS_GRAPHICS -->";
	print "\n<div class=\"css_wrap_diffusion_section_stats_graphics\" >";
	
		$html_contenido = '';

		$html_contenido .= "<div class=\"close_stats\" onclick=\"diffusion_section_stats.hide_stats_content(this)\"> ".label::get_label('cerrar')." </div>";
		$html_contenido .= "<div id=\"stats_container\" > </div>";
		#$html_contenido = "<svg id=\"pie1\" class=\"mypiechart\"></svg>";
		


		# PRINT HTML
		print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_diffusion_section_stats_graphics -->\n"; //wrap

	/*
	# CSS
	print css::build_tag(DEDALO_ROOT_WEB 	.'/lib/nvd3/src/nv.d3.css');
	print css::build_tag(DEDALO_LIB_BASE_URL.'/diffusion/'.get_class($this).'/css/'.get_class($this).'.css');

	# JS
	print js::build_tag(DEDALO_ROOT_WEB . '/lib/nvd3/lib/d3.v3.js');
	print js::build_tag(DEDALO_ROOT_WEB . '/lib/nvd3/nv.d3.js');


	print js::build_tag(DEDALO_ROOT_WEB . '/lib/nvd3/src/models/pieChart.js');
	print js::build_tag(DEDALO_ROOT_WEB . '/lib/nvd3/src/models/discreteBarChart.js');
	print js::build_tag(DEDALO_ROOT_WEB . '/lib/nvd3/src/models/multiBarHorizontalChart.js');

	print js::build_tag(DEDALO_ROOT_WEB . '/lib/nvd3/src/utils.js');
	print js::build_tag(DEDALO_ROOT_WEB . '/lib/nvd3/src/tooltip.js');		
	print js::build_tag(DEDALO_ROOT_WEB . '/lib/nvd3/src/models/legend.js');
	print js::build_tag(DEDALO_ROOT_WEB . '/lib/nvd3/src/models/axis.js');	

	print js::build_tag(DEDALO_LIB_BASE_URL . '/diffusion/'.get_class($this).'/js/'.get_class($this).'.js');
	*/
?>

<script type="text/javascript">

	var matrix_stats_json = <?php echo $matrix_stats_json ?>;
		//console.log(matrix_stats_json)

	// Build charts
	diffusion_section_stats.build_charts(matrix_stats_json);	
	
</script>