<?php

	# VISUALIZADOR HTML	
		
	# BUTTON TOOL
	$html_tool    = "\n<!-- TOOL LANG [tipo:$tipo id_matrix:$id] -->";
	$html_tool   .= "<div class=\"tool_inspector_div\">";

	$btn_title	  = label::get_label('abrir').' '.label::get_label('herramienta');
	$html_tool   .= "\n<div class=\"icon_bs tool_lang_icon link\"
						data-tipo=\"{$tipo}\" data-id_matrix=\"{$id}\" data-parent=\"{$parent}\" data-lang=\"".DEDALO_DATA_LANG."\" data-tap_id=\"img_lang_{$tipo}_{$id}\" 
						title=\"$btn_title\"
						onclick=\"tool_common.open_tool_lang(this)\"
						></div>";


	$html_tool   .= label::get_label('tool_lang');	#" Lang";

	$html_tool   .= "</div>";#/tool_inspector_div
	
	# PRINT HTML
	print $html_tool;
	
?>