<?php
/*
	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 		$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_password'])) 		$ar_css['css_password']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 	$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))	$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_password']))	$ar_css['css_wrap_password']='';
	
	if(!isset ($html_tools))					$html_tools='';
	
	
	print "\n<!-- PASSWORD [tipo:$tipo id_matrix:$id] -->";
	print "\n<div class=\"css_wrap_password {$ar_css['css_wrap_password']}\" id=\"wrap_{$tipo}\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';					
	switch($permissions) {
			
		case 0	:	$html_contenido .= ''; 		
					break;
						
		case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\">Password field</span>";
					break;	
						
		case ($permissions>=2)	:
					
					$html_contenido .= "\n <input class=\"css_password {$ar_css['css_password']}\" type=\"password\" 
					id=\"{$id}\" name=\"{$tipo}_tm\" 
					data-tipo=\"{$tipo}\" 
					value=\"{$dato}\" 
					title=\"$html_title\" 
					disabled 
					/>";
										
			if($permissions==3)
		
					$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$debugger}</span>";	
							
	}
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div>\n\n"; //wrap
	*/
?>