<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 		$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_password'])) 		$ar_css['css_password']='';
	if(!isset ($ar_css['css_wrap_password']))	$ar_css['css_wrap_password']='';
	
	
	print "\n<!-- PASSWORD [$tipo][$id] -->";
	print "\n<div class=\"css_wrap_password {$ar_css['css_wrap_password']}\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	/*
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." (password)</span>";
					break;						
		
		case ($permissions>=1)	:
		
					$html_contenido .= "\n <input class=\"css_password {$ar_css['css_password']}\" type=\"password\" name=\"{$tipo}\" data-tipo=\"{$tipo}\" id=\"{$id}\" value=\"{$dato}\" title=\"$html_title\"  ";
					#$html_contenido .= "required pattern=\"(?=.*\d)(?=.*[a-z])(?=.*[A-Z])\w{6,}\" onchange=\"this.setCustomValidity(this.validity.patternMismatch ? 'Password must contain at least 6 characters, including UPPER/lowercase and numbers' : '');\" ";
					$html_contenido .= " />";											
	}
	*/
	$html_contenido .= "\n <input class=\"css_password {$ar_css['css_password']}\" type=\"password\" 
	id=\"{$id}\" name=\"{$tipo}\"
	data-tipo=\"{$tipo}\" data-modo=\"login\" data-parent=\"{$parent}\"
	value=\"\" 
	title=\"$html_title\" 
	";
	#$html_contenido .= "required pattern=\"(?=.*\d)(?=.*[a-z])(?=.*[A-Z])\w{6,}\" onchange=\"this.setCustomValidity(this.validity.patternMismatch ? 'Password must contain at least 6 characters, including UPPER/lowercase and numbers' : '');\" ";
	$html_contenido .= " />";
	
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div>\n\n"; //wrap
?>