<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 		$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_password'])) 		$ar_css['css_password']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 	$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))	$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_password']))	$ar_css['css_wrap_password']='';
	
	if(!isset ($html_tools))					$html_tools='';
	
	
	print "\n<!-- PASSWORD [tipo:$tipo section_id_matrix:$parent] -->";
	print "\n<div class=\"css_wrap_password wrap_component {$ar_css['css_wrap_password']}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-section_tipo=\"{$section_tipo}\" data-parent=\"{$parent}\" data-modo=\"{$modo}\" data-dato=\"••••••••••\" data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}' >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." (password)</span>";
					break;
						
		case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\">Password field</span>";
					break;	
						
		case ($permissions>=2)	:
		
					$html_contenido .= "\n <input class=\"css_password css_bg_password {$ar_css['css_password']}\" type=\"password\" 
					name=\"{$tipo}\"					
					value=\"{$dato_limited_leng}\" 
					data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-section_tipo=\"{$section_tipo}\" data-parent=\"{$parent}\"
					title=\"$html_title\" 
					";	
					#id=\"{$id}\"					
					#$html_contenido .= "required pattern=\"(?=.*\d)(?=.*[a-z])(?=.*[A-Z])\w{6,}\" onchange=\"this.setCustomValidity(this.validity.patternMismatch ? 'Password must contain at least 6 characters, including UPPER/lowercase and numbers' : '');\" ";
					$html_contenido .= " />";
					
			if($permissions==3)
				
					$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
					
											
	}
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);

	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	

	
	print "\n</div><!-- /css_wrap_password -->\n\n"; //wrap
?>