<?php

	# VISUALIZADOR HTML
		
	
	print "\n<!-- PASSWORD [tipo:$tipo section_id_matrix:$parent] -->";

	print "\n<div class=\"wrap_component css_wrap_password wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-modo=\"{$modo}\"
	data-dato=\"••••••••••\"
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "";
					break;
						
		case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato\">Password field</span>";
					break;	
						
		case ($permissions>=2) :

					# Avoid autocomplete input username in Users section
					$remove_autocomplete = null;
					if ($section_tipo==DEDALO_SECTION_USERS_TIPO) {
						$remove_autocomplete = "readonly onfocus=\"this.removeAttribute('readonly');component_common.select_wrap(null,'$id_wrapper');\"";
					}else{
						$remove_autocomplete = '';//"onfocus=\"component_common.select_wrap(null,'$id_wrapper')\";\"";
						$remove_autocomplete = "onfocus=\"component_common.select_wrap_on_tab_focus(this,'$id_wrapper')\";\"";
					}
		
					$html_contenido .= "\n <input class=\"css_password css_bg_password\" type=\"password\"
					onchange=\"component_password.Save(this)\"
					name=\"{$tipo}\"
					value=\"{$dato_limited_leng}\" 
					data-tipo=\"{$tipo}\"
					data-lang=\"{$lang}\"
					data-section_tipo=\"{$section_tipo}\"
					data-parent=\"{$parent}\"
					title=\"$html_title\"
					$remove_autocomplete
					/>";

					
					if(SHOW_DEBUG) {
						#$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";
					}		
					break;											
	}

	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);

	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	

	
	print "\n</div><!-- /css_wrap_password -->\n\n"; //wrap
?>