<?php
/*
	# VISUALIZADOR HTML		
	
	print "\n<!-- PASSWORD [tipo:$tipo id_matrix:$id] -->";
	print "\n<div class=\"css_wrap_password\" id=\"wrap_{$tipo}\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';					
	switch($permissions) {
			
		case 0	:	$html_contenido .= ''; 		
					break;
						
		case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato\">Password field</span>";
					break;	
						
		case ($permissions>=2)	:
					
					$html_contenido .= "\n <input class=\"css_password\" type=\"password\" 
					id=\"{$id}\" name=\"{$tipo}_tm\" 
					data-tipo=\"{$tipo}\" 
					value=\"{$dato}\" 
					title=\"$html_title\" 
					disabled 
					/>";
										
			
			break;
		
					
							
	}
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div>\n\n"; //wrap
	*/
?>