<?php

	# VISUALIZADOR HTML	
	
	
	#print "\n<!-- PASSWORD [$tipo][$parent] -->";
	print "\n<div class=\"css_wrap_password\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido  = '';	
	$html_contenido .= "\n <input class=\"css_password\" type=\"password\"
	name=\"{$tipo}\"
	data-tipo=\"{$tipo}\" data-modo=\"login\" data-section_tipo=\"{$section_tipo}\" data-parent=\"{$parent}\"
	value=\"\"
	title=\"$html_title\"
	placeholder=\"$label\"
	";
	$html_contenido .= " />";
	
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div>\n\n"; //wrap
?>