<?php

	# VISUALIZADOR HTML	

	print "<!-- ".__CLASS__." [tipo:$tipo] -->";
	
	print "<div class=\"wrap_component css_wrap_autocomplete_hi wrap_portal_list\" id=\"{$id_wrapper}\"
				data-tipo=\"{$tipo}\"
				data-lang=\"{$lang}\"
				data-section_tipo=\"{$section_tipo}\"
				data-parent=\"{$parent}\"
				data-modo=\"{$modo}\"
				data-from_modo=\"{$from_modo}\"
				data-dato='{$dato_json}'
				data-component_name=\"{$component_name}\"
				data-component_info='{$component_info}'
				>";
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0:	
				$html_contenido .= "";
				break;
											
		case 1:
				
				$html_contenido .= $valor ;
				break;

		case ($permissions>=2)	:
				# VALOR . STRING RESOLVED TO SHOW

				#$html_contenido .= $valor ;
				#break;

					if($modo =='portal_list'){
						if(empty($ar_valor)){
							$edit_class = 'css_autocomplete_ul_edit_in_portal';
						}else{
							$edit_class = 'css_autocomplete_ul';
						}
						$html_contenido .= " <ul class=$edit_class onclick=\"component_common.change_mode_component(this, '$modo','edit')\">";
					}else{
						$html_contenido .= " <ul>";
					}
					
					foreach ($ar_valor as $current_value => $value) {
						$html_contenido .= "<li>";
							$html_contenido .= $value;
						$html_contenido .= "</li>";
					}
					$html_contenido .= "</ul>";

				break;
					
	}
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);
	
	# PRINT HTML
	print $html_contenido;	
	
	
?>