<?php

	# VISUALIZADOR HTML	
	
		
	
	print "<!-- ".__CLASS__." $label -->";

	print "<div class=\"wrap_component css_wrap_autocomplete_hi\" id=\"{$id_wrapper}\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch($permissions) {
			
		case 0	:
				$html_content .= "";
				break;
						
		case 1	:
		case 2	:
		case 3	:
				# COMPARISON OPERATORS
				$html_content .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);
				
				
				#
				# ROW
				$html_content .= "\n <ul class=\"css_autocomplete_hi_valor in_search_mode\">";
				foreach ($ar_valor as $current_value => $value) {

					$html_content .= "<li>";

					# BTN DELETE
					$html_content .= "\n <div class=\"icon_bs link css_autocomplete_hi_button_delete\"
					data-tipo=\"{$tipo}\"
					data-current_value='$current_value'
					data-role=\"autocomplete_hi_button_delete\"
					title=\"$label $parent\"
					onclick=\"component_autocomplete_hi.delete(this)\"></div>";

					# VALUE . STRING RESOLVED TO SHOW
					$html_content .= $value;
					if(SHOW_DEBUG===true) {
						#$html_content .= " <span class=\"notes\">$current_value</span>";
					}

					$html_content .= "</li>";
				}
				$html_content .= "</ul>";

				$hierarchy_types_json 	 = json_encode($hierarchy_types);
				$hierarchy_sections_json = json_encode($hierarchy_sections);

				# SOURCE_MODE SWITCH
				switch ($source_mode) {
					case 'tree':

						# BTN NEW ELEMENT
						$html_content .= "<div class=\"icon_bs link new_autocomplete_hi in_search_mode\"
						data-id_wrapper=\"$id_wrapper\"
						data-hierarchy_types='{$hierarchy_types_json}'
						data-hierarchy_sections='{$hierarchy_sections_json}'
						data-component_name=\"{$component_name}\"
						onclick=\"component_common.open_ts_window(this)\"></div>";
						break;
					
					case 'autocomplete':
					default:
				
						#
						# INPUT SEARCH FIELD
						$html_content .= "\n <input class=\"css_autocomplete_hi_search_field in_search_mode\" type=\"text\" placeholder=\"".label::get_label('buscar')."...\"
						data-id_wrapper=\"$id_wrapper\"
						data-tipo=\"$tipo\"
						data-hierarchy_types='{$hierarchy_types_json}'
						data-hierarchy_sections='{$hierarchy_sections_json}'
						onfocus=\"component_autocomplete_hi.activate(this)\"
						tabindex=\"1\"
						autocomplete=\"off\"
						autocorrect=\"off\"
						/>";

						if(SHOW_DEBUG===true) {
							#$html_content .= "<div class=\"debug_info notes\">ar_referenced_tipo: ".implode(', ', $ar_referenced_tipo)."</div>";
							$html_content .= "<div class=\"debug_info notes\">".str_replace('},', '},<br>', $dato_json) ."</div>";
						}


						# Reset var 'activated' on load
						$html_content .= "<script>component_autocomplete_hi.activated={}</script>";
						break;
				}//end switch ($source_mode)


				#
				# TREE RESOLUTION STATS
				#$html_content .= "\n <div id=\"autocomplete_hi_tree_stats_{$tipo}\" class=\"css_autocomplete_hi_tree_stats\"> Calculating.. </div>";

				# INPUT DATA HIDDEN
				$html_content .= "\n<input type=\"text\" name=\"{$input_name}\" class=\"css_autocomplete_hi_dato_hidden\" style=\"width:300px\"
				data-tipo=\"{$tipo}\"
				data-section_tipo=\"{$section_tipo}\"
				data-parent=\"{$parent}\"
				data-lang=\"{$lang}\"
				data-link_fields='{$ar_link_fields}'
				data-role=\"autocomplete_hi_dato_hidden\"
				value='{$dato_json}'
				/>";

				if(SHOW_DEBUG===true) {
					#$html_content .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$parent}\" >{$debugger}</span>";
					#$html_content .= "<div class=\"debug_info notes\">". json_encode($propiedades) ."</div>";
				}
				

				# LOGICAL OPERATORS
				$html_content .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);


				if(SHOW_DEBUG===true) {
					$html_content .= "<span class=\"debug_info\">$search_input_name</span>";
				}

				break;											
	}

	# Prepare content to show in page
	tools::prepare_content($html_content);
	
	
	# PRINT HTML
	print $html_label;
	print $html_content;	
	
	
	print "</div><!-- /css_wrap_autocomplete_hi COMPONENT_AUTOCOMPLETE_hi [tipo:$tipo id_matrix:$parent] $label -->"; //wrap
?>