<?php

	# VISUALIZADOR HTML	
	
	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in');

	print "\n<div class=\"wrap_component css_wrap_component_project_langs wrap_component_project_langs_{$this->modo} wrap_component_{$tipo}\" 
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-parent=\"{$parent}\"
	data-section_tipo=\"{$section_tipo}\"
	data-modo=\"{$modo}\"
	data-dato=\"{$valor}\"
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:
				$html_contenido .= "";
				break;
						
		case 1	: 
				$html_contenido .= "\n <span class=\"css_span_dato\">$dato</span>";
				break;	
						
		case 2	:
		case 3	:
				$html_contenido .= "
				<ul id=\"sortable_project_langs\" class=\"css_component_project_langs\"
				name=\"{$tipo}_{$parent}\"
				data-tipo=\"{$tipo}\"
				data-lang=\"{$lang}\"
				data-section_tipo=\"{$section_tipo}\"
				data-parent=\"{$parent}\"
				title=\"$html_title Drag to reorder\"
				>";
				
					foreach( (array)$ar_langs as $current_locator_json => $lang_name ) {
						
						$current_locator 			  = json_decode($current_locator_json);
						$current_locator_section_tipo = $current_locator->section_tipo;

						if(in_array($current_locator->section_tipo, $dedalo_projects_default_langs)) {

							# Default langs non editable
							$html_contenido .= "\n 
							<li class=\"ui-state-default\" data-value='{$current_locator_json}'>
								<div class=\"ui-icon ui-icon-arrowthick-2-n-s\"></div>
								<div class=\"css_component_project_langs_lang_name\" id=\"li_div_{$current_locator_section_tipo}\">$lang_name</div>					
							</li>";

						}else{

							$html_contenido .= "\n 
							<li class=\"ui-state-default\" data-value='{$current_locator_json}'>
								<div class=\"ui-icon ui-icon-arrowthick-2-n-s\"></div>
								<div class=\"css_component_project_langs_lang_name\" id=\"li_div_{$current_locator_section_tipo}\">$lang_name</div>
								<div class=\"css_component_project_langs_lang_delete\">Delete</div>							
							</li>";
						}						
						
					}					
					if(empty($ar_langs)) $html_contenido .= " <li class=\"drag_disabled\"> No language selected </li> ";				
				
				$html_contenido .= "</ul>";

				#
				# ADD LANG BUTTON
				$html_contenido .= "<div class=\"css_btn_add_lang css_button_generic drag_disabled\"> Add lang </div>";				
				
				break;				
											
	}

	# Prepare content to show in page
	tools::prepare_content($html_contenido);
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;


	#
	# DEDALO_PROJECTS_DEFAULT_LANGS
	# Used to rebuild 
	print "<script>var dedalo_projects_default_langs=". json_encode($dedalo_projects_default_langs)."</script>";
	
	
	print "</div>"; //wrap

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out');
?>