<?php

	# VISUALIZADOR HTML	
		
	
	#print "\n<!-- COMPONENT_PROJECT_LANGS [tipo:$tipo] -->";
	print "\n<div class=\"css_wrap_component_project_langs wrap_component_project_langs_{$this->modo}\" >";
	
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." (component_project_langs)</span>";
					break;
						
		case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato\">$dato</span>";
					break;	
						
		case ($permissions>=2)	:					
					
					$html_langs	= '';
					if(is_array($ar_langs)) {

						foreach($ar_langs as $locator_json => $lang_name) {						
							$html_langs .= $lang_name;	
							if(end($ar_langs)!=$lang_name) $html_langs .= ', ';	
						}
					}
					$html_contenido .= $html_langs;	
					break;
						
					
											
	}
	
	
	# PRINT HTML
	print $html_contenido;
	
	
	print "\n</div>\n\n"; //wrap
?>