<?php

	# VISUALIZADOR HTML	
	
	
	print "\n<!-- COMPONENT_PROJECT_LANGS TM [tipo:$tipo section_id_matrix:$parent] -->";
	print "\n<div class=\"css_wrap_component_project_langs_tm text_unselectable\" id=\"wrap_{$identificador_unico}\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." (component_project_langs)</span>";
					break;
						
		case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato\">$dato</span>";
					break;	
						
		case ($permissions>=2)	:
					
					/*
					$html_contenido .= "\n <input class=\"css_component_project_langs\" type=\"text\" 
					id=\"{$identificador_unico}\" name=\"{$tipo}_{$id}\" 
					data-tipo=\"{$tipo}\" data-id_matrix=\"{$id}\" data-lang=\"{$lang}\" 
					value=\"{$dato}\" title=\"$html_title\" />";
					*/
					
					$html_contenido .= "\n
					<ul id=\"sortable_project_langs_tm\" class=\"css_component_project_langs\"  
					name=\"{$tipo}_{$parent}_tm\" data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-section_tipo=\"{$section_tipo}\" data-parent=\"{$parent}\" 
					style=\"opacity:0.7;padding-bottom:10px;\">";
					
						if( is_array($ar_langs)) foreach($ar_langs as $terminoID => $lang_name ) {
						
							$html_contenido .= "\n 
							<li class=\"ui-state-default\" data-value=\"{$terminoID}\" style=\"cursor:default\">
								<div class=\"ui-icon ui-icon-arrowthick-2-n-s\"></div>
								<div class=\"css_component_project_langs_lang_name\" id=\"li_div_tm_{$terminoID}\">$lang_name</div>					
							</li>";
							
							$html_contenido .= "";
						}
					
					$html_contenido .= "\n </ul>";
					
					
					break;
					
					
											
	}
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div>\n\n"; //wrap
?>