<?php

	# VISUALIZADOR HTML	
	
	
	print "\n<!-- COMPONENT_PROJECT_LANGS [tipo:$tipo section_id_matrix:$parent] -->";

	print "\n<div class=\"wrap_component css_wrap_component_project_langs wrap_component_{$tipo}\" 
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-parent=\"{$parent}\"
	data-section_tipo=\"{$section_tipo}\"
	data-modo=\"{$modo}\"
	data-dato=\"{$valor}\"
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "";
					break;
						
		case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato\">$dato</span>";
					break;	
						
		case ($permissions>=2)	:
										
					$html_contenido .= "
					<ul id=\"sortable_project_langs\" class=\"css_component_project_langs\" 
					name=\"{$tipo}_{$parent}\" data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-section_tipo=\"{$section_tipo}\" data-parent=\"{$parent}\"
					title=\"$html_title Drag to reorder\" >";
					
						if( is_array($ar_langs)) foreach($ar_langs as $terminoID => $lang_name ) {
							
							if(in_array($terminoID, $dedalo_projects_default_langs)) {

								# Default langs non editable
								$html_contenido .= "\n 
								<li class=\"ui-state-default\" data-value=\"{$terminoID}\">
									<div class=\"ui-icon ui-icon-arrowthick-2-n-s\"></div>
									<div class=\"css_component_project_langs_lang_name\" id=\"li_div_{$terminoID}\">$lang_name</div>					
								</li>";

							}else{

								$html_contenido .= "\n 
								<li class=\"ui-state-default\" data-value=\"{$terminoID}\">
									<div class=\"ui-icon ui-icon-arrowthick-2-n-s\"></div>
									<div class=\"css_component_project_langs_lang_name\" id=\"li_div_{$terminoID}\">$lang_name</div>
									<div class=\"css_component_project_langs_lang_delete\">Delete</div>							
								</li>";
							}
							
							
							$html_contenido .= "";
						}
						
					if(empty($ar_langs)) $html_contenido .= " <li class=\"drag_disabled\"> No language selected </li> ";
					
					
					$html_contenido .= "\n </ul>";

					$html_contenido .= "\n <div class=\"css_btn_add_lang css_button_generic drag_disabled\"> Add lang </div>";
					
					
					#$html_contenido .= "\n <span  class=\"css_span_log\"></span>";						
					#$html_contenido .= $html_tools;
					
					if($permissions==3)	{
						$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";
					}
					break;				
											
	}


	# Prepare content to show in page
	tools::prepare_content($html_contenido);
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_component_project_langs -->\n\n"; //wrap
?>