<?php

	# VISUALIZADOR HTML


	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in');

	print "<div class=\"wrap_component css_wrap_email wrap_component_{$tipo}\" id=\"{$id_wrapper}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato=\"{$dato_json}\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-component_info='{$component_info}' ";
	print ">";

	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	# CONTENIDO (INPUT)
	$html_content = '';
	switch(true) {

		case $permissions===0 :
				$html_content .= "";
				break;

		case $permissions===1 :
				$html_content .= "<span class=\"css_span_dato\">$dato</span>";
				break;

		case $permissions>=2 :

				# Button add
				$html_content .= "<div class=\"css_button_generic btn_add_input_text\" onclick=\"component_email.add_input(this)\">";
				$html_content .= "<div class=\"link css_email_add\"></div>";
				$html_content .= "</div>";


				# dato_view
				$dato_view = empty($dato) ? array("") : $dato;
				$html_content .= '<ul>';
				foreach ($dato_view as $key => $value) {
					# Fix issues with quotes
					$value = htmlentities($value);

					$html_content .= '<li>';

					// input email
					$html_content .= "<input class=\"css_email\" type=\"text\" ";
					$html_content .= "onfocus=\"component_common.select_wrap(null,'$id_wrapper');\" ";
					$html_content .= "onchange=\"component_email.Save(this)\" ";
					$html_content .= "name=\"{$input_name}\" ";
					$html_content .= "data-tipo=\"{$tipo}\" ";
					$html_content .= "data-section_tipo=\"{$section_tipo}\" ";
					$html_content .= "data-parent=\"{$parent}\" ";
					$html_content .= "data-lang=\"{$lang}\" ";
					$html_content .= "value=\"{$value}\" ";
					$html_content .= "title=\"$html_title\" ";
					$html_content .= "tabindex=\"1\" ";
					$html_content .= "/>";

					// button send to current emails
					$html_content .= "<div class=\"css_button_generic btn_create_email_list current\" onclick=\"component_email.send_email(this, 'current')\">";
					$html_content .= "<div class=\"css_email_send\"></div>";
					$html_content .= "</div>";

					$html_content .= '</li>';

				}//end foreach
				$html_content .= '</ul>';

				//# INPUT EMAIL
				//$html_content .= "<input class=\"css_email\" type=\"text\" ";
				//$html_content .= "onfocus=\"component_common.select_wrap(null,'$id_wrapper');\" ";
				//$html_content .= "onchange=\"component_email.Save(this)\" ";
				//$html_content .= "name=\"{$input_name}\" ";
				//$html_content .= "data-tipo=\"{$tipo}\" ";
				//$html_content .= "data-section_tipo=\"{$section_tipo}\" ";
				//$html_content .= "data-parent=\"{$parent}\" ";
				//$html_content .= "data-lang=\"{$lang}\" ";
				//$html_content .= "value=\"{$dato}\" ";
				//$html_content .= "title=\"$html_title\" ";
				//$html_content .= "tabindex=\"1\" ";
				//$html_content .= "/>";

				// button send to all emails
				$html_content .= "<div class=\"css_button_generic btn_create_email_list\" onclick=\"component_email.send_email(this, 'all')\">";
				$html_content .= "<div class=\"css_email_send\"></div>";
				$html_content .= "</div>";

				# MULTIPLE_DATA SEND BUTTON
				if(isset($propiedades->multiple_data)){
					$html_content .= "<div class=\"css_button_generic btn_create_email_list\" ";
					$html_content .= "data-multiple_data_tipo= '$propiedades->multiple_data_tipo' ";
					$html_content .= "onclick=\"component_email.send_multiple_email_calculation(this)\" ";
					$html_content .= ">";
					$html_content .= "<div class=\"css_email_multiple_send\"></div>";
					$html_content .= "</div>";

					if(SHOW_DEBUG===true) {
						#if ($tipo==='mupreva242') {
							#unset($propiedades->css);
							#dump($propiedades, '$propiedades->multiple_data_tipo ++ '.to_string());
						#}
					}
				}

				#
				# JS Init component
				$html_content .= '<script>';
				# Init component
				$init_options = new stdClass();
					$init_options->component_name 	= $component_name;
					$init_options->wrapper_id 		= $id_wrapper;
				$html_content .= 'component_common.init('.json_encode($init_options).');';
				$html_content .= '</script>';
				break;
	}

	# Prepare content to show in page
	tools::prepare_content($html_content);


	# PRINT HTML
	print $html_label;
	print $html_content;

	print "</div>"; //wrap


	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out');


?>
