<?php

	# VISUALIZADOR HTML	
	
	
	if(isset($_REQUEST[$tipo]))					$dato = $_REQUEST[$tipo];		#var_dump($_REQUEST[$tipo]);
	
	
	print "\n<!-- EMAIL -->";

	print "\n<div class=\"wrap_component css_wrap_email\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch($permissions) {
			
		case 0	:	$html_content .= "";
					break;
						
		case 1	: 	$html_content .= "\n <span class=\"css_span_dato\">$dato</span>";
					break;	
						
		case ($permissions>=2)	:
					# COMPARISON OPERATORS
					$html_content .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);
		
					$html_content .= "\n <input class=\"css_email\" type=\"text\" name=\"{$search_input_name}\"
					id=\"{$identificador_unico}\"
					data-tipo=\"{$tipo}\"
					data-section_tipo=\"{$section_tipo}\"
					data-parent=\"{$parent}\"
					data-lang=\"{$lang}\"
					value=\"{$dato}\"
					title=\"$html_title\" />";

					# LOGICAL OPERATORS
					$html_content .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);

					if(SHOW_DEBUG===true) {
						$html_content .= "<span class=\"debug_info\">$search_input_name</span>";
					}
					break;					
	}
	
	
	# PRINT HTML
	print $html_label;
	print $html_content;
	
	
	print "\n</div>\n\n"; //wrap
?>