<?php

	# VISUALIZADOR HTML	
	
	
	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in');

	print "<div class=\"wrap_component css_wrap_email wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-modo=\"{$modo}\"
	data-dato=\"{$dato}\"
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch($permissions) {
			
		case 0	:
				$html_content .= "";
				break;
						
		case 1	: 	
				$html_content .= " <span class=\"css_span_dato\">$dato</span>";
				break;	
		
		case 2	:
		case 3	:		
				$html_content .= " <input class=\"css_email bg_email\" type=\"text\"
				onfocus=\"component_common.select_wrap(null,'$id_wrapper');\"
				onchange=\"component_email.Save(this)\"
				name=\"{$input_name}\"
				data-tipo=\"{$tipo}\"
				data-section_tipo=\"{$section_tipo}\"
				data-parent=\"{$parent}\"
				data-lang=\"{$lang}\"
				value=\"{$dato}\"
				title=\"$html_title\"
				tabindex=\"1\"
				/>";				
				break;
	}

	# Prepare content to show in page
	tools::prepare_content($html_content);
	
	
	# PRINT HTML
	print $html_label;
	print $html_content;
	
	print "</div>"; //wrap


	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out');


?>