<?php
	$html = '';

	if($file_exists) {
		
		#$html .= "<iframe src=\"$pdf_url\" class=\"pdf_object_thumb\" >[Your browser does not support iframe</iframe>";		
		#width=\"$media_width\" height=\"$media_height\"

		
		# ICON
		if(SHOW_DEBUG) {
			$html .= "<div class=\"pdf_thumb_icon\" onclick=\"component_pdf.open_pdf(this)\" data-pdf_url=\"$pdf_url\"></div>";
		}		
		
	}else{
		#$html .= "<div class=\"pdf_thumb_icon_default\"></div>";
		$html .= "<div class=\"pdf_text_no_file\">";
		$html .= label::get_label('sin_fichero');
		if(SHOW_DEBUG) {
			$html .= " <br><mark>$pdf_url</mark>";
		}
		$html .= "</div>";
	}

	print $html;
?>

