<?php

	# VIEW HTML

	print "<div class=\"wrap_component css_wrap_input_text tooltip_active\" id=\"wrap_{$tipo}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato='".json_encode($value)."' ";
	print 'title="'.search_development2::search_options_title( $this->search_operators_info() ).'" ';
	print ">";

	# LABEL
	$html_label = component_common_draw::draw_label($this);

	# CONTENT
	$html_content = '';
	switch(true) {

		case ($permissions>=1) :

			$html_content .= '<input class="css_json_search" type="text" ';
			$html_content .= "name=\"{$search_input_name}\" ";
			$html_content .= "data-tipo=\"{$tipo}\" ";
			$html_content .= "data-dato=\"$value\" ";
			$html_content .= "value=\"$value\" ";
			$html_content .= "onchange=\"component_common.fix_dato(this,'{$component_name}')\" ";
			$html_content .= '/>';

			if(SHOW_DEBUG===true) {
				$html_content .= "<span class=\"debug_info\">$search_input_name</span>";
			}
			break;
		default:
			$html_content .= label::get_label("sin_acceso");
			break;
	}//end switch($permissions)


	# Prepare content to show in page
	tools::prepare_content($html_content);


	# PRINT HTML
	print $html_label;
	print $html_content;


	print "</div>"; //wrap