<?php
	
	# VISUALIZADOR HTML	

	# ELEMENTOS	
	if(!isset ($ar_css['css_span_dato'])) 				$ar_css['css_span_dato']='';
	
	
	print "\n\n<!-- ROWS_HEADER [$tipo] ---------------------------------------------------------------------------------------------- -->";
		
	# CONTENIDO (INPUT)
	$html_contenido  = "";	
	$html_contenido .= "\n<tr>";
	
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." </span>";
					break;
						
		case ($permissions>=1)	:

					
					# TD ID
					$html_contenido .= "\n <th class=\"row_id\">";					
					$html_contenido .= "\n ID ";
					#$html_contenido .= rows_header::flechasOrden('id','id');
					$html_contenido .="<div class=\"flecha_orden_ascendent div_image_link\" onclick=\"$(this).toggleClass('flecha_orden_descendent');\"></div>";	
					$html_contenido .= "\n </th>";
					
					
					# TD INFO
					$html_contenido .= "\n <th class=\"\">";
					$html_contenido .= "\n Info";	
					$html_contenido .= "\n </th>";
													
	}
	$html_contenido .= "\n</tr>";
	
	# PRINT HTML
	print $html_contenido;
	

?>