<?php

	#
	# SEARCH_DATA_RECORDS
	# Records iteration generate 'rows' as objects 
	if(is_array($search_data_records->result)) foreach ($search_data_records->result as $row) {

		$row = (object)$row; # Convert to object for easy access
			#dump($row, ' row ++ '.to_string());

		# TITLE String
		$title = 'No title';
		if(isset($row->title)) {
			$title = $row->title;
		}
		echo "<h2>$title</h2>";


		# DATE of interview
		if (isset($row->date)) {
			$date = DateTime::createFromFormat('Y-m-d', $row->date);
			echo " <h4>".$date->format('d-m-Y')."</h4>";
		}
		

		# ABSTRACT String
		if(isset($row->abstract)) {
			$abstract = $row->abstract;
			echo "<div>$abstract</div>";
		}
		

		# MEDIA Array of records by id, like 365,368,785
		if(isset($row->image)) {
			echo "<div class=\"media images\">";
			echo "<h2>Images</h2>";
			# IMAGES . Iterate images
			foreach ((array)$row->image as $current_image_row) {
				$current_image_row = (object)$current_image_row; # Convert to object for easy access

				if(isset($current_image_row->image)) {
					# Extraemos el path de la imagen y lo sumamos al path general definido en config
					$image_url = __CONTENT_BASE_URL__ . $current_image_row->image;
					echo "<img src=\"$image_url\" />";
				}
			}
			echo "</div>";//end media div
		}


		# VIDEO
		if(isset($row->audiovisual)) {
			echo "<div class=\"media videos\">";
			echo "<h2>Videos</h2>";	
			foreach ((array)$row->audiovisual as $current_audiovisual_row) {
				$video_url 	  = __CONTENT_BASE_URL__ . $current_audiovisual_row->video;
				$poster_frame = '';;
				echo "<video class=\"video\" src=\"$video_url\" poster=\"$poster_frame\" onclick=\"this.play()\" controls>
						Sorry, your browser doesn't support embedded videos
					  </video>";
			}
			echo "</div>";//end media div
		}


		# INFORMANT
		if(isset($row->informant)) {
			echo "<div class=\"media informants\">";
			echo "<h2>Informant</h2>";
			echo "<ul>";
			foreach ((array)$row->informant as $current_informant_row) {

				echo "<li>";
				echo "<span>";
				echo "$current_informant_row->name $current_informant_row->surname";
				if (isset($current_informant_row->birthdate)) {
					$date = DateTime::createFromFormat('Y-m-d', $current_informant_row->birthdate);
					echo " (".$date->format('d-m-Y').")";
				}
				echo "</span>";
				echo "</li>";
			}
			echo "</ul>";
			echo "</div>";//end media div
		}
		

		# LINK Link to section X
		$link_url = '../sample2/?id='.$row->section_id.'&t='.$row->table;
		echo "<a href=\"$link_url\"> Link to $title </a>";
		
		
		echo "<hr>";

	}//end foreach ($search_data_records->result as $row)


	# Time info
	if(SHOW_DEBUG===true && isset($search_data_records->debug->total_time)) {
		echo "<div>Dedalo public API request total time: ".$search_data_records->debug->total_time." secs from ".JSON_TRIGGER_URL."</div>";
	}

?>
