<?php

	# VISUALIZADOR HTML	

	// print '<div class="wrap_component css_wrap_'.$component_name.' wrap_component_'.$modo.' wrap_component_'.$tipo. ' tooltip_active" ';


	// print "id=\"wrap_{$tipo}\" ";
	// print "data-tipo=\"{$tipo}\" ";
	// print "data-component_name=\"{$component_name}\" ";
	// print "data-modo=\"{$modo}\" ";
	// print "data-dato='".json_encode($dato)."' ";
	// // print 'title="'.search_development2::search_options_title( $this->search_operators_info() ).'" ';
	// print ">";

	// q operator
		// if ($modo==='search') {
		// 	$html_content .= '<input class="q_operator" type="text" value="'.$q_operator.'" ';
		// 	$html_content .= "onchange=\"component_common.fix_dato(this,'{$component_name}')\" ";
		// 	$html_content .=' />';
		// }

	$html  = '';

	// wrapper in
		$html .= '<div id="'.$component_wrapper_id.'" class="wrap_component css_wrap_'.$component_name.' wrap_component_'.$modo.' wrap_component_'.$tipo. ' tooltip_active\" ';
		$html .= "data-tipo=\"{$tipo}\" ";
		$html .= "data-section_tipo=\"{$section_tipo}\" ";
		$html .= "data-parent=\"{$section_id}\" ";
		$html .= "data-component_name=\"{$component_name}\" ";
		$html .= "data-modo=\"{$modo}\" ";
		$html .= "data-dato='".json_encode($dato_search)."' ";
		// $html .= 'title="'.search_development2::search_options_title( $this->search_operators_info() ).'" ';
		$html .= '>';

	// label
		$html .= "<span class=\"label\">$label</span>";


	// button tree selector
		$html .= "<div class=\"icon_bs link new_component_semantic_node_search\" ";
		$html .= "onclick=\"component_semantic_node.open_ts_window(this)\" ";
		$html .= "data-component_name=\"component_semantic_node\" ";
		$html .= "data-hierarchy_types='{$hierarchy_types_string}' ";
		// $html .= "data-hierarchy_sections=\"\" ";
		$html .= "></div>";


	// data list
		if (!empty($dato)) {

			$html .= '<ul class="ul_component_semantic_node">';
			foreach ((array)$dato as $locator_ds) {

				$current_term = ts_object::get_term_by_locator($locator_ds, DEDALO_DATA_LANG, true);

				$rel_locator	= new stdClass();
					$rel_locator->ds = [$locator_ds];
				$rel_locator_json = json_encode($rel_locator);

				$html .= '<li>';

				// button delete
					$html .= "<div class=\"icon_bs link delete_component_semantic_node\" ";
					$html .= "onclick=\"component_semantic_node.remove_search_index(this,event)\" ";
					$html .= "data-locator_ds='{$rel_locator_json}' ";
					$html .= "data-component_wrapper_id=\"{$component_wrapper_id}\" ";
					$html .= '></div> ';

				// label
					$html .= '<span>';
					$html .= $current_term;
					if(SHOW_DEBUG) {
						$html .= ' [' . $locator_ds->section_tipo.'_'.$locator_ds->section_id . ']';
					}
					$html .= '</span>';

				// input hidden
					$html .= '<input type="text" value=\''.json_encode($dato_search) .'\' data-role="dato_hidden" class="hide" style="width:100%">';

				$html .= '</li>';
			}
			$html .= '</ul>';
		}//end if (!empty($dato))


	// end wrapper
		$html .= '</div>';//end semantic_wrapper


	echo $html;



