<?php

	# VISUALIZADOR HTML	

	$html  = '';

	// wrapper in
		$html .= '<div id="'.$component_wrapper_id.'" class="wrap_component semantic_wrapper" ';
		$html .= "data-tipo=\"{$tipo}\" ";
		$html .= "data-section_tipo=\"{$section_tipo}\" ";
		$html .= "data-parent=\"{$section_id}\" ";
		$html .= "data-component_name=\"{$component_name}\" ";
		$html .= "data-component_info=\"{$component_info}\" ";
		$html .= "data-modo=\"{$modo}\" ";
		$html .= 'data-dato=\''.json_encode($dato).'\' ';
		// $html .= "data-portal_locator_section_tipo=\"{$row_locator->section_tipo}\" ";
		// $html .= "data-portal_locator_section_id=\"{$row_locator->section_id}\" ";
		$html .= 'data-row_locator=\''.json_encode($row_locator).'\' ';
		$html .= '>';

	// button tree selector
		$html .= "<div class=\"icon_bs link new_component_semantic_node\" ";
		$html .= "onclick=\"component_semantic_node.open_ts_window(this)\" ";
		$html .= "data-component_name=\"{$component_name}\" "; // manadatory (!)
		$html .= "data-hierarchy_types='{$hierarchy_types_string}' ";
		// $html .= "data-hierarchy_sections=\"\" ";
		$html .= "></div>";

	// data list
		if (!empty($dato)) {

			$html .= '<ul class="ul_component_semantic_node">';
			foreach ((array)$dato as $current_locator_ds) {

				$current_term				= ts_object::get_term_by_locator($current_locator_ds, DEDALO_DATA_LANG, true);
				$current_locator_ds_json	= json_encode($current_locator_ds);

				$html .= '<li>';

				// button delete
					$html .= "<div class=\"icon_bs link delete_component_semantic_node\" ";
					$html .= "onclick=\"component_semantic_node.remove_index(this,event)\" ";
					$html .= "data-locator_ds='{$current_locator_ds_json}' ";
					$html .= "data-component_wrapper_id=\"{$component_wrapper_id}\" ";
					$html .= "></div>";

				// term
					$html .= '<span>';
					$html .= $current_term;
					if(SHOW_DEBUG) {
						$html .= ' [' . $current_locator_ds->section_tipo.'_'.$current_locator_ds->section_id . ']';
					}
					$html .= '</span>';

				$html .= '</li>';
			}
			$html .= '</ul>';
		}//end if (!empty($dato))

	// end wrapper
		$html .= '</div>';//end semantic_wrapper

	echo $html;