/**
 * THE CONFIGURATION HAS ONE RESOLUTION PATH — every layer and every cross-field law,
 * asserted through the pure resolveConfig() against files this gate writes itself.
 * The resolved object is bound as `resolved`, never `config`.
 *
 * unixEnv() states NODE_ENV=test so the refusal tests can carry the token in the file;
 * the production laws (no env-file secret, no package-dir fallback) have their own blocks.
 */

import { afterEach, describe, expect, test } from 'bun:test';
import { chmodSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  ConfigError,
  CREDENTIALS_DIR_VAR,
  ENV_FILE_VAR,
  KNOWN_KEYS,
  defaultEnvFilePath,
  isUnspecifiedHost,
  resolveConfig,
  type ConfigSources,
} from '../src/config';
import { MODES } from '../src/provision/layout';
import { scratchPath } from './fixtures/instance';

const GATE_DIR = scratchPath('config_gate');
const ENV_FILE = join(GATE_DIR, 'env');
const CREDS_DIR = join(GATE_DIR, 'credentials');
const TOKEN = 'x'.repeat(40);

/** The AgentConfig field names (the plan's fixed interface + LOG_LEVEL) = the env-file keys. */
const AGENT_CONFIG_FIELDS = [
  'INSTANCE', 'LISTEN_KIND', 'LOG_LEVEL', 'MAX_BUNDLE_BYTES', 'MAX_BUNDLE_ENTRIES',
  'MEDIA_MODE', 'MEDIA_ROOT', 'NODE_ENV', 'PHP_BIN', 'RELEASES_RETAINED', 'SERVICE_TOKEN',
  'SOCKET_PATH', 'STATE_ROOT', 'TLS_CERT_FILE', 'TLS_CLIENT_CA_FILE', 'TLS_HOST', 'TLS_KEY_FILE',
  'TLS_PORT', 'V2_HEALTH_URL', 'V2_UNIT', 'WEB_CONFIGTEST_BIN', 'WEB_SERVER', 'WEB_UNIT',
];

afterEach(() => rmSync(GATE_DIR, { recursive: true, force: true }));

/** The smallest unix-socket env file that resolves (NODE_ENV=test: the token may sit here). */
function unixEnv(overrides: Record<string, string> = {}): Record<string, string> {
  return {
    INSTANCE: 'gate',
    NODE_ENV: 'test',
    LISTEN_KIND: 'unix',
    SOCKET_PATH: './a.sock', // short: the gate dir is deeper than the suite's socket dir (sun_path)
    SERVICE_TOKEN: TOKEN,
    STATE_ROOT: './state',
    WEB_SERVER: 'nginx',
    WEB_UNIT: 'nginx',
    WEB_CONFIGTEST_BIN: '/usr/sbin/nginx',
    MEDIA_MODE: 'shared',
    MEDIA_ROOT: './media',
    PHP_BIN: '/usr/bin/php',
    V2_UNIT: 'dedalo-publication-v2-gate',
    V2_HEALTH_URL: 'http://127.0.0.1:3100/dedalo/publication/server_api/v2/health',
    ...overrides,
  };
}

/** The smallest mTLS env file that resolves. */
function tlsEnv(overrides: Record<string, string> = {}): Record<string, string> {
  const base = unixEnv({
    LISTEN_KIND: 'tls',
    TLS_HOST: '10.8.0.2',
    TLS_PORT: '7443',
    TLS_CERT_FILE: './tls/server.crt',
    TLS_KEY_FILE: './tls/server.key',
    TLS_CLIENT_CA_FILE: './tls/client_ca.crt',
  });
  delete base.SOCKET_PATH;
  return { ...base, ...overrides };
}

/** A production env file: no NODE_ENV (the default), no SERVICE_TOKEN (it is a credential). */
function productionEnv(overrides: Record<string, string> = {}): Record<string, string> {
  const values = unixEnv(overrides);
  delete values.NODE_ENV;
  delete values.SERVICE_TOKEN;
  return { ...values, ...overrides };
}

function writeEnvFile(values: Record<string, string>): string {
  mkdirSync(GATE_DIR, { recursive: true });
  const body = Object.entries(values)
    .map(([key, value]) => `${key}="${value}"`)
    .join('\n');
  writeFileSync(ENV_FILE, `# generated by a gate\n${body}\n`, 'utf8');
  return ENV_FILE;
}

function writeCredential(name: string, value: string): string {
  mkdirSync(CREDS_DIR, { recursive: true });
  writeFileSync(join(CREDS_DIR, name), `${value}\n`, 'utf8');
  return CREDS_DIR;
}

function sources(patch: Partial<ConfigSources> = {}): ConfigSources {
  return { envFilePath: ENV_FILE, ambient: {}, credentialsDir: null, ...patch };
}

/** Resolve and return the refusal message (fails the test if it resolved). */
function refusal(src: ConfigSources = sources()): string {
  try {
    resolveConfig(src);
  } catch (error) {
    expect(error).toBeInstanceOf(ConfigError);
    const message = (error as Error).message;
    expect(message).not.toContain('\n');
    return message;
  }
  throw new Error('expected a ConfigError, the configuration resolved');
}

describe('a valid configuration resolves', () => {
  test('unix: paths resolve against the env file dir, defaults apply, the result is frozen', () => {
    writeEnvFile(unixEnv());
    const resolved = resolveConfig(sources());
    expect(resolved.INSTANCE).toBe('gate');
    expect(resolved.NODE_ENV).toBe('test');
    expect(resolved.LOG_LEVEL).toBe('info');
    expect(resolved.LISTEN_KIND).toBe('unix');
    expect(resolved.SOCKET_PATH).toBe(join(GATE_DIR, 'a.sock'));
    expect(resolved.STATE_ROOT).toBe(join(GATE_DIR, 'state'));
    expect(resolved.MEDIA_ROOT).toBe(join(GATE_DIR, 'media'));
    expect(resolved.RELEASES_RETAINED).toBe(3);
    expect(resolved.MAX_BUNDLE_BYTES).toBe(268435456);
    expect(resolved.MAX_BUNDLE_ENTRIES).toBe(200000);
    expect(resolved.TLS_HOST).toBeUndefined();
    for (const key of Object.keys(resolved)) expect(KNOWN_KEYS).toContain(key);
    expect(Object.isFrozen(resolved)).toBe(true);
  });

  test('tls: every TLS key resolves, the port is a number', () => {
    writeEnvFile(tlsEnv());
    const resolved = resolveConfig(sources());
    expect(resolved.LISTEN_KIND).toBe('tls');
    expect(resolved.TLS_HOST).toBe('10.8.0.2');
    expect(resolved.TLS_PORT).toBe(7443);
    expect(resolved.TLS_CLIENT_CA_FILE).toBe(join(GATE_DIR, 'tls', 'client_ca.crt'));
    expect(resolved.SOCKET_PATH).toBeUndefined();
  });

  test('MEDIA_MODE=none resolves without a media root', () => {
    const values = unixEnv({ MEDIA_MODE: 'none' });
    delete values.MEDIA_ROOT;
    writeEnvFile(values);
    expect(resolveConfig(sources()).MEDIA_ROOT).toBeUndefined();
  });

  test('an empty value is an unset value', () => {
    writeEnvFile(unixEnv({ TLS_HOST: '', TLS_CLIENT_CA_FILE: '' }));
    expect(resolveConfig(sources()).TLS_HOST).toBeUndefined();
  });

  test('production (the default NODE_ENV): secret-free env file + the credential resolves', () => {
    writeEnvFile(productionEnv());
    const resolved = resolveConfig(sources({ credentialsDir: writeCredential('SERVICE_TOKEN', TOKEN) }));
    expect(resolved.NODE_ENV).toBe('production');
    expect(resolved.SERVICE_TOKEN).toBe(TOKEN);
  });
});

describe('the transport fails closed', () => {
  test.each(['TLS_HOST', 'TLS_PORT', 'TLS_CERT_FILE', 'TLS_KEY_FILE', 'TLS_CLIENT_CA_FILE'])(
    'tls without %s is refused by name',
    key => {
      const values = tlsEnv();
      delete values[key];
      writeEnvFile(values);
      expect(refusal()).toContain(`${key} is required when LISTEN_KIND=tls`);
    },
  );

  test.each([
    '0.0.0.0', '::', '[::]', '0:0:0:0:0:0:0:0', '*',
    // Resolver numeric forms / non-literals Bun binds on EVERY interface (review of 3240fc9c10).
    '0', '0.0', '0x0', '00.0.0.0', 'localhost', 'agent.example.org', '010.8.0.2', '[10.8.0.2]',
    // IPv6 forms embedding IPv4 0.0.0.0 — also every interface.
    '::0.0.0.0', '0::0.0.0.0', '::ffff:0.0.0.0', '::ffff:0:0', '[::ffff:0.0.0.0]',
    // Any embedded-IPv4 form is refused outright: write the IPv4 address itself.
    '::ffff:10.8.0.2', '::10.8.0.2',
  ])(
    'TLS_HOST=%s (every interface, the public one included) is refused',
    host => {
      writeEnvFile(tlsEnv({ TLS_HOST: host }));
      expect(refusal()).toContain('TLS_HOST must name one interface');
    },
  );

  test.each(['10.8.0.2', '127.0.0.1', 'fd00::2', '[fd00::2]', '::1', 'fe80::1%en0'])(
    'TLS_HOST=%s (one interface, canonical literal) resolves',
    host => {
      writeEnvFile(tlsEnv({ TLS_HOST: host }));
      expect(resolveConfig(sources()).TLS_HOST).toBe(host);
    },
  );

  test('isUnspecifiedHost agrees with the TLS_HOST law', () => {
    expect(isUnspecifiedHost('::ffff:0:0')).toBe(true);
    expect(isUnspecifiedHost('0')).toBe(true);
    expect(isUnspecifiedHost('10.8.0.2')).toBe(false);
  });

  test('plain TCP does not exist', () => {
    writeEnvFile(unixEnv({ LISTEN_KIND: 'tcp' }));
    expect(refusal()).toContain('plain TCP does not exist');
  });

  test('unix without a socket is refused', () => {
    const values = unixEnv();
    delete values.SOCKET_PATH;
    writeEnvFile(values);
    expect(refusal()).toContain('SOCKET_PATH is required when LISTEN_KIND=unix');
  });

  test('a TLS key on a unix listener is refused (the operator believes in a transport the agent would not use)', () => {
    writeEnvFile(unixEnv({ TLS_CLIENT_CA_FILE: './ca.crt' }));
    expect(refusal()).toContain('TLS_CLIENT_CA_FILE is set but LISTEN_KIND=unix');
  });

  test('a socket on a tls listener is refused', () => {
    writeEnvFile(tlsEnv({ SOCKET_PATH: './a.sock' }));
    expect(refusal()).toContain('SOCKET_PATH is set but LISTEN_KIND=tls');
  });

  test('a socket path beyond sun_path is refused at config, not at bind', () => {
    writeEnvFile(unixEnv({ SOCKET_PATH: `/tmp/${'s'.repeat(120)}.sock` }));
    expect(refusal()).toContain('sun_path limit');
  });

  test('TLS_PORT out of range is refused', () => {
    writeEnvFile(tlsEnv({ TLS_PORT: '70000' }));
    expect(refusal()).toContain('TLS_PORT');
  });
});

describe('media and state roots', () => {
  test('shared without MEDIA_ROOT is refused', () => {
    const values = unixEnv();
    delete values.MEDIA_ROOT;
    writeEnvFile(values);
    expect(refusal()).toContain('MEDIA_ROOT is required when MEDIA_MODE=shared');
  });

  test('none with MEDIA_ROOT is refused', () => {
    writeEnvFile(unixEnv({ MEDIA_MODE: 'none' }));
    expect(refusal()).toContain('MEDIA_ROOT is set but MEDIA_MODE=none');
  });

  test.each([['./state/media'], ['./state'], ['.']])('MEDIA_ROOT=%s overlapping STATE_ROOT is refused', root => {
    writeEnvFile(unixEnv({ MEDIA_ROOT: root }));
    expect(refusal()).toContain('MEDIA_ROOT and STATE_ROOT must not contain each other');
  });
});

describe('the grammar', () => {
  test.each(['Test', 'a', '1abc', 'with-dash', 'x'.repeat(33)])('instance %s is refused', name => {
    writeEnvFile(unixEnv({ INSTANCE: name }));
    expect(refusal()).toContain('INSTANCE must match');
  });

  test('a missing required key is named', () => {
    const values = unixEnv();
    delete values.STATE_ROOT;
    writeEnvFile(values);
    expect(refusal()).toContain('STATE_ROOT is required');
  });

  test.each(['LISTEN_KIND', 'WEB_SERVER', 'MEDIA_MODE'])('a missing enum key %s is "required", not an invalid option', key => {
    const values = unixEnv();
    delete values[key];
    if (key === 'MEDIA_MODE') delete values.MEDIA_ROOT;
    writeEnvFile(values);
    const message = refusal();
    expect(message).toContain(`${key} is required`);
    expect(message).not.toContain('plain TCP');
    expect(message).not.toContain('Invalid option');
  });

  test('a wrong enum value keeps its own message', () => {
    writeEnvFile(unixEnv({ LISTEN_KIND: 'tcp' }));
    expect(refusal()).toContain('LISTEN_KIND must be unix or tls (plain TCP does not exist)');
  });

  test('a short SERVICE_TOKEN is refused without quoting it', () => {
    writeEnvFile(unixEnv({ SERVICE_TOKEN: 'short-secret-value' }));
    const message = refusal();
    expect(message).toContain('SERVICE_TOKEN must be at least 32 characters');
    expect(message).not.toContain('short-secret-value');
  });

  test('RELEASES_RETAINED below 2 is refused (rollback needs a previous release)', () => {
    writeEnvFile(unixEnv({ RELEASES_RETAINED: '1' }));
    expect(refusal()).toContain('RELEASES_RETAINED');
  });

  test('a relative binary is refused', () => {
    writeEnvFile(unixEnv({ PHP_BIN: 'php' }));
    expect(refusal()).toContain('PHP_BIN must be an absolute path');
  });

  test('a unit name with a slash or a space is refused', () => {
    writeEnvFile(unixEnv({ WEB_UNIT: 'apache2; rm' }));
    expect(refusal()).toContain('WEB_UNIT must match');
    // The configtest binary is one of the server's closed candidates, never a free path.
    writeEnvFile(unixEnv({ WEB_CONFIGTEST_BIN: '/opt/evil/nginx' }));
    expect(refusal()).toContain('WEB_CONFIGTEST_BIN must be one of /usr/sbin/nginx for WEB_SERVER=nginx');
    writeEnvFile(unixEnv({ WEB_SERVER: 'apache', WEB_CONFIGTEST_BIN: '/usr/sbin/nginx' }));
    expect(refusal()).toContain('WEB_CONFIGTEST_BIN must be one of /usr/sbin/apache2ctl, /usr/sbin/apachectl');
  });

  test.each(['https://127.0.0.1:3100/health', 'http://10.0.0.5:3100/health', 'not a url'])(
    'V2_HEALTH_URL %s is refused (loopback http only)',
    url => {
      writeEnvFile(unixEnv({ V2_HEALTH_URL: url }));
      expect(refusal()).toContain('V2_HEALTH_URL must be an http:// URL');
    },
  );

  test('an unknown key is refused by name, with its origin', () => {
    writeEnvFile(unixEnv({ LISTEN_PORT: '7443' }));
    expect(refusal()).toContain('Unknown configuration key(s): LISTEN_PORT (env-file)');
  });

  test('neither the env-file selector nor the credential directory is a key the file may carry', () => {
    writeEnvFile(unixEnv({ [ENV_FILE_VAR]: '/etc/other.env', [CREDENTIALS_DIR_VAR]: '/run/creds' }));
    const message = refusal();
    expect(message).toContain(`${ENV_FILE_VAR} (env-file)`);
    expect(message).toContain(`${CREDENTIALS_DIR_VAR} (env-file)`);
  });

  test('an unreadable line is refused with its line number', () => {
    mkdirSync(GATE_DIR, { recursive: true });
    writeFileSync(ENV_FILE, 'INSTANCE=gate\nthis is not an assignment\n', 'utf8');
    expect(refusal()).toContain('(line 2)');
  });

  test('a missing env file is refused', () => {
    expect(refusal(sources({ envFilePath: join(GATE_DIR, 'absent.env') }))).toContain('No env file at');
  });

  test('KNOWN_KEYS is exactly the AgentConfig field names (the renderers emit these, Tasks 8/9/11)', () => {
    expect([...KNOWN_KEYS]).toEqual(AGENT_CONFIG_FIELDS);
    expect(ENV_FILE_VAR).toBe('DEDALO_HOST_AGENT_ENV_FILE');
  });
});

describe('the credential law under production', () => {
  test('SERVICE_TOKEN in the env file is refused (default NODE_ENV), its value never quoted', () => {
    writeEnvFile(productionEnv({ SERVICE_TOKEN: TOKEN }));
    const message = refusal();
    expect(message).toContain('SERVICE_TOKEN is set in the env file');
    expect(message).toContain('LoadCredential');
    expect(message).not.toContain(TOKEN);
  });

  test('…even when the credential is also present (the file must not hold a copy)', () => {
    writeEnvFile(productionEnv({ SERVICE_TOKEN: TOKEN }));
    expect(refusal(sources({ credentialsDir: writeCredential('SERVICE_TOKEN', TOKEN) }))).toContain(
      'SERVICE_TOKEN is set in the env file',
    );
  });

  test('…and when production comes from the ambient NODE_ENV', () => {
    const values = unixEnv();
    delete values.NODE_ENV;
    writeEnvFile(values);
    expect(refusal(sources({ ambient: { NODE_ENV: 'production' } }))).toContain(
      'SERVICE_TOKEN is set in the env file',
    );
  });
});

describe('the ambient allowlist', () => {
  test('fills only what the file is silent on', () => {
    const values = unixEnv({ LOG_LEVEL: 'warn' });
    delete values.NODE_ENV;
    delete values.SERVICE_TOKEN;
    writeEnvFile(values);
    const resolved = resolveConfig(
      sources({ ambient: { NODE_ENV: 'production', LOG_LEVEL: 'debug' }, credentialsDir: writeCredential('SERVICE_TOKEN', TOKEN) }),
    );
    expect(resolved.NODE_ENV).toBe('production');
    expect(resolved.LOG_LEVEL).toBe('warn');
  });

  test('test mode is never ambient: NODE_ENV=test over a file silent on it is REFUSED', () => {
    const values = unixEnv();
    delete values.NODE_ENV;
    delete values.SERVICE_TOKEN;
    writeEnvFile(values);
    const message = refusal(
      sources({ ambient: { NODE_ENV: 'test' }, credentialsDir: writeCredential('SERVICE_TOKEN', TOKEN) }),
    );
    expect(message).toContain('NODE_ENV=test may come only from the env file');
  });

  test.each(['development', 'staging', 'Production', 'TEST'])(
    'an ambient NODE_ENV=%p that is neither production nor test gets its own refusal',
    value => {
      const values = unixEnv();
      delete values.NODE_ENV;
      delete values.SERVICE_TOKEN;
      writeEnvFile(values);
      const message = refusal(
        sources({ ambient: { NODE_ENV: value }, credentialsDir: writeCredential('SERVICE_TOKEN', TOKEN) }),
      );
      expect(message).toContain(`NODE_ENV='${value}' is not a mode of this agent`);
      expect(message).not.toContain('NODE_ENV=test may come only from the env file');
    },
  );

  test('…while a file that states NODE_ENV wins over the ambient one', () => {
    writeEnvFile(unixEnv());
    expect(resolveConfig(sources({ ambient: { NODE_ENV: 'production' } })).NODE_ENV).toBe('test');
  });

  test('every other ambient variable is ignored — even SERVICE_TOKEN and INSTANCE', () => {
    const values = unixEnv();
    delete values.SERVICE_TOKEN;
    delete values.INSTANCE;
    writeEnvFile(values);
    const message = refusal(
      sources({ ambient: { SERVICE_TOKEN: TOKEN, INSTANCE: 'gate', STATE_ROOT: '/elsewhere' } }),
    );
    expect(message).toContain('SERVICE_TOKEN is required');
    expect(message).toContain('INSTANCE is required');
  });
});

describe('the credential layer', () => {
  test('$CREDENTIALS_DIRECTORY/SERVICE_TOKEN wins over the env file', () => {
    writeEnvFile(unixEnv());
    const credential = 'c'.repeat(48);
    const resolved = resolveConfig(sources({ credentialsDir: writeCredential('SERVICE_TOKEN', credential) }));
    expect(resolved.SERVICE_TOKEN).toBe(credential);
  });

  test('a secret-free env file resolves with the credential', () => {
    const values = unixEnv();
    delete values.SERVICE_TOKEN;
    writeEnvFile(values);
    const resolved = resolveConfig(sources({ credentialsDir: writeCredential('SERVICE_TOKEN', TOKEN) }));
    expect(resolved.SERVICE_TOKEN).toBe(TOKEN);
  });

  test('any other credential is refused by name', () => {
    writeEnvFile(unixEnv());
    writeCredential('SERVICE_TOKEN', TOKEN);
    expect(refusal(sources({ credentialsDir: writeCredential('STATE_ROOT', '/x') }))).toContain(
      "The credential 'STATE_ROOT'",
    );
  });

  test('an unreadable credential directory is refused', () => {
    writeEnvFile(unixEnv());
    expect(refusal(sources({ credentialsDir: join(GATE_DIR, 'no_such_dir') }))).toContain(
      'could not be read',
    );
  });

  test('a subdirectory inside the credential directory is skipped', () => {
    writeEnvFile(unixEnv());
    writeCredential('SERVICE_TOKEN', TOKEN);
    mkdirSync(join(CREDS_DIR, 'nested'));
    chmodSync(join(CREDS_DIR, 'nested'), 0o700);
    expect(resolveConfig(sources({ credentialsDir: CREDS_DIR })).SERVICE_TOKEN).toBe(TOKEN);
  });
});

describe('defaultEnvFilePath', () => {
  test('a named file must be absolute', () => {
    expect(() => defaultEnvFilePath({ [ENV_FILE_VAR]: 'relative.env' })).toThrow(ConfigError);
  });

  test('a named absolute file is used as is, in any mode', () => {
    expect(defaultEnvFilePath({ [ENV_FILE_VAR]: '/etc/dedalo_publication_host/test/agent.env' })).toBe(
      '/etc/dedalo_publication_host/test/agent.env',
    );
  });

  test('NODE_ENV=test with no named file selects the package .env.test', () => {
    expect(defaultEnvFilePath({ NODE_ENV: 'test' }).endsWith('/.env.test')).toBe(true);
  });

  test('outside NODE_ENV=test an unnamed env file is REFUSED — never a package-dir .env', () => {
    for (const ambient of [{}, { NODE_ENV: 'production' }]) {
      expect(() => defaultEnvFilePath(ambient)).toThrow(ENV_FILE_VAR);
    }
  });
});

describe('the header states what the provisioner renders', () => {
  test('env-file owner and mode in the src/config.ts header = layout.ts MODES.envFile', () => {
    const header = readFileSync(join(import.meta.dir, '..', 'src', 'config.ts'), 'utf8').split('*/')[0]!.replace(/\s+\*\s+/g, ' ');
    const { owner, group, mode } = MODES.envFile;
    expect(header).toContain(`renders it ${owner}:${group} 0${mode.toString(8)}`);
    expect(header).not.toMatch(/the file is 0640/);
  });
});
