/**
 * THE COMMITTED EXAMPLES ARE THE DOCUMENTATION; THIS KEEPS THEM TRUE (precedent:
 * publication/site_builder/tests/provision_examples.test.ts).
 *
 * Each committed declaration (deploy/examples/*.example.json) parses through Task 8's own
 * parseDeclaration. deploy/examples/rendered/<variant>/<host path> is byte-equal to a fresh
 * renderAll of it with a fixed fake token's facts. The set is closed in both directions, and
 * deploy/examples/rendered.index lists each artifact's mode and owner (a checkout cannot carry
 * them). TLS material is issued at apply time and never rendered. To change one: change the
 * renderer or the declaration, then
 *     UPDATE_EXAMPLES=1 bun test ./tests/provision_examples.test.ts
 * which rewrites and then FAILS on purpose; re-run without it.
 */

import { describe, expect, test } from 'bun:test';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { renderAll } from '../src/provision/plan';
import type { Artifact } from '../src/provision/render/types';
import { parseDeclaration } from '../src/provision/schema';
import { factsFor } from './fixtures/provision_facts';

const EXAMPLES = join(import.meta.dir, '..', 'deploy', 'examples');
const ROOT = join(EXAMPLES, 'rendered');
const INDEX = join(EXAMPLES, 'rendered.index');
const UPDATE = process.env.UPDATE_EXAMPLES === '1';

/** A fixed, obviously fake token: the examples need a stable fingerprint, never a real secret. */
const EXAMPLE_TOKEN = 'example-service-token-not-a-secret-0000000000';
const EXAMPLE_FACTS = factsFor('example', EXAMPLE_TOKEN);

const VARIANTS = Object.freeze({
  'tls-nginx': 'instance.example.json',
  'unix-apache': 'instance.single_machine.example.json',
});
type Variant = keyof typeof VARIANTS;

const RENDERS: ReadonlyArray<{ variant: Variant; artifacts: Artifact[] }> = (Object.keys(VARIANTS) as Variant[]).map(
  variant => {
    const source = join(EXAMPLES, VARIANTS[variant]);
    const { layout } = parseDeclaration(JSON.parse(readFileSync(source, 'utf8')), source);
    return { variant, artifacts: renderAll(layout, EXAMPLE_FACTS) };
  },
);

const committedPath = (variant: Variant, hostPath: string) => join(ROOT, variant, ...hostPath.split('/').filter(Boolean));

function walk(dir: string): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .sort()
    .flatMap(name => {
      const full = join(dir, name);
      return statSync(full).isDirectory() ? walk(full) : [full];
    });
}

function formatIndex(): string {
  const lines = [
    '# GENERATED by tests/provision_examples.test.ts — do NOT edit.',
    '# mode  owner:group   kind              path on the host   (deploy/examples/rendered/<variant>/<path>)',
  ];
  for (const { variant, artifacts } of RENDERS) {
    lines.push('', `[${variant}]  ${VARIANTS[variant]}`);
    for (const a of artifacts) {
      lines.push(`${a.mode.toString(8).padStart(4, '0')}  ${`${a.owner}:${a.group}`.padEnd(12)}  ${a.kind.padEnd(16)}  ${a.path}`);
    }
  }
  return `${lines.join('\n')}\n`;
}

if (UPDATE) {
  test('UPDATE_EXAMPLES=1 rewrites the committed examples and fails so the run is never green', () => {
    mkdirSync(ROOT, { recursive: true });
    const changed: string[] = [];
    for (const { variant, artifacts } of RENDERS) {
      const claimed = new Set(artifacts.map(a => committedPath(variant, a.path)));
      for (const stale of walk(join(ROOT, variant))) {
        if (!claimed.has(stale)) {
          rmSync(stale);
          changed.push(`removed ${relative(EXAMPLES, stale)}`);
        }
      }
      for (const a of artifacts) {
        const target = committedPath(variant, a.path);
        if (!existsSync(target) || readFileSync(target, 'utf8') !== a.body) {
          mkdirSync(dirname(target), { recursive: true });
          writeFileSync(target, a.body);
          changed.push(`wrote ${relative(EXAMPLES, target)}`);
        }
      }
    }
    for (const dir of readdirSync(ROOT)) {
      if (!(dir in VARIANTS)) rmSync(join(ROOT, dir), { recursive: true, force: true });
    }
    if (!existsSync(INDEX) || readFileSync(INDEX, 'utf8') !== formatIndex()) {
      writeFileSync(INDEX, formatIndex());
      changed.push('wrote rendered.index');
    }
    throw new Error(`UPDATE_EXAMPLES=1 rewrote the examples (deliberately red):\n  ${changed.join('\n  ') || '(nothing changed)'}`);
  });
}

describe('committed rendered examples', () => {
  test('both declarations are instance `example` and parse through the real schema', () => {
    expect(RENDERS.map(r => r.artifacts[0]?.body.split('\n')[0]?.split(' ')[2])).toEqual(['example', 'example']);
  });

  test('every artifact is committed byte-for-byte', () => {
    for (const { variant, artifacts } of RENDERS) {
      for (const a of artifacts) {
        const file = committedPath(variant, a.path);
        expect(existsSync(file) ? readFileSync(file, 'utf8') : `<missing ${relative(EXAMPLES, file)}>`).toBe(a.body);
      }
    }
  });

  test('the set is closed: no committed file without a renderer, no variant without a declaration', () => {
    const claimed = RENDERS.flatMap(({ variant, artifacts }) => artifacts.map(a => committedPath(variant, a.path))).sort();
    expect(walk(ROOT).map(f => f.split(sep).join('/')).sort()).toEqual(claimed.map(f => f.split(sep).join('/')));
  });

  test('rendered.index matches the MODES table', () => {
    expect(readFileSync(INDEX, 'utf8')).toBe(formatIndex());
  });

  test('a render is stable: same declaration, same bytes', () => {
    for (const { variant, artifacts } of RENDERS) {
      const source = join(EXAMPLES, VARIANTS[variant]);
      const { layout } = parseDeclaration(JSON.parse(readFileSync(source, 'utf8')), source);
      expect(renderAll(layout, EXAMPLE_FACTS).map(a => a.body)).toEqual(artifacts.map(a => a.body));
    }
  });

  test('no committed example carries the token value', () => {
    for (const file of walk(ROOT)) expect(readFileSync(file, 'utf8')).not.toContain(EXAMPLE_TOKEN);
  });
});
