/**
 * rules.apply — the check → write → swap → configtest → reload | restore transaction (Task 5).
 *
 * Every privileged effect is the injected Exec: no sudo, no systemctl. The fake records
 * the ORDER of calls and the live include's bytes at configtest time, so "configtest ran
 * against the new file" and "a failed configtest never reloads" are observed, not inferred.
 * Includes are written in the syntax of this suite's web server (.env.test) and name
 * MEDIA_ROOT, so they pass the directive allowlist and reach the transaction.
 */

import { afterEach, beforeEach, describe, expect, test } from 'bun:test';
import { existsSync, readFileSync, statSync } from 'node:fs';
import { writeFile } from 'node:fs/promises';
import { readAudit } from '../src/audit';
import { config } from '../src/config';
import { ApiError } from '../src/errors';
import { type Exec, type ExecResult, setExecForTests } from '../src/exec';
import { routeRequest } from '../src/router';
import { handleRulesApply } from '../src/routes/rules_apply';
import { MAX_RULES_BYTES, appliedRulesHash, applyRules, rulesPaths, stampedHash } from '../src/rules/apply';
import { ACTOR_HEADER } from '../src/security/auth';
import { renderProblem } from '../src/util/response';
import { resetInstance } from './fixtures/instance';

const H1 = 'a'.repeat(64);
const H2 = 'b'.repeat(64);
const H3 = 'c'.repeat(64);
const ACTOR = 'publisher';
const SERVER = config.WEB_SERVER;
const OTHER_SERVER = SERVER === 'apache' ? 'nginx' : 'apache';
const MEDIA_ROOT = config.MEDIA_ROOT as string;

/** Three allowlisted bodies per server, all naming MEDIA_ROOT, all different bytes. */
const BODY = {
  apache: {
    a: `Alias /dedalo/media "${MEDIA_ROOT}"`,
    b: `Alias /dedalo/media "${MEDIA_ROOT}"\nRewriteEngine On`,
    c: `Alias /dedalo/media "${MEDIA_ROOT}"\nRewriteEngine Off`,
  },
  nginx: {
    a: `location ^~ /dedalo/media/ { alias ${MEDIA_ROOT}/; }`,
    b: `location ^~ /dedalo/media/ { alias ${MEDIA_ROOT}/; mp4; }`,
    c: `location ^~ /dedalo/media/ { return 404; }`,
  },
}[SERVER];

function rulesText(hash: string, body: string = BODY.a): string {
  return [
    '# Dédalo media access control, PUBLICATION-HOST profile. GENERATED by',
    '# src/core/media/publication_host_rules.ts. Do not edit: re-render instead.',
    `# config-hash: ${hash}`,
    '',
    body,
    '',
  ].join('\n');
}

/** What each server prints when the include fails at line 5 (paths and text: never on the wire). */
function configtestFailure(): string {
  const live = rulesPaths().live;
  return SERVER === 'apache'
    ? `AH00526: Syntax error on line 5 of ${live}:\nInvalid command 'Bogus'`
    : `nginx: [emerg] unknown directive "bogus" in ${live}:5\nnginx: configuration file test failed`;
}

interface FakeExec {
  calls: string[];
  seenAtConfigtest: (string | null)[];
}

let restoreExec: (() => void) | null = null;

/** Scripted exit codes, consumed in order; an exhausted script answers 0. */
function installFakeExec(script: { configtest?: number[]; reload?: number[]; configtestThrows?: boolean } = {}): FakeExec {
  const configtest = [...(script.configtest ?? [])];
  const reload = [...(script.reload ?? [])];
  const state: FakeExec = { calls: [], seenAtConfigtest: [] };
  const fake: Exec = {
    async webConfigtest(): Promise<ExecResult> {
      state.calls.push('configtest');
      const live = rulesPaths().live;
      state.seenAtConfigtest.push(existsSync(live) ? readFileSync(live, 'utf8') : null);
      if (script.configtestThrows) throw new Error('sudo: command not found');
      const code = configtest.shift() ?? 0;
      return { code, stdout: '', stderr: code === 0 ? 'Syntax OK' : configtestFailure() };
    },
    async webReload(): Promise<ExecResult> {
      state.calls.push('reload');
      const code = reload.shift() ?? 0;
      return { code, stdout: '', stderr: code === 0 ? '' : `Job for ${config.WEB_UNIT}.service failed (/etc/secret.conf)` };
    },
    async v2Restart() {
      throw new Error('rules.apply must never restart the v2 unit');
    },
    async phpLint() {
      throw new Error('rules.apply must never lint PHP');
    },
    v2ScratchBoot() {
      throw new Error('rules.apply must never boot a v2 scratch');
    },
  };
  restoreExec?.();
  restoreExec = setExecForTests(fake);
  return state;
}

async function caught(promise: Promise<unknown>): Promise<ApiError> {
  try {
    await promise;
  } catch (error) {
    if (error instanceof ApiError) return error;
    throw error;
  }
  throw new Error('expected the apply to be refused');
}

/** `<outcome>:<result>` per rules.apply audit line, sorted. */
async function outcomes(): Promise<string[]> {
  return (await readAudit())
    .filter(entry => entry.action === 'rules.apply')
    .map(entry => `${entry.outcome}:${String(entry.detail?.result)}`)
    .sort();
}

function live(): string | null {
  const path = rulesPaths().live;
  return existsSync(path) ? readFileSync(path, 'utf8') : null;
}

const apply = (text: string, hash: string, server: 'apache' | 'nginx' = SERVER) =>
  applyRules({ server, text, hash, actor: ACTOR });

beforeEach(resetInstance);
afterEach(async () => {
  restoreExec?.();
  restoreExec = null;
  await resetInstance();
});

describe('stampedHash', () => {
  test('reads exactly one stamp from the leading comment block', () => {
    expect(stampedHash(rulesText(H1))).toBe(H1);
    expect(stampedHash(`Alias x\n# config-hash: ${H1}\n`)).toBeNull();
    expect(stampedHash(`# a\n\n# config-hash: ${H1}\n`)).toBeNull();
    expect(stampedHash(`# config-hash: ${H1}\n# config-hash: ${H2}\n`)).toBeNull();
    expect(stampedHash(`# config-hash: ${H1.toUpperCase()}\n`)).toBeNull();
  });
});

describe('applyRules — success', () => {
  test('a first apply writes 0640, configtests the NEW file, reloads, reports the hash', async () => {
    const fake = installFakeExec();
    expect(await apply(rulesText(H1), H1)).toEqual({ hash: H1, reloaded: true });
    expect(fake.calls).toEqual(['configtest', 'reload']);
    expect(fake.seenAtConfigtest).toEqual([rulesText(H1)]);
    const paths = rulesPaths();
    expect(live()).toBe(rulesText(H1));
    expect(statSync(paths.live).mode & 0o777).toBe(0o640);
    expect(existsSync(paths.next)).toBe(false);
    expect(existsSync(paths.prev)).toBe(false);
    expect(existsSync(paths.pending)).toBe(false);
    expect(appliedRulesHash()).toBe(H1);
    expect(await outcomes()).toEqual(['ok:applied']);
    const [entry] = await readAudit();
    expect(entry).toMatchObject({ actor: ACTOR, action: 'rules.apply', outcome: 'ok' });
  });

  test('a replacing apply keeps the previously loaded include as .prev', async () => {
    installFakeExec();
    await apply(rulesText(H1), H1);
    await apply(rulesText(H2, BODY.b), H2);
    expect(live()).toBe(rulesText(H2, BODY.b));
    expect(readFileSync(rulesPaths().prev, 'utf8')).toBe(rulesText(H1));
    expect(appliedRulesHash()).toBe(H2);
  });
});

describe('applyRules — configtest failure restores, never reloads', () => {
  test('with a previous include: restored byte for byte, configtest re-run, codes + line reported', async () => {
    installFakeExec();
    await apply(rulesText(H1), H1);
    const fake = installFakeExec({ configtest: [1, 0] });

    const error = await caught(apply(rulesText(H2, BODY.b), H2));

    expect(error.status).toBe(422);
    expect(error.extensions).toEqual({
      reason: 'configtest_failed',
      restored: 'previous',
      configtest: { code: 1, line: 5 },
      configtest_after_restore: { code: 0 },
    });
    expect(fake.calls).toEqual(['configtest', 'configtest']);
    expect(fake.seenAtConfigtest).toEqual([rulesText(H2, BODY.b), rulesText(H1)]);
    expect(live()).toBe(rulesText(H1));
    expect(existsSync(rulesPaths().pending)).toBe(false);
    expect(appliedRulesHash()).toBe(H1);
    expect(await outcomes()).toEqual(['failed:configtest_failed', 'ok:applied']);
    // The full output is in the audit line, never in the problem.
    const failed = (await readAudit()).find(entry => entry.outcome === 'failed');
    expect(JSON.stringify(failed?.detail)).toContain(rulesPaths().live);
  });

  test('without a previous include: the new file is removed', async () => {
    const fake = installFakeExec({ configtest: [1, 0] });
    const error = await caught(apply(rulesText(H1), H1));
    expect(error.extensions).toMatchObject({ reason: 'configtest_failed', restored: 'removed' });
    expect(fake.calls).toEqual(['configtest', 'configtest']);
    expect(live()).toBeNull();
    expect(appliedRulesHash()).toBeNull();
  });

  test('a configtest that cannot even spawn is a failure, and still restores', async () => {
    const fake = installFakeExec({ configtestThrows: true });
    const error = await caught(apply(rulesText(H1), H1));
    expect(error.extensions).toMatchObject({
      reason: 'configtest_failed',
      restored: 'removed',
      configtest: { code: -1, line: null },
    });
    expect(fake.calls).toEqual(['configtest', 'configtest']);
    expect(live()).toBeNull();
  });
});

describe('applyRules — reload failure', () => {
  test('keeps the tested file, reports the state, and a re-push completes it without a write', async () => {
    installFakeExec();
    await apply(rulesText(H1), H1);
    const failing = installFakeExec({ reload: [1] });

    const error = await caught(apply(rulesText(H2, BODY.b), H2));

    expect(error.status).toBe(503);
    expect(error.extensions).toEqual({
      reason: 'reload_failed',
      applied_hash: H2,
      reload_pending: true,
      reload: { code: 1 },
    });
    expect(failing.calls).toEqual(['configtest', 'reload']);
    expect(live()).toBe(rulesText(H2, BODY.b));
    expect(existsSync(rulesPaths().pending)).toBe(true);
    expect(appliedRulesHash()).toBeNull();

    const retry = installFakeExec();
    const mtimeBefore = statSync(rulesPaths().live).mtimeMs;
    expect(await apply(rulesText(H2, BODY.b), H2)).toEqual({ hash: H2, reloaded: true });
    expect(retry.calls).toEqual(['configtest', 'reload']);
    expect(statSync(rulesPaths().live).mtimeMs).toBe(mtimeBefore);
    // .prev is still the include the server LOADED (H1), not the never-loaded H2.
    expect(readFileSync(rulesPaths().prev, 'utf8')).toBe(rulesText(H1));
    expect(existsSync(rulesPaths().pending)).toBe(false);
    expect(appliedRulesHash()).toBe(H2);
    expect(await outcomes()).toEqual(['failed:reload_failed', 'ok:applied', 'ok:applied']);
  });

  test('a different apply after a failed reload restores the LOADED include, not the pending one', async () => {
    installFakeExec();
    await apply(rulesText(H1), H1);
    installFakeExec({ reload: [1] });
    await caught(apply(rulesText(H2, BODY.b), H2));
    installFakeExec({ configtest: [1, 0] });

    const error = await caught(apply(rulesText(H3, BODY.c), H3));

    expect(error.extensions).toMatchObject({ reason: 'configtest_failed', restored: 'previous' });
    expect(live()).toBe(rulesText(H1));
    expect(appliedRulesHash()).toBe(H1);
  });
});

describe('applyRules — refusals touch nothing', () => {
  test('wrong server', async () => {
    const fake = installFakeExec();
    const error = await caught(apply(rulesText(H1), H1, OTHER_SERVER));
    expect(error.status).toBe(422);
    expect(error.extensions).toEqual({ reason: 'server_mismatch' });
    expect(fake.calls).toEqual([]);
    expect(live()).toBeNull();
    expect(await outcomes()).toEqual(['refused:refused']);
  });

  test('stamp and request disagree', async () => {
    const fake = installFakeExec();
    const error = await caught(apply(rulesText(H1), H2));
    expect(error.extensions).toEqual({ reason: 'hash_mismatch' });
    expect(fake.calls).toEqual([]);
    expect(live()).toBeNull();
  });

  test('missing stamp, malformed hash, NUL byte, oversize', async () => {
    const fake = installFakeExec();
    const cases: [string, string, string][] = [
      [`${BODY.a}\n`, H1, 'stamp_missing'],
      [rulesText(H1), H1.toUpperCase(), 'hash_invalid'],
      [rulesText(H1, `${BODY.a}\n#x\0y`), H1, 'rules_nul_byte'],
      [rulesText(H1, `${BODY.a}\n#${'#'.repeat(MAX_RULES_BYTES)}`), H1, 'rules_too_large'],
    ];
    for (const [text, hash, reason] of cases) {
      const error = await caught(apply(text, hash));
      expect(error.status).toBe(422);
      expect(error.extensions).toEqual({ reason });
    }
    expect(fake.calls).toEqual([]);
    expect(live()).toBeNull();
  });

  test('a correctly stamped include carrying a root-reachable directive is refused before any write or exec', async () => {
    const fake = installFakeExec();
    const hostile =
      SERVER === 'apache'
        ? [`LoadModule evil_module ${MEDIA_ROOT}/evil.so`, 'ErrorLog "|/bin/sh -c id"', `Include ${MEDIA_ROOT}/x.conf`]
        : [`load_module ${MEDIA_ROOT}/evil.so;`, 'error_log /etc/cron.d/x;', `include ${MEDIA_ROOT}/x.conf;`];
    for (const line of hostile) {
      const error = await caught(apply(rulesText(H1, `${BODY.a}\n${line}`), H1));
      expect(error.status).toBe(422);
      expect(error.extensions).toMatchObject({ reason: 'directive_refused', line: 6 });
    }
    expect(fake.calls).toEqual([]);
    expect(live()).toBeNull();
    expect(await outcomes()).toEqual(['refused:refused', 'refused:refused', 'refused:refused']);
  });
});

describe('applyRules — idempotency', () => {
  test('re-applying the live bytes writes nothing, reloads nothing, still reports reloaded:true', async () => {
    const fake = installFakeExec();
    await apply(rulesText(H1), H1);
    const mtimeBefore = statSync(rulesPaths().live).mtimeMs;
    expect(await apply(rulesText(H1), H1)).toEqual({ hash: H1, reloaded: true });
    expect(fake.calls).toEqual(['configtest', 'reload']);
    expect(statSync(rulesPaths().live).mtimeMs).toBe(mtimeBefore);
    expect(await outcomes()).toEqual(['ok:applied', 'ok:unchanged']);
  });

  test('same stamp, different bytes is NOT idempotent: the live file is repaired', async () => {
    const fake = installFakeExec();
    await apply(rulesText(H1), H1);
    await writeFile(rulesPaths().live, rulesText(H1, BODY.c));
    await apply(rulesText(H1), H1);
    expect(fake.calls).toEqual(['configtest', 'reload', 'configtest', 'reload']);
    expect(live()).toBe(rulesText(H1));
  });
});

describe('applyRules — serialization', () => {
  test('concurrent applies never interleave their configtest/reload pairs', async () => {
    const fake = installFakeExec();
    await Promise.all([apply(rulesText(H1), H1), apply(rulesText(H2, BODY.b), H2)]);
    expect(fake.calls).toEqual(['configtest', 'reload', 'configtest', 'reload']);
    expect(fake.seenAtConfigtest).toEqual([rulesText(H1), rulesText(H2, BODY.b)]);
    expect(appliedRulesHash()).toBe(H2);
  });
});

describe('what reaches the wire', () => {
  test('in production, neither problem carries configtest/reload output or a host path', async () => {
    installFakeExec();
    await apply(rulesText(H1), H1);
    installFakeExec({ configtest: [1, 0] });
    const configtest = await caught(apply(rulesText(H2, BODY.b), H2));
    installFakeExec({ reload: [1] });
    const reload = await caught(apply(rulesText(H3, BODY.c), H3));
    for (const error of [configtest, reload]) {
      const body = await renderProblem(error, 'production').text();
      for (const leak of ['AH00526', 'emerg', 'Syntax OK', 'Job for', '/etc/secret.conf', config.STATE_ROOT]) {
        expect(body).not.toContain(leak);
      }
    }
  });
});

describe('POST /v1/rules/apply', () => {
  const URL_ = new URL('http://agent.test/publication/host_agent/v1/rules/apply');

  function post(body: unknown, actor: string | null = ACTOR, extra: Record<string, string> = {}): Request {
    return new Request(URL_.href, {
      method: 'POST',
      headers: { 'content-type': 'application/json', ...(actor === null ? {} : { [ACTOR_HEADER]: actor }), ...extra },
      body: typeof body === 'string' ? body : JSON.stringify(body),
    });
  }

  test('through the router (bearer, actor header): 200 with the fixed result shape, actor audited', async () => {
    installFakeExec();
    const response = await routeRequest(
      post({ server: SERVER, text: rulesText(H1), hash: H1 }, 'curator.ana', {
        authorization: `Bearer ${config.SERVICE_TOKEN}`,
      }),
    );
    expect(response.status).toBe(200);
    expect(await response.json()).toEqual({ hash: H1, reloaded: true });
    expect((await readAudit())[0]).toMatchObject({ actor: 'curator.ana', outcome: 'ok' });
  });

  test('shape errors are 400 before anything runs', async () => {
    const fake = installFakeExec();
    const good = { server: SERVER, text: rulesText(H1), hash: H1 };
    const bad: [Request, string][] = [
      [post(good, null), 'actor_missing'],
      [post('not json'), 'body_invalid'],
      [post('[1]'), 'body_invalid'],
      [post({ ...good, server: 'iis' }), 'body_invalid'],
      [post({ ...good, text: 7 }), 'body_invalid'],
      [post({ ...good, hash: null }), 'body_invalid'],
      [post({ ...good, text: 'x'.repeat(1024 * 1024 + 1) }), 'body_invalid'],
    ];
    for (const [request, reason] of bad) {
      const error = await caught(Promise.resolve().then(() => handleRulesApply(request, URL_)));
      expect(error.status).toBe(400);
      expect(error.extensions).toEqual({ reason });
    }
    expect(fake.calls).toEqual([]);
    expect(await outcomes()).toEqual([]);
  });
});
