/**
 * ROOT'S HOST-MAP RENDERER (src/rules/host_map_main.ts runHostMap + src/rules/host_map.ts), run
 * as the non-root suite on macOS and Linux.
 *
 * SEAMS (named, spec §9): every directory is a scratch PARAMETER under .test-tmp/ (map dir, locks
 * dir, identities file); uids are MODELLED through an injected lstat (the real fs answers, a
 * per-path override gives a file a foreign uid — no account is created, nothing is chowned); the
 * host web lock is a fake LockIo writing to the same call log as the fake nginx exec, so "the lock
 * is taken and released on every path" and "configtest runs inside it" are observed.
 */
import { afterEach, beforeEach, describe, expect, test } from 'bun:test';
import { existsSync, mkdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { ExecResult } from '../src/provision/exec_contract';
import type { LockIo } from '../src/provision/lock';
import {
  envelopePcre,
  isMapRefusal,
  MAP_GRAMMAR,
  type MapContribution,
  NGINX_MAP_PINS,
  type NginxMapPins,
  parseNginxMap,
} from '../src/rules/directives';
import {
  CONTRIB_SCAN_CAP,
  canonicalRecord,
  hostMapHash,
  type HostMapResult,
  MAX_CONTRIBUTION_BYTES,
  parseBindings,
  parseHostMapResult,
  parseIdentities,
  planHostMap,
  renderHostMap,
  withoutBinding,
} from '../src/rules/host_map';
import { exitCodeOf, type HostMapDeps, hostMapIo, runHostMap } from '../src/rules/host_map_main';
import { scratchPath } from './fixtures/instance';

const BASE = scratchPath('rules_host_map');
const MAP_DIR = join(BASE, 'nginx_map');
const CONTRIB = join(MAP_DIR, 'contrib');
const LOCKS = join(BASE, 'locks');
const IDENTITIES = join(BASE, 'map_renderer', 'identities.json');
const LIVE = join(MAP_DIR, 'dedalo_media_map.nginx.conf');
const PENDING = `${LIVE}.reload-pending`;
const RESULT = join(MAP_DIR, 'result.json');
const BINDINGS = join(MAP_DIR, 'bindings.json');
const UID = { alpha: 1001, beta: 1002, gamma: 1003 } as const;

const H1 = '1'.repeat(64);
const H2 = '2'.repeat(64);
const ENV_A = envelopePcre('media', 'image');
const ENV_B = envelopePcre('media_b', 'image');

/** What the root renderer must write for a single contribution: the engine map, byte for byte. */
const ENGINE_MAP_H1 = [
  '# Dédalo media access control — GENERATED by src/core/media/protection.ts.',
  '# Include this in the http{} context (a map cannot live inside server{}).',
  `# config-hash: ${H1}`,
  '# It sanitizes the auth cookie to hex-only before it is used in a file path,',
  '# and classifies the URI for the MEDIA-03 response headers.',
  'map $cookie_dedalo_media_auth $dedalo_auth_key {',
  '\t"~^(?<h>[a-f0-9]{128})$"  $h;',
  '\tdefault                   "_invalid_";',
  '}',
  '',
  '# MEDIA-03: the ENVELOPE pattern must come FIRST — nginx map regexes are tested in',
  '# order and an envelope is also an `.svg`. Getting this order wrong sends every',
  '# server-generated envelope down the attachment branch and blanks the edit view.',
  'map $uri $dedalo_svg_disposition {',
  '\t"~^/dedalo/media/image/(?:[^/]+/)*svg/(?:[^/]+/)*[^/]+\\.svg$"  "";',
  '\t"~\\.(?:svg|xml|xsl|xslt)$"  "attachment";',
  '\tdefault                    "";',
  '}',
  '',
  'map $uri $dedalo_svg_csp {',
  `\t"~^/dedalo/media/image/(?:[^/]+/)*svg/(?:[^/]+/)*[^/]+\\.svg$"  "${NGINX_MAP_PINS[0]?.envelopeCsp}";`,
  '\t"~\\.(?:svg|xml|xsl|xslt)$"  "default-src \'none\'; sandbox";',
  '\tdefault                    "";',
  '}',
  '',
].join('\n');

let log: string[] = [];
let uids = new Map<string, number>();
let lockScript: { held?: boolean; missing?: boolean } = {};
/** `restart` present: the exec is renderer-shaped (rendererExec's webRestart + sleep) and records 'restart'. */
let execScript: { configtest?: number[]; reload?: number[]; active?: boolean[]; restart?: number[] } = {};

function fakeLock(): LockIo {
  let clock = 0;
  return {
    openLockFile(path, spec) {
      if (lockScript.missing) throw new Error(`ENOENT ${path}`);
      log.push(`open:${spec.uid}:${spec.create ? 'create' : 'nocreate'}`);
      return 3;
    },
    tryFlock(_fd, mode) {
      if (lockScript.held) return false;
      log.push(`lock:${mode}`);
      return true;
    },
    unlock() {
      log.push('unlock');
    },
    readOwner: () => null,
    writeOwner() {},
    holderFromProcLocks: () => [77],
    lstat: () => null,
    mkdir() {},
    now: () => clock,
    sleepSync(ms) {
      clock += ms;
    },
    async sleep(ms) {
      clock += ms;
    },
  };
}

function deps(): HostMapDeps {
  const real = hostMapIo();
  const configtest = [...(execScript.configtest ?? [])];
  const reload = [...(execScript.reload ?? [])];
  const active = [...(execScript.active ?? [])];
  const restart = [...(execScript.restart ?? [])];
  return {
    mapDir: MAP_DIR,
    locksDir: LOCKS,
    identitiesPath: IDENTITIES,
    lockIo: fakeLock(),
    exec: {
      async webConfigtest(): Promise<ExecResult> {
        log.push('configtest');
        return { code: configtest.shift() ?? 0, stdout: '', stderr: '' };
      },
      async webReload(): Promise<ExecResult> {
        log.push('reload');
        return { code: reload.shift() ?? 0, stdout: '', stderr: '' };
      },
      async webActive(): Promise<boolean> {
        log.push('active');
        return active.shift() ?? true;
      },
      ...(execScript.restart === undefined
        ? {}
        : {
            async webRestart(): Promise<ExecResult> {
              log.push('restart');
              return { code: restart.shift() ?? 0, stdout: '', stderr: '' };
            },
          }),
    },
    io: {
      ...real,
      lstat(path: string) {
        const facts = real.lstat(path);
        const uid = uids.get(path);
        return facts === null || uid === undefined ? facts : { ...facts, uid };
      },
    },
    now: () => new Date('2026-10-08T12:00:00.000Z'),
    log: () => {},
  };
}

function contribution(instance: string, envelope = ENV_A, hash = H1, extra: Partial<MapContribution> = {}): MapContribution {
  return { v: 1, grammar: 1, instance, hash, envelope, pinsId: 'pins-1', ...extra };
}

/** Plant `contrib/<name>.json` owned (modelled) by `uid`. */
function plant(name: string, body: unknown, uid: number): string {
  const path = join(CONTRIB, `${name}.json`);
  writeFileSync(path, typeof body === 'string' ? body : JSON.stringify(body));
  uids.set(path, uid);
  return path;
}

function identities(value: Record<string, number> = { alpha: UID.alpha, beta: UID.beta }): void {
  writeFileSync(IDENTITIES, JSON.stringify(value));
}

const live = () => (existsSync(LIVE) ? readFileSync(LIVE, 'utf8') : null);
const lockedRun = ['open:0:nocreate', 'lock:ex'];

beforeEach(() => {
  rmSync(BASE, { recursive: true, force: true });
  mkdirSync(CONTRIB, { recursive: true });
  mkdirSync(join(BASE, 'map_renderer'), { recursive: true });
  log = [];
  uids = new Map();
  lockScript = {};
  execScript = {};
  identities();
});
afterEach(() => rmSync(BASE, { recursive: true, force: true }));

describe('rendering', () => {
  test('a single contribution renders byte-equal to the engine map it came from; result + binding recorded', async () => {
    const pushed = parseNginxMap(ENGINE_MAP_H1);
    if (isMapRefusal(pushed)) throw new Error('fixture refused');
    plant('alpha', contribution('alpha', pushed.envelopes[0], pushed.hash), UID.alpha);
    const result = await runHostMap(deps());
    expect(live()).toBe(ENGINE_MAP_H1);
    expect(result).toMatchObject({ v: 1, seq: 1, outcome: 'applied', host_hash: H1, refused: [], invalid: 0 });
    expect(result.contributions).toEqual([{ instance: 'alpha', hash: H1, grammar: 1, pins_id: 'pins-1', envelope: ENV_A }]);
    expect(parseHostMapResult(readFileSync(RESULT, 'utf8'))).toEqual(result);
    expect(JSON.parse(readFileSync(BINDINGS, 'utf8'))).toEqual({ alpha: ENV_A });
    expect(log).toEqual([...lockedRun, 'configtest', 'reload', 'active', 'unlock']);
    expect(exitCodeOf(result)).toBe(0);
  });

  test('two instances with different media dirs: both envelopes, sorted, once; the hash digests both', async () => {
    plant('beta', contribution('beta', ENV_B, H2), UID.beta);
    plant('alpha', contribution('alpha', ENV_A, H1), UID.alpha);
    const result = await runHostMap(deps());
    const text = live() ?? '';
    const parsed = parseNginxMap(text);
    expect(parsed).toMatchObject({ envelopes: [ENV_A, ENV_B].sort(), hash: hostMapHash([{ hash: H1 }, { hash: H2 }]) });
    expect(text).toContain(`# contributions: 2 ${H1} ${H2}`);
    expect(text.split(ENV_A).length - 1).toBe(2); // once per SVG map
    expect(result.host_hash).toBe(hostMapHash([{ hash: H1 }, { hash: H2 }]));
    expect(result.contributions.map(c => c.instance)).toEqual(['alpha', 'beta']);
  });

  test('two instances with the SAME map: one envelope, the shared hash, no contributions line', async () => {
    plant('alpha', contribution('alpha'), UID.alpha);
    plant('beta', contribution('beta'), UID.beta);
    await runHostMap(deps());
    expect(live()).toBe(ENGINE_MAP_H1);
  });

  test('an identical re-render is unchanged: no configtest, no reload, exit 0', async () => {
    plant('alpha', contribution('alpha'), UID.alpha);
    await runHostMap(deps());
    log = [];
    const result = await runHostMap(deps());
    expect(result).toMatchObject({ seq: 2, outcome: 'unchanged', host_hash: H1 });
    expect(log).toEqual([...lockedRun, 'unlock']);
    expect(exitCodeOf(result)).toBe(0);
  });

  test('an older pin set contributes its envelope, and the newest pin set present supplies the values', () => {
    const newer: NginxMapPins = { ...(NGINX_MAP_PINS[0] as NginxMapPins), id: 'pins-x', grammar: 1, quarantineCsp: "default-src 'none'; sandbox; x" };
    const table = [NGINX_MAP_PINS[0] as NginxMapPins, newer];
    const { text } = renderHostMap(
      [
        { hash: H1, envelope: ENV_A, pinsId: 'pins-1' },
        { hash: H2, envelope: ENV_B, pinsId: 'pins-x' },
      ],
      table,
    );
    expect(text).toContain(ENV_A);
    expect(text).toContain(ENV_B);
    expect(text).toContain('sandbox; x');
    expect(text).not.toContain(`"${NGINX_MAP_PINS[0]?.quarantineCsp}"`);
    expect(() => renderHostMap([])).toThrow(/no contribution/);
    expect(() => renderHostMap([{ hash: H1, envelope: ENV_A, pinsId: 'pins-9' }])).toThrow(/unknown pin set/);
  });
});

describe('refusals', () => {
  test('a newer-grammar contribution refuses the WHOLE render and leaves the live file as it is', async () => {
    plant('alpha', contribution('alpha'), UID.alpha);
    await runHostMap(deps());
    const before = live();
    log = [];
    plant('beta', { grammar: MAP_GRAMMAR + 1, pinsId: 'pins-2', anything: true }, UID.beta);
    plant('alpha', contribution('alpha', ENV_B, H2), UID.alpha); // a change the refused render must NOT apply
    const result = await runHostMap(deps());
    expect(result.outcome).toBe('map_contribution_newer');
    expect(result.refused).toContainEqual({ instance: 'beta', reason: 'map_contribution_newer', grammar: MAP_GRAMMAR + 1, pins_id: 'pins-2' });
    expect(live()).toBe(before);
    expect(result.host_hash).toBe(H1);
    expect(log).toEqual([...lockedRun, 'unlock']); // no configtest, no reload
    expect(exitCodeOf(result)).toBe(1);
  });

  test('a contribution whose lstat uid is not its declared agent is refused, and never read', async () => {
    plant('alpha', contribution('alpha'), UID.alpha);
    plant('beta', '{ this is not even json', UID.alpha); // squatted by alpha's agent
    const result = await runHostMap(deps());
    expect(result.refused).toEqual([{ instance: 'beta', reason: 'map_contribution_foreign' }]);
    expect(result.invalid).toBe(1);
    expect(result.contributions.map(c => c.instance)).toEqual(['alpha']);
  });

  test('a contribution for an undeclared instance is refused (undeclared)', async () => {
    plant('alpha', contribution('alpha'), UID.alpha);
    plant('gamma', contribution('gamma'), UID.gamma);
    const result = await runHostMap(deps());
    expect(result.refused).toEqual([{ instance: 'gamma', reason: 'undeclared' }]);
    expect(result.contributions.map(c => c.instance)).toEqual(['alpha']);
  });

  test('a symlink, an oversized file, a non-.json name and malformed JSON are invalid; a temp file is skipped', async () => {
    plant('alpha', contribution('alpha'), UID.alpha);
    symlinkSync(join(BASE, 'map_renderer', 'identities.json'), join(CONTRIB, 'beta.json'));
    writeFileSync(join(CONTRIB, 'notes.txt'), 'x');
    writeFileSync(join(CONTRIB, '.alpha.json.tmp'), 'half');
    const result = await runHostMap(deps());
    expect(result.refused).toEqual([{ instance: 'beta', reason: 'map_contribution_foreign' }]);
    expect(result.invalid).toBe(2);
    rmSync(join(CONTRIB, 'beta.json'));
    plant('beta', `{"v":1,"pad":"${'x'.repeat(MAX_CONTRIBUTION_BYTES)}"}`, UID.beta);
    expect((await runHostMap(deps())).refused).toEqual([{ instance: 'beta', reason: 'map_refused' }]);
    plant('beta', '{"v":', UID.beta);
    expect((await runHostMap(deps())).refused).toEqual([{ instance: 'beta', reason: 'map_refused' }]);
  });

  test('the cap: entries past the scan cap are counted invalid unread', () => {
    const entries = Array.from({ length: CONTRIB_SCAN_CAP + 5 }, (_, i) => ({
      name: `j${String(i).padStart(4, '0')}.json`,
      facts: { type: 'file' as const, uid: 1, size: 2 },
    }));
    const plan = planHostMap({ entries, identities: {}, bindings: {}, previous: null });
    expect(plan.kind === 'render' && plan.invalid).toBe(CONTRIB_SCAN_CAP + 5);
    expect(plan.kind === 'render' && plan.kept).toEqual([]);
  });

  test('a rebind is refused and the BOUND envelope keeps being served', async () => {
    plant('alpha', contribution('alpha', ENV_A, H1), UID.alpha);
    await runHostMap(deps());
    plant('alpha', contribution('alpha', ENV_B, H2), UID.alpha);
    const result = await runHostMap(deps());
    expect(result.refused).toEqual([{ instance: 'alpha', reason: 'map_envelope_rebind' }]);
    expect(result.outcome).toBe('unchanged');
    expect(result.contributions).toEqual([{ instance: 'alpha', hash: H1, grammar: 1, pins_id: 'pins-1', envelope: ENV_A }]);
    expect(live()).toBe(ENGINE_MAP_H1);
    expect(JSON.parse(readFileSync(BINDINGS, 'utf8'))).toEqual({ alpha: ENV_A });
    // A binding that outlived its result: the bound envelope under the refused contribution's hash.
    rmSync(RESULT);
    rmSync(LIVE);
    const orphan = await runHostMap(deps());
    expect(orphan.contributions).toEqual([{ instance: 'alpha', hash: H2, grammar: 1, pins_id: 'pins-1', envelope: ENV_A }]);
  });

  test("an instance's provision apply clears its binding (withoutBinding); the next contribution binds afresh", async () => {
    plant('alpha', contribution('alpha', ENV_A, H1), UID.alpha);
    await runHostMap(deps());
    const cleared = withoutBinding(readFileSync(BINDINGS, 'utf8'), 'alpha');
    expect(cleared).toBe('{}\n');
    expect(withoutBinding(cleared, 'alpha')).toBeNull();
    writeFileSync(BINDINGS, cleared as string);
    plant('alpha', contribution('alpha', ENV_B, H2), UID.alpha);
    const result = await runHostMap(deps());
    expect(result.refused).toEqual([]);
    expect(result.contributions.map(c => c.envelope)).toEqual([ENV_B]);
  });

  test('a contribution exactly like the binding re-binds nothing; a new instance is bound at first acceptance', async () => {
    plant('alpha', contribution('alpha'), UID.alpha);
    await runHostMap(deps());
    plant('beta', contribution('beta', ENV_B, H2), UID.beta);
    await runHostMap(deps());
    expect(JSON.parse(readFileSync(BINDINGS, 'utf8'))).toEqual({ alpha: ENV_A, beta: ENV_B });
  });
});

describe('the seed', () => {
  test('_seed is used alone, and dropped once a real contribution was rendered', async () => {
    const seed = plant('_seed', contribution('_seed'), 0);
    const first = await runHostMap(deps());
    expect(first.contributions.map(c => c.instance)).toEqual(['_seed']);
    expect(live()).toBe(ENGINE_MAP_H1);
    expect(existsSync(seed)).toBe(true);
    plant('alpha', contribution('alpha'), UID.alpha);
    const second = await runHostMap(deps());
    expect(second.contributions.map(c => c.instance)).toEqual(['alpha']);
    expect(existsSync(seed)).toBe(false);
  });

  test('a seed not owned by root is refused', async () => {
    plant('_seed', contribution('_seed'), UID.alpha);
    const result = await runHostMap(deps());
    expect(result).toMatchObject({ outcome: 'empty', refused: [{ instance: '_seed', reason: 'map_contribution_foreign' }] });
    expect(live()).toBeNull();
  });
});

describe('the transaction under the web lock', () => {
  test('configtest failure restores the previous map and records configtest_failed with the LOADED hash', async () => {
    plant('alpha', contribution('alpha'), UID.alpha);
    await runHostMap(deps());
    plant('beta', contribution('beta', ENV_B, H2), UID.beta);
    execScript = { configtest: [1, 0] };
    log = [];
    const result = await runHostMap(deps());
    expect(result).toMatchObject({ outcome: 'configtest_failed', host_hash: H1 });
    expect(live()).toBe(ENGINE_MAP_H1);
    expect(log).toEqual([...lockedRun, 'configtest', 'configtest', 'unlock']);
    expect(JSON.parse(readFileSync(BINDINGS, 'utf8'))).toEqual({ alpha: ENV_A }); // beta not bound by a refused render
  });

  test('reload failure keeps the new map and the marker; host_hash reads null', async () => {
    plant('alpha', contribution('alpha'), UID.alpha);
    execScript = { reload: [1] };
    const result = await runHostMap(deps());
    expect(result).toMatchObject({ outcome: 'reload_failed', host_hash: null });
    expect(live()).toBe(ENGINE_MAP_H1);
    expect(existsSync(PENDING)).toBe(true);
    execScript = {};
    expect((await runHostMap(deps())).outcome).toBe('applied');
    expect(existsSync(PENDING)).toBe(false);
  });

  test('nginx down after a reload that returned 0 is reload_failed', async () => {
    plant('alpha', contribution('alpha'), UID.alpha);
    execScript = { active: [false] };
    expect(await runHostMap(deps())).toMatchObject({ outcome: 'reload_failed', host_hash: null });
  });

  test('B2: nginx down after a reload that returned 0 → the LOADED map restored, configtest, restart; bindings and seed untouched', async () => {
    plant('alpha', contribution('alpha'), UID.alpha);
    const first = await runHostMap(deps());
    expect(first.outcome).toBe('applied');
    const seed = plant('_seed', contribution('_seed'), 0);
    plant('beta', contribution('beta', ENV_B, H2), UID.beta);
    log = [];
    execScript = { active: [false], restart: [] };
    const result = await runHostMap(deps());
    expect(result).toMatchObject({ outcome: 'reload_failed', host_hash: H1 });
    // What nginx serves again is the map it had loaded; the result names what is loaded.
    expect(live()).toBe(ENGINE_MAP_H1);
    expect(existsSync(PENDING)).toBe(false);
    expect(result.contributions.map(c => c.instance)).toEqual(['alpha']);
    expect(log).toEqual([...lockedRun, 'configtest', 'reload', 'active', 'configtest', 'restart', 'active', 'unlock']);
    // The rendered map never reached nginx: beta is not bound, the seed is not swept.
    expect(JSON.parse(readFileSync(BINDINGS, 'utf8'))).toEqual({ alpha: ENV_A });
    expect(existsSync(seed)).toBe(true);
    expect(exitCodeOf(result)).toBe(1);
  });

  test('B2: a restart that fails leaves the marker and host_hash null (nothing is known to be loaded)', async () => {
    plant('alpha', contribution('alpha'), UID.alpha);
    await runHostMap(deps());
    plant('beta', contribution('beta', ENV_B, H2), UID.beta);
    execScript = { active: [false], restart: [1] };
    expect(await runHostMap(deps())).toMatchObject({ outcome: 'reload_failed', host_hash: null });
    expect(existsSync(PENDING)).toBe(true);
    expect(live()).toBe(ENGINE_MAP_H1);
  });

  test('a held lock is host_busy, a missing lock file lock_missing: nothing rendered, result recorded', async () => {
    plant('alpha', contribution('alpha'), UID.alpha);
    lockScript = { held: true };
    const busy = await runHostMap(deps());
    expect(busy).toMatchObject({ outcome: 'host_busy', seq: 1 });
    expect(log.at(-1)).toBe('unlock');
    expect(log).not.toContain('configtest');
    lockScript = { missing: true };
    expect(await runHostMap(deps())).toMatchObject({ outcome: 'lock_missing', seq: 2 });
    expect(live()).toBeNull();
  });

  test('unreadable identities: nothing rendered, lock released', async () => {
    writeFileSync(IDENTITIES, '{"Alpha": 1}');
    plant('alpha', contribution('alpha'), UID.alpha);
    const result = await runHostMap(deps());
    expect(result.outcome).toBe('identities_invalid');
    expect(log).toEqual([...lockedRun, 'unlock']);
    expect(live()).toBeNull();
  });

  test('no contribution at all is empty: the live file is left alone', async () => {
    expect(await runHostMap(deps())).toMatchObject({ outcome: 'empty', contributions: [] });
    expect(log).toEqual([...lockedRun, 'unlock']);
  });
});

describe('records', () => {
  test('parsers refuse what root would not have written', () => {
    expect(parseIdentities(null)).toBeNull();
    expect(parseIdentities('[1]')).toBeNull();
    expect(parseIdentities('{"alpha": -1}')).toBeNull();
    expect(parseIdentities('nope')).toBeNull();
    expect(parseIdentities('{"alpha": 5}')).toEqual({ alpha: 5 });
    expect(parseBindings('nope')).toEqual({});
    expect(parseBindings('[1]')).toEqual({});
    expect(parseBindings('{"alpha": "x", "Bad": "y", "beta": 3}')).toEqual({ alpha: 'x' });
    const result: HostMapResult = { v: 1, seq: 1, at: 'now', outcome: 'empty', host_hash: null, contributions: [], refused: [], invalid: 0 };
    expect(parseHostMapResult(JSON.stringify(result))).toEqual(result);
    for (const broken of [{ ...result, v: 2 }, { ...result, outcome: 'x' }, { ...result, host_hash: 'x' }, { ...result, contributions: [{}] }, { ...result, refused: [1] }, { ...result, invalid: 'x' }]) {
      expect(parseHostMapResult(JSON.stringify(broken))).toBeNull();
    }
    expect(parseHostMapResult('{')).toBeNull();
    expect(canonicalRecord({ b: 1, a: 2 })).toBe('{\n  "a": 2,\n  "b": 1\n}\n');
  });
});
