/**
 * GET /v1/status — AgentStatus assembled from the REAL release store (Task 6) and the REAL
 * rules module (Task 5) over the scratch state root; no stubs, so a layout or stamp change
 * in those modules is seen here.
 */
import { afterEach, beforeEach, describe, expect, test } from 'bun:test';
import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import packageJson from '../package.json';
import { config } from '../src/config';
import { probeMedia } from '../src/media/probe';
import { apiLayout, promote } from '../src/releases/store';
import { AGENT_VERSION, STATUS_APIS, buildStatus, stateRootFreeBytes, type AgentStatus } from '../src/routes/status';
import { routeRequest } from '../src/router';
import { instanceFingerprint } from '../src/security/pairing';
import { resetInstance, roots } from './fixtures/instance';

const BASE = '/publication/host_agent';
const AUTH = { authorization: `Bearer ${config.SERVICE_TOKEN}` };

beforeEach(resetInstance);
afterEach(resetInstance);

async function getStatus(): Promise<AgentStatus> {
  const res = await routeRequest(new Request(`http://localhost${BASE}/v1/status`, { headers: AUTH }));
  expect(res.status).toBe(200);
  expect(res.headers.get('cache-control')).toBe('no-store');
  return (await res.json()) as AgentStatus;
}

async function plantRelease(api: 'v1' | 'v2', releaseId: string): Promise<void> {
  await mkdir(join(apiLayout(api).releases, releaseId), { recursive: true });
}

describe('GET /v1/status', () => {
  test('is behind the bearer', async () => {
    const res = await routeRequest(new Request(`http://localhost${BASE}/v1/status`));
    expect(res.status).toBe(401);
  });

  test('a fresh instance: identity, no releases, no rules, measured media and disk', async () => {
    const body = await getStatus();
    expect(body.agent_version).toBe(packageJson.version);
    expect(AGENT_VERSION).toBe(packageJson.version);
    expect(body.bun_version).toBe(Bun.version);
    expect(body.platform).toBe(`${process.platform}-${process.arch}`);
    expect(body.instance_fingerprint).toBe(instanceFingerprint(config.INSTANCE, config.SERVICE_TOKEN));
    expect(Object.keys(body.apis).sort()).toEqual([...STATUS_APIS].sort());
    expect(body.apis).toEqual({
      v1: { current: null, previous: null },
      v2: { current: null, previous: null },
    });
    expect(body.rules).toEqual({ server: config.WEB_SERVER, hash: null });
    expect(body.media).toEqual(await probeMedia());
    expect(Number.isSafeInteger(body.disk.state_root_free_bytes)).toBe(true);
    expect(body.disk.state_root_free_bytes).toBeGreaterThan(0);
  });

  test('never publishes the instance name or the token', async () => {
    const body = await getStatus();
    expect(Object.keys(body)).not.toContain('instance');
    expect(JSON.stringify(body)).not.toContain(config.SERVICE_TOKEN);
  });

  test('current and previous come from the release store', async () => {
    await plantRelease('v2', '7.0.1_aaaaaaa');
    await plantRelease('v2', '7.0.2_bbbbbbb');
    await promote('v2', '7.0.1_aaaaaaa');
    await promote('v2', '7.0.2_bbbbbbb');

    const body = await getStatus();
    expect(body.apis.v2).toEqual({ current: '7.0.2_bbbbbbb', previous: '7.0.1_aaaaaaa' });
    expect(body.apis.v1).toEqual({ current: null, previous: null });
  });

  test('rules.hash is the config-hash stamp of the live include', async () => {
    const hash = createHash('sha256').update('status-test').digest('hex');
    const include = join(config.STATE_ROOT, 'rules', `dedalo_media_publication.${config.WEB_SERVER}.conf`);
    await mkdir(join(config.STATE_ROOT, 'rules'), { recursive: true });
    await writeFile(
      include,
      [
        '# Dédalo media access control, PUBLICATION-HOST profile. GENERATED by',
        '# src/core/media/publication_host_rules.ts. Do not edit: re-render instead.',
        `# config-hash: ${hash}`,
        '',
      ].join('\n'),
    );

    const body = await getStatus();
    expect(body.rules).toEqual({ server: config.WEB_SERVER, hash });
  });
});

describe('status helpers', () => {
  test('buildStatus is what the route serialises', async () => {
    expect(await buildStatus()).toEqual(await getStatus());
  });

  test('stateRootFreeBytes measures a real root and refuses a missing one', async () => {
    expect(await stateRootFreeBytes(roots.stateRoot)).toBeGreaterThan(0);
    await expect(stateRootFreeBytes(join(roots.stateRoot, 'absent', 'root'))).rejects.toMatchObject({
      code: 'ENOENT',
    });
  });
});
