<?php

	# VISUALIZADOR HTML	

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in', $modo, $lang);
	
	print "<div class=\"wrap_component css_wrap_text_area css_wrap_text_area_{$modo} wrap_component_{$tipo}\" id=\"{$id_wrapper}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-modo=\"{$modo}\" ";
	#print "data-dato=\"{$dato_raw}\" ";
	print "data-context_name=\"{$context_name}\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-component_info='{}' ";
	#print "data-related_tipo='{$ar_related_component_tipo_json}' ";
	#print "data-related_name='{$ar_related_component_name_json}' ";
	print ">";

	
		# ETIQUETA (LABEL)
		#$html_label = component_common_draw::draw_label($this);
		
		# CONTENIDO (INPUT)
		$html_content = (string)'';
		switch(true) {
				
			case $permissions===0:
			
					$html_content .= '';
					break;
							
			case ($permissions>=1):

					$html_content .= "<span class=\"css_span_dato\">$fragment_text</span>";				
			
					#if(SHOW_DEBUG) {
					#	$html_content .= "<span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
					#}

					
					# INIT : Init text editor	
					$html_content .= '<script>';
					#$html_content .= "var init=new component_text_area.init({uid:'$identificador_unico',modo:'$modo',propiedades:'$propiedades_json'});";
					//$html_content .= "a.init({uid:'$identificador_unico',modo:'$modo',propiedades:'$propiedades_json'});";
					#$html_content .= "console.log(init.inited);";
					#$html_content .= "Object.create(component_text_area).init({uid:'$identificador_unico',modo:'$modo',propiedades:'$propiedades_json'});";
					#$html_content .= "component_text_area.init({uid:'$identificador_unico',modo:'$modo',propiedades:'$propiedades_json'});";
					$init_options = new stdClass();
						$init_options->component_name 	= $component_name;
						$init_options->id_wrapper 		= $id_wrapper;
						$init_options->uid 				= $identificador_unico;
						$init_options->modo 			= $modo;
						$init_options->permissions 		= $permissions;
						$init_options->propiedades 		= $propiedades;

					$html_content .= 'component_common.init('.json_encode($init_options).');';
					#$html_content .= "alert('aaaaa');";
					$html_content .= '</script>';
					
					
		}
		
		tools::prepare_content($html_content);

		# PRINT HTML
		print $html_content;
	
	
	echo "</div>"; //wrap
?>