<?php

	# VISUALIZADOR HTML
	

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in', $modo, $lang);
	
	print "\n<div class=\"wrap_component css_wrap_text_area wrap_component_{$tipo} $wrap_css_selectors\" id=\"{$id_wrapper}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-modo=\"{$modo}\" ";
	#print "data-dato=\"{$dato_raw}\" ";
	print "data-context_name=\"{$context_name}\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-component_info='{$component_info}' ";
	print "data-related_tipo='{$ar_related_component_tipo_json}' ";
	print "data-related_name='{$ar_related_component_name_json}' ";
	print "role=\"wrap_component_text_area\" ";
	print ">";

	# LABEL
	$html_label = component_common_draw::draw_label($this);

	
	# LANG FAST SWITCHER
	/*
	if ($this->traducible==='si') {
		$html_label .= component_common_draw::draw_select_fast_lang_switch($id_wrapper, $lang, 'select_fast_lang_switch');
	}*/

	# TOOL LANG MULTI
	#$html_label .= tool_lang_multi::build_button($id_wrapper, $section_tipo, $section_id, $component_tipo);


	# CONTENIDO (INPUT)
	$html_content = '';
	switch($permissions) {

		case 0 :
				$html_content .= "";
				break;

		case 1 :
				#$html_content .= "\n<div class=\"text_area_content text_area_content_shadow\" >";
				$html_content .= "<span class=\"css_span_dato text_area_read_only\">$dato</span>";
				#$html_content .= "\n</div>"; #end text_area_content

				/*
				##
				# WRAP CURRENT SELECTED FRAGMENT (RELATION / ADD PORTAL BUTTON)
					#
					$html_content .= "\n <div id=\"relations_ajax_div_{$tipo}\" class=\"wrap_fragment\"
					data-tipo=\"{$tipo}\"
					data-section_tipo=\"{$section_tipo}\"
					data-parent=\"{$parent}\"
					data-modo=\"selected_fragment\"
					data-lang=\"{$lang}\"
					data-context_name=\"$context_name\"
					data-caller_id=\"$caller_id\"
					data-component_name=\"$component_name\"
					>
					<div class=\"content_data\"><!-- AJAX CONTENT HERE --></div>
					</div>";
					*/

				break;

		case 2 :
		case 3 :

				#
				# COMPONENT STATE
				if (isset($component_state_html)) {
					$html_content .= $component_state_html;
				}

				#
				# DATO REFERENCE DEFAULT LANG
				/* DESACTIVO DE MOMENTO. VOLVER A ACTIVAR CUANDO LA B4 ESTÉ ESTABLE
					#if ($modo!='tool_lang' && !empty($default_component)) {
					if ($modo=='edit' && !empty($default_component->dato)) {

						#$html_content .= "\n <div class=\"dato_refecence_default_lang\">$dato_reference_lang</div>";
						# Fijamos el lenguaje actual como el de destino para el tool_lang
						$html_content .= "<script>set_localStorage('last_target_lang','$lang')</script>";
						$tool_lang = new tool_lang($default_component,'button');
							#dump($tool_lang,'$tool_lang');
						$html_content .= $tool_lang->get_html();
					}
					*/

				#
				# BROKEN INDEX TAGS WARNING
				if (!empty($component_warning)) {
					$html_content .= "<div class=\"text_area_warning\"><span class=\"warning\">".$component_warning."</span></div>";
				}

				
				$html_content .= "<span class=\"lang_info_debug\">$lang</span>";



				#
				# INPUT TEXTAREA
					$html_content .= "<textarea class=\"css_text_area $text_area_tm\" id=\"{$identificador_unico}\" style=\"visibility:hidden\" ";
					$html_content .= "name=\"{$input_name}\" ";
					$html_content .= "data-parent=\"{$parent}\" ";
					$html_content .= "data-tipo=\"{$tipo}\" ";
					$html_content .= "data-lang=\"{$lang}\" ";
					$html_content .= "data-modo=\"{$modo}\" ";
					$html_content .= "data-section_tipo=\"{$section_tipo}\" ";
					$html_content .= "data-canvas_id=\"$canvas_id\" ";
					$html_content .= "data-context_name=\"$context_name\" ";
					$html_content .= "title=\"$html_title\" ";
					$html_content .= "tabindex=\"1\">$dato</textarea>";
				
				/*
				$html_content .= "\n <div class=\"css_text_area $text_area_tm\" id=\"{$identificador_unico}\" style=\"visibility:hidden\"
				name=\"{$input_name}\"
				data-parent=\"{$parent}\"
				data-tipo=\"{$tipo}\"
				data-lang=\"{$lang}\"
				data-modo=\"{$modo}\"
				data-section_tipo=\"{$section_tipo}\"				
				data-canvas_id=\"$canvas_id\"
				data-context_name=\"$context_name\"
				title=\"$html_title\"
				tabindex=\"1\">$dato</div>";
				*/

				#
				# BUTTON RELATE . Relate current selected text with caller_id section
				# des: data-tipo=\"$caller_tipo\" data-caller_tipo=\"$caller_tipo\"	 data-caller_id=\"$caller_id\"
				/*
					$html_content .= "<div class=\"css_button_generic btn_relate_fragment\"	
					data-portal_tipo=\"$portal_tipo\"
					data-portal_parent=\"$portal_parent\"
					data-portal_section_tipo=\"$portal_section_tipo\"
					data-rel_locator=\"$rel_locator\"
					data-tagName=\"$tagName\"	
					onclick=\"tool_portal.add_resource(this);\">
					";
						$html_content .= "Relate selected fragment";
						if(SHOW_DEBUG===true) {
							$html_content .= " <span class=\"debug_info\">[parent:$parent - section_tipo:$section_tipo]</span>";	# caller_id:$caller_id -
						}
					$html_content .= "</div>";
					*/
					#$html_content .= "<div id=\"relations_ajax_div_{$tipo}\" data-tipo=\"$tipo\" data-parent=\"$parent\" data-section-tipo=\"$section-tipo\">XXX</div>";


				#
				# BUTTON CREATE FRAGMENT
					$html_content .= "\n<div class=\"css_button_generic btn_create_fragment\" style=\"display:none\" ";
					$html_content .= "data-identificador_unico=\"$identificador_unico\" ";
					$html_content .= "data-parent=\"{$parent}\" ";
					$html_content .= "data-section_tipo=\"{$section_tipo}\" ";
					$html_content .= "data-tipo=\"{$tipo}\" ";
					$html_content .= "data-lang=\"{$lang}\" ";
					$html_content .= "onmousedown=\"tool_indexation.create_fragment(this,event);\" ";
					$html_content .= ">";
					$html_content .= label::get_label('crear_nuevo_fragmento');
					if(SHOW_DEBUG===true) {
						#$html_content .= " <span class=\"debug_info\">[last_tag_index_id:$last_tag_index_id - caller_id:$caller_id]</span>";
					}
					$html_content .= "</div>";
	
	
				#
				# BUTTON PORTAL ADD RESOURCE
					if ( isset($_GET['portal_tipo']) && strpos($context->context_name, 'portal')!==false ) {

						$portal_tipo 		 = safe_tipo($_GET['portal_tipo']);
						$portal_parent 		 = safe_xss($_GET['portal_parent']);
						$portal_section_tipo = safe_tipo($_GET['portal_section_tipo']);

						$button_action 	= 'tool_portal.add_resource(this)';#"tool_portal.add_fragment_resource(this)";
						
						$html_content .= "<div class=\"css_button_generic btn_relate_fragment\" id=\"btn_relate_fragment_{$tipo}\" style=\"display:none\" ";
						$html_content .= "onclick=\"{$button_action}\" ";
						$html_content .= "data-tipo=\"$tipo\" ";
						$html_content .= "data-portal_tipo=\"$portal_tipo\" ";
						$html_content .= "data-portal_parent=\"$portal_parent\" ";
						$html_content .= "data-portal_section_tipo=\"$portal_section_tipo\" ";
						$html_content .= "data-rel_locator=\"\"	";
						$html_content .= ">";
						$html_content .= label::get_label('relacionar_fragmento_seleccionado') . " (".label::get_label('etiqueta')."<span></span>)";
						if(SHOW_DEBUG===true) {
							#$rel_locator_js_pretty = json_encode($rel_locator);
							#$html_content .= " <span class=\"debug_info\">[parent:$parent - rel_locator:$rel_locator_js_pretty]</span>";	# caller_id:$caller_id -
						}
						$html_content .= "</div>";
					}



				#
				# JS Init component	
				$html_content .= '<script>';
				$init_options = new stdClass();
					$init_options->component_name 	= $component_name;
					$init_options->id_wrapper 		= $id_wrapper;
					$init_options->uid 				= $identificador_unico;
					$init_options->modo 			= $modo;
					$init_options->permissions 		= $permissions;
					$init_options->propiedades 		= $propiedades;
				$html_content .= 'component_common.init('.json_encode($init_options).');';
				$html_content .= '</script>';
				

				if(SHOW_DEBUG===true) {
					#$html_content .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";
				}
				break;

	}//end switch($permissions) {	
	

	# Prepare content to show in page
	tools::prepare_content($html_content);
	

	# PRINT HTML
	print $html_label;
	print $html_content;


	print "</div>"; //wrap

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out', $modo, $lang);


?>