<?php

	# VISUALIZADOR HTML	
	/*
	# BUTTON TOOL
	#$html_tool    = "\n<!-- TOOL LANG [tipo:$tipo parent:$parent] -->";
	$html_tool   .= "<div class=\"tool_inspector_div\">";

	$btn_title	  = label::get_label('abrir').' '.label::get_label('herramienta');
	$html_tool   .= "\n<div class=\"icon_bs tool_lang_icon link\"
						data-tipo=\"{$tipo}\" data-parent=\"{$parent}\" data-lang=\"{$lang}\" data-tab_id=\"img_lang_{$tipo}_{$parent}\" 
						title=\"$btn_title\"
						onclick=\"tool_common.open_tool_lang(this)\"
						></div>";


	$html_tool   .= label::get_label('tool_lang');	#" Lang";

	$html_tool   .= "</div>";#/tool_inspector_div
	
	# PRINT HTML
	print $html_tool;
	*/

	$html='';

	$html .= "<div class=\"tool_subtitles_wrap\">";		
		
		
		$html .= "<div id=\"button_build_subtitles\" class=\"css_button_generic\" onclick=\"tool_subtitles.build_subtitles_text(this)\"
		data-component_tipo=\"$component_tipo\"
		data-section_tipo=\"$section_tipo\"
		data-section_id=\"$section_id\"
		>";
		$html .= label::get_label('crear_subtitulos');
		$html .= "</div>";

		$html .= " <input type=\"text\" id=\"tool_subtitles_line_lenght\" value=\"$line_lenght\" /> " . label::get_label('caracteres_por_linea') ;

		$html .= "<div id=\"subtitles_response\"> </div>";

	$html .= "</div>";

	echo $html;
?>