/**
 * The publication path's handle on THE geo-coordinate law. FACADE ONLY — zero
 * logic lives here, so there is one law, not two.
 *
 * The law (parse + range + why the range is an input-door rule and not a
 * publication one) is src/core/concepts/geo_coordinate.ts. Import it there for
 * anything new; this alias exists because the three publication paths and
 * scripts/repair_geolocation_studio_default.ts already reach for this path.
 */

export {
	type CoordinateAxis,
	hasCoordinate,
	isCoordinateInRange,
	isStudioDefault,
	parseCoordinate,
	toCoordinate,
} from '../../core/concepts/geo_coordinate.ts';

// ---------------------------------------------------------------------------
// v6 COORDINATE WIDENING — a faithful port of PHP 8.5 number_format($v,16).
//
// component_geolocation::get_diffusion_value_as_geojson (:464-470) does NOT
// publish the stored coordinate: it runs number_format((float)$value, 16, '.', '')
// and json_decode()s that text back into a float. For 1,643 of this install's
// 133,872 stored coordinates the round trip lands one ULP away, so v6 publishes
// -0.8792865200000001 where the stored value (and v7) read -0.87928652 — the
// geojson columns differed on coordinate TEXT alone.
//
// This is a port of php-src PHP-8.5 ext/standard/math.c (_php_math_round,
// rewritten in 8.4), operation-for-operation in IEEE-754 doubles, NOT a
// reverse-engineered approximation. The load-bearing subtlety is the HALF_UP
// tie test: the threshold is `(tmp + 0.5) / 1e16` — ONE rounded double division
// compared in the ORIGINAL domain — not the scaled fraction. That is why values
// whose exact 17th decimal says "round down" still round up, and why every
// naive toFixed/multiply-round-divide emulation misses exactly these rows.
//
// Verified: 0 mismatches over all 133,872 stored coordinates against a
// ground-truth table generated by the install's own PHP 8.5.4.
// ---------------------------------------------------------------------------
const EXPONENT = 1e16; // php_intpow10(16), exact table constant

function copysign(magnitude: number, sign: number): number {
	return sign < 0 || Object.is(sign, -0) ? -Math.abs(magnitude) : Math.abs(magnitude);
}

/** _php_math_round(value, 16, PHP_ROUND_HALF_UP) — php-src PHP-8.5 math.c */
function phpMathRound16HalfUp(value: number): number {
	if (!Number.isFinite(value) || value === 0) {
		return value;
	}

	let tmpValue: number;
	let tmpValue2: number;

	if (value >= 0) {
		tmpValue = Math.floor(value * EXPONENT);
		tmpValue2 = tmpValue + 1;
	} else {
		tmpValue = Math.ceil(value * EXPONENT);
		tmpValue2 = tmpValue - 1;
	}

	// Correction for floor/ceil landing one integer short because
	// value * exponent was computed with a downward FP error.
	if (tmpValue2 / EXPONENT === value) {
		tmpValue = tmpValue2;
	}

	// Beyond our precision — rounding is pointless. (Every |value| >= 1
	// takes this path with places = 16.)
	if (Math.abs(tmpValue) >= 1e16) {
		return value;
	}

	// php_round_helper, PHP_ROUND_HALF_UP branch.
	const valueAbs = Math.abs(value);
	const edgeCase = Math.abs((tmpValue + copysign(0.5, tmpValue)) / EXPONENT);
	if (valueAbs >= edgeCase) {
		tmpValue = tmpValue + copysign(1.0, tmpValue);
	}

	// abs(places) < 23 → simple division.
	return tmpValue / EXPONENT;
}

/**
 * number_format($value, 16, '.', '') parsed back to a double by
 * json_decode. Returns the exact double PHP would hold; JSON.stringify()
 * of it reproduces json_encode()'s bytes for these values.
 */
export function phpNumberFormat16RoundTrip(value: number): number {
	if (!Number.isFinite(value)) {
		// number_format would print "NAN"/"INF"; out of scope for coordinates.
		return value;
	}

	// _php_math_number_format_ex: is_negative split, work on fabs(d).
	const isNegative = value < 0;
	let d = Math.abs(value);

	d = phpMathRound16HalfUp(d);

	// strpprintf(0, "%.16F", d): correctly rounded fixed-point, 16 decimals.
	const fixed = d.toFixed(16);

	// Minus sign is dropped when the rounded value is 0.
	const literal = isNegative && d !== 0 ? `-${fixed}` : fixed;

	// json_decode: zend_strtod, correctly rounded nearest double == Number().
	return Number(literal);
}
