<?php

	# VIEW HTML	

	$html  = "<!-- TOOL_LANG_MULTI [component_tipo:$component_tipo parent:$parent] -->";
	# INSPECTOR LOG TOOL_LANG ()
	$html .= "<div id=\"inspector_log\" class=\"tool_lang_multi_inspector_log\"></div>";
	$dedalo_application_langs = unserialize(DEDALO_APPLICATION_LANGS);

	$html .= "<div class=\"container_tool_lang_multi_page\">";
	foreach($dedalo_application_langs as $current_lang => $lang_name) {

		# Selected
		$selected = ($current_lang === $lang) ? ' selected' : '';

		$html .= "<div class=\"item_component{$selected}\">";
			$html .= "<h4>$lang_name</h4>";
						
			$current_component  = component_common::get_instance($modelo_name,
																 $component_tipo,
																 $parent,
																 'edit',
																 $current_lang,
																 $section_tipo);

			$html .= $current_component->get_html();
		$html .= "</div>";//end item_component
	}	
	$html .= "</div><!-- /container_tool_lang_multi_page -->"; //container_tool_lang_multi_page
	
	

	# Init tool
	#$html .= "<script>$tool_name.init({textarea_lang:'$original_lang'})</script>";

	print $html;
