<?php
/*
	# VISUALIZADOR HTML	
	
	
	echo "\n<!-- SELECT [tipo:$tipo id_matrix:$id] $label -->";
	echo "\n<div class=\"css_wrap_select\" id=\"wrap_{$identificador_unico}\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= ''; 		
					break;
						
		case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato\">$dato</span>";
					break;	
						
		case ($permissions>=2)	:
		
					$html_contenido .= "\n <select class=\"css_select\" 
					id=\"{$identificador_unico}\" name=\"{$tipo}_{$id}_tm\" 
					data-tipo=\"{$tipo}\" data-id_matrix=\"{$id}\" data-lang=\"{$lang}\" 
					title=\"$html_title\" disabled > ";
					foreach ($ar_list_of_values->result as $value => $rotulo) {
						
						if( $dato == $value) {
							$checked = 'selected';
						}else {
							$checked = "";
						}
						$html_contenido .= "\n <option value=\"{$value}\" {$checked}> {$rotulo}</option>";							
					}
					
					$html_contenido .= "\n </select>";
		
					if($permissions==3){
						$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$id}\" >{$debugger}</span>";	
					}
					break;	
											
	}
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	echo "\n</div>\n\n"; //wrap
	*/
?>