<?php

	# VISUALIZADOR HTML	

	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato\"> No access here (select)! </span>";		
					break;
											
		case ($permissions>=1)	:
										
					$html_contenido .= $valor;

					if($permissions==3){
						$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
					}
					break;		
											
	}
	
	# PRINT HTML
	//print $html_label;
	print $html_contenido;
	
?>