<?php

	# VISUALIZADOR HTML

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in');

	print "<div class=\"wrap_component css_wrap_select wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-parent=\"{$parent}\"
	data-section_tipo=\"{$section_tipo}\"
	data-referenced_section_tipo=\"{$referenced_tipo}\"
	data-modo=\"{$modo}\"
	data-dato='{$dato_string}'
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";

	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {

		case 0 :
				$html_contenido .= "";
				break;

		case 1 :
				$html_contenido .= $this->valor;
				break;

		case 2 :
		case 3 :
				#
				# CONTEXT
				# Set as disabled on time machine context 
				$disabled = (isset($context->context_name) && $context->context_name=='tool_time_machine') ? 'disabled="disabled"' : '';

				$html_contenido .= " <select class=\"css_select\"
				onchange=\"component_select.Save(this)\"
				onfocus=\"component_common.select_wrap(document.getElementById('$id_wrapper'));\"
				name=\"{$input_name}\"
				data-tipo=\"{$tipo}\"
				data-lang=\"{$lang}\"
				data-section_tipo=\"{$section_tipo}\"
				data-parent=\"{$parent}\"
				title=\"$html_title\"
				$disabled
				tabindex=\"1\"
				>";

				$selected = empty($dato) ? 'selected' : '';
					
					# Empty option
					$html_contenido .= "<option value=\"\" {$selected}> </option>";

					# Available options
					foreach ($ar_list_of_values->result as $value => $label) {						

						$value   = (string)$value;
						$locator = (object)json_handler::decode($value);	# Locator is json encoded object
						#dump($locator," locator"); dump($dato," dato");

						#$selected = in_array($locator, $dato) ? 'selected' : '';
						$founded  = locator::in_array_locator( $locator, $ar_locator=$dato, $ar_properties=array('section_tipo','section_id') );
						$selected = $founded ? 'selected' : '';

						$html_contenido .= "<option value='$value' {$selected}>";
						$html_contenido .= $label;
						$html_contenido .= "</option>";
					}

				$html_contenido .= " </select>";

				# Button open section referenced
				#$html_contenido .= "<input type=\"button\" value=\"Source\" class=\"css_button_generic\" onclick=\"component_select.open_section(this)\" />";
				$html_contenido .= "<a href=\"javascript:;\" class=\"icon_bs link edit_select edit_hidden\" onclick=\"component_select.open_section(this)\"></a>";


				if(SHOW_DEBUG===true) {
					$html_contenido .= "<div class=\"debug_info notes\">".json_encode( reset($dato) )."</div>";				
					#$html_contenido .= " <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";
				}
				break;
	}

	# Prepare content to show in page
	tools::prepare_content($html_contenido);


	# PRINT HTML
	print $html_label;
	print $html_contenido;

	if(SHOW_DEBUG) {
		#echo $ar_list_of_values->debug;
	}

	print "</div>"; //wrap


	// First test on load element
	if ($mandatory===true) {
		echo "<script>component_select.mandatory('{$id_wrapper}')</script>";
	}


	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out');


?>