<?php

	# VISUALIZADOR HTML	
	
	
	
	
	#print "<!-- COMPONENT_PUBLICATION [tipo:$tipo section_id_matrix:$parent] $label -->";
	print "<div class=\"wrap_component css_wrap_component_publication\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch(true) {
			
		case $permissions===0	:	
					$html_content .= "";
					break;						
		
		case ($permissions>=1)	:
					
					# COMPARISON OPERATORS
					$html_content .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);
					
					# INPUT
					$html_content .= "<span id=\"search_component_$tipo\">";
					$i=1;foreach ($ar_list_of_values->result as $value => $rotulo) {
						
						$id = "search_component_input_".$i;

						$search_input_id = $search_input_name .'_'.$i;

						$html_content .= "<input class=\"css_component_publication\" type=\"radio\" name=\"{$search_input_name}\" id=\"$search_input_id\" ";
						$html_content .= "data-tipo=\"{$tipo}\" ";
						$html_content .= "value='$value' ";
						$html_content .= "title=\"$html_title\"	";
						$html_content .= "/>";
						$html_content .= "<label for=\"$search_input_id\" class=\"css_component_publication_rotulo\">$rotulo</label>";

					$i++;}
					$html_content .= "</span>";

					# LOGICAL OPERATORS
					$html_content .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);				
					break;		
	}	
	
	
	# PRINT HTML
	print $html_label;
	print $html_content;
	
	
	print "</div>"; //wrap
?>