<?php

	# VISUALIZADOR HTML

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in');

	print "<div class=\"wrap_component css_wrap_component_publication wrap_component_{$modo} wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-lang=\"{$lang}\"
	data-modo=\"{$modo}\"
	data-dato='{$dato_json}'
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";


	# LABEL
	$html_label = component_common_draw::draw_label($this);


	# CONTENT 
	$html_content = '';
	switch($permissions) {

		case 0	:
				$html_content .= "";
				break;

		case 1	: 	
				$html_content .= "$valor";
				break;

		case 2 :
		case 3 :
				# Value yes
				$value_yes = '[{"section_id":"1","section_tipo":"dd64"}]';
				# Value no
				$value_no  = '[{"section_id":"2","section_tipo":"dd64"}]';
				# Checked add
				$checked   = $dato_json===$value_yes ? 'checked="checked"' : '';

				# Switcher				
				$html_content .= "<div class=\"switcher_publication text_unselectable\">";

				$html_content .= "<input type=\"checkbox\" class=\"ios-toggle\" $checked onchange=\"component_publication.Save(this);\"
				name=\"$input_name\"
				id=\"{$input_name}\"
				data-tipo=\"{$tipo}\"
				data-lang=\"{$lang}\"
				data-section_tipo=\"{$section_tipo}\"
				data-parent=\"{$parent}\"
				/>";
  				$html_content .= "<label for=\"$input_name\" class=\"checkbox-label\" data-off=\"off\" data-on=\"on\"></label>";

  				$html_content .= "</div>";//end switcher_publication

				# JS
				$html_content .= "<script>";
				$html_content .= "component_publication.value_yes = '$value_yes';";
				$html_content .= "component_publication.value_no  = '$value_no';";
				$html_content .= "</script>";

				//$html_content .= "<script>component_publication.check_publication('{$id_wrapper}')</script>";

				if(SHOW_DEBUG) {
					$html_content .= " <span class=\"debug_info notas\">$dato_json</span>";				
					#$html_content .= " <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";
				}
				break;
	}

	#if(isset($js_code)) $html_content .= $js_code;

	# Prepare content to show in page
	tools::prepare_content($html_content);


	# PRINT HTML
	print $html_label;
	print $html_content;


	print "</div>"; //wrap

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out');

?>