<?php

	# VISUALIZADOR HTML

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in', $modo, $lang);

	print "<div class=\"wrap_component css_wrap_component_publication css_wrap_component_publication_{$modo} wrap_component_{$modo} wrap_component_{$tipo}\" id=\"{$id_wrapper}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato='{$dato_json}' ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-component_info='{$component_info}' ";
	print "data-value_yes='{$value_yes}' ";
	print "data-value_no='{$value_no}' ";
	print ">";


	# LABEL
	$html_label = component_common_draw::draw_label($this);


	# CONTENT 
	$html_content = '';
	switch($permissions) {

		case 0	:
				$html_content .= "";
				break;

		case 1	:
				$valor = $this->get_valor();
				$html_content .= $valor;
				break;

		case 2 :
		case 3 :
				
				# Checked add
				if(empty($dato)) {
					$compare_locators = false;
				}else{
					$component_locator  	= reset($dato);
					$value_yes_ar_locator 	= json_decode($value_yes);
					$value_yes_locator 		= reset($value_yes_ar_locator);
					$compare_locators 		= locator::compare_locators( $component_locator, $value_yes_locator, $ar_properties=['section_id','section_tipo']);
				}
				$checked = ($compare_locators===true) ? 'checked="checked"' : '';

				# Switcher				
				$html_content .= "<div class=\"switcher_publication text_unselectable\">";

				$html_content .= "<input type=\"checkbox\" class=\"ios-toggle\" $checked onchange=\"component_publication.Save(this);\" ";
				$html_content .= "name=\"$input_name\" ";
				$html_content .= "id=\"{$input_name}\" ";
				$html_content .= "data-tipo=\"{$tipo}\" ";
				$html_content .= "data-lang=\"{$lang}\" ";
				$html_content .= "data-section_tipo=\"{$section_tipo}\" ";
				$html_content .= "data-parent=\"{$parent}\" ";
				$html_content .= "/>";
				
  				$html_content .= "<label for=\"$input_name\" class=\"checkbox-label\" data-off=\"off\" data-on=\"on\"></label>";

  				$html_content .= "</div>";//end switcher_publication

				#
				# JS Init component
				$html_content .= '<script>';
				# Init component
				$init_options = new stdClass();
					$init_options->component_name 	= $component_name;
					$init_options->id_wrapper 		= $id_wrapper;
					$init_options->uid 				= $identificador_unico;
				$html_content .= 'component_common.init('.json_encode($init_options).');';
				$html_content .= '</script>';

				//$html_content .= "<script>component_publication.check_publication('{$id_wrapper}')</script>";

				if(SHOW_DEBUG) {
					$html_content .= "<span class=\"debug_info notas\">$dato_json</span>";
					#$html_content .= " <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";
				}
				break;
	}

	#if(isset($js_code)) $html_content .= $js_code;

	# Prepare content to show in page
	tools::prepare_content($html_content);


	# PRINT HTML
	print $html_label;
	print $html_content;


	print "</div>"; //wrap

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out', $modo, $lang);

?>