<?php

	# VISUALIZADOR HTML	

	
	
	print "\n<!-- COMPONENT_SECURITY_ADMINISTRATOR [$tipo $parent] -->";

	print "\n<div class=\"wrap_component css_wrap_security_administrator wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-parent=\"{$parent}\"
	data-section_tipo=\"{$section_tipo}\"
	data-modo=\"{$modo}\"
	data-dato=\"{$dato_string}\"
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);	
	


	# CONTENIDO (INPUT)
	$html_contenido = '';	
	switch($permissions) {
			
		case 0	:	
				$html_contenido .= ""; 
				break;
						
		case 1	:

				# CASE CHECKED				
				$checked = (int)$dato===1 ? 'checked="checked"' : '';

				$html_contenido .= "\n <input type=\"checkbox\" class=\"css_security_administrator\"
				id=\"{$identificador_unico}\"
				name=\"{$tipo}_{$parent}\"
				value=\"{$tipo}\"
				title=\"$html_title\"
				$checked
				disabled
				/>";
				break;	
				
		case ($permissions>=2) :

				/**
				* Por defecto será 'disabled' o inactivo.
				* Si el usuario  actual es global_admin y no está editándose a si mismo, 
				* se mostrará como editable
				*/
				# DISABLED
				$disabled = 'disabled';
				if($is_global_admin===true && $parent != $logged_user_id) $disabled = '';

				
				# CASE CHECKED				
				$checked = (int)$dato===1 ? 'checked="checked"' : '';


				$html_contenido .= "\n <input type=\"checkbox\" class=\"css_security_administrator\"
				onchange=\"component_security_administrator.Save(this)\"				
				id=\"{$identificador_unico}\"
				name=\"{$tipo}_{$parent}\"
				value=\"{$tipo}\"
				data-tipo=\"{$tipo}\"
				data-lang=\"{$lang}\"
				data-section_tipo=\"{$section_tipo}\"
				data-parent=\"{$parent}\"
				title=\"$html_title\"
				$checked
				$disabled
				/>";
		
				if(SHOW_DEBUG) {
					#$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
				}
				
				break;							
	}


	# Prepare content to show in page
	tools::prepare_content($html_contenido);	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;


	if ($permissions>=2) {
		print "<script>$(function() { component_security_administrator.update_filter_master_view( + document.getElementById('$identificador_unico').checked ); })</script>";
	}
	
	
	print "\n</div><!-- /css_wrap_security_administrator -->\n\n"; //wrap

?>