<?php
/*
	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 						$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_security_administrator'])) 			$ar_css['css_security_administrator']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 					$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))					$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_security_administrator']))		$ar_css['css_wrap_security_administrator']='';
	if(!isset ($ar_css['css_security_administrator_rotulo']))	$ar_css['css_security_administrator_rotulo']='';
	
	if(!isset ($tools_html)) $tools_html='';
	
	
	print "\n<!-- COMPONENT_SECURITY_ADMINISTRATOR [$tipo $id] -->";
	print "\n<div class=\"css_wrap_security_administrator wrap_component {$ar_css['css_wrap_security_administrator']}\" 
	data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-modo=\"{$modo}\" data-dato=\"{$dato_string}\" data-component_name=\"{$component_name}\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	
	# ONLY ADMIN GLOBAL USERS CAN ACCESS THIS HTML CONTENT
	if($is_global_admin!==true) $permissions = 0;

	# CONTENIDO (INPUT)
	$html_contenido = '';	
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." (security_administrator) </span>"; 
					break;
						
		case 1	:	# CASE CHECKED
					if(!empty($dato[$tipo]) && $dato[$tipo]==2) {
						$checked = 'checked="checked"';					
					}else {
						$checked = "";
					}
					$html_contenido .= "\n <input class=\"css_security_administrator {$ar_css['css_security_administrator']}\" type=\"checkbox\" 
					id=\"{$identificador_unico}\" name=\"{$tipo}_{$id}_tm\" 
					data-tipo=\"{$tipo}\" data-id_matrix=\"{$id}\" data-lang=\"{$lang}\" 
					value=\"{$tipo}\"
					title=\"$html_title\" 
					$checked  
					disabled />";						
									
					break;	
						
		case ($permissions>=2)	:

					#
					# Por defecto será 'disabled' o inactivo.
					# Si el usuario  actal es global_admin y no está editándose a si mismo, 
					# se mostrará como editable
					#
					$disabled = 'disabled';
					if($is_global_admin===true && $edited_user_id_matrix != $logged_user_id_matrix) $disabled = NULL;


					
					# CASE CHECKED
					if(!empty($dato[$tipo]) && $dato[$tipo]==2) {
						$checked = 'checked="checked"';					
					}else {
						$checked = "";
					}
					$html_contenido .= "\n <input class=\"css_security_administrator {$ar_css['css_security_administrator']}\" type=\"checkbox\" 
					id=\"{$identificador_unico}\" name=\"{$tipo}_{$id}_tm\" 
					data-tipo=\"{$tipo}\" data-id_matrix=\"{$id}\" data-lang=\"{$lang}\" data-flag=\"component_security_administrator\"
					value=\"{$tipo}\" 
					title=\"$html_title\"					
					$checked 
					disabled />";
										
					#$html_contenido .= $html_tools;
								
		
			if($permissions==3)
			
					$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$debugger}</span>";	
					
							
	}
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	# INIT COMPONENT
	#require(DEDALO_LIB_BASE_PATH . "/component_common/trigger.component_init.php");
	
	print "\n</div>\n\n"; //wrap

	*/
?>