<?php

	# VISUALIZADOR HTML	

	
	if(isset($_REQUEST[$tipo]))						$dato = $_REQUEST[$tipo];		#var_dump($_REQUEST[$tipo]);
	
	
	print "\n<!-- COMPONENT_SECURITY_ADMINISTRATOR [$tipo $parent] -->";
	print "\n<div class=\"css_wrap_radio_button\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato\"> No access here (radio_button)! </span>";
					break;
						
		case ($permissions>=1)	:
		
					foreach ($ar_list_of_values->result as $value => $rotulo) {
						
						if( is_array($dato) && in_array($value,$dato) ) {
							$checked = 'checked="checked"';
						}else {
							$checked = "";
						}
						$html_contenido .= "\n <input class=\"css_security_administrator\" type=\"checkbox\" name=\"{$tipo}\" data-tipo=\"{$tipo}\" value=\"1\" data-section_tipo=\"{$section_tipo}\" parent=\"{$parent}\" title=\"$html_title\" $checked />";	
						
					}
							
	}	
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div>\n\n"; //wrap
?>