<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 			$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_select'])) 				$ar_css['css_select']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 		$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))		$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_select']))			$ar_css['css_wrap_select']='';
	//if(!isset ($ar_css['css_select_rotulo']))		$ar_css['css_select_rotulo']='';
	
	if(!isset ($tools_html))						$tools_html='';
	
	
	echo "\n<!-- SELECT [tipo:$tipo id_matrix:$id] $label -->";
	echo "\n<div class=\"css_wrap_select {$ar_css['css_wrap_select']}\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> No access here (select)! </span>";		
					break;
											
		case ($permissions>=1)	:
										
					$html_contenido .= $valor ;
					
					if(SHOW_DEBUG)
					$html_contenido .= " <span class=\"debug_info\">[$dato]</span>";
						
			if($permissions==3)
			
					$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$debugger}</span>";	
					
											
	}
	
	
	# PRINT HTML
	//print $html_label;
	print $html_contenido;
	//print $html_tools;
	
	
	echo "\n</div>\n\n"; //wrap
?>