<?php

	# VISUALIZADOR HTML

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 			$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_ref'])) 				$ar_css['css_ref']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 		$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))		$ar_css['css_span_debugger']='';


	print "\n<!-- COMPONENT_AUTOCOMPLETE_TS [tipo:$tipo] -->";
	print "\n<div class=\"wrap_component css_wrap_autocomplete_ts wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-modo=\"{$modo}\"
	data-dato='{$dato_json}''
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";

	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {

		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." (ref)</span>";
					break;

		case 1	: 	$html_contenido .= $valor;
					break;


		case ($permissions>=2)	:

					# VALOR . STRING RESOLVED TO SHOW
					$html_contenido .= "\n <ul class=\"css_autocomplete_ts_valor\">";
					foreach ($ar_valor as $current_value => $value) {

						$html_contenido .= "<li>";

						# BTN DELETE
						$html_contenido .= "\n <div class=\"icon_bs link css_autocomplete_ts_button_delete\"
						data-tipo=\"{$tipo}\"
						data-current_value='$current_value'
						title=\"$label $parent\"
						onclick=\"component_autocomplete_ts.delete(this)\"></div>";

						$html_contenido .= $value;
						if(SHOW_DEBUG) {
							#$html_contenido .= " <span class=\"notes\">$current_value</span>";
						}

						$html_contenido .= "</li>";

					}
					$html_contenido .= "</ul>";


					#
					# INPUT SEARCH FIELD
					$html_contenido .= "\n <input class=\"css_autocomplete_ts_search_field\" type=\"text\" placeholder=\"".label::get_label('buscar')."...\"
					data-id_wrapper=\"$id_wrapper\"
					data-ar_tipo_to_search='{$ar_referenced_tipo_json}'
					onfocus=\"component_autocomplete_ts.activate(this)\"					
					tabindex=\"1\"
					/>";

					if(SHOW_DEBUG) {
						$html_contenido .= "<div class=\"notes\">ar_referenced_tipo: ".implode(', ', $ar_referenced_tipo)."</div>";
						$html_contenido .= "<div class=\"notes\">".str_replace('},', '},<br>', $dato_json) ."</div>";
					}


					#
					# TREE RESOLUTION STATS
					#$html_contenido .= "\n <div id=\"autocomplete_ts_tree_stats_{$tipo}\" class=\"css_autocomplete_ts_tree_stats\"> Calculating.. </div>";

					# INPUT DATA HIDDEN
					$html_contenido .= "\n<input type=\"text\" name=\"{$input_name}\" class=\"css_autocomplete_ts_dato_hidden\" style=\"width:300px\"
					data-tipo=\"{$tipo}\"
					data-section_tipo=\"{$section_tipo}\"
					data-parent=\"{$parent}\"
					data-lang=\"{$lang}\"
					data-ar_tipo_to_search='{$ar_referenced_tipo_json}'
					data-link_fields='{$ar_link_fields}'
					value='{$dato_json}'
					title='$ar_referenced_tipo_json'
					disabled=\"disabled\"
					/>";

			if($permissions==3)

					$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$parent}\" >{$debugger}</span>";

	}

	# Prepare content to show in page
	tools::prepare_content($html_contenido);


	# PRINT HTML
	print $html_label;
	print $html_contenido;



	print "\n</div><!-- /css_wrap_autocomplete_ts COMPONENT_AUTOCOMPLETE_TS [tipo:$tipo parent:$parent] $label -->\n\n"; //wrap
?>
