<?php

	# VISUALIZADOR HTML	
	
		
	
	print "\n<!-- COMPONENT_AUTOCOMPLETE_TS $label -->";

	print "\n<div class=\"wrap_component css_wrap_autocomplete_ts\" id=\"{$id_wrapper}\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "";
					break;
						
		case 1	: 	$html_contenido .= $valor;
					break;	
						
		
		case ($permissions>=2)	:

					# COMPARISON OPERATORS
					$html_contenido .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);

					
		
					# VALOR . STRING RESOLVED TO SHOW
					#$html_contenido .= "\n <div class=\"css_autocomplete_ts_valor\">".$valor_searched_string."</div>";
					# VALOR . STRING RESOLVED TO SHOW
					$html_contenido .= "\n <ul class=\"css_autocomplete_ts_valor\">";					
					$html_contenido .= "</ul>";

					
					#
					# INPUT SEARCH FIELD
					$html_contenido .= "\n <input type=\"text\" class=\"css_autocomplete_ts_search_field\"
					placeholder=\"".label::get_label('buscar')."...\"
					data-ar_tipo_to_search='{$ar_referenced_tipo_json}'
					onclick=\"component_autocomplete_ts.activate(this)\"
					/>";



					# INPUT DATA HIDDEN
					$html_contenido .= "\n <input type=\"text\" name=\"{$input_name}\" class=\"css_autocomplete_ts_dato_hidden temmporal\"
					id=\"{$identificador_unico}\"						 
					data-tipo=\"{$tipo}\"
					data-section_tipo=\"{$section_tipo}\"
					data-parent=\"{$parent}\"
					data-lang=\"{$lang}\"
					value='{$dato_json}'
					/>";
					


					# BTN DELETE
					/*
					$html_contenido .= "\n <div class=\"div_image_link link css_autocomplete_ts_button_delete\" 
					data-tipo=\"{$tipo}\"
					title=\"$label $id\"
					onclick=\"component_autocomplete_ts.delete_searched_value(this)\"></div>";
					*/	


					# TREE RESOLUTION STATS
					#$html_contenido .= "\n <div id=\"autocomplete_ts_tree_stats_{$tipo}\" class=\"css_autocomplete_ts_tree_stats\">231</div>";					

								

					# LOGICAL OPERATORS
					$html_contenido .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);

					break;				
											
	}

	# Prepare content to show in page
	tools::prepare_content($html_contenido);
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	
	print "\n</div><!-- /css_wrap_autocomplete_ts COMPONENT_AUTOCOMPLETE_TS [tipo:$tipo id_matrix:$parent] $label -->\n\n"; //wrap
?>