
<div id="tm_rows">

	<div class="css_time_machine_label css_tool_label history_label text_shadow_inset">
		<?php echo label::get_label('historico') ?> 
		<?php
		# Lang selector
		#echo " $lang_name [$lang] ";

		$html_selector ='';
		#$html_selector .= "\n <span class=\"rotulo_tool_lang_selector\">".label::get_label('idioma').":</span> ";
		$html_selector .= "\n <select class=\"tool_lang_selector_source css_select\"
		onchange=\"tool_time_machine.change_tool_lang_source(this)\"
		> ";
					
			# Empty option
			#$html_selector .= "\n <option value=\"\"> </option>";
			foreach ((array)$ar_source_langs as $current_lang => $current_lang_name) {
				
				$selected 		= ($current_lang === $lang) ? 'selected' : '';
				$html_selector .= "\n <option value='{$current_lang}' {$selected}>$current_lang_name</option>";							
			}

		$html_selector .= "\n </select>";
		echo $html_selector;
		?>
	</div>


	<!-- BUTTONS APPLY / CLOSE -->
	<?php if ($permissions>=2) { ?>
	<div id="<?php echo "tm_header_{$tipo}_{$id}_{$lang}" ?>" class="tm_header_div div_image_link apply_and_save_link" onclick="tool_time_machine.assign_time_machine_value(this)"
		data-tipo="<?php echo $tipo ?>"
		data-section_tipo="<?php echo $section_tipo ?>"
		data-parent="<?php echo $parent ?>"
		data-lang="<?php echo $lang ?>">
		
		<div class="tm_apply_and_save_text text_shadow_inset"><?php echo label::get_label('aplicar_y_salvar') ?></div>
		<div class="css_time_machine_image_aplicate div_image_link"></div>
		<?php /*<div class="close_tool_tm div_image_link" onclick="close_tm(this)">Close</div>*/?>

	</div>
	<?php } ?>

		
	<div class="time_machine_record_rows shadow_inset">    
		 <!-- TM ROWS -->
		<?php
		# ROWS DATA ITERATION
		# $id_matrix_component	= $id;
		$ar_dato_printed 		= NULL;
		foreach((array)$ar_component_time_machine as $tm_obj) {	
			
			$fecha					= component_date::timestamp_to_date($tm_obj->get_timestamp(), $seconds=true);
			$userID					= $tm_obj->get_userID();
			$mod_user_name			= $tm_obj->get_user_name();
			$id_time_machine		= $tm_obj->get_ID();
			$component_tipo 		= $tm_obj->get_tipo();
			$lang					= $tm_obj->get_lang();
			$dato					= $tm_obj->get_dato();
			$identificador_unico 	= $tm_obj->get_identificador_unico();		
			$show_row 		 		= true;

			$modelo_name = RecordObj_dd::get_modelo_name_by_tipo($component_tipo,true);
			switch ($modelo_name) {
				case 'component_text_area':
					$dato_string	= TR::deleteMarks($dato);
					$dato_string	= strip_tags($dato_string);
					$dato_string	= substr($dato_string, 0, 150);	
					break;
				
				default:
					$dato_string	= to_string($dato);
					break;
			}		

			# ROW HTML
			if ($show_row===true) {
				?>
				<div class="css_time_machine_record_line" onclick="tool_time_machine.set_tm_history_value_to_tm_preview(this)"
					data-parent="<?php echo $parent ?>"
					data-tipo="<?php echo $tipo ?>"
					data-lang="<?php echo $lang ?>"
					data-current_tipo_section="<?php echo $this->section_tipo ?>"
					data-id_time_machine="<?php echo $id_time_machine ?>"
					>
					
					<!-- INFO LINE -->
					<span><?php echo $fecha ?> - <?php echo $mod_user_name ?> (<?php echo $userID ?>)</span>
					
					<!-- BUTTON BACK -->
					<div class="css_image_go_back div_image_link" title="Show tm value (<?php echo $id_time_machine ?>)"></div>

					<?php 
					if (SHOW_DEBUG===true) {
						echo "<span class=\"sample_data\">$dato_string</span>" ;
					}
					?>
				</div>
				<?php	
			}#if ($show_row===true)
			
		}// loop
		#dump($ar_dato_printed,'$ar_dato_printed');
		?>


	</div><!-- css_time_machine_record_rows -->


</div><!-- tm_rows -->

