<?php
/* DEPRECATED 


	# VISUALIZADOR HTML	
		
	# BUTTON TOOL
	$html_tool    = "\n<!-- TOOL TIME MACHINE [tipo:$tipo] -->";
	$html_tool   .= "<div class=\"tool_inspector_div\">";

	$btn_title	  = label::get_label('abrir').' '.label::get_label('herramienta');
	$html_tool   .= "\n<div class=\"icon_bs tool_time_machine_icon link\"
						data-tab_id=\"btn_time_machine_{$tipo}_{$id}\"
						data-tipo=\"{$tipo}\" data-parent=\"{$parent}\"
						data-lang=\"{$lang}\"
						title=\"$btn_title\"
						onclick=\"tool_common.open_tool_time_machine(this)\"
						></div>";
						# desactivado:  data-current_tipo_section=\"{$current_tipo_section}\" 


	$html_tool   .= label::get_label('tool_time_machine');	#" Time machine ";
	
	$html_tool   .= "</div>";#/tool_inspector_div

	# PRINT HTML
	print $html_tool;
*/
?>