<?php
/*
* TIME MACHINE MAIN PAGE
*/

	# VISUALIZADOR HTML	
	$html = '';
	#$html    = "<!-- TOOL TIME MACHINE PAGE [tipo:$tipo section_id:$parent] -->";	
	$html   .= "<div class=\"wrap_time_machine_page\" data-tipo=\"$tipo\" data-parent=\"$parent\" data-section_tipo=\"$section_tipo\" data-lang=\"$lang\">";

		# CONTENT TITLE
		#$html 	.= "<div class=\"css_time_machine_label css_tool_label text_shadow_inset\">Time Machine page</div>";
				
		#
		# ORIGINAL COMPONENT
		# Current active matrix version of current component
		$html 	.= "<div id=\"tm_component_actual\">";		
		$html 	.= 	 $source_html;
		$html 	.= "</div>";
		

		#
		# PREVIEW COMPONENT
		# Historic TM component. Default is last save (previous of actual) of source component
		$html 	.= "<div id=\"tm_component_time_machine\">";
		$html 	.= 	 $preview_html;
		$html 	.= "</div>";


		#
		# ROWS  
		# Versions selector
		$html 	.= "<div id=\"tm_selector_time_machine\">";
		$html 	.= 	 $rows_html;
		$html 	.= "</div>";


		#
		# INSPECTOR_LOG
		$html 	.= "<div id=inspector_log></div>";

		
		#
		# LOAD PREVIEW AND ROWS BY AJAX /**/		
		$html   .= "<script>";
		$html   .= "tool_time_machine.load_preview_component('$tipo','$parent','$lang',null,'$this->section_tipo');";	
		#$html   .= "//tool_time_machine.load_rows_history($id,'$tipo','$lang','$current_tipo_section');											
		$html   .= "</script>";
		
		
	$html   .= "</div><!-- /wrap_time_machine_page -->";
	


	print $html;
		
?>