<?php

	# VISUALIZADOR HTML
	$html_tool  ='';
	$html_tool .= "<div class=\"link\" onclick=\"tool_common.open_tool_time_machine(this)\"
	data-tipo=\"$tipo\"
	data-parent=\"$parent\"
	data-section_tipo=\"$section_tipo\"
	data-lang=\"$lang\"
	>";
	$html_tool .= " <div class=\"icon_bs tool_time_machine_icon\"></div>";
	$html_tool .=   label::get_label('tool_time_machine');
	$html_tool .= "</div>";
	
	
	# PRINT HTML
	echo $html_tool;
?>