<?php

	# VISUALIZADOR HTML
	$html = '';
	#$html    = "<!-- TOOL TIME MACHINE PREVIEW COMPONENT [tipo:$tipo section_id:$id] -->";
	
	# Wrap
	$html   .= "<div class=\"css_wrap_time_machine sgc_edit\">";
		
		# Header
		$html 	.= "<div class=\"css_time_machine_label css_tool_label text_shadow_inset\">";
		$html 	.= label::get_label('tool_time_machine')." ".label::get_label('preview');
		$html 	.= " [$lang]";
		if(SHOW_DEBUG===true) {
			
		}
		$html 	.= "</div>";
		
		# Component html
		$html   .= $component_for_time_machine_html;

		# Footer info					
		$html .= "<div class=\"tm_component_footer_info\"> $version_date </div>";
	
	$html   .= "</div>"; //wrap


	# Script
	$html   .= "<script>";
	#$html   .= "// Fix current id_time_machine value					 	
	$html   .= "tool_time_machine.current_id_time_machine = ".(int)$id_time_machine.";";								
	$html   .= "</script>";


	print $html;
		
?>