<?php

	# VISUALIZADOR HTML	
	
	if(!isset ($ar_css['css_wrap_time_machine']))		$ar_css['css_wrap_time_machine']='';
	if(!isset ($ar_css['css_div_time_machine']))		$ar_css['css_div_time_machine']='';
	

	$html    = "\n<!-- TOOL TIME MACHINE ACTUAL SOURCE COMPONENT [tipo:$tipo id_matrix:$id] -->";
	
	# Wrap
	$html   .= "\n<div class=\"css_wrap_time_machine {$ar_css['css_wrap_time_machine']}\" >";
		
		# Header
		$html 	.= "\n<div class=\"css_time_machine_label css_tool_label text_shadow_inset\">".label::get_label('contenido_actual')."</div>";

		# Component html
		$html   .= $source_component_html;

		# Footer info					
		$html 	.= "\n <div class=\"tm_component_footer_info\">".label::get_label('ahora')."</div>";
	
	$html   .= "\n</div>"; //wrap css_wrap_time_machine


	print $html;


	
		
?>