<?php
/*
* TIME MACHINE MAIN PAGE
*/

	# VISUALIZADOR HTML	
	
	if(!isset ($ar_css['css_wrap_time_machine']))		$ar_css['css_wrap_time_machine']='';
	if(!isset ($ar_css['css_div_time_machine']))		$ar_css['css_div_time_machine']='';
	

	$html    = "\n<!-- TOOL TIME MACHINE PAGE [tipo:$tipo id_matrix:$parent] -->";	
	$html   .= "\n<div class=\"wrap_time_machine_page\" >";		


		# CONTENT TITLE
		#$html 	.= "\n<div class=\"css_time_machine_label css_tool_label text_shadow_inset\">Time Machine page</div>";
		
		
		#
		# ORIGINAL COMPONENT
		# Current active matrix version of current component
		$html 	.= "\n<div id=\"tm_component_actual\">";
		/*
		$html   .= "\n<!-- TOOL TIME MACHINE ORIGINAL COMPONENT [tipo:$tipo id_matrix:$id] -->";
		$html   .= "\n<div class=\"css_wrap_time_machine {$ar_css['css_wrap_time_machine']}\" >";		
		$html 	.= "\n<div class=\"css_time_machine_label css_tool_label text_shadow_inset\">Actual content</div>";
		$html   .= $source_component_html;

		# Footer info
		$html .= "\n <div class=\"tm_component_footer_info\"> Current content </div>";

		$html   .= "\n</div>"; //css_wrap_time_machine
		*/
		$html 	.= $source_html;
		$html 	.= "\n</div>";
		

		#
		# PREVIEW COMPONENT
		# Historic TM component. Default is last save (previous of actual) of source component
		$html 	.= "\n<div id=\"tm_component_time_machine\">";
		$html 	.= $preview_html;
		$html 	.= "\n</div>";


		#
		# ROWS  
		# Versions selector
		$html 	.= "\n<div id=\"tm_selector_time_machine\">";
		$html 	.= $rows_html;
		$html 	.= "\n</div>";

		#INSPECTOR_LOG

		$html 	.= "<div id=inspector_log></div>";
		
		#
		# LOAD PREVIEW AND ROWS
		/**/
		$html   .= "<script>
						tool_time_machine.load_preview_component('$tipo','$parent','$lang',null,'$this->section_tipo'); 	//( id, tipo, lang, id_time_machine, current_tipo_section)			 	
						//tool_time_machine.load_rows_history($id,'$tipo','$lang','$current_tipo_section');											
					</script>";
		
		
	$html   .= "\n</div><!-- /wrap_time_machine_page -->";


	


	print $html;
		
?>