<?php

	# VISUALIZADOR HTML	
		
	# BUTTON TIME MACHINE
	#$html_time_machine    = "\n<!-- TOOL TIME MACHINE [tipo:$tipo] -->";

	
	$html_time_machine   .= "<div class=\"tm_list_wrap\">";

	$btn_title	  		  = label::get_label('abrir').' '.label::get_label('herramienta');

	$html_time_machine   .= "<div class=\"icon_bs tool_time_machine_icon link\" ";
	$html_time_machine   .= "data-tab_id=\"btn_time_machine_{$tipo}\" ";
	$html_time_machine   .= "data-tipo=\"{$tipo}\" ";
	$html_time_machine   .= "data-section_tipo=\"{$section_tipo}\" ";
	$html_time_machine   .= "data-parent=\"{$parent}\" ";
	$html_time_machine   .= "data-lang=\"{$lang}\" ";
	$html_time_machine   .= "title=\"$btn_title\" ";
	$html_time_machine   .= "onclick=\"tool_common.open_tool_time_machine(this)\" ";
	$html_time_machine   .= "></div> ";


	$html_time_machine   .= "<div class=\"tm_btn_label\">";
	$html_time_machine   .=  label::get_label('tool_time_machine');	#" Time machine ";
	$html_time_machine   .= "</div>";
	
	$html_time_machine   .= "<div id=\"tm_list_container\" class=\"tm_list_container\" style=\"display:none\"><!-- Ajax load --></div>";

	$html_time_machine   .= "</div><!-- /tm_list_wrap -->";

	
	# PRINT HTML
	print $html_time_machine;

?>