<?php


die("Deprecated");














































	
	# VISUALIZADOR HTML	

	# CUSTOM_STYLE
	$custom_style = $total_rows<=1 ? 'style="display:none"' : '';
		

	# CUSTOM_CSS
	# Add custom class in different modo''
	$custom_css = '';
	

	# CONTENIDO (INPUT)
	if(SHOW_DEBUG===true) {
		print "<!-- RECORDS NAVIGATOR [section_tipo:$section_tipo] -->";
	}
	
	$html_contenido  = "<div class=\"css_wrap_rows_paginator text_unselectable $custom_css\" $custom_style>";
					
		$html_contenido  .= "<div class=\"css_rows_paginator_content\">";		
		#if ($total_rows>0) {
			
			
			# LINKS
			$html_contenido  .= "<div class=\"css_rows_paginator_div_links\">";

				#  To first page <<					
				if($page_number>1) {							
					$options->offset  = $first_page_offset;						
					$html_contenido  .= "<div onclick='search.load_rows(".json_handler::encode($options).",this)' class=\"icon_bs paginator_first_icon link\"></div>";
				}else{
					$html_contenido  .= "<div class=\"icon_bs paginator_first_icon paginator_desactive\"></div>";
				}
				
				#  To previous page <
				if($prev_page_offset>=0) {						
					$options->offset  = $prev_page_offset;
					$html_contenido  .= "<div onclick='search.load_rows(".json_handler::encode($options).",this)' class=\"icon_bs paginator_prev_icon link\"></div>";
				}else{
					$html_contenido  .= "<div class=\"icon_bs paginator_prev_icon paginator_desactive\"></div>";
				}

				#  To next page >
				if($next_page_offset<$total_rows) {							
					$options->offset  = $next_page_offset;
						#dump($options,"options en next button");
					$html_contenido  .= "<div onclick='search.load_rows(".json_handler::encode($options).",this)' class=\"icon_bs paginator_next_icon link\"></div>";
				}else{
					$html_contenido  .= "<div class=\"icon_bs paginator_next_icon paginator_desactive\"></div>";
				}
			
				#  To last page >>
				if($page_number<$total_pages) {
					$options->offset  = $last_page_offset;
					$html_contenido  .= " <div onclick='search.load_rows(".json_handler::encode($options).",this)' class=\"icon_bs paginator_last_icon link\"></div>";
				}else{
					$html_contenido  .= "<div class=\"icon_bs paginator_last_icon paginator_desactive\"></div>";
				}		
			
			$html_contenido  .= "</div>";


			# INFO
			$html_contenido  .= "<div class=\"css_rows_paginator_info\">Page $page_number of $total_pages</div>";
			

		#}#end if ($total_rows>0)			
		$html_contenido  .= "</div><!-- /css_rows_paginator_content -->";	
	
	$html_contenido .= "</div><!-- /css_wrap_rows_paginator -->";
	
	
	# PRINT HTML
	print $html_contenido;
	

?>