<?php
	
	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_section_wrap']))		$ar_css['css_section_wrap']='';
	if(!isset ($ar_css['css_section_titulo']))		$ar_css['css_section_titulo']='';
	if(!isset ($ar_css['css_span_dato'])) 			$ar_css['css_span_dato']='';	
	
	
	print "\n\n<!-- SECTION [tipo:$tipo id_matrix:$id] -->";
	print "\n<div class=\"css_section_wrap {$ar_css['css_section_wrap']}\" >";
	
	
	# ETIQUETA (LABEL)
	#print $context;
	$html_label='';
	switch ($context) {

		case 'list_into_tool_portal_now':
			$html_label 	= '';
			break;

		default:
			/*
			$html_label 	.= "\n<div class=\"css_section_titulo\" >";
			$html_label 	.= component_common_draw::draw_label($this);
			if(SHOW_DEBUG)
			$html_label 	.= " [context:$context] ";
			$html_label 	.= "</div>";
			#$html_label  	.= "\n<div class=\"css_section_titulo\" > Número: ".$dato." </div>";
			*/
			#print "\n<script>$('#current_section_label').html('$label').css('right','8px')</script>";
			break;
	}
	
	
	
	
	# CONTENIDO (INPUT)
	$html_contenido = "\n<div class=\"css_section_content section_content_list\" >";
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato sin_acceso {$ar_css['css_span_dato']}\"> ".label::get_label('contenido_no_autorizado')." </span>";
					break;
						
		case ($permissions>=1)	:
		
					#$html_contenido .= "\n".$ar_components_html;
					#$html_contenido .= "\n <a href=\"javascript:;\" onclick=\"New(this)\" data-tipo=\"{$tipo}\"> New ($tipo)</a> <div class=\"new_ajax_response\"></div> ";	
					
					if (!empty($_REQUEST['portal_section_tipo'])) {
						$clean_url = clean_url_vars('portal_section_tipo');
						echo "<a href=\"?$clean_url\" style=\"float:right;margin-right:20px;\"> View all results </a>";
					}


					# Content html
					$html_contenido .= "\n $html_section_add ";

					# Time machine section button					
					$html_contenido .= "\n $html_section_tm ";										
						
		case 2	: 
		case 3	:	
					break;			
	}
	$html_contenido .= "\n</div><!-- /css_section_content -->";

	
	
	
	# PRINT HTML
	#print $html_label;
	print $html_contenido;
	
	
	print "\n</div><!-- /css_section_wrap SECTION [$tipo] -->\n\n"; //wrap
	
	/*
	if($label=='Tesauro') {

		$url = 'http://' .DEDALO_HOST . DEDALO_ROOT_WEB . '/ts/ts_list.php?modo=tesauro_edit&type=5';
		echo "<iframe src=\"$url\" width=\"100%\" height=\"800\"></iframe>";		
		#echo file_get_contents_curl($url);

	}
	*/
?>