<?php
	
	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_section_wrap']))		$ar_css['css_section_wrap']='';
	if(!isset ($ar_css['css_section_titulo']))		$ar_css['css_section_titulo']='';
	if(!isset ($ar_css['css_span_dato'])) 			$ar_css['css_span_dato']='';	
	
		
	# CONTENIDO (INPUT)
	$html_contenido  = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('contenido_no_autorizado')." </span>";
					break;
						
		case ($permissions>=1)	:
		
					#$html_contenido .= "\n".$ar_components_html;
					#$html_contenido .= "\n <a href=\"javascript:;\" onclick=\"New(this)\" data-tipo=\"{$tipo}\"> New ($tipo)</a> <div class=\"new_ajax_response\"></div> ";	
					
					$html_contenido .= "\n $html_section_add ";
					break;			
	}
	

	# PRINT HTML
	print $html_contenido;
	
?>