<?php

	# VIEW HTML	

	print "<div class=\"wrap_component css_wrap_input_text tooltip_active\" id=\"wrap_{$tipo}\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato='".json_encode($dato)."' ";
	print 'title="'.search_development2::search_options_title( $this->search_operators_info() ).'" ';
	print ">";
	
	# LABEL
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENT
	$html_content = '';
	switch(true) {

		case ($permissions>=1) :
			# COMPARISON OPERATORS
			#$html_content .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);

			# INPUT 
			#$html_content .= "<span id=\"search_component_$tipo\">";

			$html_content .= "<ul>";			
			foreach ((array)$dato as $key => $value) {
				
				$html_content .= "<li>";

					$html_content .= "<input class=\"css_input_text_search\" type=\"text\" ";
					$html_content .= "name=\"{$search_input_name}\" ";
					$html_content .= "data-tipo=\"{$tipo}\" ";
					$html_content .= "value=\"$value\" ";
					$html_content .= "onchange=\"component_common.fix_dato(this,'{$component_name}')\" ";
					$html_content .= "/>";

				$html_content .= "</li>";
			}
			$html_content .= "</ul>";
			
			#$html_content .= "</span>";

			# LOGICAL OPERATORS
			#$html_content .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);
			
			if(SHOW_DEBUG===true) {
				$html_content .= "<span class=\"debug_info\">$search_input_name</span>";
			}
			break;
		default:
			$html_content .= label::get_label("sin_acceso");
			break;
	}//end switch($permissions)
					

	# Prepare content to show in page
	tools::prepare_content($html_content);
	
	
	# PRINT HTML
	print $html_label;
	print $html_content;
	
	
	print "</div>"; //wrap
?>