<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_wrap_security_access']))	$ar_css['css_wrap_security_access']='';
	if(!isset ($ar_css['css_span_dato'])) 				$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_security_radio_button'])) 	$ar_css['css_security_radio_button']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 			$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))			$ar_css['css_span_debugger']='';	
	if(!isset ($ar_css['css_radio_button_rotulo']))		$ar_css['css_radio_button_rotulo']='';
		
	/**/
	print "\n<!-- SECURITY ACCESS [tipo:$tipo id_matrix:$id] -->";
	print "\n<div class=\"css_wrap_security_access wrap_component {$ar_css['css_wrap_security_access']}\" id=\"{$id_wrapper}\"
	data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-parent=\"{$parent}\" data-modo=\"{$modo}\" data-dato=\"{$dato_string}\" data-component_name=\"{$component_name}\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> No access here (security_access)! </span>";	
					break;
						
		case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> No read access here (security_access)!</span>";
					break;	
						
		case ($permissions>=2)	:
		
					/* FORMATO:
					<ul class="menu" id="security_access_ul">  
					<li class="expanded"><a href="#">Create content</a>
					  
						<ul class="menu"> 
						<li class="leaf"><a href="#">Map</a></li> 
						<li class="leaf"><a href="#">Page</a></li> 
						<li class="leaf"><a href="#">Story</a></li> 
						</ul> 
						
					</li>
					</ul>
					*/
							
					$html_contenido .= "\n\n <!-- Tree --> " ;					
					
					# TREE HTML ES CALCULADO EN EL CONTROLADOR
					$html_contenido .= $tree_html;						

					#$html_contenido .= $html_tools;
		
		
			if($permissions==3)
			
					$html_contenido .= "\n <br><span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$debugger}</span>";					
										
							
	}

	# Prepare content to show in page
	tools::prepare_content($html_contenido);	
		
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_security_access -->\n\n"; //css_wrap_security_access
?>