<?php

	# VISUALIZADOR HTML	
		
	
	print "\n<!-- SECURITY ACCESS [tipo:$tipo section_id_matrix:$parent] -->";

	print "\n<div class=\"wrap_component css_wrap_security_access wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-parent=\"{$parent}\"
	data-section_tipo=\"{$section_tipo}\"
	data-modo=\"{$modo}\"
	data-dato=\"{$dato_string}\"
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "";	
					break;
						
		case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato\"> No read access here (security_access)!</span>";					
					break;	
						
		case ($permissions>=2)	:
		
				/* FORMATO:
				<ul class="menu" id="security_access_ul">  
				<li class="expanded"><a href="#">Create content</a>
				  
					<ul class="menu"> 
					<li class="leaf"><a href="#">Map</a></li> 
					<li class="leaf"><a href="#">Page</a></li> 
					<li class="leaf"><a href="#">Story</a></li> 
					</ul> 
					
				</li>
				</ul>
				*/

				$html_contenido .= "\n <input type=\"hidden\" id=\"component_security_access\" 
				data-tipo=\"{$tipo}\"
				data-lang=\"{$lang}\"
				data-section_tipo=\"{$section_tipo}\"
				data-parent=\"{$parent}\"
				data-modo=\"{$modo}\"
				/>";							
								
				
				# TREE HTML ES CALCULADO EN EL CONTROLADOR
				$html_contenido .= "\n\n <!-- Tree --> " ;	
				$html_contenido .= $tree_html;		
	
			if($permissions==3) {
				$html_contenido .= "\n <br><span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";		
			}
			break;										
							
	}


	# Prepare content to show in page
	tools::prepare_content($html_contenido);	
		
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_security_access -->\n\n"; //css_wrap_security_access
?>