<?php

#
# NODE


$html = '';

$html .= "<li class=\"ts_term_li clearfix\">";

	#
	# CHECKBOX
	$checked = '';

	$html .= "\n <input type=\"checkbox\" class=\"css_component_security_areas\" onclick=\"component_security_aaccess.save_area(this,event)\"
	data-tipo=\"{$current_tipo}\"
	value=\"{$current_tipo}\"
	$checked />";



	#
	# TERM NAME	
	$add_class = isset($highlight) ? 'highlight_term' : '';
	$highlight = '';
	
	$html .= "<label id=\"ts_term_{$current_tipo}\" class=\"ts_term_name $add_class\">";
	$html .= $termino;
	if(SHOW_DEBUG) {
		$html .= " <small>[".$current_tipo."]</small>";
	}
	$html .= "</label>";

			/*
				$html_contenido .= "\n <label for=\"{$identificador_unico}_{$tipo}\" class=\"css_component_security_areas_rotulo\">";
				$html_contenido .= "$termino";
				if(SHOW_DEBUG) {
					$html_contenido .= " - [$tipo: ";
					$permissions = isset($dato->$tipo) ? $dato->{$tipo} : '';
					$html_contenido .= "<b>$permissions</b>]";
					$html_contenido .= " ".RecordObj_dd::get_modelo_name_by_tipo($tipo,true);
				}
				$html_contenido .= "</label>";
				*/

	#
	# CHILDRENS TOGGLE BUTTON	
	if (!empty($ar_childrens)) {
		$ar_childrens_json = json_encode($ar_childrens);
		$title = 'mostrar_ocultar';
		$html .= "<div class=\"ts_term_icon icon_show_childrens arrow_right unselectable\" rel=\"tooltip\" title=\"$title\"
		data-termino_id=\"$current_tipo\"
		data-ar_childrens='$ar_childrens_json'
		onclick=\"ts_term.toggle_childrens(this)\"
		></div>";
	}


$html .= "</li>";


#
# CHILDRENS_WRAPPER . Ajax target to load childrens
$html .= "<ul id=\"childrens_wrapper_{$current_tipo}\" class=\"childrens_wrapper\"></ul>";

echo $html;
?>