<?php

	# VISUALIZADOR HTML		
	
	print "<div class=\"css_wrap_geolocation wrap_component\" id=\"{$id_wrapper}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato='".json_encode($dato)."' ";
	print ">";
	
		
		# ETIQUETA (LABEL)
		$html_label = component_common_draw::draw_label($this);
		
		# CONTENIDO (INPUT)
		$html_contenido = '';
		switch($permissions) {
				
			case 0	:	$html_contenido .= " <span class=\"css_span_sin_acceso\">".label::get_label('sin_acceso')."</span>";
						break;
							
			case ($permissions>=1)	:						

						$html_contenido .= " <div id=\"$identificador_unico\">$component_name. working here..</div>";						
												
		}

		# PRINT HTML
		print $html_label;
		print $html_contenido;
	
	
	print "</div>"; //wrap

?>