<?php

	# VISUALIZADOR HTML	
		
	
	print "\n<!-- BUTTON LOGIN [tipo:$tipo id_matrix:$id] -->";

	print "\n<div class=\"css_wrap_button_login\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	/*	
	$html_contenido .= "\n <input class=\"css_button_login\" type=\"button\" 
	data-tipo=\"{$target_tipo}\" 
	value=\"$label\" 
	title=\"$html_title\" 
	/>";
	*/
	$html_contenido .= "\n <div class=\"css_button_login css_button_generic\"
	data-tipo=\"{$target_tipo}\" 
	title=\"$html_title\"
	onclick=\"login.Login()\" 
	>$label</div>";
		
	#$html_contenido .= "\n <input class=\"css_submit\" type=\"submit\" />";

	# PRINT HTML
	print $html_contenido;

		
	print "\n</div>\n\n"; //wrap
?>