<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 			$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_button_login'])) 		$ar_css['css_button_login']='';
	if(!isset ($ar_css['css_span_debugger']))		$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_button_login']))	$ar_css['css_wrap_button_login']='';
		
	
	print "\n<!-- BUTTON LOGIN [tipo:$tipo id_matrix:$id] -->";
	print "\n<div class=\"css_wrap_button_login {$ar_css['css_wrap_button_login']}\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	/*	
	$html_contenido .= "\n <input class=\"css_button_login {$ar_css['css_button_login']}\" type=\"button\" 
	data-tipo=\"{$target_tipo}\" 
	value=\"$label\" 
	title=\"$html_title\" 
	/>";
	*/
	$html_contenido .= "\n <div class=\"css_button_login css_button_generic {$ar_css['css_button_login']}\"
	data-tipo=\"{$target_tipo}\" 
	title=\"$html_title\" 
	>$label</div>";
		
	#$html_contenido .= "\n <input class=\"css_submit\" type=\"submit\" />";

	# PRINT HTML
	print $html_contenido;

		
	print "\n</div>\n\n"; //wrap
?>