<?php

	# VISUALIZADOR HTML	
		
	
	print "<!-- BUTTON LOGIN [tipo:$tipo id_matrix:$id] -->";

	print "<div class=\"css_wrap_button_login\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	/*	
	$html_contenido .= " <input class=\"css_button_login\" type=\"button\" 
	data-tipo=\"{$target_tipo}\" 
	value=\"$label\" 
	title=\"$html_title\" 
	/>";
	*/
	$html_contenido .= "<div class=\"css_button_login css_button_generic\" ";
	$html_contenido .= "data-tipo=\"{$target_tipo}\" ";
	$html_contenido .= "title=\"$html_title\" ";
	$html_contenido .= "onclick=\"login.Login()\" ";
	$html_contenido .= ">$label</div>";
		
	#$html_contenido .= " <input class=\"css_submit\" type=\"submit\" />";

	# PRINT HTML
	print $html_contenido;

		
	print "</div>"; //wrap
?>