<?php

	# VISUALIZADOR HTML

	$custom_tool_label = isset($custom_tool_label) 
		? " : <h2>$custom_tool_label</h2>" 
		: '';

	#
	# HEADER HTML
		$header_html = '';
		$header_html  .= "<!-- TOOL IMPORT FILES [tipo:$tipo] -->";
		$header_html  .= "<div class=\"tool_header\">";
		$header_html  .= " <div class=\"h2_title\"> TOOL IMPORT FILES $custom_tool_label DCNAV";
		
		$header_html  .= " <span class=\"notes\">[$import_mode] ";			
		$header_html  .= " Creates one section $section_tipo for each xml file ";			
		$header_html  .= "</span>";
		
		$header_html  .= " </div>";
		$header_html  .= " <div class=\"import_context_label\">";
		if(SHOW_DEBUG===true) {
		$header_html .= "  <span class=\"debug_info\">".TOOL_IMPORT_FILES_UPLOAD_DIR."</span>";
		}
		$header_html  .= " </div>";//import_context_label
		$header_html  .= " </div>";//tool_header
		echo $header_html;


	#
	# HELP INFO
		if($context_name=='files' && isset($import_help)) {
			echo $import_help;
		}

	#
	# GLOBAL SELECTORS
		echo '<div class="global_selectors">';
			
			// target portal tipo selector
				// $html  = '';
				// $html .= '<div id="global_target_portal_tipo">';
				// $html .= '<span>Target component (All)</span>';
				// $html .= '<select class="target_portal_tipo" onchange="propagate_target_portal_tipo(this.value)">';
				// # Default option
				// $html .= '<option value="'.$target_portal_tipo.'">';
				// $html .= RecordObj_dd::get_termino_by_tipo($target_portal_tipo);
				// if(SHOW_DEVELOPER===true) {
				// 	$html .= " [$target_portal_tipo]";
				// }
				// $html .= '</option>';
				// if(!empty($button_propiedades->additional_component_tipo)) foreach ($button_propiedades->additional_component_tipo as $current_tipo) {
				// 	$html .= '<option value="'.$current_tipo.'">';
				// 	$html .= RecordObj_dd::get_termino_by_tipo($current_tipo);
				// 	if(SHOW_DEVELOPER===true) {
				// 		$html .= " [$current_tipo]";
				// 	}
				// 	$html .= '</option>';
				// } 
				// $html .= '</select>';
				// $html .= '</div>';
				// echo $html;
			
			// processor selector
				// $html  = '';
				// $html .= '<div id="global_processor">';
				// $html .= '<span>Processor (All)</span>';
				// $html .= '<select class="file_processor" onchange="propagate_file_processor(this.value)">';
				// # Default option
				// $html .= '<option value="">Without processing</option>';
				// if(!empty($file_processor)) foreach ($file_processor as $file_processor_obj) {
				// 	$html .= '<option value="'.$file_processor_obj->function_name.'">';
				// 	$html .= $file_processor_obj->name;
				// 	if(SHOW_DEVELOPER===true) {
				// 		$html .= " [$file_processor_obj->function_name]";
				// 	}
				// 	$html .= '</option>';
				// }
				// $html .= '</select>';
				// $html .= '</div>';
				// echo $html;		
			
		echo '</div>';//end global selectors
	
		   

	#
	# FILES UPLOAD MANAGER HTML
		include(DEDALO_LIB_BASE_PATH.'/tools/tool_import_files_dcnav/html/jquery_upload.phtml');		
		echo "<script>var upload_handler_url='$upload_handler_url';</script>";


	
	#
	# FORM (Temporal section)
		// # Note that current section_id received in get url is like 'tmp1'. Section change automatically save_handler (to 'session') for manage this cases as temporal section		
		// $temp_id 			= DEDALO_SECTION_ID_TEMP.'_'.$section_obj->get_tipo().'_'.$user_id;
		// #$temp_id 			= $parent.'_'.$user_id;	
		// $temp_section_tipo  = $target_section_tipo; // Default
		// if ($import_mode==='section') {
		// 	$temp_section_tipo = $section_tipo;
		// 	#dump($section_tipo, ' section_tipo ++ '.to_string());
		// }
		// $section = section::get_instance($temp_id, $temp_section_tipo, 'edit');
		// $section->get_dato(); // 'get_dato' force update section->save_handler (!)

		// # Add custom layout map defined in propiedades of current component portal
		// if (!empty($custom_layout_map)) {
		// 	$section->layout_map = $custom_layout_map;	// Inject custom layout map fron propiedades
		// }
		// $section->show_inspector = (bool)false;
		
		// # Check params
		// 	#dump($custom_params, ' custom_params ++ '.to_string());
		// 	#dump($section->layout_map, ' layout_map section ++ '.to_string( $section->get_tipo() ));
		
		
		// $section_temp_html  = '';
		// $section_temp_html .= "<div class=\"section_temp_title\">".RecordObj_dd::get_termino_by_tipo($temp_section_tipo)." <span class=\"notes\">[$temp_section_tipo]</span></div>";
		// $section_temp_html .= "<div class=\"wrap_section_temp\">";		
		// $section_temp_html .= $section->get_html();
		// $section_temp_html .= "</div>";
		
		// #
		// # PAGE_GLOBALS : Set vars to enable components save data in session
		// #$section_temp_html .= "<script>
		// #page_globals.modo='edit';
		// #	//console.log(page_globals);		
		// #</script>";

		// echo $section_temp_html;


	#
	# FOOTER HTML
		$footer_html	='';
		$footer_html	.= "<div class=\"import_context_label_footer \">";
		$footer_html	.= "<a id=\"button_import_images\" href=\"javascript:void(0);\" class=\"btn btn-success fileinput-button\" ";
		$footer_html	.= "data-tipo=\"$tipo\" ";
		$footer_html	.= "data-section_tipo=\"$section_tipo\" ";
		$footer_html	.= "data-import_mode=\"$import_mode\" ";
		$footer_html	.= "onclick=\"tool_import_files_dcnav.import_files(this)\">";
		$footer_html	.= '<strong>'. label::get_label('tool_import_files'). ' ' .strip_tags($custom_tool_label). '</strong>';
		$footer_html	.= "<span id=\"button_import_span\"></span>";
		$footer_html	.= "</a>";
		$footer_html	.= "</div>";
		echo $footer_html;


?>
<script>
	// PAGE_GLOBALS : Set vars to enable components save data in session
	page_globals.modo='edit';
	// SGC_EDIT
	let current_record_wrap = document.getElementById('current_record_wrap')
	if (current_record_wrap) {		
		// sgc_edit . To enable structure css affect to components, add 'sgc_edit' class to component wrapper simulating a section group
		current_record_wrap.classList.add('sgc_edit')
	}
	let button_import_span		= document.getElementById("button_import_span")
	let import_file_name_mode	= document.getElementById("import_file_name_mode")
		if (import_file_name_mode) {
			button_import_span.innerText = " ["+import_file_name_mode.options[import_file_name_mode.selectedIndex].innerText+"]"
			import_file_name_mode.addEventListener("change",function(el){
				button_import_span.innerText = " ["+this.options[this.selectedIndex].innerText+"]"
			},false)
		}
		
	function propagate_target_portal_tipo(value) {
		let target_portal_tipo = document.querySelectorAll("select.target_portal_tipo")
		const len = target_portal_tipo.length
		for (let i = len - 1; i >= 0; i--) {
			target_portal_tipo[i].value = value
		}
	}
	function propagate_file_processor(value) {
		let file_processor = document.querySelectorAll("select.file_processor")
		const len = file_processor.length
		for (let i = len - 1; i >= 0; i--) {
			file_processor[i].value = value
		}
	}
	function set_import_mode(mode,value) {

		let jquery_upload_wrapper = document.querySelector("div.jquery_upload_wrapper")
		if (value===true) {
			jquery_upload_wrapper.classList.add(mode)
			if(mode === 'numbered'){
				document.getElementById("same_name_same_section").checked = false
				jquery_upload_wrapper.classList.remove('namered')
			}
			if(mode === 'namered'){
				document.getElementById("name_control_to_section_id").checked = false
				jquery_upload_wrapper.classList.remove('numbered')
			}
		}else{
			jquery_upload_wrapper.classList.remove(mode)
		}

		if(mode === 'to_field'){
			const file_processor		= document.querySelectorAll("span.target_component_span")
			const file_processor_len	= file_processor.length
				for (let i = file_processor_len - 1; i >= 0; i--) {
					const file_name		= file_processor[i].dataset.file_name
					const file_hashCode	= file_processor[i].dataset.hashcode
						//console.log(file_name,file_hashCode);
					tool_import_files_dcnav.fix_target_portal_tipo(file_name, file_hashCode, value)
				}
		}
		
	}
	const file_processor_properties	= JSON.parse('<?php echo json_encode($file_processor) ?>');
	const target_portal_map_name	= JSON.parse('<?php echo json_encode($target_portal_map_name) ?>');
	const copy_all_filenames_to		= JSON.parse('<?php echo json_encode($copy_all_filenames_to) ?>');
	const optional_copy_filename	= JSON.parse('<?php echo json_encode($optional_copy_filename) ?>');

	if(SHOW_DEBUG===true) {
		console.log("file_processor_properties:",file_processor_properties);
		console.log("target_portal_map_name:",target_portal_map_name);
		console.log("copy_all_filenames_to:",copy_all_filenames_to);
		console.log("optional_copy_filename:",optional_copy_filename);
	}
	/*var hashCode = function(s){
	  return s.split("").reduce(function(a,b){a=((a<<5)-a)+b.charCodeAt(0);return a&a},0);
	}*/
	
	String.prototype.hashCode = function(){
		var hash = 0;
		if (this.length == 0) return hash;
		for (i = 0; i < this.length; i++) {
			char = this.charCodeAt(i);
			hash = ((hash<<5)-hash)+char;
			hash = hash & hash; // Convert to 32bit integer
		}
		return hash;
	}
</script>