<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 		$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_span_debugger']))	$ar_css['css_span_debugger']='';
	
	print "\n<!-- IMAGE [tipo:$tipo id_matrix:$id] -->";	
		
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= ''; 		
					break;
					
		case ($permissions>=1)	:
					

				$html_image = "\n <img class=\"image_image_in_list\" src=\"$image_url\" data-id_matrix=\"$id\" data-image_id=\"$image_id\" data-parent_matrix=\"$parent\" />";

				$html_contenido .= "\n <div class=\"div_image_image_in_list\" >$html_image</div>";	#style=\"background-image:url('$image_url')\"
					
			
			#if($permissions==3)
					
					#$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$debugger}</span>";	
							
	}	

	
	# PRINT HTML	
	print $html_contenido;	
	
?>