<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	#print "\n<!-- PDF [tipo:$tipo section_id_matrix:$parent] -->";	
		
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= ''; 		
					break;
					
		case ($permissions>=1)	:
					

				#$html_image = "\n <img class=\"image_image_in_list\" src=\"$image_url\" data-image_id=\"$image_id\" data-parent_matrix=\"$parent\" />";
				#$html_contenido .= "\n <div class=\"div_image_image_in_list\" >$html_image</div>";	#style=\"background-image:url('$image_url')\"
				if($file_exists) {
					$html_contenido .= "<div class=\"pdf_thumb_icon\" onclick=\"component_pdf.open_pdf(this)\" data-pdf_url=\"$pdf_url\"></div>";
				}							
	}	

	
	# PRINT HTML	
	print $html_contenido;	
	
?>