<?php

	# VISUALIZADOR HTML
	print '<!-- '.__CLASS__.' -->';
	print '<div id="wrap_rows_search" class="css_wrap_rows_search">';

	
		# CONTENIDO (INPUT)
		$html_content   = '';		


		# VISUALIZADOR HTML
		$html_content 	.= '<script>search2.init('.$init_options_json.')</script>';
		

	print $html_content;


	print '</div><!-- /css_wrap_rows_search -->';




/*

		$search2_html = '';

		# Button to open search2 options
		$search2_html  .= '<div id="open_search2_button" onclick=\'search2.init('.$init_options_json.')\' class="btn btn-default btn-sm button_open_search2">'.label::get_label('filtro').'</div>';
		if(SHOW_DEBUG===true) {
			#$search2_html  .= "<script>window.ready(function(){ search2.init({$init_options_json}) })</script>";
		}

		if ($modo==="thesaurus") {
			#dump($this->ar_real_section_tipo, ' ar_real_section_tipo ++ '.to_string());
			$search2_html  .= '<div id="thesaurus_search_selector">';
			#$search2_html  .= 'Typology sections: ';
			$search2_html  .= '<select id="thesaurus_typology_selector" class="form-control" onchange="search2.show_sections_checkboxes(this.value,\''.encodeURIComponent(json_encode($ar_sections_by_type)).'\')">';
			foreach ($ar_sections_by_type as $key => $ar_items) {
				$typology_id 	= reset($ar_items)->typology;				
				$typology_name 	= reset($ar_items)->typology_name;
  				$search2_html  .= '<option value="'.$typology_id.'">'.$typology_name.'</option>';
  			}
  			$search2_html  .= '</select>';
			$search2_html  .= '<ul id="thesaurus_search_selector_ul">';			
			$search2_html  .= '</ul>';
			$search2_html  .= '</div>';
			$search2_html  .= '<script>';
			$search2_html  .= 'search2.init_tipology_selector({"ar_data_string":"'.encodeURIComponent(json_encode($ar_sections_by_type)).'"});';			
			$search2_html  .= '</script>';
		
			$select_path 	= []; // Always empty

		}else{
			
			// injected layout map
				$layout_map 	= isset($this->section_obj->layout_map) ? $this->section_obj->layout_map : false;
			
			// Select path
				$select_path 	= search_development2::get_search_select_from_section( $this->section_obj,  $layout_map); // Calculated from section list		
		}

		$select_path_json 	= json_encode($select_path);

		
		# GLOBAL_CONTAINER
		$search2_html  .= '<div id="search2_global_container" data-select_path="'.encodeURIComponent($select_path_json).'" style="display:none">';		

			# button_save_preset
			$search2_html  .= '<button id="button_save_preset" type="button" class="btn btn-danger btn-sm" onclick="search2.save_preset(this)">Preset: '.label::get_label('salvar').' '.label::get_label('cambios').'</button>';			
				
			#
			# FIELDS SELECTOR search2_container_selector. Where section fields list are loaded
				$search2_html  .= "<div id=\"toggle_container_selector\" onclick=\"search2.toggle_fields(this)\">".label::get_label('campos')."</div>";
				$search2_html  .= "<div id=\"search2_container_selector\"> search2_container_selector </div>";

			#
			# CANVAS SELECTION search2_container_selection. Where dragged fields are dragged and stored
				$search2_html  .= "<div id=\"search2_container_selection\">";				
				# search_group_container
				$search2_html  .= "<div id=\"search_group_container\"></div>";
				$search2_html  .= "</div>";

			#
			# PRESETS SELECTION_PRESETS search2_container_selection_presets. List of stored selection presets
				$search2_html  .= "<div id=\"search2_container_selection_presets\" data-section_tipo=\"$section_tipo\">";
				#$search2_html  .= '<button id="button_save_preset" type="button" class="btn btn-danger btn-sm btn-block" onclick="search2.save_preset(this)">'.label::get_label('salvar').' '.label::get_label('cambios').'</button>';	
				$search2_html  .= "<div class=\"component_presets_label\">";
				$search2_html  .= label::get_label('presets_de_busqueda');
				$search2_html  .= "<span id=\"button_new_preset\" class=\"button_plus\" onclick=\"search2.new_preset(this)\">+</span>";
				$search2_html  .= "</div>";

				# new_preset_div
				$search2_html  .= "<div id=\"new_preset_div\" class=\"div_edit\"></div>";
				# component_presets_list
				$search2_html  .= "<ul id=\"component_presets_list\"><ul>";
				$search2_html  .= "</div>";//end search2_container_selection_presets
				$search2_html  .= "<div id=\"toggle_container_selection_presets\" onclick=\"search2.toggle_presets(this)\"> Presets </div>";

		$search2_html  .= "</div>";//end search2_global_container

		// Add to page
		$html_content .= $search2_html;


		# PRINT HTML
		print $html_content;


	print '</div><!-- /css_wrap_rows_search -->';
*/

?>