<?php

	# VISUALIZADOR HTML
	print "<!-- ".__CLASS__." -->";
	print "<div class=\"css_wrap_rows_search\">";

	
		# CONTENIDO (INPUT)
		$html_content   = '';
		$html_content  .= " <div class=\"tab_title css_rows_search_tap\" data-tab_id=\"filter_tap\"> ".label::get_label('filtro')." </div>";


		switch(true) {

			case $permissions==0:
				$html_content .= " <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." </span>";
				break;

			case ($permissions>=1)	:

				$display_content  = false;

				$html_content  .= "<div class=\"tab_content css_rows_search_content\" $display_content >";

					# Search operators
					$html_content  .= "<div class=\"button_with_icon_left toggle_search_operators\">".label::get_label('operadores_de_busqueda')."</div>";


					# FORM
					$html_content  .= "<form class=\"css_rows_search_form\" id=\"search_form\" name=\"search_form\" method=\"POST\" action=\"\" onKeyPress=\"return search.check_submit(this, event)\">";

						# COMPONENTS ( CAMPOS DE BÚSQUEDA )
						# dump($ar_search_fields, ' ar_search_fields ++ '.to_string());
						foreach($ar_search_fields as $key_search_component => $component_obj) {

							if(strpos($key_search_component, ':') !== false){
								$case_portal = explode(':', $key_search_component);
								$search_name = $case_portal[0].'_'.$component_obj->get_section_tipo() .'_' .$case_portal[1];

								$html_content  .="<div class=\"css_portal_title\">";
								
								$component_portal =component_common::get_instance('component_portal',
																							  $case_portal[0],
																							  null,
																							  'edit',
																							  DEDALO_DATA_NOLAN,
																							  $section_tipo);
								$portal_name = $component_portal->get_label();
								$html_content  .=$portal_name;
								$html_content  .="</div>";

							}else{
								$search_name = $component_obj->get_section_tipo() .'_'. $component_obj->get_tipo();								
							}
							$component_obj->set_search_input_name($search_name);
							$html_content .= $component_obj->get_html();
						}
						$html_content  .= " <hr>";

						# BUTTONS ACC SEARCH COMPONENTS (MAX PER PAGE,SEARCH BUTTON, RESET...)
						foreach($ar_tools_search as $current_tool_search) {
							$html_content .= $current_tool_search->get_html();
						}
						
						$html_content  .= " <input type=\"hidden\" name=\"section_tipo\" value=\"$section_tipo\">";
						$html_content  .= " <input type=\"hidden\" name=\"modo\" value=\"$modo\">";
						$html_content  .= " <input type=\"hidden\" name=\"search_options_session_key\" value=\"$search_options_session_key\">";
						$html_content  .= " <input type=\"hidden\" name=\"context\" value='".json_encode($context)."'>";
						
					$html_content  .= "</form>";


				$html_content  .= "</div><!-- /css_rows_search_content -->";
				break;
		}


		# PRINT HTML
		print $html_content;


	print "</div><!-- /css_wrap_rows_search -->";
?>
