<?php

	# VISUALIZADOR HTML	

	
	
	print "\n<!-- PROFILE [tipo:$tipo section_id_matrix:$parent] $label -->";
	
	print "\n<div class=\"wrap_component css_wrap_profile wrap_component_{$tipo}\" id=\"{$id_wrapper}\" 
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-parent=\"{$parent}\"
	data-dato=\"{$dato}\"
	data-section_tipo=\"{$section_tipo}\"
	data-modo=\"{$modo}\"
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0:	
			$html_contenido .= "";
			break;

		case 1:	
			$html_contenido .= $valor;
			break;					
		
		case ($permissions>1):		
			$html_contenido .= "\n <select class=\"css_select_profile\" name=\"{$input_name}\" id=\"$identificador_unico\" onchange=\"component_profile.Save(this)\"
			data-tipo=\"{$tipo}\"
			data-lang=\"{$lang}\"
			data-section_tipo=\"{$section_tipo}\"
			data-parent=\"{$parent}\"
			data-dato=\"{$dato}\"
			title=\"$html_title\">";
			
				if(empty($dato)) {
					$checked = 'selected';
				}else{
					$checked = "";
				}
				# First option (custom)
				$html_contenido .= "\n <option value=\"0\" {$checked}> Custom </option>";
				
				# DB Options
				foreach ($ar_select_values as $value => $rotulo) {					
					
					$checked = ($value == $dato) ? 'selected' : '';

					$html_contenido .= "\n <option value=\"{$value}\" {$checked}> {$rotulo}</option>";							
				}

			$html_contenido .= "\n </select>";

			/*
			#$html_contenido .= "<div class=\"icon_bs icon_apply\"></div>";
			$html_contenido .= "\n <input type=\"button\" value=\"".label::get_label('aplicar')."\" class=\"css_button_generic apply_profile_button\" onclick=\"component_profile.apply_profile(this)\">";
			*/			


			#
			# button_value
			if ($is_global_admin===true) {
				$button_value 	 = label::get_label('ir_al_perfil');
				$html_contenido .= " <input type=\"button\" value=\"$button_value\" class=\"go_to_profile\" onclick=\"component_profile.go_to_profile(this, '$profile_section_tipo', '$identificador_unico')\">";
			}
		
			
			if(SHOW_DEBUG) {
				$html_contenido .= " <span class=\"notas\"> (Current dato: $dato)</span>";	
			}
			
	}

	# Prepare content to show in page
	tools::prepare_content($html_contenido);
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;	
	
	
	print "\n</div><!-- /css_wrap_select PROFILE [tipo:$tipo section_id_matrix:$parent] $label -->\n\n"; //wrap
?>