<?php

	# VISUALIZADOR HTML	

	
	#if(isset($_REQUEST[$tipo])) $dato = $_REQUEST[$tipo];	
	#print "<!-- ".__CLASS__." -->";
	print "<div class=\"wrap_component css_wrap_profile\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch($permissions) {
			
		case 0	:	
				$html_content .= "";
				break;				
		
		default:
				# COMPARISON OPERATORS
				$html_content .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);

				
				# SELECT
				$html_content .= "<select class=\"css_profile\" name=\"{$search_input_name}\" data-tipo=\"{$tipo}\" title=\"$html_title\">";
					
					$html_content .= "<option value=\"\"> </option>";					
					foreach ($ar_select_values as $key => $label) {						
						$html_content .= "<option value='$key'> {$label}</option>";
					}					
				$html_content .= "</select>";	
				

				# LOGICAL OPERATORS
				$html_content .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);
											
	}
	
	# Prepare content to show in page
	tools::prepare_content($html_content);
	

	# PRINT HTML
	print $html_label;
	print $html_content;	

	
	print "</div><!-- /css_wrap_profile -->"; //wrap
?>