<?php
/**
* TOOL_CALENDAR PAGE
*/
$html='';

	$html   .= "\n<!-- TOOL PAGE [tipo:$tipo] -->";
	$html   .= "\n<div id=\"wrap_tool\" >";

		$html   .= "\n <div class=\"tool_title text_shadow_inset\" > TOOL CALENDAR : $section_name</div>";		
		$html   .= "\n <div id=\"tool_response\" ></div>";
		

		# Additional custom_script_html if exists
		isset($custom_script_html) ? $html .= $custom_script_html :'';


		$html   .= "\n <div id=\"close_button\" ></div>";		
		$html   .= "\n <div id=\"full_calendar\"></div>";
		$html   .= "\n <div id=\"dialog\" style=\"display:none\"><span></span><input id=\"dialog_input\"> </div>";

	$html   .= "\n</div>";//end wrap_tool

echo $html;

# Include JS vars code
include('tool_calendar_js.phtml');
?>