<?php

	# VISUALIZADOR HTML

	print "<div class=\"wrap_component css_wrap_relation_model tooltip_active\" ";
	print 'title="'.search_development2::search_options_title( $this->search_operators_info() ).'" ';
	print "data-tipo=\"{$tipo}\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-component_info='{$component_info}' ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato='".json_encode($dato)."' ";
	print "data-search_tipos='".json_encode($search_tipos)."' ";
	print ">";

	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	# CONTENIDO (INPUT)
	$html_content = '';
	switch(true) {

		case ($permissions===0)	:
				$html_content .= "";
				break;

		case ($permissions>=1) :

				$html_content .= '<input class="q_operator" type="text" value="'.$q_operator.'" ';
				$html_content .= "onchange=\"component_common.fix_dato(this,'{$component_name}')\" ";
				$html_content .=' />';

				# SELECT
				$html_content .= "<select class=\"css_relation_model\" name=\"{$search_input_name}\" ";
				$html_content .= "onchange=\"component_common.fix_dato(this,'{$component_name}')\" ";
				$html_content .= "title=\"$html_title\" ";
				$html_content .= "data-tipo=\"{$tipo}\" ";
				$html_content .= ">";

					# Empty option
					$html_content .= "<option value=\"\"> </option>";
					foreach ($ar_list_of_values->result as $key => $item) {

						$label   = (string)$item->label;
						$locator = (object)$item->value;

						# Add fixed type
						$locator->type = DEDALO_RELATION_TYPE_MODEL_TIPO;

						$founded  = false;
						if (!empty($dato)) {
							$founded  = locator::in_array_locator( $locator, $ar_locator=$dato, $ar_properties=array('section_id','section_tipo','type') );
						}
						$selected = $founded ? 'selected' : '';

						$locator_json = json_encode($locator);

						$html_content .= "<option value='". $locator_json ."' {$selected}>";
						$html_content .= $label;

						$html_content .= "</option>";
					}

				$html_content .= "</select>";
				break;
	}

	# Prepare content to show in page
	tools::prepare_content($html_content);


	# PRINT HTML
	print $html_label;
	print $html_content;


	print "</div>"; //wrap
?>
