<?php
	
	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 		$ar_css['css_span_dato']='';
	
	print "\n<!-- AREA_ROOT [tipo:$tipo modo:$modo] -->";
	print "\n<div class=\"css_wrap_area_root\" 
	data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-component_name=\"{$component_name}\" >";
	
	# ETIQUETA (LABEL)
	$html_label = "\n<div class=\"css_area_titulo\" > ".component_common_draw::draw_label($this)." </div>";	
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." (input_text)</span>";
					break;
						
		#case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\">Read only access</span>";
		#			break;	
						
		case ($permissions>=1)	:
		
					$html_contenido .= "\n <blockquote>";
					
					#$menu = new menu('list');
					#$html_contenido .= 	"<hr>".$menu->get_html();	
					$ar_sections = component_relation::get_all_authorized_content_sections();				
					foreach ($ar_sections as $tipo => $name) {
						$html_contenido .= "<br> <a href=\"?t=$tipo\" class=\"link\">$name</a> ";
					}
					$html_contenido .= "\n </blockquote>";
					
					#$html_contenido .= "\n <span  class=\"css_span_log\"></span>";					
					#$html_contenido .= "\n <span  class=\"css_span_ejemplo {$ar_css['css_span_ejemplo']}\">$ejemplo</span>";						
					
					#$html_contenido .= $html_tools;
					
			if($permissions==3)		
					$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$debugger}</span>";	
					
											
	}	
	
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);

	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div><!-- /AREA_ROOT [tipo:$tipo modo:$modo] -->"; //wrap



?>