<?php
	
	# VISUALIZADOR HTML	

		
	
	print "<!-- AREA [tipo:$tipo] -->";

	print "<div class=\"css_wrap_area\" > ";
	
	
	# ETIQUETA (LABEL)
	$html_label = "<div class=\"css_area_titulo\" > ".component_common_draw::draw_label($this)." </div>";
		
	
	# CONTENIDO (INPUT)
	$html_contenido  ='';
	$html_contenido .= "<div class=\"css_area_content area_content_list\" >";
	
	switch(true) {
			
		case $permissions===0	:
					$html_contenido .= " <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." </span>";
					break;
						
		case ($permissions>=1) :
					/*
					#dump($ar_ts_children ,'$ar_ts_children ');
					foreach ($ar_ts_children as $key => $current_obj) {
						if (is_object($current_obj)) {
							$html_contenido .= $current_obj->get_html();
						}						
					}
					*/
					# Div stats content (loaded by ajax triggered whe button is clicked)
					#$html_contenido .= "<div id=\"stats_info\"><!-- Stats content here --></div>";


					#dump($ar_children_areas ,'$ar_children_areas ');
					$path = DEDALO_CORE_URL .'/main/';
					$html_contenido .= " <blockquote> ";
					foreach ($ar_children_areas as $tipo => $value) {

						$section_name = RecordObj_dd::get_termino_by_tipo($tipo,DEDALO_APPLICATION_LANG,true);
						$modelo_name  = RecordObj_dd::get_modelo_name_by_tipo($tipo,true);
						
						$html_contenido .= menu::create_link($tipo, $section_name, $modelo_name, null);
						$html_contenido .= "<br>";
					}
					$html_contenido .= " </blockquote> ";
					
					
					break;			
	}
	
	$html_contenido .= "</div>";
	
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);

	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "</div><!-- /AREA [$tipo] -->"; //wrap
?>