<?php

	# VISUALIZADOR HTML	
	#print "\n<!-- INPUT_TEXT [tipo:$tipo id_matrix:$id] -->";

	print "\n<div class=\"wrap_component css_wrap_input_text\" id=\"wrap_{$tipo}\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "";
					break;
						
		case ($permissions>=1) :

					# COMPARISON OPERATORS
					$html_contenido .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);

					# INPUT 
					$html_contenido .= "<span id=\"search_component_$tipo\">";
					$html_contenido .= "\n <input class=\"css_input_text_search\" type=\"text\"
					name=\"{$tipo}\"
					data-tipo=\"{$tipo}\"
					value=\"{$dato}\"
					title=\"$html_title\"
					/>";
					$html_contenido .= "</span>";

					# LOGICAL OPERATORS
					$html_contenido .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);
					
											
	}//end switch($permissions) 


	# Prepare content to show in page
	tools::prepare_content($html_contenido);	
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div>\n\n"; //wrap
?>