<?php

	# VISUALIZADOR HTML		

	print "<div class=\"css_wrap_input_text\">";
	
		# LABEL
		$html_label = component_common_draw::draw_label($this);
		
		# CONTENT
		$html_content = '';

		$html_content .= " <input class=\"css_input_text\" type=\"text\"
		onchange=\"component_input_text.Save(this)\"
		id=\"{$identificador_unico}\"
		name=\"{$tipo}_{$parent}\"
		data-tipo=\"{$tipo}\"
		data-modo=\"login\"
		value=\"\"
		title=\"$html_title\"
		placeholder=\"$label\"
		/>";		
		
		# PRINT HTML
		print $html_label;
		print $html_content;	
	
	print "</div>"; //wrap
?>