<?php

	# VISUALIZADOR HTML		
	
	
		
		# CONTENT
		$html_contenido  = '';


			$html_contenido .= "<div class=\"list_thesaurus_element input_text_list_thesaurus\" onclick=\"component_input_text.show_component_in_row_thesaurus(this)\" ";
			$html_contenido .= "data-section_tipo=\"$section_tipo\"
								data-parent=\"$parent\"
								data-tipo=\"$tipo\"
								data-lang=\"$lang\"
								data-modo=\"edit\"";

				# Content inside div
				# dump($render_vars, ' render_vars ++ '.to_string());		
				switch (true) {
					case (isset($render_vars->type) && $render_vars->type=='term'):
						$value = $this->get_valor(DEDALO_DATA_LANG);
						$valor = component_input_text::render_list_value($value, $tipo, $parent, $modo, $lang, $section_tipo, $parent);
							#dump($valor, ' $valor ++ '.to_string());				
						foreach ($render_vars as $rv_key => $rv_value) {
							$html_contenido .= " data-{$rv_key}='{$rv_value}'";
						}
						$html_contenido .= ">";
						$html_contenido .= $valor;						
						break;

					default:
						$html_contenido .= ">";
						$html_contenido .= $icon_label;
				}

			
			$html_contenido .= "</div>";	
				
		
	
		
		
		# PRINT HTML
		print $html_contenido;
	
	
?>