<?php

	# VIEW HTML	

	print "<div class=\"wrap_component css_wrap_input_text\" id=\"wrap_{$tipo}\">";
	
	# LABEL
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENT
	$html_content = '';
	switch(true) {

		case ($permissions>=1) :
				# COMPARISON OPERATORS
				$html_content .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);

				# INPUT 
				#$html_content .= "<span id=\"search_component_$tipo\">";

				$html_content .= "<input class=\"css_input_text_search\" type=\"text\" ";
				$html_content .= "name=\"{$search_input_name}\" ";
				$html_content .= "data-tipo=\"{$tipo}\" ";
				$html_content .= "value=\"\" ";
				$html_content .= "title=\"$html_title\" ";
				$html_content .= "/>";
				
				#$html_content .= "</span>";

				# LOGICAL OPERATORS
				$html_content .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);
				
				if(SHOW_DEBUG===true) {
					$html_content .= "<span class=\"debug_info\">$search_input_name</span>";
				}
				break;
		default:
			$html_content .= label::get_label("sin_acceso");

	}//end switch($permissions)
					

	# Prepare content to show in page
	tools::prepare_content($html_content);
	
	
	# PRINT HTML
	print $html_label;
	print $html_content;
	
	
	print "</div>"; //wrap
?>