<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 		$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_input_text'])) 		$ar_css['css_input_text']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 	$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))	$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_input_text']))	$ar_css['css_wrap_input_text']='';
	
	if(!isset ($html_tools))					$html_tools='';
	
	if(isset($_REQUEST[$tipo]))					$dato = $_REQUEST[$tipo];		#var_dump($_REQUEST[$tipo]);
	
	
	#print "\n<!-- INPUT_TEXT [tipo:$tipo id_matrix:$id] -->";
	#print "\n<div class=\"css_wrap_input_text {$ar_css['css_wrap_input_text']}\" id=\"wrap_{$tipo}\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_sin_acceso\">".label::get_label('sin_acceso')."</span>";
					break;
						
		case ($permissions>=1) :
		
					$html_contenido .= "\n <input class=\"css_input_text {$ar_css['css_input_text']}\" type=\"text\" 
					name=\"{$tipo}\" 
					data-tipo=\"{$tipo}\"
					value=\"{$dato}\" title=\"$html_title\" />";
											
	}

	# Prepare content to show in page
	tools::prepare_content($html_contenido);	
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	#print "\n</div>\n\n"; //wrap
?>