
<div class="jquery_upload_wrapper">

<div class="container">
    
    <!-- The file upload form used as target for the file upload widget -->
    <form id="fileupload" action="" method="POST" enctype="multipart/form-data">
        <!-- Redirect browsers with JavaScript disabled to the origin page -->
        <noscript><input type="hidden" name="redirect" value="http://blueimp.github.io/jQuery-File-Upload/"></noscript>
        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
        <div class="row fileupload-buttonbar">
            <div class="col-lg-7">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="glyphicon glyphicon-plus"></i> 
                    <span><?php echo label::get_label('anadir_ficheros')?>...</span>
                    <input type="file" name="files[]" multiple>
                </span>
                <button type="submit" class="btn btn-primary start">
                    <i class="glyphicon glyphicon-upload"></i>
                    <span><?php echo label::get_label('comenzar_la_carga')?></span>
                </button>
                <button type="reset" class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span><?php echo label::get_label('cancelar_la_carga')?></span>
                </button>
                <button type="button" class="btn btn-danger delete">
                    <i class="glyphicon glyphicon-trash"></i>
                    <span><?php echo label::get_label('borrar')?></span>
                </button>
                <input type="checkbox" class="toggle">
                <!-- The global file processing state -->
                <span class="fileupload-process"></span>
            </div>
            <!-- The global progress state -->
            <div class="col-lg-5 fileupload-progress fade">
                <!-- The global progress bar -->
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                </div>
                <!-- The extended global progress state -->
                <div class="progress-extended">&nbsp;</div>
            </div>
        </div>
        <!-- The table listing the files available for upload/download -->
        <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
    </form>
    <br>
    
</div>
<!-- The blueimp Gallery widget -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span><?php echo label::get_label('comenzar_la_carga')?></span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span><?php echo label::get_label('cancelar')?></span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
                <input type="text" readonly="true" value="{%=file.name%}" class="file_name_input_row" style="display: none"/>
            </p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            <span class="size">Image processor </span>
            <?php            
            $html  = '';
            $html .= '<select class="file_processor">';
            # Default option
            $html .= '<option value="">Without processing</option>';
            if(!empty($file_processor)) foreach ($file_processor as $file_processor_obj) {
                $html .= '<option value="'.$file_processor_obj->function_name.'">';
                $html .= $file_processor_obj->name;
                if(SHOW_DEVELOPER===true) {
                    $html .= " [$file_processor_obj->function_name]";
                }
                $html .= '</option>';
            }
            $html .= '</select>';
            echo $html;
            ?>
        </td>
        <td>
            <span class='target_component_span' data-file_name="{%=file.name%}" data-hashcode="{%=file.name.hashCode()%}" >Target component</span>
            <?php
            #
            #  TARGET
            # 
            $html  = '';
            $html .= '<select class="target_portal_tipo" id="{%=file.name.hashCode()%}">';
            # Default option
            $html .= '<option value="'.$target_portal_tipo.'">';
            $html .= RecordObj_dd::get_termino_by_tipo($target_portal_tipo);
            if(SHOW_DEVELOPER===true) {
                $html .= " [$target_portal_tipo]";
            }
            $html .= '</option>';
            if(!empty($button_properties->additional_component_tipo)) foreach ($button_properties->additional_component_tipo as $current_tipo) {

                # Selected 
                $html .= '<option value="'.$current_tipo.'">';
                $html .= RecordObj_dd::get_termino_by_tipo($current_tipo);
                if(SHOW_DEVELOPER===true) {
                    $html .= " [$current_tipo]";
                }
                $html .= '</option>';
            } 
            $html .= '</select>';
            echo $html;
            ?>
         
        </td>
        <td>
            {% if (file.deleteUrl) { %}
                <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="glyphicon glyphicon-trash"></i>
                    <span><?php echo label::get_label('borrar')?></span>
                </button>
                <input type="checkbox" name="delete" value="1" class="toggle">
            {% } else { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span><?php echo label::get_label('cancelar')?></span>
                </button>
            {% } %}
        </td>
    </tr>

{% } %}
</script>
<?php /*
<script>
	var upload_handler_url = '<?php echo $upload_handler_url ?>';
</script>

<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script src="http://blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>
*/ ?>
</div><!-- /jquery_upload_wrapper -->
