<?php

	# VISUALIZADOR HTML


	print "\n<!-- COMPONENT_INPUT_TEXT_MULTI [tipo:$tipo section_id_matrix:$parent] $label -->";
	
	print "\n<div class=\"css_wrap_component_input_text_multi wrap_component wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-modo=\"{$modo}\"
	data-dato=\"{$dato_json}\"
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}' >";


		# ETIQUETA (LABEL)
		$html_label = component_common_draw::draw_label($this);

		# CONTENIDO (INPUT)
		$html_contenido = '';
		switch($permissions) {

			case 0 :
					$html_contenido .= "";
					break;

			case 1 :
					$html_contenido .= "\n <span class=\"css_span_dato\">$dato</span>";
					break;

			case ($permissions>=2) :					

					# Read only mode (set in propiedades)					
					$read_only = (isset($propiedades->read_only) && $propiedades->read_only==true) ? 'readonly' : null;
					

					foreach ($elements as $name => $format) {
						
						$element_value 	= isset($dato->$name) ? $dato->$name : null;						
						$placeholder 	= $name;
						
						$html_contenido .= "\n<input type=\"text\" class=\"css_component_input_text_multi\" onchange=\"component_input_text_multi.Save(this,event)\"
						name=\"{$name}\"
						value=\"{$element_value}\"
						placeholder=\"{$placeholder}\"
						data-tipo=\"{$tipo}\"
						data-parent=\"{$parent}\"
						data-lang=\"{$lang}\"
						data-section_tipo=\"{$section_tipo}\"
						data-format=\"$format\"
						title=\"$html_title\"						
						$read_only
						tabindex=\"1\"
						/>";
					}	
					

					if(SHOW_DEBUG) {
						#$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";
					}
					break;

		}

		# Prepare content to show in page
		tools::prepare_content($html_contenido);


		# PRINT HTML
		print $html_label;
		print $html_contenido;


	print "\n</div><!-- /css_wrap_component_input_text_multi COMPONENT_INPUT_TEXT_MULTI [tipo:$tipo section_id_matrix:$parent] $label -->\n"; //wrap


?>
