<?php


# AR_DATA
/*
$ar_data['dir_path'] 				= $dir; # /Users/dedalo/media/media_mupreva/image/temp/files/user_1/
$ar_data['file_path'] 				= $dir.$file_name; # /Users/dedalo/media/media_mupreva/image/temp/files/user_1/45001-1.jpg
$ar_data['nombre_fichero'] 			= $ar_value[1]; # 45001-1
$ar_data['nombre_fichero_completo'] = $ar_value[0]; # 45001-1.jpg
$ar_data['numero_inventario']		= intval($ar_value[2]); # 45001
$ar_data['numero_recurso']			= intval($ar_value[3]);	# 1	
$ar_data['extension'] 				= $ar_value[4];	# jpg
$ar_data['nombre_automatico'] 		= $target_component_tipo .'-'. $ar_data['numero_recurso']; # dd750-1
$ar_data['tamano_archivo'] 			= number_format(filesize($ar_data['file_path'])/1024/1024,3) . " MB";
$ar_data['image_url'] 				= DEDALO_ROOT_WEB . "/inc/img.php?s=".$ar_data['file_path'];
$ar_data['image_preview_url'] 		= DEDALO_LIB_BASE_URL . '/component_tools/tool_import_images/foto_preview.php?f='.$ar_data['file_path'];
$colorspace_info  					= shell_exec( MAGICK_PATH . "identify " .$ar_data['file_path']);
$ar_data['image_info'] 				= str_replace($ar_data['file_path'], '', $colorspace_info);
*/

$html  = '';
$html .= "<div class=\"wrapper_preview\">";
#echo css::build_tag(DEDALO_ROOT_WEB.'/lib/bootstrap/3.1.1/css/bootstrap.min.css');
# ITERATE IMAGES ARRAY
# Las agrupamos por número
$ar_image_valid_group=array();


#dump($all_image_files,'$all_image_files');

$ar_used_names = array();
foreach ($all_image_files as $key => $ar_value) {
	
	if(empty($ar_value['numero_inventario']) || $ar_value['numero_inventario']<1) {

		$html .= $ar_value;
		$html .= "<div class=\"info_line alert_icon\">
			El nombre del fichero no es válido (".label::get_label('numero_inventario')."). 
			Por favor renombre el fichero en formato 'xxx-x.jpg' para poder importarlo.
			</div><br>";
		#$html .= " <div class=\"info_line\">Warning: Esta imagen será ignorada en la importación</div>";
	
	}else if(empty($ar_value['numero_recurso']) || $ar_value['numero_recurso']<1) {

		$html .= $ar_value;
		$html .= "<div class=\"info_line alert_icon\">
			El nombre del fichero no es válido (numero_recurso). 
			Por favor renombre el fichero en formato 'xxx-x.jpg' para poder importarlo.
			</div><br>";

	}else{
		
		$numero_recurso		= $ar_value['numero_recurso'];
		$nombre_automatico 	= $ar_value['nombre_automatico'];
		/*
		if(in_array($nombre_automatico, $ar_used_names)) {
			$msg = "<div class=\"info_line alert_icon\">Ya existe un fichero en el lote con este destino: ".$ar_value['numero_recurso'].". 
			Por favor renombre el fichero (por ejemplo como ".$ar_value['codigo']."-".intval($ar_value['numero_recurso']+1).'.'.$ar_value['extension'].") para evitar el conflicto.
			</div><br>";
			$html .= $msg;
		}		
		$ar_used_names[] = $nombre_automatico;
		*/

		# ADD TO FINAL GROUP
		$ar_image_valid_group[][$numero_recurso] = $ar_value;
	}
}
#dump($ar_image_valid_group,'$ar_image_valid_group');

# PREVIEW
foreach ($ar_image_valid_group as $key_number => $ar_group_value) {
	
	# TABLA PREVIEW DE LA IMAGEN CON SUS DATOS
	foreach ($ar_group_value as $key => $ar_data) {
		$rowspan = count($ar_data)+0;
		$html .= "<table class=\"table_preview\">";

		# CAPTION
		#if( isset($ar_data['nombre_automatico']) ) {
		#	$html .= "<caption>".$ar_data['nombre_automatico']."</caption>";
		#}
		if( isset($ar_data['nombre_fichero']) ) {
			$html .= "<caption class=\"tap_title\" data-tap_id=\"".$ar_data['nombre_fichero']."\">".$ar_data['nombre_fichero']."</caption>";
		}

		$html .= "<tbody class=\"tap_content\">";
		foreach ($ar_data as $key => $value) {

			# Skip sensible info for no admins
			if( strpos($key, 'path')!==false && SHOW_DEBUG!==true ) continue;

			
			$html .= "<tr>";

			# COLUMN 1
			$html .= "<td class=\"td_title\">";
			if (SHOW_DEBUG) {
				$html .= label::get_label($key) . ' <span class="debug_info">['.$key.']</span>';
			}else{
				$html .= label::get_label($key);
			}					
			$html .= "</td>";

			# COLUMN 2
			$html .= "<td class=\"td_content\">";
				switch ($key) {
					case 'imagen':						
						foreach ($value as $image_key => $image_value) {
							switch ($image_key) {
								case 'image_url':
									$img_url = $image_value;
									$html .= "<div class=\"image_source\">";
									$html .= " <div class=\"image_source_title\">".label::get_label('original')."</div>";
									$html .= " <a href=\"$img_url\" target=\"_blank\">";
									if( intval(filesize($ar_data['file_path'])/1024/1024,3) >4 ) {
										$html .= "Original is too big image to show (>4 MB)";
									}else{
										$html .= " <img src=\"".$img_url."\"/>";
									}
									$html .= " </a>";
									$html .= "</div>";#/image_source;
									break;
								case 'image_preview_url':
									$img_url = $image_value;
									$html .= "<div class=\"image_source\">";
									$html .= " <div class=\"image_source_title\">".label::get_label('preview')."</div>";
									$html .= " <a href=\"$img_url\" target=\"_blank\"><img src=\"".$img_url."\"/></a>";
									$html .= "</div>";#/image_source;
									break;							
								default:
									# code...
							}							
						}						
						break;
					case 'nombre_fichero':
					case 'nombre_fichero_completo':
						$html .= $value ."  <span class=\"debug_info\">(nombre seguro: ".ltrim($value,'0').")</span>";
						break;
					
					default:
						$html .= $value;
				}
			$html .= "</td>";

			$html .= "</tr>";
		}#end foreach



		# Warning : Avisa de que la imagen de destino existe ya (puede sobreescribirla o no a elección)
		$aditional_path		 = tool_import_images::numero_to_local_path($ar_data['numero_inventario'],2);
		$path_image_original = DEDALO_MEDIA_BASE_PATH.DEDALO_IMAGE_FOLDER.'/original'. $aditional_path.'/'.$ar_data['numero_inventario'].'-'.$ar_data['numero_recurso'].'.'.DEDALO_IMAGE_EXTENSION;
		$url_image_original  = DEDALO_MEDIA_BASE_URL.DEDALO_IMAGE_FOLDER.'/original'. $aditional_path.'/'.$ar_data['numero_inventario'].'-'.$ar_data['numero_recurso'].'.'.DEDALO_IMAGE_EXTENSION;
			#dump($path_image_original,'$path_image_original');
		if ( file_exists($path_image_original) ) {
			$html .= "<tr class=\"tr_warning\">";
			$html .= "<td class=\"td_title td_warning\">";
			$html .= "<div>Atención</div>";
			$html .= "</td>";
			$html .= "<td class=\"td_content \">";
			$html .= "<div class=\"info_line alert_icon\">La imagen de destino ya existe. Al importar, sobreescribirá la existente</div>";
			#$html .= "<img class=\"\" src=\"$url_image_original\"/>";

			$html .= "<div class=\"image_source\">";
			$html .= " <div class=\"image_source_title\">Imagen de calidad 'original' actual</div>";
			$html .= " <a href=\"$url_image_original\" target=\"_blank\">";
			if( intval(filesize($ar_data['file_path'])/1024/1024,3) >4 ) {
				$html .= "Original is too big image to show (>4 MB)";
			}else{
				$html .= " <img src=\"".$url_image_original."\"/>";
			}
			$html .= " </a>";
			$html .= "</div>";

			# Como el navegador no mostrará imágenes distintas a jpg, visualizamos la version convertida a jpg
			if ( strtolower($ar_data['extension'])!=DEDALO_IMAGE_EXTENSION) {
				$url_image_original_jpg = DEDALO_MEDIA_BASE_URL.DEDALO_IMAGE_FOLDER.'/original'. $aditional_path.'/'.$ar_data['numero_inventario'].'-'.$ar_data['numero_recurso'].'.'.DEDALO_IMAGE_EXTENSION;
				$html .= "<div class=\"image_source\">";
				$html .= " <div class=\"image_source_title\"> Versión ".DEDALO_IMAGE_EXTENSION."</div>";
				$html .= " <a href=\"$url_image_original_jpg\" target=\"_blank\"><img src=\"".$url_image_original_jpg."\"/></a>";
				$html .= "</div>";
			}

			$html .= "</td>";
			$html .= "</tr>";
		}
		


		$html .= "</tbody>";
		$html .= "</table>";

	}
}

if(empty($ar_image_valid_group)) {
	$html .= "<div class=\"info_line alert_icon\">Seleccione al menos un fichero en el apartado 'Gestión de archivos'</div>";			
}else{

	$html .= "<form class=\"form_preview\" action=\"\" method=\"post\">";
	
	$html .= "  <input type=\"hidden\" name=\"process\" value=\"1\">";
	$html .= "  <span>Procesar: </span><input type=\"submit\" class=\"css_button_generic submit_import\" value=\"OK\">";

		# SELECT QUALITY
		$html .= label::get_label('directorio_de_destino').": ";
		$html .= "<select name=\"quality\" class=\"quality_selector\">";
		foreach ($ar_quality as $current_quality) {
			
			if($current_quality == $default_target_quality) {
				$html .= "<option selected=\"selected\" >$current_quality</option>";
			}else{
				$html .= "<option>$current_quality</option>";
			}		
		}
		$html .= "</select>";
		if(!in_array($default_target_quality, $ar_quality)) {
			$html .= "<div class=\"warning\"> Sorry: Current target quality ($default_target_quality) not invalid</div>";
		}

		# DELETE IMAGES AFTER IMPORT OPTION
		if(SHOW_DEBUG) {
			$html .= label::get_label('eliminar_imagenes_tras_la_importacion').": ";
			$html .= " <select name=\"delete_after\" class=\"quality_selector\" >";
			$html .= " <option value=\"si\" selected=\"selected\" >".label::get_label('si')."</option>";	
			$html .= " <option value=\"no\" >".label::get_label('no')."</option>";	
			$html .= "</select>";
		}else{
			$html .= "  <input type=\"hidden\" name=\"delete_after\" value=\"si\">";
		}	

	$html .= "</fom>";
}#/if(empty($ar_image_valid_group)) {



$html .= "</div>";#end wrapper_preview

print $html;
/*
if($_POST)
$html .= dump($_POST);

echo html_page::get_html($html);
exit();
*/
?>