<?php

	# VISUALIZADOR HTML	
	
	$html    = "";

	$html .= "<table class=\"import_options\">";
	
		$html .= "<tr>";
			$html .= "<td>";
			$html .= "campo_destino";
			$html .= "</td>";
			$html .= "<td>";
			$html .= "$campo_destino_name"; if(SHOW_DEBUG) $html .= " [$campo_destino]";
			$html .= "</td>";
		$html .= "</tr>";

		if(!empty($portal_destino)) {
		$html .= "<tr>";
			$html .= "<td>";
			$html .= "portal_destino";
			$html .= "</td>";
			$html .= "<td>";
			$html .= "$portal_destino_name"; if(SHOW_DEBUG) $html .= " [$portal_destino]";
			$html .= "</td>";
		$html .= "</tr>";	
		}

		$html .= "<tr>";
			$html .= "<td>";
			$html .= "campo_referencia_seccion";
			$html .= "</td>";
			$html .= "<td>";
			$html .= "$campo_referencia_seccion_name"; if(SHOW_DEBUG) $html .= " [$campo_referencia_seccion]";
			$html .= "</td>";
		$html .= "</tr>";

		$html .= "<tr>";
			$html .= "<td>";
			$html .= "calidad prederminada";
			$html .= "</td>";
			$html .= "<td>";
			$html .= "$default_target_quality";
			$html .= "</td>";
		$html .= "</tr>";

	$html .= "</table>";


	
	$html .= "</select>";
	if(!in_array($default_target_quality, $ar_quality)) {
		$html .= "<div class=\"warning\"> Sorry: Current target quality ($default_target_quality) not invalid</div>";
	}

	# PRINT HTML
	print $html;
	
?>