<?php

	# VISUALIZADOR HTML	
	
	
	print "\n<!-- TEXT AREA [tipo:$tipo section_id_matrix:$parent] -->";
	print "\n<div class=\"wrap_component css_wrap_text_area wrap_component_{$tipo}\" 
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-dato=\"{$dato_raw}\"
	data-component_name=\"{$component_name}\"
	>";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato\"> No access here (text_area)! </span>";	
					break;
						
		case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato\">$dato</span>";
					break;	
						
		
		case ($permissions>=2)	:
		
					$html_contenido .= "\n <textarea class=\"css_text_area\" 
					id=\"{$identificador_unico}\" name=\"{$tipo}_{$parent}\" 
					data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-section_tipo=\"{$section_tipo}\" data-parent=\"{$parent}\" 
					title=\"$html_title\">$dato</textarea>";
					#$html_contenido .= "\n <span  class=\"css_span_ejemplo \">$ejemplo</span>";
					#$html_contenido .= "\n <span class=\"css_span_log\"></span>";
		
					if($permissions==3){
						$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
					}
					break;
					
					
							
	}
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div>\n\n"; //wrap
?>