<?php

	# VISUALIZADOR HTML	

	print "<div class=\"wrap_component css_wrap_text_area tooltip_active\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato='".json_encode($dato)."' ";
	print 'title="'.search_development2::search_options_title( $this->search_operators_info() ).'" ';
	print ">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch($permissions) {
			
		case 0	:	$html_content .= "<span class=\"css_span_dato\"> No access here (text_area)! </span>";	
					break;
						
		case 1	: 	$html_content .= "<span class=\"css_span_dato\">$dato</span>";
					break;	
						
		
		case ($permissions>=2)	:
		
					$html_content .= "<textarea class=\"css_text_area\" ";
					$html_content .= "id=\"{$identificador_unico}\" name=\"{$tipo}\" ";
					$html_content .= "data-tipo=\"{$tipo}\" ";
					$html_content .= "title=\"$html_title\">$dato</textarea>";
					break;
				
	}
	
	
	# PRINT HTML
	print $html_label;
	print $html_content;
	
	
	print "</div>"; //wrap
?>