<?php

	# VISUALIZADOR HTML	
	
	print "<!-- TEXT AREA [tipo:$tipo section_id_matrix:$tipo] -->";
	print "\n<div class=\"css_wrap_text_area_tm\" id=\"wrap_{$identificador_unico}\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato\"> No access here (text_area)! </span>";
					break;
						
		case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato\">$dato</span>";
					break;	
						
		case ($permissions>=2)	:
		
					$html_contenido .= "\n <textarea class=\"css_text_area\" 
					id=\"{$identificador_unico}\" name=\"{$tipo}_{$tipo}_tm\" 
					data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" 
					value=\"{$dato}\" 
					title=\"$html_title\" disabled >$dato</textarea>";
							
					if(SHOW_DEBUG) {
						$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
					}
					break;				
	}
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	print "\n</div>\n\n"; //wrap
	
?>

<script type="text/javascript">
$(function() {
	// autoesize text area with jquery plugin
	$('<?php echo "#{$identificador_unico}" ?>').css('max-height','300px').autosize();		
});							
</script>