<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">
<head>
<?php 
print css::build_tag(DEDALO_LIB_BASE_URL .'/diffusion/'.get_class($this).'/css/'.get_class($this).'.css');
print js::build_tag(DEDALO_LIB_BASE_URL  .'/diffusion/'.get_class($this).'/js/'.get_class($this).'.js');
?>
</head>

<body>
<?php
$content = '';

# CONTAINER DIV
$container_style = "width:{$this->image_widht}px;height:{$this->image_height}px;";
$content .= "<div class=\"diffusion_mupreva_ficha_fm_container_custom\" style=\"$container_style\" >";

	#
	# IMAGEN CUSTOM
		$imagen_custom_html='';
		$current_diffusion_obj = $ar_imagen_custom_diffusion_obj;
			#dump($current_diffusion_obj,'current_diffusion_obj');

		# VARS
		$label 	= $current_diffusion_obj->label;
		$valor 	= $current_diffusion_obj->columns['valor'];
			#dump($valor,'$valor');

		# FORMATO DEL ARRAY RECIBIDO
		# [valor] => Array
	    #    (
	    #        [247224] => Array
	    #            (
	    #                [dd750] => dd750-2454
	    #                [dd1110] => /2
	    #                [dd851] => 28061-1
	    #            )
	    #    )
		#dump($this->shoot,'$this->shoot');	    
	    if(count($valor)<$this->shoot) {

	    	$imagen_custom_html .= '';# "<div class=\"warning\"> Sorry. Shoot $this->shoot not exist </div>";

	    }else{

		    $current_shoot = 0;
			foreach ($valor as $section_id => $ar_components_data) {
				
				# Si $this->shoot no es el predeterminado (0) numeramos el disparo actual para identificar el deseado
				if ($this->shoot>0) {
					$current_shoot++;
				}
				

				# Skip any shoot distinct of desired shoot defined in get
				if($current_shoot!=$this->shoot) continue;			


				$SID='';
				if (empty($ar_components_data[$this->campo_imagen_path]) && empty($ar_components_data[$this->campo_imagen_nombre])) {
					$SID .= $ar_components_data[$this->campo_imagen_default_nombre];
				}else{
					# Path
					if( !empty($ar_components_data[$this->campo_imagen_path]) ) {
						$SID .= $ar_components_data[$this->campo_imagen_path];
					}
					# File name
					if( !empty($ar_components_data[$this->campo_imagen_nombre]) ) {
						if(!empty($ar_components_data[$this->campo_imagen_path])) $SID .= '/';
						$SID .= $ar_components_data[$this->campo_imagen_nombre];
					}
				}
					
				# IMG
				$image_full_url = $this->get_url_full( $SID );		
				$img_url 		= DEDALO_IMAGE_FILE_URL . "?m=image&SID=$SID&w={$this->image_widht}&h={$this->image_height}&fx=";
				#$imagen_custom_html .= "\n <div class=\"img_identificativa\">";
				$imagen_custom_html .= "\n <a href=\"$image_full_url\" target=\"_blank\">";
				$imagen_custom_html .= "\n  <img src=\"$img_url\" class=\"img_identificativa_\" />";
				$imagen_custom_html .= "\n </a>";
				#$imagen_custom_html .= "\n </div>";
					#dump($img_url,'img_url');

			}#end foreach ($valor as $section_id => $ar_components_data)
	    }
	    

		$content .= $imagen_custom_html;	
	

$content .= "\n</div>";#end diffusion_mupreva_ficha_fm_container

print $content;
?>

</body>
</html>