<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 			$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_ref'])) 				$ar_css['css_ref']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 		$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))		$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_autocomplete']))			$ar_css['css_wrap_autocomplete']='';
		
	
	print "\n<!-- COMPONENT_AUTOCOMPLETE [tipo:$tipo id_matrix:$id] $label -->";
	print "\n<div class=\"css_wrap_autocomplete wrap_component {$ar_css['css_wrap_autocomplete']}\" id=\"{$id_wrapper}\" 
	data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-parent=\"{$parent}\" data-modo=\"{$modo}\" data-dato=\"{$valor_string}\" data-component_name=\"{$component_name}\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." (ref)</span>";
					break;
						
		case 1	: 	$html_contenido .= $valor;
					break;	
						
		
		case ($permissions>=2)	:
		
					# VALOR . STRING RESOLVED TO SHOW
					$html_contenido .= "\n <div class=\"css_autocomplete_valor\">$valor</div>";


					# INPUT DATA HIDDEN
					$html_contenido .= "\n <input class=\"css_autocomplete_dato_hidden\" type=\"text\" 
						name=\"{$input_name}\" 
						data-tipo=\"{$tipo}\" data-id_matrix=\"{$id}\" data-parent=\"{$parent}\" data-lang=\"{$lang}\" data-tipo_to_search='{$referenced_tipo}' data-dato_in_db='{$dato}'
						value=\"{$dato}\"						
						title=\"$html_title\"
						disabled=\"disabled\"
						/>";


					# INPUT SEARCH FIELD
					$html_contenido .= "\n <input class=\"css_autocomplete_search_field\" type=\"text\" placeholder=\"Search..\"
						name=\"{$input_name}\" 
						data-tipo_to_search='{$referenced_tipo}'
						onclick=\"component_autocomplete.activate(this)\"
						/>";


					# BTN DELETE
					$html_contenido .= "\n <div class=\"div_image_link link css_autocomplete_button_delete\" 
					data-tipo=\"{$tipo}\"
					title=\"$label $id\"
					onclick=\"component_autocomplete.delete(this)\"></div>";
					
					
			if($permissions==3)
					
					$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$debugger}</span>";	
				
											
	}

	# Prepare content to show in page
	tools::prepare_content($html_contenido);
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	
	print "\n</div><!-- /css_wrap_component_autocomplete COMPONENT_AUTOCOMPLETE [tipo:$tipo id_matrix:$id] $label -->\n\n"; //wrap
?>