<?php

	# VISUALIZADOR HTML
	
	
	if(isset($_REQUEST[$tipo])) $dato = $_REQUEST[$tipo];		#var_dump($_REQUEST[$tipo]);
	
	
	#print "\n<!-- SELECT [tipo:$tipo section_id:$parent] $label -->";

	print "\n<div class=\"css_wrap_select\" >";

	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "";
					break;						
		
		case ($permissions>=1) :

					# COMPARISON OPERATORS
					if (isset($ar_comparison_operators)) {
					$html_contenido .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);
					}					

					
					# SELECT
					$html_contenido .= "\n <select class=\"css_select\" name=\"{$tipo}\" data-tipo=\"{$tipo}\" title=\"$html_title\"> ";					
						if(empty($dato)) {
							$checked = 'selected';
						}else{
							$checked = "";
						}
						$html_contenido .= "\n <option value=\"\" {$checked}> </option>";
						foreach ($ar_list_of_values->result as $value => $rotulo) {
							
							if( $dato == $value) {
								$checked = 'selected';
							}else {
								$checked = "";
							}
							$html_contenido .= "\n <option value='$value' {$checked}> {$rotulo}</option>";							
						}
					$html_contenido .= "\n </select>";
					

					# LOGICAL OPERATORS
					if (isset($ar_logical_operators)) {
					$html_contenido .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);
					}								
					break;
										
	}
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;	
	
	
	print "\n</div><!-- /css_wrap_select -->\n\n"; //wrap
?>