<?php

	# VISUALIZADOR HTML	
	
	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in', $modo, $lang);

	print "<div class=\"wrap_component css_wrap_autocomplete wrap_autocomplete_{$modo}\" id=\"{$id_wrapper}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	#print "data-ar_target_section_tipo='{$ar_target_section_tipo_json}' ";
	#print "data-tipo_to_search='{$tipo_to_search}' ";
	#print "data-modo=\"{$modo}\" ";
	#print "data-from_modo=\"{$from_modo}\" ";
	#print "data-dato='{$dato_json}' ";
	#print "data-component_name=\"{$component_name}\" ";
	#print "data-component_info='{$component_info}' ";
	print ">";
	
	# ETIQUETA (LABEL)
	#$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch(true) {
			
		case ($permissions===0):
			
			$html_content .= "";
			break;
		
		case ($permissions===1):
			
			$html_content .= $valor;
			break;

		case ($permissions>=2):


			

			#
			# INDIRECT COMPONENTS
			$html_content .= "<ul>";
			
			foreach ((array)$dato as $current_locator) {
								
				foreach ($ar_related_component_tipo as $current_component_tipo) {
					
					# Skip propiedades defined skip_components
					if (in_array($current_component_tipo, $this->context->skip_components)) {
						continue;
					}

					$current_section_tipo 	= $current_locator->section_tipo;
					$current_section_id 	= $current_locator->section_id;
					$current_modelo_name 	= RecordObj_dd::get_modelo_name_by_tipo($current_component_tipo,true);

					$current_component 		= component_common::get_instance($current_modelo_name,
																			 $current_component_tipo,
																			 $current_section_id,
																			 'edit',
																			 DEDALO_DATA_LANG,
																			 $current_section_tipo);

					$value = $current_component->get_html();
					#$value .= json_encode($current_locator);
					
					$html_content .= "<li>";
					$html_content .= $value;
					$html_content .= "</li>";
				}
			}			
			
			$html_content .= "</ul>";

			break;
	}			
	
	# Prepare content to show in page
	tools::prepare_content($html_content);
	
	# PRINT HTML
	print $html_content;
	
	
	echo "</div>"; //css_wrap_autocomplete
	

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out', $modo, $lang);
?>