<?php

	# VISUALIZADOR HTML	
	
	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in', $modo, $lang);

	print "<div class=\"wrap_component css_wrap_autocomplete wrap_portal_list\" id=\"{$id_wrapper}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-ar_target_section_tipo='{$ar_target_section_tipo_json}' ";
	print "data-tipo_to_search='{$tipo_to_search}' ";
	print "data-modo=\"{$modo}\" ";
	print "data-from_modo=\"{$from_modo}\" ";
	print "data-dato='{$dato_json}' ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-component_info='{$component_info}' ";
	print ">";
	
	# ETIQUETA (LABEL)
	#$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0:	
			$html_contenido .= "";
			break;
		
		case 1:									
			$html_contenido .= $valor ;
			break;

		case ($permissions>=2)	:
			# VALOR . STRING RESOLVED TO SHOW

			#$html_contenido .= $valor ;
			#break;

				if($modo =='portal_list'){
					if(empty($ar_valor)){
						$edit_class = 'css_autocomplete_ul_edit_in_portal';
					}else{
						$edit_class = 'css_autocomplete_ul';
					}
					$html_contenido .= " <ul class=\"$edit_class\" onclick=\"component_common.change_mode_component(this, '$modo','edit')\">";
				}else{
					$html_contenido .= " <ul>";
				}
				
				foreach ($ar_valor as $value_obj) {
					
					$value = $value_obj->label;

					$html_contenido .= "<li>";
						$html_contenido .= $value;
					$html_contenido .= "</li>";
				}
				$html_contenido .= "</ul>";

			break;					
	}			
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);
	
	# PRINT HTML
	print $html_contenido;
	
	
	echo "</div>"; //css_wrap_autocomplete
	

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out', $modo, $lang);
?>