<?php

	$html='';
	$html .= "<div class=\"component_autocomplete_new_element\" data-type=\"component_autocomplete_new_element\" >";

		$component_context = new stdClass();
			$component_context->context_name = 'component_autocomplete';

		#
		# INPUTS
		foreach ($ar_terminos_relacionados as $current_tipo) {

			$modelo_name = RecordObj_dd::get_modelo_name_by_tipo($current_tipo,true);
			
			if ($modelo_name=='section') continue;

			if ($modelo_name!='component_input_text') {
				if(SHOW_DEBUG) {
					trigger_error("Current component is not 'component_input_text'. Ignoring component");
				}
				//continue;
			}
			$title = RecordObj_dd::get_termino_by_tipo($current_tipo,$lang,true);
			#html .= $title;
			$component =  component_common::get_instance($modelo_name,
														 $current_tipo,
														 $parent= DEDALO_SECTION_ID_TEMP,
														 'edit',
														 $lang,
														 $target_section_tipo);
			$component->set_context($component_context);
				//dump($component, ' component ++ '.to_string());

			$html .= $component->get_html();
				
			
			
			//$html .= " <input type=\"text\" class=\"\" name=\"$current_tipo\" data-tipo=\"{$current_tipo}\" value=\"\" placeholder=\"$title\" /> ";
		}

		#
		# BUTTON NEW
		$html .= "<input type=\"button\" ";
		$html .= "class=\"css_button_generic button_submit_new_element\" ";
		$html .= "data-target_section_tipo=\"$target_section_tipo\" ";
		$html .= "value=\"".label::get_label('nuevo')."\" ";
		$html .= "onclick=\"component_autocomplete.submit_new_element(this)\" ";
		$html .= "/>";
		
		if(SHOW_DEBUG===true) {
			#$html .= " <span class=\"note\">[$target_section_tipo]</span>";
		}
		

	$html .= "</div>";


	echo $html;
?>