<?php

	# VISUALIZADOR HTML	
	$html ='';
	
	$html .= "<div class=\"descriptors_list\">";

	# Button
	$html .= "<div class=\"descriptors_button\" onclick=\"descriptors.load_terms(this)\" ";
	$html .= "data-component_tipo=\"$component_tipo\" ";
	$html .= "data-section_tipo=\"$section_tipo\" ";
	$html .= "data-section_id=\"$parent\" ";
	$html .= "data-component_portal_tipo=\"$component_portal_tipo\" ";
	$html .= "data-component_text_area_tipo=\"$component_text_area_tipo\" ";
	$html .= ">".label::get_label('terminos')."</div>";

	# Ajax container
	$html .= "<div class=\"descriptors_container\"></div>";

	$html .= "</div>";

	print $html;
?>