<?php
	# VISUALIZADOR HTML		
	
	#print "\n<!-- BUTTON IMPORT [tipo:$tipo] -->";	
	
	# CONTENIDO (INPUT)
	$html_content = '';	
	
	switch(true) {
			
		case $permissions===0	:
				$html_content .= "";
				break;
						
		case $permissions===1	:
				$html_content .= "";
				break;	
						
		case ($permissions>=2)	:

				$html_content .= "<div class=\"css_button_generic css_button_import link\" onclick=\"tool_common.open_tool_import(this)\"
				data-tipo=\"{$tipo}\"
				data-section_tipo=\"{$section_tipo}\"
				data-target_section_tipo=\"{$target_section_tipo}\"
				data-t=\"{$t}\"
				data-tool_name=\"{$tool_name}\"
				data-context_name=\"{$context_name}\"
				data-custom_params='{$custom_params}'
				title=\"$html_title\">";
				$html_content .= $label;
				$html_content .= "</div>";
	}
	
	
	# PRINT HTML
	print $html_content;	
?>