<?php

	# VISUALIZADOR HTML	
	
	
	print "\n<!-- html_file [tipo:$tipo section_id_matrix:$parent] $label -->";

	print "\n<div class=\"wrap_component css_wrap_html_file wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\" data-lang=\"{$lang}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-modo=\"{$modo}\"
	data-dato=\"{$valor}\"
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";
	
		
		# ETIQUETA (LABEL)
		$html_label = component_common_draw::draw_label($this);
		
		# CONTENIDO (INPUT)
		$html_contenido = '';
		switch($permissions) {
				
			case 0 :	$html_contenido .= "";
						break;
							
			case ($permissions>=1) :
			
						# html_file THUMB
						$html_contenido .= "\n <div class=\"html_file_info\" >";
						#$html_contenido .= to_string($dato) ;
						$html_contenido .= $html_file_id ;
						if(file_exists($html_file_path)) {
							$html_contenido .= " <a href=\"$html_file_url\" target=\"_blank\"> Open file </a> ";
						}else{
							$html_contenido .= " No file ";
							if(SHOW_DEBUG) {
								$html_contenido .= " - Filepath:" . $html_file_path;
							}
						}
						
						$html_contenido .= "\n </div>";		
						
				if($permissions==3)		
						$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
												
		}

		# Prepare content to show in page
		tools::prepare_content($html_contenido);	
		

		# PRINT HTML
		print $html_label;
		print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_html_file [tipo:$tipo section_id_matrix:$tipo] $label -->\n"; //wrap


?>