<?php

	# VISUALIZADOR HTML	

	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	
			$html_contenido .= "\n <span class=\"css_span_dato\"> No access here (text_area)! </span>";	
			break;
						
		
		case ($permissions>=1)	:			
			
			# Fragment info div
			$html_contenido .= "<div class=\"fragment_id_info\"
			data-section_tipo=\"{$section_tipo}\"
			data-parent=\"$parent\"
			data-tipo=\"$tipo\"
			data-caller_id=\"$caller_id\"
			data-rel_locator='$rel_locator'>";
			$html_contenido .= "<b>".ucfirst(label::get_label('etiqueta'))." $tag_value </b>";
			$html_contenido .= "</div>";			


			# TAG STATE SELECTOR
			$html_contenido .= "\n <div class=\"wrap_tag_state_selector\">";

				#
				# CURRENT TAG STATE SELECTOR
				#
				$name = 'tag_state_selector_' .$tag;	
				$ar_states = array(	'n'=> label::get_label('etiqueta_normal'), // Normal
									'd'=> label::get_label('etiqueta_borrada'), // Deleted
									'r'=> label::get_label('etiqueta_revisar') // To review
								  );
				$html_contenido .= ucfirst(label::get_label('estado')) ;
				$html_contenido .= "<select class=\"tag_state_selector\" name=\"$name\"
				data-tag=\"$tag\"
				onchange=\"component_text_area.change_tag_state(this)\">";			
				#$html_contenido .= "\n <option value=\"\"></option>";
				foreach ($ar_states as $key => $value) {

					$selected = ($tag_state==$key) ? " selected=\"selected\" " : '';

					$html_contenido .= "\n <option value=\"$key\" $selected >";					
					$html_contenido .= $value;
					$html_contenido .= "</option>";

				}			
				$html_contenido .= "\n</select>\n";

			$html_contenido .= "</div><!-- /wrap_tag_state_selector -->";
			

			# BUTTON DELETE TAG
			$html_contenido .= "\n <div class=\"div_delete_tag\">";

				$html_contenido .= " <div class=\"icon_bs tool_indexation_delete_icon link\"
				data-tipo=\"{$tipo}\"
				data-section_tipo=\"{$section_tipo}\"
				data-parent=\"{$parent}\"
				data-lang=\"{$lang}\"
				data-tag=\"{$tag}\"
				data-rel_locator='{$rel_locator}'
				title=\"Delete tag\"
				onclick=\"tool_indexation.delete_tag(this)\"></div>";

				$html_contenido .= " Delete tag";

			$html_contenido .= "</div>";//end div_delete_tag	


			# BUTTON CLOSE
			$html_contenido .= "\n <div class=\"icon_bs tool_indexation_show_fragment link\"
			data-tab_id=\"indexation_fragment\"
			onclick=\"tool_indexation.toggle_selected_fragment(this);\"></div>";
			

			# TEXT SELECTED FRAGMENT
			$html_contenido .= "\n <div class=\"selected_fragment\">{$fragment_text}</div>";			
	}	


	# Prepare content to show in page



	# TEXT SELECTED FRAGMENT
	$html_contenido .= "\n <div class=\"terminos_list\">";
	$html_contenido .= "\n   <div class=\"terminos_list_title\">".label::get_label('descriptores')."</div>";
	$html_contenido .= 		 $component_text_area_terminos_list_html;
	$html_contenido .= "\n </div>";



	# PRINT HTML
	print $html_contenido;
		

	
?>