<?php
	

	# VISUALIZADOR HTML

	$html    = "<!-- TOOL PAGE [tipo:$tipo] -->";	
	#$html   .= "<div class=\"wrap_tool wrap_tool_indexation_page\" >";	
	
	#
	# HEADER TOOL
	$header_html='';
	$header_html .= "<div class=\"header_tool\">";

		#
		# INFO
		$header_html .= "<div class=\"header_info\">";
		$header_html .= "ID $section_id";
		$header_html .= "</div>";

		#
		# TOP_ID SELECTOR		
		if (isset($inverse_locators) && is_array($inverse_locators)) {
			$top_id_selector  = '';
			$top_id_selector .= "<div class=\"top_id_selector\">";
			$top_id_selector .= "<label>".label::get_label('enfoque')."</label>";
			$top_id_selector .= "<select id=\"top_id_selector\" onchange=\"tool_indexation.update_top_id(this)\" >";
			#$top_id_selector .= " <option></option>";
			$ar_inverse = $this->get_ar_inverse($inverse_locators);
			foreach ($ar_inverse as $current_id => $current_name) {
				$top_id_selector .= " <option value=\"$current_id\">$current_name</option>";
			}
			$top_id_selector .= "</select>";
			$top_id_selector .= "</div>";
			$top_id_selector .= "<script>tool_indexation.update_top_id(document.getElementById('top_id_selector'));</script>";
			$header_html .= $top_id_selector;
		}		

		#
		# COMPONENT STATE
		$header_html .= $component_state_html;

	$header_html .= "</div>";//end header_tool
	$html .= $header_html;


	#
	# CONTENT 
	$html .= "<div id=\"indexation_container\" class=\"container text_shadow_inset\" >";		

		#
		# LEFT SIDE
		$html   .= "<div id=\"left_side\" class=\"split split-horizontal left_side\">";	
	
			#
			# TESAURO (IFRAME)
			#$html   .= "<div class=\"indexation_page_tesauro\">";
			$html 	.= " <iframe id=\"tesauro_frame\" name=\"tesauro_frame\" class=\"tesauro_frame\" src=\"{$tesauro_url}\" ></iframe>";
			#$html   .= "</div>";
		
		$html   .= "</div>";#end left_side


		#
		# RIGHT SIDE
		$html   .= "<div id=\"right_side\" class=\"split split-horizontal right_side\">";
		
			#
			# TEXT (TEXT AREA)
			$html   .= "<div class=\"indexation_page_text\">";
			$html 	.= $component_text_area_html;
			$html   .= "</div>";			
			
			#
			# TERM LIST
			$html   .= "<div id=\"indexation_page_list\" class=\"indexation_page_list\">";
			$html 	.= label::get_label('seleccione_una_etiqueta_para_indexar') . ' <br>';
			$html 	.= label::get_label('para_crear_un_fragmento');
			$html   .= "</div>";
			
			$html .= "<div id=\"inspector_log\" class=\"tool_transcription_inspector_log\"> </div>";
			
		$html   .= "</div>";#end right_side



	
	$html .= "</div><!-- /container -->";
	#$html .= "</div><!-- /wrap_tool -->"; //wrap_tool

	
	# INSPECTOR LOG TOOL
	$html .= "<div id=\"inspector_log\" class=\"tool_transcription_inspector_log\"> </div>";
	/**/
	$html .= "<script>
	 Split(['#left_side', '#right_side'], {
		minSize: '40%'
    });
	</script>";
	

	echo $html;
		
?>