<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 			$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_button_search'])) 		$ar_css['css_button_search']='';	
	if(!isset ($ar_css['css_wrap_button_search']))	$ar_css['css_wrap_button_search']='';
	if(!isset ($ar_css['css_span_debugger']))		$ar_css['css_span_debugger']='';	
	
	
	print "\n<!-- BUTTON SEARCH [tipo:$tipo id_matrix:$id] -->";
	print "\n<div class=\"css_wrap_button_search {$ar_css['css_wrap_button_search']}\">";
	
	# ETIQUETA (LABEL)
	//$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." (button_search)</span>";
					break;
						
		case ($permissions>=1)	:
		
					$html_contenido .= "\n <input class=\"css_button_search {$ar_css['css_button_search']}\" type=\"submit\" onclick=\"section_list.Search(this.form)\" 
					data-tipo=\"{$target_tipo}\" value=\"$label\" title=\"$html_title\" />";

					#if(empty($target_tipo)) $html_contenido .= " Error tipo empty";
											
	}
	
	
	# PRINT HTML
	print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_button_search -->\n\n"; //wrap
?>