<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS	
	if(!isset ($ar_css['css_button_search'])) 		$ar_css['css_button_search']='';	
	if(!isset ($ar_css['css_wrap_button_search']))	$ar_css['css_wrap_button_search']='';
	
	
	print "\n<!-- BUTTON SEARCH [tipo:$tipo id_matrix:$id] -->";
	print "\n<div class=\"css_wrap_button_search {$ar_css['css_wrap_button_search']}\">";
	
	# ETIQUETA (LABEL)
	//$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	
	switch($permissions) {
			
		case 0	:	$html_contenido .= "";
					break;
						
		case ($permissions>=1)	:
		
					$html_contenido .= "\n <input class=\"css_button_search {$ar_css['css_button_search']}\" type=\"button\" onclick=\"section_list.Search(this.form)\" 
					data-tipo=\"{$target_tipo}\" value=\"$label\" title=\"$html_title\" />";
											
	}
	
	
	# PRINT HTML
	print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_button_search -->\n\n"; //wrap
?>