<?php

	# VISUALIZADOR HTML	
	
	
	
	#print "<!-- BUTTON SEARCH [tipo:$tipo id_matrix:$id] -->";

	print "<div class=\"css_wrap_button_search\">";
	
	# ETIQUETA (LABEL)
	//$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	
	switch($permissions) {
			
		case 0	:	$html_contenido .= " <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." (button_search)</span>";
					break;
						
		case ($permissions>=1)	:
		
					$html_contenido .= " <input class=\"css_button_search\" type=\"button\" onclick=\"search.Search(this.form)\" 
					data-tipo=\"{$target_tipo}\" value=\"$label\" title=\"$html_title\" />";
											
	}	
	
	# PRINT HTML
	print $html_contenido;
	
	
	print "</div>"; //wrap
?>