<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width">
	<link rel="shortcut icon" href="../../favicon.ico" />
	<title><?php echo $tipo .' '. $section_id ?></title>
	<style type="text/css">
		.loading {
			opacity: 0.5;
			pointer-events: none;
			transition: opacity 0.25s
		}
		.hide {
			visibility: hidden !important;
			opacity: 0 !important;
			height: 0 !important;
			width: 0 !important;
			padding: 0!important;
			margin: 0!important;
		}
		.debug {
			display: grid;
			grid-template-columns: 1fr 1fr 1fr;
			background-color: #f1f2f3;
			padding: 1em;
			overflow: auto;
		}
		.debug pre {
			z-index: 0;
			outline: 1px solid #cad0d4;
			overflow-wrap: anywhere;
		}
		.debug .total_time {
			position: fixed;
			right:2em;
			top:1em;
		}
	</style>
	<link rel="stylesheet" type="text/css" href="../page/css/main.css?v=<?php echo DEDALO_VERSION ?>">
	<link rel="preload" href="../common/js/environment.js.php" as="script">
	<?php /*
	<link href="<?php echo DEDALO_CORE_URL ?>/common/css/structure.css" rel="stylesheet">
	<link rel="preload" href="../../lib/tinymce/js/tinymce/skins/lightgray/fonts/tinymce.woff" as="font" type="font/woff" crossorigin>
	<link rel="preload" href="../../lib/tinymce/js/tinymce/skins/lightgray/fonts/tinymce-small.woff" as="font" type="font/woff" crossorigin>
	<link rel="modulepreload" href="../common/js/components_list.js?v=<?php echo DEDALO_VERSION ?>">
	*/?>
	<link rel="modulepreload" href="../page/js/page.js">
	<link rel="modulepreload" href="../common/js/data_manager.js">
	<link rel="modulepreload" href="../common/js/event_manager.js">
	<link rel="modulepreload" href="../common/js/instances.js">
	<link rel="modulepreload" href="../common/js/common.js">
	<link rel="modulepreload" href="../common/js/ui.js">
	<link rel="modulepreload" href="../menu/js/menu.js">
	<link rel="modulepreload" href="../section/js/section.js">
	<link rel="modulepreload" href="../section_record/js/section_record.js">
	<link rel="modulepreload" href="../../tools/tool_common/js/tool_common.js">

	<link rel="preload" href="../../lib/tinymce/js/tinymce/tinymce.min.js" as="script">
	<link rel="preload" href="../../lib/tinymce/js/tinymce/skins/lightgray/fonts/tinymce.woff" as="font" type="font/woff" crossorigin>
	<link rel="preload" href="../../lib/tinymce/js/tinymce/skins/lightgray/fonts/tinymce-small.woff" as="font" type="font/woff" crossorigin>
</head>
<body>
	<div id="main" class="hide"></div>
	<div id="debug" class="debug hide"></div>
</body>
<script rel="preload" defer="defer" src="../common/js/environment.js.php"></script>
<script defer="defer" src="../../lib/tinymce/js/tinymce/tinymce.min.js"></script>
<script type="module">
	const t0 = performance.now()

	// page instance
	import {data_manager} from '../common/js/data_manager.js'
	import {get_instance} from '../common/js/instances.js'
	import {dd_console} from '../common/js/utils/index.js'
	( async () => {

		// main CSS add loading
			const main = document.getElementById("main")
				  main.classList.add("loading")

		// page instance
			const page = await get_instance({
				model	: 'page',
				context	: <?php echo json_encode($context, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>
			});

		// page instance build and render
			const build			= await page.build()
			const wrapper_page	= await page.render()

		// main. Add node and restore class
			main.appendChild(wrapper_page)
			main.classList.remove("loading","hide")

		// debug
			if(SHOW_DEBUG===true) {
				// console.log("%c + Page instantiated and rendered total (ms): ", 'background: #000000; color: violet', performance.now()-t0 )
				dd_console(`__Time to Page init, build and render: ${Math.round(performance.now()-t0)} ms`)
			}
	})()
</script>
</html>