<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link href="<?php echo DEDALO_CORE_URL ?>/page/css/main.css?v=<?php echo DEDALO_VERSION ?>" rel="stylesheet">
	<?php /*<link href="<?php echo DEDALO_CORE_URL ?>/common/css/structure.css" rel="stylesheet"> */?>
</head>
<body>
	<div id="main" class="hide"></div>
	<div id="debug" class="debug hide"></div>
</body>
<script rel="preload" defer="defer" src="<?php echo DEDALO_CORE_URL ?>/common/js/enviroment.js.php"></script>
<script defer="defer" src="<?php echo DEDALO_ROOT_WEB ?>/lib/tinymce/js/tinymce/tinymce.min.js"></script>
<link rel="modulepreload" href="<?php echo DEDALO_CORE_URL ?>/common/js/components_list.js?v=<?php echo DEDALO_VERSION ?>">
<script type="module">
	const t0 = performance.now()

	// page instance
	import {get_instance} from '../common/js/instances.js?v=<?php echo DEDALO_VERSION ?>'
	( async () => {

		const main = document.getElementById("main")
		  	  main.classList.add("loading")

		// page instance
			const page = await get_instance({
				model 		: 'page',
				//mode		: <?php echo json_encode($page_options->mode) ?> || 'edit',
				elements 	: <?php echo json_encode($page_options->page_elements) ?>
			})

		// page instance build and render
			const build 		= await page.build()
			const wrapper_page 	= await page.render()

		// main add and restore class
			main.appendChild(wrapper_page)
	 		main.classList.remove("loading","hide")

		// debug
			if(SHOW_DEBUG===true) {
				console.log("+ Page instantiated and rendered total in time ms: ",performance.now()-t0)
			}
	})()
</script>
</html>
