<?php
	
	# VISUALIZADOR HTML
	
	print "<!-- SECTION ROWS EDIT [section_id:$section_id tipo:$tipo] -->";

	print "<div id=\"current_record_wrap\" class=\"records main_section_{$modo}\" ";
	print "data-section_id=\"{$section_id}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-section_info='{$section_info}' ";
	print ">";

		# CONTENT
		$html_contenido  = '';

		#$html_contenido .= "\n<div class=\"css_section_content\" id=\"section_{$identificador_unico}\" >";			
		
			# Fields
			switch($permissions) {
					
				case $permissions===0	:
							$html_contenido .= "<span class=\"css_span_dato\">";
							$html_contenido .= label::get_label('contenido_no_autorizado');
							$html_contenido .= " (Section $tipo - $modo)</span>";
							break;
								
				case ($permissions>=1)	:						

							#
							# RECORD_LAYOUT_HTML		
							$html_contenido .= $record_layout_html;
							break;			
			}	
		

	print $html_contenido;

	print "</div><!-- /records -->";#end main_list

?>