<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_section_list_wrap']))		$ar_css['css_section_list_wrap']='';
	if(!isset ($ar_css['css_span_dato'])) 				$ar_css['css_span_dato']='';;
	
	
	
	print "\n <!-- SECTION RECORDS EDIT [tipo:$tipo modo:$modo] -->";
	print "\n <div class=\"css_section_list_wrap {$ar_css['css_section_list_wrap']}\" id=\"wrap_{$tipo}_{$modo}\" data-options='".json_handler::encode($this->options)."' >";
	
	
	# CONTENIDO 
	$html_contenido  = "\n<div class=\"css_section_group_content tab_content\">";		
	
	
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." </span>";
					break;
						
		case ($permissions>=1) :
			
				#
				# PAGINATOR HTML
				$html_contenido .= $rows_paginator_html;

				#
				# ROWS LIST HTML (ONE RECORD)
				#$html_contenido .= "\n<div class=\"records main_section_{$modo}\">";									
				$html_contenido .= $record_html;
				#$html_contenido .= "\n</div><!-- /records -->";#end main_list



				if(SHOW_DEBUG) {
					#dump($this, ' this 1 ');
					$limit_time=SLOW_QUERY_MS;
					$html_info='';
					#dump($this->rows_obj,"");
					if (isset($this->rows_obj->generated_time['get_records_data'])) {
						$total_list_time = $this->rows_obj->generated_time['get_records_data'] + round(microtime(1)-$start_time,3);
						
						$style='';
						if ($total_list_time>$limit_time) {
							$style = "color:red";
						}		
						$html_info .= "<div style=\"margin:15px;margin-bottom:20px;padding:3px;{$style}\" onclick=\"$(this).children('pre').toggle()\"> Time To Generate section list: ";
						$html_info .= $total_list_time;
						$html_info .= ", get_records_data:".$this->rows_obj->generated_time['get_records_data']." (over {$this->rows_obj->options->full_count} records)";
						$html_info .= ", HTML section edit: ".round(microtime(1)-$start_time,3);
						if (isset($this->rows_obj->generated_time['records_navigator'])) {
							$html_info .= ", records_navigator: ".$this->rows_obj->generated_time['records_navigator'];
						}					
						if (isset($this->rows_obj->generated_time['record'])) {		
							$html_info .= ", record: ".$this->rows_obj->generated_time['record'];
						}
						#dump($this->rows_obj->options->search_options_session_key," ");
						if (isset($this->rows_obj->options->search_options_session_key)) {		
							$html_info .= ", search_options_key: ".$this->rows_obj->options->search_options_session_key;
						}
						$html_info .= ", strQuery:";
						$html_info .= "<pre style=\"display:none\"> ".$this->rows_obj->strQuery ."</pre>";
						$html_info .= "</div>";
						#echo "<div> Time To Generate section list: HTML: ".round(microtime(1)-$start_time,3)."</div>";
							
						$html_contenido .= $html_info;
					}
				}#end if(SHOW_DEBUG)
								
	}
	
	$html_contenido .= "\n</div><!-- /css_section_group_content -->";
	
	
	# PRINT HTML
	print $html_contenido;	
	
	
	print "\n</div><!-- /css_section_list_wrap -->\n\n"; //wrap
?>