<?php

	# VISUALIZADOR HTML	
	
	print "\n <!-- SECTION RECORDS LIST [tipo:$tipo modo:$modo] -->";
	
	print "\n<div class=\"div_main_list\"></div>";
	
	print "\n <div class=\"css_section_list_wrap\" id=\"wrap_{$tipo}_{$modo}\" data-options='".json_handler::encode($this->options)."' >";
	
	
	# CONTENIDO
	$html_contenido='';	
	$html_contenido  .= "\n<div class=\"css_section_group_content tab_content wrap_table_rows_list\">";	
	#$html_contenido  = "\n<div class=\"content_ajax\">";
	
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." </span>";
					break;
						
		case ($permissions>=1)	:

				#$html_contenido .= "\n<div id=\"stats_info\"><!-- Stats content here --></div>";
				
				# SEARCH FILTER
					#$html_contenido .= $rows_search_html;					
				
				# PAGINATOR
				$html_contenido .= $rows_paginator_html;

				# LIST (Search,paginator,rows)
				##$html_contenido .= "\n<div class=\"main_list main_list_{$modo}\">";
				#$html_contenido .= "\n<div class=\"records main_section_{$modo}\">";


					# TABLE
					$html_contenido .= "\n<table class=\"table_rows_list\">"; // css_section_list_table box_shadow_1 box_border_radius_1
					#$html_contenido .= "\n <caption style=\"text-align:left;\"> $tipo </caption>";
					
						# TH TITULOS
						$html_contenido .= '<thead>';
						$html_contenido .= $rows_header_html;
						$html_contenido .= '</thead>';
						
						# TD DATOS
						$html_contenido .= '<tbody>';
						$html_contenido .= $rows_html;
						$html_contenido .= '</tbody>';				
						
					$html_contenido .= "\n</table>";


					# PAGINATOR
					#$html_contenido .= $rows_paginator_html;				
					

				#$html_contenido .= "\n</div><!-- /records -->";#end main_list



				if(SHOW_DEBUG) {
					#dump($this, ' this 1 ');
					$limit_time=SLOW_QUERY_MS;
					$html_info='';
					#dump($this->rows_obj,"");
					$total_list_time = $this->rows_obj->generated_time['get_records_data'] + round(microtime(1)-$start_time,3);
					$style='';
					if ($total_list_time>$limit_time) {
						$style = "color:red";
					}			
					$html_info .= "<div style=\"display:table;margin:15px;margin-bottom:20px;padding:3px;{$style}\" onclick=\"$(this).children('pre').toggle()\"> Time To Generate section list: ";
					$html_info .= $total_list_time;
					$html_info .= ", get_records_data:".$this->rows_obj->generated_time['get_records_data']." (over {$this->rows_obj->options->full_count} records)";
					$html_info .= ", HTML section list: ".round(microtime(1)-$start_time,3);
					if (isset($this->rows_obj->generated_time['rows_paginator'])) {
						$html_info .= ", rows_paginator: ".$this->rows_obj->generated_time['rows_paginator'];
					}			
					if (isset($this->rows_obj->generated_time['rows_header'])) {
						$html_info .= ", rows_header: ".$this->rows_obj->generated_time['rows_header'];
					}
					if (isset($this->rows_obj->generated_time['rows'])) {		
						$html_info .= ", rows: ".$this->rows_obj->generated_time['rows'];
					}
					#dump($this->rows_obj->options->search_options_session_key," ");
					if (isset($this->rows_obj->options->search_options_session_key)) {		
						$html_info .= ", search_options_key: ".$this->rows_obj->options->search_options_session_key;
					}
					$html_info .= ", strQuery:";
					$html_info .= "<pre style=\"display:none\"> ".$this->rows_obj->strQuery ."</pre>";
					$html_info .= "</div>";
					#echo "<div> Time To Generate section list: HTML: ".round(microtime(1)-$start_time,3)."</div>";
						
					$html_contenido .= $html_info;
				}#end if(SHOW_DEBUG)
								
	}
	#$html_contenido  = "\n</div>"; // class=\"content\"
	$html_contenido .= "\n</div><!-- /css_section_group_content -->";
	

	
	# PRINT HTML
	print $html_contenido;	
	
	
	print "\n</div><!-- /css_section_list_wrap -->\n\n"; //wrap
?>