<?php

	# VISUALIZADOR HTML	
	
	if(!isset ($ar_css['css_wrap_tool_upload']))	$ar_css['css_wrap_tool_upload']='';
	if(!isset ($ar_css['css_div_tool_upload']))		$ar_css['css_div_tool_upload']='';
	

	$html    = "\n<!-- TOOL UPLOAD PAGE [tipo:$tipo] -->";	
	$html   .= "\n<div class=\"wrap_tool_upload_page\" >";



		
		# TOP DIV
		$html 	.= "\n<div id=\"tool_upload_top\">";
		$html 	.= " rrrr $tipo ";
		$html 	.= "\n</div><!-- /tool_upload_top -->";

			
	
	$html   .= "\n</div><!-- /wrap_tool_upload_page -->"; //page wrap	


	
	# INSPECTOR LOG TOOL_UPLOAD 
	#$html 	.= "\n<div id=\"inspector_log\" class=\"tool_upload_inspector_log\"> </div>";


	print $html;
		
?>