<?php declare(strict_types=1);
/**
* CLASS COMPONENT_SVG
* Manages Scalable Vector Graphics (SVG) assets stored as disk files.
*
* Responsibilities:
* - Declares the SVG-specific constants for quality names, file extension,
*   allowed upload extensions, media folder, and MIME type.
* - Implements the normalized-quality list (only 'web' for normalized passes;
*   the full ar_quality includes 'original' as well).
* - Constructs media URLs and filesystem paths for SVG files, using the shared
*   path-building machinery inherited from component_media_common.
* - Provides get_file_content() to return the raw SVG XML for inline DOM embedding.
* - Drives the raster thumbnail pipeline (create_thumb via ImageMagick) so list
*   views can show a preview without rendering the full vector.
* - Implements process_uploaded_file(), the last step of the four-step upload chain,
*   which records upload metadata and triggers quality regeneration.
* - Implements update_data_version() for the shared migration framework (no
*   SVG-specific migration cases exist yet; always returns result = 0).
*
* Data shape: the component stores a single-element array in the section 'media'
* column. The sole meaningful entry (data[0]) is a file descriptor object:
*   {
*     "id"                      : 1,
*     "original_file_name"      : "my_drawing.svg",
*     "original_normalized_name": "rsc855_rsc302_1.svg",
*     "original_upload_date"    : { "timestamp": "2025-11-29 10:26:59" }
*   }
* The live renderable-file inventory is NOT stored here; it is rebuilt on demand
* by component_media_common::get_files_info() scanning the disk per quality.
*
* Qualities: DEDALO_SVG_AR_QUALITY = ["original", "web"].
*   - original : byte-for-byte source file as uploaded.
*   - web      : default serving quality (DEDALO_SVG_QUALITY_DEFAULT); normally
*                the same SVG file, placed in a 'web' subdirectory.
*   - thumb    : raster JPG generated by create_thumb() via ImageMagick, used for
*                list-grid previews (not in ar_quality; handled by the base class).
*
* This class is non-translatable; every instance is forced to lg-nolan.
*
* Extends component_media_common (provides path/URL building, upload binding,
*   files-info scan, quality/extension helpers, diffusion value, export atom).
* Implements component_media_interface (the minimal surface all media components
*   must satisfy for shared callers: diffusion, tools, delete/restore, etc.).
*
* @package Dédalo
* @subpackage Core
*/
class component_svg extends component_media_common implements component_media_interface {



	/**
	* GET_AR_QUALITY
	* Return the list of named quality tiers that this component supports.
	*
	* SVG qualities are defined in config as DEDALO_SVG_AR_QUALITY =
	* ["original", "web"]. The 'thumb' raster quality is handled separately
	* by the base class and does not appear in this list.
	*
	* @return array $ar_quality - ordered quality name strings, e.g. ["original","web"]
	*/
	public function get_ar_quality() : array {

		$ar_quality = DEDALO_SVG_AR_QUALITY;

		return $ar_quality;
	}//end get_ar_quality



	/**
	* GET_DEFAULT_QUALITY
	* Return the quality name used for the primary serving copy.
	*
	* Maps to config constant DEDALO_SVG_QUALITY_DEFAULT = "web". The default
	* quality is what get_url() falls back to when no explicit quality is
	* requested, and what most render views display.
	*
	* @return string - "web" (DEDALO_SVG_QUALITY_DEFAULT)
	*/
	public function get_default_quality() : string {

		return DEDALO_SVG_QUALITY_DEFAULT;
	}//end get_default_quality



	/**
	* GET_ORIGINAL_QUALITY
	* Return the quality name for the preserved source copy uploaded by the user.
	*
	* Maps to config constant DEDALO_SVG_QUALITY_ORIGINAL = "original". The
	* original-quality file is the byte-exact file placed by the upload flow;
	* it is never overwritten by normalization or transcoding passes.
	*
	* @return string $original_quality - "original" (DEDALO_SVG_QUALITY_ORIGINAL)
	*/
	public function get_original_quality() : string {

		$original_quality = DEDALO_SVG_QUALITY_ORIGINAL;

		return $original_quality;
	}//end get_original_quality



	/**
	* GET_NORMALIZED_AR_QUALITY
	* Return the subset of qualities that receive a normalized copy during
	* the regenerate / build pipeline.
	*
	* For SVG only the default ('web') quality is included in the normalized set.
	* The 'original' quality is preserved verbatim and does not go through
	* normalization. Callers that need to (re)build derived files — such as
	* component_media_common::regenerate_component() — iterate this list.
	*
	* @return array $normalized_ar_quality - e.g. ["web"]
	*/
	public function get_normalized_ar_quality() : array {

		// use qualities
		$default_quality = $this->get_default_quality();

		$normalized_ar_quality = [$default_quality];

		return $normalized_ar_quality;
	}//end get_normalized_ar_quality



	/**
	* GET_EXTENSION
	* Return the canonical file extension for SVG files stored by this component.
	*
	* Returns the instance-level override ($this->extension) if set — for example
	* when a custom extension was injected at construction — otherwise falls back
	* to the global config constant DEDALO_SVG_EXTENSION = "svg".
	*
	* @return string - e.g. "svg"
	*/
	public function get_extension() : string {

		return $this->extension ?? DEDALO_SVG_EXTENSION;
	}//end get_extension



	/**
	* GET_ALLOWED_EXTENSIONS
	* Return the list of file extensions that the upload flow accepts for this
	* component.
	*
	* Maps to config constant DEDALO_SVG_EXTENSIONS_SUPPORTED = ["svg"]. Only
	* extensions in this list will pass the valid_file_extension() check in the
	* upload tool.
	*
	* @return array $allowed_extensions - e.g. ["svg"]
	*/
	public function get_allowed_extensions() : array {

		$allowed_extensions = DEDALO_SVG_EXTENSIONS_SUPPORTED;

		return $allowed_extensions;
	}//end get_allowed_extensions



	/**
	* GET_FOLDER
	* Return the root media sub-directory that all SVG files are stored under.
	*
	* Returns the instance-level override ($this->folder) if set, otherwise the
	* config constant DEDALO_SVG_FOLDER = "/svg". This fragment is concatenated
	* by get_media_path_dir() and get_media_url_dir() (in component_media_common)
	* to form the full filesystem path or public URL.
	*
	* @return string - e.g. "/svg"
	*/
	public function get_folder() : string {

		return $this->folder ?? DEDALO_SVG_FOLDER;
	}//end get_folder



	/**
	* GET_BEST_EXTENSIONS
	* Return the ordered preference list of extensions used when selecting which
	* physical file to serve for a given quality.
	*
	* For SVG there is only one option. The base class method get_files_info()
	* and related helpers iterate this list from most to least preferred, stopping
	* at the first file that actually exists on disk.
	*
	* @return array - ["svg"]
	*/
	public function get_best_extensions() : array {

		return ['svg'];
	}//end get_best_extensions



	/**
	* GET_URL
	* Build and return the public URL for a given quality of this SVG asset.
	*
	* URL structure:
	*   DEDALO_MEDIA_URL + folder + initial_media_path + '/' + quality
	*   + additional_path + '/' + id + '.' + extension
	*
	* When $test_file is true the URL is validated against the filesystem.
	* If the file does not exist and $default_add is true, the URL is replaced
	* by the Dédalo grey-icon fallback image; if $default_add is false, null
	* is returned. This avoids broken <img src> tags in list views.
	*
	* sanitize_quality() is applied inside get_media_filepath() (called on the
	* test-file branch) so a client-supplied quality cannot escape the media
	* directory tree (SEC-065 / MEDIA-04 / MEDIA-05).
	*
	* @param string|null $quality [= null] - quality tier ("original", "web", "thumb");
	*   falls back to the current instance quality when null.
	* @param bool $test_file [= false] - when true, check the filesystem and return
	*   the fallback image URL (or null) if the file is absent.
	* @param bool $absolute [= false] - when true, prepend DEDALO_PROTOCOL + DEDALO_HOST
	*   to produce a fully qualified URL.
	* @param bool $default_add [= true] - when true and $test_file fails, return the
	*   Dédalo fallback icon URL instead of null.
	* @return string|null $image_url - relative or absolute URL; null only when
	*   $test_file=true, file is missing, and $default_add=false.
	*/
	public function get_url( ?string $quality=null, bool $test_file=false, bool $absolute=false, bool $default_add=true ) : ?string {

		// quality fallback to default
			if(empty($quality)) {
				$quality = $this->get_quality();
			}

		// image id
			$image_id = $this->get_id();

		// url
			$additional_path	= $this->additional_path;
			$initial_media_path	= $this->get_initial_media_path();
			$folder				= $this->get_folder(); // like DEDALO_SVG_FOLDER
			$extension			= $this->get_extension();
			$file_name			= $image_id .'.'. $extension;

			$image_url = DEDALO_MEDIA_URL . $folder . $initial_media_path . '/' . $quality . $additional_path . '/' . $file_name;

		// File exists test : If not, show '0' dedalo image logo
			if($test_file===true) {
				$file = $this->get_media_filepath($quality);
				if(!file_exists($file)) {
					if ($default_add===false) {
						return null;
					}
					$image_url = DEDALO_CORE_URL . '/themes/default/icons/dedalo_icon_grey.svg';
				}
			}

		// Absolute (Default false)
			if ($absolute===true) {
				$image_url = DEDALO_PROTOCOL . DEDALO_HOST . $image_url;
			}

		return $image_url;
	}//end get_url




	/**
	* GET_FILE_CONTENT
	* Read and return the raw SVG XML from disk for the current quality.
	*
	* Used when the caller wants to inline the SVG markup directly into the DOM
	* (for example to apply CSS classes or JavaScript animations to individual
	* SVG elements) rather than referencing it via an <img src> URL.
	*
	* The default quality path is used (component_media_common::get_media_filepath()).
	* Returns null without an error if the file does not exist; callers should
	* treat null as "no SVG stored yet" and render the upload affordance instead.
	*
	* @return string|null $file_content - raw SVG XML string, or null when absent.
	*/
	public function get_file_content() : ?string {

		$file_path		= $this->get_media_filepath();
		$file_content	= (file_exists($file_path))
			? file_get_contents($file_path)
			: null;

		return $file_content;
	}//end get_file_content



	/**
	* GET_DEFAULT_SVG_URL
	* Return the URL for the system-wide default SVG placeholder image.
	*
	* Used as the empty-state / upload-trigger affordance in render contexts
	* where no SVG has been uploaded yet. Resolves to the "upload.svg" icon
	* bundled in the default theme.
	*
	* @return string $url - absolute-path URL to upload.svg in the default theme.
	*/
	public static function get_default_svg_url() : string {

		$url = DEDALO_CORE_URL . '/themes/default/upload.svg';

		return $url;
	}//end get_default_svg_url



	/**
	* CREATE_THUMB
	* Generate a raster JPG thumbnail from the default-quality SVG file.
	*
	* SVG is a resolution-independent format; most list/grid views cannot
	* efficiently render arbitrary vector XML as a thumbnail, so a pre-rendered
	* JPG is produced via ImageMagick. The raster is written to the 'thumb'
	* quality path with the thumb extension (typically jpg).
	*
	* Rasterisation options used:
	*   density   = 150 dpi  — enough for a crisp thumb without huge memory use.
	*   antialias = true     — smooth curved paths.
	*   resize    = WxH      — from DEDALO_IMAGE_THUMB_WIDTH x DEDALO_IMAGE_THUMB_HEIGHT
	*                          (defaults: 224 x 149 if constants are not defined).
	*   ar_layers = [0]      — only the first page/frame of multi-page SVGs.
	*   quality   = 75       — JPEG compression.
	*
	* Returns false without throwing if the source (default-quality) SVG file
	* does not yet exist on disk. This is the normal state before the first upload
	* and should be treated as a deferred operation, not an error.
	*
	* (!) Known platform issue (macOS / Homebrew): ImageMagick may not be able to
	* locate Ghostscript because the PATH variable is not available to the web
	* server process. Fix: edit ImageMagick's delegates.xml and replace
	* command="&quot;gs&quot;" with the absolute GS path, e.g.
	* command="&quot;/usr/local/bin/gs&quot;".
	* See: http://www.imagemagick.org/discourse-server/viewtopic.php?t=29096
	*
	* (!) DEDALO_QUALITY_THUMB is expected to be defined in config. If it is not,
	* this method defines it as 'thumb' at runtime and logs a WARNING. This is a
	* defensive fallback; the config constant should always be present.
	*
	* @return bool - true on success, false when the source file is missing.
	*/
	public function create_thumb() : bool {

		// check config constant definition
			if (!defined('DEDALO_QUALITY_THUMB')) {
				define('DEDALO_QUALITY_THUMB', 'thumb');
				debug_log(__METHOD__
					." Undefined config 'DEDALO_QUALITY_THUMB'. Using fallback 'thumb' value"
					, logger::WARNING
				);
			}

		// thumb_path
			$file_name			= $this->get_id();
			$thumb_quality		= $this->get_thumb_quality();
			$thumb_extension	= $this->get_thumb_extension();
			$target_file		= $this->get_media_filepath($thumb_quality, $thumb_extension);

		// thumb not exists case: generate from PDF
			$quality		= $this->get_default_quality();
			$source_file	= $this->get_media_filepath($quality);
			if (!file_exists($source_file)) {
				debug_log(__METHOD__
					." Ignored thumb creation. default quality file does not exist ($file_name)"
					, logger::DEBUG
				);
				return false;
			}

		// dimensions . Like "102x57"
			$width		= defined('DEDALO_IMAGE_THUMB_WIDTH')  ? DEDALO_IMAGE_THUMB_WIDTH  : 224;
			$height		= defined('DEDALO_IMAGE_THUMB_HEIGHT') ? DEDALO_IMAGE_THUMB_HEIGHT : 149;
			$dimensions	= $width.'x'.$height;

			$thumb_pdf_options = new stdClass();
				$thumb_pdf_options->source_file = $source_file;
				$thumb_pdf_options->ar_layers 	= [0];
				$thumb_pdf_options->target_file = $target_file;
				$thumb_pdf_options->density		= 150;
				$thumb_pdf_options->antialias	= true;
				$thumb_pdf_options->quality		= 75;
				$thumb_pdf_options->resize		= $dimensions;

			ImageMagick::convert($thumb_pdf_options);


		return true;
	}//end create_thumb



	/**
	* GET_URL_FROM_LOCATOR
	* Resolve a public SVG URL from a component locator object.
	*
	* A locator identifies a specific component instance by its three-tuple:
	* component_tipo, section_tipo, section_id. This static helper validates both
	* tipos against the ontology before instantiating the component, preventing
	* URL generation for references to non-existent or mis-typed nodes.
	*
	* Validation rules:
	*   component_tipo — its ontology model must start with "component".
	*   section_tipo   — its ontology model must be exactly "section".
	*
	* Any validation failure is logged at ERROR level and null is returned; the
	* caller is responsible for providing a fallback (such as the default SVG URL).
	*
	* @param object $locator - locator with at minimum:
	*   $locator->component_tipo (string)  — tipo of the SVG component.
	*   $locator->section_tipo   (string)  — tipo of its owning section.
	*   $locator->section_id     (string)  — record id within that section.
	* @return string|null $url - the public URL for the component's current quality,
	*   or null when the locator is invalid.
	*/
	public static function get_url_from_locator(object $locator) : ?string {

		// check component_tipo
		if(!isset($locator->component_tipo) || !str_starts_with(ontology_node::get_model_by_tipo($locator->component_tipo, true), 'component')) {
			debug_log(__METHOD__
				. ' Error. component_tipo is invalid. Ignored URL resolution form locator.' . PHP_EOL
				. ' locator: ' . to_string($locator) . PHP_EOL
				. ' model: ' . ontology_node::get_model_by_tipo($locator->component_tipo, true)
				, logger::ERROR
			);
			return null;
		}

		// check section_tipo
		if(!isset($locator->section_tipo) || ontology_node::get_model_by_tipo($locator->section_tipo, true) !== 'section') {
			debug_log(__METHOD__
				. ' Error. section_tipo is invalid. Ignored URL resolution form locator.' . PHP_EOL
				. ' locator: ' . to_string($locator) . PHP_EOL
				. ' model: ' . ontology_node::get_model_by_tipo($locator->section_tipo, true)
				, logger::ERROR
			);
			return null;
		}

		$model		= ontology_node::get_model_by_tipo($locator->component_tipo,true);
		$component	= component_common::get_instance(
			$model,
			$locator->component_tipo,
			$locator->section_id,
			'list',
			DEDALO_DATA_NOLAN,
			$locator->section_tipo
		);
		$url = $component->get_url();

		return $url;
	}//end get_url_from_locator



	/**
	* PROCESS_UPLOADED_FILE
	* Finalize an SVG upload: persist file metadata and trigger quality regeneration.
	*
	* This is the last step in the four-method upload chain:
	*   1. dd_utils_api::upload          — permission-gated HTTP endpoint; moves
	*                                      the file to its target quality directory.
	*   2. tool_upload::process_uploaded_file — determines the target quality and
	*                                      calls component_media_common::add_file().
	*   3. component_media_common::add_file  — renames any old quality files, then
	*                                      delegates here.
	*   4. component_svg::process_uploaded_file (THIS METHOD) — records descriptor
	*                                      and re-builds all quality variants.
	*
	* When the uploaded quality is 'original' (DEDALO_SVG_QUALITY_ORIGINAL), the
	* file descriptor at data[0] is populated with:
	*   original_file_name        — human-readable name as entered by the user.
	*   original_normalized_name  — deterministic on-disk filename (same as
	*                               full_file_name, built by the upload chain).
	*   original_upload_date      — current timestamp via component_date::get_date_now().
	*
	* After the descriptor update, regenerate_component() is called to:
	*   - Build or copy the 'web' quality from the 'original'.
	*   - Generate the raster 'thumb' via create_thumb().
	*   - Persist the updated section data.
	*
	* $file_data shape (all keys required):
	* {
	*     "original_file_name": "my_file.svg",          // user-provided filename
	*     "full_file_name":     "test81_test65_2.svg",  // normalized on-disk name
	*     "full_file_path":     "/mypath/media/svg/standard/test81_test65_2.svg"
	* }
	*
	* @param object|null $file_data - upload descriptor emitted by the upload chain;
	*   null results in an immediate error response.
	* @param object|null $process_options [= null] - reserved for future per-upload
	*   pipeline options; currently unused by this method.
	* @return object $response
	*   $response->result (bool)   — true on success, false on any failure.
	*   $response->msg    (string) — human-readable status / error detail.
	*/
	public function process_uploaded_file( ?object $file_data=null, ?object $process_options=null ) : object {

		$response = new stdClass();
			$response->result	= false;
			$response->msg		= 'Error. Request failed ['.__METHOD__.'] ';

		// check file_data
			if (empty($file_data)) {
				$response->msg .= ' Empty file_data';
				return $response;
			}

		// short vars
			$original_file_name			= $file_data->original_file_name;	// kike "my file785.svg"
			$full_file_path				= $file_data->full_file_path;		// like "/mypath/media/svg/standard/test81_test65_2.svg"
			$full_file_name				= $file_data->full_file_name;		// like "test175_test65_1.svg"
			$original_normalized_name	= $full_file_name;

		// check full_file_path
			if (!file_exists($full_file_path)) {
				$response->msg .= ' File full_file_path do not exists';
				return $response;
			}

		// debug
			debug_log(__METHOD__
				. " process_uploaded_file " . PHP_EOL
				. ' original_file_name: ' . $original_file_name .PHP_EOL
				. ' full_file_path: ' . $full_file_path
				, logger::WARNING
			);

		try {

			// upload info
			// Only write the descriptor when the uploaded file is the 'original' quality.
			// Uploading a derived quality (e.g. 'web') should not overwrite the source metadata.
				$original_quality = $this->get_original_quality();
				if ($this->quality===$original_quality) {
					// update upload file info
					$data = $this->get_data();
					$key = 0;
					if (!isset($data[$key]) || !is_object($data[$key])) {
						$data[$key] = new stdClass();
					}
					$data[$key]->original_file_name			= $original_file_name;
					$data[$key]->original_normalized_name	= $original_normalized_name;
					$data[$key]->original_upload_date		= component_date::get_date_now();

					$this->set_data($data);
				}

			// Generate default_image_format : If uploaded file is not in Dedalo standard format (jpg), is converted,
			// and original file is conserved (like myfilename.tiff and myfilename.jpg)
			// regenerate component will create the default quality image calling build()
			// build() will check the normalized files of the original and modified quality
			// then if the normalized files doesn't exist, will create it
			// then will create the SVG format of the default
			// then save the data.
				$result = $this->regenerate_component();
				if ($result === false) {
					$response->msg .= ' Error processing the uploaded file';
					return $response;
				}

			// response OK
				$response->result	= true;
				$response->msg		= 'OK. successful request';

		} catch (Exception $e) {
			$msg = 'Exception[process_uploaded_file]: ' .  $e->getMessage() . "\n";
			debug_log(__METHOD__
				." $msg "
				, logger::ERROR
			);
			$response->msg .= ' - '.$msg;
		}


		return $response;
	}//end process_uploaded_file



	/**
	* UPDATE_DATA_VERSION
	* Static migration hook called by the data-version update framework when
	* upgrading stored component data to a new Dédalo schema version.
	*
	* The framework iterates every component instance in the database and calls
	* this method with the target version. The method is responsible for
	* transforming the stored data to match the new expected shape and returning
	* a result code:
	*   result = 0 — this component has no migration for the given version (no-op).
	*   result = 1 — migration was applied successfully.
	*   result = 2 — migration was attempted but the data did not need changing.
	*
	* Currently component_svg has no version-specific migration cases; the switch
	* always falls through to the default branch and returns result = 0.
	*
	* $options shape:
	* {
	*   "update_version" : string[] — version parts, e.g. ["7","0","0"]; joined
	*                                 with implode('.', ...) before the switch.
	*   "data_unchanged" : array|null — the stored data at call time.
	*   "reference_id"   : string    — "{section_tipo}.{section_id}.{component_tipo}".
	*   "tipo"           : string    — component tipo identifier.
	*   "section_id"     : string    — record id.
	*   "section_tipo"   : string    — section tipo identifier.
	*   "context"        : string    — calling context, default "update_component_data".
	* }
	*
	* @param object $options - migration options as described above.
	* @return object $response
	*   $response->result (int)    — 0 / 1 / 2 as described above.
	*   $response->msg    (string) — human-readable status detail.
	*/
	public static function update_data_version(object $options) : object {

		// options
			$update_version	= $options->update_version ?? '';
			$data_unchanged	= $options->data_unchanged ?? null;
			$reference_id	= $options->reference_id ?? null;
			$tipo			= $options->tipo ?? null;
			$section_id		= $options->section_id ?? null;
			$section_tipo	= $options->section_tipo ?? null;
			$context		= $options->context ?? 'update_component_data';

		$update_version	= implode('.', $update_version);
		switch ($update_version) {

			default:
				$response = new stdClass();
					$response->result	= 0;
					$response->msg		= "This component ".get_called_class()." don't have update to this version ($update_version). Ignored action";
				break;
		}//end switch ($update_version)


		return $response;
	}//end update_data_version



}//end class component_svg
