<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
		
	
	#print "\n<!-- BUTTON PRINT [tipo:$tipo id_matrix:$id] -->";
	#print "\n<div class=\"css_wrap_button_print\">";
	
	# ETIQUETA (LABEL)
	//$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content = '';
	
	switch(true) {
			
		case $permissions===0 :
				$html_content .= "";
				break;
						
		case ($permissions>=2)	:

				$html_content .= "<div class=\"css_button_generic btn_inside_section_buttons_container css_button_print tool_print\"
				onclick=\"tool_common.open_tool_layout_print(this)\"
				data-tipo=\"{$tipo}\"
				data-target_section_tipo=\"{$target_section_tipo}\"
				title=\"$html_title\" >";
				$html_content .= "<span>";
				$html_content .= $label;
				$html_content .= "</span>";
				$html_content .= "</div>";
	}
	
	
	# PRINT HTML
	print $html_content;
	
	
	#print "\n</div><!-- /css_wrap_button_import -->\n\n"; //wrap
?>