<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
		
	
	#print "\n<!-- BUTTON PRINT [tipo:$tipo id_matrix:$id] -->";
	#print "\n<div class=\"css_wrap_button_print {$ar_css['css_wrap_button_print]}\">";
	
	# ETIQUETA (LABEL)
	//$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	
	switch($permissions) {
			
		case 0	:	$html_contenido .= "";					
					break;
						
		case ($permissions>=2)	:

					$html_contenido .= "\n <div class=\"css_button_generic css_button_print link\"
					onclick=\"tool_common.open_tool_layout_print(this)\" 
					data-tipo=\"{$tipo}\" data-target_section_tipo=\"{$target_section_tipo}\" 
					title=\"$html_title\" >";
					$html_contenido .= $label;
					$html_contenido .= "</div>";					
	
					
			if($permissions==3)		
					$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
	}
	
	
	# PRINT HTML
	print $html_contenido;
	
	
	#print "\n</div><!-- /css_wrap_button_import -->\n\n"; //wrap
?>