<?php
	
	# VISUALIZADOR HTML	

	# ELEMENTOS	
	if(!isset ($ar_css['css_span_dato'])) 				$ar_css['css_span_dato']='';
	
	
	#print "\n\n<!-- ROWS_HEADER [$tipo] -->";
		
	# CONTENIDO (INPUT)
	$html_contenido  = "\n<tr>";	
	
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." </span>";
					break;
						
		case ($permissions>=1)	:
					
					# TD ID
					$html_contenido .= "\n <th class=\"id_column\">";
						$html_contenido .= "<div class=\"th_title\">";
						$html_contenido .= "\n ID ";
						$html_contenido .= '</div>';
						#$html_contenido .= $this->flechas_orden('id','id');
					$html_contenido .= "\n </th>";
					
					# TD DATOS					
					foreach($ar_label_html as $tipo => $label_html) {
						
						$html_contenido .= "\n <th>";
						
							$html_contenido .= "<div class=\"th_title\" title=\"$label_html\">";
							$html_contenido .= $label_html;
							$html_contenido .= '</div>';
							#$html_contenido .= $this->flechas_orden($tipo, $label_html);

						$html_contenido .= "\n </th>";						
					}

	}
	$html_contenido .= "\n</tr>";
	
	# PRINT HTML
	print $html_contenido;
	

?>