<tr>

	<!-- LANG NAME -->
	<td style="text-align:center">
		<strong><?php echo $langFull ?></strong> 
		<?php if(SHOW_DEBUG) echo " [$lang]" ?>
	</td>


	<!-- TERM -->
	<td>
    	<input type="text" name="termino_<?php echo $id ?>" id="termino_<?php echo $id ?>" style="width:99%" value="<?php echo $termino ?>" 
    	onfocus="myfocus(this)" onblur="myblur(this);" 
    	data-parent="<?php echo $parent_desc ?>" data-lang="<?php echo $lang ?>" data-tipo="termino" 
    	onchange="saveDescriptor(this)" >
    </td>


    <!-- DEFINITION -->
	<td>
    	<textarea name="def_<?php echo $def_id ?>" id="def_<?php echo $def_id ?>" style="width:100%; height:14px;" 
    	onfocus="myfocus(this)" onblur="myblur(this);" 
    	data-parent="<?php echo $parent_desc ?>" data-lang="<?php echo $lang ?>" data-tipo="def" 
    	onchange="saveDescriptor(this)" ><?php echo $def ?></textarea>
    </td>


    


    <!-- LANG : NEW -->
	<td align="center">

		<?php		
		#
		# SELECT : Sólo se muestra el selector para el idioma principal (viene disparado por ts_edit !)
		if($lang == $mainLang) {

			$select_html='';

			# LANGS SELECTOR			
			$excludeLang 	= $mainLang;
			$selectedItem 	= $lang;			
			
			$select_html .= "\n<select name=\"SelectLangList\" id=\"SelectLangList\" class=\"selectProjectLang\" onChange=\"add_new_lang(this);\" title=\"Langs\" >";
			$select_html .= "\n <option value=\"\" ></option>";

			#dump($ar_all_langs,'$ar_all_langs');
			#dump($ar_transtations_of_current,'ar_transtations_of_current '.$id);
			
			if(is_array($ar_all_langs)) foreach($ar_all_langs as $current_terminoID => $termino) {
				
				if($current_terminoID == $excludeLang) continue; # Skip

					#dump($current_terminoID,'excludeLang '.$excludeLang);
				
				#$termino	= RecordObj_ts::get_termino_by_tipo($current_terminoID);
				#$termino	= RecordObj_ts::get_termino_by_tipo($current_terminoID);
				
				$select_html .= "\n <option value=\"$current_terminoID\" ";

				if($selectedItem==$current_terminoID)
				$select_html .= " selected=\"selected\" ";

				$select_html .= ">$termino";
				if(SHOW_DEBUG)
				$select_html .= " [$current_terminoID]";
				$select_html .= "</option>";			
			}
			
			# OTRO
			global $otro_title;
			$select_html .= "\n <option value=\"otro\" > $otro_title </option>";
			
			$select_html .= "\n</select>\n";
			
			print $select_html;
		
		}else{

			# Delete current descriptor
			# 'terminoID' is defined in 'ts_descriptors_grid.php'
			echo "<img src=\"../themes/default/delete.png\" class=\"dropBox\" title=\"Delete $langFull\" onclick=\"removeDescriptor('$id','$terminoID')\" />";
		}
		#
		?>
	</td>

</tr>


<tr>
	<!-- NOTES -->
	<td colspan="4">
		<span style="vertical-align:top;">Notes</span> 
    	<textarea name="notes_<?php echo $notes_id ?>" id="notes_<?php echo $notes_id ?>" style="width:78.5%; height:2em;" 
    	onfocus="myfocus(this)" onblur="myblur(this);" 
    	data-parent="<?php echo $parent_desc ?>" data-lang="<?php echo $lang ?>" data-tipo="notes" 
    	onchange="saveDescriptor(this)" ><?php echo $notes ?></textarea>
    </td>
</tr>