<?php
	# TIPO TO OPEN
	$prefix = substr($terminoID, 0,2);
	if($prefix=='dd') {
		$tipo = 5;
	}else{
		$tipo = 'all';
	}

?>

<!-- LISTADO DE TERMINOS RELACIONADOS -->      
<div class="textoIndex" style="margin:4px">

	<!-- BTN Abrir Tesauro --> 
    <input value="<?php echo $terminos_title ?>" class="btnTesauro" onclick="javascript:abrirTSlist('tesauro_rel','<?php echo $tipo ?>');" type="button">          
        
    <?php if($n_terminos_relacionados>0){?>  
    <div style="color:#000000; font-size:11px; font-weight:bold"><?php echo $terminos_relacionados_title ?>  <?php echo " [".$n_terminos_relacionados."] "; ?></div>  
    <hr>
    
    <div style="height:80px; overflow:auto; ">
        <?php 
		
		if(count($arTR) == 0) {
		
			$html = "<span style=\"color:grey\">$no_hay_terminos_relacionados_title</span>";
		
		}else{
			//print_r($arTR);
			# recoremos el array		
			foreach($arTR['termino'] as $key => $termino) {				
					
				$terminoID		= $arTR['terminoID'][$key];
				$terminoNjs		= urlencode($termino);				
				
				$html .= "<img src=\"../themes/default/delete.png\" hspace=\"4\" onClick=\"unlinkTS('$terminoID','$terminoNjs')\" title=\"$eliminar_relacion_title\" style=\"cursor:pointer\" />";
				$html .= $termino ;
				$html .= "<span class=\"terminoIDinList\" title=\"ID\"> [ $terminoID ]</span></br>";
								
			}
		}
		echo $html; 
		?>
    </div>
    <?php }#if($ar_terminos_relacionados>0)?>
    
</div>
        
        
	
