<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>"Geo"</title>
<?php
print css::build_tag(DEDALO_ROOT_WEB .'/lib/leaflet/leaflet.css');
$leaflet_url = defined('LEAFLET_JS_URL') ? LEAFLET_JS_URL : DEDALO_ROOT_WEB . "/lib/leaflet/stable_versions/leaflet.js";
print js::build_tag($leaflet_url);
?>

</head>
<body style="margin:0;padding:0">

	<div id="map" style="width: 100%; height: 500px; position: relative;" class="leaflet-container leaflet-fade-anim"></div>


<script language="JavaScript" type="text/javascript">

		var map = L.map('map',{attributionControl: false}).setView([39.46264,-0.37615], 13);
		//map.attributionControl = false;

		L.tileLayer('https://{s}.tiles.mapbox.com/v3/{id}/{z}/{x}/{y}.png', {
			maxZoom: 18,
			attribution: false,
			id: 'examples.map-i86knfo3'
		}).addTo(map);

		var popup = L.popup();

		function onMapClick(e) {
			var georeferenciacion_valor = e.latlng.lat +','+e.latlng.lng;
			//console.log(typeof georeferenciacion_valor);
			popup
				.setLatLng(e.latlng)
				.setContent(georeferenciacion_valor +'<br><div style="text-align:center;padding:5px"><a href="javascript:window.opener.set_georeferenciacion(\'<?php echo $field_id ?>\','+georeferenciacion_valor+'); window.close();"> OK </a></div>')
				.openOn(map);
		}

		map.on('click', onMapClick);

</script>

</body>
</html>