/**
 * CHANGE LOG — `docs/change_log.md` is GENERATED from `changes/`, never written by hand.
 *
 * WHY. The page used to be hand-edited, and on 2026-09-26 it was misleading rather
 * than merely behind: ~25 entries for 1,654 commits since the cutover, every one of
 * them `[Unreleased]` while four beta tags had shipped, a "last modification" header
 * a month older than its newest entry, and one entry describing tooling this
 * repository never had. A single file that every change inserts at the top also
 * conflicts on every merge between parallel lines of work.
 *
 * THE MODEL (rules for authors: changes/README.md):
 *   changes/unreleased/<slug>.md       one FRAGMENT per reader-visible change, written
 *                                      in the commit that makes the change
 *   changes/<version>/<slug>.md        the fragments a release shipped
 *   changes/<version>/release.json     that release's snapshot: date, tag range,
 *                                      commit count, the wire-contract ids it adopted
 *
 * The page is a PURE FUNCTION of those files plus the wire-contract ledger's ids
 * (`engineering/wire_contract/`) — no git, no clock — so change_log_tripwire can
 * re-render it hermetically and demand byte identity. Git is read exactly once per
 * release, by `bun run changelog release`, and its answer is frozen in release.json.
 */

import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

export const TYPES = ['security', 'removed', 'deprecated', 'changed', 'added', 'fixed'] as const;
export const AUDIENCES = ['user', 'admin', 'developer'] as const;
export type ChangeType = (typeof TYPES)[number];
export type Audience = (typeof AUDIENCES)[number];

const TYPE_HEADINGS: Record<ChangeType, string> = {
	security: 'Security',
	removed: 'Removed',
	deprecated: 'Deprecated',
	changed: 'Changed',
	added: 'Added',
	fixed: 'Fixed',
};
const AUDIENCE_HEADINGS: Record<Audience, string> = {
	user: 'For users',
	admin: 'For administrators',
	developer: 'For developers',
};

export const GENERATED_MARKER =
	'<!-- GENERATED by scripts/changelog.ts from changes/ — do not edit this file. Add a fragment under changes/unreleased/ and run `bun run changelog` (rules: changes/README.md). -->';

export interface Fragment {
	/** Repo-relative path, for error messages. */
	file: string;
	slug: string;
	/** One line of inline markdown: what changed, said to the reader. */
	title: string;
	type: ChangeType;
	audience: Audience;
	/** yyyy-mm-dd — the day the change landed; orders entries newest first. */
	date: string;
	/** The reader must DO something when updating across this change. */
	breaking: boolean;
	/** Wire-contract ids this change adopted (either id grammar). */
	wc: string[];
	body: string;
}

export interface Release {
	version: string;
	date: string;
	/** The previous release's tag; null for the first release this log records. */
	from: string | null;
	/** This release's tag. */
	to: string;
	/** Non-merge commits in from..to, counted when the release was cut. */
	commits: number;
	/** Wire-contract ids adopted in this release (the ledger entries no earlier release claimed). */
	wire_contract: string[];
}

export interface ChangeSet {
	unreleased: Fragment[];
	/** Any order; the renderer sorts. */
	releases: { release: Release; fragments: Fragment[] }[];
}

const SLUG_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
const VERSION_RE = /^\d+\.\d+\.\d+(-[a-z]+\.\d+)?$/;
/** Both ledger grammars: the frozen sequential `WC-nnn` and the dated `WC-yyyy-mm-dd-slug`. */
export const WC_ID_RE = /^WC-(\d{3}|\d{4}-\d{2}-\d{2}-[a-z0-9]+(-[a-z0-9]+)*)$/;

const FRONT_KEYS = ['title', 'type', 'audience', 'date', 'breaking', 'wc'] as const;

function fail(file: string, message: string): never {
	throw new Error(`${file}: ${message}`);
}

function isValidDate(value: string): boolean {
	if (!DATE_RE.test(value)) return false;
	const d = new Date(`${value}T00:00:00Z`);
	return !Number.isNaN(d.getTime()) && d.toISOString().slice(0, 10) === value;
}

/** ATX headings outside fenced code — a fragment sits under the page's own h2–h4. */
function findHeading(body: string): string | null {
	let fence: string | null = null;
	for (const line of body.split('\n')) {
		const marker = /^\s*(```|~~~)/.exec(line)?.[1];
		if (marker !== undefined) {
			if (fence === null) fence = marker;
			else if (fence === marker) fence = null;
			continue;
		}
		if (fence === null && /^\s{0,3}#{1,6}(\s|$)/.test(line)) return line;
	}
	return null;
}

export function parseFragment(file: string, text: string): Fragment {
	const name = file.split('/').pop() ?? file;
	const slug = name.replace(/\.md$/, '');
	if (!name.endsWith('.md') || !SLUG_RE.test(slug)) {
		fail(file, `file name must be a kebab-case slug ending in .md (got '${name}')`);
	}
	const match = /^---\n([\s\S]*?)\n---\n?([\s\S]*)$/.exec(text.replace(/\r\n/g, '\n'));
	if (match === null) fail(file, "missing front matter (a '---' block opening the file)");
	const [, front = '', rest = ''] = match;

	const fields = new Map<string, string>();
	for (const line of front.split('\n')) {
		if (line.trim() === '') continue;
		const kv = /^([a-z_]+):\s*(.*)$/.exec(line);
		if (kv === null) fail(file, `unreadable front-matter line '${line}' (want 'key: value')`);
		const [, key = '', value = ''] = kv;
		if (!(FRONT_KEYS as readonly string[]).includes(key)) {
			fail(file, `unknown key '${key}' (allowed: ${FRONT_KEYS.join(', ')})`);
		}
		if (fields.has(key)) fail(file, `repeated key '${key}'`);
		fields.set(key, value.trim());
	}
	const required = (key: string): string => {
		const value = fields.get(key);
		if (value === undefined || value === '') fail(file, `missing '${key}'`);
		return value;
	};

	const title = required('title');
	const type = required('type');
	if (!(TYPES as readonly string[]).includes(type)) {
		fail(file, `type '${type}' is not one of ${TYPES.join(', ')}`);
	}
	const audience = required('audience');
	if (!(AUDIENCES as readonly string[]).includes(audience)) {
		fail(file, `audience '${audience}' is not one of ${AUDIENCES.join(', ')}`);
	}
	const date = required('date');
	if (!isValidDate(date)) fail(file, `date '${date}' is not a real yyyy-mm-dd date`);

	const breakingRaw = fields.get('breaking') ?? 'false';
	if (breakingRaw !== 'true' && breakingRaw !== 'false') {
		fail(file, `breaking must be true or false (got '${breakingRaw}')`);
	}
	const wcRaw = fields.get('wc') ?? '';
	const wc = wcRaw === '' ? [] : wcRaw.split(',').map((s) => s.trim());
	for (const id of wc) {
		if (!WC_ID_RE.test(id)) fail(file, `wc id '${id}' matches neither ledger grammar`);
	}

	const body = rest.trim();
	if (body === '') fail(file, 'empty body — say what changed for the reader, and why it matters');
	const heading = findHeading(body);
	if (heading !== null) {
		fail(file, `the body may not contain a heading ('${heading.trim()}') — the page owns h1–h4`);
	}

	return {
		file,
		slug,
		title,
		type: type as ChangeType,
		audience: audience as Audience,
		date,
		breaking: breakingRaw === 'true',
		wc,
		body,
	};
}

const RELEASE_KEYS = ['version', 'date', 'from', 'to', 'commits', 'wire_contract'] as const;

export function parseRelease(file: string, text: string): Release {
	let raw: unknown;
	try {
		raw = JSON.parse(text);
	} catch (error) {
		fail(file, `not JSON (${(error as Error).message})`);
	}
	if (typeof raw !== 'object' || raw === null || Array.isArray(raw))
		fail(file, 'not a JSON object');
	const obj = raw as Record<string, unknown>;
	for (const key of Object.keys(obj)) {
		if (!(RELEASE_KEYS as readonly string[]).includes(key)) fail(file, `unknown key '${key}'`);
	}
	const { version, date, from, to, commits, wire_contract } = obj;
	if (typeof version !== 'string' || !VERSION_RE.test(version)) {
		fail(file, `version '${String(version)}' is not <major>.<minor>.<patch>[-<pre>.<n>]`);
	}
	if (typeof date !== 'string' || !isValidDate(date))
		fail(file, `date '${String(date)}' is not yyyy-mm-dd`);
	if (from !== null && (typeof from !== 'string' || from === ''))
		fail(file, 'from must be a tag or null');
	if (typeof to !== 'string' || to === '') fail(file, 'to must be a tag');
	if (typeof commits !== 'number' || !Number.isInteger(commits) || commits < 0) {
		fail(file, 'commits must be a non-negative integer');
	}
	if (
		!Array.isArray(wire_contract) ||
		!wire_contract.every((id) => typeof id === 'string' && WC_ID_RE.test(id))
	) {
		fail(file, 'wire_contract must be an array of ledger ids');
	}
	return { version, date, from, to, commits, wire_contract: wire_contract as string[] };
}

/** Release order: numeric major.minor.patch, and a prerelease sorts before its release. */
export function compareVersions(a: string, b: string): number {
	const split = (v: string) => {
		const [core = '', pre] = v.split('-', 2);
		return { nums: core.split('.').map(Number), pre };
	};
	const x = split(a);
	const y = split(b);
	for (let i = 0; i < 3; i++) {
		const d = (x.nums[i] ?? 0) - (y.nums[i] ?? 0);
		if (d !== 0) return d;
	}
	if (x.pre === y.pre) return 0;
	if (x.pre === undefined) return 1;
	if (y.pre === undefined) return -1;
	const [xl = '', xn = '0'] = x.pre.split('.');
	const [yl = '', yn = '0'] = y.pre.split('.');
	if (xl !== yl) return xl < yl ? -1 : 1;
	return Number(xn) - Number(yn);
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

const INTRO = [
	'What changed in each Dédalo v7 release, newest first. Every change is filed under',
	'who it affects — **users** of the application, **administrators** who install and',
	'run it, and **developers** who build on its API. A release that needs something',
	'from you when you update says so first, in an *Action needed* box.',
	'',
	"Each release's *Wire contract* list names the deliberate changes to the API's wire",
	'shape by the id under which the source tree records each one',
	'(`engineering/wire_contract/`).',
].join('\n');

function indent(body: string): string {
	return body
		.split('\n')
		.map((line) => (line.trim() === '' ? '' : `    ${line}`))
		.join('\n');
}

function byNewest(a: Fragment, b: Fragment): number {
	if (a.date !== b.date) return a.date < b.date ? 1 : -1;
	return a.slug < b.slug ? -1 : a.slug > b.slug ? 1 : 0;
}

function renderFragments(fragments: Fragment[]): string[] {
	const out: string[] = [];
	const breaking = fragments.filter((f) => f.breaking).sort(byNewest);
	if (breaking.length > 0) {
		out.push('!!! warning "Action needed when you update"');
		out.push('');
		for (const f of breaking) out.push(`    - ${f.title}`);
		out.push('');
	}
	for (const audience of AUDIENCES) {
		const mine = fragments.filter((f) => f.audience === audience);
		if (mine.length === 0) continue;
		out.push(`### ${AUDIENCE_HEADINGS[audience]}`, '');
		for (const type of TYPES) {
			const group = mine.filter((f) => f.type === type).sort(byNewest);
			if (group.length === 0) continue;
			out.push(`#### ${TYPE_HEADINGS[type]}`, '');
			for (const f of group) {
				out.push(`- **${f.title}**${f.breaking ? ' *(action needed)*' : ''}`, '');
				out.push(indent(f.body), '');
				if (f.wc.length > 0) {
					out.push(indent(`Wire contract: ${f.wc.map((id) => `\`${id}\``).join(', ')}.`), '');
				}
			}
		}
	}
	return out;
}

function renderWireContract(ids: string[]): string[] {
	if (ids.length === 0) return [];
	const count = `${ids.length} ${ids.length === 1 ? 'entry' : 'entries'}`;
	return [
		`??? note "Wire contract — ${count}"`,
		'',
		...[...ids].sort().map((id) => `    - \`${id}\``),
		'',
	];
}

export function renderChangeLog(set: ChangeSet, unreleasedWc: string[]): string {
	const out: string[] = [GENERATED_MARKER, '', '# Change log', '', INTRO, ''];

	out.push('## Unreleased', '');
	if (set.unreleased.length === 0) {
		out.push('Nothing yet — no change note has been recorded since the last release.', '');
	} else {
		out.push('Merged since the last release; these ship with the next one.', '');
	}
	out.push(...renderFragments(set.unreleased));
	out.push(...renderWireContract(unreleasedWc));

	const releases = [...set.releases].sort((a, b) =>
		compareVersions(b.release.version, a.release.version),
	);
	for (const { release, fragments } of releases) {
		const range = release.from === null ? release.to : `${release.from}..${release.to}`;
		out.push(`## ${release.version} — ${release.date}`, '');
		out.push(`${release.commits} commits: \`git log --no-merges ${range}\``, '');
		out.push(...renderFragments(fragments));
		out.push(...renderWireContract(release.wire_contract));
	}

	return `${out.join('\n').replace(/\n+$/, '')}\n`;
}

// ---------------------------------------------------------------------------
// Loading (filesystem)
// ---------------------------------------------------------------------------

export const UNRELEASED_DIR = 'unreleased';

/** Reads `<root>/changes/`. Anything that is not a fragment, a release.json or the README is refused. */
export function loadChangeSet(root: string): ChangeSet {
	const changesDir = join(root, 'changes');
	const rel = (p: string) => relative(root, p);
	const set: ChangeSet = { unreleased: [], releases: [] };
	// Dotfiles (Finder's .DS_Store) are machine noise, never content.
	const visible = (name: string) => !name.startsWith('.');
	for (const entry of readdirSync(changesDir).filter(visible).sort()) {
		const path = join(changesDir, entry);
		if (!statSync(path).isDirectory()) {
			if (entry === 'README.md') continue;
			fail(
				rel(path),
				'unexpected file — changes/ holds only README.md and one directory per release',
			);
		}
		const fragments: Fragment[] = [];
		for (const file of readdirSync(path).filter(visible).sort()) {
			const filePath = join(path, file);
			if (file === 'release.json') continue;
			if (!file.endsWith('.md'))
				fail(rel(filePath), 'unexpected file — a release directory holds *.md and release.json');
			fragments.push(parseFragment(rel(filePath), readFileSync(filePath, 'utf8')));
		}
		if (entry === UNRELEASED_DIR) {
			if (existsSync(join(path, 'release.json')))
				fail(rel(path), 'unreleased/ cannot carry a release.json');
			set.unreleased = fragments;
			continue;
		}
		const releaseFile = join(path, 'release.json');
		if (!existsSync(releaseFile)) fail(rel(path), 'a release directory needs its release.json');
		const release = parseRelease(rel(releaseFile), readFileSync(releaseFile, 'utf8'));
		if (release.version !== entry) {
			fail(
				rel(releaseFile),
				`version '${release.version}' does not match its directory '${entry}'`,
			);
		}
		set.releases.push({ release, fragments });
	}
	return set;
}

/** Every ledger id, read from each entry's h1 (`# <id> — <title>`), the ledger's own key. */
export function wireContractIds(root: string): string[] {
	const dir = join(root, 'engineering', 'wire_contract');
	const ids: string[] = [];
	for (const file of readdirSync(dir).sort()) {
		if (!file.endsWith('.md')) continue;
		const h1 = readFileSync(join(dir, file), 'utf8').split('\n', 1)[0] ?? '';
		const id = /^# (WC-\S+) — /.exec(h1)?.[1];
		if (id === undefined || !WC_ID_RE.test(id))
			fail(`engineering/wire_contract/${file}`, 'h1 carries no ledger id');
		ids.push(id);
	}
	return ids;
}

/** Ledger ids no release has claimed yet — what the next release will adopt. */
export function unreleasedWireContract(set: ChangeSet, allIds: string[]): string[] {
	const claimed = new Set(set.releases.flatMap((r) => r.release.wire_contract));
	return allIds.filter((id) => !claimed.has(id)).sort();
}

/** The one page, as the repository's current files define it. */
export function renderFromRepo(root: string): string {
	const set = loadChangeSet(root);
	return renderChangeLog(set, unreleasedWireContract(set, wireContractIds(root)));
}

export const CHANGE_LOG_PAGE = join('docs', 'change_log.md');
