<?php 


		$html .= "<div class=\"header_tool\">";
		
		#
		# TOOL NAME
		$html .= "<div class=\"header_info header_tool_name tool_tr_portal_icon\">";
		$html .= label::get_label($tool_name) ;
		$html .= "</div>";//end header_tool_name


		#
		# INFO
		$html .= "<div class=\"header_info\">";
		$html .= $section_label;
		$html .= "</div>";//end header_info


		#
		# TOP_ID SELECTOR
		
			
		$html .= "<div class=\"header_info\"> ID: ";
		$html .= $section_id;
		$html .= "</div>";//end top_id_selector			
	


		#
		# HEADER_INFO
		#$html .= " <div id=\"header_info\"> Info: </div>";
		$html .= "<div class=\"header_buttons\">";
			
		$html .= "</div>";//end header_buttons	

		
		#
		# COMPONENT STATE
		#$html   .= $component_state_html;


	$html .= "</div><!-- /header_tool -->";
