<?php declare(strict_types=1);
/**
* CLASS EXEC_
* Thin shell-execution layer for Dédalo background tasks and media processing.
*
* Provides three escalating levels of process management:
* - exec_command: fire-and-forget synchronous shell command (e.g. ffmpeg poster frame).
* - exec_sh_file: launch a pre-built .sh script in the background and capture its PID.
* - request_cli: the primary background-task launcher used by tools and area_maintenance;
*   serialises a class/method/params tuple into a JSON argument, spawns
*   process_runner.php with `nohup nice`, and registers the resulting PID in
*   the `processes` tracking store so callers can poll status via dd_utils_api.
*
* All methods escape shell arguments before interpolation (escapeshellcmd /
* escapeshellarg). See the SEC-045 note below for removed helpers that did not.
*
* Known callers:
* - exec_command  → core/media_engine/class.Ffmpeg.php (poster frame)
* - exec_sh_file  → core/component_av/class.component_av.php (media transcode)
* - request_cli   → core/api/v1/common/class.dd_tools_api.php
*                   core/api/v1/common/class.dd_area_maintenance_api.php
*
* Also defines the `process` helper class (Linux-only) used to track, inspect, and
* stop background OS processes by PID; see that class for full docs.
*
* @package Dédalo
* @subpackage Core
*/
class exec_ {



	/**
	* EXEC_COMMAND
	* Run a synchronous shell command and return whether it produced any output.
	*
	* The command string is passed through escapeshellcmd() before execution.
	* The caller controls where stdout/stderr are redirected via the $to parameter
	* (default '2>&1' merges stderr into stdout so shell_exec can capture it).
	*
	* Returns false when shell_exec() produces no output at all — this is the
	* primary signal that the command failed, because many CLI tools (e.g. ffmpeg)
	* print at least one line of header text even on success. If the underlying
	* process genuinely produces no output and succeeds, this method will
	* incorrectly return false; callers that depend on that edge case must use
	* exec() directly.
	*
	* @param string $command - raw shell command to execute (will be escapeshellcmd-escaped)
	* @param string $to = '2>&1' - output redirection suffix appended after the command
	* @return bool - true when the command ran and produced output; false on empty output or exception
	* @throws Exception (caught internally) when $output is empty — logs and returns false
	*/
	public static function exec_command(string $command, string $to='2>&1') : bool {

		$output = null;

		try {

			// escape command for security
			$command = escapeshellcmd( $command ) . ' '. $to;

			// Exec command and get output
			$output = shell_exec( $command );

			// debug
				debug_log(__METHOD__
					. " Notice: exec command: " . PHP_EOL
					. ' command: ' . $command . PHP_EOL
					. ' output: ' . $output
					, logger::WARNING
				);

			if( !$output ) {
				debug_log(__METHOD__
					. " Error processing media command: " . PHP_EOL
					. ' command: ' . $command
					, logger::ERROR
				);
				throw new Exception("Error processing media command", 1);
			}

		}catch(Exception $e){

			debug_log(__METHOD__
				. " Exception: " . PHP_EOL
				. $e->getMessage()
				, logger::ERROR
			);

			return false;
		}


		return true;
	}//end exec_command



	/**
	* EXEC_SH_FILE
	* Execute a pre-built shell script in the background and return its OS PID.
	*
	* The script is launched via `sh <file> > /dev/null & echo $!` so the PHP
	* process does not block. stdout of the script is discarded (redirected to
	* /dev/null); stderr is NOT redirected, so errors from the script reach the
	* web-server error log.
	*
	* The PID is captured from $output[0] (the `echo $!` expansion). A null PID
	* is returned — not an exception — when exec() produces no output, because
	* the script may still be running; callers should treat null as "unknown".
	*
	* Security: $file must be a server-generated path. Currently the only caller
	* is component_av::Save(), which passes a temp .sh file created by media_engine.
	* escapeshellarg() provides defence-in-depth against future callers that might
	* interpolate user-controlled paths.
	*
	* @param string $file - absolute path to the .sh file to execute
	* @return ?int $PID - OS process ID of the spawned script, or null when unavailable
	*/
	public static function exec_sh_file(string $file) : ?int {

		$PID = null;

		try {
			// exec("sh $file > /dev/null &", $output); # funciona!!! <<<<
			// exec("sh $file > /dev/null 2>&1 & echo $!", $output); # return pid
			// $response = exec("sh $file > /dev/null 2>&1 & echo $!", $output);

			// exec command from sh file. Security: $file must be a server-built
			// path (currently only `component_av::Save` passes a temp .sh file
			// generated by `media_engine`); escapeshellarg adds defence-in-depth
			// against any future caller that interpolates user-controlled paths.
				$response = exec("sh " . escapeshellarg($file) . " > /dev/null & echo $!", $output);

			// response check. Could be empty
				if ( empty($response) ) {
					debug_log(__METHOD__
						. " Warning processing media file. response is empty: " . PHP_EOL
						. ' file: ' . $file
						, logger::WARNING
					);
				}

			// PID. Output returns the PID as ["3647"]
				$PID = isset($output[0])
					? (int)$output[0]
					: null;

			return $PID;

		}catch(Exception $e){

			debug_log(__METHOD__
				. " Exception: " . PHP_EOL
				. ' Exception message: ' . $e->getMessage()
				, logger::ERROR
			);
		}

		return $PID;
	}//end exec_sh_file




	// SEC-045: removed unused helpers `exec_sh_file_isolated`, `getCommandPath`,
	// `live_execute_command`. Each had zero callers in production / CLI / tests
	// (verified by repo-wide grep) and used raw shell interpolation that would
	// have been Class C/D had they been revived. If any of these helpers is
	// reintroduced, route through `request_cli` (below — uses `escapeshellarg`)
	// or `proc_open` with an arg array; never interpolate user-supplied strings
	// into a shell command line.



	/**
	* REQUEST_CLI
	* Spawn a background PHP process that invokes a given class method via process_runner.php.
	*
	* This is the standard mechanism for running long-lived or CPU-intensive Dédalo operations
	* (tool exports, area_maintenance tasks, etc.) without blocking the HTTP request.
	*
	* Flow:
	* 1. Serialises the target class/method/params and the current session context into JSON.
	* 2. Writes the JSON as a shell argument to process_runner.php (run under `nohup nice -n 19`).
	* 3. Captures the child PID from the `echo $!` shell expansion via the `process` helper.
	* 4. Registers (user_id, PID, pfile) in the `processes` DB table so dd_utils_api can
	*    poll status and stream the output file back to the client.
	*
	* The output file ($pfile) is stored in DEDALO_SESSIONS_PATH and receives whatever
	* process_runner.php writes to stdout (JSON-encoded result). The client polls
	* dd_utils_api::get_process_status with the pfile name to read progress.
	*
	* Params are passed through to process_runner.php WITHOUT safe_xss sanitization because
	* they are application data (e.g. SQO filter values containing '>' operators) and not
	* rendered as HTML. The runner now enforces the same rule on its side.
	*
	* (!) process_runner.php enforces authentication (login::is_logged) and an opt-in
	* BACKGROUND_RUNNABLE allowlist on the target class; exec_::request_cli is not
	* a way to bypass Dédalo's permission model.
	*
	* @param object $options - dispatch descriptor:
	*   {
	*     class_name:  string  - PHP class to invoke (e.g. 'tool_export')
	*     method_name: string  - static method on that class (e.g. 'export_records')
	*     class_file:  string  - optional absolute path to include before invoking
	*     params:      object  - arbitrary options forwarded to the method as its sole argument
	*   }
	* @return object $response - {
	*   result: bool,    - always true on the happy path (errors throw before returning)
	*   pid:    int,     - OS PID of the spawned process_runner.php child
	*   pfile:  string,  - process output filename (basename only; prepend get_process_path())
	*   msg:    string   - human-readable status line
	* }
	*/
	public static function request_cli(object $options) : object {

		// options
			$class_name		= $options->class_name;
			$method_name	= $options->method_name;
			$class_file		= $options->class_file;
			$params			= $options->params;

		// params. Pass through without safe_xss sanitization — params are
		// application data (e.g. SQO filter values with '>' operators) not
		// rendered as HTML. htmlspecialchars() corrupts such operational values.
		// The direct (non-CLI) path also passes options unsanitized to tool
		// methods, and process_runner.php now skips params sanitization too.
			$safe_params = $params;

		// server_vars
			// sh_data mandatory vars
			$sh_data = [
				'server' => [
					'HTTP_HOST'		=> $_SERVER['HTTP_HOST'] ?? 'localhost',
					'REQUEST_URI'	=> $_SERVER['REQUEST_URI'] ?? '/',
					'SERVER_NAME'	=> $_SERVER['SERVER_NAME'] ?? $_SERVER['HTTP_HOST'] ?? 'development'
				],
				'session_id'		=> session_id(),
				'error_log_path'	=> system::get_error_log_path(), // current PHP-FPM path to use the same error output
				'user_id'			=> logged_user_id(),
				'class_name'		=> $class_name, // class name
				'method_name'		=> $method_name, // method name
				'file'				=> $class_file, // class file to include optional
				'params'			=> $safe_params // object with options passed to the function
			];
			$server_vars = json_encode($sh_data, JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);

		// process file (temporal file where store function output)
			$pfile			= process::get_unique_process_file(); // like 'process_1_2024-03-31_23-47-36_3137757' usually stored in the sessions directory
			$file_path		= process::get_process_path() .'/'. $pfile; // output file with errors and stream data

		// process_runner. File to sh execute that manage given vars calling desired class and method
			$process_runner	= DEDALO_CORE_PATH . '/base/process_runner.php';

		// php binary. Resolve instead of trusting the raw PHP_BIN_PATH constant.
			// (!) PHP_BIN_PATH defaults to '/usr/bin/php' (config catalog db.php_bin_path), which does
			// NOT exist on macOS/Homebrew or on any non-standard layout. Spawning a missing binary is
			// invisible from here: the shell still forks (so `echo $!` returns a live-looking pid), the
			// output file stays empty, and the "no such file or directory" goes to stderr, which this
			// command discards. The caller then polls an empty file and reports a phantom "completed"
			// process. system::get_php_bin() applies the same resolution dd_cache already relies on
			// (configured path if real → platform base → PATH lookup).
			$php_bin = class_exists('system')
				? system::get_php_bin()
				: PHP_BIN_PATH;

			// Fail loudly rather than spawning into the void.
			if (empty($php_bin) || !is_file($php_bin)) {
				$msg = 'Error. PHP binary not found. Unable to run the background process.';
				debug_log(__METHOD__
					. ' ' . $msg . PHP_EOL
					. ' resolved php_bin: ' . to_string($php_bin) . PHP_EOL
					. ' PHP_BIN_PATH: ' . (defined('PHP_BIN_PATH') ? PHP_BIN_PATH : '(undefined)')
					, logger::ERROR
				);

				$response = new stdClass();
					$response->result	= false;
					$response->msg		= $msg;
					$response->errors	= [
						'php_bin_not_found: ' . to_string($php_bin)
						. '. Set db.php_bin_path (PHP_BIN_PATH) to the real PHP CLI binary.'
					];

				return $response;
			}

		// command composition
			// stderr is NOT merged into $file_path: that file is the process output stream the client
			// parses as JSON, and PHP warnings/notices would corrupt it (that is why `2>&1` was
			// removed). But it must not be dropped either — anything the child writes to stderr before
			// PHP can install its own error handler (a missing binary, a startup fatal) would vanish.
			// Append it to the same error log the child itself uses, so it lands in the server log.
			$cmd		= escapeshellarg($php_bin) . " $process_runner " . escapeshellarg($server_vars);
			$error_log	= system::get_error_log_path();
			$stderr		= !empty($error_log)
				? ' 2>>' . escapeshellarg($error_log)
				: '';
			$command	= "nohup nice -n 19 $cmd >$file_path$stderr & echo $!";

			// debug
				debug_log(__METHOD__
					." Running tool task in background ($pfile)". PHP_EOL
					." Command: ". PHP_EOL. to_string($command)
					, logger::DEBUG
				);

		// process creation
			$process	= new process($command);
			$pid		= $process->getPid();

		// store process info
			processes::add(
				logged_user_id(),
				$pid,
				$pfile
			);

		// response OK
			$response = new stdClass();
				$response->result	= true;
				$response->pid		= $pid;
				$response->pfile	= $pfile;
				$response->msg		= 'OK. Running publication ' . $pid;


		return $response;
	}//end request_cli



}//end class exec_



/**
* CLASS PROCESS
* Lightweight Linux-only wrapper for tracking and controlling a single OS process by PID.
*
* Encapsulates the three operations that Dédalo needs over a background process:
* - Launch a command via exec() and capture its PID (constructor with argument).
* - Query whether the process is still alive (status → ps -p).
* - Read the last line of its output file (read → tail -n 1).
* - Send SIGTERM (stop → kill).
*
* Two usage patterns exist:
*   a) Launch mode: `new process($command)` — runs the command and stores the PID.
*   b) Attach mode: `new process()` then `setPid()` + `setFile()` — used by dd_utils_api
*      to inspect a process that was spawned in a previous request.
*
* Also provides two static utility methods for process file naming:
*   - get_unique_process_file() — builds a deterministic, per-user, per-millisecond filename.
*   - get_process_path()        — resolves the directory where process output files are stored.
*
* Compatibility: Linux only. The `ps -p <pid>` and `kill <pid>` commands are POSIX
* but the specific flag and output format assumed by status() targets Linux; macOS and
* Windows are not supported.
*
* @package Dédalo
* @subpackage Core
*/
class process {

    /**
    * OS process ID captured after exec() or injected via setPid().
    * Null when the process has not yet been started or the PID is unavailable.
    * @var ?int $pid
    */
    private ?int $pid = null;

    /**
    * Shell command string passed to the constructor and used by start() / runCom().
    * Null when the instance is created in attach mode (no-arg constructor).
    * @var ?string $command
    */
    private ?string $command = null;

    /**
    * Absolute path to the process output file read by read().
    * Set externally via setFile(); not populated in launch mode.
    * @var ?string $file
    */
    private ?string $file = null;

    /**
    * __CONSTRUCT
    * Create the process instance, optionally launching a command immediately.
    *
    * Launch mode: pass a non-empty command string; the constructor calls runCom()
    * which executes the command and stores the resulting PID.
    * Attach mode: omit the argument (or pass null); the caller must then call
    * setPid() and setFile() to inspect a process from a previous request.
    *
    * @param ?string $cl - shell command to execute, or null for attach mode
    */
    public function __construct(?string $cl=null) {
        if ($cl != false){
            $this->command = $cl;
            $this->runCom();
        }
    }

    /**
    * RUNCOM
    * Execute $this->command via exec() and capture the spawned PID from output[0].
    *
    * The command is expected to end with `& echo $!` so that exec() receives the
    * PID as the sole output line. Called automatically by __construct() in launch mode.
    *
    * @return void
    */
    private function runCom() : void {
    	// reference command for non blocking process
		// $command = 'nohup '.$this->command.' > /dev/null 2>&1 & echo $!';
		$command = $this->command; // untouched command

		// debug
		if(SHOW_DEBUG===true) {
			debug_log(__METHOD__
				. " Executing process command: " . PHP_EOL
				. $command
				, logger::DEBUG
			);
		}

        exec($command, $output);
        $this->pid = (int)$output[0];
    }

    /**
    * SETPID
    * Inject a known PID into an attach-mode instance.
    *
    * Used by dd_utils_api::get_process_status when the process was spawned in a
    * prior HTTP request and the caller holds only a stored PID.
    *
    * @param ?int $pid - OS process ID to track
    * @return void
    */
    public function setPid(?int $pid) : void {
        $this->pid = $pid;
    }

    /**
    * GETPID
    * Return the OS process ID stored in this instance.
    *
    * @return ?int - PID set by the constructor or setPid(), or null if not yet set
    */
    public function getPid() : ?int {
        return $this->pid;
    }

    /**
    * STATUS
    * Check whether the tracked process is still alive.
    *
    * Runs `ps -p <pid>` and inspects the second output line; if it is absent the
    * process has exited. The PID is int-cast before interpolation (SEC-043).
    *
    * @return bool - true when the process is running; false when it has exited or is unknown
    */
    public function status() : bool {
        // SEC-043 defence-in-depth: cast pid to int. `setPid()` accepts arbitrary
        // input from `dd_utils_api::get_process_status` (which now does its own
        // ownership check), but quoting here means future callers cannot inject
        // shell metacharacters through the pid path.
        $command = 'ps -p '.(int)$this->pid;
        exec($command, $output);
        if (!isset($output[1]))return false;
        else return true;
    }

    /**
    * START
    * Re-run the stored command, launching the process a second time.
    *
    * This method is a thin wrapper around runCom(). It is provided for symmetry with
    * stop(), but in practice Dédalo always spawns processes through the constructor.
    * Note: always returns true — even when $this->command is empty — which is a
    * known quirk of the original implementation; callers should not rely on the
    * return value to detect failure.
    *
    * @return bool - always true
    */
    public function start() : bool {
        if ($this->command != '') {
            $this->runCom();
            return true;
        }
        return true;
    }

    /**
    * STOP
    * Send SIGTERM to the tracked process and confirm it has exited.
    *
    * Runs `kill <pid>` then calls status() to verify the process is gone.
    * The PID is int-cast before interpolation (SEC-043).
    *
    * @return bool - true when the process is no longer running; false when it survived the signal
    */
    public function stop() : bool {
        // SEC-043 defence-in-depth: int-cast pid before shell interpolation.
        $command = 'kill '.(int)$this->pid;
        exec($command);
        if ($this->status() === false) return true;
        else return false;
    }

    /**
    * SETFILE
    * Set the absolute path to the process output file to be read by read().
    *
    * Called by processes::get_process_item() before read() when inspecting a
    * previously spawned background process in attach mode.
    *
    * @param ?string $file - absolute path to the process output file
    * @return void
    */
    public function setFile(?string $file) : void {
        $this->file = $file;
    }

    /**
    * READ
    * Return the last line of the process output file.
    *
    * Uses `tail -n 1` on $this->file (shell-quoted via escapeshellarg, SEC-043).
    * The file must first be set via setFile(). Returns an empty array when the
    * file does not exist or is empty.
    *
    * @return array $output - array of output lines from exec() (typically a single-element array)
    */
    public function read() : array {
        // SEC-043 defence-in-depth: shell-quote $this->file. Currently set only
        // through `processes::get_process_item()` (server-generated path from
        // `get_unique_process_file()`); the helper now enforces escaping so
        // future callers cannot regress.
        $command = 'tail -n 1 '.escapeshellarg((string)$this->file);
        exec($command, $output);
        return $output;
    }

    /**
	* GET_UNIQUE_PROCESS_FILE
	* Build a unique output-file basename for a background process.
	*
	* The name embeds the current user ID, a human-readable timestamp, and a
	* high-resolution nanosecond counter (hrtime) so that two processes started
	* by the same user in the same second receive different filenames.
	*
	* Example output: 'process_1_2024-03-31_23-47-36_3137757000'
	*
	* The returned value is a basename only (no directory component). Callers must
	* prepend get_process_path() to obtain the full path.
	*
	* @return string $name - unique process file basename
	*/
	static function get_unique_process_file() : string {

		$name = 'process_' . logged_user_id() .'_'. date('Y-m-d_H-i-s') .'_'. hrtime(true);

		return $name;
	}//end get_unique_process_file

	/**
	* GET_PROCESS_PATH
	* Resolve the directory where process output files are stored.
	*
	* Returns DEDALO_SESSIONS_PATH when that constant is defined (the normal
	* production case), falling back to session_save_path() and then '/tmp'.
	* Using the sessions directory co-locates process files with PHP session data,
	* which keeps them on the same filesystem and subject to the same cleanup policy.
	*
	* @return string $dir - absolute directory path (no trailing slash)
	*/
	static function get_process_path() : string {

		$dir = defined('DEDALO_SESSIONS_PATH')
			? DEDALO_SESSIONS_PATH
			: (@session_save_path() ?? '/tmp');

		return $dir;
	}//end get_process_path

}//end class process
