<?php

	# VISUALIZADOR HTML	

	$html_content = '';
	switch(true) {
		
		case ($permissions<1) :
					$html_content .= "";
					break;
			
		case ($permissions>=1) :
					$html_content .= $valor;

					if(SHOW_DEBUG===true) {
						$html_content .= "<span class=\"component_select_lang_debug debug_info\">".exec_time($start_time)."</span>";
					}
					break;
	}
	
	# PRINT HTML
	print $html_content;
?>