<h1><?php print_r($_SERVER['SERVER_NAME']); ?> API Test enviroment</h1>
<h5>Calling to <?php echo parse_url(JSON_TRIGGER_URL)['host'] ?></h5>
<h4> </h4>
<?php
# Menu
echo $menu_html;

# Breadcrumb
if ($this->breadcrumb!==false) {
	echo '<ul id="breadcrumb">';
	foreach ($this->breadcrumb as $key => $breadcrumb_row) {

		$link = $breadcrumb_row->web_path;

		echo '<li>';
		echo '<a href="'.$link.'">';
		echo $breadcrumb_row->term;
		echo '</a>';
		echo '</li>';
	} 
	echo '</ul>';
}//end if ($this->breadcrumb!==false)
?>