<?php

	# VISUALIZADOR HTML

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in', $modo, $lang);

	print "<div class=\"wrap_component css_wrap_component_security_areas wrap_component_{$tipo}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato=\"\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-component_info='{$component_info}' ";
	print ">";

	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch(true) {
			
		case ($permissions==0)	:
				$html_contenido .= "No access here"; 
				break;
						
		case ($permissions>=1):
				
				$html_contenido .= "<div class=\"security_areas_tree\">";

				$max_input_vars = ini_get("max_input_vars");
				if ($max_input_vars<2000) {
					$html_contenido .= "<div class=\"error\">PHP directive 'max_input_vars' is too small ($max_input_vars).
					This can truncate your data when manage big structures with thousands of elements.<br>
					Please configure your instalation with max_input_vars value with 2000 or higher to use security access safely</div>";
				}
				
				$html_contenido .= $html_tree;
				$html_contenido .= "</div>";	
	
				if(SHOW_DEBUG) {
					#$html_contenido .= " <span id=\"debugger_{$tipo}\" class=\"css_span_debugger\">{$debugger}</span>";	
				}
				break;							
	}

	# Prepare content to show in page
	tools::prepare_content($html_contenido);
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "</div>"; //wrap


	# script
	print "<script>";
	print "component_security_areas.update_area_childrens_obj_opened();";
	print "component_security_areas.update_area_access_obj_opened();";
	print "</script>";
		

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out', $modo, $lang);

?>