<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_section_list_wrap']))		$ar_css['css_section_list_wrap']='';
	if(!isset ($ar_css['css_section_list_titulo']))		$ar_css['css_section_list_titulo']='';
	if(!isset ($ar_css['css_span_dato'])) 				$ar_css['css_span_dato']='';;
	
	
	
	print "\n\n<!-- SECTION LIST (RELATION MODE) [tipo:$tipo id_matrix:$id] -->";
	/*
	print "\n<div class=\"css_section_list_wrap {$ar_css['css_section_list_wrap']}\" id=\"{$id_wrapper}\"
	data-id_matrix=\"{$caller_id}\" data-tipo=\"\" data-lang=\"\" data-parent=\"\" data-modo=\"{$modo}\" data-dato=\"\" data-current_tipo_section=\"{$current_tipo_section}\" data-component_name=\"{$component_name}\" >";
	*/
	# USADO PARA ORDENAR (JS)
	print "\n<script type=\"text/javascript\">var page_query_string = '$page_query_string';</script>";
				
	
	# CONTENIDO (INPUT)
	$html_contenido  = '';
	#$html_contenido  = "\n<div class=\"css_section_group_content\" >";

	
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." </span>";
					break;
						
		case ($permissions>=1)	:
		
					if (empty($rows_html)) {

						$html_contenido .= "<span class=\"row_no_records_found\">". label::get_label('no_se_encontraron_registros'). "</span>";

					}else{
						
						$html_contenido .= "\n<table class=\"css_section_list_table_relation\">";
					
						# SEARCH FILTER
						#$html_contenido .= $rows_search_html;					
						
						# PAGINATOR
						#$html_contenido .= $rows_paginator_html;
						
						# TH TITULOS
						$html_contenido .= "\n<thead>";
						$html_contenido .= $rows_header_html;
						$html_contenido .= "\n</thead>";
						
						# TD DATOS
						$html_contenido .= "\n<tbody>";
						$html_contenido .= $rows_html;
						$html_contenido .= "\n</tbody>";				
						
						/*
						# DELETE DIALOG
						$html_contenido .= "<!-- ui-dialog -->
											<div id=\"delete_dialog\" title=\"Delete\">								
												<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
												Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>								
											</div>
											";
						*/
						$html_contenido .= "\n</table>";
					}
					
					break;							
	}
	
	#$html_contenido .= "\n</div>";

	# Prepare content to show in page
	#tools::prepare_content($html_contenido);
	
	# PRINT HTML
	print $html_contenido;
	
	
	#print "\n</div><!-- /css_section_list_wrap -->\n\n";//wrap


	
?>