<?php
	
	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_section_list_wrap']))		$ar_css['css_section_list_wrap']='';
	if(!isset ($ar_css['css_section_list_titulo']))		$ar_css['css_section_list_titulo']='';
	if(!isset ($ar_css['css_span_dato'])) 				$ar_css['css_span_dato']='';;
	
	
	
	print "\n\n<!-- SECTION LIST LIST [tipo:$tipo id_matrix:$id] -->";
	print "\n<div class=\"css_section_list_wrap {$ar_css['css_section_list_wrap']}\" id=\"wrap_{$tipo}\" >";


	

	
	# USADO PARA ORDENAR (JS)
	print "\n<script>var page_query_string='$page_query_string';</script>";
				
	# ETIQUETA (LABEL)
	#$html_label = component_common_draw::draw_label($this);
	#print "\n<hr><div class=\"css_section_group_titulo tap_title\" > $html_label </div>";
	
		
	
	# CONTENIDO (INPUT)
	$html_contenido  = "\n<div class=\"css_section_group_content tap_content\" >";
	#$html_contenido .= $group_search_html;	
	
	
	
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." </span>";
					break;
						
		case ($permissions>=1)	:
					
				# BUTTONS
				$html_contenido .= "\n<div class=\"section_buttons_container\">";
				foreach ($this->section_obj->ar_buttons as $current_button_modelo_name => $current_ar_button_obj_model) {
					# Skip delete button
					if($current_button_modelo_name=='button_delete') continue;
					foreach($current_ar_button_obj_model as $current_button_obj) {
						# Se buuton target tipo
						$current_button_obj->set_target($section_tipo);
						$html_contenido .= $current_button_obj->get_html();
					}
						
				}
				$html_contenido .= "\n</div>";#end section_buttons_container


				#$html_contenido .= "\n<div id=\"stats_info\"><!-- Stats content here --></div>";


				# LIST (Search,paginator,rows)
				$html_contenido .= "\n<div class=\"main_list\">";

					# SEARCH FILTER
					$html_contenido .= $rows_search_html;					
					
					
					# PAGINATOR
					$html_contenido .= $rows_paginator_html;

					$html_contenido .= "\n<table class=\"css_section_list_table box_shadow_1 box_border_radius_1\">";
					$html_contenido .= "\n <caption style=\"text-align:left;\"> $section_name </caption>";
					
					# TH TITULOS
					$html_contenido .= $rows_header_html;
					
					# TD DATOS
					$html_contenido .= $rows_html;					
					
					/*
					# DELETE DIALOG
					$html_contenido .= "<!-- ui-dialog -->
										<div id=\"delete_dialog\" title=\"Delete\">								
											<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
											Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>								
										</div>
										";
					*/
					$html_contenido .= "\n</table>";

				$html_contenido .= "\n</div><!-- /main_list -->";#end main_list
								
	}
	
	$html_contenido .= "\n</div><!-- /css_section_group_content -->";
	
	# PRINT HTML
	print $html_contenido;
	
	
	print "\n</div><!-- /css_section_list_wrap -->\n\n"; //wrap
?>