<?php
	

	# VISUALIZADOR HTML

	$html    = "<!-- $tool_name PAGE [tipo:$tipo] -->";	
	#$html   .= "<div class=\"wrap_tool wrap_tool_indexation_page\" >";	
	
	#
	# HEADER TOOL
	$header_html='';
	$header_html .= "<div class=\"header_tool\">";

		#
		# TOOL NAME
		$header_html .= "<div class=\"header_info header_tool_name tool_indexation_icon\">";
		$header_html .= label::get_label($tool_name) ;
		$header_html .= "</div>";//end header_tool_name

		#
		# HEADER_TOOL_TABS
		$header_html .= "<ul class=\"header_tool_tabs\">";
		$header_html .= "<li class=\"tab_active\" onclick=\"tool_common.change_view_selector(this,'thesaurus','tesaurus_frame')\">Thesaurus</li>";
		$header_html .= "<li class=\"\" onclick=\"tool_common.change_view_selector(this,'media','tesaurus_frame')\">Video</li>";
		$header_html .= "</ul>";
		$header_html .= "<script>";
		$header_html .= "tool_common.media_frame_url='$av_player_url';";
		$header_html .= "</script>";


		#
		# INFO
		$header_html .= "<div class=\"header_info\">";
		$header_html .= $section_label;
		$header_html .= ' | ' . $section_id . ' | ';
		if (is_object($inverse_code)) {
			$header_html .= $inverse_code->value;
		}
		$header_html .= "</div>";//end header_info

		#
		# TOP_ID SELECTOR	
		if (isset($inverse_locators) && is_array($inverse_locators)) {
			
			$header_html .= "<div class=\"top_id_selector\">";

			$header_html .= "<label>".label::get_label('enfoque')."</label> : ";
			$header_html .= "<select id=\"top_id_selector\" class=\"custom_dropdown\" onchange=\"$tool_name.update_top_id(this)\">";
			#$header_html .= " <option></option>";
			$ar_inverse = $this->get_ar_inverse($inverse_locators);
			foreach ($ar_inverse as $current_id => $current_name) {
				$selected = $current_id==TOP_ID ? ' selected' : '';
				$header_html .= "<option value=\"$current_id\"{$selected}>$current_name</option>";
			}
			$header_html .= "</select>";

			$header_html .= "<script>";
			$header_html .= "{$tool_name}.update_top_id(document.getElementById('top_id_selector'));";			
			$header_html .= "</script>";

			$header_html .= "</div>";//end top_id_selector	
		}


		$header_html .= "<div class=\"header_buttons\">";	
			#
			# BUTTON_TOOL_TR_PRINT_HTML
			if (isset($button_tool_tr_print_html)) {
				$header_html .= $button_tool_tr_print_html;
			}
			#
			# BUTTON_TOOL_TIME_MACHINE_HTML
			if (isset($button_tool_time_machine_html)) {
				$header_html .= $button_tool_time_machine_html;
			}
		$header_html .= "</div>";//end header_buttons


		#
		# COMPONENT STATE
		$header_html .= $component_state_html;


	$header_html .= "</div>";//end header_tool
	$html .= $header_html;


	#
	# CONTENT 
	$html .= "<div id=\"indexation_container\" class=\"container\">";		

		#
		# LEFT SIDE
		$html   .= "<div id=\"left_side\" class=\"split split-horizontal left_side\">";	
	
			#
			# THESAURUS (IFRAME)
			$html .= "<div class=\"indexation_page_tesauro\">";

				#$html   .= "<div class=\"indexation_page_tesauro\">";
				#$html 	.= " <iframe id=\"tesauro_frame\" name=\"tesauro_frame\" class=\"tesauro_frame\" src=\"{$tesauro_url}\" ></iframe>";
				$html .= "<iframe id=\"videoFrame\" name=\"videoFrame\" class=\"media_frame\" src=\"\"></iframe>"; // {$av_player_url}
				$html .= "<iframe id=\"tesaurus_frame\" name=\"tesaurus_frame\" class=\"tesaurus_frame\" src=\"{$thesaurus_url}\"></iframe>";
				#$html   .= "</div>";

			$html .= "</div>";

			
		$html   .= "</div>";#end left_side



		#
		# RIGHT SIDE
		$html   .= "<div id=\"right_side\" class=\"split split-horizontal right_side\">";
		
			#
			# TEXT (TEXT AREA)
			$html   .= "<div id=\"indexation_page_text\" class=\"indexation_page_text\">";
			$html 	.= $component_text_area_html;
			$html   .= "</div>";			
			

			#$html   .= "<div id=\"indexation_page_list\" class=\"css_section_tab_content\">";
			
				#
				# TERM LIST
				$html   .= "<div id=\"indexation_page_list\" class=\"css_section_tab_content indexation_page_list\">";
				$html 	.= label::get_label('seleccione_una_etiqueta_para_indexar') . '<br>';
				$html 	.= label::get_label('para_crear_un_fragmento');
				$html   .= "</div>";

			#$html   .= "</div>";			
			
			
		$html   .= "</div>";#end right_side


	
	$html .= "</div><!-- /container -->";
	#$html .= "</div><!-- /wrap_tool -->"; //wrap_tool

	
	# Inspector log tool
	#$html .= "<div id=\"inspector_log\" class=\"tool_transcription_inspector_log\"> </div>";
	# INSPECTOR LOG TOOL_LANG ()
	$html 	.= "<div id=\"inspector_log\" class=\"tool_inspector_log\"></div>";


	# Init tool
	$html .= "<script>";
	$html .= "$tool_name.init({textarea_lang:'$original_lang'});";
	$html .= "</script>";


	echo $html;



?>