/**
 * THE ENGINE PAIRING FRAGMENT — what the work host's engine will need to reach this agent.
 * Pure, zero-dep, stamped, SECRET-FREE. Shape copied from
 * publication/site_builder/src/provision/render/engine_fragment.ts.
 *
 * THE KEY NAMES ARE PROPOSED, NOT LIVE: the engine client, registry and config catalog are
 * phase 3, which may rename them (then it edits ENGINE_KEYS and re-renders the committed
 * examples). The header says so, so an operator does not append it to a production .env.
 *
 * Two placeholders, both self-refusing (never empty, never plausible): the bearer VALUE (read
 * as root on this host) and the engine bundle PATH on the work host (this host cannot know
 * it). cli.ts's secret guard exempts TOKEN_PLACEHOLDER by value. The fingerprint IS rendered:
 * it is not secret (the agent publishes it on /health) and it lets the engine prove the pasted
 * token and instance before its first call.
 *
 * The recipe is spelled through PAIRING_FINGERPRINT_PREFIX, never as a literal: the pairing
 * tripwire (test/unit/publication_host_pairing_tripwire.test.ts, Rule 5) allows the prefix literal in exactly two recipe files.
 */

import { instanceFingerprint, PAIRING_FINGERPRINT_PREFIX } from '../../security/pairing';
import type { AgentLayout } from '../layout';
import type { Artifact, RenderFacts, Renderer } from './types';
import { artifact } from './types';

export const ENGINE_KEYS = Object.freeze({
  instance: 'DEDALO_PUBLICATION_HOST_INSTANCE',
  url: 'DEDALO_PUBLICATION_HOST_URL',
  socket: 'DEDALO_PUBLICATION_HOST_SOCKET',
  tlsBundle: 'DEDALO_PUBLICATION_HOST_TLS_BUNDLE',
  token: 'DEDALO_PUBLICATION_HOST_TOKEN',
  fingerprint: 'DEDALO_PUBLICATION_HOST_FINGERPRINT',
});

export const TOKEN_PLACEHOLDER = 'PASTE_THE_SERVICE_TOKEN_VALUE_HERE';
export const BUNDLE_PLACEHOLDER = 'PASTE_THE_ENGINE_BUNDLE_PATH_ON_THE_WORK_HOST_HERE';
export const FINGERPRINT_PENDING = 'PENDING_SERVICE_TOKEN_NOT_MINTED_RERUN_PROVISION_APPLY';

/** The agent's BASE_PATH (Global Constraints: closed route table). */
export const AGENT_BASE_PATH = '/publication/host_agent';

/** The agent refuses a shorter token (src/config.ts); so does the fact. */
const MIN_TOKEN_LENGTH = 32;
const FINGERPRINT_SHAPE = /^[0-9a-f]{64}$/;
const FORBIDDEN_IN_VALUE = /["'`$\\]|[\u0000-\u001f\u007f]/;

function assignment(key: string, value: string): string {
  if (value.length === 0 || FORBIDDEN_IN_VALUE.test(value)) {
    throw new Error(`render(engine_fragment): the value of ${key} is empty or unsafe in an env file. Nothing was rendered.`);
  }
  return `${key}="${value}"`;
}

/** `https://<host>:<port>/publication/host_agent`, IPv6 bracketed. */
export function agentUrl(host: string, port: number): string {
  return `https://${host.includes(':') ? `[${host}]` : host}:${port}${AGENT_BASE_PATH}`;
}

/**
 * The render facts from the minted SERVICE_TOKEN, read through `readCredential` (the CLI's
 * root-only reader). The token is hashed here and never leaves this function.
 */
export function renderFacts(layout: AgentLayout, readCredential: (path: string) => string | null): RenderFacts {
  const raw = readCredential(layout.serviceTokenPath);
  if (raw === null) return { fingerprint: null };
  const token = raw.trim();
  if (token.length < MIN_TOKEN_LENGTH) {
    throw new Error(
      `provision: the service token at ${layout.serviceTokenPath} is shorter than ${MIN_TOKEN_LENGTH} characters; ` +
        `the agent would refuse to boot with it. Nothing was rendered.`,
    );
  }
  return { fingerprint: instanceFingerprint(layout.instance, token) };
}

export const engineFragmentRenderer: Renderer = {
  kind: 'engine_fragment',
  render(layout: AgentLayout, facts: RenderFacts): Artifact[] {
    if (facts.fingerprint !== null && !FINGERPRINT_SHAPE.test(facts.fingerprint)) {
      throw new Error(`render(engine_fragment): facts.fingerprint is not 64 lowercase hex. Nothing was rendered.`);
    }
    const lines: string[] = [
      `# GENERATED by publication/host_agent/src/provision/render/engine_fragment.ts — do NOT edit.`,
      `# Dédalo publication host — engine pairing fragment for instance '${layout.instance}'.`,
      `#`,
      `# PROPOSED KEY NAMES (phase 3). No engine release reads these keys yet: the engine-side`,
      `# client, registry and config catalog land in phase 3, which may rename them. Keep this`,
      `# file; do not append it to the engine's .env until the engine documents these keys.`,
      `#`,
      `# The work host's .env is APPEND-ONLY and takes documented keys only.`,
      ``,
      `# Which agent this engine pairs with (part of the fingerprint below; never published).`,
      assignment(ENGINE_KEYS.instance, layout.instance),
      ``,
    ];
    if (layout.listen.kind === 'tls') {
      lines.push(
        `# mTLS (D1/D2). The engine presents the client certificate from the bundle and pins the`,
        `# bundle's CA for the server. The bundle is ${layout.engineBundlePath}`,
        `# on THIS host (root, 0600): carry it to the work host, keep it 0600 owned by the engine user,`,
        `# then put its path below.`,
        assignment(ENGINE_KEYS.url, agentUrl(layout.listen.host, layout.listen.port)),
        assignment(ENGINE_KEYS.tlsBundle, BUNDLE_PLACEHOLDER),
      );
    } else {
      lines.push(
        `# Single machine (spec §1.1): a unix socket, 0660, group '${layout.identity.engineGroup}'. No TLS.`,
        `# The engine's user must be a member of that group.`,
        assignment(ENGINE_KEYS.socket, layout.listen.socketPath),
      );
    }
    lines.push(
      ``,
      `# THE BEARER — named here, never valued here. Read it as root on this host and paste it:`,
      `#   sudo cat ${layout.serviceTokenPath}`,
      assignment(ENGINE_KEYS.token, TOKEN_PLACEHOLDER),
      ``,
      `# sha256('${PAIRING_FINGERPRINT_PREFIX}' + instance + '\\n' + token): what the agent publishes on`,
      `# GET ${AGENT_BASE_PATH}/health as instance_fingerprint. The engine refuses a pairing whose`,
      `# own instance + token do not hash to it — a mis-pasted token names itself.`,
      assignment(ENGINE_KEYS.fingerprint, facts.fingerprint ?? FINGERPRINT_PENDING),
      ``,
    );
    return [artifact(layout, { kind: 'engine_fragment', path: layout.engineFragmentPath, mode: 'engineFragment', body: lines.join('\n') })];
  },
};
