/**
 * The agent's env file — `<config_base>/<instance>/agent.env`, 0644 root:root. The unit names
 * it through Task 1's DEDALO_HOST_AGENT_ENV_FILE and the agent's own config parses it (Task 9).
 *
 * Exactly `layout.envVars` (Task 1's env-file keys: INSTANCE for the instance,
 * never a credential: SERVICE_TOKEN arrives via systemd LoadCredential), one `KEY="value"`
 * per line, sorted. The quoting is the subset systemd and src/env_file.ts parseEnvFile read
 * identically; a value with a control character, `$` or a backtick is refused, not escaped.
 * Mirrors publication/site_builder/src/provision/render/env.ts (assignment()).
 *
 * ZERO-DEPENDENCY: root-repo tests import the renderers.
 */
import type { AgentLayout } from '../layout';
import { ENV_KEY_PATTERN, SECRET_LOOKING_KEY } from '../layout';
import type { Renderer } from './types';
import { artifact } from './types';

const CONTROL_CHARACTER = /[\x00-\x1f\x7f]/;
const SHELL_EXPANSION = /[$`]/;

export function envAssignment(key: string, value: string): string {
  if (!ENV_KEY_PATTERN.test(key)) {
    throw new Error(`render(env): '${key}' is not an environment variable name. Nothing was rendered.`);
  }
  if (SECRET_LOOKING_KEY.test(key)) {
    throw new Error(
      `render(env): '${key}' names a credential; this file may never carry one. Nothing was rendered.`,
    );
  }
  if (CONTROL_CHARACTER.test(value)) {
    throw new Error(`render(env): the value of ${key} contains a control character. Nothing was rendered.`);
  }
  if (SHELL_EXPANSION.test(value)) {
    throw new Error(`render(env): the value of ${key} contains '$' or a backtick. Nothing was rendered.`);
  }
  return `${key}="${value.replace(/[\\"]/g, '\\$&')}"`;
}

export function renderEnvBody(layout: AgentLayout): string {
  const lines = [
    '# GENERATED by the publication-host provisioner — do not edit.',
    `# Instance '${layout.instance}', declared in ${layout.declarationPath}.`,
    '# A hand edit is DRIFT: the stamp above hashes every byte below it, and the next',
    "# 'provision check' refuses to overwrite it. Change the declaration and re-run instead.",
    `# No credential is in this file: the service token reaches the agent through systemd`,
    `# LoadCredential from ${layout.serviceTokenPath}.`,
    '',
  ];
  for (const key of Object.keys(layout.envVars).sort()) {
    lines.push(envAssignment(key, layout.envVars[key] ?? ''));
  }
  return `${lines.join('\n')}\n`;
}

export const envRenderer: Renderer = {
  kind: 'env',
  render(layout) {
    return [
      artifact(layout, {
        kind: 'env',
        path: layout.envFile,
        mode: 'envFile',
        body: renderEnvBody(layout),
        effects: ['restart_agent'],
      }),
    ];
  },
};
