/**
 * The agent's env file — `<config_base>/<instance>/agent.env`, 0644 root:root. NOT a systemd
 * EnvironmentFile=: the agent's own src/config.ts parses it (render/unit_agent.ts only NAMES it
 * through DEDALO_HOST_AGENT_ENV_FILE), so one parser and one grammar read it.
 *
 * Exactly agentEnvVars(layout): `layout.envVars` (src/config.ts's env-file keys: INSTANCE for
 * the instance, never a credential: SERVICE_TOKEN arrives via systemd LoadCredential) plus the
 * two host-wide keys of the nginx media map (spec §13.4) — NGINX_MAP_MODE only when the
 * declaration's `web.nginx_map` is `conf_d`, HOST_BASE only when `paths.host_base` overrides
 * the default (the config's own defaults are `none` and layout.ts HOST_BASE, so a declaration
 * that sets neither keeps its bytes), and on a fapolicyd host TRUST_UNIT + TRUST_RESULT_FILE
 * (layout.trust: the root trust oneshot the agent starts after a release change) — one `KEY="value"` per line, sorted. The quoting is the subset systemd and src/env_file.ts parseEnvFile read
 * identically; a value with a control character, `$` or a backtick is refused, not escaped.
 * Mirrors publication/site_builder/src/provision/render/env.ts (assignment()).
 *
 * ZERO-DEPENDENCY: root-repo tests import the renderers.
 */
import type { AgentLayout } from '../layout';
import { ENV_KEY_PATTERN, HOST_BASE, SECRET_LOOKING_KEY } from '../layout';
import type { Renderer } from './types';
import { artifact } from './types';

const CONTROL_CHARACTER = /[\x00-\x1f\x7f]/;
const SHELL_EXPANSION = /[$`]/;

export function envAssignment(key: string, value: string): string {
  if (!ENV_KEY_PATTERN.test(key)) {
    throw new Error(`render(env): '${key}' is not an environment variable name. Nothing was rendered.`);
  }
  if (SECRET_LOOKING_KEY.test(key)) {
    throw new Error(
      `render(env): '${key}' names a credential; this file may never carry one. Nothing was rendered.`,
    );
  }
  if (CONTROL_CHARACTER.test(value)) {
    throw new Error(`render(env): the value of ${key} contains a control character. Nothing was rendered.`);
  }
  if (SHELL_EXPANSION.test(value)) {
    throw new Error(`render(env): the value of ${key} contains '$' or a backtick. Nothing was rendered.`);
  }
  return `${key}="${value.replace(/[\\"]/g, '\\$&')}"`;
}

/** Every key the env file carries: layout.envVars plus the host-map keys (see the header). */
export function agentEnvVars(layout: AgentLayout): Readonly<Record<string, string>> {
  const vars: Record<string, string> = { ...layout.envVars };
  if (layout.web.nginxMap === 'conf_d') vars.NGINX_MAP_MODE = 'conf_d';
  if (layout.host.base !== HOST_BASE) vars.HOST_BASE = layout.host.base;
  // fapolicyd hosts only: the trust unit the agent starts after a release change, and its record.
  if (layout.trust !== null) {
    vars.TRUST_UNIT = layout.trust.unit;
    vars.TRUST_RESULT_FILE = layout.trust.result;
  }
  return Object.freeze(vars);
}

export function renderEnvBody(layout: AgentLayout): string {
  const lines = [
    '# GENERATED by the publication-host provisioner — do not edit.',
    `# Instance '${layout.instance}', declared in ${layout.declarationPath}.`,
    '# A hand edit is DRIFT: the stamp above hashes every byte below it, and the next',
    "# 'provision check' refuses to overwrite it. Change the declaration and re-run instead.",
    `# No credential is in this file: the service token reaches the agent through systemd`,
    `# LoadCredential from ${layout.serviceTokenPath}.`,
    '',
  ];
  const vars = agentEnvVars(layout);
  for (const key of Object.keys(vars).sort()) {
    lines.push(envAssignment(key, vars[key] ?? ''));
  }
  return `${lines.join('\n')}\n`;
}

export const envRenderer: Renderer = {
  kind: 'env',
  render(layout, _facts) {
    return [
      artifact(layout, {
        kind: 'env',
        path: layout.envFile,
        mode: 'envFile',
        body: renderEnvBody(layout),
        effects: ['restart_agent'],
      }),
    ];
  },
};
