/**
 * THE v1 POOL (spec S5, decision A) — a dedicated, stamped PHP-FPM pool per instance, never the
 * site's: it runs as `v1.user` (never a web or catch-all account, layout.ts FORBIDDEN_V1_USERS)
 * with its own socket, `open_basedir` and temp directory. The website's PHP is never edited.
 * Paths come from the declared FPM flavour (layout.ts fpmLayout: Debian, EL AppStream, Remi SCL);
 * the socket's owner/group is the web server's account, DERIVED (site.fpm.webUser), never
 * discovered at render time. Effect `reload_fpm`, validator `fpm` (`php-fpm -t` after the rename,
 * under the host web lock; the reload restarts the workers of every pool of that PHP install —
 * init's confirmation says so).
 *
 * `group =` is not rendered: FPM then runs the pool with the user's primary group, which is what
 * the account was created with (`useradd --user-group`, init) — a name the declaration does not
 * hold would be a guess. `security.limit_extensions` admits exactly the web include's handler
 * pattern (`.php`, `.phar`, `.phtml`), so the two cannot disagree about what executes.
 *
 * INI INJECTION: every interpolated value is re-checked here (a newline, `]`, `=` or `;` would
 * open a new key or section).
 *
 * PURE, ZERO-DEPENDENCY.
 */
import type { AgentLayout } from '../layout';
import { ABSOLUTE_PATH_PATTERN, UNIX_NAME_PATTERN } from '../layout';
import type { Artifact, RenderFacts, Renderer } from './types';
import { artifact } from './types';

/** FPM's own name grammar for the section header we render (`dedalo_<instance>_v1`). */
export const POOL_NAME_PATTERN = /^dedalo_[a-z][a-z0-9_]{1,31}_v1$/;
/** The extensions the pool executes — the same set web_include.ts PHP_HANDLER_PATTERN routes to it. */
export const POOL_EXTENSIONS = Object.freeze(['.php', '.phar', '.phtml']);

function checked(field: string, pattern: RegExp, value: string): string {
  if (!pattern.test(value) || value.split('/').includes('..')) {
    throw new Error(`render(fpm_pool): ${field} '${value}' does not match ${pattern.source}. Nothing was rendered.`);
  }
  return value;
}

export function fpmPoolBody(layout: AgentLayout): string {
  const site = layout.site;
  if (site === null) throw new Error('render(fpm_pool): the declaration has no site. Nothing was rendered.');
  const pool = checked('the pool name', POOL_NAME_PATTERN, site.fpm.pool);
  const user = checked('v1.user', UNIX_NAME_PATTERN, layout.identity.v1User);
  const web = checked('site.fpm.webUser', UNIX_NAME_PATTERN, site.fpm.webUser);
  const listen = checked('site.fpm.listen', ABSOLUTE_PATH_PATTERN, site.fpm.listen);
  const v1Root = checked('the v1 root', ABSOLUTE_PATH_PATTERN, layout.state.apis.v1.root);
  const tmp = checked('the v1 tmp directory', ABSOLUTE_PATH_PATTERN, site.v1Var.tmp);
  const log = checked('the v1 log directory', ABSOLUTE_PATH_PATTERN, site.v1Var.log);
  return [
    '; GENERATED by publication/host_agent/src/provision/render/fpm_pool.ts — do NOT edit.',
    `; Derived from ${layout.declarationPath}. The v1 API of instance ${layout.instance}, never the site's pool.`,
    `[${pool}]`,
    `user = ${user}`,
    "; group: the user's primary group (FPM's default when unset).",
    `listen = ${listen}`,
    `listen.owner = ${web}`,
    `listen.group = ${web}`,
    'listen.mode = 0660',
    'pm = ondemand',
    'pm.max_children = 5',
    `chdir = ${v1Root}`,
    `security.limit_extensions = ${POOL_EXTENSIONS.join(' ')}`,
    `php_admin_value[open_basedir] = ${v1Root}/:${tmp}/`,
    `php_admin_value[upload_tmp_dir] = ${tmp}`,
    `php_admin_value[session.save_path] = ${tmp}`,
    `php_admin_value[sys_temp_dir] = ${tmp}`,
    'php_admin_flag[log_errors] = on',
    `php_admin_value[error_log] = ${log}/error.log`,
    '',
  ].join('\n');
}

export const fpmPoolRenderer: Renderer = {
  kind: 'fpm_pool',
  appliesTo: layout => layout.site !== null,
  render(layout: AgentLayout, _facts: RenderFacts): Artifact[] {
    const site = layout.site;
    if (site === null) throw new Error('render(fpm_pool): the declaration has no site. Nothing was rendered.');
    return [
      artifact(layout, {
        kind: 'fpm_pool',
        path: checked('site.fpm.poolFile', ABSOLUTE_PATH_PATTERN, site.fpm.poolFile),
        mode: 'fpmPool',
        body: fpmPoolBody(layout),
        commentPrefix: ';',
        effects: ['reload_fpm'],
        validate: 'fpm',
      }),
    ];
  },
};
