/**
 * THE SITE'S WEB LOG ROTATION (owner decision 1(c)) — `<logrotate_dir>/dedalo_<instance>_web`,
 * stamped. The site's vhost logs into its own directory under the distribution's log directory
 * (layout.ts webLogBase: `/var/log/apache2/<domain>`, `/var/log/httpd/<domain>`,
 * `/var/log/nginx/<domain>`), and the distribution's own rotation does NOT reach it: Debian's and
 * Ubuntu's /etc/logrotate.d/apache2 and nginx glob `/var/log/apache2/*.log` and
 * `/var/log/nginx/*.log`, EL's httpd and nginx `/var/log/httpd/*log` and `/var/log/nginx/*.log` —
 * one level, never a per-site subdirectory (measured: the drill images' own files, 2026-10-09).
 * Without this file the site's logs grow until the disk is full.
 *
 * The stanza is the distribution's own (daily, 14 kept, compressed one rotation late, `create 0640`
 * with the family's log group: `adm` on Debian/Ubuntu, `root` on EL), and after a rotation the
 * server reopens its logs the way its unit allows: Apache `systemctl reload` (graceful, both
 * families' own choice), nginx USR1 to the master (its documented reopen; Debian's `rotate` action
 * is the same signal). Only while the unit is active: a stopped server has nothing open.
 *
 * Applies in the home layout only — the layout whose site logs are placed here (compare's
 * `web.logs`; plan.ts creates the directory). No effect, no validator: logrotate reads it on its
 * next run, and every interpolated value is grammar-checked here.
 *
 * THE V1 POOL'S OWN LOG (`<logrotate_dir>/dedalo_<instance>_v1`, kind `logrotate_v1`, every site,
 * either layout): the pool's `php_admin_value[error_log] = <v1_var_base>/<instance>/v1/log/error.log`
 * (render/fpm_pool.ts) is written by the v1 workers in a directory the v1 USER owns (MODES
 * v1VarWork v1:root 0700). Nothing else rotates it. The stanza runs as that user (`su <v1> root`:
 * root never renames or creates inside a directory another account owns — the account could put a
 * link there), creates the new file as the pool's user 0600, and needs no reopen: PHP opens its
 * error_log anew for every message it writes.
 *
 * PURE, ZERO-DEPENDENCY.
 */
import type { AgentLayout } from '../layout';
import { ABSOLUTE_PATH_PATTERN, UNIX_NAME_PATTERN } from '../layout';
import { isHomeLayout } from '../selinux';
import type { Artifact, RenderFacts, Renderer } from './types';
import { artifact } from './types';

/** A systemd unit name as the declaration admits it (web.unit), with no `.service`. */
const UNIT_PATTERN = /^[a-z0-9][a-z0-9@._-]{0,63}$/;

function checked(field: string, pattern: RegExp, value: string): string {
  if (!pattern.test(value) || value.split('/').includes('..') || /\s/.test(value)) {
    throw new Error(`render(logrotate): ${field} '${value}' does not match ${pattern.source}. Nothing was rendered.`);
  }
  return value;
}

export function logrotateBody(layout: AgentLayout): string {
  const site = layout.site;
  if (site === null) throw new Error('render(logrotate): the declaration has no site. Nothing was rendered.');
  const dir = checked('site.webLogsDir', ABSOLUTE_PATH_PATTERN, site.webLogsDir);
  const unit = `${checked('web.unit', UNIT_PATTERN, layout.web.unit)}.service`;
  const group = site.fpm.flavor === 'debian' ? 'adm' : 'root';
  const reopen =
    layout.web.server === 'nginx'
      ? `systemctl --quiet is-active ${unit} && systemctl kill --kill-whom=main --signal=USR1 ${unit} || true`
      : `systemctl --quiet is-active ${unit} && systemctl reload ${unit} || true`;
  return [
    '# GENERATED by publication/host_agent/src/provision/render/logrotate.ts — do NOT edit.',
    `# Derived from ${layout.declarationPath}: the web server logs of ${site.domain}, which the`,
    "# distribution's own rotation (one level under its log directory) does not reach.",
    `${dir}/*.log {`,
    '\tdaily',
    '\tmissingok',
    '\trotate 14',
    '\tcompress',
    '\tdelaycompress',
    '\tnotifempty',
    `\tcreate 0640 root ${group}`,
    '\tsharedscripts',
    '\tpostrotate',
    `\t\t${reopen}`,
    '\tendscript',
    '}',
    '',
  ].join('\n');
}

/** The v1 pool's own error log (see the header). */
export function v1LogrotateBody(layout: AgentLayout): string {
  const site = layout.site;
  if (site === null) throw new Error('render(logrotate_v1): the declaration has no site. Nothing was rendered.');
  const dir = checked('site.v1Var.log', ABSOLUTE_PATH_PATTERN, site.v1Var.log);
  const user = checked('v1.user', UNIX_NAME_PATTERN, layout.identity.v1User);
  return [
    '# GENERATED by publication/host_agent/src/provision/render/logrotate.ts — do NOT edit.',
    `# Derived from ${layout.declarationPath}: the v1 API pool's own error log, which nothing else rotates.`,
    `${dir}/*.log {`,
    `\tsu ${user} root`,
    '\tdaily',
    '\tmissingok',
    '\trotate 14',
    '\tcompress',
    '\tdelaycompress',
    '\tnotifempty',
    `\tcreate 0600 ${user} root`,
    '}',
    '',
  ].join('\n');
}

export const v1LogrotateRenderer: Renderer = {
  kind: 'logrotate_v1',
  appliesTo: layout => layout.site !== null,
  render(layout: AgentLayout, _facts: RenderFacts): Artifact[] {
    return [
      artifact(layout, {
        kind: 'logrotate_v1',
        path: checked('the v1 logrotate file', ABSOLUTE_PATH_PATTERN, layout.v1LogrotatePath),
        mode: 'logrotate',
        body: v1LogrotateBody(layout),
      }),
    ];
  },
};

export const logrotateRenderer: Renderer = {
  kind: 'logrotate',
  appliesTo: layout => layout.site !== null && isHomeLayout(layout),
  render(layout: AgentLayout, _facts: RenderFacts): Artifact[] {
    return [
      artifact(layout, {
        kind: 'logrotate',
        path: checked('the logrotate file', ABSOLUTE_PATH_PATTERN, layout.logrotatePath),
        mode: 'logrotate',
        body: logrotateBody(layout),
      }),
    ];
  },
};
