/**
 * THE POLKIT GRANT (D4): the agent user may `reload` the observed web unit and `restart` the
 * v2 unit — those two (unit, verb) pairs, exact-matched, and nothing else. Every other
 * question returns NOT_HANDLED (falls through to the host's own policy), never NO, so this
 * file can neither widen nor narrow anything it does not name. Shape copied from
 * publication/site_builder/src/provision/render/agent_authorization.ts. Pure, zero-dep,
 * stamped with the `//` comment prefix (the file is JavaScript). polkitd reloads rules files
 * itself, so a rewrite has no effect for the plan to schedule.
 */

import { basename } from 'node:path';
import type { AgentLayout } from '../layout';
import type { Artifact, RenderFacts, Renderer } from './types';
import { artifact } from './types';

export const POLKIT_COMMENT_PREFIX = '//';

const RULES_FILE_NAME = /^[0-9]{2}-[a-z0-9_-]+\.rules$/;

export const polkitRenderer: Renderer = {
  kind: 'polkit',
  render(layout: AgentLayout, _facts: RenderFacts): Artifact[] {
    const user = layout.identity.agentUser;
    const web = `${layout.web.unit}.service`;
    const v2 = `${layout.v2.unit}.service`;
    if (!RULES_FILE_NAME.test(basename(layout.polkitPath))) {
      throw new Error(`render(polkit): '${layout.polkitPath}' is not an NN-<name>.rules file polkitd loads. Nothing was rendered.`);
    }
    // JSON.stringify on grammar-checked names (layout.ts): a quote cannot reach the rule.
    const q = (s: string) => JSON.stringify(s);
    const body = [
      `// GENERATED by publication/host_agent/src/provision/render/polkit.ts — do NOT edit.`,
      `// The publication host agent ${user} may: reload ${web}; restart ${v2}. Nothing else.`,
      `polkit.addRule(function (action, subject) {`,
      `  if (action.id !== "org.freedesktop.systemd1.manage-units") {`,
      `    return polkit.Result.NOT_HANDLED;`,
      `  }`,
      `  if (subject.user !== ${q(user)}) {`,
      `    return polkit.Result.NOT_HANDLED;`,
      `  }`,
      `  var unit = action.lookup("unit");`,
      `  var verb = action.lookup("verb");`,
      `  if (unit === ${q(web)} && verb === "reload") {`,
      `    return polkit.Result.YES;`,
      `  }`,
      `  if (unit === ${q(v2)} && verb === "restart") {`,
      `    return polkit.Result.YES;`,
      `  }`,
      `  return polkit.Result.NOT_HANDLED;`,
      `});`,
      ``,
    ].join('\n');
    return [
      artifact(layout, { kind: 'polkit', path: layout.polkitPath, mode: 'polkit', body, commentPrefix: POLKIT_COMMENT_PREFIX }),
    ];
  },
};
