/**
 * THE POLKIT GRANT (D4): the agent user may `reload` the observed web unit and `restart` the
 * v2 unit — those two (unit, verb) pairs, exact-matched — and `start`/`stop` an instance of the
 * v2 scratch template, `<v2.unit>-scratch@<port>.service` with port 1024-65535 written as 4-5
 * digits without a leading zero (render/unit_v2.ts: the scratch boot runs as v2, not the agent).
 * Nothing else. Every other
 * question returns NOT_HANDLED (falls through to the host's own policy), never NO, so this
 * file can neither widen nor narrow anything it does not name. Shape copied from
 * publication/site_builder/src/provision/render/agent_authorization.ts. Pure, zero-dep,
 * stamped with the `//` comment prefix (the file is JavaScript). polkitd reloads rules files
 * itself, so a rewrite has no effect for the plan to schedule.
 */

import { basename } from 'node:path';
import type { AgentLayout } from '../layout';
import { V2_SCRATCH_TEMPLATE_SUFFIX } from '../layout';
import type { Artifact, RenderFacts, Renderer } from './types';
import { artifact } from './types';

export const POLKIT_COMMENT_PREFIX = '//';

const RULES_FILE_NAME = /^[0-9]{2}-[a-z0-9_-]+\.rules$/;

export const polkitRenderer: Renderer = {
  kind: 'polkit',
  render(layout: AgentLayout, _facts: RenderFacts): Artifact[] {
    const user = layout.identity.agentUser;
    const web = `${layout.web.unit}.service`;
    const v2 = `${layout.v2.unit}.service`;
    if (!RULES_FILE_NAME.test(basename(layout.polkitPath))) {
      throw new Error(`render(polkit): '${layout.polkitPath}' is not an NN-<name>.rules file polkitd loads. Nothing was rendered.`);
    }
    // JSON.stringify on grammar-checked names (layout.ts): a quote cannot reach the rule.
    const q = (s: string) => JSON.stringify(s);
    // A RegExp SOURCE for the scratch instance; every metacharacter of the unit name escaped
    // (the grammar admits '.'), then embedded as a JSON string — no literal can be broken out of.
    const escaped = `${layout.v2.unit}${V2_SCRATCH_TEMPLATE_SUFFIX}`.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const scratch = `^${escaped}([1-9][0-9]{3,4})\\.service$`;
    const body = [
      `// GENERATED by publication/host_agent/src/provision/render/polkit.ts — do NOT edit.`,
      `// The publication host agent ${user} may: reload ${web}; restart ${v2};`,
      `// start/stop ${layout.v2.unit}${V2_SCRATCH_TEMPLATE_SUFFIX}<port>.service (port 1024-65535). Nothing else.`,
      `polkit.addRule(function (action, subject) {`,
      `  if (action.id !== "org.freedesktop.systemd1.manage-units") {`,
      `    return polkit.Result.NOT_HANDLED;`,
      `  }`,
      `  if (subject.user !== ${q(user)}) {`,
      `    return polkit.Result.NOT_HANDLED;`,
      `  }`,
      `  var unit = action.lookup("unit");`,
      `  var verb = action.lookup("verb");`,
      `  if (unit === ${q(web)} && verb === "reload") {`,
      `    return polkit.Result.YES;`,
      `  }`,
      `  if (unit === ${q(v2)} && verb === "restart") {`,
      `    return polkit.Result.YES;`,
      `  }`,
      `  var scratch = new RegExp(${q(scratch)}).exec(unit);`,
      `  if (scratch !== null && (verb === "start" || verb === "stop")) {`,
      `    var port = parseInt(scratch[1], 10);`,
      `    if (port >= 1024 && port <= 65535) {`,
      `      return polkit.Result.YES;`,
      `    }`,
      `  }`,
      `  return polkit.Result.NOT_HANDLED;`,
      `});`,
      ``,
    ].join('\n');
    return [
      artifact(layout, { kind: 'polkit', path: layout.polkitPath, mode: 'polkit', body, commentPrefix: POLKIT_COMMENT_PREFIX }),
    ];
  },
};
