/**
 * THE ONE SUDO GRANT (D4): the agent user may run EXACTLY `<configtest bin> -t` as root — no
 * other argument, no shell, no password prompt. In sudoers a command WITH arguments matches
 * only those arguments, so `nginx -t` does not admit `nginx -s stop` or `nginx -c x -t`.
 * Pure, zero-dep, stamped.
 *
 * src/exec.ts runs `sudo -n <WEB_CONFIGTEST_BIN> -t`; this rule must name that path (held by
 * tests/provision_render_grants.test.ts). layout.ts DERIVES the binary — the host's pick from the
 * closed WEB_CONFIGTEST_CANDIDATES (never declared) — and renders the same value into the agent
 * env; the check below is the renderer's own.
 *
 * The file name has no '.' and no trailing '~': sudo's #includedir silently skips such names,
 * and the grant would vanish while the file looks installed. apply.ts installs it with
 * `visudo -cf` on the temp file, a rename, then `visudo -c` on the whole policy, restoring the
 * previous file by rename when the policy refuses it (validate: 'sudoers').
 */

import { basename } from 'node:path';
import type { AgentLayout } from '../layout';
import { WEB_CONFIGTEST_CANDIDATES, isConfigtestBinary } from '../layout';
import type { Artifact, RenderFacts, Renderer } from './types';
import { artifact } from './types';

export function sudoersAlias(instance: string): string {
  return `DEDALO_PUBHOST_${instance.toUpperCase()}_CONFIGTEST`;
}

export const sudoersRenderer: Renderer = {
  kind: 'sudoers',
  render(layout: AgentLayout, _facts: RenderFacts): Artifact[] {
    const bin = layout.web.configtestBin;
    // The EXACT path: a root NOPASSWD grant must name what src/exec.ts runs, never a look-alike
    // elsewhere (a scratch-root gate substitutes this renderer, it does not loosen it).
    if (!isConfigtestBinary(layout.web.server, bin) || layout.envVars.WEB_CONFIGTEST_BIN !== bin) {
      throw new Error(
        `render(sudoers): web.configtestBin '${bin}' is not one of ` +
          `${WEB_CONFIGTEST_CANDIDATES[layout.web.server].join(', ')} for web.server '${layout.web.server}', ` +
          `or not the binary the agent env names. Nothing was rendered.`,
      );
    }
    const name = basename(layout.sudoersPath);
    if (name.includes('.') || name.endsWith('~')) {
      throw new Error(
        `render(sudoers): '${layout.sudoersPath}' has a '.' or a trailing '~' in its name — #includedir skips ` +
          `those names and the grant would silently not exist. Nothing was rendered.`,
      );
    }
    const alias = sudoersAlias(layout.instance);
    const user = layout.identity.agentUser;
    const body = [
      `# GENERATED by publication/host_agent/src/provision/render/sudoers.ts — do NOT edit.`,
      `# The publication host agent '${user}' may run ONE argv as root: the web server's`,
      `# configtest (it must read root-only TLS keys). Nothing else: no reload (polkit does`,
      `# that), no shell, no other argument.`,
      `Cmnd_Alias ${alias} = ${bin} -t`,
      `${user} ALL=(root) NOPASSWD: ${alias}`,
      ``,
    ].join('\n');
    return [artifact(layout, { kind: 'sudoers', path: layout.sudoersPath, mode: 'sudoers', body, validate: 'sudoers' })];
  },
};
