/**
 * THE ONE SUDO GRANT (D4): the agent user may run EXACTLY `<configtest bin> -t` as root — no
 * other argument, no shell, no password prompt. In sudoers a command WITH arguments matches
 * only those arguments, so `nginx -t` does not admit `nginx -s stop` or `nginx -c x -t`.
 * Pure, zero-dep, stamped.
 *
 * src/exec.ts runs `sudo -n <WEB_CONFIGTEST_BINARY[server]> -t`; this rule must name that
 * path (held by tests/provision_render_grants.test.ts). layout.ts DERIVES the binary from
 * WEB_CONFIGTEST_BINARY (never declared); the check below is the renderer's own.
 *
 * The file name has no '.' and no trailing '~': sudo's #includedir silently skips such names,
 * and the grant would vanish while the file looks installed. apply.ts installs it with
 * `visudo -cf` on the temp file, a rename, then `visudo -c` on the whole policy, restoring the
 * previous file by rename when the policy refuses it (validate: 'sudoers').
 */

import { basename } from 'node:path';
import type { AgentLayout } from '../layout';
import { WEB_CONFIGTEST_BINARY } from '../layout';
import type { Artifact, RenderFacts, Renderer } from './types';
import { artifact } from './types';

export function sudoersAlias(instance: string): string {
  return `DEDALO_PUBHOST_${instance.toUpperCase()}_CONFIGTEST`;
}

export const sudoersRenderer: Renderer = {
  kind: 'sudoers',
  render(layout: AgentLayout, _facts: RenderFacts): Artifact[] {
    const bin = layout.web.configtestBin;
    // By basename: derive() pins the full path; a scratch-root gate repoints only the directory.
    const expected = basename(WEB_CONFIGTEST_BINARY[layout.web.server]);
    if (basename(bin) !== expected) {
      throw new Error(
        `render(sudoers): web.configtestBin '${bin}' is not a '${expected}' binary, which is what the agent ` +
          `runs for web.server '${layout.web.server}'. Nothing was rendered.`,
      );
    }
    const name = basename(layout.sudoersPath);
    if (name.includes('.') || name.endsWith('~')) {
      throw new Error(
        `render(sudoers): '${layout.sudoersPath}' has a '.' or a trailing '~' in its name — #includedir skips ` +
          `those names and the grant would silently not exist. Nothing was rendered.`,
      );
    }
    const alias = sudoersAlias(layout.instance);
    const user = layout.identity.agentUser;
    const body = [
      `# GENERATED by publication/host_agent/src/provision/render/sudoers.ts — do NOT edit.`,
      `# The publication host agent '${user}' may run ONE argv as root: the web server's`,
      `# configtest (it must read root-only TLS keys). Nothing else: no reload (polkit does`,
      `# that), no shell, no other argument.`,
      `Cmnd_Alias ${alias} = ${bin} -t`,
      `${user} ALL=(root) NOPASSWD: ${alias}`,
      ``,
    ].join('\n');
    return [artifact(layout, { kind: 'sudoers', path: layout.sudoersPath, mode: 'sudoers', body, validate: 'sudoers' })];
  },
};
