<?php

	# VISUALIZADOR HTML	

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in', $modo, $lang);
	
	# wrapper
	print "\n<div class=\"wrap_component css_wrap_text_area wrap_component_{$tipo}\" id=\"{$id_wrapper}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-modo=\"{$modo}\" ";
	#print "data-dato=\"{$dato_raw}\" ";
	print "data-context_name=\"{$context->context_name}\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-component_info='{$component_info}' ";
	print "data-related_tipo='{$ar_related_component_tipo_json}' ";
	print "role=\"wrap_component_text_area\" ";
	print ">";

	# ETIQUETA (LABEL)
	#$html_label = component_common_draw::draw_label($this);

	# LANG FAST SWITCHER	
	if ($this->traducible==='si') {
		print component_common_draw::draw_select_fast_lang_switch($id_wrapper, $lang, 'select_fast_lang_switch fast_switch_lang_note');
	}

	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch($permissions) {

		case 0 :
				$html_content .= "";
				break;

		case 1 :
				$html_content .= "<span class=\"css_span_dato text_area_read_only\">$dato</span>";
				break;

		case 2 :
		case 3 :
				#
				# TEXTAREA								
				$html_content .= "<div id=\"{$identificador_unico}\" ";
				$html_content .= "class=\"text_area_div_editable\" ";	 // text_area_tool_structuration			
				$html_content .= "name=\"{$input_name}\" ";
				$html_content .= "data-parent=\"{$parent}\" ";
				$html_content .= "data-tipo=\"{$tipo}\" ";
				$html_content .= "data-lang=\"{$lang}\" ";
				$html_content .= "data-modo=\"{$modo}\" ";
				$html_content .= "data-section_tipo=\"{$section_tipo}\" ";
				$html_content .= "title=\"$html_title\" ";
				$html_content .= "tabindex=\"1\" ";
				$html_content .= ">";
				$html_content .= $dato;
				$html_content .= "</div>";
				
				/*
				$html_content .= "<textarea class=\"css_text_area\" id=\"{$identificador_unico}\" style=\"visibility:hidden\" ";
				$html_content .= "name=\"{$input_name}\" ";
				$html_content .= "data-parent=\"{$parent}\" ";
				$html_content .= "data-tipo=\"{$tipo}\" ";
				$html_content .= "data-lang=\"{$lang}\" ";
				$html_content .= "data-modo=\"{$modo}\" ";
				$html_content .= "data-section_tipo=\"{$section_tipo}\" ";				
				$html_content .= "title=\"$html_title\" ";
				$html_content .= "tabindex=\"1\" ";
				$html_content .= ">";
				$html_content .= $dato;
				$html_content .= "</textarea>";*/
				

				# INIT : Init text editor	
				$html_content .= "<script>";
				$html_content .= "setTimeout(function(){
					component_text_area.init({uid:'$identificador_unico',modo:'$modo',propiedades:'$propiedades_json'});
				},10)";
				$html_content .= "</script>";
				break;

	}//end switch($permissions) {	
	

	# Prepare content to show in page
	tools::prepare_content($html_content);
	

	# PRINT HTML
	#print $html_label;
	print $html_content;



	print "</div>"; //wrap

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out', $modo, $lang);

?>