<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	
	
	#echo "\n<!-- TEXT AREA [tipo:$tipo id_matrix:$id] -->";
	#echo "<div class=\"css_text_area_wrap\" >";
	
		# ETIQUETA (LABEL)
		#$html_label = component_common_draw::draw_label($this);
		
		# CONTENIDO (INPUT)
		$html_contenido = (string)'';
		switch($permissions) {
				
			case 0:		$html_contenido .= '';	
						break;
							
			case ($permissions>=1):
			
						$html_contenido .= "<span class=\"css_span_dato\">$fragmento_text</span>";
				
				
						#if($permissions==3) {
						#	$html_contenido .= "<span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
						#}
		}
		
		
		# PRINT HTML
		print $html_contenido;
	
	
	#echo "</div>"; //wrap
?>