<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 		$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_text_area'])) 		$ar_css['css_text_area']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 	$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))	$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_text_area']))	$ar_css['css_wrap_text_area']='';
	
	if(!isset ($html_tools))					$html_tools='';
	
	
	print "\n<!-- TEXT AREA [tipo:$tipo parent:$parent] $label -->";
	print "\n<div class=\"css_wrap_text_area wrap_component text_area_tool_lang {$ar_css['css_wrap_text_area']}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-lang=\"{$lang}\"
	data-modo=\"{$modo}\"
	data-dato=\"{$dato_raw}\"
	data-component_name=\"{$component_name}\"
	>";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);#."<span class=\"debug_info\"> $identificador_unico</span>";
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	

			$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> No access here (text_area)! </span>";	
			break;
						
		case 1	: 	

			$html_contenido .= "\n<div class=\"text_area_content text_area_content_shadow\" >";
			$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\">$dato</span>";
			$html_contenido .= "\n</div>"; #end text_area_content			
			break;						
		
		case ($permissions>=2)	:

			#
			# TEXT AREA
			#
			$html_contenido .= "\n <textarea class=\"css_text_area \"
			id=\"{$identificador_unico}\"
			name=\"{$input_name}\"
			data-tipo=\"{$tipo}\"
			data-lang=\"{$lang}\"
			data-section_tipo=\"{$section_tipo}\"
			data-parent=\"{$parent}\"
			data-last_tag_index_id=\"{$last_tag_index_id}\"
			title=\"$html_title\">$dato</textarea>";

			# Init text editor
			#$html_contenido .= '<script>text_editor.init("'.$identificador_unico.'");</script>';	


			if (SHOW_DEBUG) {
			#$html_contenido .= "<span class=\"debug_info\"> $identificador_unico</span>";
			}		
			

			#
			# WRAP CURRENT SELECTED FRAGMENT (ONLY FRAGMENT INFO) 
			#			
			$html_contenido .= "\n <div id=\"fragment_info_div_{$tipo}_{$lang}\" class=\"wrap_fragment\" 
			data-tipo=\"{$tipo}\" data-section_tipo=\"{$section_tipo}\" data-parent=\"{$parent}\" data-lang=\"{$lang}\" data-modo=\"fragment_info\" data-caller_id=\"$caller_id\" data-component_name=\"$component_name\"
			><div class=\"content_data\"><!-- AJAX CONTENT HERE --></div></div>";
			

			#if($permissions==3)						
			#$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$tipo}\" >{$debugger}</span>";
			
			break;							
	}

	# INIT : Init text editor 
	#$html_contenido .= "\n<script>$(function(){text_editor.init('$identificador_unico','$modo','$propiedades_json');})</script>";
	$html_contenido .= "\n<script>text_editor.init('$identificador_unico','$modo','$propiedades_json');</script>";
	
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);

	
	# PRINT HTML
	print $html_label;
	print $html_contenido;

	
	
	print "\n</div><!-- /css_wrap_text_area  $label -->\n\n"; //wrap
?>
