<?php
	/*
	# Persons html
	# This template is loaded by ajax from text area button 'Persons' only when in tool_transcription mode
	
	
	print "\n <div class=\"persons_container persons_container_{$tipo}\" role=\"text_area_persons_container\">";

	
	# CONTENIDO (INPUT)
	$html_content = '';
	
	$html_content .= "<ul>";
	foreach ($ar_tags_person as $key => $tag_obj) {
		$html_content .= "<li>";

		$html_content .= "<div>";
		$html_content .= " <label>Rol</label>";
		$html_content .= " <span>";
		$html_content .=   $tag_obj->rol;
		$html_content .= " </span>";
		$html_content .= " <label>Name</label>";
		$html_content .= " <span>";
		$html_content .=   $tag_obj->full_name;
		$html_content .= " </span>";
		$html_content .=  TR::addTagImgOnTheFly($tag_obj->tag);
		$html_content .= "</div>";

		$html_content .= "</li>";
	}
	$html_content .= "</ul>";


	# PRINT HTML
	print $html_content;


	print "</div><!-- /persons_container -->"; //persons_container
	*/

?>
