<?php

	# VISUALIZADOR HTML	
	
	
	#print "\n<div class=\"\" >";
	
		
		# CONTENIDO (INPUT)
		$html_contenido  = '';
		$html_contenido .= "<div class=\"list_thesaurus_element text_area_list_thesaurus\" onclick=\"component_text_area.show_component_in_row_thesaurus(this)\"
		data-section_tipo=\"$section_tipo\"
		data-parent=\"$parent\"
		data-tipo=\"$tipo\"
		data-lang=\"$lang\"
		data-modo=\"edit\"
		>$icon_label</div>";
		
		
		# PRINT HTML
		print $html_contenido;
	
	
	#print "\n</div>\n\n"; //wrap
?>