<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 		$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_text_area'])) 		$ar_css['css_text_area']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 	$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))	$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_text_area']))	$ar_css['css_wrap_text_area']='';
	
	if(!isset ($html_tools))					$html_tools='';
	
	
	print "\n<!-- TEXT AREA [tipo:$tipo id_matrix:$id] $label -->";
	print "\n<div class=\"css_wrap_text_area wrap_component {$ar_css['css_wrap_text_area']} text_area_tool_indexation\" id=\"{$id_wrapper}\"
	data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-parent=\"{$parent}\" data-lang=\"{$lang}\" data-modo=\"{$modo}\" data-dato=\"{$dato_raw}\" data-component_name=\"{$component_name}\" >";
	
	
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> No access here (text_area)! </span>";	
					break;
						
		case 1	: 	$html_contenido .= "\n<div class=\"text_area_content text_area_content_shadow\" >";
					$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\">$dato</span>";
					$html_contenido .= "\n</div>"; #end text_area_content

					/**
					* WRAP CURRENT SELECTED FRAGMENT (INDEXATION AND RELATIONS LIST TABS) 
					*/
					$html_contenido .= "\n <div id=\"relations_ajax_div_{$tipo}\" class=\"wrap_fragment\" 
					data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-parent=\"{$parent}\" data-modo=\"selected_fragment\" data-caller_id=\"$caller_id\"
					> <!-- AJAX CONTENT HERE --> </div>";

						
					break;	
						
		
		case ($permissions>=2)	:

					# ETIQUETA (LABEL)
					$html_contenido = component_common_draw::draw_label($this);

					/**
					* Text area
					*/
					$html_contenido .= "\n <textarea class=\"css_text_area $text_area_tm {$ar_css['css_text_area']} text_area_tool_indexation\" 
					id=\"{$identificador_unico}\" 
					name=\"{$input_name}\" 
					data-tipo=\"{$tipo}\" data-id_matrix=\"{$id}\" data-lang=\"{$lang}\" data-parent=\"{$parent}\" data-last_tag_index_id=\"{$last_tag_index_id}\"
					title=\"$html_title\">$dato</textarea>";

					
					if (SHOW_DEBUG) {
					$html_contenido .= "<span class=\"debug_info\"> $identificador_unico</span>";
					}
					
					
					/**
					* BTN CREATE FRAGMENT  
					*/
					#if($caller_id>0)
					$html_contenido .= "\n <div class=\"css_button_generic btn_create_fragment\" style=\"display:none\"
					data-identificador_unico=\"$identificador_unico\" data-id_matrix=\"$id\"
					onclick=\"tool_indexation.create_fragment(this);\"
					>";				
					$html_contenido .= label::get_label('crear_nuevo_fragmento');
					if(SHOW_DEBUG===true) {
					$html_contenido .= " <span class=\"debug_info\">[last_tag_index_id:$last_tag_index_id - caller_id:$caller_id]</span>";
					}
					$html_contenido .= "</div>";


		
			if($permissions==3)	
					
					$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$debugger}</span>";
					break;
							
	}

	# INIT : Init text editor 
	$html_contenido .= "\n<script>text_editor.init('$identificador_unico','$modo','$propiedades_json');</script>";
	
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);

	
	# PRINT HTML	
	print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_text_area  $label -->\n\n"; //wrap
?>

