<?php

	# VISUALIZADOR HTML
	
	
	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in', $modo, $lang);

	print "<div class=\"css_wrap_text_area wrap_component text_area_tool_lang\" id=\"{$id_wrapper}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-modo=\"{$modo}\" ";	
	print "data-role=\"{$role}\" ";	
	#print "data-dato=\"{$dato_raw}\" ";
	print "data-component_name=\"{$component_name}\" ";
	print ">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);#."<span class=\"debug_info\"> $identificador_unico</span>";
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch($permissions) {
			
		case 0	:
			break;
						
		case 1	:
			$html_content .= "<div class=\"text_area_content text_area_content_shadow\" >";
			$html_content .= " <span class=\"css_span_dato\">$dato</span>";
			$html_content .= "</div>"; #end text_area_content			
			break;
		
		case 2	:
		case 3	:

			$html_content .= "<span class=\"lang_info_debug\">";
			$html_content .= $lang;
			if(SHOW_DEBUG===true) {
				$html_content .= " <span>[$modo]</span>";
			}
			$html_content .= "</span>";
			

			#
			# TEXT AREA
			#
			$html_content .= "<textarea class=\"css_text_area\" style=\"visibility:hidden\" ";
			$html_content .= "id=\"{$identificador_unico}\" ";
			$html_content .= "name=\"{$input_name}\" ";
			$html_content .= "data-tipo=\"{$tipo}\" ";
			$html_content .= "data-lang=\"{$lang}\" ";
			$html_content .= "data-modo=\"{$modo}\" ";
			$html_content .= "data-section_tipo=\"{$section_tipo}\" ";
			$html_content .= "data-parent=\"{$parent}\" ";
			$html_content .= "title=\"$html_title\">";
			$html_content .= $dato;
			$html_content .= "</textarea>";

			# Init text editor
			#$html_content .= '<script>component_text_area.init("'.$identificador_unico.'");</script>';	


			if (SHOW_DEBUG===true) {
			#$html_content .= "<span class=\"debug_info\"> $identificador_unico</span>";
			}		
			

			#
			# WRAP CURRENT SELECTED FRAGMENT (ONLY FRAGMENT INFO) 
			#
			/*			
			$html_content .= "<div id=\"fragment_info_div_{$tipo}_{$lang}\" class=\"wrap_fragment\" ";
			$html_content .= "data-tipo=\"{$tipo}\" ";
			$html_content .= "data-section_tipo=\"{$section_tipo}\" ";
			$html_content .= "data-parent=\"{$parent}\" ";
			$html_content .= "data-lang=\"{$lang}\" ";
			$html_content .= "data-modo=\"fragment_info\" ";
			$html_content .= "data-caller_id=\"$caller_id\" ";
			$html_content .= "data-component_name=\"$component_name\" ";
			$html_content .= ">";
			$html_content .= "<div class=\"content_data\"><!-- AJAX CONTENT HERE --></div></div>";*/
			

			if (SHOW_DEBUG===true) {
				#$html_content .= " <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";
			}			
			break;
	}

	# INIT : Init text editor 
	$html_content .= "<script>";
	$html_content .= "component_text_area.init({uid:'$identificador_unico',modo:'$modo',propiedades:'$propiedades_json',id_wrapper:'$id_wrapper'});";
	$html_content .= "</script>";
	
	
	# Prepare content to show in page
	tools::prepare_content($html_content);

	
	# PRINT HTML
	print $html_label;
	print $html_content;

	
	
	print "</div>"; //wrap

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out', $modo, $lang);
?>