<?php

	# VISUALIZADOR HTML	

	
	if(isset($_REQUEST[$tipo]))					$dato = $_REQUEST[$tipo];		#var_dump($_REQUEST[$tipo]);
	
	#print "\n<!-- TEXT AREA [tipo:$tipo id_matrix:$id] -->";
	print "\n<div class=\"css_wrap_text_area\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato\"> No access here (text_area)! </span>";	
					break;						
		
		case ($permissions>=1)	:
					/*
					$html_contenido .= "\n <textarea class=\"css_text_area {$ar_css['css_text_area']}\" 
					id=\"{$identificador_unico}\" name=\"{$tipo}\" 
					data-tipo=\"{$tipo}\" 
					title=\"$html_title\">$dato</textarea>";
					*/
					$html_contenido .= "\n <input class=\"css_input_text text_area_search\" type=\"text\" 
					name=\"{$tipo}\" 
					data-tipo=\"{$tipo}\"
					value=\"{$dato}\" title=\"$html_title\" />";
				
	}

	# Prepare content to show in page
	tools::prepare_content($html_contenido);
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div>\n\n"; //wrap
?>