<?php

	# VIEW HTML	

	# html_delimiter
	#print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in', $modo);

	print "<div class=\"wrap_component css_wrap_text_area\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch(true) {
			
		case ($permissions==0)	:
				$html_content .= "";	
				break;						
		
		case ($permissions>=1)	:

				# COMPARISON OPERATORS
				$html_content .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);

				# INPUT
				$html_content .= "<span id=\"search_component_$tipo\">";	
				$html_content .= "<input class=\"css_input_text text_area_search\" type=\"text\" name=\"{$search_input_name}\" ";
				$html_content .= "data-tipo=\"{$tipo}\" ";
				$html_content .= "data-modo=\"{$modo}\" ";
				$html_content .= "value=\"{$valor}\" ";
				$html_content .= "title=\"$html_title\" ";
				$html_content .= "/>";
				$html_content .= "</span>";

				# LOGICAL OPERATORS
				$html_content .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);								
	}

	# Prepare content to show in page
	tools::prepare_content($html_content);
	
	
	# PRINT HTML
	print $html_label;
	print $html_content;
	
	
	print "</div>"; //wrap

	# html_delimiter
	#print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out', $modo);

?>