<?php

	# VISUALIZADOR HTML
	

	print "\n<!-- TEXT AREA [tipo:$tipo section_id:$parent modo:$modo] $label $identificador_unico -->";
	
	print "\n<div class=\"wrap_component css_wrap_text_area wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-lang=\"{$lang}\"
	data-modo=\"{$modo}\"
	data-dato=\"{$dato_raw}\"
	data-context_name=\"{$context_name}\"
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	role=\"wrap_component_text_area\"
	>";

	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {

		case 0	:	$html_contenido .= "";
					break;

		case 1	: 	#$html_contenido .= "\n<div class=\"text_area_content text_area_content_shadow\" >";
					$html_contenido .= "\n <span class=\"css_span_dato\">$dato</span>";
					#$html_contenido .= "\n</div>"; #end text_area_content

					##
					# WRAP CURRENT SELECTED FRAGMENT (RELATION / ADD PORTAL BUTTON)
					#
					$html_contenido .= "\n <div id=\"relations_ajax_div_{$tipo}\" class=\"wrap_fragment\"
					data-tipo=\"{$tipo}\"
					data-section_tipo=\"{$section_tipo}\"
					data-parent=\"{$parent}\"
					data-modo=\"selected_fragment\"
					data-lang=\"{$lang}\"
					data-context_name=\"$context_name\"
					data-caller_id=\"$caller_id\"
					data-component_name=\"$component_name\"
					>
					<div class=\"content_data\"><!-- AJAX CONTENT HERE --></div>
					</div>";


					break;


		case ($permissions>=2)	:

					#
					# COMPONENT STATE
					if (isset($component_state_html)) {
						$html_contenido .= $component_state_html;
					}

					#
					# DATO REFERENCE DEFAULT LANG
					/* DESACTIVO DE MOMENTO. VOLVER A ACTIVAR CUANDO LA B4 ESTÉ ESTABLE
					#if ($modo!='tool_lang' && !empty($default_component)) {
					if ($modo=='edit' && !empty($default_component->dato)) {

						#$html_contenido .= "\n <div class=\"dato_refecence_default_lang\">$dato_reference_lang</div>";
						# Fijamos el lenguaje actual como el de destino para el tool_lang
						$html_contenido .= "<script>set_localStorage('last_target_lang','$lang')</script>";
						$tool_lang = new tool_lang($default_component,'button');
							#dump($tool_lang,'$tool_lang');
						$html_contenido .= $tool_lang->get_html();
					}
					*/

					#
					# BROKEN INDEX TAGS WARNING
					if (isset($component_warning)) {
						$html_contenido .= "<div class=\"text_area_warning\"><span class=\"warning\">".$component_warning."</span></div>";
					}


					#
					# TEXTAREA  contenteditable=\"true\"
					#
					$html_contenido .= "\n <textarea class=\"css_text_area $text_area_tm\"
					id=\"{$identificador_unico}\"
					name=\"{$input_name}\"
					title=\"$html_title\"
					data-tipo=\"{$tipo}\"
					data-lang=\"{$lang}\"
					data-section_tipo=\"{$section_tipo}\"
					data-parent=\"{$parent}\"
					data-last_tag_index_id=\"{$last_tag_index_id}\"
					data-canvas_id=\"$canvas_id\"
					data-context_name=\"$context_name\"
					data-id_wrapper=\"$id_wrapper\"
					tabindex=\"1\"
					>$dato</textarea>";




					/*
					##
					# DIV
					#
					$html_contenido .= "\n <div class=\"css_text_area $text_area_tm\"
					id=\"{$identificador_unico}\"
					name=\"{$input_name}\"
					title=\"$html_title\"
					data-tipo=\"{$tipo}\"
					data-lang=\"{$lang}\"
					data-section_tipo=\"{$section_tipo}\"
					data-parent=\"{$parent}\"
					data-last_tag_index_id=\"{$last_tag_index_id}\"
					data-canvas_id=\"$canvas_id\"
					data-context_name=\"$context_name\"
					>$dato</div>";
					*/


					if (SHOW_DEBUG) {
					#$html_contenido .= "<span class=\"debug_info\"> $identificador_unico</span>";
					}


					##
					# BTN CREATE FRAGMENT
					#
					/*
					#if($caller_id>0)
					$html_contenido .= "\n <div class=\"css_button_generic btn_create_fragment\" onclick=\"tool_indexation.create_fragment('$identificador_unico');\">";
					$html_contenido .= "Create new fragment with selection";
					if(SHOW_DEBUG===true) {
					$html_contenido .= " <span class=\"debug_info\">[last_tag_index_id:$last_tag_index_id - caller_id:$caller_id]</span>";
					}
					$html_contenido .= "</div>";
					*/




					#
					# RELATE BUTTON . Relate current selected text with caller_id section
					# des: data-tipo=\"$caller_tipo\" data-caller_tipo=\"$caller_tipo\"	 data-caller_id=\"$caller_id\"
					/*
					$html_contenido .= "<div class=\"css_button_generic btn_relate_fragment\"
					data-id_matrix=\"$parent\"
					data-tagName=\"\"
					onclick=\"component_text_area.relate_fragment(this);\">
					";
						$html_contenido .= "Relate selected fragment";
						if(SHOW_DEBUG===true) {
							$html_contenido .= " <span class=\"debug_info\">[parent:$parent - section_tipo:$section_tipo]</span>";	# caller_id:$caller_id -
						}
					$html_contenido .= "</div>";
					*/


					#
					# BTN CREATE FRAGMENT
					#
					$html_contenido .= "\n <div class=\"css_button_generic btn_create_fragment\" style=\"display:none\"
					data-identificador_unico=\"$identificador_unico\"
					data-parent=\"{$parent}\"
					data-section_tipo=\"{$section_tipo}\"
					onclick=\"tool_indexation.create_fragment(this);\"
					>";
					$html_contenido .= label::get_label('crear_nuevo_fragmento');
					if(SHOW_DEBUG) {
						#$html_contenido .= " <span class=\"debug_info\">[last_tag_index_id:$last_tag_index_id - caller_id:$caller_id]</span>";
					}
					$html_contenido .= "</div>";



					##
					# WRAP CURRENT SELECTED FRAGMENT (RELATION / ADD PORTAL BUTTON)
					#
					$html_contenido .= "\n <div id=\"relations_ajax_div_{$tipo}\" class=\"wrap_fragment\"
					data-tipo=\"{$tipo}\"
					data-section_tipo=\"{$section_tipo}\"
					data-parent=\"{$parent}\"
					data-modo=\"selected_fragment\"
					data-lang=\"{$lang}\"
					data-context_name=\"$context_name\"
					data-caller_id=\"$caller_id\"
					data-component_name=\"$component_name\"
					>
					<div class=\"content_data\"><!-- AJAX CONTENT HERE (selected_fragment) --></div>
					</div>";




					if($permissions==3)	{
						#$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";
					}

					break;
	}

	# INIT : Init text editor
	$html_contenido .= "\n<script>text_editor.init('$identificador_unico','$modo','$propiedades_json');</script>";
	#$html_contenido .= "\n<script>tinymce.init({ selector:'textarea' });</script>";

	# Prepare content to show in page
	tools::prepare_content($html_contenido);


	# PRINT HTML
	print $html_label;
	print $html_contenido;


	print "\n</div><!-- /css_wrap_text_area  $label -->\n\n"; //wrap


?>
