<?php

	# VISUALIZADOR HTML	

	print "\n<div class=\"wrap_btn_relate_fragment\">";


	# CONTENIDO (INPUT)
	$html_contenido = '';

	
	switch($permissions) {
			
		case 0	:	
			$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> No access here (text_area)! </span>";	
			break;
						
		
		case ($permissions>=1)	:

			/**
			* CURRENT SELECTED RELATION (FRAGMENT AND RELATIOS LIST)
			*/


			switch ($context) {

				case 'list_into_tool_relation':
					$button_action 	= "parent.tool_relation.add_relation(this)";
					$button_label 	= label::get_label('relacionar_fragmento_seleccionado') . " (".label::get_label('etiqueta')." $tag_value)";
					break;

				case 'list_into_tool_portal':
					$button_action 	= 'tool_portal.add_resource(this)';#"tool_portal.add_fragment_resource(this)";
					$button_label 	= label::get_label('relacionar_fragmento_seleccionado') . " (".label::get_label('etiqueta')." $tag_value)";
					break;				
				
				default:
					$button_label 	= '';
					$button_action 	= "alert('Please define context to activate this button')";
					break;
			}
			
			# RELATE BUTTON . 
			# Relate current selected text with caller_id section
			# des: data-tipo=\"$caller_tipo\" data-caller_tipo=\"$caller_tipo\"	 data-caller_id=\"$caller_id\"			
			$html_contenido .= "<div class=\"css_button_generic btn_relate_fragment\"  
			 data-rel_locator=\"$rel_locator\" data-tipo=\"$tipo\"
			 onclick=\"{$button_action}\"
			 >";
			$html_contenido .= $button_label;
			$html_contenido .= " context:$context";
			if(SHOW_DEBUG===true) {
				$html_contenido .= " <span class=\"debug_info\">[id_matrix:$parent - rel_locator:$rel_locator]</span>";	# caller_id:$caller_id -
			}	 
			$html_contenido .= "</div>";
			
	}
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);	


	# PRINT HTML
	print $html_contenido;

	
	print "\n</div><!-- /wrap_btn_relate_fragment -->\n\n"; //wrap	
	
?>