<?php

	# VISUALIZADOR HTML	
	
	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in', $modo, $lang);

	print "<div class=\"css_wrap_text_area wrap_component text_area_tool_indexation\" id=\"{$id_wrapper}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-role=\"{$role}\" ";	
	print "data-component_info='{$component_info}' ";
	print "data-component_name=\"{$component_name}\" ";
	print ">";


	# LANG FAST SWITCHER
	print component_common_draw::draw_select_fast_lang_switch($id_wrapper, $lang, 'select_fast_lang_switch tool_indexation_fast_lang_switch', 'tool_indexation.fast_switch_lang');
	
	
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch($permissions) {
			
		case 0	:
			$html_content .= "";
			break;
						
		case 1	: 
			$html_content .= "<div class=\"text_area_content text_area_content_shadow\" >";
			$html_content .= "<span class=\"css_span_dato\">$dato</span>";
			$html_content .= "</div>"; #end text_area_content

			/**
			* WRAP CURRENT SELECTED FRAGMENT (INDEXATION AND RELATIONS LIST TABS) 
			*/
			$html_content .= "<div id=\"relations_ajax_div_{$tipo}\" class=\"wrap_fragment\" ";
			$html_content .= "data-tipo=\"{$tipo}\" ";
			$html_content .= "data-section_tipo=\"{$section_tipo}\" ";
			$html_content .= "data-parent=\"{$parent}\" ";
			$html_content .= "data-modo=\"selected_fragment\" ";
			$html_content .= "data-lang=\"{$lang}\" ";
			$html_content .= "data-caller_id=\"$caller_id\" ";
			$html_content .= "> <!-- AJAX CONTENT HERE --> </div>";
			break;					
		
		case 2	:
		case 3	:
			# ETIQUETA (LABEL)
			$html_content = component_common_draw::draw_label($this);

			#
			# BROKEN INDEX TAGS WARNING
			if (!empty($component_warning)) {
				$html_content .= "<div class=\"text_area_warning\"><span class=\"warning\">".$component_warning."</span></div>";
			}

			if(SHOW_DEBUG===true) {
				$html_content .= "<br><span class=\"lang_info_debug\">$lang</span>" ;
			}

			#
			# TEXT AREA
			#
			$html_content .= "<textarea class=\"css_text_area $text_area_tm text_area_tool_indexation\" ";
			$html_content .= "id=\"{$identificador_unico}\" ";
			$html_content .= "name=\"{$input_name}\" ";
			$html_content .= "data-tipo=\"{$tipo}\" ";
			$html_content .= "data-parent=\"{$parent}\" ";
			$html_content .= "data-lang=\"{$lang}\" ";
			$html_content .= "data-modo=\"{$modo}\" ";
			$html_content .= "data-section_tipo=\"{$section_tipo}\" ";
			$html_content .= "data-role=\"text_area_indexation\" ";
			$html_content .= "title=\"$html_title\">";
			$html_content .= $dato;
			$html_content .= "</textarea>";

			if (SHOW_DEBUG) {
			#$html_content .= "<span class=\"debug_info\"> $identificador_unico</span>";
			}				
			
			#
			# BTN CREATE FRAGMENT  
			#
			#if($caller_id>0)
			$html_content .= "<div class=\"css_button_generic btn_create_fragment\" style=\"display:none\" ";
			$html_content .= "onmousedown=\"tool_indexation.create_fragment(this,event);\" ";
			$html_content .= "data-identificador_unico=\"$identificador_unico\" ";
			$html_content .= "data-parent=\"{$parent}\" ";
			$html_content .= "data-section_tipo=\"{$section_tipo}\" ";
			$html_content .= "data-tipo=\"{$tipo}\" ";
			$html_content .= "data-lang=\"{$lang}\" ";			
			$html_content .= ">";				
			$html_content .= label::get_label('crear_nuevo_fragmento');
			if(SHOW_DEBUG) {
				#$html_content .= " <span class=\"debug_info\">[caller_id:$caller_id]</span>";
			}
			$html_content .= "</div>";


			if(SHOW_DEBUG) {
				#$html_content .= " <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";
			}
			break;				
	}

	# INIT : Init text editor 
	$html_content .= "<script>";
	$html_content .= "component_text_area.init({uid:'$identificador_unico',modo:'$modo',propiedades:'$propiedades_json'});";
	$html_content .= "tool_indexation.fix_height()";
	$html_content .= "</script>";
	
	
	# Prepare content to show in page
	tools::prepare_content($html_content);

	
	# PRINT HTML	
	print $html_content;
	
	
	print "</div>"; //wrap

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out', $modo, $lang);

?>