<?php

	# VISUALIZADOR HTML	
		
	# BUTTON TOOL IN INSPECTOR
	$html_tool    = "\n<!-- TOOL_REPLACE_COMPONENT_DATA [tipo:$tipo parent:$parent] -->";
	$html_tool   .= "<div class=\"tool_inspector_div\">";

	$btn_title	  = label::get_label('abrir').' '.label::get_label('herramienta');
	$html_tool   .= "\n<div class=\"icon_bs tool_relation_icon link\"
								data-tipo=\"{$tipo}\" data-parent=\"{$parent}\" data-caller_id=\"{$parent}\"
								title=\"$btn_title\"
								onclick=\"tool_common.open_tool_replace_component_data(this)\"
								> </div> ";


	$html_tool   .= label::get_label('tool_replace_component_data');
	

	$html_tool   .= "</div>";#/tool_inspector_div

	# PRINT HTML
	print $html_tool;
	
?>