<?php
	

	# HTML VIEW
	


	$html    = "\n<!-- TOOL PAGE [tipo:$component_tipo] -->";
	$html   .= "\n<div class=\"wrap_tool wrap_tool_replace_component_data_page\" >";
	$html   .= "\n<div class=\"content_data tool_replace_component_data_text\" >";

	
		// 'Se reemplazara el contenido del campo: %s en los %s registros actuales con el valor %s'
		$dialog = label::get_label('tool_replace_component_data_dialog');
			#dump($dialog, ' dialog'.to_string());
		
		$label 			= "<label>$label</label>";
		if (empty($valor)) {
			$valor 		= "<label><i>". label::get_label('vacio') ."</i></label>";
		}else{
			$valor 		= "<label>$valor</label>";
		}
		
		$total_records 	= "<label>$total_records</label>";
		if ($lang==DEDALO_DATA_NOLAN) {
			$lang_text		= "<label>". label::get_label('todos') ."</label>";
		}else{
			$lang_text		= "<label>". lang::get_name_from_code( $lang, DEDALO_DATA_LANG ) ."</label>";
		}
		
			#dump($lang, " lang ".to_string());

		$html   .= sprintf($dialog, $label, $total_records, $valor, $lang_text );

		# Cancel button
		//$html .= "<div class=\"css_button_generic button_cancel\" onclick=\"top.$('#dialog_page_iframe').dialog('close');\">".label::get_label('cancelar')."</div>";

		# Ok button
		$html .= "<div class=\"css_button_generic button_replace\" onclick=\"tool_replace_component_data.replace_data(this)\"
		data-component_tipo=\"$component_tipo\"
		data-parent=\"$section_id\"
		data-section_tipo=\"$section_tipo\"
		>";
		$html .= label::get_label('tool_do_replace');
		$html .= "</div>";



		$html .= "<div id=\"tool_replace_component_data_response\"></div>";
	
	$html .= "\n</div><!-- /content_data -->";
	$html .= "\n</div><!-- /wrap_tool -->"; //wrap_tool

	
	# INSPECTOR LOG TOOL
	$html .= "\n<div id=\"inspector_log\" class=\"tool_transcription_inspector_log\"> </div>";




	print $html;

?>