<?php	

	# HTML VIEW

	$html    = "<!-- TOOL PAGE [tipo:$component_tipo] -->";
	$html   .= "<div class=\"wrap_tool wrap_tool_replace_component_data_page\" >";
	$html   .= "<div class=\"content_data tool_replace_component_data_text\" >";

	
		// 'Se reemplazara el contenido del campo: %s en los %s registros actuales con el valor %s'
		$dialog = label::get_label('tool_replace_component_data_dialog');
			#dump($dialog, ' dialog'.to_string());
		
		$label 			= "<label>$label</label>";
		if (empty($valor)) {
			$valor 		= "<label><i>". label::get_label('vacio') ."</i></label>";
		}else{
			$valor 		= "<label>$valor</label>";
		}
		
		$total_records 	= "<label>$total_records</label>";
		if ($lang===DEDALO_DATA_NOLAN) {
			$lang_text		= "<label>". label::get_label('todos') ."</label>";
		}else{
			$lang_text		= "<label>". lang::get_name_from_code( $lang, DEDALO_DATA_LANG ) ."</label>";
		}
		

		$html .= sprintf($dialog, $label, $total_records, $valor, $lang_text);

		
		# Ok button
		$html .= "<div class=\"css_button_generic button_replace\" onclick=\"tool_replace_component_data.replace_data(this)\" ";
		$html .= "data-component_tipo=\"$component_tipo\" ";
		$html .= "data-parent=\"$section_id\" ";
		$html .= "data-section_tipo=\"$section_tipo\" ";
		$html .= ">";
		$html .= label::get_label('tool_do_replace');
		$html .= "</div>";


		$html .= '<div id="tool_replace_component_data_response"></div>';
	
	$html .= "</div><!-- /content_data -->";
	$html .= "</div><!-- /wrap_tool -->"; //wrap_tool

	
	# INSPECTOR LOG TOOL
	$html .= "<div id=\"inspector_log\" class=\"tool_transcription_inspector_log\"> </div>";



	print $html;

?>