<?php

	# VISUALIZADOR HTML
	$html_tool  ='';
	
	$html_tool .= "<div id=\"tool_diffusion_thesaurus\">";
	
	$html_tool .= "\n <div class=\"btn_inside_section_buttons_container tool_diffusion button_duffusion_thesaurus\">";

	# Button label
	$html_tool .= "<span onclick=\"tool_diffusion.export_thesaurus()\">".label::get_label('tool_diffusion')."</span>";

	$html_tool .= "<select id=\"tool_diffusion_thesaurus_select\" data-options='$options_json' onchange=\"tool_diffusion.export_thesaurus(this,'')\" >";
	$html_tool .= "<option></option>";
	$separator = "<option disabled=\"disabled\"> --------------- </option>";
	foreach ($ar_thesaurus_tables as $prefix => $name) {

		if ($name=='separator') {
			$html_tool .= $separator;
			continue;
		}

		$ar_prefix = json_encode( array($prefix) );
		$html_tool .= "<option value='$ar_prefix'>";
		$html_tool .= $name;
		$html_tool .= "</option>";
	}
	$all_json = json_encode( array_keys($ar_thesaurus_tables) );
	
	$html_tool .= "<option value='$all_json'>".label::get_label('todos')."</option>";
	$html_tool .= "</select>";

	

	$html_tool .= "</div></div>";//end tool_diffusion_thesaurus
	
	# PRINT HTML
	echo $html_tool;
	
?>