<?php

	# VISUALIZADOR HTML		

	
	#print "<!-- MAX ROWS [tipo:$tipo] -->";
	print "<div class=\"wrap_component css_wrap_max_rows\" id=\"wrap_{$tipo}\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch(true) {
			
		case $permissions===0	:	$html_content .= "";
					break;		
						
		case ($permissions>=1)	:
		
					$html_content .= "<input class=\"css_max_rows\" type=\"text\" name=\"max_rows\" value=\"{$valor}\" title=\"$html_title\" />";
					break;					
	}
	
	
	# PRINT HTML
	print $html_label;
	print $html_content;

	# INIT COMPONENT
	#require(DEDALO_LIB_BASE_PATH . "/component_common/trigger.component_init.php");
	
	
	print "</div>"; //wrap
?>