<?php

	# VISUALIZADOR HTML	
	
	
	
	#print "\n<!-- MAX ROWS [tipo:$tipo] -->";
	print "\n<div class=\"wrap_component css_wrap_max_rows\" id=\"wrap_{$tipo}\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "";
					break;		
						
		case ($permissions>=1)	:
		
				$html_contenido .= "\n <input type=\"text\" name=\"max_rows\" class=\"css_max_rows\" value=\"1\" title=\"$html_title\" readonly />";
											
	}
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;

	# INIT COMPONENT
	#require(DEDALO_LIB_BASE_PATH . "/component_common/trigger.component_init.php");	
	
	print "\n</div>\n\n"; //wrap
?>