<?php

	# VISUALIZADOR HTML		
	
	
	if(isset($_REQUEST[$tipo])) $dato = $_REQUEST[$tipo];		#var_dump($_REQUEST[$tipo]);
	
	
	#print "\n<!-- MAX ROWS [tipo:$tipo] -->";
	print "\n<div class=\"css_wrap_max_rows\" id=\"wrap_{$tipo}\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "";
					break;		
						
		case ($permissions>=1)	:
		
					$html_contenido .= "\n <input class=\"css_max_rows\" type=\"text\" name=\"max_rows\" value=\"{$valor}\" title=\"$html_title\" />";
					break;					
	}
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;

	# INIT COMPONENT
	#require(DEDALO_LIB_BASE_PATH . "/component_common/trigger.component_init.php");
	
	
	print "\n</div>\n\n"; //wrap
?>