<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 		$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_max_rows'])) 		$ar_css['css_max_rows']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 	$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))	$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_max_rows']))	$ar_css['css_wrap_max_rows']='';
	
	
	if(isset($_REQUEST[$tipo]))					$dato = $_REQUEST[$tipo];		#var_dump($_REQUEST[$tipo]);
	
	
	#print "\n<!-- MAX ROWS [tipo:$tipo] -->";
	print "\n<div class=\"css_wrap_max_rows {$ar_css['css_wrap_max_rows']}\" id=\"wrap_{$tipo}\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." (max_rows) [$tipo] </span>";
					break;		
						
		case ($permissions>=1)	:
		
					$html_contenido .= "\n <input class=\"css_max_rows {$ar_css['css_max_rows']}\" type=\"text\" name=\"max_rows\" value=\"{$valor}\" title=\"$html_title\" />";
											
	}
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;

	# INIT COMPONENT
	#require(DEDALO_LIB_BASE_PATH . "/component_common/trigger.component_init.php");
	
	
	print "\n</div>\n\n"; //wrap
?>