<?php

	# VISUALIZADOR HTML	

	
	$html_contenido = '';


	/**
	* CURRENT TESAURUS ROW
	*/
	# Key icon
	$html_contenido .= "\n <div class=\"tesauro_index_list_key\"> </div>";
	
	# Remove link
	$html_contenido .= "\n <div class=\"tesauro_index_list_remove\" 
	data-id_matrix=\"$current_matrix_id\" data-rel_locator=\"$rel_locator\" data-tag=\"$tag\" data-termino_id=\"$terminoID\" data-termino=\"$termino\" 
	onclick=\"component_text_area.remove_index(this)\"
	>";
	$html_contenido .= label::get_label('remove');
	$html_contenido .= "</div>";

	# Termino text
	$html_contenido .= "\n <div class=\"tesauro_index_list_termino\">{$termino} <span>[$terminoID]</span></div>";
	
	

	# PRINT HTML
	print $html_contenido;
	
?>