<?php

	# VISUALIZADOR HTML
	
	print "<div class=\"wrap_component css_wrap_relation_index tooltip_active in_search_mode\"id=\"{$id_wrapper}\" ";
	print 'title="'.search_development2::search_options_title( $this->search_operators_info() ).'" ';
	print "data-tipo=\"{$tipo}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-component_info='{$component_info}' ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato='".json_encode($dato)."' ";
	print ">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch(true) {
			
		case ($permissions===0) :
				$html_content .= "";
				break;
						
		
		case ($permissions>=1)	:

				# Q_OPERATOR
				$html_content .= '<input class="q_operator" type="text" value="'.$q_operator.'" ';
				$html_content .= 'onchange="component_common.fix_dato(this,\''.$component_name.'\')" ';
				$html_content .=' />';
					
				# INPUT
				#$html_content .= "<input class=\"css_relation_index\" type=\"text\" name=\"{$search_input_name}\" value=\"\"/> ";
				
	}
	
	# Prepare content to show in page
	tools::prepare_content($html_content);
	

	# PRINT HTML
	print $html_label;
	print $html_content;	

	
	print "</div>"; //wrap
?>