<?php

	# VISUALIZADOR HTML	

	
	#print "\n\n<!-- BUTTON NEW [tipo:$tipo id_matrix:$id] -->";
	#print "\n<div class=\"css_wrap_button_new\">";
	
	# ETIQUETA (LABEL)
	#$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
		
	switch($permissions) {
			
		case 0	:	$html_contenido .= "";	//\n <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." (button_stats)</span>";
					break;
						
		case ($permissions>=2)	:
					
					# BUTTON SHOW STATS
					$html_contenido .= "\n <div class=\"css_button_generic css_button_stats link\" onclick=\"button_stats.Stats(this)\" 
					data-tipo=\"{$context_tipo}\"					
					title=\"$html_title\" >";
					$html_contenido .= $label;
					$html_contenido .= "</div>";

					$date_yesterday		= component_date::get_timestamp_now_for_db( array('sub'=>'P1D') );
					$fecha_de_los_datos	= date("Y-m-d", strtotime($date_yesterday));

					# Usuario logeado actualmente
					$user_id	= navigator::get_user_id();

					# Verificamos que el usuario logeado es administrador
					$is_global_admin = component_security_administrator::is_global_admin($user_id);

					/*
					# INPUT TEXT FECHA
					# Por defecto ocultamos este campo, que se rellena con la fecha de ayer (ya que las estadísticas del día de hoy no estarán hasta que no acabe el día salvo que se
					# fuerce su creación con el botón 'Generate'). Para el global admin, lo haremos visible
					if ($is_global_admin) {
						$add_css = "show_stats_date";
					}else{
						$add_css = '';
					}
					$html_contenido .= "\n <input type=\"text\" value=\"$fecha_de_los_datos\" class=\"css_input_text input_stats_date $add_css\" />";


					# BUTTON GENERATE
					# Permite (sólo al global admin) regenerar las estadísticas para una fecha específica. Permite cambiar el valor del campo de fecha de los datos y llamar al trigger como 
					# si se ejecutara el cron automático. Elimina posibles datos procesados de ese día existentes en matrix_stats para evitar redundancias
					if ($is_global_admin) {
						# TRIGGER BUTTON
						$html_contenido .= "\n <div class=\"css_button_generic stats_generate_button\" onclick=\"button_stats.Generate(this)\">Generar</div>";
					}
					*/

					if(SHOW_DEBUG) {
						#$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
					}	
					break;											
	}
	
	
	# PRINT HTML
	print $html_contenido;
	
	
	#print "\n</div><!-- /css_wrap_button_new -->\n\n"; //wrap
?>