/**
 * THE HOST-WIDE NGINX MAP — the pure half of root's renderer (spec §13.3, §13.5).
 *
 * nginx's http{}-level map defines three variables ONCE per host, and several instances
 * share the host. Each instance's agent writes only its own CONTRIBUTION
 * (`contrib/<instance>.json`: one envelope, its engine's config-hash, its pin set); root's
 * oneshot (./host_map_main.ts) re-validates every contribution, decides which to keep
 * (`planHostMap`), and renders ONE file from them (`renderHostMap`):
 *   - the auth-key map, identical for everyone (pinned);
 *   - in each SVG map one envelope entry per distinct envelope (sorted, each once), then the
 *     quarantine entry, then `default`;
 *   - the header values of the NEWEST admitted pin set among the contributions.
 * When every instance contributes the same map (same engine version, same media dir) the
 * file is BYTE-IDENTICAL to the engine's buildNginxMap() (test/unit/publication_host_nginx_map_native.test.ts).
 *
 * WHAT ROOT TRUSTS: nothing a contribution says about itself. A file is kept only when its
 * name is `_seed` and root owns it, or its name is an instance in `identities.json` (root-written
 * by `provision apply`) and its lstat uid is that instance's agent uid; then its JSON must pass
 * judgeContribution (./directives.ts). A grammar or pin set this code does not know refuses the
 * WHOLE render (`map_contribution_newer`) — never skipped: skipping would drop a newer
 * instance's envelope from the host file. Each instance is BOUND to the envelope it first
 * contributed (`bindings.json`); a different envelope is refused (`map_envelope_rebind`) and
 * the bound one keeps being served, until that instance's `provision apply` clears the binding.
 *
 * ZERO-DEPENDENCY (it is part of root's renderer copy, src/provision/host_map_renderer.ts):
 * node: builtins and ./directives.
 */

import { createHash } from 'node:crypto';
import {
  CONTRIBUTION_INSTANCE,
  judgeContribution,
  MAP_AUTH_COOKIE,
  MAP_AUTH_INVALID,
  MAP_AUTH_PATTERN,
  type MapContribution,
  NGINX_MAP_PINS,
  type NginxMapPins,
  pinsById,
  SEED_CONTRIBUTION,
} from './directives';

/** The live file in HOST_NGINX_MAP_DIR the provisioned include (render/nginx_map_include.ts) loads. */
export const HOST_MAP_FILE = 'dedalo_media_map.nginx.conf';
export const HOST_MAP_RESULT_FILE = 'result.json';
export const HOST_MAP_BINDINGS_FILE = 'bindings.json';
export const HOST_MAP_CONTRIB_DIR = 'contrib';
/** `identities.json` in HOST_MAP_RENDERER_DIR (provision apply rewrites it on every apply). */
export const IDENTITIES_FILE = 'identities.json';
/** The largest contribution file root reads (and an agent writes). */
export const MAX_CONTRIBUTION_BYTES = 64 * 1024;
/** Directory entries examined per render; the rest are counted invalid unread. */
export const CONTRIB_SCAN_CAP = 256;
const HOST_HASH_DOMAIN = 'dedalo-host-map\n';

/* ── rendering ────────────────────────────────────────────────────────────────────── */

/** What renderHostMap needs of each kept contribution. */
export type RenderableContribution = Pick<MapContribution, 'hash' | 'envelope' | 'pinsId'>;

/** The host file's own hash: the contributions' when they share one, else a digest of the distinct ones. */
export function hostMapHash(contributions: readonly Pick<MapContribution, 'hash'>[]): string {
  const hashes = [...new Set(contributions.map(c => c.hash))].sort();
  if (hashes.length === 1) return hashes[0] as string;
  return createHash('sha256').update(`${HOST_HASH_DOMAIN}${hashes.join('\n')}`).digest('hex');
}

/**
 * The canonical host file, with the comment lines of buildNginxMap() (src/core/media/protection.ts;
 * the native gate holds the single-contribution render byte-equal to it). Throws on an empty
 * list or an unknown pin id: callers render only judged contributions.
 */
export function renderHostMap(
  contributions: readonly RenderableContribution[],
  pinsTable: readonly NginxMapPins[] = NGINX_MAP_PINS,
): { text: string; hash: string } {
  if (contributions.length === 0) throw new Error('renderHostMap: no contribution to render');
  let newest = -1;
  for (const contribution of contributions) {
    const index = pinsTable.findIndex(pins => pins.id === contribution.pinsId);
    if (index === -1) throw new Error(`renderHostMap: unknown pin set '${contribution.pinsId}'`);
    newest = Math.max(newest, index);
  }
  // NEWEST = latest in the append-only table (`pinsTable` is a parameter only so a gate can hold two sets).
  const pins = pinsTable[newest] as NginxMapPins;
  const envelopes = [...new Set(contributions.map(c => c.envelope))].sort();
  const hash = hostMapHash(contributions);
  const distinct = [...new Set(contributions.map(c => c.hash))].sort();
  const lead = [
    '# Dédalo media access control — GENERATED by src/core/media/protection.ts.',
    '# Include this in the http{} context (a map cannot live inside server{}).',
    `# config-hash: ${hash}`,
    ...(distinct.length > 1 ? [`# contributions: ${contributions.length} ${distinct.join(' ')}`] : []),
    '# It sanitizes the auth cookie to hex-only before it is used in a file path,',
    '# and classifies the URI for the MEDIA-03 response headers.',
  ];
  const text = [
    ...lead,
    `map $cookie_${MAP_AUTH_COOKIE} $dedalo_auth_key {`,
    `\t"${MAP_AUTH_PATTERN}"  $h;`,
    `\tdefault                   "${MAP_AUTH_INVALID}";`,
    '}',
    '',
    '# MEDIA-03: the ENVELOPE pattern must come FIRST — nginx map regexes are tested in',
    '# order and an envelope is also an `.svg`. Getting this order wrong sends every',
    '# server-generated envelope down the attachment branch and blanks the edit view.',
    'map $uri $dedalo_svg_disposition {',
    ...envelopes.map(envelope => `\t"~${envelope}"  "";`),
    `\t"~${pins.quarantine}"  "${pins.disposition}";`,
    '\tdefault                    "";',
    '}',
    '',
    'map $uri $dedalo_svg_csp {',
    ...envelopes.map(envelope => `\t"~${envelope}"  "${pins.envelopeCsp}";`),
    `\t"~${pins.quarantine}"  "${pins.quarantineCsp}";`,
    '\tdefault                    "";',
    '}',
    '',
  ].join('\n');
  return { text, hash };
}

/* ── the records root writes ──────────────────────────────────────────────────────── */

/** The reasons root records against one contribution (the agent maps each to its wire reason). */
export type HostMapRefusalReason =
  | 'map_contribution_foreign'
  | 'map_refused'
  | 'map_envelope_rebind'
  | 'map_contribution_newer'
  | 'undeclared';

export interface HostMapRefusal {
  readonly instance: string;
  readonly reason: HostMapRefusalReason;
  /** map_contribution_newer: the grammar / pin set this renderer does not know. */
  readonly grammar?: number;
  readonly pins_id?: string;
}

export interface HostMapEntry {
  readonly instance: string;
  readonly hash: string;
  readonly grammar: number;
  readonly pins_id: string;
  readonly envelope: string;
}

/** Every way one render ends. `empty` = nothing to render (the live file is left as it is). */
export const HOST_MAP_OUTCOMES = [
  'applied',
  'unchanged',
  'empty',
  'configtest_failed',
  'reload_failed',
  'host_busy',
  'lock_missing',
  'map_contribution_newer',
  'identities_invalid',
] as const;
export type HostMapOutcome = (typeof HOST_MAP_OUTCOMES)[number];

/** `result.json` (root:root 0644): the agents answer from it, `GET /v1/status` reads it. */
export interface HostMapResult {
  readonly v: 1;
  readonly seq: number;
  readonly at: string;
  readonly outcome: HostMapOutcome;
  /** The `# config-hash:` of the LOADED host file, or null (absent, or a reload pending). */
  readonly host_hash: string | null;
  readonly contributions: readonly HostMapEntry[];
  readonly refused: readonly HostMapRefusal[];
  readonly invalid: number;
}

const HEX64 = /^[0-9a-f]{64}$/;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isEntry(value: unknown): value is HostMapEntry {
  return (
    isRecord(value) &&
    typeof value.instance === 'string' &&
    typeof value.hash === 'string' &&
    HEX64.test(value.hash) &&
    Number.isSafeInteger(value.grammar) &&
    typeof value.pins_id === 'string' &&
    typeof value.envelope === 'string'
  );
}

function isRefusal(value: unknown): value is HostMapRefusal {
  return isRecord(value) && typeof value.instance === 'string' && typeof value.reason === 'string';
}

/** A result.json, or null when the text is not one (never a throw: the agent reads it too). */
export function parseHostMapResult(text: string | null): HostMapResult | null {
  if (text === null) return null;
  let value: unknown;
  try {
    value = JSON.parse(text);
  } catch {
    return null;
  }
  if (!isRecord(value) || value.v !== 1 || !Number.isSafeInteger(value.seq) || typeof value.at !== 'string') return null;
  if (!(HOST_MAP_OUTCOMES as readonly unknown[]).includes(value.outcome)) return null;
  if (value.host_hash !== null && !(typeof value.host_hash === 'string' && HEX64.test(value.host_hash))) return null;
  if (!Array.isArray(value.contributions) || !value.contributions.every(isEntry)) return null;
  if (!Array.isArray(value.refused) || !value.refused.every(isRefusal)) return null;
  if (!Number.isSafeInteger(value.invalid)) return null;
  return value as unknown as HostMapResult;
}

/** `identities.json` (root 0644, provision apply): `{<instance>: <agent uid>}` of every nginx conf_d declaration. */
export function parseIdentities(text: string | null): Readonly<Record<string, number>> | null {
  if (text === null) return null;
  let value: unknown;
  try {
    value = JSON.parse(text);
  } catch {
    return null;
  }
  if (!isRecord(value)) return null;
  const out: Record<string, number> = {};
  for (const [instance, uid] of Object.entries(value)) {
    if (!CONTRIBUTION_INSTANCE.test(instance) || !Number.isSafeInteger(uid) || (uid as number) < 0) return null;
    out[instance] = uid as number;
  }
  return Object.freeze(out);
}

/** `bindings.json` (root 0644, this renderer): `{<instance>: <envelope>}`; an unreadable file binds nothing new over. */
export function parseBindings(text: string | null): Record<string, string> {
  if (text === null) return {};
  try {
    const value: unknown = JSON.parse(text);
    if (!isRecord(value)) return {};
    const out: Record<string, string> = {};
    for (const [instance, envelope] of Object.entries(value)) {
      if (CONTRIBUTION_INSTANCE.test(instance) && typeof envelope === 'string') out[instance] = envelope;
    }
    return out;
  } catch {
    return {};
  }
}

/**
 * `bindings.json` without `instance`'s binding — what that instance's `provision apply` writes
 * (the ONLY way a binding is cleared, spec §13.5), so its next contribution binds afresh.
 * Null when there was nothing to clear (no write needed).
 */
export function withoutBinding(text: string | null, instance: string): string | null {
  const bindings = parseBindings(text);
  if (!Object.hasOwn(bindings, instance)) return null;
  delete bindings[instance];
  return canonicalRecord(bindings);
}

/** Canonical JSON for the root-written records: sorted keys at the top level, trailing newline. */
export function canonicalRecord(value: Readonly<Record<string, unknown>>): string {
  const sorted: Record<string, unknown> = {};
  for (const key of Object.keys(value).sort()) sorted[key] = value[key];
  return `${JSON.stringify(sorted, null, 2)}\n`;
}

/* ── the decision ─────────────────────────────────────────────────────────────────── */

/** One directory entry of `contrib/`, as root observed it (lstat never followed; JSON read O_NOFOLLOW). */
export interface ContribEntry {
  readonly name: string;
  readonly facts: { readonly type: 'file' | 'dir' | 'symlink' | 'other'; readonly uid: number; readonly size: number } | null;
  /** The parsed JSON; `undefined` = unreadable or not JSON. Only read for a name/owner that passed. */
  readonly json?: unknown;
}

export type HostMapPlan =
  | {
      readonly kind: 'newer';
      readonly newer: HostMapRefusal;
      readonly refused: readonly HostMapRefusal[];
      readonly invalid: number;
    }
  | {
      readonly kind: 'render';
      /** In instance order; the seed alone when no real contribution was kept. */
      readonly kept: readonly HostMapEntry[];
      /** A seed file is present and a real contribution exists: remove it after a successful render. */
      readonly dropSeed: boolean;
      readonly bindings: Readonly<Record<string, string>>;
      readonly bindingsChanged: boolean;
      readonly refused: readonly HostMapRefusal[];
      readonly invalid: number;
    };

/** Which name/owner pair may carry a contribution; null = keep reading it, else why not. */
export function ownerProblem(
  entry: ContribEntry,
  identities: Readonly<Record<string, number>>,
): HostMapRefusalReason | 'skip' | null {
  const stem = entry.name.endsWith('.json') ? entry.name.slice(0, -'.json'.length) : null;
  if (entry.name.startsWith('.')) return 'skip'; // an agent's own `.<instance>.json.tmp` mid-write
  if (stem === null) return 'map_refused';
  if (entry.facts === null) return 'skip'; // removed between readdir and lstat
  if (entry.facts.type !== 'file') return 'map_contribution_foreign';
  if (entry.facts.size > MAX_CONTRIBUTION_BYTES) return 'map_refused';
  if (stem === SEED_CONTRIBUTION) return entry.facts.uid === 0 ? null : 'map_contribution_foreign';
  const uid = identities[stem];
  if (uid === undefined) return 'undeclared';
  return entry.facts.uid === uid ? null : 'map_contribution_foreign';
}

function entryOf(contribution: MapContribution): HostMapEntry {
  return {
    instance: contribution.instance,
    hash: contribution.hash,
    grammar: contribution.grammar,
    pins_id: contribution.pinsId,
    envelope: contribution.envelope,
  };
}

function shownName(name: string): string | null {
  const stem = name.endsWith('.json') ? name.slice(0, -'.json'.length) : name;
  return CONTRIBUTION_INSTANCE.test(stem) || stem === SEED_CONTRIBUTION ? stem : null;
}

/**
 * The bound envelope's entry when `instance` is refused for a rebind: its entry from the
 * previous result when that one carried the bound envelope, else the bound envelope under the
 * refused contribution's hash and pins (the binding outlived the result that recorded it).
 */
function boundEntry(instance: string, envelope: string, rejected: MapContribution, previous: HostMapResult | null): HostMapEntry {
  const before = previous?.contributions.find(entry => entry.instance === instance && entry.envelope === envelope);
  if (before !== undefined && pinsById(before.pins_id) !== null) return before;
  return { instance, hash: rejected.hash, grammar: rejected.grammar, pins_id: rejected.pinsId, envelope };
}

/** Root's decision over one directory listing (pure: every fact is an input). */
export function planHostMap(input: {
  readonly entries: readonly ContribEntry[];
  readonly identities: Readonly<Record<string, number>>;
  readonly bindings: Readonly<Record<string, string>>;
  readonly previous: HostMapResult | null;
}): HostMapPlan {
  const refused: HostMapRefusal[] = [];
  let invalid = 0;
  const reject = (name: string, reason: HostMapRefusalReason) => {
    invalid++;
    const instance = shownName(name);
    if (instance !== null) refused.push({ instance, reason });
  };
  const accepted: MapContribution[] = [];
  let seed: MapContribution | null = null;
  const sorted = [...input.entries].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  for (const [index, entry] of sorted.entries()) {
    if (index >= CONTRIB_SCAN_CAP) {
      invalid++;
      continue;
    }
    const owner = ownerProblem(entry, input.identities);
    if (owner === 'skip') continue;
    if (owner !== null) {
      reject(entry.name, owner);
      continue;
    }
    const stem = entry.name.slice(0, -'.json'.length);
    const verdict = judgeContribution(entry.json, stem);
    if (!verdict.ok && verdict.newer) {
      const newer: HostMapRefusal = { instance: stem, reason: 'map_contribution_newer', grammar: verdict.grammar, pins_id: verdict.pinsId };
      return { kind: 'newer', newer, refused: [...refused, newer], invalid: invalid + 1 };
    }
    if (!verdict.ok) {
      reject(entry.name, 'map_refused');
      continue;
    }
    if (stem === SEED_CONTRIBUTION) seed = verdict.contribution;
    else accepted.push(verdict.contribution);
  }

  // The cap: one contribution per declared nginx instance (names are unique per directory, and
  // only declared names reach here), so this can only fail if identities were read wrongly.
  if (accepted.length > Object.keys(input.identities).length) {
    throw new Error('planHostMap: more contributions than declared nginx instances');
  }
  const bindings: Record<string, string> = { ...input.bindings };
  let bindingsChanged = false;
  const kept: HostMapEntry[] = [];
  for (const contribution of accepted) {
    const bound = bindings[contribution.instance];
    if (bound === undefined) {
      bindings[contribution.instance] = contribution.envelope;
      bindingsChanged = true;
      kept.push(entryOf(contribution));
    } else if (bound === contribution.envelope) {
      kept.push(entryOf(contribution));
    } else {
      refused.push({ instance: contribution.instance, reason: 'map_envelope_rebind' });
      kept.push(boundEntry(contribution.instance, bound, contribution, input.previous));
    }
  }
  if (kept.length === 0 && seed !== null) {
    return { kind: 'render', kept: [entryOf(seed)], dropSeed: false, bindings, bindingsChanged, refused, invalid };
  }
  return { kind: 'render', kept, dropSeed: seed !== null, bindings, bindingsChanged, refused, invalid };
}

/** renderHostMap over plan entries. */
export function renderEntries(entries: readonly HostMapEntry[]): { text: string; hash: string } {
  return renderHostMap(entries.map(entry => ({ hash: entry.hash, envelope: entry.envelope, pinsId: entry.pins_id })));
}
