<?php
	
	# VISUALIZADOR HTML	
	
	print "<!-- area_activity [tipo:$tipo modo:$modo] -->";
	print "<div class=\"css_wrap_area css_wrap_area_activity\" 
	data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-component_name=\"{$component_name}\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= " <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." (input_text)</span>";
					break;
						
		#case 1	: 	$html_contenido .= " <span class=\"css_span_dato\">Read only access</span>";
		#			break;	
						
		case ($permissions>=1)	:
		
					$html_contenido .= " You are in $component_name page of $label ";	


					$html_contenido .= " <br>Please select a section: ";
					$html_contenido .= " <blockquote>";
					
					#$menu = new menu('list');
					#$html_contenido .= 	"<hr>".$menu->get_html();	
					$ar_sections = component_relation::get_all_authorized_content_sections();				
					foreach ($ar_sections as $tipo => $name) {
						$html_contenido .= "<br> <a href=\"?t=$tipo\" class=\"link\">$name</a> ";
					}
					$html_contenido .= " </blockquote>";
					
					if(SHOW_DEBUG) {
						#$html_contenido .= " <span class=\"css_span_debugger\" id=\"debugger_{$id}\" >{$debugger}</span>";	
					}		
					break;				
	}	
	
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);

	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "</div><!-- /area_activity [tipo:$tipo modo:$modo] -->"; //wrap



?>