<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 			$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_input_text'])) 			$ar_css['css_input_text']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 		$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))		$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_input_text']))		$ar_css['css_wrap_input_text']='';
	
	if(!isset ($html_tools))						$html_tools='';
	
	
	print "\n<!-- INPUT_TEXT [tipo:$tipo id_matrix:$id] -->";
	print "\n<div class=\"css_wrap_input_text wrap_component {$ar_css['css_wrap_input_text']}\" 
	data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" >";
		
	# ETIQUETA (LABEL)
	#$html_label = component_common_draw::draw_label($this);
	$html_label = "$lang_name <br>";
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> No access here ! (input_text)</span>";
					break;
						
		case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\">$dato</span>";
					break;	
						
		case ($permissions>=2)	:
		
					$html_contenido .= "\n <input class=\"css_input_text {$ar_css['css_input_text']}\" type=\"text\" 
					id=\"{$identificador_unico}\" name=\"{$tipo}_{$id}\" 
					data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" 
					value=\"{$dato}\" 
					title=\"$html_title\" 
					style=\"width:90%\"
					/>";	
					$html_contenido .= "\n <div class=\"css_lang_image_delete div_image_link\" onclick=\"tool_lang.delete_lang(this)\" data-tipo=\"$tipo\" data-id_matrix=\"$id\" ></div>";			
					
					#$html_contenido .= "\n <span  class=\"css_span_log\"></span>";	
					
					$html_contenido .= $html_tools;
					
			if($permissions==3)		
					$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$debugger}</span>";						
											
	}
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;	
	
	print "\n</div>\n\n"; //wrap
	
?>

<script>
	// Force set current values to data vars
	$('.css_lang_record_rows, .css_input_text:input').each(function() {
		$(this).data('oldVal', $(this).val());
	});
</script>