<div id="actividades_list_content">
	<div id="list_left"></div>
	<div id="list_right">
	<?php
		#
		# HTML LIST
		$html='';
		$html .= "\n<ul class=\"rows\">";
		#
		# rows iterate
		# dump($ar_rows, ' ar_rows ++ '.to_string());
		# ubicacion
		$last_showed_day = null;
		foreach ($ar_rows as $key => $row_obj) {

			$current_day = isset($row_obj->date_showed_obj->day_of_month) ? $row_obj->date_showed_obj->day_of_month.'_'.$row_obj->date_showed_obj->month_name : 0; #echo $current_day.", ";
			$li_class = '';
			if ($current_day===$last_showed_day) {
				$li_class = 'same_day';
			}
			
			$html .= "\n<li class=\"$li_class\">";

				#
				# Day info
					$html .= "\n<div class=\"day_info\">";
					if (!empty($row_obj->fecha) && !empty($row_obj->date_showed_obj)) {					
						
						$html .= "<span class=\"day_name\">".$row_obj->date_showed_obj->day_name."</span>";
						if ($row_obj->date_showed_obj->is_today===true) {
							$html .= "<span class=\"day_today\">".tstring('hoy')."</span>";
							$html .= "<span class=\"month_name\">".$row_obj->date_showed_obj->day_of_month.' '.$row_obj->date_showed_obj->month_name."</span>";
						}else{
							$html .= "<span class=\"day_of_month\">".$row_obj->date_showed_obj->day_of_month."</span>";
							$html .= "<span class=\"month_name\">".$row_obj->date_showed_obj->month_name."</span>";
						}
					}
					$html .= "\n</div>";//end Day info

				#
				# Activity info
					$html .= "\n<div class=\"activity_info\">";
					if (!empty($row_obj->hora)) {
						if (substr($row_obj->hora, -1)!=='h') {
							$row_obj->hora .= 'h';
						}
						$html .= "<span class=\"hora\">".$row_obj->hora."</span>";
					}
					if (!empty($row_obj->tipo_actividad)) {
						$html .= "<span class=\"tipo_actividad\">".$row_obj->tipo_actividad."</span>";
					}					
					if (!empty($row_obj->fecha_fin) && !empty($row_obj->date_end_obj)) {
						$html .= "\n<div class=\"day_info_end\">";
						$html .= "<span class=\"day_name_end\">";

						$html .= tstring('desde')." ";
						$html .= $row_obj->date_obj->day_name." ";
						$html .= $row_obj->date_obj->day_of_month." ";
						$html .= $row_obj->date_obj->month_name . " ";

						$html .= tstring('hasta_el')." ";
						$html .= $row_obj->date_end_obj->day_name." ";
						$html .= $row_obj->date_end_obj->day_of_month." ";
						$html .= $row_obj->date_end_obj->month_name;
						$html .= "</span>";
						$html .= "\n</div>";
					}
					if(!empty($row_obj->ubicacion)){
						$html .= "<span class=\"ubicacion\"> | ".$row_obj->ubicacion."</span>";
					}
		     		$html .= "<span class=\"titulo\">".$row_obj->titulo."</span>";
		     		$html .= "<span class=\"entidad\">".$row_obj->entidad."</span>";
					$html .= "\n</div>";//end Activity info

			$html .= "</li>";

			$last_showed_day = $current_day;
		}//end foreach ($ar_images as $key => $image)
		$html .= "\n</ul><!-- /records -->";
		
		echo $html;
	?>
	</div><!-- /#list_right -->

	<?php
	$html = '';
	$html .= "<ul id=\"page_circles\">";
	foreach (range(1, $total_pages) as $n_page) {
		$style = '';
		if ($n_page==$page_number) {
			$style = 'selected';
		}
		$html .= "<li class=\"$style\">";
		$html .= "</li>";
	}	
	$html .= "</ul>";

	$lang_label = (WEB_CURRENT_LANG_CODE==="lg-vlca") ? tstring('valenciano') : tstring('castellano');
	$html .= "<div class=\"label_lang\">".$lang_label."</div>";
	echo $html;
	?>
</div><!-- /#actividades_list_content -->

<script>
var actividades_list_vars = {
	total  		 : <?php echo $rows_total ?>,
	offset 		 : <?php echo $rows_offset ?>,
	limit  		 : <?php echo $rows_limit ?>,
	total_pages  : <?php echo $total_pages ?>,
	page_number  : <?php echo $page_number ?>,
	lang 		 : '<?php echo WEB_CURRENT_LANG_CODE ?>',
	max_days 	 : <?php echo $max_days ?>
}
//console.log("actividades_list_vars:",actividades_list_vars);
</script>