<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 		$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_button_send'])) 		$ar_css['css_button_send']='';
	if(!isset ($ar_css['css_span_debugger']))	$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_button_send']))	$ar_css['css_wrap_button_send']='';
		
	
	print "\n<!-- BUTTON SEND [tipo:$tipo id_matrix:$id] -->";
	print "\n<div class=\"css_wrap_button_send {$ar_css['css_wrap_button_send']}\">";
	
	
		# ETIQUETA (LABEL)
		$html_label = component_common_draw::draw_label($this);
		
		# CONTENIDO (INPUT)
		$html_contenido = '';
		switch($permissions) {
				
			case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." (button_send)</span>";
						break;
							
			case 1	: 	$html_contenido .= "";
						break;	
							
			case ($permissions>=2)	:
			
						$html_contenido .= "\n <input class=\"css_button_send {$ar_css['css_button_send']}\" type=\"button\" onclick=\"New(this)\" data-tipo=\"{$target_tipo}\" value=\"$label\" title=\"$html_title\" />";
						
						
				if($permissions==3)		
						$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
						
												
		}
		
		
		# PRINT HTML
		print $html_contenido;

	
	
	print "\n</div><!-- /css_wrap_button_send -->\n\n"; //wrap
?>