<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 		$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_input_text'])) 		$ar_css['css_input_text']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 	$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))	$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_input_text']))	$ar_css['css_wrap_input_text']='';
	
	if(!isset ($html_tools))					$html_tools='';
	
	
	print "\n<!-- INPUT_TEXT [tipo:$tipo id_matrix:$id] $label -->";
	print "\n<div class=\"css_wrap_input_text wrap_component {$ar_css['css_wrap_input_text']}\" id=\"{$id_wrapper}\"
	data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-parent=\"{$parent}\" data-modo=\"{$modo}\" data-dato=\"{$dato}\" data-component_name=\"{$component_name}\" >";
	
		
		# ETIQUETA (LABEL)
		#$html_label = component_common_draw::draw_label($this);
		
		# CONTENIDO (INPUT)
		$html_contenido = '';
		switch($permissions) {
				
			case 0	:	$html_contenido .= "\n <span class=\"css_span_sin_acceso\">".label::get_label('sin_acceso')."</span>";
						break;
							
			case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\">$dato</span>";
						break;	
							
			case ($permissions>=2)	:
			
						$html_contenido .= "\n <input class=\"css_input_text {$ar_css['css_input_text']}\" type=\"text\" 
						name=\"{$input_name}\" 
						data-tipo=\"{$tipo}\" data-id_matrix=\"{$id}\" data-parent=\"{$parent}\" data-lang=\"{$lang}\" 
						value=\"{$dato}\" 
						title=\"$html_title\"
						/>";			
										
						
				if($permissions==3)		
						$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$debugger}</span>";	
												
		}

		# Prepare content to show in page
		tools::prepare_content($html_contenido);	
		

		# PRINT HTML
		#print $html_label;
		print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_input_text INPUT_TEXT [tipo:$tipo id_matrix:$id] $label -->\n"; //wrap


?>