<?php declare(strict_types=1);

require_once __DIR__ . '/class.migration_destination.php';
require_once dirname(__DIR__) . '/core/base/boot/class.env_sync.php';
require_once dirname(__DIR__) . '/core/base/boot/class.env_value.php';

/**
* ENV_WRITER
* Renders the migration's two .env artifacts from the 4a classification, as content
* strings (no disk writes). render_php() → the PHP-side ../private/.env (ENV-destination
* constants with literal values; the salt verbatim). render_bun() → the Bun diffusion
* engine .env, reusing env_sync::MAP (spec Appendix B) so the name map has ONE source.
* Quoting is chosen to round-trip through env_loader::parse (verified by the test).
*/
final class env_writer {

	/** @param array<string,array> $classification migration_classifier::classify() output */
	public static function render_php(array $classification) : string {
		$lines = ['# Dédalo v7 secrets — generated by the migration. chmod 600. Never commit.'];
		foreach ($classification as $name => $info) {
			if ($info['destination'] !== migration_destination::ENV) {
				continue;
			}
			if (($info['record']['kind'] ?? null) !== 'literal') {
				continue; // a secret must have a resolved literal value
			}
			$lines[] = $name . '=' . self::quote((string) self::stringify($info['record']['value']));
		}
		return implode("\n", $lines) . "\n";
	}//end render_php

	/** @param array<string,array> $classification */
	public static function render_bun(array $classification) : string {
		$lines = ['# Dédalo diffusion (Bun) .env — generated by the migration; keys mapped via env_sync::MAP.'];
		foreach (env_sync::MAP as $php_key => $bun_key) {
			if (!isset($classification[$php_key])) {
				continue;
			}
			$record = $classification[$php_key]['record'];
			if (($record['kind'] ?? null) !== 'literal') {
				continue; // runtime/derived (e.g. DEDALO_API_URL) is computed at boot, not migration
			}
			$lines[] = $bun_key . '=' . self::quote((string) self::stringify($record['value']));
		}
		return implode("\n", $lines) . "\n";
	}//end render_bun

	/**
	* Render the per-install CONFIG overrides as readable .env lines (CONSTANT=value): each
	* CONFIG-destination constant whose migrated LITERAL value differs from the catalog default,
	* by constant name and readable type — bool→true/false, null→null, list/map→single-quoted
	* JSON, scalars quoted. Values equal to the default, runtime values, and non-CONFIG
	* destinations are omitted (the catalog seeds defaults). Returns '' when there are no
	* overrides. The migration folds this into ../private/.env, so .env is the single config place.
	* @param array<string,array> $classification
	* @param config_key[] $catalog
	*/
	public static function render_config(array $classification, array $catalog) : string {
		$default_of = [];
		foreach ($catalog as $key) {
			if ($key->const !== null) { $default_of[$key->const] = $key->default; }
		}
		$lines = [];
		foreach ($classification as $name => $info) {
			if ($info['destination'] !== migration_destination::CONFIG) {
				continue;
			}
			if (($info['record']['kind'] ?? null) !== 'literal') {
				continue; // runtime/derived → the catalog computes it
			}
			if (!array_key_exists($name, $default_of)) {
				continue; // CONFIG implies a catalog key; defensive
			}
			$value = $info['record']['value'];
			if ($value === $default_of[$name]) {
				continue; // matches the shipped default — no override needed
			}
			$lines[] = $name . '=' . self::format_value($value);
		}
		sort($lines);
		if ($lines === []) {
			return '';
		}
		return "\n# --- general config (per-install overrides; or edit ../private/config.local.php) ---\n"
			. implode("\n", $lines) . "\n";
	}//end render_config

	/** A typed config value → a readable .env value (bool/null as literals; arrays as JSON; scalars quoted). */
	private static function format_value(mixed $value) : string {
		if ($value === null) {
			return 'null';
		}
		if (is_bool($value)) {
			return $value ? 'true' : 'false';
		}
		if (is_int($value) || is_float($value)) {
			return (string) $value;
		}
		if (is_array($value)) {
			return self::quote((string) json_encode($value));
		}
		return self::quote((string) $value);
	}//end format_value

	/** value → string for an env line: bools as 1/'' ; list/map as JSON; scalars as-is. */
	private static function stringify(mixed $value) : string {
		if (is_bool($value)) {
			return $value ? '1' : '';
		}
		if (is_array($value)) {
			return (string) json_encode($value); // list/map secrets — decoded back at boot by catalog type
		}
		return (string) $value;
	}//end stringify

	/**
	* Quote an env value so env_loader::parse reads it back identically:
	*  - plain tokens → unquoted;
	*  - otherwise SINGLE-quoted (literal, no escaping) when the value carries no single-quote
	*    or newline — keeps JSON readable, e.g. API_X='[{"code":"","api_ui":null}]' instead of
	*    "[{\"code\":\"\",\"api_ui\":null}]";
	*  - values containing a single-quote (or newline) → double-quoted with \ and " escaped,
	*    since a literal ' can't live inside a single-quoted value in this minimal .env subset.
	*/
	private static function quote(string $value) : string {
		return env_value::quote($value); // single source of truth (shared with the runtime installer)
	}//end quote
}
