<?php declare(strict_types=1);

require_once __DIR__ . '/class.migration_destination.php';

/**
* CONFIG_WRITER
* Renders the per-install config override file (a compiler layer override) from the 4a
* classification: each CONFIG-destination constant whose migrated LITERAL value differs
* from the catalog default, keyed by the catalog dot-path. Returns the PHP file content
* `<?php return ['dot.path' => value, ...];`. Values that equal the default, runtime
* values, and non-CONFIG destinations are omitted (the compiler already seeds defaults).
*/
final class config_writer {

	/**
	* @param array<string,array> $classification migration_classifier::classify() output
	* @param config_key[] $catalog
	*/
	public static function render(array $classification, array $catalog) : string {
		$path_of    = [];
		$default_of = [];
		foreach ($catalog as $key) {
			if ($key->const !== null) {
				$path_of[$key->const]    = $key->path;
				$default_of[$key->const] = $key->default;
			}
		}

		$overrides = [];
		foreach ($classification as $name => $info) {
			if ($info['destination'] !== migration_destination::CONFIG) {
				continue;
			}
			if (($info['record']['kind'] ?? null) !== 'literal') {
				continue; // do not bake runtime values
			}
			if (!isset($path_of[$name])) {
				continue; // CONFIG implies a catalog key; defensive
			}
			$value = $info['record']['value'];
			if ($value === ($default_of[$name] ?? null)) {
				continue; // matches the shipped default — no override needed
			}
			$overrides[$path_of[$name]] = $value;
		}

		ksort($overrides);
		return "<?php declare(strict_types=1);\n\n// Per-install config overrides — generated by the migration.\nreturn " . var_export($overrides, true) . ";\n";
	}//end render
}
