<?php declare(strict_types=1);

require_once __DIR__ . '/class.migration_destination.php';
require_once dirname(__DIR__) . '/core/base/boot/class.env_sync.php';

/**
* ENV_WRITER
* Renders the migration's two .env artifacts from the 4a classification, as content
* strings (no disk writes). render_php() → the PHP-side ../private/.env (ENV-destination
* constants with literal values; the salt verbatim). render_bun() → the Bun diffusion
* engine .env, reusing env_sync::MAP (spec Appendix B) so the name map has ONE source.
* Quoting is chosen to round-trip through env_loader::parse (verified by the test).
*/
final class env_writer {

	/** @param array<string,array> $classification migration_classifier::classify() output */
	public static function render_php(array $classification) : string {
		$lines = ['# Dédalo v7 secrets — generated by the migration. chmod 600. Never commit.'];
		foreach ($classification as $name => $info) {
			if ($info['destination'] !== migration_destination::ENV) {
				continue;
			}
			if (($info['record']['kind'] ?? null) !== 'literal') {
				continue; // a secret must have a resolved literal value
			}
			$lines[] = $name . '=' . self::quote((string) self::stringify($info['record']['value']));
		}
		return implode("\n", $lines) . "\n";
	}//end render_php

	/** @param array<string,array> $classification */
	public static function render_bun(array $classification) : string {
		$lines = ['# Dédalo diffusion (Bun) .env — generated by the migration; keys mapped via env_sync::MAP.'];
		foreach (env_sync::MAP as $php_key => $bun_key) {
			if (!isset($classification[$php_key])) {
				continue;
			}
			$record = $classification[$php_key]['record'];
			if (($record['kind'] ?? null) !== 'literal') {
				continue; // runtime/derived (e.g. DEDALO_API_URL) is computed at boot, not migration
			}
			$lines[] = $bun_key . '=' . self::quote((string) self::stringify($record['value']));
		}
		return implode("\n", $lines) . "\n";
	}//end render_bun

	/** scalar → string for an env value (bools become 1/'' ; null handled by caller skip) */
	private static function stringify(mixed $value) : string {
		if (is_bool($value)) {
			return $value ? '1' : '';
		}
		return (string) $value;
	}//end stringify

	/**
	* Quote an env value so env_loader::parse reads it back identically. Unquoted when the
	* value is "plain"; otherwise double-quoted with backslash + double-quote escaped.
	*/
	private static function quote(string $value) : string {
		if ($value !== '' && preg_match('/^[A-Za-z0-9_\/.:@+-]+$/', $value) === 1) {
			return $value;
		}
		return '"' . str_replace(['\\', '"'], ['\\\\', '\\"'], $value) . '"';
	}//end quote
}
