<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
		
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_sin_acceso\">".label::get_label('sin_acceso')."</span>";		
					break;
					
		case ($permissions>=1)	:
			
					foreach ((array)$dato as $key => $value) {
						$html_contenido .= $value;
						if ( $value!=end($dato) ) {
							$html_contenido .= "<br>";
						}
					}	
						
	}	

	
	# PRINT HTML	
	print $html_contenido;	
	
?>