<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	
	
	print "\n<!-- COMPONENT_ARRAY [tipo:$tipo section_id:$parent] $label -->";
	print "\n<div class=\"wrap_component css_wrap_component_array wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\" data-lang=\"{$lang}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-modo=\"{$modo}\"
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";
	
		
		# ETIQUETA (LABEL)
		$html_label = component_common_draw::draw_label($this);
		
		# CONTENIDO (INPUT)
		$html_contenido = '';
		switch($permissions) {
				
			case 0	:	$html_contenido .= "";
						break;
							
			case 1	: 	
						foreach ((array)$dato as $key => $value) {
							$html_contenido .= $value;
							if ( $value!=end($dato) ) {
								$html_contenido .= "<br>";
							}
						}
						break;	
							
			case ($permissions>=2) :

						$html_contenido .='<ul>';
						foreach ((array)$dato as $key => $value) {
							$html_contenido .='<li>';
							$html_contenido .= $value;
							$html_contenido .='</li>';
							#if ( $value!=end($dato) ) $html_contenido .= "<br>";
						}
						$html_contenido .='</ul>';

						/*
						$html_contenido .= "\n <input class=\"css_component_array\" type=\"text\" 
						name=\"{$input_name}\" 
						data-tipo=\"{$tipo}\" data-parent=\"{$parent}\" data-lang=\"{$lang}\" 
						value=\"{$dato}\" 
						title=\"$html_title\"
						/>";			
						*/					
		}

		# Prepare content to show in page
		tools::prepare_content($html_contenido);	
		

		# PRINT HTML
		print $html_label;
		print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_component_array COMPONENT_ARRAY [tipo:$tipo section_id:$parent] $label -->\n"; //wrap


?>