<?php

	$html  = "\n<select name=\"quality\" id=\"quality\" class=\"quality_selector css_button_generic\" onchange=\"set_and_load_media(this.value,1)\" >";
		
		if(empty($selectedItem))
		$html .= "\n <option value=\"\" >". label::get_label('calidad') ."</option>";
		
		if(is_array($ar_valid)) foreach($ar_valid as $quality) {
			
			$obj	 = new ImageObj($image_id, $quality, $aditional_path, $initial_media_path);
			$src	 = $obj->get_url();
			
			$html .= "\n <option value=\"$src\" ";
			if($selectedItem==$quality)
			$html .= " selected=\"selected\" ";				
			$html .= ">$quality";
			$html .= "</option>";				
		}
		
	$html .= "\n</select>\n";


	print $html;
?>