<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 			$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_button_reset'])) 		$ar_css['css_button_reset']='';
	if(!isset ($ar_css['css_span_debugger']))		$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_button_reset']))	$ar_css['css_wrap_button_reset']='';
		
	
	print "\n<!-- BUTTON RESET [tipo:$tipo id_matrix:$id] -->";
	print "\n<div class=\"css_wrap_button_reset {$ar_css['css_wrap_button_reset']}\">";
	
	# ETIQUETA (LABEL)
	//$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." (button_reset)</span>";
					break;					
						
		case ($permissions>=1)	:
		
					$html_contenido .= "\n <input class=\"css_button_reset {$ar_css['css_button_reset']}\" type=\"button\" onclick=\"section_list.reset_form(this.form)\" 
					data-tipo=\"{$target_tipo}\" value=\"$label\" title=\"$html_title\" />";					
											
	}
	
	
	# PRINT HTML
	print $html_contenido;
	
	# INIT COMPONENT
	#require(DEDALO_LIB_BASE_PATH . "/component_common/trigger.component_init.php");
	
	print "\n</div><!-- /css_wrap_button_reset -->\n\n"; //wrap
?>