<?php

	# VISUALIZADOR HTML	
	
	
	#print "<!-- BUTTON RESET [tipo:$tipo id_matrix:$id] -->";

	print "<div class=\"css_wrap_button_reset\">";
	
	# ETIQUETA (LABEL)
	//$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content = '';
	
	switch(true) {
			
		case $permissions===0	:	$html_content .= "<span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." (button_reset)</span>";
					break;					
						
		case ($permissions>=1)	:
		
					$html_content .= "<input class=\"css_button_reset\" type=\"button\" ";
					$html_content .= "onclick=\"search.reset_form(this.form)\" ";
					$html_content .= "data-role=\"button_reset\" ";
					$html_content .= "data-tipo=\"{$target_tipo}\" ";
					$html_content .= "value=\"$label\" title=\"$html_title\" ";
					$html_content .= "/>";					
											
	}	
	
	# PRINT HTML
	print $html_content;
	
	# INIT COMPONENT
	#require(DEDALO_LIB_BASE_PATH . "/component_common/trigger.component_init.php");
	
	print "</div>"; //wrap
?>