<?php

	# VISUALIZADOR HTML	
	
	print "<div class=\"wrap_component css_wrap_relation_related tooltip_active in_search_mode\" id=\"{$id_wrapper}\" ";
	print 'title="'.search_development2::search_options_title( $this->search_operators_info() ).'" ';
	print "data-tipo=\"{$tipo}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-hierarchy_sections='".json_encode($hierarchy_sections)."' ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-component_info='{$component_info}' ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato='".json_encode($dato)."' ";
	print "data-relation_type='{$relation_type}' ";
	print "data-search_tipos='".json_encode($search_tipos)."' ";
	print 'data-search_query_object=\''.$json_search_query_object.'\' ';
	print "data-limit=\"$limit\" ";
	print ">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch(true) {
			
		case $permissions===0	:
				$html_content .= "";
				break;
						
		
		case ($permissions>=1):

				# Q_OPERATOR
				$html_content .= '<input class="q_operator" type="text" value="'.$q_operator.'" ';
				$html_content .= "onchange=\"component_common.fix_dato(this,'{$component_name}')\" ";
				$html_content .=' />';

				#
				# AUTOCOMPLETE SERVICE
				$autocomplete_wrapper_id = 'aw_' . $identificador_unico;
				$html_content .= '<div class="autocomplete_wrapper in_search_mode" id="'.$autocomplete_wrapper_id.'"></div>';


				#
				# INIT COMPONENT
				$html_content .= '<script>';
				$init_options = new stdClass();
					$init_options->component_name 	= $component_name;
					$init_options->uid 				= $identificador_unico;
				$html_content .= "component_common.init(".json_encode($init_options).");";
				$html_content .= '</script>';


				#
				# TERMS
				$html_content .= '<ul class="css_relation_related_valor in_search_mode">';
				foreach ($ar_valor as $current_value => $value) {

					$html_content .= '<li>';

					# BTN DELETE
					$html_content .= "<div class=\"icon_bs link css_relation_related_button_delete\" ";
					$html_content .= "data-tipo=\"{$tipo}\" ";
					$html_content .= "data-current_value='$current_value' ";
					$html_content .= "data-role=\"relation_related_button_delete\" ";
					$html_content .= "title=\"$label $parent\" ";
					$html_content .= "onclick=\"component_relation_related.delete(this)\"></div>";

					# VALUE . STRING RESOLVED TO SHOW
					//$value = strip_tags($value);
					$html_content .= $value;
					if(SHOW_DEBUG===true) {
						#$html_content .= " <span class=\"notes\">$current_value</span>";
					}

					$html_content .= '</li>';
				}
				$html_content .= '</ul>';

				# INPUT DATA HIDDEN
				$html_content .= "<input type=\"text\" name=\"{$search_input_name}\" class=\"relation_related_dato_hidden\" style=\"width:300px;display: none\" ";
				$html_content .= "data-limit=\"$limit\" ";
				$html_content .= "value='{$dato_json}' ";
				$html_content .= "/>";

				

				if(SHOW_DEBUG===true) {
					$html_content .= "<span class=\"debug_info\">$search_input_name</span>";
				}
	}
	
	# Prepare content to show in page
	tools::prepare_content($html_content);
	

	# PRINT HTML
	print $html_label;
	print $html_content;	

	
	print '</div>'; //wrap
?>