<?php

	# VISUALIZADOR HTML	
	
	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in', $modo, $lang);
	
	print "<div class=\"wrap_component css_wrap_section_id css_wrap_section_id_{$modo} wrap_component_{$tipo}\" id=\"{$id_wrapper}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato=\"{$dato}\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-component_info=\"\" ";
	print ">";	
		
		# ETIQUETA (LABEL)
		$html_label = component_common_draw::draw_label($this);
		
		# CONTENIDO (INPUT)
		$html_contenido = '';		
			
		$html_contenido .= "<div class=\"css_section_id\">".$dato."</div>";
		/*
		$html_contenido .= " <input class=\"css_section_id\" type=\"text\" 
		name=\"{$input_name}\" 
		data-tipo=\"{$tipo}\"
		data-section_tipo=\"{$section_tipo}\"
		data-parent=\"{$parent}\"
		data-lang=\"{$lang}\" 
		value=\"{$dato}\" 
		title=\"$html_title\"
		/>";
		*/
		# Prepare content to show in page
		tools::prepare_content($html_contenido);		

		# PRINT HTML
		print $html_label;
		print $html_contenido;
	
	
	print "</div>"; //wrap

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out', $modo, $lang);


?>