<?php

	# VISUALIZADOR HTML	
	
	print "\n<!-- COMPONENT_SECTION_ID [tipo:$tipo section_id:$parent] $label -->";
	
	print "\n<div class=\"wrap_component css_wrap_section_id wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-modo=\"{$modo}\"
	data-dato=\"{$dato}\"
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";	
		
		# ETIQUETA (LABEL)
		$html_label = component_common_draw::draw_label($this);
		
		# CONTENIDO (INPUT)
		$html_contenido = '';		
			
		$html_contenido .= "<div class=\"css_section_id\">$dato</div>";
		/*
		$html_contenido .= "\n <input class=\"css_section_id\" type=\"text\" 
		name=\"{$input_name}\" 
		data-tipo=\"{$tipo}\"
		data-section_tipo=\"{$section_tipo}\"
		data-parent=\"{$parent}\"
		data-lang=\"{$lang}\" 
		value=\"{$dato}\" 
		title=\"$html_title\"
		/>";
		*/
		# Prepare content to show in page
		tools::prepare_content($html_contenido);		

		# PRINT HTML
		print $html_label;
		print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_section_id COMPONENT_SECTION_ID [tipo:$tipo section_id:$parent] $label -->\n"; //wrap
?>