<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 		$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_wrap_portal'])) 	$ar_css['css_wrap_portal']='';
	if(!isset ($html_tools))					$html_tools='';
	
	
	print "\n<!-- PORTAL [tipo:$tipo id_matrix:$id] $label -->";
	print "\n <div class=\"css_wrap_portal wrap_component {$ar_css['css_wrap_portal']}\" id=\"{$id_wrapper}\"
	data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-parent=\"{$parent}\" data-modo=\"{$modo}\" data-dato=\"{$valor}\" data-component_name=\"{$component_name}\" >";
	
		
		# ETIQUETA (LABEL)
		$html_label = component_common_draw::draw_label($this);
		
		# CONTENIDO (INPUT)
		$html_contenido = '';
		switch($permissions) {
				
			case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." (portal)</span>";
						break;
							
			#case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\">$valor</span>";
			#			break;	
							
			case ($permissions>=1)	:


						# HEADER ROW HTML
						#$html_contenido .= "\n<div class=\"portal_header_row \">";
						
						
							# LABEL
							#$html_contenido .= "<span>";
							#$html_contenido .=  $label ;
							#$html_contenido .= "</span>";
							
							/*
							# ID
							$html_contenido .= "<span class=\"elemento_proceso_id_header\" >";
							#$html_contenido .= $section->get_id() ;
							$html_contenido .= "</span>";
							*/

							

							
							# BUTTON NEW HTML
							if($permissions>=2)
							$html_contenido .= $button_new_html ;


							# BUTTON TOOL_PORTAL
							if($permissions>=2)
							$html_contenido .= $button_select_html ;
							/*
							$html_contenido .= "\n<div class=\"btn_new_ep css_button_generic\" 
							data-id_matrix=\"{$id}\" data-tipo=\"{$current_section_tipo}\" 
							onclick=\"component_portal.new_portal_record(this)\"
							>";
							$html_contenido .= label::get_label('nuevo').' '.$label;
							$html_contenido .= "\n</div>";
							*/					

						#$html_contenido .= "</div><!-- /portal_header_row -->";


						#
						# SECTION HTML (LIST ROWS)
						#
						$html_contenido .= "\n$section_html";
						

						break;	
												
		}

		# Prepare content to show in page
		tools::prepare_content($html_contenido);	
		

		# PRINT HTML
		if ($show_button_new) {
			print $html_label;
		}
		
		print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_portal [tipo:$tipo id_matrix:$id] $label -->\n"; //wrap


?>