<?php

	# VISUALIZADOR HTML	
	
	print "\n<!-- PORTAL [tipo:$tipo section_id_matrix:$parent] $label -->";
	print "\n <div class=\"css_wrap_portal wrap_component\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-section_tipo=\"{$section_tipo}\" data-parent=\"{$parent}\" data-modo=\"{$modo}\" data-dato=\"{$valor}\" data-component_name=\"{$component_name}\" >";
	
		
		# ETIQUETA (LABEL)
		$html_label = component_common_draw::draw_label($this);
		
		# CONTENIDO (INPUT)
		$html_contenido = '';
		switch($permissions) {
				
			case 0	:	$html_contenido .= "\n <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." (portal)</span>";
						break;
							
			case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato\">$valor</span>";
						break;	
							
			case ($permissions>=2)	:

						$html_contenido .= "\n <span class=\"css_span_dato\"> portal </span>";
						

						break;	
												
		}		
		
		print $html_contenido;
	
	
	print "\n</div><!-- /css_wrap_portal [tipo:$tipo section_id_matrix:$parent] $label -->\n"; //wrap


?>