<?php

	# VISUALIZADOR HTML	

	#$semantic_wrapper_id = $ds_key.'_'.$current_locator->section_tipo.'_'.$current_locator->section_id;
	#$ds_element 		 = isset($current_locator->ds->$ds_key) ? $current_locator->ds->$ds_key : null;

	
	$ds_html  = '';

	$ds_html .= "<div id=\"$semantic_wrapper_id\" class=\"semantic_wrapper\">";

	if (isset($semantic_node_title)) {
		$ds_html .= "<span class=\"semantic_node_title\">$semantic_node_title</span>";
	}

	$ds_html .= "<div class=\"icon_bs link new_semantic_node\" onclick=\"tool_semantic_nodes.open_ts_window(this)\" ";
	$ds_html .= "data-portal_locator_section_tipo=\"{$current_locator->section_tipo}\" ";
	$ds_html .= "data-portal_locator_section_id=\"{$current_locator->section_id}\" ";
	$ds_html .= "data-ds_key=\"{$ds_key}\" ";
	$ds_html .= "data-semantic_wrapper_id=\"{$semantic_wrapper_id}\" ";
	$ds_html .= "data-component_name=\"tool_semantic_nodes\" ";
	$ds_html .= "data-hierarchy_types='[\"4\"]' ";
	$ds_html .= "data-hierarchy_sections=\"\" ";
	$ds_html .= "></div>";
	/*
		$ds_html .= "<div class=\"button_add relation_related_add_from_tree_button\"
			data-id_wrapper=\"$semantic_wrapper_id\"
			data-component_name=\"tool_semantic_nodes\"
			data-hierarchy_types='[\"4\"]'
			data-hierarchy_sections=\"\"
			onclick=\"component_common.open_ts_window(this)\"></div>";
	*/
	if (!empty($ds_element)) {
		#dump($current_locator->ds, '$current_locator->ds ++ '.to_string());
		#dump($ds_element, ' ds_element ++ '.to_string());		
			
		$ds_html .= "<ul class=\"ul_semantic_node\">";

		foreach ((array)$ds_element as $locator_ds) {
			#dump($locator_ds, ' locator_ds ++ '.to_string());

			$term = ts_object::get_term_by_locator( $locator_ds, $lang=DEDALO_DATA_LANG, $from_cache=true );
			$locator_ds_json = json_encode($locator_ds);

			$ds_html .= "<li>";

			$ds_html .= "<div class=\"icon_bs link delete_semantic_node\" onclick=\"tool_semantic_nodes.remove_index(this,event)\" ";
			$ds_html .= "data-portal_locator_section_tipo=\"{$current_locator->section_tipo}\" ";
			$ds_html .= "data-portal_locator_section_id=\"{$current_locator->section_id}\" ";
			$ds_html .= "data-ds_key=\"{$ds_key}\" ";
			$ds_html .= "data-locator_ds='{$locator_ds_json}' ";
			$ds_html .= "data-semantic_wrapper_id=\"{$semantic_wrapper_id}\" ";
			$ds_html .= "></div>";

			$ds_html .= "<span>";
			$ds_html .= $term;
			if(SHOW_DEBUG) {
				$ds_html .= ' [' . $locator_ds->section_tipo.'_'.$locator_ds->section_id . ']';
			}
			$ds_html .= "</span>";

			$ds_html .= "</li>";
		}

		$ds_html .= "</ul>";
	}

	$ds_html .= "</div>"; //end semantic_wrapper


	echo $ds_html;

?>