<?php

	# VISUALIZADOR HTML	
	
	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in');	
		
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= ''; 		
					break;
					
		case ($permissions>=1)	:
			
					$html_contenido .= "\n <span class=\"css_span_dato\" 
					data-tipo=\"{$tipo}\" data-section_tipo=\"{$section_tipo}\" data-parent=\"{$parent}\" data-lang=\"{$lang}\" 
					>$valor <span class=\"debug_info\">[$userID]<span></span>";
					
					if(SHOW_DEBUG) {
						#$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\">{$debugger}</span>";		
					}							
							
	}	

	
	# PRINT HTML	
	print $html_contenido;
	

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out');
?>