<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 		$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_span_debugger']))	$ar_css['css_span_debugger']='';
	
	echo "\n<!-- COMPONENT_USER [tipo:$tipo section_id_matrix:$parent] -->";	
		
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= ''; 		
					break;
					
		case ($permissions>=1)	:
			
					$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\" 
					data-tipo=\"{$tipo}\" data-section_tipo=\"{$section_tipo}\" data-parent=\"{$parent}\" data-lang=\"{$lang}\" 
					>$valor <span class=\"debug_info\">[$userID]<span></span>";
					
			if($permissions==3)
					
					$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
							
	}	

	
	# PRINT HTML	
	print $html_contenido;	
	
?>