<?php


$html  = '';
$html .= "<div class=\"wrapper_preview\">";
#echo css::build_tag(DEDALO_ROOT_WEB.'/lib/bootstrap/3.1.1/css/bootstrap.min.css');

#dump($section_tipo," section_tipo in preview");


#
# ORDER AND GROUP BY NUMBER (numero_inventario)
# Iterate images array
# Las agrupamos por número
$ar_image_valid_group=array();

# Order by nombre_fichero
/*
usort($all_av_files, function($a, $b) {
	$key 	= 'nombre_fichero';

	$a_key 	= strtolower($a[$key]);
	$b_key 	= strtolower($b[$key]);

	if (strpos($a_key, '-')===false) { 
		$a_key = preg_replace("/([0-9]*).(jpg)/", "$1-.$2", $a_key);
	}
	if (strpos($b_key, '-')===false) { 
		$b_key = preg_replace("/([0-9]*).(jpg)/", "$1-.$2", $b_key);
	}
    return strnatcmp($a_key, $b_key);
});
*/
#dump($all_av_files,'$all_av_files');#die();
	#dump(IMPORT_VERIFY_FILE_NAME, 'IMPORT_VERIFY_FILE_NAME');



#
# PREVIEW
# Formulario html que previsualiza el contenido a importar
$ar_image_valid_group = $all_av_files;
$html .= "<form class=\"form_preview\" action=\"\" method=\"post\">";

foreach ($ar_image_valid_group as $key => $ar_data) {
	#dump($ar_group_value, ' ar_group_value'); continue;


	# VERIFY_FILE_NAME
	if ( isset($this->button_import_propiedades->verify_file_name) && $this->button_import_propiedades->verify_file_name===true ) {
		if( !verify_file_name($ar_data['nombre_fichero_completo']) ) {
			continue;
		}
	}

	if(SHOW_DEBUG) {
		$start_time = microtime(true);	
	}

	# TABLA PREVIEW DE LA IMAGEN CON SUS DATOS
	#foreach ($ar_group_value as $key => $ar_data) {

		$rowspan = count($ar_data)+0;
		$html .= "<table class=\"table_preview\">";

		# CAPTION		
		if( isset($ar_data['nombre_fichero']) ) {

			$html .= "<caption class=\"tab_title\" data-tab_id=\"".$ar_data['nombre_fichero']."\">";
			$html .= $ar_data['nombre_fichero'];
			$html .="</caption>";
		}

		$html .= "<tbody class=\"tab_content\">";

			$html .= "<tr>";
			$html .= "<td class=\"td_title\">";
			$html .= "Import";
			if(SHOW_DEBUG) {
				$html .= " [$key]";
			}
			$html .= "</td>";
			$html .= "<td>";
			if (isset($this->button_import_propiedades->enable_selector) && $this->button_import_propiedades->enable_selector===false) {
				# hide selector checkboxes
			}else{
				$html .= "<input type=\"checkbox\" name=\"import_image_checkbox[]\" value=\"$key\" checked=\"yes\">";
			}			
			$html .= "</td>";
			$html .= "</tr>";

		foreach ($ar_data as $key => $value) {

			if(SHOW_DEBUG) {
				$partial_time = microtime(true);	
			}

			# Skip sensible info for no admins
			if( strpos($key, 'path')!==false && SHOW_DEBUG!==true ) continue;

			$html .= "<tr>";

			# COLUMN 1
			$html .= "<td class=\"td_title\">";
			if (SHOW_DEBUG) {
				$html .= label::get_label($key) . ' <span class="debug_info">['.$key.']</span>';
			}else{
				$html .= label::get_label($key);
			}					
			$html .= "</td>";

			# COLUMN 2
			$html .= "<td class=\"td_content\">";
				switch ($key) {
					case 'imagen':
						if ( strtolower( pathinfo($value['image_url'],PATHINFO_EXTENSION) )=='pdf' ) {
							$html .= "<div class=\"image_source\">pdf file</div>";
							break;	
						}		
						foreach ($value as $image_key => $image_value) {
							switch ($image_key) {
								case 'image_url':
									$img_url = $image_value;
									$html .= "<div class=\"image_source\">";
									$html .= " <div class=\"image_source_title\">".label::get_label('original')."</div>";
									$html .= " <a href=\"$img_url\" target=\"_blank\">";
									if( intval(filesize($ar_data['file_path'])/1024/1024,3) >4 ) {
										$html .= "Original is too big image to show (>4 MB)";
									}else{
										$html .= " <img src=\"".$img_url."\"/>";
									}
									$html .= " </a>";
									$html .= "</div>";#/image_source;
									break;
								case 'image_preview_url':
									$img_url = $image_value;
									$html .= "<div class=\"image_source\">";
									$html .= " <div class=\"image_source_title\">".label::get_label('preview')."</div>";
									$html .= " <a href=\"$img_url\" target=\"_blank\"><img src=\"".$img_url."\"/></a>";
									$html .= "</div>";#/image_source;
									break;							
								default:
									# code...
							}							
						}						
						break;
					case 'nombre_fichero':
					case 'nombre_fichero_completo':
						$html .= $value ."  <span class=\"debug_info\">(nombre seguro: ".ltrim($value,'0').")</span>";
						break;
					
					default:
						$html .= $value;
				}
			$html .= "</td>";

			$html .= "</tr>";
		}#end foreach ($ar_data as $key => $value)


		if(SHOW_DEBUG) {
			#$total=round(microtime(true)-$partial_time,4);
			#error_log("Partial time $total - ".$ar_data['numero_recurso']);
		}

		$html .= "</tbody>";
		$html .= "</table>";

	#}#end foreach ($ar_group_value as $key => $ar_data)

	if(SHOW_DEBUG) {
		#$total=round(microtime(true)-$start_time,4);
		#error_log("- Total time $total ");
	}	
}

if(empty($ar_image_valid_group)) {
	$html .= "<div class=\"info_line alert_icon\">Seleccione al menos un fichero en el apartado 'Gestión de archivos'</div>";			
}else{

	#$html .= "<form class=\"form_preview\" action=\"\" method=\"post\">";

	$html .= "<div class=\"form_spacer\"></div><hr>";

	$html .= "  <input type=\"hidden\" name=\"process\" value=\"1\">  ";	

		#
		# SELECT QUALITY
		$html .= "<span>". label::get_label('directorio_de_destino')."</span>: ";
		$html .= "<select name=\"quality\" class=\"quality_selector\">";
		foreach ($ar_quality as $current_quality) {
			if ($current_quality=='modificada') {
				continue;
			}
			if($current_quality == $default_target_quality) {
				$html .= "<option selected=\"selected\" >$current_quality</option>";
			}else{
				$html .= "<option>$current_quality</option>";
			}		
		}
		$html .= "</select>";
		if(!in_array($default_target_quality, $ar_quality)) {
			$html .= "<div class=\"warning\"> Sorry: Current target quality ($default_target_quality) not valid</div>";
		}


		#
		# ADITIONAL CUSTOM FORM ELEMENTS (From specific script like mupreva)
		$html .= get_aditional_form_elements();		


		#
		# DELETE IMAGES AFTER IMPORT OPTION
		if(SHOW_DEBUG) {
			$html .= "<span></span>";
			$html .= label::get_label('eliminar_imagenes_tras_la_importacion').": ";
			$html .= "<select name=\"delete_after\" class=\"quality_selector\" >";
			if(SHOW_DEBUG) {
				$html .= " <option value=\"si\">".label::get_label('si')."</option>";
				$html .= " <option value=\"no\"  selected=\"selected\" >".label::get_label('no')."</option>";
			}else{
				$html .= " <option value=\"si\" selected=\"selected\" >".label::get_label('si')."</option>";
				$html .= " <option value=\"no\" >".label::get_label('no')."</option>";
			}			
			$html .= "</select>";
		}else{
			$html .= "  <input type=\"hidden\" name=\"delete_after\" value=\"si\">";
		}

		$html .= "<div class=\"form_line2\">";

			#
			# TARGET ID
			if (isset($this->button_import_propiedades->enable_target_id) && $this->button_import_propiedades->enable_target_id===false) {
				# hide target id option
				$html .= "<input type=\"hidden\" name=\"target_id\" id=\"target_id\" value=\"1\">";
			}else{
				$html .= " $custom_tool_label ID <input type=\"text\" name=\"target_id\" id=\"target_id\" value=\"\">";
			}	
			

			#
			# PROCESS BUTTON
			$html .= "<input type=\"submit\" class=\"css_button_generic submit_import\" value=\" PROCESAR \" onclick=\"return tool_import_av.process_files(this)\">";

		$html .= "</div>";
	
}#/if(empty($ar_image_valid_group)) {
$html .= "</fom>";


$html .= "</div>";#end wrapper_preview

print $html;
/*
if($_POST)
$html .= dump($_POST);

echo html_page::get_html($html);
exit();
*/
?>