<?php

	# VISUALIZADOR HTML	


	# PLAYER
	$html_contenido = '';

	$html_contenido .= "<div class=\"css_player_wrap\">";


	# POSTERFRAME ONLY
	#$html_contenido .= "\n <img class=\"av_posterframe_only\" src=\"$posterframe_url\" width=\"$video_width\" height=\"$video_height\" alt=\"Posterframe\" title=\"\" />";

	
	# VIDEO HTML5 OBJ	

		$html_contenido .= "<video class=\"css_av_video\" ";
		$html_contenido .= "preload=\"none\" ";
		$html_contenido .= "controls=\"controls\" ";
		$html_contenido .= "poster=\"$posterframe_url\" ";
		$html_contenido .= "onerror=\"component_av.failed(event)\" ";
		$html_contenido .= "id=\"{$player_id}\" ";
		$html_contenido .= "data-tipo=\"{$tipo}\" ";
		$html_contenido .= "data-section_tipo=\"{$section_tipo}\" ";
		$html_contenido .= "data-parent=\"{$parent}\" ";
		$html_contenido .= "data-video_id=\"{$video_id}\" ";	
		$html_contenido .= ">";

			$html_contenido .= "<source id=\"video_mp4_{$tipo}\" src=\"$video_url\" type=\"video/mp4\" onerror=\"alert('Sorry. Unplayable media')\">";
			
			# FALLBACK IMG (no html5 codec video support)
			$html_contenido .= "<img src=\"$posterframe_url\" alt=\"Posterframe\" title=\"No video playback capabilities\"/>";

		$html_contenido .= "</video>";
	
	
	
		
	
	/*
	# CONTROLS
	$html_contenido .= "\n<div class=\"css_av_video_controls\">";

		# BUTTON GOTO BEGIN
		$html_contenido .= "\n<div class=\"css_button_generic css_av_video_controls_inicio av_player_btn\" onclick=\"component_av.goto_time(this,0)\">Inicio</div>";
		
		# BUTTON PLAY / PAUSE
		$html_contenido .= "\n<div class=\"css_button_generic css_av_video_controls_play_pause av_player_btn\">Play</div>";

		# TC DISPLAY
		$html_contenido .= "\n<div class=\"tc_display\">00:00:00</div>";

		# BUTTONS REWIND / FORDWARD
		$html_contenido .= "\n<div class=\"css_button_generic css_av_video_controls_rew av_player_btn\" onclick=\"component_av.controlVideo(this,'-10')\"><10</div>";
		$html_contenido .= "\n<div class=\"css_button_generic css_av_video_controls_rew av_player_btn\" onclick=\"component_av.controlVideo(this,'-5')\">< 5</div>";
		$html_contenido .= "\n<div class=\"css_button_generic css_av_video_controls_forw av_player_btn\" onclick=\"component_av.controlVideo(this,'5')\">5 ></div>";
		$html_contenido .= "\n<div class=\"css_button_generic css_av_video_controls_forw av_player_btn\" onclick=\"component_av.controlVideo(this,'10')\">10 ></div>";

		# QUALITY SELECTOR
		$html_contenido .= "\n<div class=\"quality_selector\"> quality_selector here </div>";

	$html_contenido .= "\n</div><!-- /css_av_video_controls -->";
	*/


	$html_contenido .= "</div><!-- /css_player_wrap -->";

	# PRINT HTML
	print $html_contenido;

?>