<?php

	# VISUALIZADOR HTML	


	# PLAYER
	$html_contenido = '';

	$html_contenido .= "<div class=\"css_posterframe_wrap\">";


		# POSTERFRAME 
		$html_contenido .= "<img class=\"av_posterframe\" ";
		$html_contenido .= "data-video_id=\"$video_id\" ";
		$html_contenido .= "src=\"$posterframe_url\" ";	
		$html_contenido .= "/>";


		/*
		# CONTROLS
		$html_contenido .= "\n<div class=\"css_av_posterframe_controls\">";
						# BUTTON NEW
			$html_contenido .= "\n<div class=\"css_button_generic link css_av_posterframe_controls_new\"
			data-video_id=\"$video_id\" data-quality=\"$quality\" data-tipo=\"$tipo\"
			onclick=\"component_av.open_media_window(this,'posterframe')\"
			>New posterframe</div>";


			# BUTTON DELETE POSTERFRAME
			$html_contenido .= "<div class=\"av_icon link av_delete_icon av_delete_posterframe_icon\"
			data-video_id=\"$video_id\" data-quality=\"$quality\"
			onclick=\"component_av.delete_posterframe(this)\"
			></div>";
			

		$html_contenido .= "\n</div><!-- /css_av_posterframe_controls -->";
		*/


	$html_contenido .= "</div><!-- /css_posterframe_wrap -->";

	# PRINT HTML
	print $html_contenido;

?>