<?php

	# VISUALIZADOR HTML		

	$html    = "<!-- TOOL PAGE [tipo:$tipo] -->";	
	$html   .= "<div class=\"wrap_tool wrap_tool_av_versions_page\">";
	$html   .= $header_html;
	$html   .= "<div class=\"content_data text_shadow_inset\" >";


		$html   .= "<script>";
		$html   .= "page_globals.video_base_path='$video_base_path';";
		$html   .= "page_globals.video_extension='$video_extension';";
		$html   .= "</script>";

		


		# PLAYER
		$html .= $player_html;


		# VERSIONS
		$html .= "<table class=\"table_versions\">";
	    	 

	    	#
			# QUALITY ROW
		    $html .= "<tr>";
		    $html .= "<th>". label::get_label('calidad'). "</th>" ;
		    foreach ($ar_all_files_by_quality as $quality => $file_path) {
		    	$td_style = null; if($quality==DEDALO_AV_QUALITY_DEFAULT) $td_style = 'td_default_quality';
		    	$html .= "<th class=\"$td_style\">";
		    	$html .= $quality;
		    	if ($quality==DEDALO_AV_QUALITY_DEFAULT) {
		    		$html .= " <span class=\"av_info\">[Default]</span>";
		    	}
		    	$html .= "</th>";
		    }
		    $html .= "</tr>";
			
		    

		    #
	      	# FILE ROW (ICON VIDEO)
		    $html .= "<tr>";
		    $html .= "<td>". label::get_label('fichero')."</td>" ;
		    foreach ($ar_all_files_by_quality as $quality => $file_path) {

		    	$td_style = null; if($quality==DEDALO_AV_QUALITY_DEFAULT) $td_style = 'td_default_quality';
		    	$html .= "<td class=\"$td_style\">";

		    	$title = '';
		    	if(SHOW_DEBUG) {
		    		$title .= $this->component_obj->get_video_path($quality);
		    		#dump($this->component_obj->get_video_path($quality), '$this->component_obj->get_video_path($quality)');
		    	}
		    	$style = '';
	    		if( !file_exists($this->component_obj->get_video_path($quality)) ) {
	    			$style = "display:none";
	    		}
		    	$html .= "<div class=\"icon_bs link av_video_icon\" style=\"$style\" ";
		    	$html .= "data-video_id=\"$video_id\" ";
		    	$html .= "data-quality=\"$quality\" ";
		    	$html .= "data-parent=\"$parent\" ";
		    	$html .= "data-section_tipo=\"$section_tipo\" ";
		    	$html .= "data-tipo=\"$tipo\" ";
		    	$html .= "onclick=\"tool_av_versions.change_media_quality(this)\" ";
		    	$html .= "title=\"$title\" ";
		    	$html .= "></div>";
		    	# Unplayable msg
		    	$file_ext = pathinfo($file_path, PATHINFO_EXTENSION);
		    	if (!empty($file_ext) && $file_ext!=DEDALO_AV_EXTENSION) {
		    	 	$html .= "<span class=\"notas\">unplayable [$file_ext]</span>";
		    	}

		    	if (is_dir($file_path)) {
		    	 	$html .= "<span class=\"notas\">unplayable [DVD]</span>";
		    	}	
		    	$html .= "</td>";
		    }
		    $html .= "</tr>";
			

		    
		    #
		    # SIZE ROW
		    $html .= "<tr>";
		    $html .= "<td>". label::get_label('tamano')."</td>" ;
		    foreach ($ar_all_files_by_quality as $quality => $file_path) {
		    	$td_style = null; if($quality==DEDALO_AV_QUALITY_DEFAULT) $td_style = 'td_default_quality';
		    	$html .= "<td class=\"$td_style\">";

		    	$style = '';
	    		if( !$file_path ) {
	    			$style = "display:none";
	    		}else{
					$html .= "<div class=\"av_size_info\" style=\"$style\" ";
			    	$html .= "data-quality=\"$quality\" ";
			    	$html .= "data-parent=\"$parent\" ";
			    	$html .= "data-section_tipo=\"$section_tipo\" ";
			    	$html .= "data-tipo=\"$tipo\" ";
			    	$html .= ">";			    	
			    	$html .= $this->component_obj->get_video_size($quality, $file_path);				    	
			    	$html .= "</div>";	#dump($this->component_obj->get_video_size($quality), $this->component_obj->get_video_path($quality));
	    		}				
		    		    	
		    	$html .= "</td>";
		    }
		    $html .= "</tr>";
			

		    
			#
			# UPLOAD ROW
			if ($permissions>=2) {

				$html .= "<tr>";
				$html .= "<td>". label::get_label('subir')."</td>" ;
				foreach ($ar_all_files_by_quality as $quality => $file_path) {
					$td_style = null; if($quality==DEDALO_AV_QUALITY_DEFAULT) $td_style = 'td_default_quality';
		    	$html .= "<td class=\"$td_style\">";

					$html .= "<div class=\"icon_bs link tool_upload_icon\" ";
				 	$html .= "data-video_id=\"$video_id\" ";
				 	$html .= "data-quality=\"$quality\" ";
				 	$html .= "data-parent=\"$parent\" ";
				 	$html .= "data-section_tipo=\"$section_tipo\" ";
				 	$html .= "data-tipo=\"$tipo\" ";
					$html .= "onclick=\"tool_common.open_tool_upload(this)\" ";
					$html .= "></div>";
					$html .= "</td>";
				}
				$html .= "</tr>";
		    }
			
		    

		    #
		    # DOWNLOAD ROW
		    if ($permissions>=2) {

			    $html .= "<tr>";
			    $html .= "<td>". label::get_label('descargar')."</td>";
			    
			    foreach ($ar_all_files_by_quality as $quality => $file_path) {
			    	$td_style = null; if($quality==DEDALO_AV_QUALITY_DEFAULT) $td_style = 'td_default_quality';
		    		$html .= "<td class=\"$td_style\">";

			    	$style = '';
		    		if( $this->component_obj->get_original_file_path($quality)==false ) {
		    			$style = "display:none";
		    		}
			    	$html .= "<div class=\"icon_bs link av_download_icon\" style=\"$style\" ";
			    	$html .= "data-video_id=\"$video_id\" ";
			    	$html .= "data-quality=\"$quality\" ";
			    	$html .= "data-parent=\"$parent\" ";
			    	$html .= "data-section_tipo=\"$section_tipo\" ";
			    	$html .= "data-tipo=\"$tipo\" ";
			    	$html .= "onclick=\"tool_av_versions.download_file(this)\" ";
			    	$html .= "></div>";
			    	    	
			    	$html .= "</td>";
			    }
			    $html .= "</tr>";
			}
			

			
			#
		    # DELETE ROW
		    if ($permissions>=2) {

			    $html .= "<tr>";
			    $html .= "<td>". label::get_label('borrar')."</td>" ;
			    foreach ($ar_all_files_by_quality as $quality => $file_path) {
			    	$td_style = null; if($quality==DEDALO_AV_QUALITY_DEFAULT) $td_style = 'td_default_quality';
		    	$html .= "<td class=\"$td_style\">";
			    	
			    	$style = '';
		    		if( $this->component_obj->get_original_file_path($quality)==false ) {
		    			$style = "display:none";
		    		}
			    	$html .= "<div class=\"icon_bs link av_delete_icon\" style=\"$style\" ";
			    	$html .= "data-video_id=\"$video_id\" ";
			    	$html .= "data-quality=\"$quality\" ";
			    	$html .= "data-parent=\"$parent\" ";
			    	$html .= "data-section_tipo=\"$section_tipo\" ";
			    	$html .= "data-tipo=\"$tipo\" ";
			    	$html .= "data-file_path=\"$file_path\" ";
			    	$html .= "onclick=\"tool_av_versions.delete_version(this)\" ";
			    	$html .= "></div>";
			    	    	
			    	$html .= "</td>";
			    }
			    $html .= "</tr>";
			}
			
			

			#
		    # GENERATE ROW
		    if ( $permissions>=2 && strlen(DEDALO_AV_FFMPEG_PATH)>4 ) {

			    $html .= "<tr>";
			    $html .= "<td>". label::get_label('generar') .' '.label::get_label('version'). "</td>" ;
			    foreach ($ar_all_files_by_quality as $quality => $file_path) {
			    	
			    	$td_style = null; if($quality==DEDALO_AV_QUALITY_DEFAULT) $td_style = 'td_default_quality';
		    		
		    		$html .= "<td class=\"$td_style\">";
			    	$tmp_file		 		= DEDALO_MEDIA_BASE_PATH . DEDALO_AV_FOLDER . '/tmp/'.$quality.'_'.$video_id.'.sh';
			    	$source_quality_file 	= $file_path;	//$this->component_obj->get_video_path($quality);

			    	if( file_exists($tmp_file) ) {	//&& !file_exists($source_quality_file)
			    		$html .= "<small class=\"blink\">Processing..</small>";
			    	//}else if ( !file_exists($source_quality_file) ) {
			    	}else {
			    		   		
						$source_quality = $this->component_obj->get_source_quality_to_build($quality);
							#dump($source_quality,'$source_quality for quality '.$quality);
						$style = '';
						if( empty($source_quality) ) {
							$style = "display:none";
						}
						$html .= "<div class=\"icon_bs link av_generate_icon\" style=\"$style\" ";
						$html .= "data-video_id=\"$video_id\" ";
						$html .= "data-quality=\"$quality\" ";
						$html .= "data-source_quality=\"$source_quality\" ";
						$html .= "data-target_quality=\"$quality\" ";
						$html .= "data-parent=\"$parent\" ";
						$html .= "data-section_tipo=\"$section_tipo\" ";
						$html .= "data-tipo=\"$tipo\" ";						
						$html .= "onclick=\"tool_av_versions.generate_version(this)\" ";
						$html .= "title=\"$source_quality\" ";
						$html .= "></div>";
					}
					$html .= "</td>";

				}//end foreach ($ar_all_files_by_quality as $quality => $file_path) {
			    $html .= "</tr>";
			}



			#
		    # CONFORM HEADER
		    if ( $permissions>=2 && strlen(DEDALO_AV_FFMPEG_PATH)>4 ) {

			    $html .= "<tr>";
			    $html .= "<td>". label::get_label('conformar_cabeceras'). "</td>" ;
			    foreach ($ar_all_files_by_quality as $quality => $file_path) {
			    	
			    	$td_style = null; if($quality==DEDALO_AV_QUALITY_DEFAULT) $td_style = 'td_default_quality';
		    		
		    		$html .= "<td class=\"$td_style\">";			    	
			    	$source_quality_file = $file_path;	//$this->component_obj->get_video_path($quality);	
			    			    	
			    		if ($quality!=DEDALO_AV_QUALITY_ORIGINAL && $file_path && file_exists($source_quality_file)) {

			    			$source_quality = $this->component_obj->get_source_quality_to_build($quality);						
							
							$style = '';							
							$html .= "<div class=\"icon_bs link av_generate_icon\" style=\"$style\" ";
							$html .= "data-video_id=\"$video_id\" ";
							$html .= "data-quality=\"$quality\" ";						
							$html .= "data-parent=\"$parent\" ";
							$html .= "data-section_tipo=\"$section_tipo\" ";
							$html .= "data-tipo=\"$tipo\" ";					
							$html .= "onclick=\"tool_av_versions.conform_header(this)\" ";
							$html .= "title=\"$source_quality\" ";
							$html .= "></div>";
						}//end if (file_exists($source_quality_file)) {
					
					$html .= "</td>";

				}//end foreach ($ar_all_files_by_quality as $quality => $file_path) {
			    $html .= "</tr>";
			}
			


		$html .= "</table><!-- /table_versions -->";


	
	$html .= "</div><!-- /content_data -->";
	$html .= "</div><!-- /wrap_tool -->"; //wrap_tool

	
	# INSPECTOR LOG TOOL
	$html .= "<div id=\"inspector_log\" class=\"tool_transcription_inspector_log\"> </div>";

	print $html;
		
?>