<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 			$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_radio_button'])) 		$ar_css['css_radio_button']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 		$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))		$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_radio_button']))	$ar_css['css_wrap_radio_button']='';
	if(!isset ($ar_css['css_radio_button_rotulo']))	$ar_css['css_radio_button_rotulo']='';
	
	if(!isset ($tools_html))						$tools_html='';
	if(isset($_REQUEST[$tipo]))						$dato = $_REQUEST[$tipo];		#var_dump($_REQUEST[$tipo]);
	
	
	print "\n<!-- RADIO BUTTON [tipo:$tipo id_matrix:$id] $label -->";
	print "\n<div class=\"css_wrap_radio_button {$ar_css['css_wrap_radio_button']}\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	# CAMPO OBLIGATORIO
	$required_code 	= NULL;
	if($required)	$required_code = 'style="font-weight:bold"';
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> No access here (radio_button)! </span>";
					break;
						
		case 1	: 	if (is_array ($ar_list_of_values)) foreach ($ar_list_of_values as $value => $rotulo) {
						
						if( $value == $dato ) {
							$checked = 'checked="checked"';
						}else {
							$checked = "";
						}
						$html_contenido .= "\n <input class=\"css_radio_button {$ar_css['css_radio_button']}\" type=\"radio\" name=\"{$tipo}\" 
						data-tipo=\"{$tipo}\" value=\"{$value}\" title=\"$html_title\" $checked disabled />";
						$html_contenido .= "\n <label class=\"css_radio_button_rotulo {$ar_css['css_radio_button_rotulo']}\"
						$required_code >$rotulo</label>";	
					}
					break;	
						
		
		case ($permissions>=2)	:
		
					if (is_array ($ar_list_of_values)) foreach ($ar_list_of_values as $value => $rotulo) {
						
						if( $value == $dato ) {
							$checked = 'checked="checked"';
						}else {
							$checked = "";
						}
						$html_contenido .= "\n <input class=\"css_radio_button {$ar_css['css_radio_button']}\" type=\"radio\" name=\"{$tipo}\" data-tipo=\"{$tipo}\" value=\"{$value}\" title=\"$html_title\" $checked />";
						$html_contenido .= "\n <label class=\"css_radio_button_rotulo {$ar_css['css_radio_button_rotulo']}\" $required_code >$rotulo</label>";
						
					}										
							
	}	
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	print "\n</div>\n\n"; //wrap
?>