<?php
/**
* TOOL_EXPORT PAGE
*/

$html='';

	
	#
	# WRAP_TOOL_EXPORT
	$html .= "<div id=\"wrap_columns_selector\" class=\"no-print\">";	
		
		

		#
		# COL1
		$html .= "<div id=\"col1\" class=\"col\">";

			#
			# SOURCE LIST
			$html .= "<div class=\"list_title\">".label::get_label('elementos_desactivos')."</div>";
			$html .= "<ul id=\"source_list\" class=\"connectedSortable\">";			
			foreach ($source_list as $tipo => $name) {
				$html .= "<li data-tipo=\"$tipo\">";
				$html .= $name;
				if(SHOW_DEVELOPER===true) {
					$html .= ' <span class="small">';
					$html .= "[$tipo]";
					$html .= ' '.RecordObj_dd::get_modelo_name_by_tipo($tipo,true);
					$html .= '</span>';
				}
				$html .= "</li>";
			}
			$html .= "</ul>";

		$html .= "</div>";//end col1


		#
		# COL2
		$html .= "<div id=\"col2\" class=\"col\"></div>";


		#
		# COL3
		$html .= "<div id=\"col3\" class=\"col\">";

			#
			# TARGET LIST
			$html .= "<div class=\"list_title\">".label::get_label('elementos_activos')."</div>";
			$html .= "<ul id=\"target_list\" class=\"connectedSortable\" data-section_tipo=\"$section_tipo\">";			
			foreach ($target_list as $tipo => $name) {
				$html .= "<li data-tipo=\"$tipo\" class=\"ui-icon ui-icon-arrow-4\" >";
				$html .= $name;
				if(SHOW_DEVELOPER===true) {
					$html .= " [$tipo]";
				}
				$html .= "</li>";
			}
			$html .= "</ul>";

		$html .= "</div>";//end col3


		#
		# COL4
		$html .= "<div id=\"col4\" class=\"col\">";

			#
			# INFO
			$html .= "<div id=\"records_info\">";
			$html .= " <h1>Section: <strong>$section_label</strong></h1><span> ".label::get_label('total_records').": <strong>$total_records</strong> </span>"; 
			$html .= "</div>";


			$html .= "<div id=\"buttons_div\">";
				
				/*
				#
				# SELECT ENCODING
				$html .= '<div class="input-group">';
				$html .= '<span class="input-group-addon" id="basic-addon1">Encoding</span>';
				
				$html .= '</div>';

				#
				# SELECT FORMAT
				$html .= '<div class="input-group">';
				$html .= '<span class="input-group-addon" id="basic-addon1">Format</span>';
				
				$html .= '</div>';
				*/

				#
				# BUTTON EXPORT
				$html .= '<div class="input-group">';
				$html .= "<a id=\"button_export\" class=\"btn btn-success fileinput-button\" onclick=\"tool_export.export_data(this);\">
							<strong>".label::get_label('tool_export')."</strong>
						 </a>";
				/*
				$html .= '<span class="input-label">Encoding</span>';	 
				$html .= "<select id=\"select_encoding_export\" class=\"form-control\">
							<option value=\"UTF8\">UTF8</option>
							<option value=\"ISO-8859-1\">ISO-8859-1 (Excel)</option>
						 </select>";
				*/
				$html .= '<span class="input-label">Format</span>';
				$html .= "<select id=\"select_data_format_export\" class=\"form-control\">
							<option value=\"standar\">Standar (Resolved)</option>
							<option value=\"dedalo\">Dédalo (Raw)</option>
						 </select>";


				$html .= '<a id="active_all_columns" class="move_columns" onclick="tool_export.active_all_columns(this);">Active all columns</a>';
				$html .= '<a id="unactive_all_columns" class="move_columns" onclick="tool_export.unactive_all_columns(this);">Unactive all columns</a>';

				$html .= '</div>';		 

			$html .= "</div>";//end buttons_div
			

		$html .= "</div>";//end col4



	$html .= "</div>";//end wrap_columns_selector


	#
	# DOWNLOAD_FILE
	$html .= "<div id=\"download_file\" class=\"no-print\">";
	# DOWNLOAD_FILE CSV UTF-8
	#$html .= "	<h2><a href=\"\" target=\"_blank\" id=\"download_file_link\">".label::get_label("descargar")." CSV</a></h2>";
	$html .= '<a id="download_file_link" class="btn btn-success fileinput-button"><strong>'.label::get_label("descargar").' CSV</strong></a>';

	# DOWNLOAD_FILE_EXCEL
	#$html .= "<h2><a href=\"\" target=\"_blank\" id=\"download_file_link_excel\">".label::get_label("descargar")." Excel</a></h2>";
	$html .= '<a id="download_file_link_excel" class="btn btn-success fileinput-button"><strong>'.label::get_label("descargar").' Excel</strong></a>';

	// print
		$html .= '<a id="print_button" class="btn btn-success fileinput-button" onclick="window.print()"><strong>'.label::get_label("imprimir").'</strong></a>';
	
	$html .= "</div>";



	#
	# TABLE_DATA_PREVIEW
	$html .= "<div id=\"table_data_preview\"></div>";

	
	

echo $html;
?>
<script>  
  tool_export.init();
</script>