<?php
/*
# HEADERS FOR ALLOW CACHE THIS PAGE 
header("Cache-Control: private, max-age=10800, pre-check=10800");
header("Pragma: private");
header("Expires: " . date(DATE_RFC822,strtotime(" 120 day")));
header('Content-Type: text/html');
*/
#header("Access-Control-Allow-Origin: *");
?>
<!DOCTYPE html>
<?php /*<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">*/ ?>
<html lang="<?php echo $lang_tld2 ?>">
<head>
<?php /*<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />*/?>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?php echo $page_title ?></title>
<link rel="shortcut icon" href="<?php echo DEDALO_ROOT_WEB ?>/favicon.ico" />
<?php echo trim($css_link_code); ?>
<?php
$page_globals = new stdClass();
	# version
	$page_globals->dedalo_version 			= DEDALO_VERSION;
	# lang
	$page_globals->dedalo_application_lang 	= DEDALO_APPLICATION_LANG;
	$page_globals->dedalo_data_lang 		= DEDALO_DATA_LANG;
	$page_globals->dedalo_data_nolan 		= DEDALO_DATA_NOLAN;
	# parent
	$page_globals->_parent 	= isset($parent) ? (int)$parent : '';
	# tipos
	$page_globals->tipo 		= $tipo;
	$page_globals->section_tipo = defined('SECTION_TIPO') ? SECTION_TIPO : null;
	$page_globals->section_name = defined('SECTION_TIPO') ? RecordObj_dd::get_termino_by_tipo(SECTION_TIPO,DEDALO_APPLICATION_LANG) : null;
	# top
	$page_globals->top_tipo 	= TOP_TIPO;
	$page_globals->top_id 		= TOP_ID;
	# modo
	$page_globals->modo 		= isset($modo) ? $modo : null;
	# caller_tipo
	$page_globals->caller_tipo 	= $caller_tipo;
	# context_name
	$page_globals->context_name = $context_name;
	# tag_id
	$page_globals->tag_id 		= isset($_REQUEST["tag_id"]) ? safe_xss($_REQUEST["tag_id"]) : "";
	# user_id
	$page_globals->user_id 		= isset($user_id) ? $user_id : null;
	# username
	$page_globals->username 	= isset($username) ? $username : null;
	# full_username
	$page_globals->full_username= isset($full_username) ? $full_username : null;
	# is_global_admin
	$page_globals->is_global_admin = (bool)$is_global_admin;
	# components_to_refresh
	$page_globals->components_to_refresh = [];
	# portal
	$page_globals->portal_tipo 			= isset($_REQUEST["portal_tipo"]) ? safe_xss($_REQUEST["portal_tipo"]) : null;
	$page_globals->portal_parent 		= isset($_REQUEST["portal_parent"]) ? safe_xss($_REQUEST["portal_parent"]) : null;
	$page_globals->portal_section_tipo 	= isset($_REQUEST["portal_section_tipo"]) ? safe_xss($_REQUEST["portal_section_tipo"]) : null;
	# id_path
	$page_globals->id_path 		= isset($_REQUEST["id_path"]) ? safe_xss($_REQUEST["id_path"]) : null;
	# dedalo_protect_media_files
	$page_globals->dedalo_protect_media_files 	= (defined('DEDALO_PROTECT_MEDIA_FILES') && DEDALO_PROTECT_MEDIA_FILES===true) ? 1 : 0;
	# notifications
	$page_globals->DEDALO_NOTIFICATIONS 	  	= defined("DEDALO_NOTIFICATIONS") ? (int)DEDALO_NOTIFICATIONS : 0;
	$page_globals->DEDALO_PUBLICATION_ALERT 	= defined("DEDALO_PUBLICATION_ALERT") ? (int)DEDALO_PUBLICATION_ALERT : 0;
	# float_window_features
	$page_globals->float_window_features 		= json_decode('{"small":"menubar=no,location=no,resizable=yes,scrollbars=yes,status=no,width=600,height=540"}');
?>

<script>
const page_globals=<?php echo SHOW_DEBUG===true ? json_encode($page_globals, JSON_PRETTY_PRINT) : json_encode($page_globals) ?>;
<?php #echo js::get_json_elements_data(); ?>
</script>
<?php echo trim($js_link_code) ?>
<script>
// window.addEventListener("load", function (event) {
// 	menu.init()
// });
</script>
</head>
<body>
<div id="html_page_wrap" class="<?php echo "html_page_wrap_{$modo} html_page_wrap_{$tipo}"; if(SHOW_DEBUG===true && DEVELOPMENT_SERVER===true) {echo " daleks";}?>">
	<?php


	#
	# HEADER . PAGE HEADER HTML
		print $html_header;	


	#
	# LOG MESSAGES		
		print '<!-- LOG MESSAGES HTML -->';
		print '<div id="log_messages" ondblclick="this.innerHTML=\'\';">';
		if(SHOW_DEBUG===true) {
			if (!TOP_TIPO) {
				print "<div class=\"warning\">Error: TOP_TIPO is empty</div>";
			}		
		}
		print implode('<br>', (array)$log_messages);
		if(error_get_last()) {
			print "Last Error: <pre>";
			print_r(error_get_last());
			print "</pre>";
		}
		print '</div><!-- /log_messages -->';
		
	
	#
	# GLOBAL INFO
		print '<!-- GLOBAL INFO-->';
		print '<div id="global_info" ondblclick="this.innerHTML=\'\';">';
		print '</div>';


	#
	# CONTENT HTML
		print '<!-- CONTENT_HTML -->';
		print '<div class="content_html">';
		print $html;
		print '</div><!-- /content_html -->';


	#
	# FOOTER
		print '<!-- FOOTER HTML -->';

		# BUTTON BACK
		if(
			isset($_SERVER['HTTP_REFERER']) 
			&& empty($caller_id)
			&& empty($_GET['bc_path'])
			&& strpos($modo, 'tool_')===false
			&& login::is_logged()
			)
		{
			print '<div class="css_button_generic button_back link" onclick="goto_url(document.referrer);">';
			print label::get_label('volver') ;
			print '</div>';
		}

		#
		# TIME TO LOAD
		if(SHOW_DEBUG===true) {
			if($modo!=='relation') include(DEDALO_LIB_BASE_PATH.'/html_page/html/html_page_time_to_load.phtml');
		}
	?>

</div><!-- /html_page_wrap -->
<?php
	# DEBUG
	if(SHOW_DEBUG===true) {

		# DEBUGGER INFO
		# if($modo!='relation') include(DEDALO_LIB_BASE_PATH.'/html_page/html/html_page_debug.phtml');
		if(SECTION_TIPO === 'test65'){
			?>
				<div id='section_content'>PATATAAAAA
					
					<script type="module" src="<?php echo DEDALO_LIB_BASE_URL ?>/test/page.js"></script>
					<script>
						// import {lets_go} from '../../../test/page.js';
					</script>
				</div>
				
			<?php
		}
		
		
	}#if(SHOW_DEBUG===true)
?>
</body>
</html>