<?php
die();







/*
$dedalo_ar_langs = array(
					"lg-spa",
					"lg-eng",
					"lg-cat"
					);
print "<!-- JUMP LANG -->";	
print "<select name=\"dedalo_data_lang\" onchange=\"jump_select(this)\">";

	foreach($dedalo_ar_langs as $lang => $lang_name) {
		
	}
	$slected = '';
	if(DEDALO_DATA_LANG == 'lg-spa') $slected = 'selected="selected';
print "	<option value=\"lg-spa&dedalo_application_lang=lg-spa\" <?php if(DEDALO_DATA_LANG == 'lg-spa') echo 'selected="selected"' ?> >LANG : Español</option>";
print "	<option value=\"lg-eng&dedalo_application_lang=lg-eng\" <?php if(DEDALO_DATA_LANG == 'lg-eng') echo 'selected="selected"' ?> >LANG : English</option>";
print " <option value="\lg-cat&dedalo_application_lang=lg-cat\" <?php if(DEDALO_DATA_LANG == 'lg-cat') echo 'selected="selected"' ?> >LANG : Català</option>";
print "</select>";
*/
?>