<!-- PAGE HEADER -->
<?php
# MENU
# Carga el listado del menú de tipo <ul><li></li></ul> generado por el objeto menu
# que se llama desde el controlador de html_page y se visualiza en 'html_page.phtml'
if (login::is_logged()) {
	
	switch (true) {
		case (SHOW_DEBUG===TRUE && DEDALO_DATABASE_CONN=='dedalo4_development' && strpos($_SERVER['HTTP_HOST'],'8888')!==FALSE):
			$menu_wrapper_css = 'menu_wrapper_debug_development';
			break;
		case (SHOW_DEBUG):
			$menu_wrapper_css = 'menu_wrapper_debug';
			break;		
		default:
			$menu_wrapper_css='';
			break;
	}

	# Sólo se usa para ocupar el espacio del mewnu_wrapper ya que este es de posición fija y no ocupa espacio en la página
	print "<div class=\"menu_wrapper_space\"></div>";

	print "<div id=\"menu_wrapper\" class=\"$menu_wrapper_css\" >";

		# Quit button
		print "<div id=\"quit\" class=\"button_in_menu icon_bs link\" title=\"".label::get_label('salir')."\"></div>";

		# icon Dédalo
		print "\n<a href=\"http://www.fmomo.org/\" target=\"_blank\" class=\"dedalo_icon_top\" title=\"Dédalo version ".DEDALO_VERSION." ( build ".DEDALO_BUILD.")\"></a>";

		# menu tree
		print $menu_html;

		# Logged user
		print "\n<div class=\"button_in_menu logged_user_name\">".navigator::get_username()."</div>";

		
		# log messages in debug mode
		if(SHOW_DEBUG===TRUE) {
			print "\n<div class=\"button_in_menu div_log_messages_checkbox\">
					<input type=\"checkbox\" id=\"log_messages_checkbox\" class=\"button_in_menu\" value=\"1\" > 
					Messages
				</div>";
		}		
		


		# INSPECTOR : button open / hide sidebar 
		$caller_id = navigator::get_selected('caller_id');
		if( empty($caller_id) && $modo=='edit' ) {
			print "<!-- Inspector toggle button -->";
			#print "<div id=\"button_toggle_inspector\" class=\"button_in_menu text_unselectable'\" onclick=\"inspector.toggle_sidebar()\">INSPECTOR $caller_id</div>";
			print "<div id=\"button_toggle_inspector\" class=\"button_in_menu icon_bs link'\" title=\"".label::get_label('mostrar_inspector')."\" onclick=\"inspector.toggle_sidebar()\"></div>";
		}



		# LANG JUMP
		if(!isset($dedalo_aplication_langs_selector_html)) $dedalo_aplication_langs_selector_html = html_page::get_dedalo_aplication_langs_selector_html();
		print $dedalo_aplication_langs_selector_html;		

		?>


		<?php if(SHOW_DEBUG===TRUE) { ?>
		<a href="javascript:void" style="position:relative;top:5px;left:10px;color: #E7E5E5;font-weight: bold;text-decoration: none;text-shadow: 0 1px 1px rgba(0, 0, 0, 0.3);"
			onclick="if( confirm('Sure to IMPORT and overwrite current structure data in active DB from file \n  dedalo4_development -> <?php echo DEDALO_DATABASE_CONN ?> \nMySQL Database?') ) window.open('<?php echo DEDALO_LIB_BASE_URL ?>/backup/trigger.db_utils.php?action=import','Export','width=600,height=200');"
			>STR Import</a>
		<?php } #if(SHOW_DEBUG===TRUE) { ?>


		<?php if(SHOW_DEBUG===TRUE && DEDALO_DATABASE_CONN=='dedalo4_development' && strpos($_SERVER['HTTP_HOST'],'8888')!==FALSE) { ?>
		<a href="javascript:void" style="position:relative;top:5px;left:15px;color: #E7E5E5;font-weight: bold;text-decoration: none;text-shadow: 0 1px 1px rgba(0, 0, 0, 0.3);"
		onclick="if( confirm('Sure to EXPORT and overwrite structure data in file \n <?php echo DEDALO_DATABASE_CONN ?>.sql \nfile?') ) window.open('<?php echo DEDALO_LIB_BASE_URL ?>/backup/trigger.db_utils.php?action=export','Export','width=600,height=220');" 
		>STR Export</a> 
		<?php } #if( DEDALO_DATABASE_CONN=='dedalo4_development' ) { ?>

		

		<?php
		# SECTION : label
		$current_selected_area = navigator::get_selected('area');
		if(!empty($current_selected_area)) {
			$section_tipo 	= $current_selected_area;
			$section_name 	= RecordObj_ts::get_termino_by_tipo($section_tipo,DEDALO_APPLICATION_LANG);
			if($section_name  && ( SHOW_DEBUG===true) ) {
				$current_table 	= common::get_matrix_table_from_tipo($section_tipo);
				$section_name .= " [$current_table]";
			}		
			print "<!-- Section label -->";
			if( !empty($section_tipo) && $modo=='list' ) {
				print "<div id=\"current_section_label\" class=\"button_in_menu css_label text_unselectable cursor_default\">$section_name</div>";
			}else if(!empty($section_tipo)) {
				print "<div id=\"current_section_label\" class=\"button_in_menu css_label text_unselectable\" title=\"".label::get_label('ir_a_seccion')."\" onclick=\"goto_url('?m=list&t=$section_tipo')\">";				
				print $section_name;
				print ' '.section::$active_section_id;
				print "</div>";

			}

		}
		
	
	print "</div><!-- /menu_wrapper -->\n";
}
?>





	<?php if (login::is_logged()) {
		#echo "<div class=\"icon_bs link\" id=\"quit\" title=\"".label::get_label('salir')."\"></div>";
	}else{			

		if( strpos(DEDALO_HOST, 'debug:8888')!==false || (isset($_REQUEST['larana']) && $_REQUEST['larana']=='cantora') ) { 
			?>
			<div class="dedalo_header_info_div">
			<?php echo " Database: <b>".DEDALO_DATABASE_CONN . "</b> " ?>
			
			<?php /*if( DEDALO_DATABASE_CONN=='dedalo4_development' ) { ?>
			<a href="javascript:void"
			onclick="if( confirm('Sure to EXPORT and overwrite structure file \n <?php echo DEDALO_DATABASE_CONN ?>.sql \nfile?') ) window.open('<?php echo DEDALO_LIB_BASE_URL ?>/backup/trigger.db_utils.php?action=export','Export','width=600,height=200');" 
			>STR DB Export</a> | 
			<?php } #if( DEDALO_DATABASE_CONN=='dedalo4_development' ) { */?>
			
			<a href="javascript:void"
			onclick="if( confirm('Sure to IMPORT and overwrite current structure data in active DB from file \n  dedalo4_development -> <?php echo DEDALO_DATABASE_CONN ?> \nMySQL Database?') ) window.open('<?php echo DEDALO_LIB_BASE_URL ?>/backup/trigger.db_utils.php?action=import','Export','width=600,height=200');"
			>STR DB Import</a> |

			<a href="javascript:;" onclick="$(document).fullScreen(true)">Fullscreen</a>
			</div><!-- /dedalo_header_info_div -->
			<?php
		}# /if( isset($_REQUEST['larana'] && $_REQUEST['larana']='cantora') 

	}
	?>

