<?php
/*
# HEADERS FOR ALLOW CACHE THIS PAGE 
header("Cache-Control: private, max-age=10800, pre-check=10800");
header("Pragma: private");
header("Expires: " . date(DATE_RFC822,strtotime(" 120 day")));
header('Content-Type: text/html');
*/
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>D4 <?php echo $page_title ?> <?php if(isset($username)) echo $username ?> [<?php if(isset($userID_matrix)) echo $userID_matrix ?>] MAIN</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="shortcut icon" href="<?php echo DEDALO_ROOT_WEB ?>/favicon.ico" />
<?php echo $css_link_code ?>

<script>
var DEDALO_LIB_BASE_URL	= '<?php echo DEDALO_LIB_BASE_URL ?>', DEDALO_ROOT_WEB = '<?php echo DEDALO_ROOT_WEB ?>';
var page_globals = new Object();
	page_globals.dedalo_application_lang	= '<?php echo DEDALO_APPLICATION_LANG ?>' ;
	page_globals.dedalo_data_lang		= '<?php echo DEDALO_DATA_LANG ?>' ;
	page_globals.dedalo_data_nolan		= '<?php echo DEDALO_DATA_NOLAN ?>' ; 
	page_globals._parent			= '<?php echo $parent ?>' ;
	page_globals.tipo			= '<?php echo $tipo ?>' ;
	page_globals.modo			= '<?php echo $modo ?>' ;
	page_globals.caller_id			= '<?php echo $caller_id ?>' ;
	page_globals.caller_tipo		= '<?php echo $caller_tipo ?>' ;
	page_globals.context			= '<?php if(isset($context)) echo $context ?>' ;

	page_globals.top_tipo			= '<?php if(isset($top_tipo)) echo $top_tipo ?>' ;
	page_globals.top_id			= '<?php if(isset($top_id)) echo $top_id ?>' ;

DEBUG = <?php var_export(SHOW_DEBUG); ?>;
</script><?php echo $js_link_code ?>

</head>

<body>
<div id="html_page_wrap">

	<?php

	# PAGE HEADER HTML
		print $html_header;


	# LOG MESSAGES		
		print '<!-- LOG MESSAGES HTML -->';
		print '<div id="log_messages">';
		print $log_messages ;
		if(error_get_last()) {
			print "Last Error: <pre>";
			print_r(error_get_last());
			print "</pre>";
		}
		print "</div><!-- /log_messages -->\n\n";
		
	
	# GLOBAL INFO
		print '<!-- GLOBAL INFO-->';
		print '<div id="global_info">';
		print '</div>';


	# CONTENT HTML
		print '<!-- CONTENT HTML -->';
		print "\n<div class=\"content_html\">";
		print $html;
		print "\n</div><!-- /content_html -->\n\n";



	# FOOTER
		print '<!-- FOOTER HTML -->';

		# BUTTON BACK
		if(
			isset($_SERVER['HTTP_REFERER']) 
			&& empty($caller_id)
			&& strpos($modo, 'tool_')===false
			&& login::is_logged()
			)
		{
			print "\n <div class=\"css_button_generic button_back link\" onclick=\"goto_url(document.referrer);\">";
			print label::get_label('volver') ;
			print "</div>";
		}



		# DIALOG FRAME
		#if(empty($caller_id))
		print "\n <iframe id=\"dialog_page_iframe\" class=\"dialog_page_iframe\" src=\"about:blank\"></iframe><!-- /dialog_page_iframe -->\n\n";


		# DEBUG
		if(SHOW_DEBUG===true) {

			# DEBUGGER INFO
			if($modo!='relation')
			require_once('html_page_debug.phtml');
			
		}#if(SHOW_DEBUG===true)



		# TIME TO LOAD
		if($modo!='relation')
		require_once('html_page_time_to_load.phtml');
	?>

</div><!-- /html_page_wrap -->
</body>
</html>