<!-- PAGE HEADER -->
<?php
# MENU
# Carga el listado del menú de tipo <ul><li></li></ul> generado por el objeto menu
# que se llama desde el controlador de html_page y se visualiza en 'html_page.phtml'
if (login::is_logged()) {
	
	switch (true) {
		case (SHOW_DEBUG===TRUE && DEDALO_DATABASE_CONN=='dedalo4_development' && DEDALO_ENTITY=='development'):
			$menu_wrapper_css = 'menu_wrapper_debug_development';
			break;
		case (SHOW_DEBUG):
			$menu_wrapper_css = 'menu_wrapper_debug';
			break;		
		default:
			$menu_wrapper_css='';
			break;
	}

	
	echo "<div id=\"menu_wrapper\" class=\"$menu_wrapper_css\" >";

		# Quit button
		echo "<div id=\"quit\" class=\"button_in_menu icon_bs link\" title=\"".label::get_label('salir')."\" onclick=\"login.Quit()\"></div>";

		# Icon Dédalo
		echo "\n<a href=\"http://www.fmomo.org/\" target=\"_blank\" class=\"dedalo_icon_top\" title=\"Dédalo version ".DEDALO_VERSION." ( build ".DEDALO_BUILD.")\"></a>";

		# Menu tree
		echo $menu_html;		

		# Logged user
		echo "\n<div class=\"button_in_menu logged_user_name\">".navigator::get_username()."</div>";

		
		# log messages in debug mode
		/*
		if(SHOW_DEBUG===TRUE) {
			echo "\n<div class=\"button_in_menu div_log_messages_checkbox\">
					<input type=\"checkbox\" id=\"log_messages_checkbox\" class=\"button_in_menu\" value=\"1\" > 
					Messages
				</div>";
		}
		*/	

		# INSPECTOR : button open / hide sidebar 
		$caller_id = navigator::get_selected('caller_id');
		if( empty($caller_id) && $modo=='edit' ) {
			echo "<!-- Inspector toggle button -->";
			#echo "<div id=\"button_toggle_inspector\" class=\"button_in_menu text_unselectable'\" onclick=\"inspector.toggle_sidebar()\">INSPECTOR $caller_id</div>";
			echo "<div id=\"button_toggle_inspector\" class=\"button_in_menu icon_bs link'\" title=\"".label::get_label('mostrar_inspector')."\" onclick=\"inspector.toggle_sidebar()\"></div>";
		}

		#
		# LANG JUMP
		$dedalo_aplication_langs_selector_html = html_page::get_dedalo_aplication_langs_selector_html();
		echo $dedalo_aplication_langs_selector_html;
		

		#
		# SECTION : label
		$current_selected_area = navigator::get_selected('area');
		if(!empty($current_selected_area)) {
			$section_tipo 	= $current_selected_area;
			$section_name 	= RecordObj_dd::get_termino_by_tipo($section_tipo,DEDALO_APPLICATION_LANG,true);
			if($section_name  && ( SHOW_DEBUG===true) ) {
				$current_table 	= common::get_matrix_table_from_tipo($section_tipo);
				$section_name .= " [$current_table]";
			}		
			echo "<!-- Section label -->";
			if( !empty($section_tipo) && $modo=='list' ) {
				echo "<div id=\"current_section_label\" class=\"button_in_menu css_label text_unselectable cursor_default\">$section_name</div>";
			}else if(!empty($section_tipo)) {
				echo "<div id=\"current_section_label\" class=\"button_in_menu css_label text_unselectable\" title=\"".label::get_label('ir_a_seccion')."\" onclick=\"goto_url('?m=list&t=$section_tipo')\">";				
				echo $section_name;
				echo ' <span id="current_section_id_label">'.section::$active_section_id.'</span>';
				echo "</div>";

			}
		}#end if(!empty($current_selected_area))



		
	
	echo "</div><!-- /menu_wrapper -->\n";



		#
		# DEBUG SECOND LINE
		if(SHOW_DEBUG) {
			/**/
			$debug_line_html  ='';
			$debug_line_html .= "<div class=\"debug_line_wrap\">";

			#
			# DEDALO_ENTITY
			$processUser = posix_getpwuid(posix_geteuid());
			$debug_line_html .= "<span>".DEDALO_ENTITY."</span>";


			#
			# PHP USER
			$processUser = posix_getpwuid(posix_geteuid());
			$debug_line_html .= "<span>PHP ".phpversion()." ".ini_get('session.save_handler')." <b>".$processUser['name']."</b></span>";

			#
			# DATABASE 
			$debug_line_html .= "<span>DB PGSQL ".pg_version(DBi::_getConnection())['server']." <b>".DEDALO_DATABASE_CONN."</b></span>";

			#
			# HTTP SERVER 
			if (function_exists('apache_get_version')) {
				$debug_line_html .= "<span>HTTP "." <b>".apache_get_version()."</b></span>";
			}
		

			#
			# INFO LINK
			$debug_line_html .= "<a href=\"".DEDALO_LIB_BASE_URL."/main/?m=tool_administration&t=".DEDALO_AREA_ROOT_TIPO."&menu=1\">".label::get_label('tool_administration')."</a>"; 

			#
			# STRUCTURE LINKS
			if ( SHOW_DEBUG===true && 
				component_security_administrator::is_global_admin(navigator::get_user_id())===true && 
				strpos($_SERVER['REQUEST_URI'], 'dd_list.php')!==false
				) {

					# IMPORT BUTTON (ADMIN)
					if( strpos(DEDALO_HOST, 'localhost')===false ) {	
						$debug_line_html .= "<a href=\"javascript:void(0)\" class=\"\" onclick=\"menu.import_str(this)\">IMPORT</a>";
					}

					# EXPORT BUTTON (ADMIN)
					if( DEDALO_DATABASE_CONN=='dedalo4_development' && strpos(DEDALO_HOST,'localhost')!==false ) { 
						$debug_line_html .= "<a href=\"javascript:void(0)\" class=\"\" onclick=\"menu.export_str(this)\">EXPORT</a>";
					}

			}//END STRUCTURE LINKS

			#
			# VERSION
			$debug_line_html .= "<span>".DEDALO_VERSION." ".DEDALO_BUILD."</span>";

			$debug_line_html .= "</div>";//END debug_line_wrap
			echo $debug_line_html;


			#$menu_wrapper_space_style = 'height:53px';
			#echo "<div class=\"menu_wrapper_space\" style=\"height:253px\"></div>";
		}

	
	# Sólo se usa para ocupar el espacio del mewnu_wrapper ya que este es de posición fija y no ocupa espacio en la página
	echo "<div class=\"menu_wrapper_space\"></div>";

	if (isset($debug_line_html)) {
		echo "<div class=\"debug_line_wrap_spacer\"></div>";
	}


	
	
		

	
}
?>