<script type="text/javascript">
// tool vars
var tool_options = {
editable: <?php 		echo isset($ar_tool_data['editable']) ? json_encode($ar_tool_data['editable']) : json_encode(true) ?>, //true
selectable: <?php 		echo isset($ar_tool_data['selectable']) ? json_encode($ar_tool_data['selectable']) : json_encode(true) ?>,
allDaySlot: <?php 		echo isset($ar_tool_data['allDaySlot']) ? json_encode($ar_tool_data['allDaySlot']) : json_encode(false) ?>,
slotEventOverlap: <?php echo isset($ar_tool_data['slotEventOverlap']) ? json_encode($ar_tool_data['slotEventOverlap']) : json_encode(false) ?>,
selectHelper: <?php 	echo isset($ar_tool_data['selectHelper']) ? json_encode($ar_tool_data['selectHelper']) : json_encode(true) ?>,
firstDay : <?php 		echo isset($ar_tool_data['firstDay']) ? json_encode($ar_tool_data['firstDay']) : 1 ?>, //1,
get_events_options: {},
eventColor: '#f1ac28',
select_title: <?php echo json_encode($section_name) ?>,
<?php	
if(isset($ar_tool_data['businessHours'])): 
/*
businessHours : {
start: '10:00', // a start time (10am in this example)
end: '17:00', // an end time (6pm in this example)
dow: [ 2, 3, 4 ,5]
// days of week. an array of zero-based day of week integers (0=Sunday)
// (Monday-Thursday in this example)
},
*/
?>
businessHours : <?php echo json_encode($ar_tool_data['businessHours']) ?>,	
<?php endif; ?>
weekends: <?php 	echo isset($ar_tool_data['weekends']) ? json_encode($ar_tool_data['weekends']) : json_encode(true) ?>, //false
hiddenDays: <?php 	echo isset($ar_tool_data['hiddenDays']) ? json_encode($ar_tool_data['hiddenDays']) : json_encode([]) ?>, //[1]
lang: <?php 		echo isset($lang_tld2) ? json_encode($lang_tld2) : json_encode('en') ?>,
<?php if(isset($ar_tool_data['minTime'])): ?>
minTime: <?php echo json_encode($ar_tool_data['minTime']) ?>, //"09:00:00"
<?php endif; ?>
<?php if(isset($ar_tool_data['maxTime'])): ?>
maxTime: <?php echo json_encode($ar_tool_data['maxTime']) ?>, //"20:00:00",
<?php endif; ?>
<?php if(isset($ar_tool_data['slotDuration'])): ?>
slotDuration:<?php echo json_encode($ar_tool_data['slotDuration']) ?>, //'00:15:00',
<?php endif; ?>
}//end tool_options
</script>