<?php

	# VISUALIZADOR HTML	

	
	# ETIQUETA (LABEL)
	#$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= ""; 		
					break;	
						
		case ($permissions>=1)	:
		
					if (!empty($dato)) {

						$dato_keys = array_keys((array)$dato);	
						#dump($ar_proyectos_section,"ar_proyectos_section");
						#dump($dato_keys,"dato_keys");

						$html_contenido .= "<ul>";
						foreach ($ar_proyectos_section as $project_id => $project_name) {

							if (!in_array($project_id, $dato_keys)) continue; # Skip

							#$html_contenido .= "\n <span class=\"css_span_dato\" title=\"$project_id\">$project_name</span>, ";
							$html_contenido .= "\n<li title=\"project_id: $project_id\">$project_name</li>";
						}
						$html_contenido .= "</ul>";
							#dump($html_contenido,"html_contenido");	
					}

		
					/*if($permissions==3){
						$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
					}*/		
					break;					
										
	}
	
	
	# PRINT HTML
	print $html_contenido;
	
	
?>