<?php

	# VISUALIZADOR HTML	
	
	print "<div class=\"wrap_component css_wrap_filter wrap_component_{$modo} tooltip_active\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato='".json_encode($dato)."' ";
	print 'title="'.search_development2::search_options_title( $this->search_operators_info() ).'" ';
	print ">";

	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	
	# CONTENIDO (INPUT)
	$html_content  = '';
	
	switch(true) {
			
		case $permissions==0 :

				$html_content .= ""; 
				break;
						
		case ($permissions>=1) :

				$html_content .= "<ul class=\"filter_projects_list\">";

				# INPUT
				#$html_content .= "<span id=\"search_component_$tipo\">";					
				$i=1; foreach((array)$ar_proyectos_section as $value => $rotulo) {
					
					$html_content .= "<li>";
											
						$input_id = $input_name.'_'.$i;

						$checked  = is_array($dato) && in_array($value, array_keys($dato)) ? 'checked="checked"' : '';
					
						$html_content .= "<input type=\"checkbox\" class=\"filter_checkbox\" id=\"{$input_id}\" ";
						$html_content .= "name=\"{$search_input_name}_array\" ";
						$html_content .= "data-tipo=\"{$tipo}\" ";
						$html_content .= "value=\"{$value}\" ";
						$html_content .= $checked;
						$html_content .= "onchange=\"component_common.fix_dato(this,'{$component_name}')\" ";
						$html_content .= "/> ";
						
						$html_content .= "<label for=\"$input_id\" class=\"filter_checkbox_rotulo\">$rotulo</label> ";
					
					$html_content .= "</li>";
					$i++;
				}
				#$html_content .= "</span>";

				$html_content .= "</ul>";


				if(SHOW_DEBUG===true) {
					$html_content .= "<span class=\"debug_info\">$search_input_name</span>";
				}
					break;							
	}

	
	# Prepare content to show in page
	tools::prepare_content($html_content);

	
	# PRINT HTML
	print $html_label;
	print $html_content;


	print "</div>"; //wrap
?>