<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 				$ar_css['css_span_dato']='';
	if(!isset ($ar_css['filter_checkbox'])) 			$ar_css['filter_checkbox']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 			$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))			$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_component_filter']))	$ar_css['css_wrap_component_filter']='';
	if(!isset ($ar_css['filter_checkbox_rotulo']))		$ar_css['filter_checkbox_rotulo']='';
	
	if(!isset ($tools_html))							$tools_html='';
	
	print "\n<!-- COMPONENT FILTER CHECK BOX [tipo:$tipo section_id_matrix:$parent] $label -->";
	
	print "\n<div class=\"css_wrap_filter css_wrap_component_filter wrap_component {$ar_css['filter_checkbox_rotulo']}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-section_tipo=\"{$section_tipo}\" data-parent=\"{$parent}\" data-modo=\"{$modo}\" data-dato=\"{$dato_string}\" data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}' >";
	
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	$required_code 	= NULL;
	#if($required)	$required_code = 'style="font-weight:bold"';
	
	# CONTENIDO (INPUT)
	$html_contenido  = '';
	$html_contenido .= "\n <div class=\"wrap_dato_component_filter\"> ";	
	switch($permissions) {
			
		case 0 :	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." ($component_name)</span>"; 
					break;
						
		case 1 : 	

					if (is_array ($ar_proyectos_section)) foreach ($ar_proyectos_section as $value => $rotulo) {
						
						if( is_array($dato) && in_array($value, array_keys($dato)) ) {													
							$html_contenido .= "\n <label class=\"filter_checkbox_rotulo {$ar_css['filter_checkbox_rotulo']}\" $required_code >$rotulo</label>";
							$html_contenido .= "\n <br>";
						}	
					}
					break;	
						
		case 2 :
					#dump($ar_proyectos_section,"ar_proyectos_section");
					#dump($dato,"dato");
					
					if (is_array ($ar_proyectos_section)) foreach ($ar_proyectos_section as $value => $rotulo) {
						
						if( is_array($dato) && in_array($value, array_keys($dato)) ) {
							$checked = 'checked="checked"';
						}else {
							$checked = "";
						}
						$html_contenido .= "\n <input class=\"filter_checkbox {$ar_css['filter_checkbox']}\" type=\"checkbox\"
						name=\"{$input_name}\"
						data-tipo=\"{$tipo}\"
						data-lang=\"{$lang}\"
						data-section_tipo=\"{$section_tipo}\"
						data-parent=\"{$parent}\"
						value=\"{$value}\"
						onfocus=\"component_common.select_wrap(null,'$id_wrapper');\"
						title=\"$html_title $value\" $checked />";	#id=\"{$identificador_unico}\" 
												
						$html_contenido .= "\n <label class=\"filter_checkbox_rotulo {$ar_css['filter_checkbox_rotulo']}\" $required_code >$rotulo</label>";
						$html_contenido .= "\n <span class=\"debug_info\">id: $value</span>";
						$html_contenido .= "\n <br>";	
					}					
					break;
		
		case 3 :			
					#$html_contenido .= "\n ".to_string($valor);
					#$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$debugger}</span>";
					break;	
					
							
	}
	$html_contenido .= "\n </div><!-- /wrap_dato_component_filter -->";#end wrap_dato_component_filter
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);

	
	# PRINT HTML
	print $html_label;
	print $html_contenido;



	print "\n</div><!-- /css_wrap_filter COMPONENT FILTER CHECK BOX [tipo:$tipo section_id_matrix:$parent] $label -->\n\n"; //wrap
?>
