<?php
/*
	# VISUALIZADOR HTML	

	
	print "\n<!-- CHECK BOX [tipo:$tipo id_matrix:$id] -->";
	print "\n<div class=\"css_wrap_filter css_wrap_check_box wrap_component\" 
	data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-modo=\"{$modo}\" data-dato=\"{$dato_string}\" data-component_name=\"{$component_name}\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido  = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." (checkbox)</span>"; 
					break;
						
		case 1	: 	if (is_array ($ar_proyectos_section)) foreach ($ar_proyectos_section as $value => $rotulo) {
						
						if( is_array($dato) && array_key_exists($value,$dato) ) {
							$checked = 'checked="checked"';
						}else {
							$checked = "";
						}
						$html_contenido .= "\n <input class=\"filter_checkbox\" type=\"checkbox\" 
						id=\"{$identificador_unico}_tm\" name=\"{$tipo}_{$id}_tm\" 
						data-tipo=\"{$tipo}\" value=\"{$value}\" id=\"{$id}\" 
						title=\"$html_title\" $checked  disabled />";						
						$html_contenido .= "\n <label class=\"css_check_box_rotulo\" $required >$rotulo</label>";	
					}
					break;	
						
		case ($permissions>=2)	:
		
					if (is_array ($ar_proyectos_section)) foreach ($ar_proyectos_section as $value => $rotulo) {
						
						if( is_array($dato) && array_key_exists($value,$dato) ) {
							$checked = 'checked="checked"';
						}else {
							$checked = "";
						}
						$html_contenido .= "\n <input class=\"filter_checkbox\" type=\"checkbox\" 
						id=\"{$identificador_unico}_tm\" name=\"{$tipo}_{$id}_tm\"
						data-tipo=\"{$tipo}\" data-id_matrix=\"{$id}\" data-lang=\"{$lang}\"
						value=\"{$value}\" 
						title=\"$html_title\" $checked />";
												
						$html_contenido .= "\n <label class=\"css_check_box_rotulo\">$rotulo</label>";
						$html_contenido .= "\n <br>";	
					}
					
					#$html_contenido .= "\n <span class=\"css_span_log\"></span>";										
					#$html_contenido .= "\n <span class=\"css_span_ejemplo\">$ejemplo</span>";
							
					if($permissions==3){
						$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$id}\" >{$debugger}</span>";
					}
					break;
			
						
					
							
	}

	# Prepare content to show in page
	tools::prepare_content($html_contenido);
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;

	# INIT COMPONENT
	#require(DEDALO_LIB_BASE_PATH . "/component_common/trigger.component_init.php");
	
	
	print "\n</div>\n\n"; //wrap

	*/
?>