<?php

	# VISUALIZADOR HTML	

	
	# ETIQUETA (LABEL)
	#$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= ""; 		
					break;	
						
		case ($permissions>=1)	:
		
					if (!empty($dato)) {

						$html_contenido .= "<ul>";
						foreach ($ar_proyectos_section as $key => $row) {

							if (!locator::in_array_locator( $row->locator, (array)$dato )) {
								continue;
							}

							$html_contenido .= "<li title=\"project_id: $row->locator->section_id\">$row->label</li>";
						}
						$html_contenido .= "</ul>";	
					}
					break;
										
	}
	
	
	# PRINT HTML
	print $html_contenido;
	
	
?>