<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 				$ar_css['css_span_dato']='';
	if(!isset ($ar_css['filter_checkbox'])) 			$ar_css['filter_checkbox']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 			$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))			$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_component_filter']))	$ar_css['css_wrap_component_filter']='';
	if(!isset ($ar_css['filter_checkbox_rotulo']))		$ar_css['filter_checkbox_rotulo']='';
	
	if(isset($_REQUEST[$tipo])) {
		$dato = (array)$_REQUEST[$tipo];
		#dump($_REQUEST,'dato');dump($dato,'dato');
	}							
		
	
	#print "\n<div class=\"css_wrap_filter css_wrap_component_filter wrap_component {$ar_css['filter_checkbox_rotulo']}\" id=\"{$id_wrapper}\"
	#data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-parent=\"{$parent}\" data-modo=\"{$modo}\" data-dato=\"{$dato_string}\" data-component_name=\"{$component_name}\" >";
	
	#print "\n<!-- COMPONENT FILTER CHECK BOX [tipo:$tipo id_matrix:$id] $label -->";

	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	$required_code 	= NULL;
	#if($required)	$required_code = 'style="font-weight:bold"';
	
	# CONTENIDO (INPUT)
	$html_contenido  = '';
	$html_contenido .= "\n <div class=\"wrap_dato_component_filter\"> ";
	switch($permissions) {
			
		case 0 :	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." ($component_name)</span>"; 
					break;		
						
		case ($permissions>=1) :

					# COMPARISON OPERATORS
					$html_contenido .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);
					

					# INPUT
					$html_contenido .= "<span id=\"search_component_$tipo\">";					
					$i=1; if(is_array ($ar_proyectos_section)) foreach ($ar_proyectos_section as $value => $rotulo) {
						#dump($value,'value'); dump($dato,'dato');
						#if( is_array($dato) && array_key_exists($value,$dato) ) {
						if( is_array($dato) && in_array($value, array_keys($dato)) ) {
							$checked = 'checked="checked"';
						}else {
							$checked = "";
						}
						$html_contenido .= "\n <input class=\"filter_checkbox {$ar_css['filter_checkbox']}\" type=\"checkbox\"
						name=\"{$tipo}_array\"
						data-tipo=\"{$tipo}\"
						value=\"{$value}\"
						title=\"$html_title $value\" $checked
						/> ";
						
						$html_contenido .= "\n <label class=\"filter_checkbox_rotulo {$ar_css['filter_checkbox_rotulo']}\" $required_code >$rotulo</label> ";
						$html_contenido .= "\n <span class=\"debug_info\">id: $value</span> ";
						#$html_contenido .= "\n <br>";
						
					$i++;}
					$html_contenido .= "</span>";	

					# LOGICAL OPERATORS
					$html_contenido .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);
					break;
					
							
	}
	$html_contenido .= "\n </div><!-- /wrap_dato_component_filter -->";#end wrap_dato_component_filter
	
	# Prepare content to show in page
	tools::prepare_content($html_contenido);

	
	# PRINT HTML
	print $html_label;
	print $html_contenido;



	#print "\n</div><!-- /css_wrap_filter COMPONENT FILTER CHECK BOX [tipo:$tipo id_matrix:$id] $label -->\n\n"; //wrap
?>
