<?php

	# VISUALIZADOR HTML

	# ELEMENTOS
	
	#print "\n<!-- COMPONENT_IP [tipo:$tipo section_id_matrix:$parent] -->";	
	print "\n <div class=\"div_ip_list\">";
		
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:
				$html_contenido .= ''; 		
				break;
					
		case ($permissions>=1)	:
			
				$html_contenido .= "\n <span class=\"css_span_dato list_ip_dato\"
				data-tipo=\"{$tipo}\"
				data-section_tipo=\"{$section_tipo}\"
				data-parent=\"{$parent}\"
				data-lang=\"{$lang}\"
				>$dato</span>";

				# GEOIP FLAGS : geoip_info
				if (isset($geoip_info) && is_object($geoip_info)) {
					
					#$html_contenido .= "\n<span class=\"city_span\">$geoip_info->city</span>" ;
					$html_contenido .= "\n<a href=\"$geoiptoolURL\" target=\"_blank\" title=\"Info\">";
					# Flag (http://cdn.whatismyipaddress.com/images/flags/mx.png)							
					$html_contenido .= "\n<img src=\"".DEDALO_LIB_BASE_URL."/themes/default/flags/{$geoip_info->code}.gif\" class=\"flag_img\" title=\"$geoip_info->continent $geoip_info->country $geoip_info->region_name\" />" ; 
					#$html_contenido .= "\n<img src=\"http://cdn.mmcreation.com/icon/flags-iso/flat/16/".strtolower($code).".png\" class=\"flag_img\" title=\"$continent_code $country $region_name\" />" ;			
					$html_contenido .= "\n</a>";
				}		
				
				
				break;					
							
	}	

	
	# PRINT HTML	
	print $html_contenido;


	print "\n </div><!-- /div_ip_list -->";
	
?>