<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 		$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_span_debugger']))	$ar_css['css_span_debugger']='';
	
	print "\n<!-- COMPONENT_IP [tipo:$tipo id_matrix:$id] -->";	
	print "\n <div class=\"div_ip_list\">";
		
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= ''; 		
					break;
					
		case ($permissions>=1)	:
			
					$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']} list_ip_dato\" 
					data-tipo=\"{$tipo}\" data-id_matrix=\"{$id}\" data-parent=\"{$parent}\" data-lang=\"{$lang}\" 
					>$dato</span>";


					# country  
					if(isset($geoip_mm)) {
						
						$geo_tool_link 	= $geoiptoolURL.$ip ;				
						$code 			= 'A1';				
						$continent_code	= false;
						$country		= false;
						$region			= false;
						$region_name	= false;
						$city			= false;				
						
						if($geoip_mm_mode == 'city') {	# mode city
							
							$record 			= geoip_record_by_addr($geoip_mm,$ip);					
							if($record) {
								$code 			= $record->country_code ;		
								$city			= utf8_encode($record->city) ;
								$country 		= $record->country_name ;
								$region 		= $record->region ;
								#if(!empty($code) && !empty($region) && $region>0)
								#$region_name	= $GEOIP_REGION_NAME[$code][$region];
								$continent_code	= $record->continent_code ;

								#dump($record);
							}
							
						}else{							# mode country
							
							$code 				= geoip_country_code_by_addr($geoip_mm, $ip);
							$country			= geoip_country_name_by_addr($geoip_mm, $ip);	
						}				
						
						$html_contenido .= "\n <span class=\"city_span\">$city</span>"  ;
						$html_contenido .= "\n<a href=\"$geo_tool_link\" target=\"_blank\" title=\"Info\">";

						# Flag (http://cdn.whatismyipaddress.com/images/flags/mx.png)							
						$html_contenido .= "\n<img src=\"".DEDALO_ROOT_WEB."/lib/geoip/flags/{$code}.gif\" class=\"flag_img\" title=\"$continent_code $country $region_name\" />" ; 
						#$html_contenido .= "\n<img src=\"http://cdn.mmcreation.com/icon/flags-iso/flat/16/".strtolower($code).".png\" class=\"flag_img\" title=\"$continent_code $country $region_name\" />" ;			
						$html_contenido .= "\n</a>";

						geoip_close($geoip_mm);
					}
			
					
			if($permissions==3)
					
					$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$debugger}</span>";	
							
	}	

	
	# PRINT HTML	
	print $html_contenido;


	print "\n </div><!-- /div_ip_list -->";
	
?>