<?php

	# VISUALIZADOR HTML	
	
	
	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in', $modo, $lang);
	

	print "<div class=\"wrap_component css_wrap_component_info wrap_component_{$tipo}\" id=\"{$id_wrapper}\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-component_info='{$component_info}' ";
	print ">";
	
		
		# ETIQUETA (LABEL)
		$html_label = component_common_draw::draw_label($this);
		
		# CONTENIDO (INPUT)
		$html_contenido = '';
		switch($permissions) {
				
			case 0	:	$html_contenido .= "";
						break;
							
			case 1	: 	$html_contenido .= "";
						break;	
							
			case 2	:
			case 3	:		
						
						#$html_contenido .= "Info: <br>";
						foreach ((array)$ar_widget_html as $key => $widget_html) {
							$html_contenido .= $widget_html;
							#$html_contenido .= "<hr>";
						}

						$html_contenido .= "<a href=\"javascript:;\" class=\"update_info edit_hidden\" onclick=\"component_info.update_info(this);\" data-wrapper_id=\"$id_wrapper\">";
						$html_contenido .= label::get_label('actualizar');
						$html_contenido .= "</a>";
		}

	
		# Prepare content to show in page
		tools::prepare_content($html_contenido);	
		

		# PRINT HTML
		print $html_label;
		print $html_contenido;	
	

	print "</div>"; //wrap


	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in', $modo, $lang);


?>