<?php

	# VISUALIZADOR HTML	

	$html = '';
	switch(true) {
			
		case $permissions===0 :
				$html .= "";
				break;
					
		case $permissions>=1 :
					
				// widgets_html
					$widgets_html = '';
					foreach ((array)$ar_widget_html as $key => $current_widget_html) {
						$widgets_html .= $current_widget_html;
					}

				// add wrapper
				if ($widget_mode==='export') {
					$html .= $widgets_html;
				}else{
					$html .= '<div class="widgets_wrapper">' . $widgets_html . '</div>';
				}
				break;
	}	

	if(SHOW_DEBUG===true && $modo==='edit') {
		$html .= "<span class=\"component_info_debug debug_info\">".exec_time($start_time)."</span>";
	}

	
	# PRINT HTML	
	print $html;