<h2>Thematic</h2>

	
<?php foreach ($data->result as $section_tipo => $ar_nodes) { ?>
	<?php foreach ($ar_nodes as $key => $ts_node_obj) {	?>		
		<div><strong>Term:</strong> <?php echo $ts_node_obj->term ?> <em> [<?php echo $ts_node_obj->term_id ?>]</em> 
		<?php if (!empty($ts_node_obj->ar_childrens)) { ?>
			<a href="javascript:void(0)" onclick='thematic_search.load_childrens(this)' data-container_id="<?php echo "ts_container_".$ts_node_obj->term_id ?>" data-ar_childrens='<?php echo json_encode($ts_node_obj->ar_childrens) ?>'>Load childrens</a>
			<div id="<?php echo "ts_container_".$ts_node_obj->term_id ?>" style="padding-left:20px;">
				<!-- ajax load html here -->
			</div>
		<?php } ?>
		<?php 
		/*
		$ar_indexation = json_decode($ts_node_obj->indexation);
		if (!empty($ar_indexation) && count($ar_indexation)>0 ) { ?>
			<a href="javascript:void(0)" onclick='thematic_search.load_indexations(this,"<?php echo "index_container_".$key ?>")'>Load indexations <?php echo "T:".count($ar_indexation) ?></a>
			<div id="<?php echo "index_container_".$key ?>" data-ar_indexations='<?php echo json_encode($ar_indexation) ?>' style="padding-left:20px;">
				<!-- ajax load html here -->
			</div>
		<?php } */?>
		</div>
	<?php } ?>
<?php } ?>	

<br>