<?php

	# VISUALIZADOR HTML	

	
	#print "\n\n<!-- BUTTON NEW [tipo:$tipo id_matrix:$id] -->";
	#print "\n<div class=\"css_wrap_button_new\">";
	
	# ETIQUETA (LABEL)
	#$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	
	switch($permissions) {
			
		case 0	:	$html_contenido .= "";
					#$html_contenido .= "\n <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." (button_new)</span>";
					break;
						
		case 1	: 	$html_contenido .= "";
					break;	
						
		case ($permissions>=2)	:
					
					$html_contenido .= "\n <div class=\"css_button_generic css_button_new link\" onclick=\"button_new.New(this)\" 
					data-tipo=\"{$target_tipo}\"
					data-section_tipo=\"{$section_tipo}\"
					title=\"$html_title\" >";
					$html_contenido .= $label;
					$html_contenido .= "</div>";
					break;				
	}
	
	
	# PRINT HTML
	print $html_contenido;
	
	
	#print "\n</div><!-- /css_wrap_button_new -->\n\n"; //wrap
?>