<?php

	# VISUALIZADOR HTML	

	
	# CONTENIDO (INPUT)
	$html_content = '';
	
	switch(true) {
			
		case ($permissions===0)	:
				$html_content .= "";
				#$html_content .= "\n <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." (button_new)</span>";
				break;
						
		case ($permissions===1)	:
				$html_content .= "";
				break;	
						
		case ($permissions>=2)	:
				$html_content .= "<div class=\"css_button_generic btn_inside_section_buttons_container css_button_new button_add_record\" onclick=\"button_new.New(this)\" ";
				$html_content .= "data-tipo=\"{$target_tipo}\" ";
				$html_content .= "data-section_tipo=\"{$section_tipo}\" ";
				$html_content .= "title=\"$html_title\">";
				$html_content .= "<span>";
				$html_content .= $label;
				$html_content .= "</span>";
				$html_content .= "</div>";
				break;
	}	
	
	# PRINT HTML
	print $html_content;
?>