<?php

	# VISUALIZADOR HTML	

	
	$html_contenido = '';


	/**
	* CURRENT TESAURUS ROW
	*/
	
	

	# Term text
	#$html_contenido .= "\n <div class=\"tool_indexation_index_list_termino\" title=\"$terminoID\">{$termino}</div><br>";

	
	$html_contenido .= "\n <li class=\"tool_indexation_index_list_termino\" title=\"$terminoID\">";	
	
		# Icon 
		if($context=='tool_window') {
			# Delete button
			$html_contenido .= "\n <div class=\"icon_bs tool_indexation_delete_icon link\" 
								data-id_matrix=\"$current_matrix_id\" data-rel_locator=\"$rel_locator\" data-tag=\"$selected_tagName\"
								data-termino_id=\"$terminoID\" data-termino=\"$termino\" data-tipo=\"$tipo\" data-rel_locator=\"$rel_locator\"
								onclick=\"tool_indexation.remove_index(this)\"
								>";
			$html_contenido .= "</div>";
		}else{
			# label icon
			$html_contenido .= "\n <div class=\"icon_bs tool_indexation_icon link\" 
								data-id_matrix=\"$current_matrix_id\" data-rel_locator=\"$rel_locator\" data-tag=\"$tag_value\" 
								data-termino_id=\"$terminoID\" data-termino=\"$termino\" data-tipo=\"$tipo\"					
								>";
			$html_contenido .= "</div>";
		}
		
		# Termino
		$html_contenido .= $termino;

	$html_contenido .= "</li>";
	
	
	
	# PRINT HTML
	print $html_contenido;
	
?>