<?php
	

	# VISUALIZADOR HTML
	


	$html    = "\n<!-- TOOL PAGE [tipo:$tipo] -->";	
	$html   .= "\n<div class=\"wrap_tool wrap_tool_indexation_page\" >";
	$html	.= $header_html;
	$html   .= "\n<div class=\"content_data text_shadow_inset\" >";

		/*
		$html   .= "\n<script>
					var media_base_path = '',
						media_extension = ''									
					</script>";
		*/

		# LEFT SIDE
		$html   .= "\n<div class=\"left_side\">";			

			#
			# TESAURO (IFRAME)
			$html   .= "\n<div class=\"indexation_page_tesauro\">";
			$html 	.= "\n <iframe id=\"tesauro_frame\" name=\"tesauro_frame\" class=\"tesauro_frame\" src=\"{$tesauro_url}\" ></iframe>";
			$html   .= "\n</div>";

		$html   .= "\n</div>";#left_side

		
		# RIGHT SIDE
		$html   .= "\n<div class=\"right_side\">";
			
			#
			# TEXT (TEXT AREA)
			$html   .= "\n<div class=\"indexation_page_text\">";
			$html 	.= $component_text_area_html;
			$html   .= "\n</div>";

			
			#
			# TERM LIST
			$html   .= "\n<div id=\"indexation_page_list\" class=\"indexation_page_list\">";
			$html 	.= label::get_label('seleccione_una_etiqueta_para_indexar') . ' <br>';
			$html 	.= label::get_label('para_crear_un_fragmento');
			$html   .= "\n</div>";
			

		$html   .= "\n</div>";#right_side
	
	$html .= "\n</div><!-- /content_data -->";
	$html .= "\n</div><!-- /wrap_tool -->"; //wrap_tool

	
	# INSPECTOR LOG TOOL
	$html .= "\n<div id=\"inspector_log\" class=\"tool_transcription_inspector_log\"> </div>";

	print $html;
		
?>