<?php

	# VISUALIZADOR HTML	

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in');

	print "<div class=\"wrap_component css_wrap_security_tools wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-parent=\"{$parent}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-modo=\"{$modo}\"
	data-dato=\"{$dato_string}\"
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";
	
	//data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-parent=\"{$parent}\" data-modo=\"ajax\"
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	
				$html_contenido .= " <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." (security_tools)</span>"; 
				break;
						
		case 1	: 	
				if (is_array ($ar_tools)) foreach ($ar_tools as $tool_name) {
						
					if( is_array($dato) && in_array($tool_name,$dato) ) {
						$checked = 'checked="checked"';
					}else {
						$checked = "";
					}
					$html_contenido .= " <input class=\"css_check_box_security_tools\" type=\"checkbox\" 
					name=\"{$input_name}\"
					data-tipo=\"{$tipo}\"
					data-section_tipo=\"{$section_tipo}\"
					data-parent=\"{$parent}\"
					value=\"{$tool_name}\" title=\"$html_title\" 
					$checked  disabled />";						
					$html_contenido .= " <label class=\"css_check_box_security_tools_rotulo\" $required >$tool_name</label>";	
				}
				break;	
						
		case 2 :
		case 3 :					
				$disabled = null;
				
				$html_contenido .= "<ul>";

				if (is_array ($ar_tools)) foreach ($ar_tools as $tool_name => $tool_label) {
					
					$html_contenido .= "<li>";

						$checked = (is_array($dato) && array_key_exists($tool_name,$dato)) ? 'checked="checked"' : '';
						
						$html_contenido .= " <input class=\"css_check_box_security_tools\" type=\"checkbox\"
						onchange=\"component_security_tools.Save(this)\"
						name=\"{$input_name}\"
						data-tipo=\"{$tipo}\"
						data-lang=\"{$lang}\"
						data-parent=\"{$parent}\"
						data-section_tipo=\"{$section_tipo}\"
						value=\"{$tool_name}\"
						title=\"$tool_name\"
						$checked
						$disabled
						/>";

						$html_contenido .= "<div class=\"icon_bs {$tool_name}_icon icon_tool_preview\"> </div>";

						#$tool_label = label::get_label($tool_name);
						if(SHOW_DEVELOPER===true) {
							$tool_label .= " <small class=\"notas\">[$tool_name]</small>";
						}
						$html_contenido .= " <label class=\"css_check_box_security_tools_rotulo\" $required >$tool_label</label><br>";

						$html_contenido .= "</li>";		
				}

				$html_contenido .= "</ul>";
				
				#$html_contenido .= " <span class=\"css_span_log\"></span>";					
				#$html_contenido .= " <span class=\"css_span_ejemplo\">$ejemplo</span>";
						
				if(SHOW_DEBUG===true) {
					#$html_contenido .= " <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";
				}
				break;
	}


	# Prepare content to show in page
	tools::prepare_content($html_contenido);
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;

	print "</div>"; //wrap


	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out');

?>