<?php

	# VISUALIZADOR HTML	

		
	# CONTENIDO
	$html_contenido = (string)'';
	switch($permissions) {
					
		case ($permissions>=1):
				
		
			$html_av = "<img class=\"\" style=\"width:100%\" src=\"$posterframe_url\" />";	

			# ETIQUETA (LABEL)
			if (!isset($this->print_options->show_label) || $this->print_options->show_label==true) {
			$html_contenido .= "\n <div class=\"print_label {$component_name}_print_label\">$label</div>";
			}
			# CONTENT (DATO)
			$html_contenido .= "\n <div class=\"print_content {$component_name}_print_content\">$html_av</div>";	
	}	

	
	# PRINT HTML	
	print $html_contenido;	
	
?>
