<?php

	# VISUALIZADOR HTML	


	# PLAYER
	$html_contenido = '';

	$html_contenido .= "\n<div class=\"css_player_wrap\"							
							data-tipo=\"{$tipo}\"
							data-section_tipo=\"{$section_tipo}\"
							data-parent=\"{$parent}\"
							data-video_id=\"{$video_id}\"
							>";

		$html_contenido .= "\n <iframe id=\"videoFrame\" name=\"videoFrame\" class=\"videoFrame\" src=\"{$iframe_url}\" onload=\"resizeIframe(this)\"></iframe>";


	$html_contenido .= "\n</div><!-- /css_player_wrap -->";

	# PRINT HTML
	print $html_contenido;

?>