<?php

	# VISUALIZADOR HTML	

		
	# CONTENIDO
	$html_contenido = (string)'';
	switch($permissions) {
			
		case 0	:	
			$html_contenido .= '';
			break;
					
		case ($permissions>=1):
				
			# CLICK_ACTION
			$click_action="onclick=\"tool_common.open_player(this,{'type':'component_av','reelID':'$video_id','quality':'".DEDALO_AV_QUALITY_DEFAULT."'});\" ";

			$html_contenido .= "<img class=\"thumb_in_list av_posterframe_in_list\" data-video_id=\"$video_id\" src=\"$posterframe_url\" $click_action />";	
	}	

	
	# PRINT HTML	
	print $html_contenido;	
	
?>