<?php

	# VISUALIZADOR HTML		

	$html    = "\n<!-- ".__CLASS__." -->";	
	$html   .= "\n<div class=\"wrap_tool wrap_tool_note_page\" >";	

	$html .= $component_text_html;
	#$html   .= $header_html;


	#
	# FILES
	/*
	$html   .= "\n<div class=\"content_data block-content-1\" >";

		



		# PANELS 1 IMPORT FILES CSV
		$html   .= "<div class=\"panel panel-primary\">";
		$html   .= "  <div class=\"panel-heading\">";
		$html   .= "    <h3 class=\"panel-title\"> TOOL IMPORT DEDALO CSV </h3>";
		$html   .= "  </div>";
		$html   .= "  <div class=\"panel-body\">";
			#
			# IMPORT FILES CSV
			$html   .= "<div class=\"panel_option form-inline\"> ";
			
			#$html   .= " <span class=\"glyphicon glyphicon-cog\" aria-hidden=\"true\"></span>";
			#$html   .= " <span>".label::get_label('ruta_carpeta_ficheros')."</span>";

			$html   .= " <div class=\"panel_option_subcontent\">";

			$html   .= " <span>".label::get_label('ruta_carpeta_ficheros')."</span>";

			$default_value = defined('DEDALO_TOOL_IMPORT_DEDALO_CSV_FOLDER_PATH') ? DEDALO_TOOL_IMPORT_DEDALO_CSV_FOLDER_PATH : null;
			$html   .= "  <input type=\"text\" id=\"files_path\" class=\"form-control input-sm files_path\" autocomplete=\"off\" placeholder=\"".label::get_label('files_path')."\" value=\"$default_value\" onchange=\"tool_import_dedalo_csv.set_path(this)\"/>";
			
			$html   .= "  <input type=\"button\" id=\"button_read\" class=\"btn btn-default btn-sm button_read\" value=\"".label::get_label('leer')."\" onclick=\"tool_import_dedalo_csv.get_dir_files(this,event)\"
			data-mode=\"read_dir\" />";
			
			$html   .= "  <div id=\"get_dir_files_response\"></div>";
			$html   .= "  <div id=\"import_seleted_files_response\"></div>";
			$html   .= " </div>";#end panel_option_subcontent

			$html   .= "</div>";#end panel_option
		$html   .= "  </div>";//end panel-body
		$html   .= "</div>";//end panel-primary

	

		# PANELS 2 RENAME FILES
		$html   .= "<div class=\"panel panel-primary\">";
		$html   .= "  <div class=\"panel-heading\">";
		$html   .= "    <h3 class=\"panel-title\"> RENAME FILES FROM CSV </h3>";
		$html   .= "  </div>";
		$html   .= "  <div class=\"panel-body\">";
			#
			# RENAME FILES
			$html   .= "<div class=\"panel_option form-inline\"> ";
			
			#$html   .= " <span class=\"glyphicon glyphicon-cog\" aria-hidden=\"true\"></span>";
			#$html   .= " <span>".label::get_label('ruta_carpeta_ficheros')."</span>";

			$html   .= " <div class=\"panel_option_subcontent\">";
			
			# CSV File
			$html   .= " <span>".label::get_label('ruta_carpeta_ficheros_renombrar')."</span>";			
			$default_rename_dir = $default_value .'/rename';
			$html   .= "  <input type=\"text\" id=\"rf_files_path\" class=\"form-control input-sm files_path\" autocomplete=\"off\" placeholder=\"".label::get_label('files_path')."\" value=\"$default_rename_dir\"/><br>";
				
			# Conserve original files
			$html   .= "<input type=\"checkbox\" id=\"conserve_original_files\" value=\"1\" class=\"checkbox_file\" checked >";
			$html   .= "<label for=\"conserve_original_files\" class=\"\">Conserve original files</label><br>";

			# Submit button
			$html   .= " <input type=\"button\" id=\"rf_button_checkbox\" value=\"Rename files\" class=\"btn btn-default btn-sm submit_button\" onclick=\"tool_import_dedalo_csv.rename_files(this)\">";
			$html   .= " <span class=\"submit_button_label\"> Remember select above a csv file and section tipo before submit rename files</span>";
			
			$html   .= "  <div id=\"rf_get_dir_files_response\"></div>";
			$html   .= "  <div id=\"rf_import_seleted_files_response\"></div>";
			$html   .= " </div>";#end panel_option_subcontent

			$html   .= "</div>";#end panel_option
		$html   .= "  </div>";//end panel-body
		$html   .= "</div>";//end panel-primary	



	$html   .= "\n</div>";//end content_data block-content-1
	*/


	$html .= "\n</div><!-- /wrap_tool -->"; //wrap_tool

	

	print $html;		
?>