<?php

	# VISUALIZADOR HTML	
		
	# BUTTON TOOL IN INSPECTOR
	$html_tool    = "<!-- TOOL FILE VERSIONS [tipo:$tipo id_matrix:$id] -->";
	$html_tool   .= "<div class=\"tool_inspector_div\">";

	$btn_title	  = label::get_label('abrir').' '.label::get_label('herramienta');

	$html_tool   .= "<div class=\"icon_bs tool_image_versions_icon link\" ";
	$html_tool   .= "data-tipo=\"{$tipo}\" data-parent=\"{$parent}\" ";
	$html_tool   .= "title=\"$btn_title\" ";
	$html_tool   .= "onclick=\"tool_common.open_tool_image_versions(this)\" ";
	$html_tool   .= "> </div>";


	$html_tool   .= label::get_label('tool_image_versions');	#" File versions";
	

	$html_tool   .= "</div>";#/tool_inspector_div

	# PRINT HTML
	print $html_tool;