<?php

	# VISUALIZADOR HTML	

	print "<div class=\"wrap_component css_wrap_select tooltip_active\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato='".json_encode($dato)."' ";
	print "data-q_operator='".$q_operator."' ";
	print 'title="'.search_development2::search_options_title( $this->search_operators_info() ).'" ';
	print "data-relation_type='{$relation_type}' ";
	print ">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch($permissions) {
			
		case 0	:
				$html_content .= "";
				break;						
		
		default:

				# COMPARISON OPERATORS
				#$html_content .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);

				$html_content .= '<input class="q_operator" type="text" value="'.$q_operator.'" ';
				$html_content .= "onchange=\"component_common.fix_dato(this,'{$component_name}')\" ";
				$html_content .=' />';

				
				# SELECT
				$html_content .= "<select class=\"css_select\" name=\"{$search_input_name}\" data-tipo=\"{$tipo}\" title=\"$html_title\" ";
				$html_content .= "onchange=\"component_common.fix_dato(this,'{$component_name}')\" ";
				$html_content .= "data-role=\"component_select_selector\" ";
				$html_content .= ">";

					
					$html_content .= "<option value=\"\"> </option>";
					
					/*foreach ($ar_list_of_values->result as $value => $rotulo) {
						
						if( $dato == $value) {
							$checked = 'selected';
						}else {
							$checked = "";
						}
						$html_content .= "<option value='$value' {$checked}> {$rotulo}</option>";
					}*/

					# Available options
					foreach ($ar_list_of_values->result as $key => $item) {

						$label   = (string)$item->label;	# Locator is json encoded object
						$locator = (object)clone $item->value;						
						#dump($locator," locator"); dump($dato," dato");

						#$selected = in_array($locator, $dato) ? 'selected' : '';
						$founded  = locator::in_array_locator( $locator, $ar_locator=$dato, $ar_properties=array('section_id','section_tipo') );
						$selected = $founded ? 'selected' : '';

						$html_content .= '<option value=\''.json_encode($item->value).'\' '.$selected.'>';
						$html_content .= $label;
						$html_content .= '</option>';					
					}


				$html_content .= "</select>";	
				

				# LOGICAL OPERATORS
				#$html_content .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);

				if(SHOW_DEBUG===true) {
					$html_content .= "<span class=\"debug_info\">$search_input_name</span>";
				}
											
	}
	
	# Prepare content to show in page
	tools::prepare_content($html_content);
	

	# PRINT HTML
	print $html_label;
	print $html_content;	

	
	print "</div>"; //wrap
?>