// @license magnet:?xt=urn:btih:0b31508aeb0634b347b8270c7bee4d411b5d4109&dn=agpl-3.0.txt AGPL-3.0
/*global*/
/*eslint no-undef: "error"*/



/**
 * WORKER_CACHE
 * Manages Dédalo files cache when is fired by login
 * Note that files_list is generated by API dd_utils_api::get_dedalo_files
 * and is a list of main javascript Dédalo core and tools modules cached
 * with this service to take control about files changes on every user login.
 * On user logout (quit), the service worker is unregistered and cache is deleted.
 * This is a HTTP fallback option to manage Dédalo files cache !
 * (HTTPS request are managed by service worker 'sw.js')
 */



/**
 * ONMESSAGE
 * Fired from caller 'postMessage' action like:
	const current_worker = new Worker('../area_development/js/worker.js', {
		type : 'module'
	});
	current_worker.postMessage({
		url		: DEDALO_API_URL,
		dd_api	: item.trigger.dd_api,
		action	: item.trigger.action,
		options	: item.trigger.options
	});
	current_worker.onmessage = function(e) {
		const api_response = e.data.api_response
		print_response(body_response, api_response)
		widget_info.classList.remove("lock")
		spinner.remove()
		current_worker.terminate()
	}
*/
self.addEventListener('message', async (event) => {
	const t1 = performance.now()

	// options
		const url = event.data.url

	// get_dedalo_files from API
		const api_response = await data_manager.request({
			url : url,
			body : {
				action	: 'get_dedalo_files',
				dd_api	: 'dd_utils_api'
			}
		});

		// API error case
		if (!api_response.result) {
			console.error('Error on get api response:', api_response);
			self.postMessage({
				status	: 'finish',
				error	: 'Error on get api response'
			});
			return
		}

	// response data
		const api_response_result_length = api_response.result.length

	// worker msg
		self.postMessage({
			status		: 'ready',
			total_files	: api_response_result_length,
		});

	// pre-built headers per type (avoids rebuilding on every iteration)
		const js_headers = new Headers();
		js_headers.append('Content-Type', 'text/javascript');

		const css_headers = new Headers();
		css_headers.append('Content-Type', 'text/css');

		const headers_map = {
			js	: js_headers,
			css	: css_headers
		}

	// fetch cache @see https://developer.mozilla.org/en-US/docs/Web/API/Request/cache
		// cache modes
			// reload :
				// Download a resource with cache busting, but update the HTTP
				// cache with the downloaded resource.
			// no-cache:
				// Download a resource with cache busting when dealing with a
				// properly configured server that will send the correct ETag
				// and Date headers and properly handle If-Modified-Since and
				// If-None-Match request headers, therefore we can rely on the
				// validation to guarantee a fresh response.
		const cache = 'reload';

	// atomic counter for monotonically increasing progress
		let loaded_count = 0

	// fetch each file. Force cache reload (https://hacks.mozilla.org/2016/03/referrer-and-cache-control-apis-for-fetch/)
		const ar_promises = []
		for (let i = 0; i < api_response_result_length; i++) {

			const item = api_response.result[i]

			const file_url = item.url

			const headers = headers_map[item.type] || js_headers

			ar_promises.push(
				fetch(file_url, {
					headers		: headers,
					method		: 'GET',
					cache		: cache, // "no-store","reload","no-cache","force-cache"
				})
				.then((response) => {

					if (!response.ok) {
						throw new Error('Network response was not OK', { cause: item });
					}

					// notify only after confirming a successful response
					loaded_count++
					self.postMessage({
						status		: 'loading',
						key			: loaded_count,
						total_files	: api_response_result_length,
						file_loaded	: true
					});
				})
				.catch((error) => {
					console.error('Error on load file:', item.url, error);
				})
			)
		}

	// wait until all fetch are done
		await Promise.all(ar_promises)

	// worker msg
		self.postMessage({
			status			: 'finish',
			total_files		: api_response_result_length,
			time			: performance.now()-t1
		})

	// debug
		console.log("__***Time performance.now()-t1 worker:", performance.now()-t1);


	return true
})//end message event



/**
 * DATA_MANAGER REQUEST CUSTOM
 * Avoid to use data_manager module to allow happy Firefox users
 */
const data_manager = {
	request : async function(options) {

		// options (local variables prevent shared-state races on concurrent calls)
			const url			= options.url
			const method		= options.method || 'POST' // *GET, POST, PUT, DELETE, etc.
			const mode			= options.mode || 'cors' // no-cors, cors, *same-origin
			const cache			= options.cache || 'no-cache' // *default, no-cache, reload, force-cache, only-if-cached
			const credentials	= options.credentials || 'same-origin' // include, *same-origin, omit
			const headers		= options.headers || {'Content-Type': 'application/json'}// 'Content-Type': 'application/x-www-form-urlencoded'
			const redirect		= options.redirect || 'follow' // manual, *follow, error
			const referrer		= options.referrer || 'no-referrer' // no-referrer, *client
			const body			= options.body // body data type must match "Content-Type" header

		// handle_errors
			const handle_errors = function(response) {
				if (!response.ok) {
					console.warn("-> HANDLE_ERRORS response:",response);
					throw Error(response.statusText);
				}
				return response;
			}

		const api_response = fetch(
			url,
			{
				method		: method,
				mode		: mode,
				cache		: cache,
				credentials	: credentials,
				headers		: headers,
				redirect	: redirect,
				referrer	: referrer,
				body		: JSON.stringify(body)
			})
			.then(handle_errors)
			.then(response => {
				const json_parsed = response.json().then((result)=>{

					if (result.error) {

						// debug console message
							console.error("result error:",result);

						// alert msg to user
							const msg = result.msg || result.error
							console.error("An error occurred in the connection with the API (worker cache data_manager). \n" + msg);

						// custom behaviors
							switch (result.error) {
								case 'not_logged':
									// redirect to login page
									// location.reload();
									console.warn('Result error. no logged!', result);
									break;

								default:
									// write message to the console
									break;
							}
					}

					return result
				})

				return json_parsed
			})
			.catch(error => {
				console.error("!!!!! [data_manager.request] SERVER ERROR. Received data is not JSON valid. See your server log for details. catch ERROR:\n", error)
				console.warn("options:", options);
				return {
					result	: false,
					msg		: error.message,
					error	: error
				}
			});


		return api_response
	}
}//end data_manager



// @license-end
