<?php

	# VISUALIZADOR HTML


	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in');

	print "<div class=\"wrap_component css_wrap_select_lang wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-parent=\"{$parent}\"
	data-section_tipo=\"{$section_tipo}\"
	data-modo=\"{$modo}\"
	data-dato='{$dato_json}'
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";

	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	# CONTENIDO (INPUT)
	$html_content = '';
	switch($permissions) {

		case 0 :	
				$html_content .= "";
				break;

		case 1 : 
				$html_content .= $valor;
				break;

		case 2 :
		case 3 :

				#
				# CONTEXT
				# Set as disabled on time machine context 
				$disabled = (isset($context->context_name) && $context->context_name=='tool_time_machine') ? 'disabled="disabled"' : '';
		
				$html_content .= " <select class=\"css_select_lang\"
				onchange=\"component_select_lang.Save(this)\"
				onfocus=\"component_common.select_wrap(null,'$id_wrapper');\"
				name=\"{$input_name}\"
				data-tipo=\"{$tipo}\"
				data-lang=\"{$lang}\"
				data-section_tipo=\"{$section_tipo}\"
				data-parent=\"{$parent}\"
				data-related_component_text_area=\"{$related_component_text_area}\"
				title=\"$html_title\"
				$disabled
				tabindex=\"1\"
				>";

					#
					# OPTIONS

					# OPTION EMPTY
					#$selected = empty($dato) ? 'selected' : ''; // {$selected}
					$html_content .= " <option value=\"\" > </option>";
				

					# OPTIONS VALUES
					# dump($ar_all_project_select_langs, ' ar_all_project_select_langs ++ '.to_string());
					$option_selected = false;
					foreach ((array)$ar_all_project_select_langs as $current_lang_code => $current_label) {
			
						$current_locator 		= lang::get_lang_locator_from_code($current_lang_code);
						$current_locator_json 	= json_encode($current_locator);

						# Selected
						$selected 				= locator::in_array_locator( $current_locator, (array)$dato, $ar_properties=array('section_tipo','section_id') ) ? 'selected' : false;
						if ($selected!==false) {
							$option_selected = true;
						}

						$html_content .= " <option value='{$current_locator_json}' data-lang='{$current_lang_code}' {$selected}>";
						$html_content .= $current_label;
						if(SHOW_DEBUG===true) {
							#$html_content .= " - ". trim($current_locator_json);
						}
						$html_content .="</option>";
					}

					# dump($dato, ' dato ++ '.to_string());
					if ($option_selected===false && !empty($dato)) {
						#dump($dato, ' dato ++ '.to_string());
						$locator = reset($dato);
						$current_lang_name = lang::get_lang_name_by_locator($locator);
						$current_lang_code = lang::get_code_from_locator($locator);
						
						$value = json_encode( $locator );
						$html_content .= " <option value='".$value."' data-lang='{$current_lang_code}' selected>".$current_lang_name." *</option>";						
					}
					
				$html_content .= " </select>";


				if(SHOW_DEBUG===true) {
					$html_content .= " <span class=\"debug_info notes\">".json_encode($dato)."</span>";
				}				
				break;
	}

	# Prepare content to show in page
	tools::prepare_content($html_content);


	# PRINT HTML
	print $html_label;
	print $html_content;


	print "</div>"; //wrap

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out');


?>