<?php

	# VISUALIZADOR HTML	

	$var_requested = common::get_request_var($tipo);
	#if(isset($_REQUEST[$tipo])) $dato = $_REQUEST[$tipo];	#var_dump($_REQUEST[$tipo]);
	if(!empty($var_requested)) $dato = $var_requested;
		

	print "<!-- COMPONENT SELECT -->";
	print "<div class=\"wrap_component css_wrap_select_lang\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= " <span class=\"css_span_dato\"> No access here (select_lang)! </span>";
					break;
						
		
		case ($permissions>=1)	:

					# COMPARISON OPERATORS
					$html_contenido .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);
		

					# SELECT
					$html_contenido .= " <select class=\"css_select_lang\" name=\"{$search_input_name}\" data-tipo=\"{$tipo}\" title=\"$html_title\"> ";		

						$checked = "";	
						
						$html_contenido .= " <option value=\"\" {$checked}> </option>";
						/*
						foreach((array)$ar_all_project_select_langs as $current_lang_code => $current_locator) {

							$current_label 			= lang::get_name_from_code($current_lang_code);
							$current_locator_json 	= json_encode($current_locator);
							
							$html_contenido .= " <option value='{$current_locator_json}' {$checked}> {$current_label}</option>";							
						}
						*/						
						foreach ((array)$ar_all_project_select_langs as $current_lang_code => $current_label) {
			
							$current_locator 		= lang::get_lang_locator_from_code($current_lang_code);
							$current_locator_json 	= json_encode($current_locator);

							$html_contenido .= " <option value='{$current_locator_json}' data-lang='{$current_lang_code}'>";
							$html_contenido .= $current_label;
							if(SHOW_DEBUG===true) {
								#$html_contenido .= " - ". trim($current_locator_json);
							}
							$html_contenido .="</option>";
						}



					$html_contenido .= " </select>";

					# LOGICAL OPERATORS
					$html_contenido .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);	
					
					break;			
											
	}

	# Prepare content to show in page
	tools::prepare_content($html_contenido);
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;

	print "</div><!-- /css_wrap_select -->"; //wrap
	
?>