<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 				$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_select_lang'])) 			$ar_css['css_select_lang']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 			$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))			$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_select_lang']))		$ar_css['css_wrap_select_lang']='';
	//if(!isset ($ar_css['css_select_lang_rotulo']))	$ar_css['css_select_lang_rotulo']='';
	
	
	if(isset($_REQUEST[$tipo])) $dato = $_REQUEST[$tipo];
		#dump($dato,'dato');
	
	
	#print "\n<!-- SELECT_lang [tipo:$tipo id_matrix:$id] $label -->";
	#print "\n<div class=\"css_wrap_select_lang {$ar_css['css_wrap_select_lang']}\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> No access here (select_lang)! </span>";
					break;
						
		
		case ($permissions>=1)	:

					# COMPARISON OPERATORS
					$html_contenido .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);
		

					# INPUT
					$html_contenido .= "\n <select class=\"css_select_lang {$ar_css['css_select_lang']}\" name=\"{$tipo}\" data-tipo=\"{$tipo}\" title=\"$html_title\"> ";		

					$checked = "";	
					
					$html_contenido .= "\n <option value=\"\" {$checked}> </option>";
					
					if (is_array ($ar_all_project_select_langs)) foreach ($ar_all_project_select_langs as $value => $rotulo) {
						
						
						/*
						if( $dato == $value) {
							$checked = 'selected';
						}else {
							$checked = "";
						}
						*/
						$html_contenido .= "\n <option value=\"{$value}\" {$checked}> {$rotulo}</option>";							
					}					
					$html_contenido .= "\n </select>";

					# LOGICAL OPERATORS
					$html_contenido .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);	
					
					break;			
											
	}

	# Prepare content to show in page
	tools::prepare_content($html_contenido);
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;
	
	
	
	#print "\n</div><!-- /css_wrap_select -->\n\n"; //wrap
?>