<?php

	# VISUALIZADOR HTML	

	
	if(isset($_REQUEST[$tipo])) $dato = $_REQUEST[$tipo];
		

	print "\n<!-- COMPONENT SELECT -->";
	print "\n<div class=\"wrap_component css_wrap_select_lang\" >";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato\"> No access here (select_lang)! </span>";
					break;
						
		
		case ($permissions>=1)	:

					# COMPARISON OPERATORS
					$html_contenido .= operator::get_search_comparison_operators_html($tipo,$ar_comparison_operators);
		

					# SELECT
					$html_contenido .= "\n <select class=\"css_select_lang\" name=\"{$tipo}\" data-tipo=\"{$tipo}\" title=\"$html_title\"> ";		

						$checked = "";	
						
						$html_contenido .= "\n <option value=\"\" {$checked}> </option>";
						
						foreach((array)$ar_all_project_select_langs as $locator_json => $label) {
							
							$html_contenido .= "\n <option value='{$locator_json}' {$checked}> {$label}</option>";							
						}

					$html_contenido .= "\n </select>";

					# LOGICAL OPERATORS
					$html_contenido .= operator::get_search_logical_operators_html($tipo,$ar_logical_operators);	
					
					break;			
											
	}

	# Prepare content to show in page
	tools::prepare_content($html_contenido);
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;

	print "\n</div><!-- /css_wrap_select -->\n\n"; //wrap
	
?>