<?php

	# VISUALIZADOR HTML


	print "\n<!-- SELECT [tipo:$tipo section_id_matrix:$parent] $label -->";

	print "\n<div class=\"wrap_component css_wrap_select_lang wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-parent=\"{$parent}\"
	data-section_tipo=\"{$section_tipo}\"
	data-modo=\"{$modo}\"
	data-dato=\"{$valor_string}\"
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";

	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {

		case 0 :	
				$html_contenido .= "";
				break;

		case 1 : 
				$html_contenido .= $this->valor;
				break;

		case ($permissions>=2)	:

				$html_contenido .= "\n <select class=\"css_select_lang\"
				onchange=\"component_select_lang.Save(this)\"
				onfocus=\"component_common.select_wrap(null,'$id_wrapper');\"
				name=\"{$input_name}\"
				data-tipo=\"{$tipo}\"
				data-lang=\"{$lang}\"
				data-section_tipo=\"{$section_tipo}\"
				data-parent=\"{$parent}\"
				data-related_component_text_area=\"{$related_component_text_area}\"
				title=\"$html_title\"
				tabindex=\"1\"
				> ";

					#
					# OPTIONS

					# OPTIONS EMPTY
					$selected = empty($dato) ? 'selected' : '';
					$html_contenido .= "\n <option value=\"\" {$selected}> </option>";

					# OPTIONS VALUES
					if (is_array ($ar_all_project_select_langs)) foreach ($ar_all_project_select_langs as $value => $value_label) {						
						$selected = ($dato == $value) ? 'selected' : '';
						$html_contenido .= "\n <option value=\"{$value}\" {$selected}> {$value_label}</option>";
					}

				$html_contenido .= "\n </select>";


				if(SHOW_DEBUG) {
					#$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";
				}				
				break;
	}

	# Prepare content to show in page
	tools::prepare_content($html_contenido);


	# PRINT HTML
	print $html_label;
	print $html_contenido;



	print "\n</div><!-- /css_wrap_select_lang SELECT [tipo:$tipo section_id_matrix:$parent] $label -->\n\n"; //wrap
?>
