<?php declare(strict_types=1);
/**
* CLASS DD_CONFIG_STATE
* --------------------------------------------------------------------------
* Atomic, structured writer for Dédalo's auto-managed runtime state file
* (config/config_core.php): install status, maintenance mode, media-access
* override and notification.
*
* Replaces the legacy mutation strategy (append + preg_replace on live PHP
* source, which could half-write executable code) with:
*   - parse the existing define() map (read-only),
*   - apply the single change,
*   - regenerate the whole file to a temp file in the SAME directory,
*   - rename() over the target (atomic on POSIX) under an advisory lock,
*   - opcache_invalidate() so the next request sees the new value.
*
* Callers (area_maintenance::set_config_core, install_config_manager::
* set_install_status) keep ALL their validation and authorization; they only
* delegate the file write here. A structured JSON sidecar (state.json) is
* written alongside as the canonical record; config_core.php remains the file
* the bootstrap reads, so the read path and constant names are unchanged.
* --------------------------------------------------------------------------
*/
final class dd_config_state {

	/** Constants this writer is allowed to manage (the config_core surface). */
	private const WRITABLE = [
		'DEDALO_INSTALL_STATUS',
		'DEDALO_MAINTENANCE_MODE_CUSTOM',
		'DEDALO_NOTIFICATION_CUSTOM',
		'DEDALO_MEDIA_ACCESS_MODE_CUSTOM',
		'DEDALO_RECOVERY_MODE'
	];


	/**
	* set_literal
	* Sets one config_core constant to the given PHP-literal value string
	* (e.g. "'installed'", "false", "'publication'") and atomically regenerates
	* config_core.php. The literal is exactly what the validated caller already
	* builds, so value semantics are unchanged.
	*
	* @param string $name        constant name (must be in WRITABLE)
	* @param string $php_literal  PHP source literal for the value
	* @param string|null $file    config_core.php path (default DEDALO_CONFIG_PATH)
	* @return bool                true on success
	*/
	public static function set_literal(string $name, string $php_literal, ?string $file=null) : bool {

		if (!in_array($name, self::WRITABLE, true)) {
			return false;
		}
		$file = $file ?? self::config_core_file();

		$map = self::parse_define_map($file);
		$map[$name] = $php_literal;

		return self::atomic_write($file, $map);
	}


	/**
	* get
	* Reads the current value of a managed constant from the live constant (if
	* defined) or the file. Returns null when unknown.
	*/
	public static function get(string $name) {
		if (defined($name)) {
			return constant($name);
		}
		$map = self::parse_define_map(self::config_core_file());
		return $map[$name] ?? null; // raw literal string
	}


	// ---- internals ----------------------------------------------------------

	private static function config_core_file() : string {
		return (defined('DEDALO_CONFIG_PATH') ? DEDALO_CONFIG_PATH : __DIR__.'/..') . '/config_core.php';
	}
	private static function state_file() : string {
		return (defined('DEDALO_CONFIG_PATH') ? DEDALO_CONFIG_PATH : __DIR__.'/..') . '/state.json';
	}

	/**
	* parse_define_map
	* Extracts every `define('NAME', <literal>);` from the file as NAME => literal
	* (the literal kept verbatim so unchanged entries round-trip byte-for-byte).
	* @return array<string,string>
	*/
	private static function parse_define_map(string $file) : array {
		$map = [];
		if (!is_file($file)) {
			return $map;
		}
		$content = (string)file_get_contents($file);
		// single-line define()s (config_core only ever holds single-line literals)
		if (preg_match_all('/define\(\s*\'([A-Z0-9_]+)\'\s*,\s*(.+?)\)\s*;/', $content, $m, PREG_SET_ORDER)) {
			foreach ($m as $row) {
				$map[$row[1]] = trim($row[2]);
			}
		}
		return $map;
	}

	/**
	* atomic_write
	* Regenerates config_core.php from the define map and a JSON sidecar.
	* Temp file in the same dir + rename() = atomic; flock guards concurrent
	* writers; opcache is invalidated so the next request reads fresh values.
	*/
	private static function atomic_write(string $file, array $map) : bool {

		$dir = dirname($file);

		// build file content, managed constants first in canonical order
		$php = "<?php\n// Important!: this file is auto-generated by the core system, do not change it manually\n\n";
		foreach (self::WRITABLE as $name) {
			if (array_key_exists($name, $map)) {
				$php .= "define('{$name}', {$map[$name]});\n";
			}
		}
		// preserve any unexpected extra define() found in the file
		foreach ($map as $name => $literal) {
			if (!in_array($name, self::WRITABLE, true)) {
				$php .= "define('{$name}', {$literal});\n";
			}
		}

		// atomic write: temp in same filesystem + rename
		$tmp = tempnam($dir, '.cc_');
		if ($tmp===false) {
			return false;
		}
		$fh = fopen($tmp, 'wb');
		if ($fh===false) {
			@unlink($tmp);
			return false;
		}
		flock($fh, LOCK_EX);
		$ok = fwrite($fh, $php) !== false;
		fflush($fh);
		flock($fh, LOCK_UN);
		fclose($fh);
		if (!$ok || !rename($tmp, $file)) {
			@unlink($tmp);
			return false;
		}
		@chmod($file, 0664);

		// structured sidecar (best-effort; config_core.php stays authoritative)
		@file_put_contents(
			self::state_file(),
			json_encode($map, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . "\n",
			LOCK_EX
		);

		// drop stale opcode cache so the next include sees the new value
		if (function_exists('opcache_invalidate')) {
			@opcache_invalidate($file, true);
		}

		return true;
	}
}
