<?php
/**
* VIEW HTML
* 
*/
$html='';

	$html   .= "<!-- ".__CLASS__." [tipo:$tipo] -->";
	$html 	.= "<div class=\"import_marc21_wrap\">";
	
		# Title
		$html   .= "<h2 class=\"text_shadow_inset\" > TOOL IMPORT MARC21 </h2>";

		#
		# SECTION_TEMP_WRAP
		$html .= "<div id=\"section_temp_wrap\">";
		$html .= $section_temp->get_html();
		$html .= "</div>";


		#
		# UPLOAD FORM
		$html .= "<div id=\"wrap_upload\">";
		$html .= "";
		$html .= "</div>";		
		# JS
		$js  = "";
		$js .= "<script>";
		$js .= "dedalo_upload.build_upload_form({
					container_id 		: 'wrap_upload',
					target_file_path 	: '$target_file_path',
					target_file_name 	: '$target_file_name',
					allowed_extensions 	: ['mrc'],
					on_complete 		: 'tool_import_marc21.upload_complete',
				})";
		$js .= "</script>";

			
		#
		# SECTION_TEMP_WRAP
		$html .= "<button type=\"button\" class=\"btn btn-primary\" id=\"button_import\"> ".label::get_label('importar')." </button>";
		$html .= "<div id=\"response_div\"></div>";


	$html .= "</div>";//end import_marc21_wrap

echo $html;
echo $js;
?>