<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 		$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_relation'])) 		$ar_css['css_relation']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 	$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))	$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_relation']))	$ar_css['css_wrap_relation']='';
	
	if(!isset ($tools_html))					$tools_html='';



	
	print "\n<!-- RELATION TM [tipo:$tipo id_matrix:$id] -->";


	print "\n<div class=\"css_wrap_relation wrap_component {$ar_css['css_wrap_relation']}\" id=\"wrap_relation_{$section_tipo}_tm\"
	data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-modo=\"{$modo}\" data-dato=\"{$dato_string}\" data-component_name=\"{$component_name}\" >";
	#data-id_matrix=\"{$id}\" data-tipo=\"{$section_tipo}\" data-parent=\"{$parent}\" data-modo=\"{$modo}\" data-lang=\"{$lang}\" data-component_name=\"{$component_name}\" >";

	#$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';

	# CONTENIDO (INPUT)
	#$html_contenido .= "\n<div class=\"css_section_group_content \" >";

	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> No access here (relation)! </span>";
					break;
						
		case 1	: 	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\">$dato</span>";
					break;	
						
		case ($permissions>=2)	:

					$html_contenido .= "<div id=\"component_relation_{$section_tipo}_ajax_tm\" class=\"\" 
					data-id_matrix=\"\" data-caller_id=\"{$id}\" data-tipo=\"{$section_tipo}\" data-parent=\"{$parent}\" data-modo=\"ajax\"
					> <span class=\"ajax_loading_msg\">TM Relation loading.. (id:$id)</span> </div>";

					$html_contenido .= "<script>
											component_common.load_component_by_ajax('component_relation_{$section_tipo}_ajax_tm');
										</script>";
					
					
	}
	#$html_contenido .= "\n</div>"; //content



	
	# PRINT HTML
	#print $html_label;
	print $html_contenido;

	
	print "\n</div>\n\n"; //wrap
	
?>