<?php

	# VISUALIZADOR HTML	

	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "";		
					break;
											
		case ($permissions>=1)	:
										
					$html_contenido .= $valor;

					if(SHOW_DEBUG) {
						$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
					}
					break;		
											
	}
	
	# PRINT HTML
	print $html_contenido;
	
?>