<?php

	# VISUALIZADOR HTML	

	
	# CONTENT
	$html_contenido  = '';


		$html_contenido .= "<div class=\"list_thesaurus_element relation_children_list_thesaurus\" ";
		$html_contenido .= "data-section_tipo=\"$section_tipo\"
							data-parent=\"$parent\"
							data-tipo=\"$tipo\"
							data-lang=\"$lang\"
							data-modo=\"edit\"";

			# Content inside div
			# dump($render_vars, ' render_vars ++ '.to_string());	
			switch (true) {
				case (isset($render_vars->type) && $render_vars->type=='link'):

					$html_contenido .= " data-ar_childrens='{$ar_childrens_json}'";

					$value = $this->get_valor(DEDALO_DATA_LANG);
					$valor = component_relation_children::render_list_value($value, $tipo, $parent, $modo, $lang, $section_tipo, $parent);
						#dump($valor, ' $valor ++ '.to_string());
					foreach ($render_vars as $rv_key => $rv_value) {
						$html_contenido .= " data-{$rv_key}='{$rv_value}'";
					}
					$html_contenido .= " onclick=\"component_relation_children.load_childrens(this)\">";
					$html_contenido .= "<div class=\"row_thesaurus_childrens_arrow_icon\"></div>";
					break;

				default:
					$html_contenido .= " onclick=\"component_relation_children.show_component_in_row_thesaurus(this)\">";
					$html_contenido .= $icon_label;
			}

		
		$html_contenido .= "</div>";	
			
	

	
	
	# PRINT HTML
	print $html_contenido;
	
?>