/**
 * TRIPWIRE — a path named in a comment must RESOLVE (P3-1 / DEAD-11).
 *
 * A committed, browser-served file named `docs/client_tests.md` six times. That
 * file does not exist on any clone: the content lives at an internal,
 * GITIGNORED `rewrite/` path, and the live baseline had since moved again into
 * the runner's own `KNOWN_FAILING` map — stale in both directions at once. A
 * reader following it finds nothing and cannot tell whether the doc was deleted,
 * renamed, or never public.
 *
 * `docs_current_engine_tripwire` checks links WITHIN `docs/`. Nothing checked
 * the pointers that live in CODE COMMENTS, which is where a developer actually
 * meets them.
 *
 * CENSUS: TOTAL over comments in `client/`, `tools/` and `scripts/`.
 *
 * MULTI-ROOT BY DESIGN. A comment in `client/dedalo/**` naming `test/client/…`
 * means that path relative to `client/dedalo`, and the site-builder package
 * resolves against `publication/site_builder`. A single-root resolver reported
 * ~30 false positives — and a gate that cries wolf is one somebody deletes.
 */

import { describe, expect, test } from 'bun:test';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { Glob } from 'bun';

const REPO_ROOT = join(import.meta.dir, '..', '..');

/**
 * A repo-shaped path inside a comment. `json` precedes `js` in the alternation
 * DELIBERATELY: regex alternation is first-match, so the other order truncates
 * every `master.json` to `master.js` and invents a missing file.
 */
const PATH_IN_COMMENT =
	/(?:^|[\s(`'"])((?:docs|engineering|scripts|src|client|tools|test|deploy|install|audits|publication)\/[A-Za-z0-9_./-]*\.(?:json|md|ts|js|sh))/g;

/** Roots a comment's path may be relative to. */
const ROOTS = ['', 'client/dedalo', 'publication/site_builder'];

/**
 * Paths that are deliberately not files: illustrative examples, elisions, and
 * GENERATED artifacts absent from a fresh clone.
 */
const NOT_A_FILE = [
	/\.\.\./, // an elided path (`client/.../frame_runner.js`)
	/\bfoo\b|\bbar\b|\bexample\b/, // an illustrative name in prose
	/^engineering\/test_baseline\//, // generated by `bun run test:baseline` (its README says so)
];

function commentPaths(): { file: string; path: string }[] {
	const found: { file: string; path: string }[] = [];
	for (const dir of ['client', 'tools', 'scripts'] as const) {
		for (const rel of new Glob('**/*.{js,ts}').scanSync({ cwd: join(REPO_ROOT, dir) })) {
			const file = `${dir}/${rel}`;
			if (file.includes('node_modules')) continue;
			for (const line of readFileSync(join(REPO_ROOT, file), 'utf8').split('\n')) {
				const trimmed = line.trim();
				if (!(trimmed.startsWith('*') || trimmed.startsWith('//') || trimmed.startsWith('/*'))) {
					continue;
				}
				for (const match of line.matchAll(PATH_IN_COMMENT)) {
					found.push({ file, path: match[1] as string });
				}
			}
		}
	}
	return found;
}

function resolves(path: string): boolean {
	return ROOTS.some((root) => existsSync(join(REPO_ROOT, root, path)));
}

describe('a path named in a comment resolves', () => {
	const refs = commentPaths();

	test('the census reads the trees (anti-vacuity)', () => {
		// "This list is empty" over a scan that found nothing is not a verdict.
		expect(refs.length).toBeGreaterThan(300);
		expect(new Set(refs.map((ref) => ref.file)).size).toBeGreaterThan(80);
	});

	test('every referenced path exists', () => {
		const broken = [
			...new Set(
				refs
					.filter((ref) => !NOT_A_FILE.some((pattern) => pattern.test(ref.path)))
					.filter((ref) => !resolves(ref.path))
					.map((ref) => `${ref.file}: ${ref.path}`),
			),
		].sort();
		expect(
			broken,
			'A comment points at a file that is not on a clone. Repoint it at the real path, ' +
				'or delete the reference — a pointer to nothing is worse than no pointer, because ' +
				`the reader cannot tell which.\n  ${broken.join('\n  ')}`,
		).toEqual([]);
	});

	test('anti-vacuity: the matcher finds a planted broken path and spares a real one', () => {
		const planted = ' * See docs/this_file_does_not_exist.md for details.';
		const hit = [...planted.matchAll(PATH_IN_COMMENT)].map((match) => match[1] as string);
		expect(hit).toEqual(['docs/this_file_does_not_exist.md']);
		expect(resolves(hit[0] as string)).toBe(false);
		// ...and the `json`/`js` ordering bug that invented ~30 missing files.
		const real = ' * The catalog lives in src/core/labels/master.json.';
		const realHit = [...real.matchAll(PATH_IN_COMMENT)].map((match) => match[1] as string);
		expect(realHit).toEqual(['src/core/labels/master.json']);
		expect(resolves(realHit[0] as string)).toBe(true);
	});
});
