/**
 * CSS BUILD tripwire (DEC-12: every documented invariant has one).
 *
 * The client's CSS is COMPILED from LESS and COMMITTED. That is not a style choice, it is
 * forced by the deployment model: `deploy/deploy.sh` states "the repo IS the artifact —
 * deploy = fetch + checkout <ref> on the host", and production installs with
 * `bun install --frozen-lockfile --production`, which does not even install the LESS
 * compiler. Nothing builds CSS on the way to production. So the bytes in git ARE the bytes
 * the browser gets, and the only question worth gating is: **do they still match the source
 * they claim to come from?**
 *
 * WHAT WENT WRONG WITHOUT THIS GATE (all of it real, all found 2026-07-13):
 *   - The CSS was built by a Mac GUI app on one developer's desktop. It stamped ABSOLUTE
 *     source paths into every `.css.map` — `/Users/<whoever>/…/master_dedalo/core/…`, naming
 *     the retired PHP tree's layout. TWO different developers' home directories were
 *     committed this way, and devtools could not resolve a single source, for anyone.
 *   - 33 tool stylesheets `@import`ed a path that resolves to NOTHING in this repo. They only
 *     ever compiled because the GUI app had a search path configured in its own project file.
 *   - One tool's stylesheet imported nothing at all yet used `@color_white`, compiling only
 *     because the same app silently prepended a global LESS file.
 *   - A block of CSS was HAND-APPENDED to the compiled `main.css`, with no source anywhere.
 *
 * Every one of those is a source→output divergence, invisible until someone rebuilds. This
 * gate makes a rebuild happen on every run.
 *
 * THREE ASSERTIONS:
 *   1. every committed `.css` is byte-identical to a fresh compile of its `.less`
 *      (edit the LESS, forget `bun run css:build`, and CI is red);
 *   2. no `sources` entry in any map is an absolute path — the exact regression above;
 *   3. every `sources` entry resolves to a real file, relative to the map itself.
 *
 * THE MAPS THEMSELVES ARE NOT COMMITTED (2026-08-01, `.gitignore`): a `.css.map` ships
 * nothing — it is a devtools aid, regenerated by `bun run css:build` — and 45 committed
 * machine-generated JSON blobs meant every token change in a shared `.less` handed two
 * developers a merge conflict in files nobody reads. So (2) and (3) read the map this run
 * just BUILT, not a file on disk; they still catch the absolute-path regression at its
 * source, which is where it was introduced. The `.css` is a different matter and stays
 * committed: it IS the shipped artifact.
 *
 * It imports the REAL build (`scripts/build_css.ts`), so the gate cannot drift from the tool:
 * a second copy of the compile logic here would be a second thing to keep in sync.
 *
 * COST: compiles 41 entrypoints (~1s). DB-less, network-less → hermetic tier.
 */

import { describe, expect, test } from 'bun:test';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join, normalize } from 'node:path';
import { buildOne, entrypoints } from '../../scripts/build_css.ts';

const REPO_ROOT = join(import.meta.dir, '..', '..');

/** What a maintainer needs to be told when one of these fires. */
const WHY_STALE =
	'Committed CSS is out of date with its LESS. The compiled CSS is what SHIPS (deploy is a checkout, and production installs --production so the compiler is not even there), so a stale .css means the browser gets bytes that no source in this repo produces.\n\nFix: bun run css:build — then commit the result. (Or keep `bun run dev` running; it recompiles on save.)';
const WHY_ABSOLUTE =
	'A .css.map "sources" entry is an ABSOLUTE path. It names one machine\'s filesystem, so it resolves for nobody else — the exact bug the repo build replaced. Sources must be RELATIVE to the map; see relativizeSources() in scripts/build_css.ts.';
const WHY_MISSING =
	'A .css.map names a source file that does not exist, so devtools will 404 on it.';

/** Compile every entrypoint once; the three assertions below all read this. */
const targets = entrypoints();
const built = await Promise.all(
	targets.map(async (lessPath) => ({ lessPath, ...(await buildOne(lessPath)) })),
);

describe('css build tripwire', () => {
	test('there are entrypoints to build (a zero-length pass is not a pass)', () => {
		// Guards the guard: if the discovery ever silently returned [], the two tests below
		// would iterate nothing and report GREEN while proving nothing at all.
		expect(targets.length).toBeGreaterThan(30);
		expect(targets).toContain('client/dedalo/core/page/css/main.less');
	});

	test('every committed .css matches a fresh compile of its .less', () => {
		// Deliberately NOT the .css.map: it is gitignored build output, so on a fresh
		// checkout there is nothing to compare and a byte check here would report every
		// entrypoint stale. The map is still gated — by the two tests below, on the
		// freshly-built bytes.
		const stale: string[] = [];
		for (const { lessPath, css } of built) {
			const cssPath = lessPath.replace(/\.less$/, '.css');
			const cssOnDisk = existsSync(join(REPO_ROOT, cssPath))
				? readFileSync(join(REPO_ROOT, cssPath), 'utf8')
				: null;
			if (cssOnDisk !== css) stale.push(cssPath);
		}
		expect(stale, `${WHY_STALE}\n\nStale:\n${stale.map((f) => `  ${f}`).join('\n')}`).toEqual([]);
	});

	test('no source map points at an absolute path', () => {
		const offenders: string[] = [];
		for (const { lessPath, map } of built) {
			if (map === '') continue;
			const sources: string[] = JSON.parse(map).sources ?? [];
			for (const s of sources) {
				if (s.startsWith('/')) offenders.push(`${lessPath.replace(/\.less$/, '.css.map')} → ${s}`);
			}
		}
		expect(offenders, `${WHY_ABSOLUTE}\n${offenders.join('\n')}`).toEqual([]);
	});

	test('every source map entry resolves to a real file', () => {
		const missing: string[] = [];
		for (const { lessPath, map } of built) {
			if (map === '') continue;
			const cssDir = dirname(lessPath);
			const sources: string[] = JSON.parse(map).sources ?? [];
			for (const s of sources) {
				if (s.startsWith('/')) continue; // reported by the previous test
				if (!existsSync(join(REPO_ROOT, normalize(join(cssDir, s))))) {
					missing.push(`${lessPath.replace(/\.less$/, '.css.map')} → ${s}`);
				}
			}
		}
		expect(missing, `${WHY_MISSING}\n${missing.join('\n')}`).toEqual([]);
	});

	// WHO MAY EMIT the `:root` palette (the 2026-08-02 vars.less → vars_tokens.less split)
	// is a different question from "do the bytes match their source", and lives in its own
	// tripwire: test/unit/css_token_duplication_tripwire.test.ts. It compiles the same
	// entrypoints through the same buildOne().

	/**
	 * The diffusion job table's column template is LOAD-BEARING, and until now it
	 * was defended by a comment alone (diffusion_server_control.less) — exactly the
	 * "state a rule, add no gate" shape DEC-12 forbids.
	 *
	 * WHAT WENT WRONG WITHOUT IT: the table was a plain <table> under auto layout.
	 * Its cells carry `word-break: break-word`, which resolves to
	 * `overflow-wrap: anywhere` — and that COUNTS AS A SOFT-WRAP OPPORTUNITY when
	 * the browser computes min-content width. So the layout believed the State
	 * column could be one character wide and rendered "completed" as "complet/ed",
	 * with the machine-string columns squeezed the same way.
	 *
	 * The fix was an explicit grid template whose first five tracks are all
	 * non-intrinsic (`minmax(<length>, …fr)` or a bare length). That is also
	 * precisely what makes the progress bar's percentage width safe: CSS Grid
	 * §12.5 never consults a cell's min-content contribution for a track whose
	 * sizing functions are non-intrinsic, so no cell content can move these
	 * columns. Relax any of the five to auto / min-content / max-content /
	 * fit-content and BOTH properties fail at once — the wrapping returns and the
	 * bar (a percentage child) starts contributing 0 to its own track.
	 *
	 * The sixth `.with_actions` track is deliberately `auto` and deliberately
	 * excluded: it holds only buttons, never a percentage-width child.
	 */
	test('the diffusion job table keeps a non-intrinsic column template', () => {
		const INTRINSIC = /\b(?:auto|min-content|max-content|fit-content)\b/;
		const main = built.find((b) => b.lessPath === 'client/dedalo/core/page/css/main.less');
		expect(main, 'main.less is not among the compiled entrypoints').toBeDefined();

		// every `.diffusion_server_control_job_table{…}` rule carrying the template
		const rules = [
			...(main as { css: string }).css.matchAll(
				/\.diffusion_server_control_job_table[^{}]*\{([^}]*grid-template-columns[^}]*)\}/g,
			),
		];
		// guards the guard: a selector rename must fail LOUDLY, not pass vacuously
		expect(
			rules.length,
			'No compiled .diffusion_server_control_job_table rule declares grid-template-columns. Either the template was removed (the bug returns) or the selector was renamed — update this gate deliberately.',
		).toBeGreaterThanOrEqual(2);

		const offenders: string[] = [];
		for (const rule of rules) {
			const declared = /grid-template-columns\s*:\s*([^;}]+)/.exec(rule[1] as string);
			if (declared === null) continue;
			// tracks are space-separated, but minmax(a, b) contains a space inside
			// its parens — split on top-level whitespace only
			const tracks = (declared[1] as string).trim().match(/(?:[^\s(]+\([^)]*\)|[^\s]+)/g) ?? [];
			for (const track of tracks.slice(0, 5)) {
				if (INTRINSIC.test(track)) offenders.push(`${track}  (in: ${declared[1]?.trim()})`);
			}
		}
		expect(
			offenders,
			`A .diffusion_server_control_job_table column track among the first five is INTRINSIC (auto / min-content / max-content / fit-content).\n\nThat single change reintroduces two bugs at once: cells wrap mid-word ("complet/ed", "…mdcat353_/rsc170") because word-break:break-word collapses their min-content width to one character, and the progress bar stops sizing because a percentage width contributes 0 to an intrinsic track.\n\nKeep every one of the first five as minmax(<length>, …fr) or a bare length. See the comment above this test.\n\nOffending tracks:\n${offenders.map((o) => `  ${o}`).join('\n')}`,
		).toEqual([]);
	});
});
