// includes
	import '/dedalo/lib/dedalo/section_record/js/section_record.js'
	import '/dedalo/lib/dedalo/section/js/section.js'
	import '/dedalo/lib/dedalo/section/js/render_section.js'
	import '/dedalo/lib/dedalo/section_group/js/section_group.js'

	import '/dedalo/lib/dedalo/component_input_text/js/component_input_text.js'
	import '/dedalo/lib/dedalo/component_select/js/component_select.js'
	import '/dedalo/lib/dedalo/component_radio_button/js/component_radio_button.js'
	import '/dedalo/lib/dedalo/component_check_box/js/component_check_box.js'
	import '/dedalo/lib/dedalo/component_date/js/component_date.js'
	import '/dedalo/lib/dedalo/component_number/js/component_number.js'
	import '/dedalo/lib/dedalo/component_filter/js/component_filter.js'
	import '/dedalo/lib/dedalo/component_section_id/js/component_section_id.js'
	import '/dedalo/lib/dedalo/component_calculation/js/component_calculation.js'
	import '/dedalo/lib/dedalo/component_iri/js/component_iri.js'
	import '/dedalo/lib/dedalo/component_email/js/component_email.js'
	import '/dedalo/lib/dedalo/component_json/js/component_json.js'