// includes
	import '../../section_record/js/section_record.js'
	import '../../section/js/section.js'
	import '../../section/js/render_section.js'
	import '../../section_group/js/section_group.js'


	import '../../component_input_text/js/component_input_text.js'
	import '../../component_select/js/component_select.js'
	import '../../component_radio_button/js/component_radio_button.js'
	import '../../component_check_box/js/component_check_box.js'
	import '../../component_date/js/component_date.js'
	import '../../component_section_id/js/component_section_id.js'	
	import '../../component_filter/js/component_filter.js'
	import '../../component_number/js/component_number.js'
	import '../../component_calculation/js/component_calculation.js'
	import '../../component_iri/js/component_iri.js'
	import '../../component_email/js/component_email.js'
	import '../../component_json/js/component_json.js'

	import '../../common/js/ui.js'

	import '../../component_input_text/js/render_component_input_text.js'
	import '../../component_select/js/render_component_select.js'
	import '../../component_radio_button/js/render_component_radio_button.js'
	import '../../component_check_box/js/render_component_check_box.js'
	import '../../component_date/js/render_component_date.js'
	import '../../component_section_id/js/render_component_section_id.js'	
	import '../../component_filter/js/render_component_filter.js'
	import '../../component_number/js/render_component_number.js'
	import '../../component_calculation/js/render_component_calculation.js'
	import '../../component_iri/js/render_component_iri.js'
	import '../../component_email/js/render_component_email.js'
	import '../../component_json/js/render_component_json.js'