<?php

	# VISUALIZADOR HTML

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'in');

	print "<div class=\"wrap_component css_wrap_relation_children wrap_component_{$modo} wrap_component_{$tipo}\" id=\"{$id_wrapper}\"
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-parent=\"{$parent}\"
	data-section_tipo=\"{$section_tipo}\"
	data-modo=\"{$modo}\"
	data-dato='{$dato_string}'
	data-component_name=\"{$component_name}\"
	data-component_info='{$component_info}'
	>";

	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	# CONTENIDO (INPUT)
	$html_content = '';
	switch($permissions) {

		case 0 :
			$html_content .= "";
			break;

		case 1 :
			$html_content .= $this->valor;
			break;


		case 2 :
		case 3 :

			$html_content .= "<div class=\"wrap_relation_children_values\">";

				# ADD BUTTON
				/**/
				$html_content .= "<div class=\"button_add relation_children_add_button\"
				data-target_section_tipo=\"$target_section_tipo\"
				onclick=\"component_relation_children.open_children_selector_window(this,event)\">
				</div>";
				

				# SOURCE_MODE SWITCH
				$source_mode = 'tree';
				switch ($source_mode) {
					
					case 'tree':
					case 'autocomplete':
					default:

						$hierarchy_types_json 	   = '';
						$hierarchy_sections_json   = json_encode(array($target_section_tipo));
						$parent_area_is_model_json = json_encode($parent_area_is_model);

						# BTN LINK ELEMENT
						$html_content .= "<div class=\"button_add relation_children_add_from_tree_button\"
						data-id_wrapper=\"$id_wrapper\"
						data-parent_area_is_model='{$parent_area_is_model_json}'
						data-component_name=\"$component_name\"
						data-hierarchy_types='{$hierarchy_types_json}'
						data-hierarchy_sections='{$hierarchy_sections_json}'
						onclick=\"component_common.open_ts_window(this,event)\"></div>";

						/*
						#
						# INPUT SEARCH FIELD
						$html_content .= " <input class=\"css_autocomplete_hi_search_field\" type=\"text\" placeholder=\"".label::get_label('buscar')."...\"
						data-id_wrapper=\"$id_wrapper\"
						data-tipo=\"$tipo\"
						data-hierarchy_types='{$hierarchy_types_json}'
						data-hierarchy_sections='{$hierarchy_sections_json}'
						onfocus=\"component_autocomplete_hi.activate(this)\"
						tabindex=\"1\"
						autocomplete=\"off\"
						autocorrect=\"off\"
						/>";
						*/
						if(SHOW_DEBUG===true) {
							#$html_content .= "<div class=\"debug_info notes\">ar_referenced_tipo: ".implode(', ', $ar_referenced_tipo)."</div>";
							#$html_content .= "<div class=\"debug_info notes\">".str_replace('},', '},<br>', $dato_json) ."</div>";
						}	

						# Reset var 'activated' on load
						#$html_content .= "<script>component_autocomplete_hi.activated={}</script>";
						break;
				}//end switch ($source_mode)



				# TERMS
				foreach ((array)$dato as $key => $current_locator) {

					$html_content .= "<div class=\"relation_children_input_line\">";

					# REMOVE BUTTON
					$html_content .= "<input type=\"button\" class=\"button_remove component_relation_children_button_remove\" value=\"\"
										data-role=\"component_relation_children_button_remove\"
										data-target_section_tipo=\"$current_locator->section_tipo\"
										data-target_section_id=\"$current_locator->section_id\"
										onclick=\"component_relation_children.remove_children(this)\" />";

					# TERM STRING
					$value = ts_object::get_term_by_locator( $current_locator, DEDALO_DATA_LANG, $from_cache=true );
					$html_content .= '<span class="locator_label">'.$value.'</span>';

					$html_content .= "</div>";//relation_children_input_line
				}//end foreach ((array)$dato as $key => $current_locator)


					






			$html_content .= "</div>";//end wrap_parent_values
			


			if(SHOW_DEBUG===true) {
				#$html_content .= " <div class=\"debug_info\"> Current val: <strong>$valor</strong></div>";				
				#$html_content .= " <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\">{$debugger}</span>";
				$html_content .= "<span class=\"debug_info\">";
				$html_content .= "<br> locators in section relation (children.tipo: ".$this->relation_type.") : ";
				$html_content .= wrap_pre( to_string($this->get_my_section_relations($this->relation_type)), false );
				$html_content .= "</span>";
			}
			break;
	}

	# Prepare content to show in page
	tools::prepare_content($html_content);


	# PRINT HTML
	print $html_label;
	print $html_content;


	print "</div>"; //wrap

	# html_delimiter
	print component_common_draw::html_delimiter($component_name, $tipo, $parent, $label, 'out');


?>