<?php

	# VISUALIZADOR HTML	

	print "<div class=\"wrap_component css_wrap_date tooltip_active\" id=\"wrap_{$tipo}\" ";
	print "data-mode=\"$date_mode\" ";
	print "data-component_name=\"{$component_name}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-dato='".json_encode($dato)."' ";
	print 'title="'.search_development2::search_options_title( $this->search_operators_info() ).'" ';
	print ">";

	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content = '';
	switch(true) {
			
		case $permissions===0:
				$html_content .= "";
				break;
						
		case ($permissions>=1):

				// q_operator
					$html_content .= '<input class="q_operator" type="text" value="'.$q_operator.'" ';
					$html_content .= "onchange=\"component_common.fix_dato(this,'{$component_name}')\" ";
					$html_content .=' />';

				// input date
					$html_content .= '<ul>';
					foreach ((array)$ar_dato as $key => $current_dato) {
						
						$html_content .= '<li>';
						
						// value 
							$value = isset($valor_start[$key]) ? $valor_start[$key] : '';
							// If operator exists prepend to value (search values)
							//if (isset($current_dato->start->op)) {
							//	$value = $current_dato->start->op . $value;
							//}
					
						// role 
							switch ($date_mode) {
								case 'range':
									$role = 'range_start';
									break;
								case 'period':
									$role = 'period_year';
									break;
								case 'time':
									$role = 'date_time';
									break;
								case 'date':
								default:
									$role = 'range_start';
									break;
							}

						// input
							$html_content .= '<input class="css_date" type="text" ';
							$html_content .= 'data-role="'.$role.'" ';
							$html_content .= 'value="'.$value.'" ';
							$html_content .= "onchange=\"component_common.fix_dato(this,'{$component_name}')\" ";
							$html_content .= '/>';

						$html_content .= " <span class=\"css_span_ejemplo\">Format $ejemplo</span>";

					
						$html_content .= '</li>';
					}//end foreach ($ar_dato as $key => $current_dato)
					$html_content .= '</ul>';

				#
				# JS Init component
					$html_content .= '<script>';
					# Init component
					$init_options = new stdClass();
						$init_options->component_name 	= $component_name;
						$init_options->wrapper_id 		= $id_wrapper;
					$html_content .= 'component_common.init('.json_encode($init_options).');';
					$html_content .= '</script>';
				break;				
	}
	
	# Prepare content to show in page
	tools::prepare_content($html_content);

	# PRINT HTML
	print $html_label;
	print $html_content;
	
	
	print '</div>'; //wrap


