<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 			$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_state'])) 				$ar_css['css_state']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 		$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))		$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_state']))			$ar_css['css_wrap_state']='';
	if(!isset ($ar_css['css_state_rotulo']))		$ar_css['css_state_rotulo']='';
	
	if(!isset ($tools_html))						$tools_html='';
	
	
	print "\n<!-- STATE [tipo:$tipo id_matrix:$id] $label -->";
	print "\n<div class=\"css_wrap_state wrap_component {$ar_css['css_wrap_state']}\" id=\"{$id_wrapper}\"
	data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-parent=\"{$parent}\" data-modo=\"{$modo}\" data-dato=\"{$dato_string}\" data-component_name=\"{$component_name}\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	$required_code 	= NULL;
	#if($required)
	#	$required_code = 'style="font-weight:bold"';
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> No access here (state)! </span>";
					break;						
		
		case ($permissions>=1)	:
		
					if (is_array ($estado)) foreach ($estado as $key => $value) {

						if($key=='ar_porcentaje_lang') {
							$html_contenido .= " (";
							foreach ($value as $current_lang => $porcentaje_lang) {
								$html_contenido .= "<span>".RecordObj_ts::get_termino_by_tipo($current_lang).":{$porcentaje_lang}%</span> ";
							}
							$html_contenido .= ") ";
						}else{
							$html_contenido .= "<span><b>".label::get_label($key)."</b>:{$value}%</span> - ";
						}
					}
					
					#$html_contenido .= 	$html_tools;
					
			if($permissions==3)
			
					$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$debugger}</span>";											
							
	}

	# Prepare content to show in page
	tools::prepare_content($html_contenido);	
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;

	
	
	print "\n</div>\n\n"; //wrap
?>