<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	#if(!isset ($ar_css['css_span_dato'])) 		$ar_css['css_span_dato']='';
	
	#echo "\n<!-- STATE [tipo:$tipo parent:$parent] -->";	
		
	# CONTENIDO 
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	
				$html_contenido .= ''; 		
				break;
					
		case ($permissions>=1) :
					
				/* OLD WORLD
					$icon_html = '';

					$estado_copy = $estado;
					if (is_array ($estado)) foreach ($estado as $key => $value) {

						$title ='';
						
						if($value>0) {


							if($key=='tool_lang') {

								$title .= label::get_label($key);		 
								$title .=":{$value}% ";

								foreach ($estado_copy as $key_copy => $value_copy) {

									if($key_copy=='ar_porcentaje_lang') {										
										foreach ($value_copy as $current_lang => $porcentaje_lang) {									
											$title .= "\n  ".RecordObj_ts::get_termino_by_tipo($current_lang,null,true).":{$porcentaje_lang}%  ";
										}										
									}
								}
							}

							if($key=='ar_porcentaje_lang'){
								# ˙Nothing to do
							}else{
								if($key!='tool_lang') {
									$title .= label::get_label($key);		 
									$title .=":{$value}%";
								}
								
								$key_maped = $this->map_tool_name($key);
								$icon_html .= "<div class=\"icon_map_state\" title=\"$title\">$key_maped</div>";
							}							

							
						}							
						
					}

					$html_contenido .= $icon_html;
					*/

				#dump($ar_valor, ' $ar_valor ++ '.to_string());
				foreach ($ar_valor as $process_name => $ar_values) {						
					#dump($ar_values, ' ar_values ++ '.to_string( $process_name.' : '));
					
					$show_icon = isset($ar_values['show_icon']) ? $ar_values['show_icon'] : false;
					if (!$show_icon) continue;	// Skip this

					$title = '';
					foreach ($ar_values as $key => $element_object) {
						if($key=='show_icon' || !is_object($element_object)) continue;	// Skip 'show_icon' info and possible no objects data

						$title .= $this->element_object_to_text($element_object)."\n";
					}
					$title = trim($title);
					
					$current_class 	= $ar_values['show_icon'];	// state name locator like dd174_1
					$html_contenido .= "<div class=\"icon_state_list $current_class\" title=\"$title\"></div>";						

				}//end foreach ($ar_valor as $key => $ar_values) {
				break;							
	}	

	
	# PRINT HTML	
	print $html_contenido;	
	
?>