<?php

	# VISUALIZADOR HTML	

	
	print "\n<!-- STATE [tipo:$tipo section_id_matrix:$parent] $label -->";
	print "\n<div id=\"{$id_wrapper}\" class=\"css_wrap_state css_wrap_state_edit_tool wrap_component\"
	data-tipo=\"{$tipo}\"
	data-lang=\"{$lang}\"
	data-label=\"{$label}\"
	data-section_tipo=\"{$section_tipo}\"
	data-parent=\"{$parent}\"
	data-modo=\"{$modo}\"
	data-component_name=\"{$component_name}\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	//	dump($_SESSION['dedalo4']['auth']['permissions_table'], '$_SESSION'.to_string());
			#dump($permissions, ' permissions'.to_string());
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." ".get_class()."</span>"; 
					break;
						
		case 1	: 	$html_contenido .= $valor;
					$html_contenido .= "\n <label class=\"css_state_rotulo\">". label::get_label($this->caller_element) ."</label>";
					break;
						
		case ($permissions>=2)	:
					
					# User options
					$checked = $valor_for_checkbox[0]>=1 ? 'checked="checked"' : '';					
					$html_contenido .= "\n <input type=\"checkbox\" class=\"css_state\"
					data-tipo=\"{$tipo}\"
					data-section_tipo=\"{$section_tipo}\"
					data-parent=\"{$parent}\"
					data-lang=\"{$lang}\"
					data-id_wrapper=\"{$id_wrapper}\"
					data-options='".$options_json."'
					data-type='user'					
					value=\"".$valor_for_checkbox[0]."\"
					title=\"$html_title\" $checked
					onchange=\"component_state.update_state_locator(this)\" />";
											
					$html_contenido .= "<span> ".label::get_label('acabado')." </span>";
					if(SHOW_DEBUG) {
					//	$html_contenido .= " [".$this->options->lang."] ";
					}
					#$html_contenido .= "</label> valor: $valor - valor_for_checkbox: $valor_for_checkbox ";

					if ($permissions<3) {

						# USER: Label to info user about current admin options values (read only)
						switch (true) {
							case $valor_for_checkbox[1]==50:
								$html_contenido .= " <strong>".label::get_label('para_revisar')."</strong>";
								break;
							case $valor_for_checkbox[1]==100:
								$html_contenido .= " <strong>".label::get_label('validado')."</strong>";
								break;
							default:
								$html_contenido .= " <strong>".''."</strong>";
								break;
						}
						
					}else if ($permissions>=3) {

						# Admin options
						$html_contenido .= "\n <select onchange=\"component_state.update_state_locator(this)\"
						data-tipo=\"{$tipo}\"
						data-section_tipo=\"{$section_tipo}\"
						data-parent=\"{$parent}\"
						data-lang=\"{$lang}\"
						data-id_wrapper=\"{$id_wrapper}\"
						data-options='".$options_json."'
						data-type='admin'												
						>";
						$html_contenido .= "<option value=\"0\"> </option>";
						$selected = ($valor_for_checkbox[1]==50) ? 'selected="selected"' : '';
						$html_contenido .= "<option value=\"50\" $selected >".label::get_label('para_revisar')."</option>";
						$selected = ($valor_for_checkbox[1]==100) ? 'selected="selected"' : '';
						$html_contenido .= "<option value=\"100\" $selected >".label::get_label('validado')."</option>";
						$html_contenido .= "</select> ";
												
						if(SHOW_DEBUG) {
							#$html_contenido .= " [".$this->options->lang."]";
						}
						#$html_contenido .= "</label> valor: $valor - valor_for_checkbox: $valor_for_checkbox ";
					}

					if(SHOW_DEBUG) {
						#$html_contenido .= "\n <span class=\"css_span_debugger\" id=\"debugger_{$tipo}\" >{$debugger}</span>";	
					}
					break;
			
	}

	# Prepare content to show in page
	tools::prepare_content($html_contenido);	
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;

	
	
	print "\n</div>\n\n"; //wrap
?>