<?php

	# VISUALIZADOR HTML	

	# ELEMENTOS
	if(!isset ($ar_css['css_span_dato'])) 			$ar_css['css_span_dato']='';
	if(!isset ($ar_css['css_state'])) 				$ar_css['css_state']='';
	if(!isset ($ar_css['css_span_ejemplo'])) 		$ar_css['css_span_ejemplo']='';
	if(!isset ($ar_css['css_span_debugger']))		$ar_css['css_span_debugger']='';
	if(!isset ($ar_css['css_wrap_state']))			$ar_css['css_wrap_state']='';
	if(!isset ($ar_css['css_state_rotulo']))		$ar_css['css_state_rotulo']='';
	
	if(!isset ($tools_html))						$tools_html='';
	
	
	print "\n<!-- STATE [tipo:$tipo id_matrix:$id] $label -->";
	print "\n<div class=\"css_wrap_state wrap_component {$ar_css['css_wrap_state']}\" id=\"{$id_wrapper}\"
	data-id_matrix=\"{$id}\" data-tipo=\"{$tipo}\" data-lang=\"{$lang}\" data-parent=\"{$parent}\" data-modo=\"{$modo}\" data-dato=\"{$dato_string}\" data-component_name=\"{$component_name}\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);

	$required_code 	= NULL;
	#if($required)
	#	$required_code = 'style="font-weight:bold"';
	
	# CONTENIDO (INPUT)
	$html_contenido = '';
	switch($permissions) {
			
		case 0	:	$html_contenido .= "\n <span class=\"css_span_dato {$ar_css['css_span_dato']}\"> ".label::get_label('sin_acceso')." (checkbox)</span>"; 
					break;
						
		case 1	: 	$html_contenido .= $valor;											
					$html_contenido .= "\n <label class=\"css_state_rotulo {$ar_css['css_state_rotulo']}\" $required_code >". label::get_label($this->caller_element) ."</label>";
					break;
						
		case ($permissions>=2)	:
						
					if($estado) {
						$checked = 'checked="checked"';
					}else {
						$checked = "";
					}
					$html_contenido .= "\n <input class=\"css_state {$ar_css['css_state']}\" type=\"checkbox\" 
					name=\"{$input_name}\"
					data-tipo=\"{$tipo}\" data-id_matrix=\"{$id}\" data-parent=\"{$parent}\" data-lang=\"{$lang}\" data-dato='".$valor_for_checkbox."' data-caller_component_tipo=\"$this->caller_component_tipo\"
					value=\"$this->caller_element\"
					title=\"$html_title\" $checked />";

											
					$html_contenido .= "\n <label class=\"css_state_rotulo {$ar_css['css_state_rotulo']}\" $required_code >";
					$html_contenido .= $rotulo ;

					#$html_contenido .= "</label> valor: $valor - valor_for_checkbox: $valor_for_checkbox ";							
					
		
			if($permissions==3)
			
					$html_contenido .= "\n <span class=\"css_span_debugger {$ar_css['css_span_debugger']}\" id=\"debugger_{$id}\" >{$debugger}</span>";	
					
							
	}

	# Prepare content to show in page
	tools::prepare_content($html_contenido);	
	
	
	# PRINT HTML
	print $html_label;
	print $html_contenido;

	
	
	print "\n</div>\n\n"; //wrap
?>