<?php

	# VISUALIZADOR HTML	

	
	print "<!-- STATE [tipo:$tipo section_id_matrix:$parent] $label -->";
	print "<div id=\"{$id_wrapper}\" class=\"css_wrap_state css_wrap_state_edit_tool wrap_component\" ";
	print "data-tipo=\"{$tipo}\" ";
	print "data-lang=\"{$lang}\" ";
	print "data-label=\"{$label}\" ";
	print "data-section_tipo=\"{$section_tipo}\" ";
	print "data-parent=\"{$parent}\" ";
	print "data-modo=\"{$modo}\" ";
	print "data-component_name=\"{$component_name}\">";
	
	# ETIQUETA (LABEL)
	$html_label = component_common_draw::draw_label($this);
	
	# CONTENIDO (INPUT)
	$html_content = '';
	
	
	switch($permissions) {
			
		case 0	:	$html_content .= " <span class=\"css_span_dato\"> ".label::get_label('sin_acceso')." ".get_class()."</span>"; 
					break;
						
		case 1	: 	$html_content .= $valor;
					$caller_element  = isset($this->caller_element) ? $this->caller_element : null;
					$html_content .= " <label class=\"css_state_rotulo\">". label::get_label($caller_element) ."</label>";
					break;
						
		case 2	:
		case 3	:					
					# User options
					$checked = $valor_for_checkbox[0]>=1 ? 'checked="checked"' : '';

					$html_content .= "<input type=\"checkbox\" class=\"css_state\" onchange=\"component_state.update_state_locator(this)\" ";
					$html_content .= "id=\"{$id_wrapper}_checkbox\" ";
					$html_content .= "title=\"$html_title\" $checked ";
					$html_content .= "data-tipo=\"{$tipo}\" ";
					$html_content .= "data-section_tipo=\"{$section_tipo}\" ";
					$html_content .= "data-parent=\"{$parent}\" ";
					$html_content .= "data-lang=\"{$lang}\" ";
					$html_content .= "data-id_wrapper=\"{$id_wrapper}\" ";
					$html_content .= "data-options='".$options_json."' ";
					$html_content .= "data-type='user' ";
					$html_content .= "value=\"".$valor_for_checkbox[0]."\" ";					
					$html_content .= "/>";
											
					$html_content .= "<label for=\"{$id_wrapper}_checkbox\">".label::get_label('acabado')."</label>";
					
					

					if($permission_section>=3 || (bool)$is_global_admin===true) {

						# Admin options
						$html_content .= "<select class=\"custom_dropdown\" onchange=\"component_state.update_state_locator(this)\" ";
						$html_content .= "data-tipo=\"{$tipo}\" ";
						$html_content .= "data-section_tipo=\"{$section_tipo}\" ";
						$html_content .= "data-parent=\"{$parent}\" ";
						$html_content .= "data-lang=\"{$lang}\" ";
						$html_content .= "data-id_wrapper=\"{$id_wrapper}\" ";
						$html_content .= "data-options='".$options_json."' ";
						$html_content .= "data-type='admin'";											
						$html_content .= ">";

						$html_content .= "<option value=\"0\"> </option>";

						$selected = ($valor_for_checkbox[1]==50) ? 'selected="selected"' : '';

						$html_content .= "<option value=\"50\" {$selected}>".label::get_label('para_revisar')."</option>";
						$selected = ($valor_for_checkbox[1]==100) ? 'selected="selected"' : '';
						$html_content .= "<option value=\"100\" {$selected}>".label::get_label('validado')."</option>";
						$html_content .= "</select> ";

					}else{

						# USER: Label to info user about current admin options values (read only)
						switch (true) {
							case $valor_for_checkbox[1]==50:
								$html_content .= "<strong>".label::get_label('para_revisar')."</strong>";
								break;
							case $valor_for_checkbox[1]==100:
								$html_content .= "<strong>".label::get_label('validado')."</strong>";
								break;
							default:
								$html_content .= "<strong>".''."</strong>";
								break;
						}
												
					}//end if($permissions>=3 || (bool)$is_global_admin===true)					
					break;
	}

	# Prepare content to show in page
	tools::prepare_content($html_content);	
	
	
	# PRINT HTML
	print $html_label;
	print $html_content;

	
	
	print "</div>"; //wrap
?>