/**
 * PUBLICATION-HOST RULE PROFILE: the media gate for a SEPARATE publication machine that
 * reads the work host's media through a read-only shared mount.
 * Definition: engineering/PUBLICATION_HOST_SPEC.md §5.1.
 *
 * RULE B ONLY. Rule A's auth/ markers are WORK-session credentials; honouring them on
 * the public host would let a work cookie read unpublished media there. So this profile
 * carries the always-on hardening, rule 0 (the marker store is never served), Rule B
 * against the HOST's mount root, and the 404 default deny. Nothing else.
 *
 * ONE TEMPLATE SOURCE. The hardening (htaccessHardeningBlock / nginxHardeningLocations),
 * the Rule B lines, the filename grammar and the SVG header lines are protection.ts's
 * own, imported, never copied. The two profiles are held in lockstep by
 * media_protection_tripwire.test.ts.
 *
 * PURE: no filesystem, no config writes. The CLI (scripts/media_publication_host_rules.ts)
 * and, from phase 2, the publication agent are the only consumers.
 */

import { createHash } from 'node:crypto';
import { config } from '../../config/config.ts';
import { DedaloError } from '../errors/dedalo_error.ts';
import {
	escapeRegexLiteral,
	filterPublicQualities,
	htaccessHardeningBlock,
	nginxHardeningLocations,
	nginxNamedGrammar,
	nginxSvgHeaderLines,
	ruleBApacheLines,
	TEMPLATE_VERSION,
} from './protection.ts';

export type PublicationHostServer = 'apache' | 'nginx';

export interface PublicationHostRuleInput {
	/** Absolute path where the publication host mounts the published media (read-only). */
	readonly root: string;
	/** Public quality folders, filtered through filterPublicQualities (never a master tier). */
	readonly qualities: readonly string[];
}

export interface NormalizedPublicationHostInput {
	readonly root: string;
	readonly qualities: string[];
	/** Requested qualities the filter refused, for the caller to REPORT (never silent). */
	readonly dropped: string[];
}

/** The root is interpolated unquoted into nginx `if (-f …)` and quoted into Apache
 * directives: a closed charset is the whole injection defence. */
const HOST_ROOT_REGEX = /^\/[A-Za-z0-9._/-]+$/;

/** The media URL is IDENTICAL on both hosts (spec §4): published records carry it. */
export function publicationHostMediaUrl(): string {
	return `/dedalo/${config.mediaDir}`;
}

export function normalizePublicationHostInput(
	input: PublicationHostRuleInput,
): NormalizedPublicationHostInput {
	const root = input.root.replace(/\/+$/, '');
	const segments = root.split('/');
	if (!HOST_ROOT_REGEX.test(root) || segments.includes('..') || segments.includes('.')) {
		throw new DedaloError('request.invalid_options', {
			message: `publication host media root must be absolute, [A-Za-z0-9._/-] only, with no '.'/'..' segment and not '/': ${JSON.stringify(input.root)}`,
		});
	}
	const qualities = filterPublicQualities(input.qualities);
	const dropped = input.qualities.filter(
		(raw) => !qualities.includes(String(raw).replace(/^\/+|\/+$/g, '')),
	);
	if (qualities.length === 0) {
		throw new DedaloError('request.invalid_options', {
			message: `publication host profile needs at least one public quality folder; none survived the filter (refused: ${dropped.join(', ') || 'none given'})`,
		});
	}
	return { root, qualities, dropped };
}

/** Everything that shapes one rendered include. The agent reports it; the panel compares. */
export function getPublicationHostConfigHash(
	server: PublicationHostServer,
	input: NormalizedPublicationHostInput,
): string {
	return createHash('sha256')
		.update(
			JSON.stringify({
				version: TEMPLATE_VERSION,
				profile: 'publication_host',
				server,
				root: input.root,
				qualities: input.qualities,
				media_dir: config.mediaDir,
			}),
		)
		.digest('hex');
}

/**
 * The Apache vhost include. A vhost include and not a .htaccess on purpose: the work
 * host's .htaccess lives on the shared tree, and `AllowOverride None` is what keeps the
 * publication host from ever reading it.
 *
 * (!) The gate is NOT inside `<IfModule mod_rewrite.c>`. In a .htaccess that wrapper
 * is tolerable; here it would turn "mod_rewrite missing" into "every file served". Without
 * the module Apache must refuse the configuration.
 */
export function buildPublicationHostApacheConf(input: PublicationHostRuleInput): string {
	const normalized = normalizePublicationHostInput(input);
	const { root, qualities } = normalized;
	return [
		'# Dédalo media access control, PUBLICATION-HOST profile. GENERATED by',
		'# src/core/media/publication_host_rules.ts. Do not edit: re-render instead.',
		`# config-hash: ${getPublicationHostConfigHash('apache', normalized)}`,
		'# Include inside the publication vhost, BEFORE any broader /dedalo Alias.',
		'# Rule B only: work-session media cookies are never honoured on this host.',
		'',
		`Alias ${publicationHostMediaUrl()} "${root}"`,
		`<Directory "${root}">`,
		'\tAllowOverride None',
		'\tRequire all granted',
		htaccessHardeningBlock(),
		'RewriteEngine On',
		'# 0. The marker store itself is never served.',
		'RewriteRule (^|/)\\.publication(/|$) - [R=404,L]',
		...ruleBApacheLines(root, qualities),
		'',
		'# 3. Default deny: 404 hides the existence of unpublished media.',
		'RewriteRule ^ - [R=404,L]',
		'</Directory>',
		'',
	].join('\n');
}

/**
 * The nginx server{} include. The http{} map file is protection.ts's buildNginxMap(),
 * unchanged: its SVG classification maps are needed here, and its cookie map is inert.
 *
 * (!) SELF-CONTAINED AGAINST LOCATION PRECEDENCE. Everything sits inside ONE outer
 * `location ^~ <url>/`, with `return 404` as its default. A `^~` prefix stops nginx from
 * consulting the server's OTHER regex locations, so an operator's static-asset rule
 * (`location ~* \.(jpg|mp4|svg)$ { expires 30d; }`, before or after the include) can never
 * win the request and serve a master or an unpublished file from `root`. Regex locations
 * NESTED in the `^~` are still evaluated, so the hardening and Rule B keep working.
 * (A plain-prefix catch-all lost to any server-level regex: measured on nginx 1.31.)
 *
 * (!) Rule B ALIASES into the host root through the captured `dd_path`. An alias inside
 * a regex location must use the location's captures, and the `if (-f …)` test is not a
 * regex, so it resets none of them.
 */
export function buildPublicationHostNginxConf(input: PublicationHostRuleInput): string {
	const normalized = normalizePublicationHostInput(input);
	const { root, qualities } = normalized;
	const url = publicationHostMediaUrl();
	const escapedUrl = escapeRegexLiteral(url);
	const alternation = qualities.map(escapeRegexLiteral).join('|');
	const nest = (line: string): string => (line === '' ? '' : `\t${line}`);
	return [
		'# Dédalo media access control, PUBLICATION-HOST profile. GENERATED by',
		'# src/core/media/publication_host_rules.ts. Do not edit: re-render instead.',
		`# config-hash: ${getPublicationHostConfigHash('nginx', normalized)}`,
		'# WIRING: http   { include dedalo_media_protection_map.nginx.conf; }  (--server nginx-map)',
		'#         server { include <this file>; }      then: nginx -t && nginx -s reload',
		'# Rule B only: work-session media cookies are never honoured on this host.',
		'# Do NOT enable open_file_cache here: it caches stat() and delays an unpublish.',
		'# The mount must NOT sit under any server/vhost document root.',
		'',
		'# ONE outer `^~` prefix: no server-level regex location can take a media request.',
		`location ^~ ${url}/ {`,
		...nginxHardeningLocations(url).map(nest),
		'\t# 2. Rule B: public quality folders, gated by the publication marker.',
		`\tlocation ~ "^${escapedUrl}/(?<dd_path>(?:${alternation})/(?:.+/)?${nginxNamedGrammar()})" {`,
		`\t\tif (!-f ${root}/.publication/pub/\${dd_s}_\${dd_i}) { return 404; }`,
		`\t\talias ${root}/$dd_path;`,
		...nginxSvgHeaderLines().map(nest),
		"\t\tmp4;   # '?start='/'?end=' clipping (no-op for non-mp4)",
		'\t}',
		'',
		'\t# 3. Default deny: everything else under the media URL.',
		'\treturn 404;',
		'}',
		'',
	].join('\n');
}
