<?php

	$html_row = '';

	$html_row .= "<tr class=\"tr_row\">";
	
	# Empty td
	$html_row .= "<td>";
	$html_row .= " ";
	$html_row .= "</td>";

	# INFO
	$colspan = count($ar_diffusion_obj_head)-1;
	$html_row .= "<td colspan=\"$colspan\">";

	
	$html_row .= "<table class=\"diffusion_index_ts_row_table\">";
	$included_tr_head = false;
	foreach ($ar_row_elements as $current_section_id => $rel_locator_obj) {

		
		# COMPONENT_TEXT_AREA
		$component_text_area 	= component_common::get_instance('component_text_area', $rel_locator_obj->component_tipo,$rel_locator_obj->section_id,'list',DEDALO_DATA_LANG, $rel_locator_obj->section_tipo);
			#dump($component_text_area,'component_text_area');
		$propiedades 			= array('rel_locator'=>$rel_locator_obj);
		$diffusion_obj 			= $component_text_area->get_diffusion_obj( $propiedades );
			#dump($diffusion_obj,'$diffusion_obj'); #die();

		$section_tipo 	= $component_text_area->get_section_tipo();
		$parent 		= $component_text_area->get_parent();
		$id_matrix 		= $component_text_area->get_id();

		#dump($rel_locator_obj);
		$top_tipo 	= $rel_locator_obj->section_top_tipo;
		$top_id 	= $rel_locator_obj->section_top_id;

		# ROW TR HEAD ------------------------------------------------
		if(!$included_tr_head) {
	
			$html_row .= "<tr>";
			$html_row .= "<th>ID</th>";
			$html_row .= "<th>Tag</th>";
			$html_row .= "<th clas=\"th_fragment\">Fragment</th>";
			$html_row .= "<th>".label::get_label('informacion')."</th>";
			$html_row .= "</tr>";

			$included_tr_head = true;
		}		
		

	
		# ROW TR -----------------------------------------------------
		$html_row .= "<tr>";

		
			# ID
			$html_row .= "<td>";
			$html_row .= "<div class=\"section_id\">";
			$html_row .= $rel_locator_obj->section_id;
			$html_row .= "</div>";
			$html_row .= "</td>";

			
			# TAG ID
			$html_row .= "<td>";
			
			# dump($rel_locator_obj, ' diffusion_obj');
			# DEDALO_LIB_BASE_URL + '/main/?m='+target_modo+'&t='+tipo+'&parent='+parent+'&top_tipo='+page_globals.top_tipo+'&top_id='+page_globals.top_id ;
			# <div class="icon_bs tool_indexation_icon link" data-tipo="rsc36" data-parent="63" data-lang="lg-spa" data-tab_id="img_lang_rsc36_63" data-context_name="component_text_area" title="Abrir Herramienta" onclick="tool_common.open_tool_indexation(this)"></div>
			$url = DEDALO_LIB_BASE_URL . "/main/?m=tool_indexation&t={$diffusion_obj->tipo}&section_tipo={$section_tipo}&parent={$parent}&top_tipo={$rel_locator_obj->section_top_tipo}&top_id={$rel_locator_obj->section_top_id}&tag_id={$rel_locator_obj->tag_id}";
			$html_row .= "<div class=\"tag_id\" data-parent=\"$parent\" data-section_tipo =\"$section_tipo\" data-tipo=\"$diffusion_obj->tipo\" onclick=\"window.open('$url')\" title=\"".label::get_label('ir_al_fragmento')."\">";
			
			$html_row .= $rel_locator_obj->tag_id;
			$html_row .= "</div>";
			$html_row .= "</td>";

			
			# FRAGMENT			
			$html_row .= "<td>";
			$html_row .= TR::limpiezaFragmentoEnListados($diffusion_obj->columns['fragment'],160);
			$html_row .= "</td>";

		
			# INFO 
			$html_row .= "<td>";
			/**/
			if( !isset($diffusion_obj->columns['related']) ) $diffusion_obj->columns['related'] = null;
			$related = $diffusion_obj->columns['related'];
			switch ($related) {
				
				# COMPONENT_AV
				case 'component_av':
					$tc_in 		 = $diffusion_obj->columns['tc_in'];		#dump($diffusion_obj->columns['tc_in']," ");
					$tc_out 	 = $diffusion_obj->columns['tc_out'];
					$duracion_tc = $diffusion_obj->columns['duracion_tc'];

					$html_row .= $tc_in .' - '. $tc_out;
					$html_row .= ' '.label::get_label('total').': '. $duracion_tc;

					# Download fragment
	                if( !empty($duracion_tc) && $duracion_tc!='00:00:00') {
	                   
						$quality 	= DEDALO_AV_QUALITY_DEFAULT;
						$video_id 	= $diffusion_obj->columns['video_id'];

						if(SHOW_DEBUG) {
							#dump($diffusion_obj, ' $diffusion_obj');
						}
						

						# DOWNLOAD BUTTON NORMAL
	                    $html_row .= " <div class=\"icon_bs link av_download_icon\"
				    	data-video_id=\"$video_id\" data-quality=\"$quality\" data-tc_in=\"$tc_in\" data-tc_out=\"$tc_out\" data-watermark=\"0\" data-tag_id=\"$rel_locator_obj->tag_id\"
				    	data-parent=\"$parent\" data-tipo=\"$diffusion_obj->tipo\" data-top_id=\"$top_id\" data-top_tipo=\"$top_tipo\"
				    	onclick=\"tool_av_versions.donwload_fragment(this)\"
				    	></div>";

				    	# DOWNLOAD BUTTON WATERMARK
				    	if(file_exists(DEDALO_AV_WATERMARK_FILE)) {
				    	$html_row .= " <div class=\"icon_bs link av_download_icon_watermark\"
				    	data-video_id=\"$video_id\" data-quality=\"$quality\" data-tc_in=\"$tc_in\" data-tc_out=\"$tc_out\" data-watermark=\"1\" data-tag_id=\"$rel_locator_obj->tag_id\"
				    	data-parent=\"$parent\" data-section_tipo =\"$section_tipo\" data-tipo=\"$diffusion_obj->tipo\" data-top_id=\"$top_id\" data-top_tipo=\"$top_tipo\"
				    	onclick=\"tool_av_versions.donwload_fragment(this)\"
				    	></div>";
				    	}
	                }
					break;
				
				# COMPONENT_IMAGE
				case 'component_image':

					break;

				# COMPONENT_GEOLOCATION
				case 'component_geolocation':
					
					break;
				default:
					# code...
					break;
			}
			

			$html_row .= "</td>";
			



		$html_row .= "</tr>";
	}
	$html_row .= "</table>";



	$html_row .= "</td>";


	$html_row .= "</tr>";

	#echo $html_row ;
?>