<?php

	$html_head = '';

	$html_head .= "<tr class=\"tr_head\">";


	# INFO	
	for ($i=0; $i < count($ar_diffusion_obj_head) ; $i++) {

		$current_diffusion_obj = $ar_diffusion_obj_head[$i];
			#dump($current_diffusion_obj,'current_diffusion_obj');

		# VARS
		$label 	= $current_diffusion_obj->label;
		$valor 	= $current_diffusion_obj->columns['valor'];
			

		$current_css_class = '';
		#if($i==0)
		#$current_css_class = "class='head_first_column'";

		$html_head .= "<td $current_css_class >";
		
		$html_head .= "<div class=\"head_row_wrap\">";
		
			# LABEL : Excluimos el label del primer elemento, generalmente la foto identificativa (sólo nos interesa el contenido, no el label de la misma)
			if($i>0) {
				$html_head .= "<div class=\"head_row_label\">";
				$html_head .= "<h5>$label</h5>";
				$html_head .= "</div>";
			}
			

			# CONTENT
			$html_head .= "<div class=\"head_row_content\">";

				# VALOR : Si el valor recibido es único (no es un compuesto de varios registros) se formatea para unificar la lectura
				if(!is_array($valor)) {
					$valor = array( $current_diffusion_obj->id = array($current_diffusion_obj->tipo => $valor ) );
				}
				#dump($valor);

				# VALOR IS ARRAY
				if (is_array($valor)) {

					# FORMATO DEL ARRAY RECIBIDO
					# [valor] => Array
		            #    (
		            #        [58] => Array
		            #            (
		            #                [dd72] => Javier
		            #                [dd77] => Gómez López
		            #            )
		            #        [61] => Array
		            #            (
		            #                [dd72] => José
		            #                [dd77] => Perez Ramírez
		            #            )
		            #    )
					foreach ($valor as $section_id => $ar_section_id) {
					
						foreach ($ar_section_id as $component_tipo => $current_valor) {

							# SWITCH component_modelo_name
							$component_modelo_name = RecordObj_dd::get_modelo_name_by_tipo($component_tipo,true);
								#dump($component_modelo_name,'$component_modelo_name '.$current_valor);
							switch( $component_modelo_name ) {

								# IMG
								case 'component_image':
									$component_image = component_common::get_instance('component_image',$component_tipo,$section_id,'list');
									$html_head .= $component_image->get_html();
									#$img_url 	= DEDALO_IMAGE_FILE_URL . "?m=image&SID=$current_valor&w=102&h=57&fx=crop";
									#$html_head .= "<img src=\"$img_url\" class=\"index_ts_thumb\" />";
									break;

								# AV
								case 'component_av':
									$img_url 	= DEDALO_IMAGE_FILE_URL . "?m=posterframe&SID=$current_valor&w=102&h=57&fx=crop";
									$html_head .= "<img src=\"$img_url\" class=\"index_ts_thumb\" />";
									break;

								default:
									$html_head .= $current_valor;
									# Separador
									$html_head .= ' ';
									break;
							}

						}#end foreach ($ar_section_id as $component_tipo => $current_valor)

						# Foto Identificativa : sólo nos interesa el primer registro
						if($i==0) break;

						# Separador
						$html_head .= '<br>';

					}#end foreach ($valor as $section_id => $ar_section_id)

				# VALOR IS STRING
				}else{
					
					$html_head .= $valor;
				}

			$html_head .= "</div>"; #end head_row_content


		$html_head .= "</div>";#end head_row_wrap
		

		$html_head .= "</td>";
		
	}
	

	$html_head .= "</tr>";

	#echo $html_head ;
?>