<?php
	
	# VISUALIZADOR HTML
	$html_content = '';

	
	$html_content  = '<div class="css_wrap_rows_paginator text_unselectable">';
					
		$html_content  .= '<div class="css_rows_paginator_content">';
			
			# LINKS
			$html_content  .= '<div class="css_rows_paginator_div_links">';

				#  To first page <<					
				if($page_number>1) {
					$html_content  .= '<div class="icon_bs paginator_first_icon link" onclick="search.load_paginated_rows(this,'.(int)$first_page_offset.')"></div>';
				}else{
					$html_content  .= '<div class="icon_bs paginator_first_icon paginator_desactive"></div>';
				}
				
				#  To previous page <
				if($prev_page_offset>=0) {
					$html_content  .= '<div class="icon_bs paginator_prev_icon link" onclick="search.load_paginated_rows(this,'.(int)$prev_page_offset.')"></div>';
				}else{
					$html_content  .= '<div class="icon_bs paginator_prev_icon paginator_desactive"></div>';
				}

				#  To next page >
				if($next_page_offset<$total_rows) {
					$html_content  .= '<div class="icon_bs paginator_next_icon link" onclick="search.load_paginated_rows(this,'.(int)$next_page_offset.')"></div>';
				}else{
					$html_content  .= '<div class="icon_bs paginator_next_icon paginator_desactive"></div>';
				}
			
				#  To last page >>
				if($page_number<$total_pages) {					
					$html_content  .= '<div class="icon_bs paginator_last_icon link" onclick="search.load_paginated_rows(this,'.(int)$last_page_offset.')"></div>';
				}else{
					$html_content  .= '<div class="icon_bs paginator_last_icon paginator_desactive"></div>';
				}		
			
			$html_content  .= '</div>';


			# INFO
			$html_content  .= '<div class="css_rows_paginator_info">Page '.$page_number.' of '.$total_pages;
			if($modo==="list") {
				$html_content  .= '. Displayed records from '.$page_row_begin.' to '.$page_row_end.' of '.$total_rows;
				$html_content  .= '. '.label::get_label('go_to_page').' ';
			}
			
			if($modo==="edit") {
				$html_content  .= '. '.label::get_label('go_to_record').' ';
			}
				$html_content  .= '<input id="go_to_page" placeholder="'.$page_number.'" onkeyUp="search.go_to_page(this, event, '.(int)$total_pages.', '.(int)$item_per_page.')">';
				
			$html_content  .= '</div>';
			

		#}#end if ($total_rows>0)			
		$html_content  .= '</div>';// end <!-- /css_rows_paginator_content -->
	
	$html_content .= '</div>';//end <!-- /css_wrap_rows_paginator -->
	
	
	# PRINT HTML
	print $html_content;
	

?>