<?php 
#dump($initial_media_path, '$initial_media_path');die();

# SOURCE
switch ($m) {

	case 'image':
		# ImageObj
		include(DEDALO_CORE_PATH . '/media_engine/class.ImageObj.php');
		$image_id 		= $SID;
		$ImageObj 		= new ImageObj($image_id, $quality, $aditional_path, $initial_media_path, $external_source);
		$source 		= $ImageObj->get_local_full_path();
		$file_exists 	= $ImageObj->get_file_exists();
	
		if (!$file_exists) {
			#return null;#exit();
			$fx = 'crop';
			$source = DEDALO_CORE_PATH . '/themes/default/0.jpg';
		}


		# Thumb obj
		$thumb = new Thumb($source);
		break;

	case 'posterframe':
		
		# PosterFrameObj
		include(DEDALO_CORE_PATH . '/media_engine/class.PosterFrameObj.php');
		$reel_id 			= $SID;	
		$PosterFrameObj		= new PosterFrameObj($reel_id);
		$source 			= $PosterFrameObj->get_local_full_path();
			#dump(file_exists($source),"source $source");

		if (!file_exists($source)) {
			$fx = 'crop';
			$source = DEDALO_CORE_PATH . '/themes/default/0.jpg';
		}

		# Thumb obj
		$thumb = new Thumb($source);
		break;

	case 'free':
		$source = DEDALO_MEDIA_BASE_PATH .'/'. $SID;
		#dump($source, ' source ++ '.to_string());
		# Thumb obj
		$thumb = new Thumb($source);
		break;
	
	default:
		throw new Exception("Error Processing Request. Mode $m is not valid!", 1);		
		break;
}


# FX 
switch ($fx) {

	# CROP
	case 'crop':
		# position
		if(empty($p)) $p = 'center';			
		$thumb->crop($cwidth=$w, $cheight=$h, $pos=$p);
		break;

	# RESIZE
		case 'resize':
		# prop width/height
		if(empty($prop) || strlen($prop)<5) $prop = 'width'; 
		# value
		if($prop=='width') {
			$value = $w;
		}else{
			$value = $h;
		}
		$thumb->resize($value,$prop);
		break;

	# RESIZE WITH LIMITS (DEFAULT)
	default:
		$thumb->resizeWithLimits($maxWidht=$w,$maxHeight=$h) ;
		break;
}	
	
	


# HEADERS
header("Cache-Control: private, max-age=10800, pre-check=10800");
header("Pragma: private");
header("Expires: " . date(DATE_RFC822,strtotime(" 120 day")));
/*
header("Pragma-directive: no-cache");
header("Cache-directive: no-cache");
header("Cache-control: no-cache");
header("Pragma: no-cache");
header("Expires: 0");
*/
# show header for jpg
header('Content-Type: image/jpeg');

# show created image raw code without save the file
$thumb->show();

exit();
?>