<?php

	# VISUALIZADOR HTML	
	$html ='';	

	$html .= "<ul class=\"widget_descriptors\">";

	#
	# HEADER
	#$html .= "<li class=\"tab_title\">";	
	#$html .= "  <div class=\"label_second header\">".label::get_label('terminos')." : $total_terms / $total_index</div>";
	#$html .= "</li>";


	#
	# ROWS	


	#
	# TC
		$html .= "<li class=\"\">";
		$html .= "<div class=\"label_first\">TC :</div>";
		$html .= "<div class=\"label_second\">".$total_tc."</div>";

		if (!empty($ar_tc_wrong)) {
			#$html .= "<li class=\"\">";
			$html .= "<div class=\"label_second\">";
			$html .= "<span class=\"warning\">".label::get_label('etiqueta_revisar').":";
			foreach ($ar_tc_wrong as $current_tc) {
				$html .= " $current_tc<br>";
			}
			$html .= "</span></div>";
			
		}
		$html .= "</li>";


	#
	# INDEX
		$html .= "<li class=\"\">";
		$html .= "<div class=\"label_first\">INDEX :</div>";
		$html .= "<div class=\"label_second\">".$total_index."</div>";
		

		if ($total_missing_tags>0 || $total_to_review_tags>0) {
		
			#$html .= "<li class=\"\">";
			$html .= "<div class=\"label_second\">";
			if ($total_missing_tags>0) {
				$html .= "<span class=\"error\">".label::get_label('etiquetas_perdidas').": $total_missing_tags</span><br>";
			}
			if ($total_to_review_tags>0) {
				$html .= "<span class=\"warning\">".label::get_label('etiqueta_revisar').": $total_to_review_tags</span><br>";
			}	
			$html .= "</div>";
			#$html .= "</li>";
		}

		$html .= "</li>";	

	#
	# STRUCT
		$html .= "<li class=\"\">";
		$html .= "<div class=\"label_first\">STRUCT :</div>";
		$html .= "<div class=\"label_second\">".$total_struct."</div>";
		


		if ($struct_total_missing_tags>0 || $struct_total_to_review_tags>0) {
		
			#$html .= "<li class=\"\">";
			$html .= "<div class=\"label_second\">";
			if ($struct_total_missing_tags>0) {
				$html .= "<span class=\"error\">".label::get_label('etiquetas_perdidas').": $struct_total_missing_tags</span><br>";
			}
			if ($struct_total_to_review_tags>0) {
				$html .= "	<span class=\"warning\">".label::get_label('etiqueta_revisar').": $struct_total_to_review_tags</span><br>";
			}	
			$html .= "</div>";
			#$html .= "</li>";
		}
		$html .= "</li>";

	#
	# NOTES

		if ($total_private_notes>0 || $total_public_notes>0) {
			$html .= "<li>";
			if ($total_private_notes>0) {
						$html .= "<div class=\"label_first\">Work NOTES :</div>";
						$html .= "<div class=\"label_second\">".$total_private_notes."</div>";
						
			}
			if ($total_public_notes>0) {
				
						$html .= "<div class=\"label_first\">Public NOTES :</div>";
						$html .= "<div class=\"label_second\">".$total_public_notes."</div>";
			}
			$html .= "</li>";
		}


	#
	# TOTALS CHARS
		$html .= "<li>";
		$html .= "<div class=\"label_first\">CHARS :</div>";
		$html .= "<div class=\"label_second\">".$total_chars."</div>";
		$html .= "<div class=\"label_first\">NO SPACES:</div>";
		$html .= "<div class=\"label_second\">".$total_chars_no_spaces."</div>";			
		$html .= "</li>";

		if(SHOW_DEBUG===true) {		
		$html .= "<li class=\"\">";
		$html .= "<div class=\"label_first notes\">CHARS REAL:</div>";
		$html .= "<div class=\"label_second notes\">".$total_real_chars."</div>";			
		$html .= "</li>";
		}

	$html .= "</ul>";


	print $html;

?>