<?php

	# JS Init 
	$html_content = '';
	$html_content .= '<script>';
	# Init component
	$init_options = new stdClass();
		$init_options->relation_list_name 	= $relation_list_name;
		$init_options->modo 				= $modo;
		$init_options->tipo 				= $tipo;
		$init_options->section_tipo 		= $section_tipo;
		$init_options->section_id 			= $section_id;
	$html_content .= 'relation_list.init('.json_encode($init_options).');';

	$html_content .= '</script>';

	# PRINT HTML
	echo $html_content;
	
?>