<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title><?php echo $page_title ?></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="shortcut icon" href="<?php echo DEDALO_ROOT_WEB ?>/favicon.ico" />
<?php echo $css_link_code ?>
<?php 
$page_globals = new stdClass();
	# version
	$page_globals->dedalo_version 			= DEDALO_VERSION;
	# lang
	$page_globals->dedalo_application_lang 	= DEDALO_APPLICATION_LANG;
	$page_globals->dedalo_data_lang 		= DEDALO_DATA_LANG;
	$page_globals->dedalo_data_nolan 		= DEDALO_DATA_NOLAN;

	$page_globals->section_tipo 			= defined('SECTION_TIPO') ? SECTION_TIPO : null;
	# modo
	$page_globals->modo 					= $modo;
	# user_id
	$page_globals->user_id 					= (isset($user_id)) ? $user_id : null;
?>
<script>
const page_globals=<?php echo SHOW_DEBUG===true ? json_encode($page_globals, JSON_PRETTY_PRINT) : json_encode($page_globals) ?>;
setTimeout(function(){
	window.location.reload(true);
},2000)
</script><?php echo $js_link_code ?>
</head>

<body>
	<div id="html_page_wrap">

		<?php
		# PAGE HEADER HTML
			#print $html_header;
		
		# CONTENT HTML
			echo '<!-- CONTENT HTML -->';
			echo "\n<div id=\"content_maintenance\" class=\"content_html\">";
			echo "	<h1 class=\"main_font_light\"> ".label::get_label('sitio_en_mantenimiento')." </h1>";
			echo "\n</div><!-- /content_html -->\n\n";	
		?>

	</div><!-- /html_page_wrap -->
</body>
</html>